apache/nuttx-apps

examples/noteprintf/noteprintf_main.c
system/sched_note/note_main.c
system/trace/trace.c
system/trace/trace.h
system/trace/trace_dump.c

sched/note: add support of trace section mark
The implementation of this feature is based on android systrace:
https://source.android.com/devices/tech/debug/ftrace
Application developers are more concerned about the performance of
the specified application section,
added two APIs to implement performance measurement:
```
void sched_note_begin(FAR const char *str);
void sched_note_end(FAR const char *str);
or
SCHED_NOTE_BEGIN();  /* defined to sched_note_begin(__FUNCTION__) */
SCHED_NOTE_END();    /* defined to sched_note_end(__FUNCTION__) */
```
Depends on: https://github.com/apache/incubator-nuttx/pull/5915
https://source.android.com/devices/tech/debug/ftrace
https://github.com/catapult-project/catapult/
test code:
```
void ccc(void)
{ …
```

sched/note: add support of trace section mark 

---

netutils/ftpd/ftpd.c
netutils/ftpd/ftpd.h

Some FTP clients (like FileZilla) try to check if directory exists with CWD command. If CWD fails then MKD command is issued. In current implementation if CWD fails the server terminates the connection.
Do not terminate connection if CWD fails and just notify client considering this as a normal operation.
FTPD users
Tested with custom board based on SAME70 + FileZilla directory upload

netutils/ftpd: Do not terminate connection if CWD fails

---

netutils/usrsock_rpmsg/Kconfig

since all rpmsg driver need the extension api exposed by rptun driver
follow up nuttx side change: https://github.com/apache/incubator-nuttx/pull/5982
Minor
Pass CI

usrsock/rpmsg: Change the dependence from OPENAMP to RPTUN

---

system/sched_note/note_main.c
system/trace/trace_dump.c

system/note: correct unflatten format
Fix endian issue reported by @pkarashchenko :
https://github.com/apache/incubator-nuttx-apps/pull/1114#discussion_r842466352
sched note trace test

system/note: correct unflatten format

---

system/nxplayer/nxplayer_main.c

According to the help text, the balance command should display the current balance value. This patch adjusts
the code accordingly.
Bugfix I hope.

According to the help text, the balance command without value

---

examples/scd41/Kconfig
examples/scd41/Make.defs
examples/scd41/Makefile
examples/scd41/scd41_main.c

Add new example for scd41 CO2 sensor application.
This is an example application of https://github.com/apache/incubator-nuttx/pull/6030.
None
Build test and work on Spresense board.

examples/scd41: Add new example for scd41 CO2 sensor

---

nshlib/nsh_command.c
nshlib/nsh_fscmds.c

nshlib/nsh_fscmds.c: Make losetup command take optional sector size
losetup command
tested with littlefs, sim/macOS, https://github.com/apache/incubator-nuttx/pull/6023

nshlib/nsh_fscmds.c: Make losetup command take optional sector size

---

include/wireless/wapi.h

Correct the alg field type of the wpa_wconfig_s structure, which may cause an unaligned access exception.
None
None

wireless/wapi: fix wapi wpa_wconfig_s alg data type error

---

netutils/ping/icmp_ping.c
netutils/ping/icmpv6_ping.c

https://joekuan.wordpress.com/2017/05/30/behaviour-of-identifier-field-in-icmp-ping-as-udp-between-linux-and-osx/
https://lwn.net/Articles/443051/
https: //github.com/apache/incubator-nuttx-apps/blob/master/netutils/ping/icmp_ping.c#L298
ping on sim

netutils/ping: skip the id check

---

wireless/gs2200m/gs2200m_main.c

- I noticed that wget causes ASSERT in gs2200m_main.c recently.
- Finally, I found that it sends a wrong ack message in
recvfrom_request() when the socket is closed passively
- This commit fixes this issue.
- gs2200m only

wireless: gs2200m: Fix recvfrom_request() in gs2200m_main.c

---

Application.mk

Makefile/Application: correct libgcc PATH
if "--print-libgcc-file-name" unable to find the correct libgcc PATH
then go ahead and try "--print-file-name"
N/A
ToolChain:
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm
./tools/configure.sh lm3s6965-ek:qemu-flat
CONFIG_ARMV7M_TOOLCHAIN_CLANGL=y

Makefile/Application: correct libgcc PATH

---

testing/ostest/Kconfig
testing/ostest/fpu.c

testing/ostest: remove CONFIG_TESTING_OSTEST_FPUSIZE
fptest should not need to care about the size of FPU
fpu test
./tools/configure.sh sabre-6quad/smp
ostest

testing/ostest: remove CONFIG_TESTING_OSTEST_FPUSIZE

---

system/i2c/i2c_reset.c

Close fd before return.
i2ccmd_reset
CI

system/i2c: Fix fd leak in i2ccmd_reset

---

nshlib/nsh_fileapps.c

Now that the environ pointer is a list of pointers-to-string, it can be
passed to the standard posix_spawn function as-is.
icicle:nsh & icicle:knsh

nshlib/nsh_fileapps.c: Pass global environ instead of NULL for posix_spawnp

---

system/ping/ping.c
system/ping6/ping6.c

Guard against division by zero when calculating the RTT, otherwise system could crash with the delay is 0.
ping
esp32-devkitc:netnsh pinging the router.

system/ping: Guard against division by zero when calculating the RTT.

---

interpreters/ficl/src/nuttx.h

Add double include guard to nuttx.h
None
Pass CI

interpreters/ficl: add double include guard to nuttx.h

---

Application.mk

lxx must be before lmm at least, because new uses malloc().
Fixes C++ library linkage with CONFIG_BUILD_KERNEL
icicle:knsh

import/Make.defs: Fix C++ library linkage with CONFIG_BUILD_KERNEL

---

audioutils/.gitignore
audioutils/Make.defs
audioutils/Makefile
audioutils/mml_parser/Kconfig
audioutils/mml_parser/Make.defs
audioutils/mml_parser/Makefile
audioutils/mml_parser/README.md
audioutils/mml_parser/mml_parser.c
examples/mml_parser/Kconfig
examples/mml_parser/Make.defs
examples/mml_parser/Makefile
examples/mml_parser/mml_parser_main.c
include/audioutils/mml_parser.h

Add a new utility library as music macro language parser.
Can parse MML.
An example for this library is added.

audioutils/mml_parser: Add mml_parser library

---

system/sched_note/note_main.c
system/trace/trace.c

1. trace: format the usage output
before:
```
Usage: trace <subcommand>...
Subcommand:
start [-c][<duration>]          : Start task tracing
stop                            : Stop task tracing
dump [-a][-c][<filename>]           : Output the trace result
[-a] <Android SysTrace>
mode [{+|-}{o|w|s|a|i|d}...]        : Set task trace options
switch [+|-] : Configure switch trace filter
syscall [{+|-}<syscallname>...] : Configure syscall trace filter
irq [{+|-}<irqnum>...]          : Configure IRQ trace filter
print [+|-] : Configure dump tnsh>
```
after:
```
Usage: trace <subcommand>...
Subcommand:
start [-c][<duration>]          : Start task tracing
stop                            : Stop task tracing
dump [-a][-c][<filename>]       : Output the trace result
[-a] <Android SysTrace>
mode …
```

system/trace: correct arg index if command is alreay set

---

system/libuv/Makefile

test-idna.c will include idna.c and then cause multiple definition.
libuv test suite only
custom board

libuv: Don't add idna.c to CSRCS if test enabled

---

interpreters/wamr/Kconfig

interpreters/wamr/Kconfig: Add an option to enable wasi libc

---

interpreters/wamr/Kconfig

aot requires executable memory. make it explicit in Kconfig.
tested on esp32

interpreters/wamr/Kconfig: enable text heap when necessary

---

include/graphics/nxwm/nxwmconfig.hxx

Follow up to kernel side https://github.com/apache/incubator-nuttx/pull/6197

nxwm: Fix warning about on_exit() dependency

---

netutils/dhcpc/Kconfig
netutils/dhcpc/dhcpc.c

netutils/dhcpc: Change the timeout unit to milliseconds
None
bl602evb:wifi

netutils/dhcpc: Change the timeout unit to milliseconds

---

interpreters/wamr/Kconfig
interpreters/wamr/Makefile

This allows to use a commit sha1 for CONFIG_INTERPRETERS_WAMR_VERSION.
Note: the existing configs with specific wamr version
need to be updated.
Tested with:
CONFIG_INTERPRETERS_WAMR_VERSION=main
CONFIG_INTERPRETERS_WAMR_VERSION=WAMR-04-15-2021
CONFIG_INTERPRETERS_WAMR_VERSION=3168ba8dcf20d9d8539d75c637420f5fd8682335

interpreters/wamr: Remove WAMR_VERSION_STUB and always use actual tags

---

include/netutils/webclient.h

Include stdint.h for uint16_t explicitly.
This was necessary when I was trying to build this natively
on Ubuntu.  It seems some other headers happen to pull
the uint16_t definition by luck on NuttX and macOS.

webclient.h: Avoid relying on indirect inclusion

---

system/libuv/0001-libuv-port-for-nuttx.patch
system/libuv/Makefile

fix the linker error when compile libuv test
Pass CI

system/libuv: Skip compile strscpy.c when CONFIG_LIBUV_UTILS_TEST enable

---

canutils/slcan/slcan.c
netutils/ftpd/ftpd.c

follow nuttx kernel side change: https://github.com/apache/incubator-nuttx/pull/6357
Minor
Pass CI

Remove "| O_BINARY" or " |= O_BINARY" since O_BINARY is 0 now

---

examples/elf/tests/helloxx/Makefile

Should guard against these being included if exception support isn't there. Fixes https://github.com/apache/incubator-nuttx-apps/issues/1190
https://github.com/apache/incubator-nuttx-apps/issues/1190 these two require exception support
Broken example
Works on my machine (tm)

Address #1190 -- EXAMPLES_ELF_CXX broken w/o exceptions

---

include/wireless/wapi.h

Similar to #1134: This fixes the sta_mode field data type which causes:
```c
src/wapi.c: In function 'wapi_save_config_cmd':
src/wapi.c:866:38: warning: passing argument 3 of 'wapi_get_mode' from incompatible pointer type [-Wincompatible-pointer-types]
866 |   ret = wapi_get_mode(sock, argv[0], &conf.sta_mode);
|                                      ^~~~~~~~~~~~~~
|                                      |
|                                      uint8_t * {aka unsigned char *}
In file included from src/wapi.c:55:
../apps/include/wireless/wapi.h:508:41: note: expected 'enum wapi_mode_e *' but argument is of type 'uint8_t *' {aka 'unsigned char *'}
508 |                   FAR enum wapi_mode_e *mode);
|                       ~~~~~~~~~~~~~~~~~~^~~~
```
Make `wireless/wapi` compile without …

wireless/wapi: fix wapi wpa_wconfig_s sta_mode data type error

---

testing/irtest/cmd.cxx

Fix issue of failure to open multiple IR devices.
`irtest`

testing/irtest: Fix issue of failure to open multiple IR devices

---

include/netutils/webclient.h
netutils/webclient/webclient.c

My primary motivation at this point is to use it for basic proxy auth.
(specify "Proxy-Authorization" header)
But there can be other use cases for proxy-specific extra headers.
If/when we want to support other non-trivial auth methods, probably
a callback-based mechanism will be necessary. But at this point,
this serves my purpose well.
tested with my app + squid

webclient: Allow users to specify extra headers for proxy

---

netutils/webclient/webclient.c

webclient_abort: Fix a resource leak for the tunneling case
tested with my app on macOS with LSan.

webclient_abort: Fix a resource leak for the tunneling case

---

.github/workflows/build.yml

Follow the nuttx side change: https://github.com/apache/incubator-nuttx/pull/6509
Fix the ci broken
Pass CI

.github/workflows: Add nuttx/source to the safe directory 

---

nshlib/nsh_ddcmd.c

Improve calculation accuracy.
None
Daily test

nshlib/nsh_ddcmd: calculate time difference with microsecond precision

---

system/hostname/hostname_main.c

Add an option to read the hostname from a file (eg: in `/etc/init.d/rcS`). Add a check that the hostname is non-empty.
Makes it possible to set hostname from a file without `NSH_CMDPARMS` enabled (eg: "hostname \`cat /etc/hostname\`"). Ensures that hostname must be non-blank.
```
nsh> hostname -F /data/hostname
nsh> hostname -F /tmp/missing
ERROR: Failed to open '/tmp/missing': No such file or directory
nsh> hostname ""
ERROR: The specified hostname is invalid
nsh> echo > /tmp/newline
nsh> hostname -F /tmp/newline
ERROR: The specified hostname is invalid
nsh> echo -n > /tmp/empty
nsh> hostname -F /tmp/empty
ERROR: The specified hostname is invalid
nsh> 
```

system/hostname: Add an option to read the hostname from a file

---

testing/ostest/ostest_main.c

I noticed that some prints in ostest are incorrect.  
They do not reflect the actual operation to be carried-out.
This PR fixes these prints.
N/A
N/A

ostest: Fixed prints in setenv test.

---

nshlib/Kconfig

Allow disabling nslookup even when not using dnsclient.
#151 touched cmd_nslookup, replacing `gethostbyname()` with `getaddrinfo()` for IPv6 compatibility. 
It also touched the macro conditions, effectively dropping the dependency on activated NETDB_DNSCLIENT. 
`nshlib/Kconfig` was not updated accordingly. See 8da81578b0e5822719ca764416ebb6a74e568fa4
Now we're forced to use nslookup with or without dnsclient. That pulls some functions into the build, according to System.map 
(derived from `diff -NarU0 <(cut -d' ' -f3 ../build-10.3.0/nucleo-h743zi2/System.map) <(cut -d' ' -f3 System.map)`
and Puncover utility:
```
cmd_nslookup	160
getaddrinfo	496
getnameinfo	368
lib_numeric_address	228
getservbyname_r	180
lib_localhost	168
getservbyport_r	164
gethostentbyname_r	86
```
and possibly others. …

nshlib/netcmds: Decouple nslookup() from NETDB_DNSCLIENT

---

nshlib/nsh_syscmds.c

nsh_syscmds.c:352:40: error: passing argument 2 of 'boardctl' makes integer from pointer without a cast [-Werror=int-conversion]
352 |   ret = boardctl(BOARDIOC_RESET_CAUSE, &cause);
|                                        ^~~~~~
|                                        |
|                                        struct boardioc_reset_cause_s *

apps:fix reset cause warning

---

nshlib/nsh_syscmds.c

can use ouput string set a env to argv
in a nsh script:
```set flag "cause:0x9,flag:0x4"
set rel `resetcause`
if [ $flag == $rel ]
then 
echo "do something"
fi
```
but,if `resetcause` output have `space`,  `if [ $flag == $rel ]` will parse error

cmd_reset_cause:remove extra space in text ouput

---

nshlib/nsh_proccmds.c

Fixes the output of the `ps` command.
Related to [this](https://github.com/apache/incubator-nuttx/issues/6641) issue and [this](https://github.com/apache/incubator-nuttx/pull/6658) PR.
`ps` command produces correct output.
Tested on simulator for `CONFIG_MM_BACKTRACE` both enabled and disabled.

Fixed heap information output in nsh ps command.

---

nshlib/Kconfig
nshlib/nsh_script.c

if rcS use set +x or other，rcS can output other path
nothing
CI

nshlib:support nsh can redirect

---

testing/uclibcxx_test/Makefile

Fix the warning
uclibcxx_test
Pass CI

Fix find: '/github/workspace/sources/nuttx/libs/libxx/uClibc++/tests' No such file or directory

---

testing/sensortest/sensortest.c

update sensortest tool:
1.update prefix of sensor event structure to sensor_xxx.
2.remove activate cmd because of open will auto activate sensor.
N/A
Vela CI

testing/sensortest: update sensortest according enhance sensor driver

---

testing/sensortest/sensortest.c

testing/sensortest: fix compile break
fix compile break

testing/sensortest: fix compile break

---

nshlib/nsh_proccmds.c

nshlib/ps: update config MM_BACKTRACE to int type
memory debug function
Vela CI

nshlib/ps: update config MM_BACKTRACE to int type

---

system/popen/Kconfig
system/popen/popen.c

- This commit fixes to build with CONFIG_BUILD_KERNEL=y
- None
- Tested with sabre-6quad:knsh (not merged yet)

system: popen: Fix to build with CONFIG_BUILD_KERNEL=y

---

testing/sensortest/sensortest.c

testing/sensortest: fix cmd argument mismatch(follow new sensor driver)

testing/sensortest: fix cmd argument mismatch(follow new sensor driver)

---

system/cu/cu.h
system/cu/cu_main.c

cu: fix cu hang when meet ctrl + C
We can't do sem_wait in sigaction
hang backtrace:
[<0x2c5a6958>] arm_switchcontext+0xc/0x10
[<0x2c579eba>] nxsem_wait+0x6e/0xa8
[<0x3c9a8cb5>] pb_field_iter_find+0xffde8cb/0xd3635c15
[<0x2c58d164>] uart_tcdrain.constprop.0+0x10/0xf8
[<0x2c58d5c6>] uart_close+0x10e/0x180
[<0x2c579f38>] nxsem_wait_uninterruptible+0x44/0xb8
[<0x2c95f87a>] file_close+0x12/0x44
[<0x2c95e5a8>] close+0x80/0xb4
[<0x2c5c6396>] sigint+0x1a/0x28
[<0x2c57b1b0>] nxsig_deliver+0x54/0xb8
[<0x2c5a549a>] arm_sigdeliver+0x1a/0x44
[<0x2c579eb6>] nxsem_wait+0x6a/0xa8
[<0x2c579eb6>] nxsem_wait+0x6a/0xa8
[<0x2c579eb6>] nxsem_wait+0x6a/0xa8
[<0x2c58aa1a>] pm_lock+0x1a/0x28
[<0x2c58a656>] pm_stay+0xa/0x60
[<0x2c58bb14>] rptun_notify+0x4c/0x58
[<0x2c97b8fc>] virtqueue_kick+0x54/0x7c …

cu: fix cu hang when meet ctrl + C

---

fsutils/mkfatfs/configfat.c
fsutils/mkfatfs/mkfatfs.h
fsutils/mkfatfs/writefat.c

g_bootcodeblob was allocated in RAM, to be able to patch the offset logic.
This patch makes g_bootcodeblob a constant and patches the offset afterwards to save on ram usage
Saves 132 bytes on .data section and moves it to the .rodata section.
Tested on MR-CANHUBK3 formatting SD cards as FAT16/FAT32 and checking partition table

mkfats make g_bootcodeblob const to save on .data section usage

---

include/netutils/netlib.h
netutils/netlib/Makefile
netutils/netlib/netlib_setipv6dnsaddr.c
nshlib/nsh_netcmds.c

Signed-off-by: liyi <liyi25@xiaomi.com>
ifconfig support set IPv6 DNS server
ifconfig can be used to set IPv6 DNS server with the command format below:
ifconfig [dev_name] [ipv6_addr] gw [ipv6_gw] dns [ipv6_dns] inet6 
Testing cases has been done with nuttx sim:nsh program

ifconfig support set IPv6 DNS server

---

netutils/iperf/Kconfig

Fix description as iperf can run not only with Wi-Fi network interface
None
Pass CI

netutils/iperf: fix string for iperf test interface option

---

fsutils/mkfatfs/fat32.h

fsutils/mkfatfs: remove invalid header file
This patch is related to https://github.com/apache/incubator-nuttx/pull/6803
N/A
Local test.

fsutils/mkfatfs: remove invalid header file

---

testing/sensortest/sensortest.c

Device Paths for NuttX Sensors are now named `/dev/sensor/sensor_...` according to [drivers/sensors/sensor.c](https://github.com/apache/incubator-nuttx/blob/3fdd036ba6eee2ffd76cfba561ab1b044e3275e2/drivers/sensors/sensor.c#L49):
```c
#define DEVNAME_FMT        "/dev/sensor/sensor_%s%s%d"
```
`sensortest` fails to open any sensor because it's using the old Device Path:
```text
nsh> sensortest -n 1 baro0
Failed to open device:/dev/sensor/baro0, ret:No such file or directory
nsh> sensortest -n 1 sensor_baro0
The sensor node name:sensor_baro0 is invalid
nsh> ls /dev/sensor
/dev/sensor:
sensor_baro0
sensor_humi0
```
This patch updates the Device Path in `sensortest` so that it can open the sensor correctly.
Hi @Donny9 I hope this patch is correct? Thanks!
After applying the patch, `sensortest` …

testing/sensortest: Update device path

---

system/uorb/uORB/uORB.h
testing/sensortest/sensortest.c

driver/sensor: rename /dev/sensor -> /dev/uorb
because this directory contains all topics, not just sensors.
rename  directory for sensor device
Local test

driver/sensor: rename /dev/sensor -> /dev/uorb

---

interpreters/wamr/Kconfig

Add a new option to enable semaphore support, see : https://github.com/bytecodealliance/wasm-micro-runtime/pull/1345
New feature
Custom boards

wamr: Add a new option to enable semaphore support

---

include/netutils/telnetd.h
include/nshlib/nshlib.h
netutils/telnetd/Kconfig
netutils/telnetd/telnetd_daemon.c
nshlib/Kconfig
nshlib/nsh_telnetd.c
system/nsh/nsh_main.c
system/telnetd/Kconfig
system/telnetd/Make.defs
system/telnetd/Makefile
system/telnetd/telnetd.c

- This PR contains the following commits
- commit1: netutils: Make telnetd_daemon() in public
- This commit makes telnetd_daemon() in public so that we
can call it from applications.
- Also, adds new configs to support posix_spawnp()
- commit2: nshlib: Make nsh_telnetmain() in public
- This commit makes nsh_telnetmain() in public so that we can
call it from applications.
- Also, CONFIG_NSH_DISABLE_TELNETSTART is introduced so that
we can disable nsh_telnetstart()
- nsh with telnet daemon
- Tested with sabre-6quad:netnsh (will be updated later)

Modify telnetd

---

interpreters/wamr/Kconfig

Reserve some space in stack as guard to detect stack overflow, use stack base by default but may not safe enough.
See also : https://github.com/bytecodealliance/wasm-micro-runtime/pull/1368
New option
Custom board

wamr: Add a new option to custom stack guard size

---

examples/configdata/configdata_main.c
fsutils/mkgpt/mkgpt.c
system/zmodem/host/nuttx/crc16.h
system/zmodem/host/nuttx/crc32.h
system/zmodem/zm_proto.c
system/zmodem/zm_send.c
system/zmodem/zm_state.c
system/zmodem/zm_utils.c
testing/fstest/fstest_main.c
testing/nxffs/nxffs_main.c
testing/smart/smart_main.c

to avoid the conflict with the 3rd party library.
note: all major libc provider doesn't put crc8.h, crc16.h and crc32.h directly under include folder.
depends on https://github.com/apache/incubator-nuttx/pull/6840

zmodem: Move crc16.h and crc32.h from host to host/nuttx

---

netutils/dhcpd/dhcpd.c

CC:  dhcpd.c
In function 'dhcpd_openlistener',
inlined from 'dhcpd_run.part.0' at dhcpd.c:1513:20:
dhcpd.c:1425:3: error: 'strncpy' specified bound 16 equals destination size [-Werror=stringop-truncation]
1425 |   strncpy(req.ifr_name, interface, IFNAMSIZ);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Change-Id: I8f9dd8bfb7cc9d270f02ab11b4953aa2dec7cc8b
Minor change
CI

dhcpd: fix build warning

---

wireless/wapi/src/wapi.c
wireless/wapi/src/wireless.c

wireless/wapi: correct check of return value
1. correct check of return value
```
----------------------
* Name: ioctl
...
* Returned Value:
*   >=0 on success (positive non-zero values are cmd-specific)
*   -1 on failure with errno set properly:
```
2. country code length should contain LF
N/A
bcm43013

wireless/wapi: correct check of return value

---

interpreters/quickjs/Makefile

Use +make or $(MAKE) instead of make -C to pass jobserver
Signed-off-by: Peter Bee <bijunda1@xiaomi.com>

quickjs/Makefile: pass jobserver status to submake

---

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

usrsock: ioctl Remove bad copy operations
usrsock_server: Reduce unnecessary poll prepare
usrsock: fix usrsock close hang when net not ready

some usrsock_rpmsg issue fix

---

examples/foc/Kconfig

examples/foc/Kconfig: EXAMPLES_FOC_SETPOINT_ADC depends on ADC

examples/foc/Kconfig: EXAMPLES_FOC_SETPOINT_ADC depends on ADC

---

examples/rpmsgsocket/Kconfig

Signed-off-by: yintao <yintao@xiaomi.com>
fix wrong typo in examples/rpmsgsocket
none
vela ci passed

examples/rpmsgsocket: fix wrong typo

---

system/nxlooper/nxlooper_main.c
system/nxplayer/nxplayer_main.c
system/nxrecorder/nxrecorder_main.c

readline might return EOF, which causes coverity bug.

nxlooper nxplayer nxrecorder: fix coverity bug

---

netutils/usrsock_rpmsg/usrsock_rpmsg_client.c

Signed-off-by: weizihan <weizihan@xiaomi.com>
netutils/usrsock_rpmsg/usrsock_rpmsg_client.c
Fix the bug that didn't initialize structure
usrsock_rpmsg_client.c Calling memset to initialize pfd
passed vela CI

apps: Fix the bug that didn't initialize structure

---

netutils/webclient/webclient.c

Signed-off-by: weizihan <weizihan@xiaomi.com>
netutils/webclient/webclient.c
Fix the bug that setsockopt didn't check return value
webclient.c：Check retutn value will be more safe
Passed vela CI

apps: Fix the bug that setsockopt didn't check return value

---

nshlib/Kconfig

You can't disable dmesg if RAMLOG_SYSLOG disabled since `NSH_DISABLE_DMESG` depends on it.
dmesg only, minor
Custom build

nshlib: Disable dmesg if RAMLOG_SYSLOG disabled

---

include/industry/foc/float/foc_ident.h
industry/foc/float/foc_ident.c

1. change flux linkage identification from V/F openloop to I/F openloop to solve the problem of some motors fail to start on V/F openloop;
2. reset FOC ident routine state machine so that identification can be performed once more without restart FOC app;
flux linkage identification
Tested on custom FOC control board based on STM32F405RG

industry/foc foc_ident: improve flux linkage identification method

---

netutils/dhcpc/Kconfig
netutils/dhcpc/dhcpc.c
netutils/dhcpd/dhcpd.c

net/sockopt: move BINDTODEVICE to socket level
rename the UDP_BINDTODEVICE to SO_BINDTODEVICE to follow the linux
style to be compatible with non-UDP protocol binding requirements
Signed-off-by: chao.an [anchao@xiaomi.com](mailto:anchao@xiaomi.com)
Depends on: https://github.com/apache/incubator-nuttx/pull/6907
dhcpc renew
sim/tcpblaster

net/sockopt: move BINDTODEVICE to socket level

---

testing/getprime/getprime_main.c

- I noticed that getprime sometimes shows a wrong thread number
- None
- Tested with sabre-6quad:netnsh

testing: getprime: Fix the thread number info

---

examples/mld/mld_main.c
netutils/netlib/netlib_setdripv4addr.c
nshlib/nsh_routecmds.c

Signed-off-by: liyi <liyi25@xiaomi.com>
fix the use of addroute/delroute
addroute/delroute function's input parameter may be a structure sockadd_in(netlib_set_dripv4addr),
which has only 16B. But structure sockaddr_storage's size is larger than 16B. In fact, its size is 128B. 
So when you pass a structure sockadd_in and try to copy as a structure sockaddr_storage
it will overstep the buffer's bounary. It is the similar condition for IPv6's structure sockaddr_in6.
app's code must fit this change 
before this modification, the nuttx may crash with "stack buffer overflow", like blow
The fault error is caused by the wrong way to use addroute (netlib_set_dripv4addr)
after this, it can work well!

fix use of addroute/delroute

---

examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_mq.c
examples/foc/foc_parseargs.c
examples/foc/foc_thr.c
examples/foc/foc_thr.h

- examples/foc: print default values in the help message
- examples/foc: terminate the control thread if no work to do
- examples/foc: make sure that the queue is empty before start the control thread
steval-eth001v1/foc_f32

examples/foc: improvements

---

examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c
examples/foc/foc_thr.h

- examples/foc: add options to run only the sensor alignment routine or the motor identification routine
steval-eth001v1/foc_f32

examples/foc: add options to run routines only

---

boot/mcuboot/Makefile
crypto/libtomcrypt/Makefile
crypto/mbedtls/Makefile
examples/lvgldemo/Makefile
gpsutils/minmea/Makefile
graphics/lvgl/Makefile
interpreters/duktape/Makefile
interpreters/lua/Makefile
interpreters/quickjs/Makefile
interpreters/wamr/Makefile
interpreters/wasm3/Makefile
math/libtommath/Makefile
mlearning/cmsis/Makefile
mlearning/darknet/Makefile
mlearning/libnnablart/Makefile
netutils/cjson/Makefile
netutils/mqttc/Makefile
system/adb/Makefile
system/argtable3/Makefile
system/embedlog/Makefile
system/libuv/Makefile
testing/iozone/Makefile
testing/ltp/Makefile
testing/unity/Makefile
wireless/bluetooth/nimble/Makefile

Don't download tarballs if a local git repo found, to save time or avoid modify the makefile in local, make it easy to intergrate nuttx with customized third party software.
Refactor only
CI and local machine.

Don't download tarballs if a local git repo found

---

interpreters/wamr/Kconfig

Add an option to enable WAMR_BUILD_DEBUG_INTERP equivalent.
The corresponding WAMR PR: https://github.com/bytecodealliance/wasm-micro-runtime/pull/1426
Tested with sim/Linux/amd64 and esp32 devkit-c.
(with a few more patches)

interpreters/wamr/Kconfig: Add INTERPRETERS_WAMR_DEBUG_INTERP option

---

gpsutils/minmea/Makefile

minmea is not cover by CI and in current implementations,
the source files from downloaded tarball were put into root path in gpsutils/minmea instead of in `$(MINMEA_DIR)/$(MINMEA_UNPACKNAME)`,
and then:
```
mv: cannot stat 'minmea-db46128e73cee26d6a6eb0482dcba544ee1ea9f5': No such file or directory
```
minmea
Custom board

gpusutils/minmea: Fix build break by wrong unpack path

---

testing/mtd_config_fs/Kconfig
testing/mtd_config_fs/Make.defs
testing/mtd_config_fs/Makefile
testing/mtd_config_fs/README.md
testing/mtd_config_fs/mtd_config_fs_test_main.c

testcases for fail-safe MTD config data.
Fail-safe here means the new config data system is resilient to power loss.
Only on the fail-safe MTD config data.
Tested on Risc-v/Esp32c3

testing:add MTD Fail-safe config-data tests

---

examples/usrsocktest/usrsocktest_basic_daemon.c
examples/usrsocktest/usrsocktest_block_recv.c
examples/usrsocktest/usrsocktest_daemon.c
examples/usrsocktest/usrsocktest_noblock_recv.c
examples/usrsocktest/usrsocktest_wake_with_signal.c

1. examples/usrsocktest: add some delay to wait the daemon task ready
2. examples/usrsocktest: add USRSOCK_REQUEST_IOCTL support
The test model of usrsock ioctl() has changed after file socket layer implemented from vfs,
usrsock must implement the ioctl() hook to pass this test
3. examples/usrsocktest: fix build break
```
usrsocktest_wake_with_signal.c: In function ‘do_wake_test’:
usrsocktest_wake_with_signal.c:553:16: error: ‘USEC_PER_MSEC’ undeclared (first use in this function)
553 |   usleep(100 * USEC_PER_MSEC); /* Let worker thread proceed to blocking
|                ^~~~~~~~~~~~~
```
4. examples/usrsocktest: correct the check region of remote address
let us skip the sin_zero
5. examples/usrsocktest: correct return value check of dup2()
```
DUP(2) Linux Programmer's Manual
NAME …
```

net/usrsock: fix usrsocktest test case break

---

examples/ftpd/Kconfig
examples/ftpd/ftpd_main.c
include/netutils/ftpd.h
netutils/ftpd/ftpd.c

The ftpd was previously only working on the hard-coded port 21.
This commit allows the user to specify the desired port when the server is created.
ftpd can run on any port.
Tested within custom application on an STM32F427 board.  
Builds and runs as expected.

ftpd: server port made configurable.

---

netutils/dhcp6c/dhcp6c.c
netutils/dhcpd/dhcpd.c

netutils/dhcp: fix build warning/break of dhcp6c
```
dhcp6c.c:222:3: error: unknown type name ‘pthread_t’
222 |   pthread_t thread;
|   ^~~~~~~~~
dhcp6c.c: In function ‘dhcp6c_get_result’:
dhcp6c.c:415:7: warning: implicit declaration of function ‘netlib_prefix2ipv6netmask’ [-Wimplicit-function-declaration]
415 |       netlib_prefix2ipv6netmask(presult->pl, &presult->netmask);
|       ^~~~~~~~~~~~~~~~~~~~~~~~~
dhcp6c.c: In function ‘dhcp6c_parse_ia’:
dhcp6c.c:1046:30: warning: unused variable ‘pdhcp6c’ [-Wunused-variable]
1046 |   FAR struct dhcp6c_state_s *pdhcp6c = (FAR struct dhcp6c_state_s *)handle;
|                              ^~~~~~~
dhcp6c.c: In function ‘dhcp6c_precise_open’:
dhcp6c.c:1702:3: warning: missing braces around initializer [-Wmissing-braces]
1702 |   {
|   ^
...... …
```

netutils/dhcp: fix build warning/break of dhcp6c

---

testing/ostest/sighand.c

ostest: fix sighand_test report error
sighand_test: ERROR waiter task did not exit
reason:
sleep will be interrupt by signal
Signed-off-by: ligd <liguiding1@xiaomi.com>
ostest
sim:smp

ostest: fix sighand_test report error

---

wireless/gs2200m/gs2200m_main.c

- I noticed that the latest ifconfig command shows nothing
- Finally, I found that gs2200m_main.c needs to handle SIOCGIFFLAGS
- gs2200m only
- Tested with spresense:wifi
- NOTE: gs2200m driver needs to be updated as well

wireless: gs2200m: Add SIOCGIFFLAGS support to gs2200m_main.c

---

tools/README.md

Fix typo (Run Length Length -> Run Length Encoding) and reflow paragraph due to the changed length.
Improves documentation.
None.

tools/README.md: Fix typo and reflow paragraph

---

interpreters/quickjs/Kconfig
interpreters/quickjs/Makefile

Do not compile and generate the qjs tool by default

quickjs: add qjs tool configuration item

---

Application.mk
examples/hello_zig/hello_zig_main.zig

* Zig don't allow unused return value, so let's discard it explictly.
* Correct wrong make variable name for Zig main source, and update compile command for latest compiler.
Zig only
Custom board

Fix hello_zig build break

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_proccmds.c

support uptime command for NuttX
N/A
run uptime command on sim:
nsh>
nsh>
nsh> uptime
19:35:01 up  1:40, load average: 0.00, 0.00, 0.00
nsh>
nsh>
nsh> uptime -s
2022-09-16 17:54:26
nsh>
nsh>
nsh> uptime -p
up 1 hour, 40 minutes
nsh>
nsh>
nsh> uptime -h
Usage:
uptime [options]
Options:
-p, show uptime in pretty format
-h, display this help and exit
-s, system up since
nsh>
nsh>
nsh> uptime -abc
uptime: invalid option -- -abc
Usage:
uptime [options]
Options:
-p, show uptime in pretty format
-h, display this help and exit
-s, system up since
nsh>
nsh>
nsh> date
Fri, Sep 16 19:35:18 2022
nsh>
nsh>

apps/nshlib: add uptime command support

---

nshlib/nsh.h
nshlib/nsh_codeccmd.c
nshlib/nsh_command.c
nshlib/nsh_ddcmd.c
nshlib/nsh_envcmds.c
nshlib/nsh_fscmds.c
nshlib/nsh_mmcmds.c
nshlib/nsh_mntcmds.c
nshlib/nsh_modcmds.c
nshlib/nsh_netcmds.c
nshlib/nsh_parse.c
nshlib/nsh_passwdcmds.c
nshlib/nsh_printf.c
nshlib/nsh_proccmds.c
nshlib/nsh_routecmds.c
nshlib/nsh_script.c
nshlib/nsh_syscmds.c
nshlib/nsh_telnetd.c
nshlib/nsh_test.c
nshlib/nsh_timcmds.c
nshlib/nsh_vars.c

Add the missing **`FAR`** macro for all source files under `apps/nshlib`

Add the missing FAR macro for all source files under apps/nshlib

---

netutils/dhcpc/dhcpc.c
netutils/netinit/netinit.c

netutls/dhcpc: treat EINTR as normal errno
A return code of EINTR is perfectly normal, and isn't an error as such.
It's an indication that your program may need to do something because
a signal occurred, but if not, should re-call recv().
netutils/dhcpc: Set close-on-exec by default to avoid udp_conn leak
netinit: associate wlan if DRIVERS_IEEE80211 enabled
N/A
netinit/dhcpc

netutils/dhcpc: Set close-on-exec by default to avoid udp_conn leak 

---

netutils/dhcpc/dhcpc.c

- Add client id field for dhcp discover and request
- Maybe optimize dhcp server response 
- unknown
Pass CI

netutils/dhcpc: Add dhcp client id option

---

system/trace/trace_dump.c

Optimize sched_note_begin/end, replace note_printf with note_string
the time required changed from 50us to 1us
Need to be used with [#7196](https://github.com/apache/incubator-nuttx/pull/7196)

system/trace: expand dump string

---

examples/i2schar/i2schar_main.c
examples/i2schar/i2schar_transmitter.c

Fix compile error due to unnecessary endif.
Fix warning of long line.
Before fixing the issue whenever the `i2schar` example was selected to be compiled it broke the compilation because of the unnecessary `endif`statement.
Tested with internal CI.

examples/i2schar: Fix compile error and warning

---

testing/ostest/prioinherit.c

When application is compiled without optimisation the stack usage is higher. 1K stack of `adversary` task is getting overflowed and that leads to crash. Set stack size to CONFIG_DEFAULT_TASK_STACKSIZE for `adversary` task.
Improve stability of ostest
ostest passed when compiled with `CONFIG_DEBUG_FULLOPT=n` on stm32f4-discovery and same70-qmtech boards.

ostest/prioinherit: fix priority inheritance test when compiled without optimisation

---

Makefile

The condition:
[ -f "$${f}" ] && cp -f "$${f}" "${EXPORTDIR}"$(DELIM)registry ;
Fails if the first part of the condition returns empty / false, stopping make for no reason due to the error.

make export: Fix make export for CONFIG_BUILD_KERNEL=y

---

examples/tcpblaster/tcpblaster_client.c
examples/tcpblaster/tcpblaster_server.c
examples/udpblaster/udpblaster_target.c
graphics/twm4nx/src/cinput.cxx
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

since spec require the implementation always report POLLERR/POLLHUP: https://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html
Follow nuttx patch: https://github.com/apache/incubator-nuttx/pull/7227
Minor
Pass CI

poll: Don't need monitor POLLERR or POLLHUP explicitly

---

wireless/wapi/src/wapi.c

Avoid setting a password with invalid size, according with IEEE802.11i:
"A pass-phrase is a sequence of between 8 and 63 ASCII-encoded characters. The limit of 63 comes from the desire to distinguish between a pass-phrase and a PSK displayed as 64 hexadecimal characters."
Some WIFI libs like the ESP32 expects that the password size respect the norm.
```
nsh> wapi psk wlan1 SmallP 3
The password should have between 8 and 63 characters!
ERROR: Process command (psk) failed.
```

wapi: Verify if password size if valid

---

examples/pipe/interlock_test.c
examples/pipe/transfer_test.c

clean example pipe build warning 
transfer_test.c:66:12: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
int fd = (int)pvarg;
^
transfer_test.c: In function 'transfer_writer':
transfer_test.c:122:12: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
int fd = (int)pvarg;
^
transfer_test.c: In function 'transfer_test':
transfer_test.c:169:58: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ret = pthread_create(&readerid, NULL, transfer_reader, (pthread_addr_t)fdin);
^
transfer_test.c:179:58: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ret = pthread_create(&writerid, NULL, transfer_writer, (pthread_addr_t)fdout);
^
transfer_test.c:202:13: error: …

examples: clean warning of pipe

---

examples/nxterm/nxterm_main.c
graphics/nxwm/src/cnxterm.cxx
graphics/twm4nx/apps/cnxterm.cxx
nshlib/nsh_altconsole.c
nshlib/nsh_consolemain.c
nshlib/nsh_init.c
nshlib/nsh_telnetd.c
nshlib/nsh_usbconsole.c
system/nsh/nsh_main.c

- nshlib: Call nsh_sysinitscript in usb or alt console like normal one
- nshlib: Call nsh_telnetstart in nsh_initialize to avoid the dupliation
- nshlib: Move commoin initialization from console_main to nsh_initialize
nshlib
sim:nsh

Refine nshlib implementation

---

examples/tcp_ipc_client/Kconfig
examples/tcp_ipc_client/Make.defs
examples/tcp_ipc_client/Makefile
examples/tcp_ipc_client/README.md
examples/tcp_ipc_client/protocol.h
examples/tcp_ipc_client/tcp_ipc_client_main.c
examples/tcp_ipc_server/Kconfig
examples/tcp_ipc_server/Make.defs
examples/tcp_ipc_server/Makefile
examples/tcp_ipc_server/README.md
examples/tcp_ipc_server/lorawan/uart_lorawan_layer.h
examples/tcp_ipc_server/protocol.c
examples/tcp_ipc_server/protocol.h
examples/tcp_ipc_server/tcp_ipc_server_main.c
examples/tcp_ipc_server/uart_lorawan_layer.c

This commit consists of a cleint & server examples that use TCP/IP sockets as IPC channel.
The IPC here is a reliable and controlled way to controll LoRaWAN connectivity access by multiple applications, allowing multiple LoraWAN applications that use LoraWAN to work on a single ESP32 without any conflicts on using LoRaWAN connectivity.
The server_tcp and client_tcp examples have been developed by Flavio Ipirranga and Pedro Bertoleti from Instituto de Pesquisas Eldorado (IPE) in Brazil.
No impact (these examples don't affect any other examples and/or repositories.
Successfully tested and validated, as seen on Nuttx International Workshop 2022: https://www.youtube.com/watch?v=hr0OfTt1KeY

Client & Server examples to use TCP/IP socket as an IPC Channel

---

Application.mk
Makefile
import/Make.defs

Allows building the static "libapps.a" library separately for CONFIG_BUILD_KERNEL=y
Almost nothing, kernel mode build only. The result for make import remains the same, this merely allows building libapps.a separately if it is needed.
icicle:knsh

Libapps for kernel build

---

graphics/libjpeg/0001-libjpeg-add-preconfigured-jconfig.h.patch
graphics/libjpeg/Kconfig
graphics/libjpeg/Make.defs
graphics/libjpeg/Makefile

This package contains C software to implement JPEG image encoding, decoding, and transcoding.  JPEG is a standardized compression method for full-color and grayscale images.
The distributed programs provide conversion between JPEG JFIF format and image files in PBMPLUS PPM/PGM, GIF, BMP, and Targa file formats.  The core compression and decompression library can easily be reused in other programs, such as image viewers.  The package is highly portable C code; we have tested it on many machines ranging from PCs to Crays.
JPEG support
Spresense

apps: system: add libjpeg

---

examples/tcp_ipc_client/Kconfig
examples/tcp_ipc_client/tcp_ipc_client_main.c
examples/tcp_ipc_server/Kconfig

This PR makes the following:
- Fixes unusable variable warning (ndx variable)
- Improve Kconfig of TCP IPC Client and Server examples, by automatically configuring all configs needed when enabling these examples.
There's no impact on other examples
This was successfully tested and validated on a hardware test set (ESP32 + Radioenge LoraWAN module)

Fixed unused variable and improved Kconfig for TCP IPC Client & Server

---

netutils/cwebsocket/0001-Porting-the-code-for-NuttX.patch
netutils/cwebsocket/0002-Revert-dsp_message-and-app_message-to-original.patch
netutils/cwebsocket/Kconfig
netutils/cwebsocket/Make.defs
netutils/cwebsocket/Makefile

High performance websocket client/server
The goal of cwebsocket is to provide a portable,
high performance websocket client/server,
especially on low power embedded systems.
cwebsocket is currently in a development state. You may encounter bugs. Report them for a timely fix.
Successful tests have been conducted on the following architectures:
x86
x86_64
ARM
cwebsocket is compliant with the following standards:
ANSI C
POSIX
RFC 6455
websockets
Spresense

system: add cwebsocket support

---

README.md
boot/mcuboot/Make.defs
boot/mcuboot/Makefile
crypto/tinycrypt/.gitignore
crypto/tinycrypt/Kconfig
crypto/tinycrypt/Make.defs
crypto/tinycrypt/Makefile

add tinycrypt to crypto
and then inside of mucboot internal used lib
mcuboot

add tinycrypt to crypto

---

netutils/dhcpc/dhcpc.c

A bug causing xid to be 0.
DHCP xid
Tested on BL602

dhcpc:fix xid error clear bug.

---

testing/ostest/prioinherit.c

since CONFIG_SEM_NNESTPRIO is removed by:
https://github.com/apache/incubator-nuttx/pull/6318
Remove the dead code
Pass CI

testing/ostest: Remove the code which reference CONFIG_SEM_NNESTPRIO

---

netutils/webserver/httpd_dirlist.c
netutils/webserver/httpd_sendfile.c

- I noticed that the webserver can not handle a directory.
- This commit fixes this issue.
- None

netutils: webserver: Fix directory handling

---

testing/ostest/prioinherit.c

ostest,sem use lock need set protocl `SEM_PRIO_INHERIT`
[patch](https://github.com/apache/incubator-nuttx/pull/5070)
use sem as lock,need do is change
ostest

ostest:add sem protocl to priority inheritance

---

testing/ltp/Makefile

Signed-off-by: nietingting <nietingting@xiaomi.com>
ltp: fix build fail with "argument too long" issue on 20.04
no
test on local

ltp: fix build fail with "argument too long" issue on 20.04

---

testing/cxxtest/cxxtest_main.cxx

enable test_stl2 only when CONFIG_LIBCXX is enabled since uClibc++/minic++ doesn't have array header file
Fixed the build break report here: https://github.com/apache/incubator-nuttx/actions/runs/3305999084/jobs/5456570758
Pass CI

Fix fatal error: array: No such file or directory

---

README.md

When try to access `nuttx/Documentation/NuttXPortingGuide.html` online, it will prompt that `the repository has been deleted`, and the prompt information is as follows:
```
This repository has been deleted
Our apologies, but the repository "nuttx/nuttx" has been deleted. 
It now lives at https://bitbucket.org/patacongo/nuttx.
```
Also the file `nuttx/Documentation/NuttXPortingGuide.html` has been removed under `nuttx/Documentation`, so this link is not needed here.
None

README.md: remove inaccessible links

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
include/industry/foc/fixed16/foc_ident.h
include/industry/foc/float/foc_ident.h
industry/foc/fixed16/foc_ident.c
industry/foc/float/foc_ident.c

- industry/foc/foc_ident: make the Ki resistance measurement parameter configurable
The hardcoded parameter may not be suitable for various types of motors
CI

foc_ident: make the Ki resistance measurement parameter configurable

---

wireless/gs2200m/gs2200m_main.c

Fix the type to match usrsock.h has been changed by https://github.com/apache/incubator-nuttx/pull/6893

wireless: gs2200m: Change usrsock xid from uint64_t to uint32_t

---

examples/usrsocktest/usrsocktest_daemon.c

The following error was reported when runing usrsocktest with KASAN check enabled.
==1348590==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xf20ec610 at pc 0x56ac61ba bp 0xf20ec278 sp 0xf20ec268
rootcause:
hdrbuf's size is not large enough to store the data in usrsock's request.
solution:
double herbuf's size to make sure the space, used to store usrsock's request, is enough.
usrsocktest

usrsock:fix stack-buffer-overflow issue when running basic_send test case

---

README.md

Removing NuttX Porting Guide Online link directly is unfriendly, please refer to https://github.com/apache/incubator-nuttx-apps/pull/1380#issuecomment-1288098689, so update this link to make it easier for users.

README.md: Update NuttX Porting Guide Online link

---

netutils/ftpd/ftpd.c

Report by: https://github.com/apache/incubator-nuttx/actions/runs/3318241409/jobs/5482179373
Fix warning
Pass CI

Fix Error: ftpd.c:1773:9: error: variable 'pos' set but not used [-Werror,-Wunused-but-set-variable]

---

netutils/discover/discover.c

```
Error: discover.c:210:13: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'in_addr_t' {aka 'unsigned int'} [-Werror=format=]
210 |       ninfo("Received discover from %08lx'\n", srcaddr.sin_addr.s_addr);
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~
|                                                                |
|                                                                in_addr_t {aka unsigned int}
discover.c:210:41: note: format string is defined here
210 |       ninfo("Received discover from %08lx'\n", srcaddr.sin_addr.s_addr);
|                                     ~~~~^
|                                         |
|                                         long unsigned int
| …
```

Fix the compiler warning

---

testing/mm/mm_main.c

It's better to add DEBUGASSERT in mm code to check the unaligned problem instead add a complex test case.
BTW, there are other memory implementation(e.g. sim use the host heap manager directly), it isn't good to test the internal data struct in common code.
no impach
sim:nsh config mm test pass

mm_main: delete realloc boundary test

---

examples/alarm/alarm_main.c

alarm: using timegm instead of mktime beacuse rtc is gmt time
Signed-off-by: dongjiuzhu1 <dongjiuzhu1@xiaomi.com>
correct for command: alarm -r 
local test

alarm: using timegm instead of mktime beacuse rtc is gmt time

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c
examples/foc/foc_parseargs.h
examples/foc/foc_thr.h

- examples/foc: refactor args
- examples/foc: separate control thread configuration from general args
- examples/foc: simplify control thread configuration
- examples/foc: move validate_args to parseargs file
- examples/foc/Kconfig: update EXAMPLES_FOC_MMODE range
- examples/foc: control motor identification parameters from cmd line
nucleo-g431rb/ihm16m1

examples/foc: various improvements and refactor

---

industry/foc/fixed16/foc_ident.c
industry/foc/float/foc_ident.c

- industry/foc/fixed16/foc_ident.c: port changes from float32 implementation
- industry/foc/fixed16/foc_ident.c: fix div operation
- industry/foc/fixed16/foc_ident.c: add b16_t overflow protection
nucleo-g431rb/ihm16m1

industry/foc/fixed16/foc_ident.c: improvements

---

examples/tcp_ipc_server/lorawan/uart_lorawan_layer.h
examples/tcp_ipc_server/protocol.c
examples/tcp_ipc_server/uart_lorawan_layer.c

This PR improves the tcp_ipc_server code, by doing:
- "AT_BUSY_ERROR" (sent from LoRaWAN module) handling
- Retry to send LoRaWAN message (max. 3 times) when "AT_BUSY_ERROR" happens
- Fix downlink message buffer size
There's no impact to other projects, it's just a set of improvements to tcp_ipc_server code
It was successfully tested on a hardware set (ESP32 + Radioenge LoRaWAN module).

Improve tcp_ipc_server LoraWAN module communication

---

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

recv request can only get maximum 1500 bytes payload in single response in
earlier design, this patch aggregrate more payloads（maximum 16k bytes）
into one response to make sure usrsock’s req/response mechanism is not
bottleneck during usrsock’s throughput test.
Signed-off-by: liangchaozhong <liangchaozhong@xiaomi.com>

usrsock:aggregrate more data into single recf_from response

---

testing/fstest/Kconfig
testing/fstest/fstest_main.c
testing/mm/Kconfig
testing/mm/mm_main.c

Adds a poweroff call at the end of the FS and MM tests.  
This is needed, as the graceful shutdown allows the generation of .gcda files.
This allows our CI to get code coverage data for these tests when run on the simulator.
By default the option is disabled, so there is no impact on any current system.
Tested execution of both tests, and then I got code coverage information on both tests using lcov.

Added poweroff in fs and mm tests.

---

graphics/nxwidgets/src/cgraphicsport.cxx
graphics/nxwidgets/src/cimage.cxx
graphics/nxwidgets/src/clabel.cxx
graphics/nxwidgets/src/cscaledbitmap.cxx
graphics/slcd/slcd_trapezoids.cxx
include/graphics/nxwidgets/clabel.hxx
include/graphics/nxwm/ccalibration.hxx
include/graphics/twm4nx/ciconmgr.hxx

Reported here:  https://github.com/apache/incubator-nuttx/pull/7391
Style change
Pass CI

Fix slcd_trapezoids.cxx:38:5: error: array designators are a C99 extension

---

graphics/slcd/slcd_trapezoids.cxx

Fix Error: slcd_trapezoids.cxx:84:5: error: array designators are a C99 extension [-Werror,-Wc99-designator]

---

examples/gps/gps_main.c

Fix CI crash because switch() as missing NMEA sentences
Only for CI
LilyGO_TBEAM_LoRa_GPS

Fix CI crash because switch() was missing NMEA sentences

---

netutils/dhcpc/Kconfig

Issue
DHCP server will send DHCP offer/ack via broadcast packet if broadcast flag is enabled in DHCP discover/request.
There's no retransmition mechanism for broadcast frame in 802.11 MAC layer, thus transmit fail rate might be very high. This will increase DHCP fail rate.
Solution
Disable broadcast flag by default
DHCP
Internal compatibility test

disable BOOTP flag by default during DHCP

---

graphics/pdcurs34/nuttx/pdcthread.c
netutils/netlib/netlib_getarptab.c
netutils/netlib/netlib_getdevs.c
netutils/netlib/netlib_getnbtab.c
netutils/netlib/netlib_getroute.c
netutils/thttpd/libhttpd.c
system/taskset/taskset.c
testing/ostest/prioinherit.c
testing/ostest/timedwait.c

following the change in the nuttx kernel, implement the right semantics:
1. getpid should return the main thread id
2. gettid should return the current thread id
update apps code
Refer:
https://github.com/apache/incubator-nuttx/issues/2499
https://github.com/apache/incubator-nuttx/pull/2518
Nuttx Kernel PR:
https://github.com/apache/incubator-nuttx/pull/7597
any code that use getpid/gettid need to check
ostest PASSED at qemu with configure
1. ARM 32bit: ./tools/configure.sh -l sabre-6quad:nsh
2. ARM 64bit: ./tools/configure.sh -l qemu-armv8a:nsh
Let's ignore the false nxstyle warning.

apps: getpid should return process id not thread id

---

DISCLAIMER

NuttX has graduated the Incubator!
- Removing the DISCLAIMER file.
None.
N/A.

Remove DISCLAIMER. Apache NuttX has graduated the Incubator.

---

examples/tcp_ipc_server/Makefile

The `lorawan` folder is under the path of `examples/tcp_ipc_server`, the `server_tcp` folder does not exist here, so fix it.
```
➜  /home/mi/xiaomi/nuttx/apps/examples/tcp_ipc_server/lorawan git:(makefile) pwd
/home/mi/xiaomi/nuttx/apps/examples/tcp_ipc_server/lorawan
➜  /home/mi/xiaomi/nuttx/apps/examples/tcp_ipc_server/lorawan git:(makefile)
```

examples/tcp_ipc_server: fix wrong file path typo

---

wireless/wapi/src/util.c

Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>

wapi: fix save_config can not update if string prefix is same

---

system/ping/Kconfig
system/ping6/Kconfig

system/ping[6]: ping[6] should also be enabled if NET_ICMP[v6]_NO_STACK == y
N/A
icmp ping

system/ping[6]: ping[6] should also be enabled if NET_ICMP[v6]_NO_STACK == y

---

examples/ft80x/ft80x_coprocessor.c
system/vi/vi.c

Found by https://github.com/apache/incubator-nuttx/pull/7391
please ignore the following false warning:
```
/home/xiaoxiang/backup/os/nuttx/apps/system/vi/vi.c:540:57: error: Multiple data definitions
/home/xiaoxiang/backup/os/nuttx/apps/system/vi/vi.c:541:54: error: Multiple data definitions
```
Minor change
Pass CI

Fix Error: vi.c:888:57: error: format string is not a string literal(potentially insecure)

---

system/ping/Kconfig
system/ping6/Kconfig

system/ping: remove depends since NETUTILS_PING already contains this check
N/A
icmp test

system/ping: remove depends since NETUTILS_PING already contains this check

---

netutils/iperf/Kconfig

netutils/iperf: add more default device name
N/A
iperf test

netutils/iperf: add more default device name

---

system/vi/vi.c

```
system/vi: fix nxstyle warning
system/vi/vi.c:540:57: error: Multiple data definitions
system/vi/vi.c:541:54: error: Multiple data definitions
```
N/A
ci-check

system/vi: fix nxstyle warning

---

.github/workflows/build.yml
.github/workflows/check.yml

Update base OS versions:
Linux
* Only the check job is updated from  Ubuntu 18.04 [deprecated]  to "latest" (20.04). Others were already on "latest" which is  Ubuntu 20.04 
MacOS
* Update from  macOS Catalina 10.15 [deprecated] to  macOS Monterey 12
Builds are moved off deprecated runner images.  The Linux build itself should not change as it was already running in a container with a pinned version.
Passing CI provides coverage for this change.

CI: Update worker base OS versions

---

netutils/netlib/netlib_ipv6route.c

When parsing the route table in /proc/net/route/ipv6 the file has leading spaces (represented by '.' in sample below) before every line. The current code would fail to read routes because it looks for the first char of the first line to be a digit. Also fixes a typo in the check for a decimal digit.

fix issue with reading ipv6 routes.

---

.github/workflows/build.yml
.github/workflows/check.yml

NuttX has graduated the Incubator and the repositories will be renamed to remove the `incubator-` prefix.
This PR updates all links, documentation, etc., to the new names.
Note: Please **DO NOT MERGE** until Infra has renamed the repositories!!
See the Infra Jira ticket: https://issues.apache.org/jira/browse/INFRA-23935
Affects GitHub workflows.
N/A

NuttX graduated the Incubator; update repository links

---

testing/monkey/Kconfig

Automatically enable the uinput device when enable the monkey configuration, simplifying user configuration.
Monkey test.
Daily test.

testing/monkey: add auto select uinput

---

include/system/nxplayer.h
system/nxplayer/Makefile
system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_mp3.c
system/nxplayer/nxplayer_pcm.c

nxplayer: add mp3 offload playback demo.
only parse ID3v2 header simple.
usage:
nxplayer
device pcm0p
play /stream/1.mp3
nxplayer
VELA

nxplayer: add mp3 offload playback demo

---

Application.mk
Directory.mk
Make.defs
Makefile
builtin/Makefile
platform/Makefile

These patch finally raised NuttX Windows native build
Windows native build
Tested build of stm32f4discovery on Windows XP/7 + GnuW32 + MinGW + kconfig-frontends-win32

Fix various error in Windows native build

---

graphics/libyuv/0001-include-libyuv-fix-strict-prototype-warning.patch
graphics/libyuv/Makefile

Fix a strict-prototype warning introduced by libyuv headers.

graphics/libyuv: fix strict-prototype warning by patch

---

include/system/nxcamera.h
system/nxcamera/Kconfig
system/nxcamera/Make.defs
system/nxcamera/Makefile
system/nxcamera/nxcamera.c
system/nxcamera/nxcamera_main.c

Add NxCamera app similar to NxLooper, which can be used to control video capture device. The basic capture n' display function is complete, while file output and camera control features are left TODO.
The app can be used even without a real camera. To use v4l2loopback virtual camera (which captures from your desktop screen), you need to have v4l2loopback module installed and enabled. On Ubuntu the commands are:
```
sudo apt-get -y install v4l2loopback-dkms
sudo modprobe v4l2loopback
```
Then `lsmod | grep v4l2loopback` will output something like:
```
v4l2loopback           57344  2
videodev              315392  6 videobuf2_v4l2,v4l2loopback,uvcvideo,videobuf2_common
```
Now that you have v4l2loopback enabled, you can install `ffmpeg` and start a virtual camera with:
```
ffmpeg -f x11grab …
```

apps/system: add nxcamera app

---

interpreters/luamodules/luv/0001-fix-compile-warnings.patch

Fix compile error when reported by CI.
No.
Local build with Wall Werror passed.

luamodules/luv: fix comile warning -Werror=int-to-pointer-cast

---

netutils/iperf/iperf.c

- I noticed that the iperf shows incorrect transfer bytes in each period.
- Also, the bandwidth overflows sometimes.
- This commit fixes these issues.
- None
- Tested with qemu-armv8a:netnsh_smp on QEMU-7.1

netutils: iperf: Fix the transfer bytes and the bandwidth overflow

---

system/nxcamera/nxcamera_main.c

system/camera: fix 'is_image' uninitialized

---

examples/netlink_route/netlink_route_main.c
include/netutils/netlib.h
netutils/dhcpd/dhcpd.c
netutils/netlib/netlib_delarp.c
netutils/netlib/netlib_getarp.c
netutils/netlib/netlib_getarptab.c
netutils/netlib/netlib_setarp.c
nshlib/nsh_command.c
nshlib/nsh_netcmds.c

New command format:
arp [-i <ifname>]                     
arp [-i <ifname>] -a <ipaddr>         
arp [-i <ifname>] -d <ipdaddr>        
arp [-i <ifname>] -s <ipaddr> <hwaddr>

arp commands can specify a network adapter

---

examples/watcher/task_mn.c
system/sched_note/note_main.c
system/trace/trace_dump.c

rename note devices to support multiple note devices
depends on : https://github.com/apache/nuttx/pull/7841
sim:note

drivers/note: rename /dev/note to /dev/note/ram

---

examples/bridge/bridge_main.c
examples/discover/discover_main.c
examples/netlink_route/netlink_route_main.c
examples/tcpecho/tcpecho_main.c
examples/thttpd/thttpd_main.c
examples/webserver/webserver_main.c
examples/xmlrpc/xmlrpc_main.c
netutils/netlib/netlib_delarp.c
netutils/netlib/netlib_getarp.c
netutils/netlib/netlib_getarptab.c
netutils/netlib/netlib_getdevs.c
netutils/netlib/netlib_setarp.c
nshlib/nsh_netcmds.c
wireless/wapi/src/wireless.c

and change the remain inclusion to netinet/arp.h
depends on https://github.com/apache/nuttx/pull/7889

arp: Remove the unnecessary inclusion of nuttx/net/arp

---

interpreters/luamodules/cjson/.gitignore
interpreters/luamodules/cjson/Kconfig
interpreters/luamodules/cjson/Make.defs
interpreters/luamodules/cjson/Makefile

Add luamodules cjson from https://github.com/openresty/lua-cjson
No.
Locally tested.

luamodules/cjson: add lua cjson module

---

industry/scpi/.gitignore
industry/scpi/Kconfig
industry/scpi/Make.defs
industry/scpi/Makefile

Add scpi parser lib from https://github.com/j123b567/scpi-parser/
No.
Builtin demo `scpidemo` in scpi-def.c runs with no problem.

apps/industry: add scpi parser lib

---

interpreters/luamodules/cjson/0001-fix-compile-warnings.patch
interpreters/luamodules/cjson/Makefile

Fix compile warnings -Wstrict-prototypes
No.
CI pass

luamodules: fix compile warning in cjson

---

system/ramspeed/ramspeed_main.c

Fix the error of CI compilation caused by not initializing irqstate_t flags in some cases

system/ramspeed:Fix the error of CI compilation caused by not initializing irqstate_t flags in some cases

---

examples/nxscope/Kconfig
examples/nxscope/Make.defs
examples/nxscope/Makefile
examples/nxscope/nxscope_main.c
include/logging/nxscope/nxscope.h
include/logging/nxscope/nxscope_chan.h
include/logging/nxscope/nxscope_intf.h
include/logging/nxscope/nxscope_proto.h
logging/.gitignore
logging/Make.defs
logging/Makefile
logging/nxscope/Kconfig
logging/nxscope/Make.defs
logging/nxscope/Makefile
logging/nxscope/README.md
logging/nxscope/nxscope.c
logging/nxscope/nxscope_chan.c
logging/nxscope/nxscope_idummy.c
logging/nxscope/nxscope_internals.c
logging/nxscope/nxscope_internals.h
logging/nxscope/nxscope_iser.c
logging/nxscope/nxscope_pser.c

This library provides real-time data logging functionality for NuttX.
Supported features:
- up to 255 channels possible
- support for standard data types and user-specific data
- support for vector data or point data
- support for character-based channels (text messages)
- support for channel metadata - can be used to enumerate samples or timestamp
- stream buffer overflow detection
- remote control with commands
- protocol and interface implementation can be different for control commands and stream data
- (optional) support for user-specific commands
- (optional) support for samples divider
- (optional) support for ACK frames
- (optional) support for user-defined types
- (optional) support for non-buffered critical channels
In the future I would like to extend its functionality. What …

Add the NxScope library - a real-time data logging tool for NuttX

---

system/cachespeed/cachespeed_main.c

In the output format, we expect the format to be [Types Result unit], and this change unifies the output format. And the size of the specified range in the icache test is changed from memset_size to opt_size.

system/cachespeed:Optimize output format and processing logic

---

testing/fstest/fstest_main.c

app/fstest: config the number of open file and the maximum size of file
Adjust resource using on resource-constrained systems
Signed-off-by: dongjiuzhu1 <dongjiuzhu1@xiaomi.com>
using -o and -s to specifc the maximum number of open file and the maximum size of file.
local test

app/fstest: config the number of open file and the maximum size of file

---

netutils/netlib/netlib_prefix2ipv6netmask.c
nshlib/README.md
nshlib/nsh_netcmds.c

Patches included:
- ifconfig: Allow hostip on first non-option place after inet/inet6 
- ifconfig: Support prefixlen/CIDR for IPv6 
NuttX previous:
```
ifconfig eth0 10.0.0.1 [inet]
ifconfig eth0 2022::2 inet6
```
Linux:
```
ifconfig eth0 [inet] 10.0.0.1
ifconfig eth0 [inet6] add 2022::2[/96]
```
FreeBSD:
```
ifconfig eth0 inet 10.0.0.1
ifconfig eth0 inet6 2022::2[/96]
ifconfig eth0 inet6 2022::2 [prefixlen 96]
```
NuttX newly supported:
```
ifconfig eth0 [inet] 10.0.0.1
ifconfig eth0 inet6 [add] 2022::2[/96]
ifconfig eth0 inet6 [add] 2022::2 [prefixlen 96]
```
Ref:
https://man7.org/linux/man-pages/man8/ifconfig.8.html
https://www.freebsd.org/cgi/man.cgi?ifconfig
Improve ifconfig functionality.
Manually tested with commands listed above.

ifconfig: Be compatible with linux/freebsd and support prefixlen for IPv6

---

examples/lp503x/Kconfig
examples/lp503x/Make.defs
examples/lp503x/Makefile
examples/lp503x/lp503x_main.c

Adds example app for LP5030/LP5036 RGB LED driver chip. Depends on successful merge of related PR in main NuttX repo for the relevant driver
None
Custom board with SAMA5D27C-D1G with 2x LP5036 driver chips

Add example app for LP503x LED driver

---

nshlib/nsh.h
nshlib/nsh_fscmds.c
nshlib/nsh_script.c
nshlib/nsh_session.c
nshlib/nsh_stdsession.c

nshlib/script: delete unnecessary log when missing script file.
Signed-off-by: dongjiuzhu1 <dongjiuzhu1@xiaomi.com>
delete unnecessary log 
local test

nshlib/script: delete unnecessary log when missing script file

---

examples/module/drivers/chardev/chardev.c

Continue the change in kernel side: https://github.com/apache/nuttx/pull/8016
code refactor only
Please ignore the nxstyle false alarm:
```
Error: apps/examples/module/drivers/chardev/chardev.c:50:46: error: Multiple data definitions
```

Remove the unnecessary NULL fields in global instance definition of file_operations

---

examples/netlink_route/netlink_route_main.c

examples/netlink_route: fix compiler warning
```
netlink_route_main.c: In function ‘dump_neighbor’: netlink_route_main.c:151:26: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint8_t *’ {aka ‘unsigned char *’} [-Wformat=]
151 |               printf("%02x", nb->ne_addr.u.na_addr);
|                       ~~~^   ~~~~~~~~~~~~~~~~~~~~~
|                          |                |
|                          unsigned int     uint8_t * {aka unsigned char *}
|                       %02hhn
netlink_route_main.c:155:26: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint8_t *’ {aka ‘unsigned char *’} [-Wformat=]
155 |               printf("%02x.", nb->ne_addr.u.na_addr);
|                       ~~~^ …
```

examples/netlink_route: fix compiler warning

---

wireless/wapi/src/util.h

I want to control print information through setlogmask()，so I changed wapi err print to wlerr.
I don't get why the original wapi util.h defined its own err print, which seems redundant to me.
Please review, I don't know if I am missing anything. 
Only on wapi err print message.
Tested on ESP32C3.

wireless/wapi:rework wapi error print in util.h

---

examples/lvgldemo/lvgldemo.c

The LVGL Example App `lvgldemo` currently requires 1 argument: the name of the demo to show.
```bash
lvgldemo widgets
```
In this PR, we propose to make the argument optional if there is only one demo configured. This will enable PINE64 PinePhone to boot straight into `lvgldemo` and auto-start the LVGL App, without entering any `nsh` commands.
`examples/lvgldemo/lvgldemo.c`: If no arguments are specified and only 1 demo exists, select the demo
With this PR, `lvgldemo` will no longer require an argument if there is only one demo configured. So this command:
```bash
lvgldemo
```
Is equivalent to `lvgldemo widgets` if there is only one demo `widgets` configured.
If there is more than one demo configured, or if an argument is provided, `lvgldemo` will work the same way as before.
We …

examples/lvgldemo: Select default demo

---

system/ramspeed/ramspeed_main.c

Make ramspeed test not terminate.
ramspeed test.
None.

system/ramspeed: skip cases where time too short

---

.gitignore

*.su is generated by gcc/clang when we pass -fstack-usage to them
Minor
Pass CI

Add *.su to .gitignore

---

benchmarks/.gitignore
benchmarks/Make.defs
benchmarks/Makefile
benchmarks/coremark/.gitignore
benchmarks/coremark/Kconfig
benchmarks/coremark/Make.defs
benchmarks/coremark/Makefile

Add a benchmark category and EEMBC's CoreMark.
An universal benchmark tool to use on NuttX.
Tested using an ESP32-DevKItC with SMP enabled.
```
nsh> coremark
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 17440
Total time (secs): 17.440000
Iterations/Sec   : 688.073394
Iterations       : 12000
Compiler version : GCC11.2.0
Compiler flags   : Using NuttX compilation options
Parallel PThreads : 2
Memory location  : Defined by the NuttX configuration
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[1]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[1]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[1]crcstate      : 0x8e3a
[0]crcfinal      : 0xa14c
[1]crcfinal      : 0xa14c
Correct operation validated. See README.md for …
```

benchmarks: Add EEMBC's CoreMark

---

nshlib/Kconfig

Enable TMPFS and NSH_QUOTE to get CONFIG_NSH_CMDPARMS working
Now users will get it working because it selects automatically the required features
ESP32-DEVKIT

Enable TMPFS and NSH_QUOTE to get CONFIG_NSH_CMDPARMS working

---

system/nxlooper/nxlooper_main.c
system/nxplayer/nxplayer_main.c

nxplayer_main.c:
code checker warning:
level_percent = (uint8_t) atoi(parg);
'atoi' used to convert a string to an integer value, but function will not report conversion errors; consider using 'strtol' instead.
nxlooper_main.c:
code checker warning:
percent = (uint16_t)(atof(parg) * 10.0);
'atof' used to convert a string to a floating-point value, but function will not report conversion errors; consider using 'strtod' instead
Minor
Pass CI

apps/system/nxplayer&nxlooper:  fix codechecker warning

---

Makefile

Move compile flags to third argument
Depended on by https://github.com/apache/nuttx/pull/8347

Makefile: adjust compilation flags order

---

testing/ostest/mqueue.c

- This commit shows errno in message queue test
- None
- Tested with esp32-devkitc:smp on QEMU-7.1

testing: ostest: Show errno in message queue test

---

include/system/nxplayer.h
system/nxplayer/Makefile
system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_common.c

nxplayer: enqueue streaming data to audio driver.
Signed-off-by: qiaohaijiao1 <qiaohaijiao1@xiaomi.com>
add support streaming data instead of framed. 
N/A
Xiaomi Vela

nxplayer: enqueue streaming data to audio driver.

---

Application.mk

Avoid add ZIGELFFLAGS to each board level Make.defs by default value.
Zig only
Local machine

Application.mk: Provide a default ZIGELFFLAGS if not defined

---

nshlib/README.md
nshlib/nsh_command.c
nshlib/nsh_netcmds.c

From comment in cmd_ifconfig, it seems that we support `ifconfig [interface]`, but actually not considering the interface param now. After this commit, we only print the information of interface specified in param, just like linux.
Also updates the arg limit of the ifconfig command to meet current function.
Support `ifconfig eth0` to only print information on `eth0`
Manually on sim.

ifconfig: Support `ifconfig interface` and update arg limit

---

system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_mp3.c

Signed-off-by: qiaohaijiao1 <qiaohaijiao1@xiaomi.com>
Improve compatibility which mp3 file has no ID3V2 header
N/A
Xiaomi Vela

nxplayer: add support which mp3 file which has no ID3 header

---

testing/sensortest/sensortest.c

Fix sensortest.c:168:40: error: format specifies type 'unsigned long' but the argument has type 'uint32_t' (aka 'unsigned int') [-Werror,-Wformat]

---

examples/README.md
examples/lvglterm/Kconfig
examples/lvglterm/Make.defs
examples/lvglterm/Makefile
examples/lvglterm/lvglterm.c

This PR adds an LVGL App that executes NSH Commands (entered with a Touchscreen Keyboard) and renders the NSH Output. The app follows the same design as the `lvgldemo` app and is explained here: ["NuttX RTOS for PinePhone: LVGL Terminal for NSH Shell"](https://lupyuen.github.io/articles/terminal)
`examples/README.md`: Added doc for `lvglterm` app
`examples/lvglterm/lvglterm.c`: LVGL Terminal App
`examples/lvglterm/Makefile`, `Make.defs`: Makefile for LVGL Terminal
`examples/lvglterm/Kconfig`: Added menuconfig option for "Application Configuration > Examples > LVGL Terminal"
LVGL Terminal is not called by any existing code.
We tested LVGL Terminal on PINE64 PinePhone:
-  [Build Settings](https://github.com/lupyuen/lvglterm/blob/main/README.md)
- …

examples/lvglterm: Add LVGL Terminal for NSH

---

examples/nxscope/Kconfig
examples/nxscope/nxscope_main.c
logging/nxscope/nxscope_iser.c

- logging/nxscope/nxscope_iser.c: wait for device if CONFIG_SERIAL_REMOVALBE=y
- examples/nxscope: add support for CDCACM dev
stm32f4discovery

examples/nxscope: add support for CDCACM dev

---

system/trace/trace.c

When using the Android trace format, if there is no file header, the file cannot be parsed correctly
In this case, the file content is the same, but the parsing fails when there is no header
Open these two files respectively in https://ui.perfetto.dev/
[trace_has_header.log](https://github.com/apache/nuttx-apps/files/10673523/trace_has_header.log)
[trace_no_header.log](https://github.com/apache/nuttx-apps/files/10673524/trace_no_header.log)

trace: add trace header when dumping

---

examples/timer_gpio/timer_gpio_main.c

examples/timer_gpio: fix compilation
Broken since 9368b659a763faa4e45b657ea71922b651751aa5
CI

examples/timer_gpio: fix compilation

---

examples/nxscope/Kconfig
examples/nxscope/nxscope_main.c

- examples/nxscope: add a new option to wake up the samples thread with timer.
Now we can add samples at a higher frequency than with usleep().
stm32f4disco

examples/nxscope: wake up the samples thread with timer

---

include/logging/nxscope/nxscope_chan.h
logging/nxscope/nxscope_chan.c

- nxscope: use the entire reserved channel length when sending strings.
The previous version makes stream data parser too complicated and susceptible to errors.

nxscope: use the entire reserved buffer when sending strings

---

examples/calib_udelay/Kconfig
graphics/twm4nx/Kconfig
mlearning/cmsis/Kconfig
mlearning/libnnablart/Kconfig
netutils/thttpd/Kconfig
netutils/webserver/Kconfig
system/dumpstack/Kconfig

build/Kconfig: fix warnings detected by kconfiglib
Part of https://github.com/apache/nuttx/pull/8485
N/A
before:
$ APPSDIR=../apps/ EXTERNALDIR=dummy menuconfig
```bash
Kconfig:233: warning: the 'modules' option is not supported. Let me know if this is a problem for you, as it wouldn't be that hard to implement. Note that modules are supported -- Kconfiglib just assumes the symbol name MODULES, like older versions of the C implementation did when 'option modules' wasn't used.
arch/arm/Kconfig:1361: warning: style: quotes recommended around 'arch/arm/src/s32k3xx/Kconfig' in 'source arch/arm/src/s32k3xx/Kconfig'
arch/arm/Kconfig:1418: warning: style: quotes recommended around 'arch/arm/src/stm32wb/Kconfig' in 'source arch/arm/src/stm32wb/Kconfig' …
```

build/Kconfig: fix warnings detected by kconfiglib

---

canutils/candump/Kconfig
canutils/cansend/Kconfig
examples/nrf24l01_btle/Kconfig
examples/pty_test/Kconfig
games/shift/Kconfig
math/libtommath/Kconfig
mlearning/cmsis/Kconfig
mlearning/darknet/Kconfig
netutils/codecs/Kconfig
netutils/dhcp6c/Kconfig
netutils/thttpd/Kconfig
nshlib/Kconfig
system/uniqueid/Kconfig
wireless/bluetooth/nimble/Kconfig

Throughout Kconfig, we indent with TABS. However, some Kconfig files had areas indented with spaces. Making these consistent with the rest.
Consistent style.
N/A

Kconfig: Make indent consistent with TABS

---

platform/Kconfig

build/Kconfig: add BINDIR/APPSBINDIR to support out of tree build
First decoupling changes from https://github.com/apache/nuttx/pull/6718
Depends on: https://github.com/apache/nuttx/pull/6718
N/A
cmake (https://github.com/apache/nuttx/pull/6718)

build/Kconfig: add BINDIR/APPSBINDIR to support out of tree build

---

system/cle/cle.c

The old flagging was insufficient, only '\r' was accepted as a line terminator if CONFIG_EOL_IS_EITHER_CRLF was set.
I noticed this regression after:
https://github.com/apache/nuttx/pull/8454
Now that CR is bucketed into LF, this patches the nsh terminal, if the PC terminal uses CR
icicle:nsh

system/cle.c: Fix configuration for CONFIG_EOL_IS_EITHER_CRLF=y

---

system/nxcamera/nxcamera_main.c

system/nxcamera: fix sscanf overflow

---

netutils/netinit/Kconfig

The current WiFi configuration expects user to look at symbols in the wireless headers to configure it. This patch will improve it. Notice that even those symbols that are bitfields are not allowed to have more than 1 bit set at time, so this modification will not have impact since the bits were already mutually exclusive.
Make it easier to users to configure the WiFi
ESP32

netinit: Improve WiFi configuration

---

testing/cmocka/0001-cmocka.c-Reduce-the-call-stack-consumption-of-printf.patch
testing/cmocka/0002-cmocka-feature-to-forwarding-cmocka-log-message-to-c.patch
testing/cmocka/Makefile

Specify cmocka as the latest version 1.15
add patch to enable cmocka to output with syslog
Update cmocka version and add patch
None
Pass vela CI

testing/cmocka: update cmocka version and add patch

---

fsutils/passwd/passwd_find.c

I manually added the `-fanalyzer` compile option on the simulation (Ubuntu 20.04 with GCC 10.3.0) to check my application for potential memory leaks. Then, I found this problem.
```
In function ‘passwd_find’:
passwd_find.c:82:14: warning: leak of ‘iobuffer’ [CWE-401] [-Wanalyzer-malloc-leak]
82 |       return -errcode;
|              ^~~~~~~~
‘passwd_find’: events 1-5
|
|   65 |   iobuffer = (FAR char *)malloc(CONFIG_FSUTILS_PASSWD_IOBUFFER_SIZE);
|      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|      |                          |
|      |                          (1) allocated here
|   66 |   if (iobuffer == NULL)
|      |      ~
|      |      |
|      |      (2) assuming ‘iobuffer’ is non-NULL
|      |      (3) following ‘false’ branch (when ‘iobuffer’ is …
```

fsutils/passwd: fix warning: leak of ‘iobuffer’ [CWE-401] [-Wanalyzer-malloc-leak]

---

graphics/lvgl/Kconfig
graphics/lvgl/port/lv_port_touchpad.c

Add a virtual cursor display for easy comparison of click positions.
Set the value of `LV_PORT_TOUCHPAD_CURSOR_SIZE` to configure the cursor size, and set it to 0 to turn off the cursor display.
LVGL application.
`sim:lvgl_fb`

lvgl/port/lv_port_touchpad: add cursor display

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_fscmds.c

Create MTD loop device from command line (lomtd, similar to losetup, losmart)
No impact
Testing should be performed when related code will be added to nuttx repository (pr. #8573)
Preparing:
config: Simulator, enable littlfs, spiffs, filemtd + mtd loop
apps: nsh component lomtd is not disabled
host: create files, e.g., littlefs.dat, spiffs.dat
./nuttx
nsh>mount -t hostfs -o fs=/home/oreh /host
nsh>lomtd -s 1024 -e 4096 -o 0 /dev/mtd0 /host/littlefs.dat
nsh>mount -t littlefs -f "forceformat" /dev/mtd0 /mnt0
nsh>ls /mnt0
nsh>lomtd -s 1024 -e 4096 -o 0 /dev/mtd1 /host/spiffs.dat
nsh>mount -t spiffs -o "forceformat" /dev/mtd1 /mnt1
nsh>ls /mnt1

Add NSH lomtd command

---

system/libuv/Makefile

system/libuv: check GCC version before set special flags
GCC-12.2
GCC-12.2

system/libuv: check GCC version before set special flags

---

testing/drivertest/Makefile
testing/drivertest/drivertest_i2c_spi.c

The BMI160 6-axis acceleration sensor is used as the peripheral of the I2C test. The main purpose of the test is to open the peripheral and read the data of the sensor. If it is read successfully, the test is successful.
Add compiled constraints to make it work only when the bmi160 driver is turned on.

drivertest/drivertest_i2c_spi: add testcase for `i2c` and `spi`

---

examples/lvgldemo/lvgldemo.c
graphics/lvgl/Kconfig
graphics/lvgl/Makefile
graphics/lvgl/port/lv_port_libuv.c
graphics/lvgl/port/lv_port_libuv.h

Add LVGL libuv porting to replace traditional UI polling.
LVGL application.
```bash
./tools/configure.sh -l sim:lvgl_fb
```
libuv config:
```
CONFIG_LIBUV=y
CONFIG_DISABLE_ENVIRON=n
CONFIG_PTHREAD_MUTEX_TYPES=y
CONFIG_TLS_TASK_NELEM=32
```

lvgl/port: add libuv porting

---

graphics/lvgl/Makefile

Without this change the build produces error:
error: ‘-Wformat-security’ ignored without ‘-Wformat’

graphics/lvgl: fix build due to no-format-security

---

examples/lvgldemo/lvgldemo.c

Use nitems to get the length of the array, simplify the code.
lvgldemo
None

lvgldemo: use nitems instead of sizeof

---

Makefile

and nuttx/tools/testbuild.sh already do the same check.
Minor
CI

build: Remove the annoy warning from distclean

---

interpreters/bas/bas_fs.c
system/cle/cle.c
system/readline/readline.h
system/readline/readline_common.c
system/vi/vi.c

Remove CONFIG_EOL_IS_XXX relative logic since serial driver will do the convertion.
Please ignore nxstyle error from `bas_fs.c`.
Should be none.
cle/vi/bas/readline

stdio: Remove CONFIG_EOL_IS_XXX

---

crypto/mbedtls/Makefile

crypto/mbedtls: disable optimize on sim platform 
mbedtls
build break if enable MBEDTLS_HAVE_ASM && CONFIG_DEBUG_FULLOPT on sim platform
```bash
In file included from mbedtls/library/bignum.c:41:
mbedtls/library/bignum.c: In function ‘mpi_mul_hlp’:
mbedtls/library/bn_mul.h:86:13: error: ‘asm’ operand has impossible constraints
86 | #define asm __asm
|             ^~~~~
mbedtls/library/bn_mul.h:102:5: note: in expansion of macro ‘asm’
102 |     asm(                                    \
|     ^~~
mbedtls/library/bignum.c:1669:9: note: in expansion of macro ‘MULADDC_INIT’
1669 |         MULADDC_INIT
|         ^~~~~~~~~~~~
mbedtls/library/bn_mul.h:86:13: error: ‘asm’ operand has impossible constraints
86 | #define asm __asm
|             ^~~~~
mbedtls/library/bn_mul.h:102:5: note: in …
```

crypto/mbedtls: disable optimize on sim platform 

---

nshlib/nsh.h
nshlib/nsh_altconsole.c
nshlib/nsh_builtin.c
nshlib/nsh_codeccmd.c
nshlib/nsh_command.c
nshlib/nsh_console.c
nshlib/nsh_console.h
nshlib/nsh_consolemain.c
nshlib/nsh_dbgcmds.c
nshlib/nsh_ddcmd.c
nshlib/nsh_envcmds.c
nshlib/nsh_fileapps.c
nshlib/nsh_fscmds.c
nshlib/nsh_fsutils.c
nshlib/nsh_login.c
nshlib/nsh_mmcmds.c
nshlib/nsh_modcmds.c
nshlib/nsh_parse.c
nshlib/nsh_printf.c
nshlib/nsh_script.c
nshlib/nsh_system.c
nshlib/nsh_telnetlogin.c
nshlib/nsh_usbconsole.c
nshlib/nsh_usbtrace.c

continue the change from https://github.com/apache/nuttx-apps/pull/1559, found by https://github.com/apache/nuttx/pull/4819.
nshlib
CI

nshlib: Remove the remaining CONFIG_FILE_STREAM dependence

---

nshlib/nsh_builtin.c

Fix nsh_builtin.c:91:22: error: 'SA_NOCLDWAIT' undeclared

---

logging/nxscope/README.md

logging/nxscope: add a mention of available client tools for NxScope.
- nsxlib - a client library for NxScope devices
- nxscli - a command-line interface tool with 'pythonic' plugin architecture
I also started working on a GUI tool with embedded Matplotlib plots, but abandoned it for now. The command-line interface is easier to use (and more fun to write).

logging/nxscope: add a mention of available client tools for NxScope

---

config.nims
examples/hello_nim/.gitignore
examples/hello_nim/Kconfig
examples/hello_nim/Make.defs
examples/hello_nim/Makefile
examples/hello_nim/hello_nim_async.nim
examples/hello_nim/hello_nim_main.c

Added sample application in Nim language
It allows you to create applications in the Nim language, which can be easily integrated with the C language so that you can use NuttX features in Nim right away.
1.  No need to create HAL, binding modules.
2.  Can use Nim standard libraries, external libraries.
Tested on sim, arm Cortex-A5, Cortex-M4.
1.  install choosenim, latest Nim language.
> https://nim-lang.org/install_unix.html
>  `$ choosenim devel --latest`
2. configure NuttX.
This example uses async/await, which requires the following items to be enabled
>CONFIG_SCHED_CHILD_STATUS=y
>CONFIG_NET=y
>CONFIG_NET_SOCKOPTS=y
important:
I am sending out a pull request to clear Nim's asyncdispatch module global dispatcher at the end of the task.
https://github.com/nim-lang/Nim/pull/21432
Until …

add "hello_nim" example application written in Nim.

---

examples/pwm/Kconfig

PWM drivers support channel numbers 0 (skip the channel) and -1 (skip this channel and all following channels). This commit enables usage of this numbers in PWM example application.
Just config option.
Application tested.

pwm: update channel range with support of 0 and -1

---

nshlib/nsh_script.c

When using the rcS file, the end of reading the file will enter an infinite loop

nsh: fix nsh startup failure

---

system/readline/readline_common.c

Let's echo character by serial driver, this will imporve the experience of telnetd, which will display input command and newline twice.
And also enhance the compatiblity with some third party linux readline based application (like WAMR repl).
nsh
nsh over serial and telnetd

readline: Don't echo input except VT100 command

---

wireless/bluetooth/nimble/Kconfig

bluetooth/nimble: update to bc7828341226d860429c63994065f8f1b8b8d7b0
which fix https://github.com/apache/mynewt-nimble/pull/1472

bluetooth/nimble: update to bc7828341226d860429c63994065f8f1b8b8d7b0

---

graphics/lvgl/Makefile

This introduces changes from NuttX commit
03b164f59ce40a3f5677b0588af2aee8d9697bf6.

lvgl: silent download and unpack

---

nshlib/nsh_command.c
nshlib/nsh_proccmds.c

This change reduce the usage of `printf`,
which will improve both CPU usage and IO performance.
help command
esp32c3 and telnet

nsh: Improve performance of `help` by line buffer

---

nshlib/nsh_login.c

* nsh/login: Fix error prompt length
* nsh: Don't echo password during login
nsh login
sim:nsh

nsh: Don't echo password during login

---

interpreters/wamr/Kconfig

This PR intends to fix a hidden dependency issue with the `INTERPRETERS_WAMR_LIBC_WASI` config, which requires `PSEUDOFS_SOFTLINKS` to be enabled to properly build.
Not including it results in linker errors due to missing symbols:
```
LD: nuttx
xtensa-esp32s3-elf-ld: /home/nihei/Projects/NuttX/nuttx/staging/libapps.a(posix.c.home.nihei.Projects.NuttX.apps.interpreters.wamr.o):(.literal.readlinkat_dup+0x0): undefined reference to `readlinkat'
xtensa-esp32s3-elf-ld: /home/nihei/Projects/NuttX/nuttx/staging/libapps.a(posix.c.home.nihei.Projects.NuttX.apps.interpreters.wamr.o):(.literal.wasmtime_ssp_path_link+0x0): undefined reference to `linkat'
xtensa-esp32s3-elf-ld: /home/nihei/Projects/NuttX/nuttx/staging/libapps.a(posix.c.home.nihei.Projects.NuttX.apps.interpreters.wamr.o):(.literal.wasmt …
```

wamr: Fix `INTERPRETERS_WAMR_LIBC_WASI` dependency on `PSEUDOFS_SOFTLINKS`

---

system/cle/cle.c

Before:
```
NuttShell (NSH) NuttX-12.0.0
nsh> free
total       used       free    largest  nused  nfree
Umem:   33154512      33584   33120928   33120928     96      1
```
After:
```
NuttShell (NSH) NuttX-12.0.0
nsh> free
total       used       free    largest  nused  nfree
Umem:   33154512      33584   33120928   33120928     96      1
```
nsh with cle
QEMU

system/cle: Don't echo extra '\n'

---

nshlib/nsh_command.c

Introduced by https://github.com/apache/nuttx-apps/pull/1610, internal line buffer should have more bytes for tab before newline and '\0'.
cmd help
QEMU with ubsan/kasan enabled

nsh: Fix a buffer overflow in `help`

---

.gitignore
Application.mk
Make.defs
Makefile
benchmarks/coremark/Makefile
examples/hello/Makefile
interpreters/Wasm.mk
interpreters/wamr/Toolchain.defs

interpreters/wamr: add compile role of WebAssembly
Add compilation rules to support WebAssembly(WASM/WAMR):
1. Compile Toolchain 
1> Download WASI sdk and export the WASI_SDK_PATH path:
```bash
$ wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk-19.0-linux.tar.gz
$ tar xf wasi-sdk-19.0-linux.tar.gz
Put wasi-sdk-19.0 to your host WASI_SDK_PATH environment variable, like:
$ export WASI_SDK_PATH=`pwd`/wasi-sdk-19.0
```
2> Download Wamr "wamrc" AOT compiler and export to the PATH:
```bash
$ mkdir wamrc
$ wget https://github.com/bytecodealliance/wasm-micro-runtime/releases/download/WAMR-1.1.2/wamrc-1.1.2-x86_64-ubuntu-20.04.tar.gz
$ tar xf wamrc-1.1.2-x86_64-ubuntu-20.04.tar.gz
$ export PATH=$PATH:$PWD
```
3. Configuring and running
1> Configuring sim/wamr and …

interpreters/wamr: add compile role of WebAssembly

---

nshlib/nsh_script.c
system/nsh/nsh_main.c

This PR intends to add missing headers to files from `nshlib` and `system/nsh` .
These were being transitively included by the `userspace.h` header from `kmalloc.h`, which will be removed for not being required at the current point of inclusion.
No functional change, should have no impact.
CI build pass.

Include missing headers

---

system/cu/cu_main.c

Disable echo if it's enabled to avoid double input character
cu
VELA

system/cu: Disable echo if it's enabled to avoid double input character

---

Application.mk

Application: fix multiple main target mismatch during incremental compile
MAINSRC will fail to match with PROGNAME if one of main source is changed in incremental compilation
this PR will correct this issue.
N/A
ci check

Application: fix multiple main target mismatch during incremental compile

---

system/tcpdump/Kconfig
system/tcpdump/Make.defs
system/tcpdump/Makefile
system/tcpdump/tcpdump.c

Add a simple tcpdump command to capture pcap file from network traffic.
The captured file can be recognized by wireshark.
Note: needs https://github.com/apache/nuttx/pull/8753 for full feature, otherwise we may only capture some of the packets.
```shell
> tcpdump                                                                                        
Usage:                                                                                                                              
-i, --interface=interface      Capture device                                                                                     
-w file                        Path to dump file                                                                                  
-s, --snapshot-length=snaplen  Max dump length of …
```

apps/system: Add tcpdump command

---

nshlib/nsh_init.c

`netutils/netinit.h` was always included unconditionaly, regardless whether it was needed or not.
This causes some problems with projects without the need of netinit, or networking whatsoever.  
Sometimes, the apps repo is used partially, netutils may not even be available.
This PR makes sure that this file is included only when needed.
NSH can be build without dependency on netutils.
Build test.

nsh: Added conditional include of netinit.

---

nshlib/nsh_command.c

Forget to fix another place in https://github.com/apache/nuttx-apps/pull/1621, fix issue of builtin command list.
cmd help
VELA

nsh: Fix a potential buffer overflow in cmd help

---

sdr/.gitignore
sdr/Make.defs
sdr/Makefile
sdr/liquid_dsp/Kconfig
sdr/liquid_dsp/Make.defs
sdr/liquid_dsp/Makefile
sdr/liquid_dsp/config.h

Adding new group sdr (Software Defined Radio) with initial liquid-dsp library.
tbd

Adding sdr group with liquid-dsp library

---

netutils/nng/Kconfig
netutils/nng/Makefile

Switching to poll instead of epoll mechanism in NNG library, because PUB/SUB example doesn't work when epoll is used. This was not an issue a few months ago, thus regression testing on epoll and local socket implementation need to be done.
DIsabled mbedtls functionality in Makefile can be enabled, but then MBEDTLS_X509_CRL_PARSE_C macro must be defined in mbedtls_config.h also.
NNG library only.
Pub/Sub example

Using poll instead of epoll in NNG library

---

Directory.mk

since .kconfig is required to trigger the recursive processing
build system
CI

Directory.mk: Always generate and remove .kconfig

---

graphics/nxwidgets/src/ccallback.cxx
graphics/twm4nx/apps/ccalibration.cxx
graphics/twm4nx/apps/cclock.cxx
graphics/twm4nx/src/cinput.cxx
testing/ostest/roundrobin.c
wireless/ieee802154/i8sak/i8sak_main.c

Semaphore does not need set protocol, so remove sem_setprotocol code for semaphore.
NA
CI Pass

apps: remove unnecessary sem_setprotocol code

---

nshlib/nsh_vars.c

nsh_vars.c: In function 'nsh_setvar':
nsh_vars.c:285:3: error: incompatible implicit declaration of built-in function 'sprintf' [-Werror]
285 |   sprintf(pair, "%s=%s", name, value);
Fix build issue
CI pass

nshlib/nsh_vars.c: Add missing stdio.h

---

system/cle/cle.c

Fix https://github.com/apache/nuttx/issues/8731, don't rely on the vt100 to report
the cursor position.
This avoid the implicit input (response of get cursor command) during the user inputs.
Notice: This assume that the nsh prompt is always shown at line start.
cle
esp32c3-devkit:usbconsole with cle and lua

system/cle: Remove cle_getcursor()

---

system/ymodem/Kconfig
system/ymodem/Make.defs
system/ymodem/Makefile
system/ymodem/README.md
system/ymodem/rb_main.c
system/ymodem/sb_main.c
system/ymodem/ymodem.c
system/ymodem/ymodem.h

support ymodem, can use `sb` `rb` to send file and receive file
Noting
i test sb and rb in armv8-m borad, that run ok.
Compared with zmodem, ymodem is less prone to errors and has lower requirements on hardware.

support ymodem protocal and sb rb application

---

system/nxplayer/nxplayer_common.c

Previously, if the read bytes were less than the requested, the file was closed immediately. This behavior, however, does not consider the fact that the read operation may be blocking when no bytes are available at the moment. That is true for a named pipe (FIFO), for instance. Thus, reading it again lets to the underlying file system the decision of 1) blocking until bytes become available or 2) return 0 immediately (the case for actual files) or 3) read available bytes.
No impact on actual files: if the file has reached its end, the second `read` operation will return `0` and the file will be closed. 
It enables, however, using files that `read` may block to wait for new bytes to become available. That is the case for named pipes (FIFO).
Tested on ESP32-LyraT board using an actual file …

nxplayer: read file completely until 0 bytes are returned

---

interpreters/lua/.gitignore
interpreters/lua/Make.defs
interpreters/lua/Makefile

The tarball from github has same file layout as git repo while the tarball from ftp doesn't, so change URL to github
Update Makefile to accommodate this change.
No.
Local test and CI pass.

lua: download tarball from github release tag

---

netutils/ftpc/ftpc_connect.c

The timer is for connect timeout, but is not cancelled on connect error, then it may be triggered after ftpc quit and cause heap-use-after-free.
ftpc won't trigger heap-use-after-free on connect failure now.
Manually

netutils/ftpc: Cancel wdog on error state in ftpc_reconnect.

---

testing/ostest/Makefile
testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/wqueue.c

An ostest for https://github.com/apache/nuttx/pull/8832
The test consists of two parts:
- A tester that tries to trigger wrong states of work queue
- A verifier that checks whether the wqueue is still working properly
The tester is trying to queue and cancel work several times with priority lower/same/higher than the work queue.
Most wrong cases are likely to happen with high priority like:
- https://github.com/apache/nuttx/pull/8321
- If `cancel` never decreases semcount, the count may keep growing and finally overflow
- https://github.com/apache/nuttx/pull/8832
- If `cancel` is decreasing semcount too much, the `work_thread` may be waken up less times than expected
The lower/same priority testers are just added for covering other unexpected situations.
The verifier is trying to queue …

ostest: Introduce basic work queue test

---

netutils/iperf/iperf.c

netutils/iperf: guaranteed precision before division
Iperf test on photon/wlan
Before:
`   0.00-   1.08 sec      65536 Bytes    0.00 Mbits/sec`
After:
`   0.00-   1.04 sec      74970 Bytes    0.58 Mbits/sec`
N/A
photon/wlan

netutils/iperf: guaranteed precision before division

---

examples/adc/adc.h
examples/charger/Makefile
examples/fboverlay/Makefile
examples/flash_test/Makefile

fix error: Relative file path does not match actual file
Add missing Apache Foundation copyright header
none

apps: fix nxstyle

---

nshlib/Kconfig
nshlib/Makefile
nshlib/nsh.h
nshlib/nsh_alias.c
nshlib/nsh_command.c
nshlib/nsh_console.h
nshlib/nsh_parse.c

Add support for shell aliases into NSH. As a pre-requisite add support for single ('') and double ("") quotes as well. Note, this changes the parser behavior quite significantly so if ANY issues please let me know ASAP and I'll fix them at once.
Quite significant on the parser (the code is simplified somewhat IMO), adds new POSIX feature to the shell.
icicle:nsh, tried several happy cases and error cases. Everything seemingly works.

nsh/alias: Add shell alias support for NSH

---

interpreters/wamr/Kconfig

New option to dump call stack
WAMR only
QEMU

interpreters/wamr: New option to dump call stack

---

import/Make.defs

This pull request is paired with this [PR](https://github.com/apache/nuttx/pull/8870), from the Nuttx repository. It allows  LDELFFLAGS to be extended based on the target's definitions. 
An additional definition, `LDELFFLAGS` is added to the exported `Make.defs`  in the application repository `import/scripts/` directory. These flags are picked up with the additions from the above PR and used when building the application elf targets.
`$ cat import/scripts/Make.defs`
```
LDNAME           = ld-kernel32.script
LDELFFLAGS       = (flags from board Make.def, or toolchain)
```
I've tried this out on `rv-virt:knsh32` from #8643, the upstream `rv-virt:knsh64` as well as the vexriscv-smp port I'm working on `#8762`. However this PR may have wider implications.

tools/mkimport: Allow additions LDELFFLAGS from exported Nuttx builds.

---

industry/scpi/Make.defs

Fix compilation of SCPI library
Expose SCPI library API to application
SCPI parser APIs can be used
Code compiles locally

industry/scpi: fix compilation of SCPI library

---

nshlib/nsh_proccmds.c

- I noticed that the ps command shows the wrong format due to recent changes on sigmask length from 32bits to 64bits
```
Before:
nsh> ps
PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 000544  54.4%  CPU0 IDLE
1     1   1   0 FIFO     Kthread N-- Running            0000000000000000 001000 000664  66.4%  CPU1 IDLE
2     2   2   0 FIFO     Kthread N-- Running            0000000000000000 001000 000664  66.4%  CPU2 IDLE
3     3   3   0 FIFO     Kthread N-- Running            0000000000000000 001000 000664  66.4%  CPU3 IDLE
4     4 --- 192 RR       Kthread --- Waiting  Semaphore 0000000000000000 001992 000416  20.8%  hpwork 0x10824b44
5 …
```

nshlib: Fix the ps command format

---

nshlib/Kconfig
nshlib/README.md
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_syscmds.c

`boot [<image path> [<header size>]]`
Boot a new firmware image. This command depends on hardware support
CONFIG_BOARDCTL_BOOT_IMAGE. `<image path>` may point to a partion or file
which contain the firmware to boot. The optional, numeric argument
`<header size>` may be useful for skipping metadata information preprended
to the firmware image.
new nsh command
CI

nshlib: Add boot command

---

testing/ostest/cancel.c

Fixes an uninitialized variable in ostest (and stops the corresponding compiler warning).
Bug fix.
Build test.

 ostest: Fixed use of uninitialized variable.

---

nshlib/Kconfig
nshlib/README.md
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_syscmds.c

switchboot <image path>
Switch to the updated or specified boot system. This command depends on hardware support CONFIG_BOARDCTL_SWITCH_BOOT. `<image path>` point to a partion or file which contain the firmware to boot.
New nsh command
CI

nshlib: Add switchboot command

---

system/usbmsc/Kconfig

system/usbmsc: set stack size to DEFAULT_TASK_STACKSIZE
768 for stack is too small to work
Related PR on the NuttX side https://github.com/apache/nuttx/pull/8962
CI

system/usbmsc: set stack size to DEFAULT_TASK_STACKSIZE

---

testing/ostest/pthread_rwlock.c
testing/ostest/signest.c

Make sure that signets and pthread_rwlock tests are executed properly.
The issues has been found during working on https://github.com/apache/nuttx/pull/7464
`ostest` is even more reliable
Pass `sim:ostest`

testing/ostest: make sure that signets and pthread_rwlock tests are executed properly 

---

system/ramspeed/ramspeed_main.c

Fix the problem that "when repeat_num!=0, there is no break, so irq_disable will be configured to true by default".

system/ramspeed:Fix the problem that irq_disable is changed due to missing break

---

nshlib/nsh_parse.c

The logic that handles back-quotes was faulty, i.e. example command
set FOO `ls -l` would be split into two tokens as follows:
- set FOO `ls
- -l`
This results in nsh: `: no matching ` error, this fixes that issue.
Fix something I broke when shell aliases were introduced.
nsh> set FOO `ls -la`
nsh: `: no matching `
icicle:nsh

nsh/nsh_parse: Fix handling of back-quotes

---

netutils/iperf/iperf.c
netutils/iperf/iperf.h
netutils/iperf/iperf_main.c

Patches included:
- netutils/iperf: Use argtable's builtin glossary to print usage
- netutils/iperf: Split out sockaddr from general logic 
- netutils/iperf: Support local socket test 
- netutils/iperf: Support RPMsg socket test 
Usage:
```
iperf -s --local <path>
iperf -c <path> --local || iperf -c <whatever> --local <path>
iperf -s --rpmsg <name>
iperf -c <cpu> --rpmsg <name>
```
Note:
- Can combine with other options, e.g. `-u --local` will result in local UDP (DGRAM).
- RPMsg with SOCK_DGRAM (`-u`) doesn't have server mode (bind) yet, iperf may not work in this case before rpsock is enhanced.
- Need https://github.com/apache/nuttx/pull/9042 for RPMsg test.
Improve `iperf` functionality.
manually

netutils/iperf: Support local/RPMsg socket test

---

examples/pipe/interlock_test.c
examples/pipe/pipe_main.c
examples/pipe/redirect_test.c
examples/pipe/transfer_test.c

Adjust the test considering the [POSIX-compliant behavior of NuttX's FIFO](https://github.com/apache/nuttx/pull/8985) (`mkfifo`), which should block `open` for read-only and write-only when there are no writers or readers, respectively. This test's result is expected to be the same as any other POSIX-compliant system.
This commit also:
* Fix redirect test;
* Use pthread instead `task_create` to be able to run this test on POSIX-compliant systems;
* General fixes regarding formatting and error messages;
Test the POSIX-compliant implementation of NuttX's pipes.
Testing with `sim:citest` and on Linux.

apps/examples/pipe: check POSIX-compliant behavior of NuttX's FIFOs

---

nshlib/nsh_fscmds.c

When rm -r is passed with no address specified, it will automatically recursively unlink all files under the root path ('/') until unlinking to the mounted folder causes the unlink to fail. In this change, rm -r without a specified path will prompt for missing arguments

nshlib/nsh_fscmds.c:Add whether or not to pass in empty arguments when rm -r

---

graphics/twm4nx/src/cresize.cxx
graphics/twm4nx/src/ctwm4nx.cxx
netutils/ftpc/ftpc_transfer.c
netutils/ftpd/ftpd.c
system/critmon/critmon.c
system/stackmonitor/stackmonitor.c
system/zmodem/zm_receive.c

Similarly to [this](https://github.com/apache/nuttx/pull/9009), this PR fixes uses of `asprintf()` that their return value is not checked.
Potential bug fix.
CI only.

Fixes in asprintf usage.

---

system/adb/Kconfig
system/adb/adb_main.c

depends on https://github.com/apache/nuttx/pull/8964
unify the reset cause usage
CI

system/adb: Replace adb special reset cause with boardctl.h's value

---

testing/ostest/cancel.c
testing/ostest/cond.c
testing/ostest/pthread_rwlock.c
testing/ostest/robust.c
testing/ostest/sem.c
testing/ostest/wqueue.c

we need improve thread waiting strategy, if we don't do this ostest may fail, especially in smp
none
ostest

ostest:  fix smp ostest fail

---

system/iptables/iptables.c
system/tcpdump/tcpdump.c

Call arg_freetable before iptables/tcpdump exit.
Previously forget to free argtable before exit.
Avoid memleak.
manually

apps/system: Call arg_freetable before iptables/tcpdump exit

---

include/netutils/netlib.h
netutils/netlib/Makefile
netutils/netlib/netlib_setmtu.c
nshlib/README.md
nshlib/nsh_command.c
nshlib/nsh_netcmds.c

support to set MTU
N/A
Usage:ifconfig interfacename mtu ***
example:
ap> ifconfig eth0 mtu 1300
ap> ifconfig
eth0	Link encap:Ethernet HWaddr 42:de:09:1c:71:1e at RUNNING mtu 1300
inet addr:10.0.1.2 DRaddr:10.0.1.1 Mask:255.255.255.0
inet6 addr: fe80::40de:9ff:fe1c:711e/64
inet6 DRaddr: ::/64

nshlib/netcmds:support to set MTU

---

examples/cbortest/Kconfig
examples/cbortest/Make.defs
examples/cbortest/Makefile
examples/cbortest/cbortest_main.c
fsutils/libtinycbor/.gitignore
fsutils/libtinycbor/Kconfig
fsutils/libtinycbor/Make.defs
fsutils/libtinycbor/Makefile
fsutils/libtinycbor/fix_open_memstream.patch

Add TinyCBOR library (initially integrated by Lup Yuen: https://lupyuen.github.io/articles/cbor2 )
Users will be able to use CBOR library on NuttX
ESP32-DevkitC.
Please ignore code style issue caused by TinyCBOR CamelCase

Add TinyCBOR library and test example

---

include/wireless/wapi.h
wireless/wapi/src/wapi.c
wireless/wapi/src/wireless.c

Similarly to the `alg_flag` of the `wapi_psk_cmd` (which can be set by text), the new `ver_flag` is able to select the WPA version which will be sent to the Wi-Fi driver through the `IW_AUTH_WPA_VERSION` command. A new bit field (`IW_AUTH_WPA_VERSION_WPA3`) was created to indicate WPA3 is set.
It's up to the arch's Wi-Fi driver to implement handling of this new bit field and config the underlying driver to handle WPA3 on AP and/or STA mode. This implementation doesn't interfere with commonly used commands: 
`wapi psk wlan0 mypasswd 3` still selects CCMP algorithm and WPA2 and is equivalent to `wapi psk wlan0 mypasswd 3 WPA_VER_2` from now on.
One can use `wapi psk wlan0 mypasswd 3 WPA_VER_3` to set WPA3.
Please consider that `wapi` documentation and necessary flags were submitted in …

 wireless/wapi: support WPA3 on `wapi psk` command

---

examples/module/drivers/chardev/chardev.c

Please ignore the nxstyle false alarm:
```
apps/examples/module/drivers/chardev/chardev.c:43:46: error: Multiple data definitions
```
code refactor only
CI

examples/module: Add g_ prefix to chardev_fops

---

examples/etl/etl_main.cxx
examples/helloxx/helloxx_main.cxx

examples: Enable cxxinfo output if CONFIG_DEBUG_FEATURES is defined

---

netutils/rtptools/Makefile

The flag '-Wno-maybe-uninitialized' is not known by clang, so a workaround substitutes it for '-Wno-uninitialized' when clang is being used as C compiler.
Fixing [CI error](https://github.com/apache/nuttx/actions/runs/4856277612/jobs/8659303315?pr=9150#step:7:1676) of PR https://github.com/apache/nuttx/pull/9150
NuttX CI

apps/netutils/rtptools: fix warning while building with clang

---

nshlib/nsh_command.c

nsh: Fix the typo error cmd_swtichboot -> cmd_switchboot

---

system/spi/spi_common.c
system/spi/spi_exch.c

Extend SPI tool with support for 32-bit data width
Currently SPI tool only supports 8 and 16-bit width.
Tested on SPI driver with loopback enabled, successfully sent and received single and multiple words at 8, 16 and 32 bit widths.

spitool: add support for 32-bit SPI BUS width

---

examples/bmp280/Kconfig
examples/bmp280/Make.defs
examples/bmp280/Makefile
examples/bmp280/bmp280_main.c

Added BMP280 example to apps.
Currently, there is a BMP180/280 example which reads from _/dev/press0_. It is not compatible with BMP280 since the driver binds to _/dev/uorb/sensor_baro0_.
New example add to apps/example.
Tested on the BMP280 I2C sensor using a Tiva TM4C board. No issues noticed.

Added example for Bosch BMP280 pressure sensor

---

examples/adjtime/Kconfig
examples/adjtime/Make.defs
examples/adjtime/Makefile
examples/adjtime/adjtime_main.c

This application demonstrates the usage of adjtime() interface.
None, just new example application.
Tested on samv7 based board.

examples: add adjtime example application

---

netutils/dhcpc/dhcpc.c

add errno to help analyze possible causes of dhcp failures
device

dhcpc: adds errno to the dhcpc internal error

---

testing/ostest/pthread_rwlock_cancel.c

rwlock need to be destroy
none
ostest

ostest: rwlock need to be destroy

---

builtin/builtin_list.c
examples/flowc/flowc.h
examples/nettest/nettest.h
examples/tcpblaster/tcpblaster.h
examples/udp/udp.h
examples/webserver/webserver_main.c
graphics/nxwidgets/Doxygen/Doxyfile
graphics/nxwm/Doxygen/Doxyfile
include/graphics/curses.h

follow the coding style
code refactor
ci

Indent the include statement by two spaces

---

system/nxlooper/nxlooper_main.c

set default format as AUDIO_FMT_PCM for nxlooper.

nxlooper: set default format for nxlooper

---

include/logging/nxscope/nxscope.h
logging/nxscope/Kconfig
logging/nxscope/nxscope.c
logging/nxscope/nxscope_chan.c
logging/nxscope/nxscope_internals.c

- logging/nxscope: fix invalid zalloc size for rxbuf
- logging/nxscope: add an option to disable lock in channels put interfaces
With this option enabled the user can speed up adding a large amount of data to the stream buffer
by minimizing the usage of the nxscope lock interface:
nxscope_lock(&nxs->nxs);
nxscope_put_vfloat(&nxs, 0, data0, 1);
nxscope_put_vfloat(&nxs, 1, data1, 1);
nxscope_put_vfloat(&nxs, 2, data2, 1);
nxscope_put_vfloat(&nxs, 3, data3, 1);
nxscope_unlock(&nxs->nxs);
-  logging/nxscope: do not complete the stream frame if the previous send failed.    
In this case, the buffer already contains a frame ready to be send
examples/foc with enabled nxscope logging (not yet upstream)

logging/nxscope: various improvements

---

examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c
examples/foc/foc_thr.c
examples/foc/foc_thr.h

- examples/foc: add controller IDLE mode - useful for testing purposes
- examples/foc/foc_main.c: fix de-initialization sequence
- examples/foc: send messages only to active control threads
- examples/foc: add missing deinit calls
CI

examples/foc: various improvements

---

examples/mqttc/mqttc_pub.c
netutils/mqttc/0001_add_connection_status.patch
netutils/mqttc/Makefile

Fix MQTTC to wait for connection (MQTT ACK) and avoid passing '\0' in the payload
Users will get MQTTC example working with other MQTT Brokers like TagoIO
ESP32-Devkitc sending data to TagoIO

Fix MQTTC to wait for connection (MQTT ACK)

---

crypto/wolfssl/.gitignore
crypto/wolfssl/Kconfig
crypto/wolfssl/Make.defs
crypto/wolfssl/Makefile
crypto/wolfssl/README.md
crypto/wolfssl/user_settings.h

Add wolfSSL build files, allows wolfSSL to be cloned in and used quickly
Allows wolfSSL to be built into NuttX
Tested using wolfSSL tests in the NuttX simulator and on the STM32F746ZG, STM32H753 and STM32L552ZE

Wolfssl code back

---

testing/ostest/sem.c

ostest: sem need to be destroyed
none
ostest

ostest: sem need to be destroyed

---

testing/fdsantest/Kconfig
testing/fdsantest/Make.defs
testing/fdsantest/Makefile
testing/fdsantest/fdsantest_simple.c

Add fdsan unit test. Due to the current Nuttx not supporting death test, we removed death test from the original test cases of Android
none
none

add fdsan unit test

---

nshlib/nsh_ddcmd.c

nshlib: fix memory leak found out by -fanalyzer 
```bash
nsh_ddcmd.c: In function ‘cmd_dd’:
nsh_ddcmd.c:492:1: warning: leak of ‘dd.buffer’ [CWE-401] [-Wanalyzer-malloc-leak]
492 | }
| ^
‘cmd_dd’: events 1-14
|
|  294 | int cmd_dd(FAR struct nsh_vtbl_s *vtbl, int argc, FAR char **argv)
|      |     ^~~~~~
|      |     |
|      |     (1) entry to ‘cmd_dd’
|......
|  334 |   for (i = 1; i < argc; i++)
|      |               ~~~~~~~~
|      |                 |
|      |                 (2) following ‘true’ branch (when ‘i < argc’)...
|  335 |     {
|  336 |       if (strncmp(argv[i], "if=", 3) == 0)
|      |          ~            ~
|      |          |            |
|      |          |            (3) ...to here
|      |          (4) following ‘true’ branch...
|  337 |         {
|  338 | …
```

nshlib: fix memory leak found out by -fanalyzer 

---

.github/workflows/build.yml

CI currently runs with the warning:
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
The is the apps version of https://github.com/apache/nuttx/pull/9289
Passing CI should be sufficient to verify we are still pulling the correct source references for the two repos.

CI: set-output command is deprecated

---

nshlib/Kconfig
nshlib/nsh_session.c

If ```CONFIG_NSH_DISABLE_ECHOBACK``` is selected, the NSH disables echoback prompt.
I needed this changes to use ```nsh``` like a AT-command based modem.

nshlib: Add support for disabling echoback

---

examples/foc/Kconfig
examples/foc/Makefile
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_main.c
examples/foc/foc_nxscope.c
examples/foc/foc_nxscope.h
examples/foc/foc_thr.c
examples/foc/foc_thr.h

- examples/foc/foc_thr: fix mutex logic
- examples/foc/foc_thr: get controller type from controller ID
- examples/foc: add real time data capture with the NxScope library
It's now possible to capture controller data easily and then visualizing them. Useful for controller tuning and debugging.
Tested with nxscope client https://github.com/railab/nxscli
Data stream on UART works fine.
Data stream on full-speed CDCACM device adds too much uC overload which breaks FOC control loops and is not recommended (usbdev full-speed packet limit is too small). High-speed CDCACM should be more practical, but I don't have proper hardware to test.

examples/foc: add real time data capture with nxscope lib

---

Application.mk

tools: Disable wasm build if toolchain not found
Fix #1751 
wasm build only

tools: Disable wasm build if toolchain not found

---

nshlib/nsh_command.c
nshlib/nsh_mmcmds.c

support memdump can dump by seq number
memdump
nsh with mm_backtrace = 8

support memdump can dump by seq number

---

netutils/netlib/netlib_setipv4dnsaddr.c

In `dns_add_nameserver`, the `dns_check_nameserver` is comparing addresses with `addrlen = sizeof(struct sockaddr_in)` for IPv4 addresses, so the trailing `sin_zero` field should be `0`, otherwise it may fail to figure out same nameserver address.

netlib: set addr.sin_zero to 0 in netlib_set_ipv4dnsaddr

---

testing/ostest/cond.c

cond and mutex need to be destroyed
none
ostest

ostest/cond_test: cond and mutex need to be destroyed

---

system/coredump/Kconfig
system/coredump/Make.defs
system/coredump/Makefile
system/coredump/coredump.c

sabre-6quad/coredump: add coredump config to enable ci check
tools/coredump: add coredump python parser
sched/misc: add coredump support on assert
elf/coredump: add support of dump task stack without memory segments
stream/hexdump: add hexdump stream to dump binary to syslog
1. Build config coredump:
```
$ ./tools/configure.sh ./boards/arm/imx6/sabre-6quad/configs/coredump
$ make
```
2. Run qemu and get the coredump snapshot:
```bash
$ qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -nographic -kernel ./nuttx -s
ABCDGHIJKNOPQ
nsh> coredump
[CPU0] [ 6] Start coredump:
[CPU0] [ 6] 5A5601013D03FF077F454C4601010100C0000304002800C00D003420036000070400053400200008200A4000000420030034C024200001D8092004E00200601A
[CPU0] [ 6] …
```

system/coredump: add coredump tool to capture system status

---

tools/Wasm.mk

For example, before this patch, object file is like:
```
apps/examples/hello/hello_main.wo
```
With this patch, it will be:
```
apps/examples/hello/hello_main.c.home.huang.Work.nx.apps.examples.hello.wo
'''
Follow the native build:
'''
apps/examples/hello/hello_main.c.home.huang.Work.nx.apps.examples.hello.o
```
Minor

tools/Wasm.mk: Generate object file name with full path

---

system/nxdiag/nxdiag.c
tools/host_sysinfo.py

Requires apache/nuttx#9400.
Fix compilation issues introduced in #1776 by removing the non-existent info.h.
Fix compilation error when enabling the Nxdiag application.
Tested using ESP32-DevKitC

system/nxdiag: Fix issues introduced by #1776

---

include/netutils/dhcpd.h
netutils/dhcpd/dhcpd.c

Add some interface to configure DHCP daemon.
Currently the parameters of DHCPD is configured static via kconfig. This PR is to add some interfaces for some of the parameters (startip, netmask, router, dns ip) as these parameters are need be configured dynamically
Only add the interface to overwite the default configurations defined in kconfig. If no one call these interface, the definiations in kconfig still used.
update example apps with setting interface called before `dhcpd_start()` called, the DHCP can assign ip address and others as expected.

Add interface to configure DHCP daemon

---

nshlib/nsh_command.c

nshlib/command: exclude usage to reduce data size
Test on sim/nsh (CONFIG_NSH_DISABLE_HELP=y):
```bash
text	   data	    bss	    dec	    hex	filename
393746	  26824	   4000	 424570	  67a7a	nuttx     /* before */
391858	  26440	   4000	 422298	  6719a	nuttx     /* after */
-1888    -384
```
N/A
sim/nsh

nshlib/command: exclude usage to reduce data size 

---

system/cu/Kconfig
system/cu/cu_main.c

system/cu: disable error print if SYSTEM_CUTERM_DISABLE_ERROR_PRINT enabled
Test on sim/nsh (CONFIG_SYSTEM_CUTERM_DISABLE_ERROR_PRINT=y):
text    data     bss     dec     hex filename
397049   26704    4128  427881   68769 nuttx      /* before */
396481   26704    4128  427313   68531 nuttx      /* after */
-568
N/A
sim/nsh

system/cu: disable error print if SYSTEM_CUTERM_DISABLE_ERROR_PRINT enabled

---

wireless/bluetooth/btsak/README.md
wireless/bluetooth/btsak/btsak.h
wireless/bluetooth/btsak/btsak_gatt.c
wireless/bluetooth/btsak/btsak_main.c
wireless/bluetooth/btsak/btsak_scan.c
wireless/bluetooth/btsak/btsak_security.c

Currently the help messages use "private" string while code expects "random".
Remove not needed `(CODE void *)` cast.
Use 'nitems' macro to calculate number of elements in array Align output in `btsak_cmd_scanget` command.
Fix style issues
Should be none
Pass CI
Tested with `btsak` application on ESP32

wireless/bluetooth/btsak: fix help messages

---

testing/ostest/Makefile
testing/ostest/cancel.c
testing/ostest/ostest_main.c
testing/ostest/pthread_rwlock_cancel.c

testing/ostest: adjust PTHREAD_CLEANUP_STACKSIZE with nuttx project
in project nuttx "remove PTHREAD_CLEANUP, and use PTHREAD_CLEANUP_STACKSIZE to enable or disable interfaces pthread_cleanup_push() and pthread_cleanup_pop()", apps project also needes adjust code.
Kconfig
CI, need merge with https://github.com/apache/nuttx/pull/9527

testing/ostest: adjust PTHREAD_CLEANUP_STACKSIZE with nuttx project

---

nshlib/nsh_usbconsole.c

nsh_usbconsole.c: add support for NSH console over composite device
nrf52840-dongle

nsh_usbconsole.c: add support for NSH console over composite device

---

netutils/dhcpc/Kconfig
netutils/dhcpc/dhcpc.c

Socket binded to `INADDR_ANY` is not intended to receive unicast traffic before being fully configured, at least dhclient configured with socket-only won't do so on Linux and BSDs (https://github.com/isc-projects/dhcp/blob/v4_4_3/common/socket.c#L1201).
We can sometimes receive unicast traffic before being fully configured, it's good, but not always, so we need to set the broadcast flag under some situations.
dhcpc with `CONFIG_NET_IPFORWARD=y`

netutils/dhcpc: Set BOOTP BROADCAST flag when IPFORWARD is enabled

---

netutils/iperf/iperf.c

Fix the floating point precision issue when calculating data in the iperf cycle, to prevent abnormal bandwidth display caused by this.
None
bl616evb:wifi

netutils/iperf: Fix possible precision loss

---

examples/watcher/watcher_main.c
testing/ostest/waitpid.c

from the comment: https://github.com/apache/nuttx/pull/9564#discussion_r1233425912
minor
ci

Remove the unnecessary cast from pid_t to int

---

wireless/bluetooth/btsak/Kconfig

bluetooth/btsak: add dependency on WIRELESS_BLUETOOTH_HOST=y
CI

bluetooth/btsak: add dependency on WIRELESS_BLUETOOTH_HOST=y

---

Application.mk
Directory.mk

When rebuilding, it's not really useful to see reams of "Nothing to be done for" for every application being built. This change attempts to silence these messages.
Stops make spitting out "nothing to be done.." messages for each target of every application. These can be distracting, when a large number of applications are enabled.
With 5 registered applications.
Before the change:
```
$ make import --no-print-directory -j16
cc  -O2 -Wall -Wstrict-prototypes -Wshadow -DHAVE_STRTOK_C=1 nuttx/apps/import/tools/incdir.c -o "nuttx/apps/import/tools/incdir"
make[3]: Nothing to be done for 'context'.
make[3]: Nothing to be done for 'context'.
make[3]: Nothing to be done for 'context'.
LN: platform/board to /path/to/xx
make[3]: Nothing to be done for 'context'.
make[3]: Nothing to be done for …
```

mk: Attempt to silence "Nothing to be done for xx" messages.

---

system/ramspeed/ramspeed_main.c

Allocates the read and write buffers used from ramspeed on the heap.
This change makes it much easier to use the ramspeed test in BUILD_KERNEL, as one does not need to know which virtual address is safe to use.
Using ramspeed in conjunction with BUILD_KERNEL is easier.
arty_a7:knsh with `CONFIG_SYSTEM_RAMSPEED=m`
```
nsh> ramspeed -a -s 4096
______memcpy performance______
______Perform 32 Bytes access ______
RAM Speed: Time-consuming is too short, please increase the <repeat number>
RAM Speed: Time-consuming is too short, please increase the <repeat number>
______Perform 64 Bytes access ______
RAM Speed: Time-consuming is too short, please increase the <repeat number>
... more results follow.
```

system/ramspeed: Allow read and write buffers to be allocated from the heap.

---

nshlib/nsh_ddcmd.c

Increases the maximum sector size, and number of bytes that can be transferred with DD.
On some systems, using sector sizes larger than 65536 is needed for profiling performance or testing.
Can now use DD with sector size > 65536.
arty_a7:knsh.
Example usage also in [#9080](https://github.com/apache/nuttx/issues/9080) (from Nuttx)

nshlib/dd: Increase the integer width for sector size in dd.

---

Application.mk

When archiving, if the number of files is large, the full path in SUFFIX may exceed the command line limit for Cygwin and other
programs. To avoid this, the SUFFIX can be changed in the Makefile in each application or library.
No impact since existing Makefiles do not have SUFFIX overrides.
Build check

Change the way of definition of SUFFIX

---

examples/nimble/Kconfig
examples/nimble/Make.defs
examples/nimble/Makefile
examples/nimble/nimble_main.c
wireless/bluetooth/nimble/Kconfig
wireless/bluetooth/nimble/Makefile
wireless/bluetooth/nimble/Makefile.nimble
wireless/bluetooth/nimble/include/logcfg/logcfg.h
wireless/bluetooth/nimble/include/syscfg/syscfg.h

- nimble: make nimble porting example optional
Enabled by default for the moment to avoid CI errors
- nimble: improve integration with NuttX
1. add Makefile.nimble that helps integrate NimBLE with custom applications
To enable NimBLE for an custom application, user needs to include Makefile.nimble in the app's Makefile:
include $(APPDIR)/wireless/bluetooth/nimble/Makefile.nimble
2. add NuttX specific syscfg.h
- file based on nimble/porting/examples/nuttx/include/syscfg/syscfg.h
- all unnecessary definitions was removed
- definitions are configurable from Kconfig
3. add NuttX specific logcfg.h
- bind NimBLE logging with debug.h macros
- examples: add NimBLE example, based on nimble/porting/examples/nuttx
It's better to keep this example as part of nuttx-apps instead of relying on an …

nimble: various improvements for nimble intergartion

---

system/nxdiag/Makefile
system/nxdiag/nxdiag.c
tools/host_sysinfo.py

Adds the currently used ESP HAL version to NXdiag's output.
Also refactor some portions of the code.
New information for NXdiag.
Tested on ESP32-C3-DevKitC

system/nxdiag: Add Espressif's HAL version

---

testing/ostest/Makefile
testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/pthread_exit.c

Add a minimal test to assure that pthread_self() and pthread_exit() work correctly when called from the main thread.
None expected.  Worst case would be an OS test failure
sim/ostest
Test result:
1. Test has to run in a separate task because it will exit.
pthread_exit_test:  Starting pthread_exit_main at PID=183
2. Test logic a) starts the pthread_exit_thread, b) waits 5 seconds and then c) calls pthread_exit()
a) pthread_exit_main 183: Starting pthread_exit_thread
b) pthread_exit_main 183: Sleeping for 5 seconds
3. Process does not terminate (correct) and pthread_exit_thread is started
4. The pthread_exit_thread d) sleeps for 5 seconds, then e) 5 more seconds, then f)  implicitly calls pthread_exit()
d) pthread_exit_thread 189: Sleeping for 10 second
c) pthread_exit_main 183: Calling …

Add small test of pthread_exit()/pthread_self() on main thread.

---

import/Make.defs

Allows board configuration to select the output ELF format for applications built using the `make import` target.
This PR should be paired with [#9635](https://github.com/apache/nuttx/pull/9635), from the NuttX main repository.
The format of application ELFs built through `make import` can be set by board configuration.
Copied from [#9635](https://github.com/apache/nuttx/pull/9635):
```
$ cd nuttx
$ ./tools/configure.sh arty_a7:knsh
$ make
$ make export
$ cd ../apps
$ ./tools/mkimport.sh -z -x ../nuttx/nuttx-export-*.tar.gz
$ make import
$ riscv64-unknown-elf-readelf -a bin/init | grep Type:
Type:                              EXEC (Executable file)
$ cd nuttx
$ ./tools/configure.sh rv-virt:knsh32:knsh
$ make
$ make export
$ cd ../apps
$ ./tools/mkimport.sh -z -x …
```

import/mk: Update ELF flags to represent build configuration type.

---

tools/mkimport.sh

The `make export` target from the Nuttx repository correctly packs the System.map file. This change ensure that ./tools/mkimport.sh extracts this file correctly into the `import`correctly.
The `System.map` file is now available in the import directory for applications to build against.
```
$ cd nuttx
$ ./tools/configure.sh rv-virt:knsh32:knsh
$ make
$ make export
$ cd ../apps
$ ./tools/mkimport.sh -z -x ../nuttx/nuttx-export-*.tar.gz
$ ls import
include  libs  Make.defs  Makefile  scripts  startup  System.map  tools
```
Notice the addition of the `System.map` file.

tools/mkimport: Add system map to mkimport script.

---

netutils/rexec/Kconfig
netutils/rexecd/Kconfig

Close apache/nuttx#9642.
Warn users about cleartext password transmission of rexec.

rexec: warn users about cleartext password transmission

---

system/libuv/Makefile

CC:  pthread/pthread_mutexinconsistent.c libuv/src/unix/getaddrinfo.c:103:9: warning: implicit declaration of function ‘getaddrinfo’; did you mean ‘uv_getaddrinfo’? [-Wimplicit-function-declaration]
103 |   err = getaddrinfo(req->hostname, req->service, req->hints, &req->addrinfo);
|         ^~~~~~~~~~~
|         uv_getaddrinfo
libuv/src/unix/getaddrinfo.c: In function ‘uv_freeaddrinfo’:
libuv/src/unix/getaddrinfo.c:222:5: warning: implicit declaration of function ‘freeaddrinfo’; did you mean ‘uv_freeaddrinfo’? [-Wimplicit-function-declaration]
222 |     freeaddrinfo(ai);
|     ^~~~~~~~~~~~
|     uv_freeaddrinfo
CC:  misc/lib_crc16ccitt.c libuv/src/unix/getnameinfo.c: In function ‘uv__getnameinfo_work’:
libuv/src/unix/getnameinfo.c:45:9: warning: implicit declaration of function …

libuv: fix compile warning

---

interpreters/wamr/Kconfig

New option for configurable bounds checks, works with https://github.com/bytecodealliance/wasm-micro-runtime/pull/2289
New option
CI and local macine

interpreters/wamr: New option for configurable bounds checks

---

boot/miniboot/Kconfig
boot/miniboot/Make.defs
boot/miniboot/Makefile
boot/miniboot/miniboot_main.c

- boot: add support for a minimal NuttX-based bootloader
This can be useful for development purposes when you don't need any complex bootloader yet,
but just want to jump to the app image.
Can be helpful when we need to switch from secure environment to non-secure environment.
nrf9160: boot from secure bootlaoder to non-secure app

boot: add support for a minimal NuttX-based bootloader

---

examples/module/module_main.c
examples/posix_spawn/spawn_main.c
examples/thttpd/thttpd_main.c
netutils/thttpd/thttpd.c
netutils/thttpd/thttpd_cgi.c
nshlib/nsh_init.c

follow up the change in nuttx side: https://github.com/apache/nuttx/pull/9671
minor
ci

Remove the const cast from the initialization of boardioc_symtab_s::symtab

---

CMakeLists.txt

apps/cmake: add some note on cmake header
```
| # Important note:
| # This CMakeLists.txt is not meant as a top-level CMakeLists.txt. Instead, | # CMake must be run using the top-level CMakeLists.txt from the nuttx | # repository and point to this directory via NUTTX_APPS_DIR. For example:
| #   cmake -S <nuttx-dir> -B <build-dir> [...] -DNUTTX_APPS_DIR=<apps-dir>
```
N/A
ci-check

apps/cmake: add some note on cmake header

---

include/netutils/xtables.h
netutils/iptables/Kconfig
netutils/iptables/Make.defs
netutils/iptables/Makefile
netutils/iptables/xtables.c

Add xtables.c and xtables.h
In order to support the compilation of third-party utils, we encounter some situations where the macro is not defined, refer to the common implementation of other systems, add relevant definitions and empty function.
sim:local

iptables: add iptables libary

---

system/gdbstub/Kconfig
system/gdbstub/Make.defs
system/gdbstub/Makefile
system/gdbstub/gdbstub.c

Partially implement the gdb rsp protocol,
you can debug the nuttx kernel through the serial port or the network
support gdbstub app
debug
stm32f429i-disco:gdbstub
run `gdbstub -d /dev/ttyS1 &` on nsh
then use gdb to connet board
```
$ arm-none-eabi-gdb nuttx -ex "set target-charset ASCII" -ex "set print pretty on" -ex "set remotelogfile gdb.log"  -ex "set serial baud 115200" -ex "target remote /dev/ttyUSB1"
GNU gdb (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.1.90.20221210-git
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB …
```

gdbstub:Support a general gdbstub, support serial port and network link

---

examples/pwm/pwm_main.c

This commit fixes the overflow that happens when setting the duty cycle to 100% in the PWM example.
It now correctly passes to the lower level the value `0xffff` rather than `0x0000` when setting the duty cycle to 100 and makes sure that no underflow happens when setting the duty cycle to 0.
Correct handling of the duty cycle range in the PWM example.
`esp32c3-devkit:pwm`

examples/pwm: Fix duty cycle overflow

---

testing/ostest/pthread_exit.c

testing/ostest: fix Compiler Warning (level 1) C4716: 'function' must return a value
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4716?view=msvc-170
N/A
ci-check

testing/ostest: fix Compiler Warning (level 1) C4716: 'function' must return a value

---

Application.mk

Provide a method to build wasm app only, by define a variable WASM_BUILD_ONLY 
Build system

tools: Don't register app into nsh if WASM_BUILD_ONLY == y

---

boot/mcuboot/CMakeLists.txt
boot/miniboot/CMakeLists.txt
examples/mcuboot/CMakeLists.txt
examples/mcuboot/slot_confirm/CMakeLists.txt
examples/mcuboot/swap_test/CMakeLists.txt
examples/mcuboot/update_agent/CMakeLists.txt

cmake: add support for boot utils
mcuboot examples depends on https://github.com/apache/nuttx/pull/9820 to build correctly
nrf52/nrf91

cmake: add support for boot utils

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_fscmds.c

In this modification, we can use fdinfo to get all the fd information, or specify the PID (e.g. fdinfo 11) to get the fd information of the target process

nshlib: Add fdinfo to get information about the process associated fd

---

testing/ostest/CMakeLists.txt
testing/ostest/Makefile
testing/ostest/dev_null.c
testing/ostest/ostest.h
testing/ostest/ostest_main.c

report here: https://github.com/apache/nuttx/pull/9837#issuecomment-1637282337
ostest
ci

ostest: Skip test_dev_null when CONFIG_DEV_NULL isn't enabled

---

system/nxdiag/Makefile

This commit fixed a race condition that might happen by only unshallowing the Espressif HAL only after it was completely cloned.
This is done by checking the `.git/index` file of the HAL repository.
Correct compilation behavior of NXdiag.
ESP32-C3-DevKitC

system/nxdiag: Fix race condition during build

---

Application.mk

Move Wasm.mk to end of file since it need definition from Application itself.
Wasm build only

Move Wasm.mk to end of file since it need definition from Application

---

testing/ostest/rmutex.c

ostest/rmutex: mutex need to be destroyed
none
none

ostest/rmutex: mutex need to be destroyed

---

audioutils/fmsynth/CMakeLists.txt
audioutils/mml_parser/CMakeLists.txt
audioutils/nxaudio/CMakeLists.txt
benchmarks/coremark/CMakeLists.txt

cmake: add support for audioutils and coremark.
coremark has passed verification with stm32/nucleo-g431rb

cmake:migrate apps CMakeLists for [audioutils benchmarks]

---

LICENSE
crypto/tinydtls/.gitignore
crypto/tinydtls/CMakeLists.txt
crypto/tinydtls/Kconfig
netutils/wakaama/.gitignore
netutils/wakaama/CMakeLists.txt
netutils/wakaama/Kconfig
netutils/wakaama/examples.cmake

- crypto: add Eclipse tinydtls support
- netutils: add Eclipse Wakaama support
only CMake build supported
sim and nrf9160-dk

add support for tinydtls and wakaama

---

system/uorb/listener.c

Support frequency less than 1hz
daily test

system/uorb: Support frequency less than 1hz

---

nshlib/nsh.h

"rptun" and "pmconfig" depend on "NSH_HAVE_FOREACH_DIRENTRY"

Fix dependents of nsh_foreach_direntry

---

netutils/rexec/rexec.c
netutils/rexecd/rexecd.c
system/popen/popen.c

1. support popen in "r+ w+" mode
2. supports remote execution and interaction
1. The standard popen uses the pipeline internally, so the stream returned by it can only support read-only or write-only. Now this PR is expanded through sockpair, which can support both read and write. Therefore, we can use the stream to read and write access this task (posix_spawn).
2. Using the above features, rexec can interact with the remote service on the command line, supporting input and output until the local voluntarily exits or the remote service ends
daily test
rexec + nxplayer

netutils/rexec/rexecd: Supports remote execution and interaction

---

system/ymodem/rb_main.c
system/ymodem/sbrb.py
system/ymodem/ymodem.c

ymodem:Fix bugs and improve the usage of python scripts
1.Timeout processing
2.clear error count when received successfully once
3.fix the bug of insufficient header memory application
ymodem
esp32s3:nsh with mincom sbrb.py

ymodem:Fix bugs and improve the usage of python scripts

---

examples/thttpd/thttpd_main.c
examples/unionfs/unionfs_main.c

since unionfs_mount isn't exported through syscall
code refactor
sim:unionfs

examples: Change unionfs_mount to mount

---

examples/sotest/Kconfig
examples/sotest/sotest_main.c

1. remove unnecessary config EXAMPLES_SOTEST_DEVPATH
2. fix issue about running multiple times
daily test

examples/sotest: remove unnecessary config and fix minor issue

---

nshlib/nsh_ddcmd.c

before:
infile sector 0
```
7f454c46010101000000000000000000
02002800010000007d13001834000000
8cbd2a00000400053400200004002800
```
now:
infile sector 0:
```
0000: 7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 .ELF............ 
0010: 02 00 28 00 01 00 00 00 7d 13 00 18 34 00 00 00 ..(.....}...4... 
0020: 8c bd 2a 00 00 04 00 05 34 00 20 00 04 00 28 00 ..*.....4. ...(.
```

nshlib: refine dd verify printing format

---

tools/Wasm.mk

shell in makefile will not report error even if $WCC exited with failure.
Build would be break if wasm module build failed.

tools: Raise error if wasm module build failed

---

testing/ostest/sigprocmask.c

fix ostest sigprocmask testcase
problem: signal "SIGSTOP" and "SIGKILL" shouldn't be in sigprocmask

ostest: sigprocmask testcase fix

---

.gitignore
testing/nist-sts/0001-Solve-the-memory-out-of-bounds-problem-in-sts.patch
testing/nist-sts/0002-Fix-bug-that-crash-in-running-a-single-test-after-ru.patch
testing/nist-sts/Kconfig
testing/nist-sts/Make.defs
testing/nist-sts/Makefile

NIST-Statistical-Test-Suite for testing random-number generators

testing/nist-sts: porting NIST-Statistical-Test-Suite

---

system/ofloader/Kconfig
system/ofloader/Make.defs
system/ofloader/Makefile
system/ofloader/ofloader.c
system/ofloader/ofloader.h
system/ofloader/segger.c

support openflashloader for nuttx
wiki:https://wiki.segger.com/SEGGER_Flash_Loader
If the nuttx driver supports it, we can flash any firmware through openflashloader
stm32f429i-disco with internal flash
Details:[nuttx-9962](https://github.com/apache/nuttx/pull/9962)
Please ignore "error: Mixed case identifier found" since some symbols defined by Segger are mix case.

support openflashloader for nuttx

---

boot/mcuboot/CMakeLists.txt
boot/mcuboot/Kconfig
boot/mcuboot/Makefile

Older versions of mcuboot did not support swap using move and therefore the build would have failed CONFIG_MCUBOOT_SWAP_USING_MOVE=y.
Newer mcuboot contains initial support of swap using move for NuttX. Also Makefile was updated to as some bootutil files were removed from mcuboot.
Updates MCUboot and because of deletion of some files older versions will not compile.
Tested on SAMv7 MCU.

mcuboot: update mcuboot to support swap using move

---

examples/usrsocktest/usrsocktest_wake_with_signal.c

When the value of the signal is modified, the function will be faulty
sim:local

usrsocktest: correct the parameter when pthread_kill is called

---

system/memstress/Kconfig
system/memstress/Make.defs
system/memstress/Makefile
system/memstress/memorystress_main.c

A new memory stress testing tool

memorystress:For pressure detection of memory stability

---

testing/nist-sts/Makefile

fix compile warning as following:
nist-sts/sts/src/cusum.c:15:23: warning: 'zerv' may be used uninitialized in this function[-Werror=maybe-uninitialized]

testing/nist-sts: fix -Wmaybe-uninitialized compile warning

---

testing/ostest/CMakeLists.txt
testing/ostest/Makefile
testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/prioinherit.c
testing/ostest/schedlock.c

This test helps to verify that scheduler lock/unlock functionality is working as expected.
Currently there is a bug, so test fails.
More test coverage
The test pass if https://github.com/apache/nuttx/pull/7464 is applied

testing/ostest: add test case for task priority change with locked scheduler

---

system/adb/Kconfig
system/adb/adb_main.c

support adb boardctl when not composite device.
adbd
sim:usbdev

adb: support adb boardctl when not composite device

---

include/system/nxplayer.h
system/nxplayer/CMakeLists.txt
system/nxplayer/Makefile
system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_sbc.c

Usage:
device /dev/audio/compress0p
play /data/test.sbc
This function requires the platform to support compress decoding and playback

nxplayer:add sbc simple parser in nxplayer

---

examples/fb/fb_main.c

For screens with transparency, the alpha value should be set to 0xFF

apps/examples: fix fb example show error

---

system/i2c/i2c_hexdump.c
system/i2c/i2c_main.c
system/i2c/i2c_reset.c

Add function missing FAR information

Add function missing FAR information

---

examples/mtdpart/mtdpart_main.c

fix a compiling warning.
printf compiling warning only.
Compiled Okay.

examples/mtdpart:fix compiling warning in printf.

---

system/coredump/Kconfig

coredump/priority: Increase the default priority of coredump to 254
Increase coredump priority to avoid unnecessary task switch during dump
N/A
coredump

coredump/priority: Increase the default priority of coredump to 254

---

testing/ostest/mutex.c

mut need to be destroyed
none
none

ostest/mutex: mut need to be destroyed

---

testing/drivertest/drivertest_watchdog.c
tools/mkkconfig.sh

testing/drivertest: add watch dog irq test

---

nshlib/nsh_command.c

Inconsistent table sizes may lead to stack buffer overflow

nsh: fix a buffer overflow in help

---

include/system/nxcamera.h
system/nxcamera/nxcamera.c

Since the current fb display format of vela qemu is rgb565, it is necessary to convert the frame obtained by v4l2 to rgb565
please ignore ConvertToXxxx function defined by libyuv.
nxcamera support more video format
with https://github.com/apache/nuttx/pull/10118

nxcamera: Add logic to convert to rgb565

---

include/system/nxlooper.h
include/system/nxplayer.h
include/system/nxrecorder.h

resolve compilation errors: '%0lx' directive output may be truncated writing between 1 and 16 bytes into a region of size 11 [-Werror=format-truncation=]
ci

audio:Resolve compilation errors in nxplayer/nxrecorder/nxlooper on ARM64

---

system/dd/Kconfig
system/dd/Make.defs
system/dd/Makefile
system/dd/dd_main.c

enabling SYSTEM_DD will disable nsh_dd by selecting NSH_DISABLE_DD
Somtime we need do read/write on filesystem to evaluate the stack usage. 
Use the original nsh dd, the nsh used stack, such as nsh_parse_command/nsh_execute, will be counted in.
So provide this stand alone version dd.
N/A

system: dd: add standalone dd command

---

system/adb/Makefile
system/adb/adb_banner.c
system/adb/adb_main.c
system/adb/logcat_service.c

Add adb log level prevent mistakenly printing INFO messages.
depends on https://github.com/spiriou/microADB/pull/35
adb
bes board

adb: add adb log level

---

system/uorb/sensor/gps.c
system/uorb/sensor/topics.c

fix uorb of g_sensor_list error.
1. uorb/sensor/gps: fix uorinfo_raw print error
2. uorb/topics: update delicated match of listener topics
only output of sensor_gps_satellite formated.
when user input "sensor_gps_sat" which does not exist in g_sensor_list, sensor_gps will not give as output.
Pass Vela CI.

Uorb: fix format and g_sensor_list error in sensor gps and its topics

---

system/uorb/sensor/force.c
system/uorb/sensor/force.h
system/uorb/sensor/topics.c
testing/sensortest/sensortest.c

A sensor of this type measures the force on it, and additionally compares the force with one or more specified thresholds. The sensor can output the force value directly. Moreover, it's usually applied as a press key. In that case, when it detects a force greater than some given threshold, a corresponding event is reported.

sensor: add force sensor

---

Application.mk
Make.defs
builtin/Makefile
testing/ltp/Makefile

define a macro for split long variable and redefine variable in batch. 
see details in `apps/Make.defs` `SPLITVARIABLE`.
replace the variable reference that caused the error.
Make.dep generation, builtin apps
ltp cases

Enhance Makefile to avoid "Argument list too long"

---

testing/drivertest/Makefile
testing/drivertest/drivertest_watchdog.c

watchdog test

---

testing/batterydump/Kconfig
testing/batterydump/Make.defs
testing/batterydump/Makefile
testing/batterydump/batterydump.c

```
armv8a> batterydump -h
batterydump -h
batterydump [arguments...] <command>
[-h      ]  batterydump commands help
[-t   val]  0:charger 1:gauge 2:monitor
[-f      ]  poll the battery state and dump
command:
<batttery_node_name> ex:/dev/charge/goldfish_battery
armv8a> 
```
```
armv8a> batterydump -f -t 1 /dev/charge/goldfish_battery
batterydump -f -t 1 /dev/charge/goldfish_battery
state:2, online:0, vol:5.000000, capacity:71%,current:900.000000, temperature:25.000000
```

add batterydump tool for dump the battery info

---

examples/watcher/task_mn.c
examples/watcher/task_mn.h

Get the thread name using pthread_getname_np
note/ram devices will remove the NOTERAM_GETTASKNAME method

examples/watcher: get the thread name using pthread_getname_np

---

system/nxcamera/nxcamera.c

```
CC:  nxcamera.c nxcamera.c: In function 'show_image': nxcamera.c:85:20: error: initialization of 'uint32_t *' {aka 'unsigned int *'} from incompatible pointer type 'uint8_t *' {aka 'unsigned char *'} [-Werror=incompatible-pointer-types]
85 |   uint32_t *pbuf = pcam->bufs[buf->index];
|                    ^~~~
cc1: all warnings being treated as errors
```
please ignore:
```
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/system/nxcamera/nxcamera.c:72:13: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/system/nxcamera/nxcamera.c:89:17: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/system/nxcamera/nxcamera.c:115:16: error: Mixed case identifier found
Error: …
```

nxcamera: Solve compilation errors caused by type mismatch

---

testing/drivertest/drivertest_uart.c

Made by:
```
commit 5659906fdfdac0a363aecb329c39c936324dcc55
Author: Gregory Nutt <gnutt@nuttx.org>
Date:   Fri Mar 24 12:02:04 2023 -0600
Changes to apps needed by nutts PR 8885
needby:965551
ostest contains some logic that depends on internal implementation of signal sets and ostest must be updated to match those changes.
There is no particular impact from this PR.  This PR is the result of impact from nuttx 8885.
Tested with nuttx 8885
Change-Id: I2550888ee29aadcfcf8a98bfe5690920ee2b17d1
```
internal ci

testing/drivertest: Fix typo error in drivertest_uart.c

---

testing/fstest/fstest_main.c

fstest_main.c:340:47: note: expected ‘struct fstest_ctx_s *’ but argument is of type ‘fsblkcnt_t’ {aka ‘long long unsigned int’}
340 | static int fstest_gc(FAR struct fstest_ctx_s *ctx, size_t nbytes)
|                          ~~~~~~~~~~~~~~~~~~~~~^~~
fstest_main.c:1168:13: error: too few arguments to function ‘fstest_gc’
1168 |       ret = fstest_gc(buf.f_bfree);
|             ^~~~~~~~~
fstest_main.c:340:12: note: declared here
340 | static int fstest_gc(FAR struct fstest_ctx_s *ctx, size_t nbytes)
|            ^~~
fstest

fstest:fix typo

---

canutils/lely-canopen/CMakeLists.txt
canutils/libdronecan/CMakeLists.txt
canutils/libopencyphal/CMakeLists.txt

migrate apps CMakeLists
> [!WARNING]
> `nuttx_add_user_library` have unexpected results, I will track and fix in this issue [apache/nuttx/issues#10191](https://github.com/apache/nuttx/issues/10191)
sim with enable NET CAN NET_CAN and enbale the corresponding library configuration

cmake:migrate lely-canopen,libdronecan,libopencyhal for cmake build

---

Application.mk
Make.defs
builtin/builtin_list.c

File uid and gid configuration for builtin fs, if set-user-ID bit is set in the file permissions, then the euid of process set as file uid. Use the confiuration to emulate builtin app set.
MODE must octal number and use similar with linux chmod OCTAL-MODE FILE
UID  = 2000
GID  = 3000
MODE = 06555
That pull is followed by https://github.com/apache/nuttx/pull/8924
sim:nsh with CONFIG_SCHED_USER_IDENTITY=y
hello example emulates to set uid and file set-user-ID bit, and call geteuid and getegid API.
UID  = 2000
GID  = 3000
MODE = 06555
nsh> ls -l /bin/hello
-r-sr-sr-x    2000    3000       0 hello
nsh> hello
geteuid:2000
getegid:3000
let's ignore the below warning:
```
/home/runner/work/nuttx-apps/nuttx-apps/apps/builtin/builtin_list.c:43:1: warning: #include outside of 'Included Files' …
```

builtin: uid and gid configuration for builtin app

---

crypto/tinycrypt/CMakeLists.txt

migrate cmake build for tinycrypt
CMake build Eanble CONFIG_TINYCRYPT CONFIG_TINYCRYPT_TEST

cmake:migrate apps CMakeLists for tinycrypt

---

system/dumpstack/dumpstack.c

Wrong start and end values would make dead cycle. Exchange the values when start value is bigger than end value.

---

.gitignore
crypto/libsodium/.gitignore
crypto/libsodium/CMakeLists.txt

migrate cmake build for libsodium
CMake build eanble CONFIG_LIBSODIUM

cmake:migrate apps CMakeLists for libsodium

---

examples/bme680/CMakeLists.txt
examples/bme680/Kconfig
examples/bme680/Make.defs
examples/bme680/Makefile
examples/bme680/bme680_main.c

This is a usage example for the bme680 when all its sub-sensors are enabled and it can be easily modified to accomodate other configurations.
Testing was done on the esp32-sparrow board.

examples/bme680: Added test program for the BME680 sensor

---

nshlib/nsh_syscmds.c

rptun/ping: print invalid arguments error
nrf53

rptun/ping: print invalid arguments error

---

nshlib/nsh_syscmds.c

rptun/ping: fix invalid use of nsh_error after 31421db6f
reported by CI https://github.com/apache/nuttx/actions/runs/5924486445/job/16062219720#step:7:525:
```
Error: nsh_syscmds.c:541:27: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
nsh_error(vtbl, g_fmtargrequired);
^~~~~~~~~~~~~~~~
./nsh_console.h:54:49: note: expanded from macro 'nsh_error'
^~~~~~~~~~~
nsh_syscmds.c:541:27: note: treat the string as an argument to avoid this
nsh_error(vtbl, g_fmtargrequired);
^
"%s", 
./nsh_console.h:54:49: note: expanded from macro 'nsh_error'
```
CI, I don't get this error locally

rptun/ping: fix invalid use of nsh_error after 31421db6f

---

testing/ostest/wqueue.c

Fix "check_return" reported by Coverity
ostest/wqueue, normally no impact.
CI

ostest/wqueue: Check return value for pthread ops.

---

nshlib/nsh_timcmds.c

Fixes following warning:
CC:  grp/lib_getgrbufr.c nsh_timcmds.c: In function 'cmd_date': nsh_timcmds.c:370:19: warning: variable 'errfmt' set but not used [-Wunused-but-set-variable]
370 |   FAR const char *errfmt;
|
Fixes build warning
Code compiles without the warning

nshlib/nsh_timcmds.c: Suppress warning about unused variable (errfmt)

---

interpreters/toywasm/Makefile
interpreters/toywasm/include/toywasm_version.h

toywasm: bump to v33
tested on sim/macos/x86-64
build-tested esp32-devkitc

toywasm: bump to v33

---

Application.mk
Make.defs
tools/Wasm.mk

> this patch fix issue https://github.com/apache/nuttx-apps/issues/633 
- issue
when a program has **multiple** `MAINSRC` for **incremental compilation**, the `PROGNAME` of the compiled file may generate errors
```
-------------------- compile definition error ---------------------
cc -c -g CFLAGS INCLUDEDIR -Dmain=funA_main funB.c -o funB.c.path.o
^^^^  ^^^^^^    ^^^^
-------------------------------------------------------------------
```
- solution
we use the `MAINOBJ:PROGNAME` mapping variable to define the main entry name, for example:
```makefile
MAINSRC = demoA.c demoB.c
PROGNAME = runA runB
``` 
```makefile
PROGKEY_home.apps.examples.myapp.demoA.o := runA
PROGKEY_apps.examples.myapp.demoB.o := runB
ELFPROGKEY_/home/apps/bin/runA :=  apps.examples.myapp.demoA.o …
```

Application.mk:define main entry MAINNAME relatively

---

benchmarks/coremark/CMakeLists.txt
canutils/lely-canopen/CMakeLists.txt
crypto/libsodium/CMakeLists.txt
crypto/libtomcrypt/CMakeLists.txt
crypto/mbedtls/CMakeLists.txt
crypto/tinycrypt/CMakeLists.txt
math/libtommath/CMakeLists.txt
system/argtable3/CMakeLists.txt

> this patch is another part of this  issue https://github.com/apache/nuttx/issues/10241
- delete the .git condition that cause duplication of fetching stage.
- replace custom_patch_target with PATCH_COMMAND.
- remove custom_patch_target dependencies.
- when fetch a lib during cmake configure phase,it will download into `/cmake-build-dir/_dep/lib_src/` directory.
every time the build directory is deleted,the download will be repeated. this patch also fixes these problem.
related to:https://github.com/apache/nuttx/pull/10379
fetch for the first time and compile repeated

cmake:replace custom_patch_target with PATCH_COMMAND

---

benchmarks/coremark/Makefile

fix no coremark in bin register
re regsiter coremark in building with CONFIG_INTERPRETERS_WAMR enabled.
Pass Vela CI

benchmarks/coremark: fix no coremark in bin

---

crypto/mbedtls/Kconfig

when enable MBEDTLS_SLEFTEST it will import parts related to ssl and need to define MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT

mbedtls: mbedtls_selftest depends on MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT

---

nshlib/nsh_console.h
nshlib/nsh_timcmds.c

Adds way to forward any output into nothingness. Handles CONFIG_NSH_DISABLE_ERROR_PRINT case gracefully for any
amount of arguments.
Only nsh_error output, when CONFIG_NSH_DISABLE_ERROR_PRINT is set
Build passes, output works when enabled, output is silent when not

nshlib/nsh_console.h: Add nsh_none, where empty output can be forwarded

---

boot/miniboot/Kconfig

boot/miniboot: hide miniboot options if not enabled
cosmetics
CI

boot/miniboot: hide miniboot options if not enabled

---

Application.mk

Avoid warning when PROGNAME contains space blank.
None

Application.mk: Remove warning that program names mismatch

---

examples/rpmsgsocket/rpsock_client.c

Fix warning:
CC:  rpsock_client.c rpsock_client.c: In function 'rpsock_unsync_test': rpsock_client.c:203:30: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
203 |                       printf("client check fail total %d, \
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
204 |                               i %d, %08x, %08x\n",
|                               ~~~~~~~~~~~~~~~~~~~
205 |                               ALIGN_UP(total), i, intp[i],
|                                                   ~~~~~~~
|                                                       |
|                                                       uint32_t {aka long unsigned int}
warning fix
ci

apps/rpsock_client: Fix rpsock_client.c [-Wformat=] warning

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_fsutils.c
nshlib/nsh_proccmds.c

Add the API "nsh_getpid" in "nsh_fsutils. c" and the nsh command pidof
Currently, it only supports querying the pid of specific process names.
None
pidof 'Idle Task'

apps/nshlib: Add the pidof command and API nsh_getpid

---

nshlib/nsh_consolemain.c

Properly returns `-ENOMEM` from `nsh_consolemain` if the `pstate` is `NULL`.
This issue occured in PX4 when the mavlink shell was opened some time after boot.
This calls `nsh_newconsole`, which calls `zalloc(804)`:
```c
FAR struct console_stdio_s *nsh_newconsole(bool isctty)
{
FAR struct console_stdio_s *pstate =
(FAR struct console_stdio_s *)zalloc(sizeof(struct console_stdio_s));
if (pstate)
{
/* ... */
}
return pstate;
}
```
```
(gdb) bt
#0  nsh_newconsole (isctty=isctty@entry=true) at nsh_console.c:441
#1  0x08011244 in nsh_consolemain (argc=argc@entry=0, argv=argv@entry=0x0) at nsh_consolemain.c:69
#2  0x080e2d0a in MavlinkShell::shell_start_thread (argc=<optimized out>, argv=<optimized out>) at src/modules/mavlink/modules__mavlink_unity.cpp:12472
#3  0x08017956 in nxtask_startup …
```

nshlib/nsh_consolemain: detect null pointer

---

testing/ostest/mqueue.c
testing/ostest/timedmqueue.c

testing: fix visual studio Compiler Error C2057
expected constant expression
The context requires a constant expression, an expression whose value is known at compile time. The compiler must know the size of a type at compile time in order to allocate space for an instance of that type.
Reference:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2057?view=msvc-170
Signed-off-by: chao an anchao@xiaomi.com
N/A
visual studio 2023 + cmake

testing: fix visual studio Compiler Error C2057

---

crypto/tinycrypt/Kconfig
crypto/tinycrypt/Makefile

application may use micro-ecc for some ecc operation, which may be faster than tinycrypt, due to assemble code, but both of them have same function definition, cause build error on there case.
new option
internal test

add macro for ecc

---

fsutils/inih/CMakeLists.txt
fsutils/ipcfg/CMakeLists.txt
fsutils/libtinycbor/CMakeLists.txt
fsutils/mkgpt/CMakeLists.txt
fsutils/mkmbr/CMakeLists.txt

migrate cmake build 
- inifile
- inih
- ipcfg
- libtinycbor
- mkgpt
- mkmbr
CMake build eanble CONFIG_FSUTILS_INIFILE, CONFIG_FSUTILS_INIH,CONFIG_FSUTILS_IPCFG,CONFIG_FSUTILS_TINYCBOR_LIB,CONFIG_FSUTILS_MKGPT,CONFIG_FSUTILS_MKMBR

cmake:migrate apps CMakeLists for fsutils

---

examples/pipe/pipe_main.c

fix issue about can't print info to screen after calling redirect_test func. reason:stdin/stdout was redirected and closed in redirect_test.c. measures:change all printf() to fprint(stderr,...) in pipe_main.c, and modify fflush(stdout) to fflush(stderr) in line 231.
N/A
daily test/local test

apps/examples/pipe: fix issue about can't log after calling redirect_test

---

system/cu/cu_main.c

Type int expects 4 bytes for function write(). Type char expects 1 byte which matches the real usage of function write().
ci

Fix wrong parameter size

---

Application.mk

related to https://github.com/apache/nuttx-apps/pull/1853
a large number of objs caused an error that the parameters were too long in the archive stage.
CI build

Application.mk:execute archive in batches

---

system/nxlooper/nxlooper.c

* system/nxlooper: Initialize `audio_caps_s` to 0
This prevents unspecified values from being passed to the lower interfaces of the audio subsystem.
Preventing erroneous behavior.
Internal CI testing + ESP32-S3 with `esp32s3-devkit:nxlooper` (yet to be submitted).

system/nxlooper: Initialize `audio_caps_s` to 0

---

examples/mqttc/Kconfig
netutils/mqttc/Kconfig
netutils/mqttc/Makefile

The mqttc demo under example path can not support mbedtls api. Because of the MQTT-C source code already contains many types of link examples, so we added the corresponding makefile to support mbedtls mqttc connections publisher and posix mqttc connections publisher and subscriber.
sim:local

mqttc: add mbedtls MQTTC support

---

examples/udgram/udgram_client.c
examples/udgram/udgram_server.c
examples/ustream/ustream_client.c
examples/ustream/ustream_server.c
nshlib/nsh_fsutils.c

improve the speed and reduce the code size a little bit
code refactor
ci

Replace strlen with sizeof for kconfig string

---

testing/ltp/0001-pthread_rwlock_unlock-follow-linux.patch
testing/ltp/0002-Use-ifdef-instead-of-if-for-__linux__.patch
testing/ltp/0003-LTP-Re-init-static-variable-to-avoid-errors-during-m.patch
testing/ltp/0004-test-update-ltp-test-case.patch
testing/ltp/0005-ltp-update-pthread_cond_timedwait-testcase.patch
testing/ltp/0006-test-modified-ltp-rwlock-need-init.patch
testing/ltp/0007-pthread_kill-add-usleep-aviod-semcount-overturn.patch
testing/ltp/0008-test-ltp-fix-ltp_interfaces_sigaction_23_10-deadloop.patch
testing/ltp/0009-ltp-modify-user-code-for-fdcheck-compatibility.patch
testing/ltp/0010-ltp-fix-build-warning.patch
testing/ltp/Makefile

apply that patch that to fix the build warning in ltp
the origin ltp testcases has many build warnings which consider error in Nuttx, thus to apply the patches to fix these build warnings

ltp/makefile: apply that patch that to fix the build warning in ltp

---

testing/atomic/Kconfig
testing/atomic/Make.defs
testing/atomic/Makefile
testing/atomic/atomic_main.c

verify atomic function provided by the toolchain or nuttx/libc
new example
ci

add test atomic

---

system/fastboot/Kconfig
system/fastboot/Make.defs
system/fastboot/Makefile
system/fastboot/fastboot.c

Add the fastbootd program to support the flash, getvar, and reboot commands.
You can be enabled fastbootd by opening the following configs:
> CONFIG_SYSTEM_FASTBOOTD=y
> CONFIG_SYSTEM_FASTBOOT_STACKSIZE=4096
> CONFIG_SYSTEM_FASTBOOTD_DOWNLOAD_MAX=40960
> CONFIG_USB=y
> CONFIG_USBDEV=y
> CONFIG_USBADB=y
> CONFIG_USBFASTBOOT=y
The operation is as follows:
- Run fastbootd:
> bl> fastbootd
-  Host PC check the connect device:
> $ fastboot devices
> 1234    fastboot
-  Flash img:
> $ fastboot flash ap ap.bin
-  Reboot the devices after successful flashing:
> $ fastboot reboot
NA
BES board

system: support system fastbootd

---

testing/crypto/aescbc.c

iv content always should be updated when performing encryption operation, so need update testing case

testing/crypto: fix aescbc crash when update iv

---

testing/drivertest/drivertest_block.c

Fix insufficient number of erasures for mtd devices when operating multiple rwblocks.

drivertest_block:Fix a problem when operating mtd devices

---

lte/alt1250/alt1250_usockif.c
lte/alt1250/usock_handlers/alt1250_ioctlhdlr.c

Fix usrsock_bind error by uninitialized value.
lte/alt1250: Fix issue that ifconfig does not work.
lte/alt1250

lte/alt1250: Fix usrsock_bind error by uninitialized value

---

testing/ltp/Makefile

the ltp.zip file is not tracked in git record, so after download and unzip finished, we do not need to keep this ltp.zip file.
After remove the ltp.zip file can also avoid the CI warning.

ltp/makefile: rm the ltp.zip file after unzipped

---

crypto/mbedtls/Makefile

crypto/mbedtls: fix build break on sha256.c
Build break on Assemble compiler if -fno-omit-frame-pointer and -O3 enabled at same time
```
{standard input}: Assembler messages:
{standard input}:2560: Error: branch out of range
make[2]: *** [apps/Application.mk:170: mbedtls/library/sha256.o] Error 1
```
N/A
ci-check

crypto/mbedtls: fix build break on sha256.c

---

testing/ltp/Makefile

fix the Makefile mac compiler error found by https://github.com/apache/nuttx/pull/10543
ci

Ltp Makefile:fix make macro error block on Mac

---

crypto/mbedtls/Kconfig
crypto/mbedtls/Makefile
crypto/mbedtls/include/mbedtls/mbedtls_config.h
crypto/mbedtls/include/md5_alt.h
crypto/mbedtls/source/md5_alt.c

add md5 alternative implementation via /dev/crypto

mbedtls-alt/md5: add md5 alternative implementation

---

system/nxcamera/nxcamera_main.c

nxcamera_main.c:160:26: warning: format '%d' expects argument of type 'int *', but argument 5 has type 'uint32_t *' {aka 'long unsigned int *'} [-Wformat=]
```
160 |   sscanf(parg, "%hd %hd %d %4s", &width, &height, &framerate, cc);
|                         ~^                        ~~~~~~~~~~
|                          |                        |
|                          int *                    uint32_t * {aka long unsigned int *}
|                         %ld
```
nxcamera
ci

nxcamera: Fix compilation warnings caused by format issues

---

system/fastboot/fastboot.c

Fix command comparation.
e.g. The command is "reboot-bootloader", but will match and break when compared  with "reboot"
apps/system/fastboot
|CMD|Result|
|--|--|
|fastboot reboot|OK|
|fastboot reboot-bootloader|OK|
|fastboot flash \<PARTITION\> \<IMG_FILE\> (, and download) | OK|
|fastboot getvar \<VAR\>| OK|
|fastboot erase \<PARTITION\> | OK|

system/fastboot: Fix command comparation

---

.gitignore
Application.mk
Directory.mk
Make.defs
Makefile

apps/build: Restore ARLOCK to improve compile speed in incremental case
To solve the issue of carrying object files from previous builds, Matias changed the archiving process to re-archive libapps.a on every compilation, if libapps.a carries more object files, incremental compilation will waste too many time in re-archiving, compared with the previous implement, this is a degradation of the build system.  Referring to mature engineering projects such as cmake, if there is configuration or source file changed, the best solution should be to reconfigure the environment.
Revert this PR to ensure the compilation speed during incremental compilation.
https://github.com/apache/nuttx-apps/pull/380
```
|  commit 18137c0fec3cea30871f29238e11ea0f4e8523da
|  Author: Matias N <matias@protobits.dev>
| …
```

apps/build: Restore ARLOCK to improve compile speed in incremental case

---

Application.mk

makefile/archive: fix build break if object target is split to multi-part
N/A
ci-check

makefile/archive: fix build break if object target is split to multi-part

---

system/adb/Makefile

to fix error: microADB/hal/hal_uv.c:32:38: error:
a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
please see the discussion here: https://github.com/apache/nuttx/pull/10600
minor
ci

system/adb: Download the latest package

---

lte/alt1250/callback_handlers/alt1250_evt.c

Fix bug that name resolution failed for a long time under particular cases. If a DNS query for IPv6 succeeds and IPv4 fails, only the answer of the IPv6 query is saved in the cache. If only IPv4 is given from LTE, name resolution will fail while the answer is saved in the cache. Therefore, the ALT1250 daemon sets the given IP type to the DNS client, which can only send DNS queries for that IP type.
Only alt1250 daemon.

lte/alt1250: Fix bug that name resolution failed for a long time

---

crypto/mbedtls/include/mbedtls/mbedtls_config.h
interpreters/bas/bas_auto.c
interpreters/bas/bas_auto.h
interpreters/bas/bas_global.c
interpreters/bas/bas_global.h
interpreters/bas/bas_program.c
interpreters/bas/bas_program.h
interpreters/bas/bas_str.c
interpreters/bas/bas_str.h
interpreters/bas/bas_value.c
interpreters/bas/bas_value.h
interpreters/bas/bas_var.c
interpreters/bas/bas_var.h
nshlib/nsh_syscmds.c
system/hex2bin/hex2bin_main.c
system/hex2bin/hex2mem_main.c

Complementary apps PR of https://github.com/apache/nuttx/pull/10565.
Rename stream struct fields named `public` and functions parameters named `this` in `streams.h` and `rtt.h` so C++ compilers won't fail to compile them (these are [reserved keywords](https://en.cppreference.com/w/cpp/keyword) in C++). This fixes the issue called out by https://github.com/apache/nuttx/issues/10556
`lib/libc/stream`, `segger/rtt.h`
- Successfully compiled `nsh` app for IMXRT after I:
- modified it to include [segger/rtt.h](https://github.com/apache/nuttx/blob/master/include/nuttx/segger/rtt.h)
- set the following [segger Kconfigs](https://github.com/apache/nuttx/blob/master/drivers/segger/Kconfig):  `STREAM_RTT`, `SEGGER_RTT`

c++ compatibility: rename usages of reserved c++ keyword 'public' and 'this'

---

interpreters/duktape/Makefile
interpreters/duktape/not_used.patch

fix the ci error found by: https://github.com/apache/nuttx/actions/runs/6207328376/job/16852506513?pr=10647
duktape
ci

interpreters/duktape: Fix error: variable 'num_stmts' set but not used

---

crypto/mbedtls/0001-mbedtls-entropy_poll-use-getrandom-to-get-the-system.patch
crypto/mbedtls/Makefile

use getrandom to get system entropy and not dependent on config DEVURANDOM

mbedtls: use 'getrandom' to get system entropy

---

netutils/pppd/ipcp.c

Fixed typo in printip
pppd could not build with PPP_DEBUG enabled.

Fix typo of uint8_t in printip

---

nshlib/nsh_codeccmd.c

Simplify the "cmd_codecs_proc" md5 related framework and modify the implementation of the command md5:
None
None

nshlib: Add FAR Keyword to command md5

---

examples/ina226/ina226_main.c

Fixes compiler warnings while printing uint32_t and int32_t values.
None.
Not tested. I don't have a board with INA226.

Fixes compiler warnings while printing uint32_t and int32_t values.

---

nshlib/nsh_syscmds.c

check domain if invaild return error avoid to crash
self test

pmconfig: check domain if invaild return error avoid to crash

---

system/libuv/0001-libuv-port-for-nuttx.patch

If UV_ONCE_INIT is a struct, the following errors will occur:
libuv/src/unix/nuttx.c: In function 'uv__global_get': /home/hujun5/downloads1/vela_sim/apps/system/libuv/libuv/include/uv/unix.h:136:22: error: expected expression before '{' token
136 | #define UV_ONCE_INIT PTHREAD_ONCE_INIT
|                      ^~~~~~~~~~~~~~~~~
libuv/src/unix/nuttx.c:287:26: note: in expansion of macro 'UV_ONCE_INIT'
287 |           global->once = UV_ONCE_INIT;
|                          ^~~~~~~~~~~~
/home/hujun5/downloads1/vela_sim/apps/system/libuv/libuv/include/uv/unix.h:136:22: error: expected expression before '{' token
136 | #define UV_ONCE_INIT PTHREAD_ONCE_INIT
|                      ^~~~~~~~~~~~~~~~~
libuv/src/unix/nuttx.c:288:50: note: in expansion of macro 'UV_ONCE_INIT'
288 | …

libuv: fix build error

---

testing/osperf/osperf.c

This issue (https://github.com/apache/nuttx/issues/10754) found that there are some problems using osperf on qemu-armv8a
In SMP mode, all threads must be thread synchronized and cannot rely on priority for synchronization.

Fix osperf running error in SMP mode

---

nshlib/nsh_alias.c

getopt returns the argument if it is found, so testing against != ERROR is wrong. Testing against 'a' in this case is correct (no other
arguments are possible)
Fix trivial bug in alias handling (remove all aliases command)
unalias -a works

nsh_alias.c: unalias -a command does not work correctly

---

testing/drivertest/drivertest_rtc.c

Fix ./drivertest_rtc.c:43:10: fatal error: nuttx/time.h: No such file or directory

---

testing/drivertest/drivertest_watchdog.c

fix compiler error
drivertest
internal ci

Fix drivertest_watchdog.c:284:33: error: storage size of 'reset_cause' isn't known

---

examples/can/can_main.c

Junk data in TX and RX structs creates a header mismatch problem in esp32s2 twai example. To solve this, structs assigned 0 at startup.
- examples/can: TX and RX structs assigned 0 at startup
Only can example
[ESP32-S2 Saola with using `esp32s2-saola-1:twai` configuration and `can` example](https://github.com/apache/nuttx/pull/10823)

examples/can: TX and RX structs assigned 0 at startup

---

examples/foc/foc_nxscope.c
examples/nxscope/Kconfig
include/logging/nxscope/nxscope_intf.h
logging/nxscope/nxscope_iser.c

- nxscope/serial: ignore baud configuration if set to 0
- examples/foc: allow nxscope transfer over RTT interface
For UART serial interface TERMIOS is required, but for RTT serial interface it's not
nxscope data stream over RTT is now possible. 
Much more powerful debugging tool than data stream over UART/USB.
nxscope example on nrf52832-dk (built-in jlink)
foc exampe with nxscope enabled on b-g431b-esc1 (on-board stlink replaced with jlink)

nxscope: support for RTT serial interface

---

lte/alt1250/usock_handlers/alt1250_sms.c

ENOTSUP is now a special error code to fallback to the kernel network stack. Therefore, change the error code from ENOTSUP to EAFNOSUPPORT.
Only alt1250 daemon.
Test with Spresense LTE Board.

lte/alt1250: Change error code from ENOTSUP to EAFNOSUPPORT

---

examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_motor_b16.h
examples/foc/foc_motor_f32.h
examples/foc/foc_nxscope.c
examples/foc/foc_nxscope.h
include/industry/foc/fixed16/foc_handler.h
include/industry/foc/float/foc_handler.h
industry/foc/fixed16/foc_handler.c
industry/foc/fixed16/foc_svm3.c
industry/foc/float/foc_handler.c
industry/foc/float/foc_svm3.c
logging/nxscope/nxscope.c

- logging/nxscope/nxscope.c: fix indentation
- industrail/foc: add an interface that returns the modulation state
- examples/foc: support svm3 state with nxscope
useful for debugging and demonstrating SVM3 operations
foc example on b-g431b-esc1 with RTT transfer
Below SVM3 modulation state data stream (sampling rate 1kHz) visualized with PlotJuggler:

examples/foc: add support for streaming modulation state

---

examples/adjtime/adjtime_main.c
include/netutils/ptpd.h
netutils/ptpd/Kconfig
netutils/ptpd/Make.defs
netutils/ptpd/Makefile
netutils/ptpd/ptpd.c
netutils/ptpd/ptpv2.h
system/ptpd/Kconfig
system/ptpd/Make.defs
system/ptpd/Makefile
system/ptpd/ptpd_main.c

This adds beginnings of a PTP (precision time protocol) daemon, which can work as server, client or both.
What works:
- Basic server & client operation
- Transmission and reception of announce, sync and follow-up
Still missing:
- SO_TIMINGS for getting more precise packet timestamps
- Implementation of delay_req and delay_resp packets
- Status and stop interfaces for the daemon
Adds a new application `ptpd`.
Tested against Linux ptpd2 version 2.3.1 using a custom STM32F4 board.
PC to NuttX sync (with debug messages enabled):
<pre>
linux$ sudo ptpd -i enp8s0 -V
nsh> ptpd eth0
Started the PTP daemon as PID=6
ptp_process_rx_packet: Got packet: 44 bytes
ptp_process_rx_packet: Got sync packet, seq 0
ptp_process_rx_packet: Got packet: 44 bytes
ptp_process_rx_packet: Got follow-up packet, seq 0 …

Add basic IEEE-1588 PTP server/client

---

crypto/mbedtls/Kconfig

crypto/mbedtls: fix kconfig typo
crypto/mbedtls

crypto/mbedtls: fix kconfig typo

---

examples/hello_wasm/Kconfig
examples/hello_wasm/Make.defs
examples/hello_wasm/Makefile
examples/hello_wasm/hello_main.c

Decouple the hello example into hello and hello_wasm. The hello_wasm example is a minimal example to show how to build a wasm application by using the NuttX build system, and avoid disturbing the hello (native build).
Wasm build

examples: Split hello example into hello and hello_wasm

---

netutils/dhcp6c/dhcp6c.c
system/dhcp6c/CMakeLists.txt
system/dhcp6c/Kconfig
system/dhcp6c/Make.defs
system/dhcp6c/Makefile
system/dhcp6c/renew6_main.c

Add the renew6 command for dhcp6c. The command can supports two mode Stateless and Stateful.
The renew6 is used as follows:
- Stateless: renew6 eth0
- Stateful: renew6 eth0 1
The renew6 comand can obtain an IPv6 address for a specify interface using the dhcpv6 protocol.
Use the following steps to verify the renew6 command function.
- Open the configuration option `SYSTEM_DHCPC_RENEW6`
- Up interface, for example `ifup eth0`
- Obtain IPv6 address, `renew6 eth0 1`
- Check the obtained IPv6 address, `ifconfig eth0`

dhcp6c: Add the renew6 command for dhcp6c.

---

industry/foc/float/foc_ang_onfo.c

- industry/foc/nfo: use float numbers in all calculations
we want to use FPU instructions in calculations not __aeabi
optimization
b-g431b-esc1

industry/foc/nfo: use float numbers in all calculations

---

industry/foc/fixed16/foc_ang_onfo.c

industry/foc/fixed16/foc_ang_onfo.c: use b16abs operation
we get rid of custom ABS() macro
cosmetics
CI

industry/foc/fixed16/foc_ang_onfo.c: use b16abs operation

---

industry/foc/fixed16/foc_ang_openloop.c
industry/foc/float/foc_ang_openloop.c

industry/foc/openloop: don't use direction argument, instead use signed velocity
otherwise, when dir=-1 and the velocity value is negative, the output from velocity is in the opposite direction than the intended one

foc/openloop: don't use direction argument, instead use signed velocity

---

industry/foc/fixed16/foc_ang_onfo.c
industry/foc/fixed16/foc_ang_osmo.c
industry/foc/float/foc_ang_onfo.c
industry/foc/float/foc_ang_osmo.c

industry/foc: force angle observers output to zero if motor stopped
this prevents junk data from the observer when the motor is stopped

industry/foc: force angle observers output to zero if motor stopped

---

examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
industry/foc/Kconfig
industry/foc/fixed16/foc_align.c
industry/foc/float/foc_align.c

- industry/foc: make direction alignment configurable
for sensorless velocity controller (ESC) we don't need to align the direction,
but we have to align the initial motor phase each time the motor start
- industry/foc: reset align data when align is finished
this allows the align procedure to be run multiple times

industry/foc: improvements for align

---

industry/foc/fixed16/foc_vel_odiv.c
industry/foc/fixed16/foc_vel_opll.c
industry/foc/float/foc_vel_odiv.c
industry/foc/float/foc_vel_opll.c

industry/foc: reset velocity observer output foc_velocity_zero_xx() is called

industry/foc: reset observer data when foc_velocity_zero is called

---

examples/foc/foc_fixed16_thr.c

examples/foc: fix wrong nxscope functions for fixed16
CI

examples/foc: fix wrong nxscope functions for fixed16

---

include/industry/foc/fixed16/foc_feedforward.h
include/industry/foc/float/foc_feedforward.h
industry/foc/CMakeLists.txt
industry/foc/Kconfig
industry/foc/Makefile
industry/foc/fixed16/foc_feedforward.c
industry/foc/float/foc_feedforward.c

industry/foc: add support for PMSM feedforward compensation
reference: https://electronics.stackexchange.com/questions/386246/field-oriented-control-feed-forward-term

industry/foc: add support for feedforward compensation

---

examples/foc/Kconfig
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c

examples/foc: configure active breake current

examples/foc: configure active breake current

---

examples/foc/Kconfig
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c

examples/foc: add support for feedforward compensation
needs https://github.com/apache/nuttx-apps/pull/2125

examples/foc: add support for feedforward compensation

---

examples/foc/foc_cfg.h
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c

- examples/foc: rename SETPOINT_ADC_SCALE to SETPOINT_INTF_SCALE
SETPOINT_INTF_SCALE is more appropriate name because this definition is not only used for ADC scale
cosmetics
CI

examples/foc: rename SETPOINT_ADC_SCALE to SETPOINT_INTF_SCALE

---

examples/foc/Kconfig
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_main.c

- examples/foc: add an option to call nxscope work from control thread
This alows nxscope data to be sent with every cycle of the control loop,
which increases the execution time of the control loop, but allows data
to be sent at a highier frequency using the small nxscope buffer.
Useful when tuning and debuging using RTT transfer.

examples/foc: add an option to call nxscope work from control thread

---

testing/fstest/fstest_main.c
testing/scanftest/Kconfig
testing/scanftest/scanftest_main.c

This adds counting of correct/incorrect tests to scanftest and fstest and thus allow to check whether the tests are really
successful. Current CI tests only check whether the test program does on end with hard fault but do not check whether
the results are correct (and they are not). This will allow to check if new patches break some OS functions.
Better CI.
CI test pass

testing: add verbose output of correct/incorrect tests

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_float_thr.c
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_b16.h
examples/foc/foc_motor_f32.c
examples/foc/foc_motor_f32.h
examples/foc/foc_nxscope.c
examples/foc/foc_nxscope.h
examples/foc/foc_parseargs.c
include/industry/foc/foc_common.h

- examples/foc: add phase angle observer support (sensorless mode)
This app can work now as sensorless ESC.
Also introduce a cmd line option that force open-loop control
which is useful when tuning angle/velocity observers

examples/foc: add phase angle observer support (sensorless mode)

---

industry/foc/fixed16/foc_ang_onfo.c

industry/foc: use b16sign() instead of custom macro
CI

industry/foc: use b16sign() instead of custom macro

---

examples/sensor_fusion/Kconfig
examples/sensor_fusion/Make.defs
examples/sensor_fusion/Makefile
examples/sensor_fusion/sensor_fusion_main.c
inertial/.gitignore
inertial/CMakeLists.txt
inertial/Make.defs
inertial/Makefile
inertial/madgwick/Kconfig
inertial/madgwick/Make.defs
inertial/madgwick/Makefile

This PR adds support for the Madgwick Algorithm (Sensor Fusion Library) and adds an example that uses this lib with the MPU6050.
The library is under Application Configuration -> Inertial Libraries Support and requires MIT licenses to be enabled.
The example is available under Application Configuration -> Examples -> Sensor Fusion Example.
On compilation, it downloads the Fusion library from Github and the header files can be accessed using:
`#include "Fusion/Fusion.h""`
Next PRs should add board example and the example code will support other IMUs.
Shout out to @acassis for helping to set up the library entries!
New entry on Application Configuration and new example is available. This can be useful for those who use NuttX to control drones.
Testing works fine using MPU6050 on a Tiva-C …

examples/sensor_fusion: Support for Madgwick Fusion lib and example

---

system/ramspeed/ramspeed_main.c

Fixed a bug that caused misrecognition when using the -i parameter.
None
Local test passed

ramspeed:Fix the problem that the "-i" option doesn't work.

---

netutils/netinit/netinit.c

Without this addition, icmpv6 is never configured in the case that the device is powered on without an ethernet cable connected.
IPv6 is configured in the case that a network cable is connected after the device has already initialised.  
IPv6 stack on `eth0`, using custom hardware based on the litex:arty_a7.

netutils/netinit: Perform icmpv6 autoconfiguration when link transitions from down to up.

---

examples/calib_udelay/Kconfig
examples/calib_udelay/calib_udelay_main.c

The calibration test can take a long time on platforms with less processing power. Allow the default value to be changed with kconfig.
The calibration test completes in a more reasonable time.
Before this change, with the default 100000 iterations:
```
nsh> calib_udelay
Calibrating timer for main calibration...
Performing main calibration for udelay. This will take approx. 220.677 seconds.
```
With this change, and `CONFIG_EXAMPLES_CALIB_UDELAY_DELAY_TEST_ITERATIONS=5000`
```
nsh> calib_udelay
Calibrating timer for main calibration...
Performing main calibration for udelay.This will take approx. 12.739 seconds.
Calibration slope for udelay:
Y = m*X + b, where
X is loop iterations,
Y is time in nanoseconds,
b is base overhead,
m is nanoseconds per loop iteration.
m = 127.01355925 nsec/iter …
```

examples/calib_udelay: Allow the number of delay loop iterations to be specified by kconfig.

---

games/brickmatch/Kconfig
games/brickmatch/Make.defs
games/brickmatch/Makefile
games/brickmatch/bm_input_console.h
games/brickmatch/bm_input_gesture.h
games/brickmatch/bm_input_joystick.h
games/brickmatch/bm_inputs.h
games/brickmatch/bm_main.c

Rename Shift game to Brickmatch
Better name of the game
esp32-devkitc:brickgame (see https://github.com/apache/nuttx/pull/10996)

apps/games: Rename Shift game to Brickmatch

---

netutils/netinit/netinit.c

Waiting for an hour can cause the calculated tick count in `nxsem_clockwait` to overflow due to the default width of  `sclock_t`. Reduce the long wait period on platforms not using 64-bit time.
Timed wait in the network monitor thread now operates as intended.
Custom hardware, based on litex:arty_a7

netutils/netinit: Reduce net monitor delay on platforms without 64 bit time type.

---

LICENSE
testing/sd_stress/Kconfig
testing/sd_stress/Make.defs
testing/sd_stress/Makefile
testing/sd_stress/sd_stress_main.c

Add port of the sdstress utility from PX4-Autopilot:  https://github.com/PX4/PX4-Autopilot
Used in conjunction with https://github.com/apache/nuttx/pull/10478 , This tool is useful for verifying correct operation of SD, EMMC, or other mountpoints.
Relevant Kconfig options:
```
CONFIG_ALLOW_BSD_COMPONENTS=y
CONFIG_TESTING_SD_STRESS=m
CONFIG_TESTING_SD_STRESS_PROGNAME="sdstress"
CONFIG_TESTING_SD_STRESS_PRIORITY=100
CONFIG_TESTING_SD_STRESS_STACKSIZE=8192
CONFIG_TESTING_SD_STRESS_DEVICE="/mnt"
```
Help prompt:
```
nsh> sdstress -h
Stress test on a mount point
sdstress: [-r] [-b] [-f]
-r   Number of runs (1-10000), default 32
-b   Number of bytes (1-10000), default 4096
-f   Number of files (1-999), default 64
```
Example usage:
```
nsd> sdstress -b 4096 -f 8 -r 4
Start stress test with 32 …
```

testing/sd_stress: Port sdstress testing utility from PX4-Autopilot.

---

wireless/wapi/src/driver_wext.c

The generated SSID string has no terminator, which causes a out of bounds.
We add a terminator '\0' for the SSID string.
The ‘’wapi disconnect‘’ command no longer crahes.
The command 'wapi disconnect wlan0' can work fine.

wapi: Fix disconnect crash.

---

import/Make.defs

Fixes:
/apps/import/Make.defs:79: extraneous text after 'else' directive
Fix makefile condition
make import

import/Make.defs: Fix erroneous formatting of make condition

---

netutils/rexecd/rexecd.c
system/popen/popen.c

1. rexecd: avoid socket/pipe/socketpair dup to new task
2. system/popen: remove O_CLOEXEC if mode exinclude 'e'
rexecd/rexec and support popen without 'e'
Vela test

system/popen: add O_CLOEXEC to avoid fd dup

---

nshlib/nsh_fscmds.c

Since the output format will be messed up with a size of GB.
correct before
```
ap> ls -l
/dev:
brw-rw-rw-       0       0314572800 app
dr--r--r--       0       0       0 audio/
crw-rw-rw-       0       0       0 buttons
crw-rw-rw-       0       0       0 console
brw-rw-rw-       0       0104857600 coredump
crw-rw-rw-       0       0       0 crypto
brw-rw-rw-       0       02214592512 data
```
correct after
```
ap> ls -l
/dev:
brw-rw-rw-       0       0   314572800 app
dr--r--r--       0       0           0 audio/
crw-rw-rw-       0       0           0 buttons
crw-rw-rw-       0       0           0 console
brw-rw-rw-       0       0   104857600 coredump
crw-rw-rw-       0       0           0 crypto
brw-rw-rw-       0       0  2214592512 …
```

nshlib: correct `ls -l` command output format

---

nshlib/nsh_fileapps.c

Locking the scheduler prior to calling posix_spawn() might lock the scheduler for a relatively long time, if the file to be loaded is large.
posix_spawn() loads the process into memory, possibly linking it as well if the binary format is linkable (elf). This can take tens / hundreds of milliseconds, which basically destroys the OS's real time performance.
Missing the death-of-child signal is a very trivial penalty considering the alternative.
Remove a potentially very long scheduler lock from task spawning.
rv-virt:knsh64 and MPFS target with >100 processes

nshlib/nsh_fileapps.c: Remove sched_lock() from nsh_fileapp()

---

Application.mk
Make.defs

This is a workaround to solve the problem of not being able to use `ar rcsP`
when there are too many target files in archive and need to be processed in batches,
in order to avoid file replacement due to duplicate names,
we dynamically rename the target files here.
```makefile
OBJS := SAME_NAME.foo.bar.o ...... SAME_NAME.foo.bar.o
AROBJS := SAME_NAME.foo.bar_1.o ...... SAME_NAME.foo.bar_2.o
.built : $(AROBJS)
``` 
relate to (merge before):  https://github.com/apache/nuttx/pull/10973
CI build

Application.mk:resolve file conflicts with the same name when batching archives

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c

- examples/foc: configure acceleration and deceleration from command line
- examples/foc: change the velocity ramp parameters scale to x1  
controlling the ramp with greater accuracy makes no practical sense

examples/foc: configure acceleration and deceleration from command line

---

nshlib/nsh.h

rename CONFIG_SCHED_CPULOAD to CONFIG_SCHED_CPULOAD_NONE
Modify cpuload configuration name, see this PR for details：https://github.com/apache/nuttx/pull/11102
None
sim/mm

nsh: explicitly select the cpuload clock source configuration

---

testing/epoll/Kconfig
testing/epoll/Make.defs
testing/epoll/Makefile
testing/epoll/epoll.c

This commid add an epoll testcase to test the epoll
Test case 1: epoll_wait timeout test.
Test case 2: epoll_wait with driver call poll_notify() many times simultaneously.
Test case 3: epoll_wait with some driver/socket need call poll_setup() again when its internal state changed.
Add epoll test cases, related PR: https://github.com/apache/nuttx/pull/10706
and mail list: https://www.mail-archive.com/dev@nuttx.apache.org/msg10503.html
new testcase
test with PR: https://github.com/apache/nuttx/pull/10706

testing/epoll: add epoll test case

---

include/industry/foc/foc_log.h
industry/foc/Kconfig

industrial/foc: add options to configure foclib logs
ci

industrial/foc: add options to configure foclib logs

---

examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c

-  examples/foc: refactor control loop  
1. get FOC device state at the beginning of the loop
2. simplify if-else block
refactor
b-g431b-esc1

examples/foc: refactor control loop

---

examples/foc/CMakeLists.txt
examples/foc/Kconfig
examples/foc/Makefile
examples/foc/foc_device.c
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_perf.c
examples/foc/foc_perf.h

examples/foc: add support for control loop performance measurements
b-g431b-esc1

examples/foc: add support for control loop performance measurements

---

include/netutils/netlib.h
netutils/netlib/CMakeLists.txt
netutils/netlib/Makefile
netutils/netlib/netlib_addipv6addr.c
netutils/netlib/netlib_delipv6addr.c
nshlib/nsh_command.c
nshlib/nsh_netcmds.c

Depends on https://github.com/apache/nuttx/pull/11054
Patches included:
- netutils/netlib: Add support for add/del a single IPv6 address
- nshlib/ifconfig: Add support for add/del a single IPv6 address
We're using similar syntaxes and error codes as Linux:
```
linux> sudo ifconfig eth0 inet6 add fc00::2/64
linux> sudo ifconfig eth0 inet6 del fc00::2/112
SIOCDIFADDR: Cannot assign requested address
linux> sudo ifconfig eth0 inet6 del fc00::3/64
SIOCDIFADDR: Cannot assign requested address
linux> sudo ifconfig eth0 inet6 add fc00::2/64
SIOCSIFADDR: File exists
nuttx> ifconfig eth0 inet6 add fc00::2/64
nuttx> ifconfig eth0 inet6 del fc00::2/112
Failed to manage IPv6 address: Cannot assign requested address
nuttx> ifconfig eth0 inet6 del fc00::3/112
Failed to manage IPv6 address: Cannot …
```

nshlib/ifconfig: Add support for add/del a single IPv6 address

---

lte/alt1250/alt1250_netdev.c
lte/alt1250/alt1250_usockif.c
lte/alt1250/usock_handlers/alt1250_ioctl_ifreq.c
lte/alt1250/usock_handlers/alt1250_sockethdlr.c

Fix alt1250 daemon to return -ENOTTY when receiving ioctl request and in the state of using kernel's network stack.
Fix alt1250 daemon to return -ENOTSUP when receiving socket request and in the state of using kernel's network stack.
Fix alt1250 daemon to set dummy subnet mask in network devices. This allows the correct network device to be selected when two network devices exist.
Only alt1250 daemon

lte/alt1250: Fix some bugs in alt1250 daemon

---

canutils/lely-canopen/Makefile

This fixes the failure in compilation due to mismatch of extracted version hash of lely-core package from the tar file.
Compilation with CAN support should continue as expected.
Verified that the correct extracted directory is selected for further compilation.

Fix Compilation failure due to improper handling of extracted directory of lely-core package

---

examples/thttpd/content/tasks/tasks.c

The flags are removed from kernel side, needed by https://github.com/apache/nuttx/pull/11165

examples/thttpd: Remove TCB_FLAG_CANCEL stuff

---

examples/foc/foc_cfg.h

- examples/foc: allow sensored velocity mode
- examples/foc: add #error messages
- examples/foc: raise error if both sensorless and sensored modes enabled
- examples/foc: fix warning for sensored configurations
CI

examples/foc: various fixes foc_cfg.h

---

examples/foc/foc_device.c
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_perf.c
examples/foc/foc_perf.h

- examples/foc: start from the beginning if control loop is started
After the start request to FOC device, we should return to the beginning of the loop and wait for the first synchronization event.
This also fixes the problem with the extended first loop cycle, so we can remove the workaround in foc_perf.
b-g431b-esc1

examples/foc: start from the beginning if control loop is started

---

examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c

- examples/foc: get velocity from observer if sensored mode
- examples/foc: fix active brake for sensored mode
- examples/foc: fix compilation for open-loop without angle observer
velocity control and position control with qencoder

examples/foc: fixes for sensored operation mode

---

examples/foc/foc_cfg.h

- examples/foc: don't raise error when EXAMPLES_FOC_IPHASE_ADC isn't set   
This is the first step towards getting rid of CONFIG_EXAMPLES_FOC_IPHASE_ADC completely
CI

examples/foc: don't raise error when EXAMPLES_FOC_IPHASE_ADC isn't set

---

examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_b16.h
examples/foc/foc_motor_f32.c
examples/foc/foc_motor_f32.h

examples/foc: get iphase scale from the FOC device interface
CI

examples/foc: get iphase scale from the FOC device interface

---

system/popen/Kconfig

system/popen: popen should depends on pipe()
N/A
cicheck

system/popen: popen should depends on pipe()

---

examples/foc/Kconfig

examples/foc: remove obsolete CONFIG_EXAMPLES_FOC_IPHASE_ADC option
needs https://github.com/apache/nuttx/pull/11192 to pass CI
CI

examples/foc: remove obsolete CONFIG_EXAMPLES_FOC_IPHASE_ADC option

---

interpreters/bas/Kconfig
interpreters/bas/bas_statement.c
testing/ostest/CMakeLists.txt
testing/ostest/Makefile
testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/vfork.c

- Resolves an issue where `vfork_test` was not executed following
the renaming from CONFIG_ARCH_HAVE_VFORK to CONFIG_ARCH_HAVE_FORK,
as detailed in https://github.com/apache/nuttx/pull/9755.
- Please ** merge ** https://github.com/apache/nuttx/pull/11200 before
merging this PR.
- Successfully tested with rv-virt:smp64, spresense:smp, and sim:smp.

apps: Replace CONFIG_ARCH_HAVE_VFORK with CONFIG_ARCH_HAVE_FORK

---

system/uorb/CMakeLists.txt

cmake: support for system/uorb
nrf9160-dk with uorb_listener

cmake: support for system/uorb

---

tools/Wasm.mk

Allow application defined linker flags by define WLDFLAGS in there own Make.defs.
Minor
Vela and CI

Wasm.mk: Allow application defined linker flags

---

industry/foc/fixed16/foc_align.c
industry/foc/float/foc_align.c

- industry/foc: fix direction alignment
CCW direction wasn't properly detected when we start alignment from near zero position
odrive3.6

industry/foc: fix direction alignment

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_b16.h
examples/foc/foc_motor_f32.c
examples/foc/foc_motor_f32.h
examples/foc/foc_nxscope.c
examples/foc/foc_parseargs.c
examples/foc/foc_thr.c

- examples/foc: replace CONFIG_INDUSTRY_FOC_* with CONFIG_EXAMPLES_FOC_*
Decouple the FOC example configuration from the FOC lib configuration. 
Purely cosmetic change, without affecting functionality.
CI

examples/foc: replace CONFIG_INDUSTRY_FOC_* with CONFIG_EXAMPLES_FOC_*

---

examples/libtest/CMakeLists.txt

It looks like this word is needed for this build to work with cmake
Fixes cmake build when `libtest` is enabled

libtest: add PRIVATE to CMakeLists.txt

---

netutils/connectedhomeip/.gitignore
netutils/connectedhomeip/0001-chip-add-compile-support-for-NuttX.patch
netutils/connectedhomeip/CMakeLists.txt
netutils/connectedhomeip/Kconfig
netutils/jsoncpp/.gitignore
netutils/jsoncpp/CMakeLists.txt
netutils/jsoncpp/Kconfig
netutils/jsoncpp/Make.defs
netutils/jsoncpp/Makefile

A nuttx with the matter command can be compiled using cmake and enable CONFIG_MATTER option.
The matter compiled by the current script is just a lighting example of
a limited number of commands that can be tested by chip-tool.
After nuttx is connected to the LAN and the matter command is executed, other devices in the LAN, such as linux PCS, can run the following commands to scan, connect, turn on and off, adjust brightness and contrast, and so on.
chip-tool pairing onnetwork 1 20202021
chip-tool onoff on 1 1
chip-tool levelcontrol move-to-level 128 10 0 0 1 1
chip-tool colorcontrol move-to-hue-and-saturation 240 100 0 0 0 1 1
Depends on the following configuration options:
CONFIG_CRYPTO_MBEDTLS=y
CONFIG_DEV_URANDOM=y
CONFIG_LIBCXX=y
CONFIG_LIBM=y
CONFIG_NET_IPv6=y
CONFIG_NET_ICMPv6=y …

cmake: add compilation support for matter

---

include/netutils/ptpd.h
netutils/ptpd/Kconfig
netutils/ptpd/ptpd.c
netutils/ptpd/ptpv2.h
system/ptpd/ptpd_main.c

Implemented missing functionality in PTPD and fixed bugs.
Most importantly:
* Negative clock deltas were not correctly handled.
* Add `SO_TIMESTAMP` support to get accurate packet reception times
* Add network path delay measurement
* Add status and stop interfaces to control ptpd
* Improve clock adjustment algorithm, implement clock drift estimator
Improves timing accuracy achievable.
Tested on custom STM32F417 board, both against Linux `ptpd2 version 2.3.1` and between two STM32 boards.
My PC does not have PTP-compatible hardware timestamping, so it has some 50 µs of jitter.
Between two STM32 boards the clocks are synchronized within +- 5µs as confirmed by measuring GPIO PPS signal with oscilloscope.
Clock settling time depends primarily on `CONFIG_CLOCK_ADJTIME_PERIOD_MS` and …

PTPD improvements

---

graphics/lvgl/Makefile

lvgl/makefile: workaround for lvgl.v8
Since this change is only merged into the lvgl.v9, let us workaround for v8:
https://github.com/hubbell2019/LVGL/commit/37835260ca30a5b191d8b55d0d2b49892aad7a21
./lvgl/src/core/lv_obj.c:363:25: warning: variable 'x' set but not used [-Wunused-but-set-variable]
363 |         static uint32_t x = 0;
|                         ^
1 warning generated.
CFLAGS += -Wno-unused-but-set-variable
N/A
ci-check

lvgl/makefile: workaround for lvgl.v8

---

testing/open_memstream/Kconfig
testing/open_memstream/Make.defs
testing/open_memstream/Makefile
testing/open_memstream/open_memstream.c

Adds test tool application for open_memstream for CI testing. Performs basic write/seek operations.
New test application.
CI test pass.

testing: add open_memstream test tool

---

interpreters/wamr/Toolchain.defs
tools/WASI-SDK.defs
tools/Wasm.mk

* Emit map file like NuttX's `System.map` for more debug information.
* Before WAMR 1.3.0, eabihf in wamrc is `gnueabihf`, so without this patch call wamrc will failed with target abi was `eabihf`, we should convert the standard llvm target to wamrc required. Both `eabihf` and `gnueabihf` supported after WAMR 1.3.0.
* Split origin Wasm.mk into Wasm.mk and WASI-SDK.defs
* Allow customize ld flags for each wasm module
* Move final wasm module to bin/wasm, and leave all intermediate file in apps/wasm, such as .map file, entry object etc used in wasm module build.
Makefile for wasm build system
Vela and CI

Wasm build system improvements

---

include/netutils/netlib.h
netutils/netlib/Makefile
netutils/netlib/netlib_obtainipv6addr.c
system/dhcp6c/renew6_main.c

If Managed Address Congfiguration flag in the Router Advertisement Messsage is set, we would obtain the IPv6 address though the stateful DHCPv6 procedure.
The change will affect the process of obtaining IPv6 address by `renew6`.
We can use radvd to simulte the IPv6 server, and control the RA flags by turning on or off the `AdvManagedFlag` field.
- open the `NET_ICMPv6_AUTOCONF`;
- then, get the IPv6 address by `renew6`;
- and check the result with `ifconfig`;
The radvd configuration is as follows:
```
interface nuttx0 {
IgnoreIfMissing on;
AdvSendAdvert on;
MinRtrAdvInterval 200;
MaxRtrAdvInterval 600;
AdvOtherConfigFlag on;
AdvManagedFlag on;
AdvLinkMTU 1500;
prefix 2408:501:ffff:abc::/64 {
AdvOnLink on;
AdvAutonomous on;
AdvRouterAddr off;
AdvValidLifetime 600;
AdvPreferredLifetime 600; …
```

renew6: Optimize the process of obtaining an IPv6 address.

---

nshlib/nsh_netcmds.c

Patches included:
- nshlib/ifconfig: Set network mask before setting gateway
- Switch the order of setting network mask and gateway, re-order only, no logic change.
- nshlib/ifconfig: Generate default IPv4 gateway with netmask
- Generate default gateway using configured netmask instead of fixed 255.255.255.0, which may be more flexible under certain situations. e.g. A subnet like 10.0.23.16/28 may not contain the .1 address.
Before:
ifconfig eth0 10.0.23.22 netmask 255.255.255.252 => DRaddr:10.0.23.1
ifconfig eth0 10.0.23.22 netmask 255.255.255.240 => DRaddr:10.0.23.1
ifconfig eth0 10.0.23.22 netmask 255.255.255.0   => DRaddr:10.0.23.1
ifconfig eth0 10.0.23.22 netmask 255.255.0.0     => DRaddr:10.0.23.1
ifconfig eth0 10.0.23.22 => Mask:255.255.255.0      DRaddr:10.0.23.1
After:
ifconfig …

nshlib/ifconfig: Generate default IPv4 gateway with netmask

---

interpreters/bas/bas_token.h

````
bas_token.l: In function 'yylex':
Error: bas_token.l:1210:31: error: 'strcpy' writing 1 or more bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
1210 |                             }
|                               ^
In file included from bas_auto.h:77,
from bas_token.l:16:
bas_token.h:103:8: note: at offset 2 into destination object 'name' of size 2
103 |   char name[2/* ... */];
|        ^~~~
```
fix ci break report here: https://github.com/apache/nuttx/actions/runs/7144096261/job/19457106837?pr=11301
ci

interpreters/bas: Fix compiler warning after gcc upgrade to version 12

---

modbus/nuttx/porttimer.c

Please ignore the "Mixed case identifier found" from the 3rd party library:
```
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/modbus/nuttx/porttimer.c:51:9: error: Mixed case identifier found
```
fix ci break reported here: https://github.com/apache/nuttx/actions/runs/7161008130/job/19496039910?pr=11365
ci

Fix nuttx/porttimer.c:71:24: error: a function declaration without a prototype is deprecated

---

nshlib/nsh_command.c
nshlib/nsh_fscmds.c

dmesg add '-c|-C' opt
No impact on previous usage, while supporting "dmesg - c/-C"
os test

nshlib:dmesg add '-c|-C' opt

---

examples/rmtchar/CMakeLists.txt
examples/rmtchar/Kconfig
examples/rmtchar/Make.defs
examples/rmtchar/Makefile
examples/rmtchar/rmtchar.h
examples/rmtchar/rmtchar_common.c
examples/rmtchar/rmtchar_main.c
examples/rmtchar/rmtchar_receiver.c
examples/rmtchar/rmtchar_transmitter.c

* examples/rmtchar: Implement RX and/or TX using the RMT char driver
The RMT (remote control) character driver is used to send and/or receive data packets. Eventually, this app can be used to perform a loopback test to validate the RMT driver implementation.
Enable testing the RMT character driver.
Internal CI testing + ESP32-S2-Saola-1 and ESP32-S3-DevKitC-1 with the new RMT driver (to be sent upstream).

examples/rmtchar: Implement RX and/or TX using the RMT char driver

---

tools/WASI-SDK.defs

WASI-SDK.defs: Simplify CFLAGS filters
And also prevent introduce user defined but wasm clang unsupported flags.
Wasm build
Vela

WASI-SDK.defs: Simplify CFLAGS filters

---

include/fsutils/passwd.h

```passwd_update/adduser/deluser```  should be enabled
if ```CONFIG_FSUTILS_PASSWD_READONLY``` is not defined.

fsutils: passwd: Fix wrong macro

---

interpreters/wamr/Kconfig

At least it's sometimes useful for nuttx sim.
eg. (modified a bit to avoid github autolinks)
```
spacetanuki% lldb ./nuttx
(lldb) target create "./nuttx"
Current executable set to '/Users/yamamoto/git/nuttx/nuttx/nuttx' (x86_64).
(lldb) settings set plugin.jit-loader.gdb.enable on
(lldb) b foo
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) r
Process 37011 launched: '/Users/yamamoto/git/nuttx/nuttx/nuttx' (x86_64)
nsh> mount -t hostfs -o fs=/tmp/wasm /mnt
nsh> iwasm /mnt/test.aot
1 location added to breakpoint 1
Process 37011 stopped
* thread #_1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
frame #_0: 0x0000000105800673 JIT(0x1058002d4)`foo(exenv=0x0000000101284280) at test.c:5
2
3 …
```

interpreters/wamr: add INTERPRETERS_WAMR_DEBUG_AOT option

---

testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/pthread_exit.c
testing/ostest/restart.c
testing/ostest/sighand.c
testing/ostest/signest.c
testing/ostest/suspend.c
testing/ostest/waitpid.c

This is the continuation of the pull https://github.com/apache/nuttx-apps/pull/1500
task_* APIs are unavailable in kernel build mode, replacing with posix_spawn or pthread_* API to pass the case. But posix_spawn require some dependency, for example CONFIG_BUILTIN and CONFIG_LIBC_EXECFUNCS, so pthread_* APIs are used in most scenarios. Some tests should be re-visited because the intent is to user another task (in this case another process) to e.g. receive signals. That will require quite a bit of extra work.
Tests that had to be disabled:
- restart: task_restart() does not work at all with kernel mode so it is disabled entirely
- fpu: make sure the FPU test is not even attempted, because it will cause ASSERT() and stop the test
- vfork: vfork() does not work for some reason in …

ostest: Add initial support for CONFIG_BUILD_KERNEL

---

tools/mkromfsimg.sh

This adds one optional position argument for generated ROMFS file path.
The existing headerfile path is used when the argument is missing, falling back to existing behavior.
No impacts to exsiting users.
checked on Ubuntu Jammy host.

optional argument for generated ROMFS file path.

---

testing/drivertest/drivertest_audio.c

1.call AUDIOIOC_RELEASE when finished
2.make sure the driver dequeue all buffers before free the buffers
let's ignore the false alarm:
```
/home/runner/work/nuttx-apps/nuttx-apps/apps/testing/drivertest/drivertest_audio.c:482:33: error: Operator/assignment must be followed with whitespace
```

drivertest: Fix drivertest_audio crash

---

nshlib/nsh_netcmds.c

"dns" option of `ifconfig` can work just with `CONFIG_NETDB_DNSCLIENT`, no need to depend on `CONFIG_NETINIT_DNS` or `CONFIG_NETINIT_DHCPC`.
command `ifconfig <interface> <ip> dns <xxx>`
Manually & CI

nshlib/ifconfig: Let "dns" option depend on `CONFIG_NETDB_DNSCLIENT`

---

examples/hello_nim/Makefile

The Nim Example App fails to build because the `.nimcache` is located 2 folders up. This PR fixes the location of `.nimcache` in the `Makefile` of the Nim Example App.
`.nimcache` is explained in [this article](https://lupyuen.github.io/articles/nim#inside-nim-on-nuttx).
Nim Example App builds and runs correctly after fixing the `.nimcache` location.
No impact on other apps, since the `Makefile` is used only by the Nim Example App.
We tested on QEMU Arm64:
```bash
$ tools/configure.sh -l qemu-armv8a:nsh
$ make menuconfig
$ make
```
NuttX Build fails because `.nimcache/hello_nim_async.h` could not be found:
```text
./hello_nim_main.c:26:10: fatal error: hello_nim_async.h: No such file or directory
26 | #include "hello_nim_async.h"
```
[(See the Build …

examples/hello_nim: Fix nimcache location

---

netutils/ping/icmp_ping.c

netutils/ping: Optimize stack usage of `icmp_ping`
Can reduce 88~144 Bytes on ARMv7-A depending on optimization level.
`icmp_ping` only
`ping` command & CI

netutils/ping: Optimize stack usage of `icmp_ping`

---

examples/nrf24l01_btle/nrf24l01_btle.c
include/netutils/xtables.h
system/uorb/uORB/uORB.h
testing/monkey/monkey_utils.c

and format the multiple line comments
format change only
ci

Remove @ tag from all comments

---

tools/mkromfsimg.sh

currently `romfs_img_len` is not defined with `const`, but `romfs_img` is.
this PR adds `const` to back `romfs_img_len` so that both are read-only as they are corelated. 
they both were read-only before commit# 2498be1f4083c199d33755f24758d76cd95f9d0f
ROMFS usages
checked with canmv230/knsh

add const for romfs_img_len

---

netutils/libcoap/.gitignore
netutils/libcoap/CMakeLists.txt
netutils/libcoap/Kconfig
netutils/libcoap/Make.defs
netutils/libcoap/Makefile
netutils/libcoap/coap_config.h

added support for coap and testing tools.
server:
when ipv6 is enable:
ap> coap_server
only ipv4 is enable, we need to specify the ip address of the network card:
ap> coap_server -A [ipv4 address]
client:
ap> coap_client -m get coap://[ipv4/6 address]/time
Dec 26 06:41:12
Other Examples:
coap_client -m get coap://[::1]/
coap_client -m get coap://[::1]/.well-known/core
coap_client -m get coap+tcp://[::1]/.well-known/core
coap_client -m get coap://%2Funix%2Fdomain%2Fpath%2Fdgram/.well-known/core
coap_client -m get coap+tcp://%2Funix%2Fdomain%2Fpath%2Fstream/.well-known/core
coap_client -m get coaps://[::1]/.well-known/core
coap_client -m get coaps+tcp://[::1]/.well-known/core
coap_client -m get coaps://%2Funix%2Fdomain%2Fpath%2Fdtls/.well-known/core
coap_client -m get …

libcoap: add makefile, Kconfig and CMakeLists.txt

---

nshlib/nsh_command.c
nshlib/nsh_syscmds.c

nsh cmd rptun: add rptun ping useage description
when rptun -h is entered, the usage of rptun will be displayed.
tested in sim vela.

nsh cmd rptun: add rptun ping useage description

---

nshlib/nsh_ddcmd.c

Print the errno gives more information to debug the dd failed problem.
Should be none
dd in sim

nsh_ddcmd: print errno instead the return value when dd failed
