- nshlib/nsh_mmcmds.c
Compare with "cat /proc/memdump", use "memdump -h/help" is more convenient.
Enchance memdump
memdump -h
> nsh_mmcmds: support "memdump -h/help" to show usage and sequence number

- examples/rpmsgsocket/rpsock_client.c
rpsock_client.c: fix printf format warning as flows
rpsock_client.c:203:30: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 5 has type ‘long unsigned int’ [-Wformat=]
203 |                       printf("client check fail total %d, \
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
204 |                               i %d, %08" PRIx32 ", %08x\n",
|                               ~~~~~~~~~~
205 |                               ALIGN_UP(total), i, intp[i],
206 |                               (ALIGN_UP(total) / sizeof(uint32_t) + i));
|                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                                                   |
|                                                                   long unsigned …
> rpsock_client.c: fix printf format warning

- nshlib/nsh_syscmds.c
nsh syscmds: add CONFIG_RPTUN_PING when use rptun_ping.
rptun_ping can only be used when CONFIG_RPTUN_PING = y.
Tested in sim vela and 86panel.
> nsh syscmds: add CONFIG_RPTUN_PING when use rptun_ping

- interpreters/wamr/Kconfig
- tools/Wasm.mk
Fixes partly: https://github.com/apache/nuttx-apps/issues/2046
> Wasm.mk: disable by default

- netutils/iperf/iperf_main.c
In addition to the CONFIG_NETUTILS_IPERFTEST_DEVNAME configuration, you can specify network cards by parameter to support devices with multiple network interface.
sim:local
> iperf: add parameters to support dynamic device bind

- Application.mk
- examples/hello_zig/Makefile
- examples/hello_zig/hello_zig.zig
This patch adds support of building hello-zig app for kernel mode NuttX.
works with `nuttx-export` containing Zig macros which is available in https://github.com/apache/nuttx/pull/11548
hello_zig elf can build and run in kernel mode NuttX
with `rv-virt/knsh32` on Linux host
> Zig apps: add kernel mode build support

- config.nims
When editing in VSCode, NimSuggest refers to config.nims and tries to find the NuttX .config.
Fixed a problem that .config cannot be read because the environment variable "TOPDIR" is not defined.
Confirmation that completion works with VSCode, etc.
> config.nims: fix NimSuggest crash.

- include/lte/lte_lwm2m.h
- lte/alt1250/callback_handlers/alt1250_evt.c
Notice instance information of LwM2M server operation to application.
Alt1250 Daemon only
Test if Alt1250 daemon works fine on Spresense environment.
> lte/alt1250: Notice instance information

- include/wireless/wapi.h
- wireless/wapi/src/wapi.c
- wireless/wapi/src/wireless.c
Added scanning in passive mode without affecting the scan command.
Cortex-M33 and bcm43xxx Wi-Fi chip
> wapi: Add pscan cmd to trigger a passive scan.

- nshlib/nsh_syscmds.c
The ping subcommand of rptun command is guarded with RPTUN_PING in handler. its help mesg should also have same guard to avoid confusing user.
rptun command 
checked with `sim/rpserver`
> nshcmd/rptun: align help mesg with command handler

- nshlib/Kconfig
- nshlib/nsh_command.c
nshlib: add `expr` command support
It is a mini version for the `expr` command, which implements the features of addition, subtraction, multiplication, division and mod.
Reference: https://www.geeksforgeeks.org/expr-command-in-linux-with-examples/
bl2> expr 5 - 2
3
bl2> set hello 10
bl2> expr $hello - 2
8
bl2> expr 8 a 9
Unknown operator
bl2> expr 20 / 5
4
bl2> expr 10 % 4
2
bl2> expr 10 / 0
operand2 invalid
bl2>
bl2> expr 100 + 0
100
> nshlib: add `expr` command support

- nshlib/nsh_timcmds.c
NuttX build fails otherwise as required structures are not included.
Build fix.
Build pass, app works.
> nsh_timcmds: show RTC time in timedatectl command only if CONFIG_RTC_DRIVER is set

- nshlib/nsh_command.c
- nshlib/nsh_timcmds.c
nsh_timcmds: display date using set format
Reference: https://www.geeksforgeeks.org/date-command-linux-examples/?ref=gcse#9-list-of-format-specifiers-used-with-date-command
date command
ap>
ap> date
Fri, Jan 26 10:23:13 2024
ap>
ap>
ap> date -u "+%A %B %d %T %y"
Friday January 26 02:23:17 24
ap>
ap>
ap> date +%s
1706235968
ap>
ap>
> nsh_timcmds: display date using set format

- testing/getprime/CMakeLists.txt
add CMakeLists.txt to support building with CMake
None
checked with CanMV230
> testing/getprime: add cmake support

- nshlib/Kconfig
- nshlib/nsh.h
- nshlib/nsh_command.c
- nshlib/nsh_syscmds.c
To support rpmsg ioctl, add cmd_rpmsg function, and update rptun ping to rpmsg ping.
depends on https://github.com/apache/nuttx/pull/11618
Able to use rpmsg ioctl cmd.
Tested in sim vela and 86 panel.
> nsh_syscmds: update rptun_ping to rpmsg_ping, add cmd_rpmsg.

- nshlib/nsh_fscmds.c
The define macro was wrong
fscmds works for shm objects
CI pass
> nsh_fscmds.c: Fix CONFIG_FS_SHM -> CONFIG_FS_SHMFS

- interpreters/toywasm/Makefile
- interpreters/toywasm/include/toywasm_version.h
toywasm: update to v38
Tested with sim/macOS/x86-64
> toywasm: update to v38

- benchmarks/spinlock_bench/CMakeLists.txt
- testing/cachespeed/CMakeLists.txt
- testing/smp/CMakeLists.txt
- wireless/ieee802154/CMakeLists.txt
- wireless/ieee802154/i8sak/CMakeLists.txt
- wireless/ieee802154/i8shark/CMakeLists.txt
- wireless/ieee802154/libmac/CMakeLists.txt
- wireless/ieee802154/libutils/CMakeLists.txt
- cmake: fix spinlock_bench compilation
- cmake: add cachespeed
- cmake: add smp test
- cmake: add ieee802154 tools
> port more tools to cmake

- lte/alt1250/alt1250_devevent.c
If the ALT1250_EVTBIT_RESTARTAPI event is received, the ALT1250 daemon changes its state to handle LAPI normally.
Only ALT1250 daemon.
> lte/alt1250: Correspond to ALT1250_EVTBIT_RESTARTAPI event

- lte/alt1250/alt1250_atcmd.c
- lte/alt1250/alt1250_devif.c
- lte/alt1250/alt1250_devif.h
- lte/alt1250/alt1250_reset_seq.c
- lte/alt1250/alt1250_select.c
- lte/alt1250/usock_handlers/alt1250_accepthdlr.c
- lte/alt1250/usock_handlers/alt1250_bindhdlr.c
- lte/alt1250/usock_handlers/alt1250_closehdlr.c
- lte/alt1250/usock_handlers/alt1250_connecthdlr.c
- lte/alt1250/usock_handlers/alt1250_getsocknamehdlr.c
- lte/alt1250/usock_handlers/alt1250_getsockopthdlr.c
- lte/alt1250/usock_handlers/alt1250_ioctl_event.c
- lte/alt1250/usock_handlers/alt1250_ioctl_fwupdate.c
- lte/alt1250/usock_handlers/alt1250_ioctl_ifreq.c
- lte/alt1250/usock_handlers/alt1250_ioctl_normal.c
- lte/alt1250/usock_handlers/alt1250_listenhdlr.c
- lte/alt1250/usock_handlers/alt1250_recvfromhdlr.c
- lte/alt1250/usock_handlers/alt1250_sendtohdlr.c
- lte/alt1250/usock_handlers/alt1250_setsockopthdlr.c
- lte/alt1250/usock_handlers/alt1250_shutdownhdlr.c
- lte/alt1250/usock_handlers/alt1250_sms.c
- lte/alt1250/usock_handlers/alt1250_sockethdlr.c
Fix a bug that caused the application to get stuck when executing the socket API after waking up from hibernation and before executing lte_hibernation_resume().
Only ALT1250 daemon
> lte/alt1250: Fix bug that caused stack when executing the socket API

- examples/rmtchar/rmtchar_transmitter.c
* examples/rmtchar: Increase initial duration time
With higher RMT source clocks, small durations are hard to be
detected. Increasing it makes it easier to enable automated tests.
Makes it easier to enable automated testing
Internal CI testing
> examples/rmtchar: Increase initial duration time

- lte/alt1250/alt1250_atcmd.c
- lte/alt1250/alt1250_atcmd.h
- lte/alt1250/alt1250_reset_seq.c
In some conditions, LTE connection has issue.
To fix it, need to change a modem parameter.
Only ALT1250 daemon.
> lte/alt1250: Force change modem parameter

- examples/elf/tests/helloxx/hello++5.cxx
fix the below build error by correcting the typo (tring -> string)
hello++5.cxx: In member function 'virtual void CThingSayer::ThrowMyThing(const char*)': hello++5.cxx:157:21: error: 'tring' was not declared in this scope
157 |   throw MyException(tring(czSayThis));
|                     ^~~~~
> elf/tests/helloxx: fix build break with elf cpp exceptions example

- examples/modbusmaster/mbmaster_main.c
- include/modbus/mbport.h
- modbus/mb_m.c
- modbus/nuttx/portevent_m.c
- modbus/rtu/mbrtu_m.c
The modbus master exemplo stop to work before the PR [#6038](https://github.com/apache/nuttx/pull/6038l)
Fix modbus master example.
```
$tools/configure.sh stm32f401rc-rs485:modbus_master
$ sudo diagslave -a 10 -b 38400 /dev/ttyUSB0
nsh> modbusmaster
Initializing modbus master...
Creating poll thread.
Sending 100 requests to slave 10
mbmaster_main: Exiting poll thread.
Modbus master statistics:
Requests count:  100
Responses count: 100
Errors count:    0
Deinitializing modbus master...
```
> fix modbus master exemple

- wireless/ieee802154/i8sak/CMakeLists.txt
- wireless/ieee802154/i8sak/Makefile
- wireless/ieee802154/i8sak/i8sak.h
- wireless/ieee802154/i8sak/i8sak_main.c
- wireless/ieee802154/i8sak/i8sak_tracedump.c
- i8sak: add support for tracedump command
used to dump trace log from radio
depends on https://github.com/apache/nuttx/pull/11701
> i8sak: add support for tracedump command

- nshlib/nsh_syscmds.c
nsh/uname: alloc dynamic heap on non-GNU compilers
The alloca() function is machine- and compiler-dependent.  For certain applications, its use can improve efficiency compared to the use of malloc(3) plus free(3).  In certain cases, it can also simplify memory deallocation in applications that use longjmp(3) or siglongjmp(3). Otherwise, its use is discouraged.
N/A
Tasking
> nsh/uname: alloc dynamic heap on non-GNU compilers

- modbus/nuttx/portevent_m.c
- modbus/nuttx/portother.c
- modbus/nuttx/portother_m.c
- modbus/nuttx/porttimer_m.c
fix build warning of PR [11698](https://github.com/apache/nuttx/pull/11698).
```
Cleaning...
Configuring...
Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
Enabling CONFIG_ARM_TOOLCHAIN_CLANG
Building NuttX...
Error: nuttx/porttimer_m.c:117:30: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
117 | void xMBMasterPortTimersClose()
|                              ^
|                               void
Error: nuttx/porttimer_m.c:171:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
171 | void vMBMasterPortTimersDisable()
|                                ^
|                                 void
2 errors generated.
```
Fix build modbus master warning
```
nuttx$ …
```
> modbus_master: fix cmake build warning

- graphics/lvgl/port/lv_port_lcddev.c
Fix crash in lvgldemo while using lcd dev.
Reference: https://github.com/apache/nuttx/issues/11683
CI
ESP32 Wrover
> apps/graphics: add lcddev_obj initialization to fix crash in lcd_dev mode

- testing/getprime/getprime_main.c
This patch attempts to fix the blocking issues encountered with build 6374 of apps/pull/2300.
It needs be used with #11739 in nuttx repo.
CI checker
CI checks.
> build/ci: fix CI blocking unused warning issues (apps repo part)

- examples/lvgldemo/CMakeLists.txt
- graphics/CMakeLists.txt
- graphics/lvgl/CMakeLists.txt
Add LVGL cmake support.
cmake -Bbuild -DBOARD_CONFIG=boards/sim/sim/sim/configs/lvgl_fb -GNinja
> cmake: add lvgl cmake support

- system/lm75/lm75.c
The stm32 common logic board uses /dev/temp0 as
default, but system/lm75/lm75.c is trying to
open /dev/temp instead
Make things work out of box
stm32
> apps: Make /dev/temp0 as default to system/lm75

- nshlib/CMakeLists.txt
- nshlib/Kconfig
- nshlib/Makefile
- nshlib/nsh.h
- nshlib/nsh_init.c
- nshlib/nsh_parse.c
- nshlib/nsh_prompt.c
- nshlib/nsh_session.c
Currently NSH prompt string is determined at build time, this is inflexible in some AMP cases where the same NSH binary runs on different AMP nodes as the same prompt string is showed everywhere. Yet another issue is that empty `NSH_RPOMPT_STRING` config leads to no prompt at all, making people questioning if the system is stalled.
This patch attempts to solve these issues by adding ordered runtime fallbacks for empty NSH_PROMPT_STRING case from sources like environment variable (default to `PS1`) and hostname, both suffixed with ` > `. If all sources are empty, the non-empty suffix string will be used. The patch has little impacts on for existing use cases with non-empty NSH_PROMPT_STRING .
Changes in nshlib/ folder:
- Kconfig:      add NSH_PROMPT_MAX and NSH_PROMPT_ENV configs
- nsh.h: …
> nshlib/prompt: add empty prompt string fallbacks

- nshlib/nsh_command.c
- nshlib/nsh_ddcmd.c
Added "seek" support to the dd command, We can use "seek" to set how many Bytes the written target should skip first.
“dd“ supports seek parameter parsing
local test PASS
> dd:support "seek"

- graphics/lvgl/CMakeLists.txt
graphics/lvgl: remove unused code
Since it has beed used from https://github.com/apache/nuttx-apps/blob/master/graphics/lvgl/CMakeLists.txt#L72-L74
local build
> graphics/lvgl: remove unused code

- nshlib/nsh_command.c
- nshlib/nsh_fscmds.c
The cp command supports recursive copying. Use "cp -r" to copy a folder.
The behavior of mkdir is used during the cp -r process, and the mkdir behavior is skipped when mkdir is unavailable (this may cause unpredictable behavior of cp -r)
local test PASS
> cp:support -r recursive copies

- examples/dac/dac_main.c
Implements simple function generating triangular pattern / saw tooth.
cmd_dac_test - create simple configurable triangle wave to test the DAC
-c count  can create this wave multiple times
-d delay  introduces delay between each value - this can be handy when
measuring only with multimeter
-b bit  resolution determines max value - this depends on the
underlying architecture. By default this is set to 8 bits and
therefore max value 255.
-s step  is the increment added to the previous value. If you need only few
measuring points you can set high value such as 64, if you need finer
steps , set to lower value. The default is 8.
Example use for 8-bit DAC using multimeter
nsh> dac -d 5000 -b 8 -s 16 test
Example use for 12-bit DAC using osciloscope
nsh> dac -d 10 -b 12 -s 4 test
Easier …
> examples/dac: Add test mode

- testing/fmemopen/fmemopen.c
since the back slash is only needed for the long macro definition
code refactor only
ci
> testing/fmemopen: Remove the back slash from long literal string

- netutils/netinit/Kconfig
- netutils/netinit/netinit.c
Some systems the sd card gets mounted later after netinit started this causes netinit to be unable to read the config. 
This pr add a KConfig symbol to set retries to allow delayed mount
Minimal, default behavior is the same
Teensy
> netinit: Add check mount path retry option for delayed mounts

- audioutils/nxaudio/nxaudio.c
- examples/fmsynth/keyboard_main.c
- examples/fmsynth/mmlplayer_main.c
- include/audioutils/nxaudio.h
Fix a freaze BUG when the example is executed again after 1st execution.
examples/fmsynth
Verify if fmsynth examples work again after finished 1st execution, on spresense board.
> examples/fmsynth: Fix freaze when execute it in 2nd time

- examples/hx711/CMakeLists.txt
- examples/hx711/Kconfig
- examples/hx711/Make.defs
- examples/hx711/Makefile
- examples/hx711/hx711_main.c
new example program to text hx711 chip
> examples/hx711: add new program to test hx711 chip

- examples/settings/Kconfig
- examples/settings/Make.defs
- examples/settings/Makefile
- examples/settings/settings_main.c
- include/system/settings.h
- system/settings/Kconfig
- system/settings/Make.defs
- system/settings/Makefile
- system/settings/readme.md
- system/settings/settings.c
- system/settings/storage.h
- system/settings/storage_bin.c
- system/settings/storage_text.c
Last year @fjpanag offered to donate some code to the repo. This is my (second) attempt at making his "settings" functions NuttX compatible along with an example app to check it out
None. This is new.
On my custom board (SAMA5D27C-D1G). 
There  may still be some style and/or NuttX-convention errors/inconsistencies of course. Also, a reviewer previously reported that the dump_cache function was not safe to call from a signal handler but neither I nor the original author can understand why?
> Add Settings Utility and example app

- .gitignore
to fix the ci break reported by:
https://github.com/apache/nuttx/actions/runs/8124056482/job/22205151164?pr=11829
fix ci break
ci
> Ignore all *.lock in apps folder

- .github/workflows/build.yml
the check isn't really enabled and enforce before
due to a mass of false alarm, but recently it break ci frequently, so it's better to remove it now.
ci
ci
> ci: Remove the codecheck from build.yml

- testing/getprime/getprime_main.c
getprime can now run without creating any additional threads. This helps testing pthreads and measuring performance of directly searching primes from main thread versus creating one thread.
Also don't misuse ASSERT() for checking command-line input coming from user.
Tested with ox64:nsh board
> testing/getprime: allow running with zero threads

- testing/ostest/CMakeLists.txt
- testing/ostest/Makefile
- testing/ostest/libc_memmem.c
- testing/ostest/ostest.h
- testing/ostest/ostest_main.c
ostest: add test for libc memmem() function
See https://github.com/apache/nuttx/pull/11889
> ostest: add test for libc memmem() function

- netutils/dhcpc/dhcpc.c
dhcpc can run in async mode with a background thread. this can be cancelled (when the link goes down)
but when the link goes up again the variable dhcpc_state->cancel is not reinitialized, so the async mode works only once
dhcpc async thread can be started multiple times
verified to work experimentally on a stm32f4 custom board
> dhcpc: reset the state of the "cancel" variable when restarting the async dhcpc thread

- examples/hello_rust/Makefile
The current issue with the "hello_rust_main.rs" file not building successfully is addressed by this pull request, which aims to enhance the build process by incorporating the "-O" flag into the rustc flags. This adjustment is crucial for optimizing the code at level 2, ensuring better performance and efficiency. The modifications are made in the Makefile located at `apps/examples/hello_rust/Makefile`
The discussion surrounding the Rust build issue can be found in the [Rust-Lang issue #245](https://github.com/rust-lang/compiler-builtins/issues/245), where various aspects of the problem and potential solutions are discussed. This issue highlights the importance of optimization flags in the Rust compiler and how they can impact the build process and the resulting application's performance. …
> examples/hello_rust: Add -O flag

- netutils/netinit/Kconfig
- netutils/netinit/netinit.c
Adds an option to derive a MAC Address from the board's unique_id.  Essentially just retrieves the unique_id and performs bit manipulation to ensure it is a valid unicast, locally administered MAC address.  This is useful for Ethernet hardware that does not have a built-in MAC address.  
Requires BOARDCTL_UNIQUEID.
Adds the NETINIT_UIDMAC Kconfig option.
Allows use of multiple boards on the same network without having to manually configure different MAC addresses for each.
Enable NETINIT_NOMAC and NETINIT_UIDMAC.  Your Ethernet interface should initialize with a unique MAC address based on the board's ID.
Tested on a RP2040 based W5500-EVB-Pico evaluation board and a custom board.
> Derive MAC Address from board unique_id

- testing/unity/CMakeLists.txt
cmake: add support for Unity
local
> cmake: add support for Unity

- netutils/connectedhomeip/CMakeLists.txt
Otherwise, the compilation may fail due to changes in the pigweed code
sim:matter
> matter: use a fixed version of pigweed

- nshlib/Kconfig
- nshlib/nsh.h
- nshlib/nsh_command.c
- nshlib/nsh_syscmds.c
nshlib/irqaff: add irq affinity command
add support for set an IRQ affinity to CPUs by software
N/A
Depends on: https://github.com/apache/nuttx/pull/12020
qemu-armv7a/bmp ostest on single core
```
nuttx$ qemu-system-arm -cpu cortex-a7 -nographic      -machine virt,virtualization=off,gic-version=2 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx -smp 4 
NuttShell (N
NuttS
Nutt
NH) NutShellShetSutlltX- (NSH) NuttX-10.4.0
4t(NheSH) NuttX-ns0.h> 1ll (NSH) Nu0.4.0
nstX-1h> 
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK   USED  FILLED COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 004080 000536  13.1%  CPU0 IDLE
1     1 192 RR …
```
> nshlib/irqaff: add irq affinity command 

- Make.defs
hi @xiaoxiang781216 @anchao 
I saw the issue discussed in this PR https://github.com/apache/nuttx/pull/11997 about ltp failure
we previously used batch splitting to solve the problem of `argument too long` during compilation.
but there is a problem here in `nuttx/tools/Config.mk`
application `OBJS` clean call `CLEAN` macro defined in nuttx/tools/Config.mk
variables are expand directly within the marco.
https://github.com/apache/nuttx/blob/806d783fd6dab9cb4de79da2516e9ece71b4efdc/tools/Config.mk#L597-L601
this is no problem in the nuttx call, because the obj generated by nuttx compilation definitely does not have a suffix.
however, there is uncertainty in the obj expansion of the Applications call.
---
This patch follows the previous design of batch splitting and performs batch …
> Make.defs:make all AROBJS and OBJS batch cleaned in Application

- interpreters/wamr/CMakeLists.txt
This patch follows the platform in wasm-micro-runtime to add CMake build support for nuttx
this should cooperate with https://github.com/bytecodealliance/wasm-micro-runtime/pull/3256
no impact currently
requires wamr version support
> cmake:migrate wamr to CMake build

- nshlib/Kconfig
Never disable HELP and ?
Users will be able to see available commands in NSH
stm32f103-minimum
Please ignore the CI failing, it needs https://github.com/apache/nuttx/pull/12038 because default board config changed (chichen-egg dilemma).
> apps/nshlib: Never disable HELP and ?

- .github/workflows/build.yml
function bloaty() Add  -D CMAKE_INSTALL_PREFIX="${NUTTXTOOLS}"/bloaty. Improves workflow execution time because it is now cached.
Changed reference file to calculate the hash for key of actions/cache@v4. Now it is darwin.sh.
ci
ci
> Minor improvement for tools/ci:  Fixed cmake build of bloaty and installation in darwin.sh script.

- testing/monkey/monkey_main.c
Fix comparing `uint8_t` type variable with 0.
None.
None.
> testing/monkey: fix unsigned type comparison with 0

- nshlib/Kconfig
Never disable HELP and ?
Users will be able to see available commands in NSH
stm32f103-minimum
Please ignore the CI failing, it needs https://github.com/apache/nuttx/pull/12038 because default board config changed (chichen-egg dilemma).
> {bp-2344} apps/nshlib: Never disable HELP and ?

- testing/ostest/cancel.c
Revert "testing/ostest/cancel: joining a detached/canceled thread should return EINVAL, not ESRCH"
This reverts commit 69e497f68127cad345fd13786c5342822c58173f.
In order to ensure the detached thread obtain the correct return value from pthread_join()/pthread_cancel(), the detached thread will create joininfo to save the detached status after thread destroyed.  If there are too many of detached threads in the process group, the joininfo will consume too much memory. This is not friendly to embedded MCU devices.
This commit keep the semantics as #11898 was introduced, will no longer save joininfo for detached threads to avoid wasting memory.
Refer PR:
https://github.com/apache/nuttx/pull/12106
Fix issue https://github.com/apache/nuttx/issues/12096
ostest / ci-check
> Revert "testing/ostest/cancel: joining a detached/canceled thread should return EINVAL, not ESRCH"

- examples/pipe/pipe_main.c
A file was created during the test, and it was not deleted when it was used up
> examples/pipe:removes useless data from test cases

- nshlib/nsh_command.c
Currently new users when try to run NuttX using the SIM get stuck into simulator, because they have no idea that poweroff command is used to leave it. Let use KISS approach and use quit as alias to poweroff command.
Make it easier to user to leave SIM
sim
> apps/nsh_commands: Use quit to poweroff

- benchmarks/cachespeed/Kconfig
- benchmarks/coremark-pro/Kconfig
- benchmarks/coremark/Kconfig
This patch changes the enable options of coremark, coremark-pro and cachespeed from bool to tristate.
This allows the user to select the benchmark to be built as a elf module, which can be loaded and executed on the target dynamically.
None
> benchmarks: Change options from bool to tristate

- include/netutils/netlib.h
- netutils/netlib/CMakeLists.txt
- netutils/netlib/Makefile
- netutils/netlib/netlib_conntrack.c
- system/conntrack/Kconfig
- system/conntrack/Make.defs
- system/conntrack/Makefile
- system/conntrack/conntrack.c
A simple tool like Linux's `conntrack` command, only supports printing NAT connections now.
```
nuttx> conntrack -E
[NEW] icmp  src=192.168.21.66 dst=1.2.3.4 type=8 code=0 id=26739 src=1.2.3.4 dst=192.168.11.1 type=0 code=0 id=26739
[NEW] tcp   src=192.168.21.66 dst=1.2.3.4 sport=38446 dport=80 src=1.2.3.4 dst=192.168.11.1 sport=80 dport=38446
[DESTROY] icmp  src=192.168.21.66 dst=1.2.3.4 type=8 code=0 id=26739 src=1.2.3.4 dst=192.168.11.1 type=0 code=0 id=26739
```
```
nuttx> conntrack -L
tcp   src=192.168.21.66 dst=1.2.3.4 sport=38446 dport=80 src=1.2.3.4 dst=192.168.11.1 sport=80 dport=38446
icmp  src=192.168.21.66 dst=1.2.3.4 type=8 code=0 id=26739 src=1.2.3.4 dst=192.168.11.1 type=0 code=0 id=26739
conntrack: 2 flow entries have been shown.
```
Our own implementation behaves like …
> apps/system: Add `conntrack` command

- netutils/dhcp6c/dhcp6c.c
Fix compiler warnings due to type inconsistencies in printf-style format strings.
None to be expected.
Build tests show that warnings are gone.
> netutils/dhcp6c: Fix printf-style format strings

- examples/mqttc/mqttc_pub.c
Added QOS argument option. Users can optionally change QOS to 0/1/2.
None.
./tools/configure.sh esp32-devkitc:mqttc
make
> examples/mqttc: Add QOS argument option

- boot/mcuboot/Kconfig
- boot/mcuboot/Makefile
Configuration option MCUBOOT_REPOSITORY adds possibility to configure MCUboot GIT repository to be downloaded (for specified hash commit or version). This allows to use different forks and personal repositories.
MCUboot main repository is kept as default option.
> mcuboot: add option to specify MCUboot source git repository

- import/Make.defs
This matches the entry name change in [nuttx/pull/12201](https://github.com/apache/nuttx/pull/12201).
kernel mode app building with `make import`
`rv-virt/knsh64` and CI checks
> build/import: matching nuttx side #12201

- testing/ostest/fpu.c
- testing/ostest/fpu.c: align FPU context
some architectures requires FPU context to be aligned, for example x86-64 when used with XSAVE instruction must be aligned to 64
x86
> testing/ostest/fpu.c: align FPU context

- graphics/lvgl/0001-fix-demo-fix-compile-warning.patch
- graphics/lvgl/CMakeLists.txt
- graphics/lvgl/Makefile
Add patch to fix the compile warning, which is already fixed in upstream: https://github.com/lvgl/lvgl/pull/6100
No.
Tested with sim:lvgl_lcd
> apps/lvgl: fix compile warning

- graphics/lvgl/Makefile
LVGL uses `shell find` to set CSRCS. LVGL sources have already been deleted when `Application.mk ` is included at file end, thus causing the warning.
lvgl/lvgl.mk
```makefile
LVGL_PATH ?= ${shell pwd}/lvgl
ASRCS += $(shell find $(LVGL_PATH)/src -type f -name '*.S')
CSRCS += $(shell find $(LVGL_PATH)/src -type f -name '*.c')
CSRCS += $(shell find $(LVGL_PATH)/demos -type f -name '*.c')
CSRCS += $(shell find $(LVGL_PATH)/examples -type f -name '*.c')
CXXEXT := .cpp
CXXSRCS += $(shell find $(LVGL_PATH)/src -type f -name '*${CXXEXT}')
AFLAGS += "-I$(LVGL_PATH)"
CFLAGS += "-I$(LVGL_PATH)"
CXXFLAGS += "-I$(LVGL_PATH)"
```
Cleaning...
find: '/github/workspace/sources/apps/graphics/lvgl/lvgl/src': No such file or directory find: '/github/workspace/sources/apps/graphics/lvgl/lvgl/src': No such …
> apps/lvgl: fix distclean warnings

- testing/sd_bench/sd_bench_main.c
- testing/sd_stress/sd_stress_main.c
Add the static keyword to required function and variable delcaration to reduce their scope. Stops namespace pollution in `CONFIG_BUILD_FLAT`
Stops symbol collision when `CONFIG_TESTING_SD_BENCH` and `CONFIG_TESTING_SD_STRESS` are enables simultaneously. 
Enable `CONFIG_TESTING_SD_BENCH` and `CONFIG_TESTING_SD_STRESS` at the same time.
> testing/sd_*: Restrict function and variable scope to current file.

- wireless/wapi/src/wireless.c
Avoid wrq.u.essid.length being different from the actual length
cortex-m55
> wapi: use strlen to calc the length of ssid

- benchmarks/cachespeed/CMakeLists.txt
CONFIG_TESTING_ -> CONFIG_BENCHMARK_
fix Relative file path does not match actual file.
none
> benchmarks/cachespeed/CMakeLists.txt: fix the names of the config entry

- testing/ramtest/CMakeLists.txt
CONFIG_SYSTEM_ -> CONFIG_TESTING_
fix Relative file path does not match actual file.
none
> testing/ramtest/CMakeLists.txt: fix the names of the config entry

- system/adb/Makefile
Will cause compilation warning if NDEBUG is defined We can't modify the code of the external library, so let's ignore it
microADB/hal/hal_uv_client_usb.c:90:13: warning: unused variable 'ret' [-Wunused-variable]
90 |         int ret = uv_read_start((uv_stream_t*)&client->pipe,
> system/adb: Ignore warnings for using variables

- wireless/bluetooth/nimble/CMakeLists.txt
- wireless/bluetooth/nimble/Makefile.nimble
Will cause compilation warning if NDEBUG is defined We can't modify the code of the external library, so let's ignore it
services/ans/src/ble_svc_ans.c:450:9: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
450 |     int rc;
|         ^~
> nimble: Ignore nimble compile warnings

- interpreters/wamr/Kconfig
Also, add a help text to explain the current situation.
cf. https://github.com/bytecodealliance/wasm-micro-runtime/pull/3419
> wamr: flip the default of INTERPRETERS_WAMR_DISABLE_HW_BOUND_CHECK

- boot/mcuboot/Makefile
Will cause compilation warning if NDEBUG is defined We can't modify the code of the external library, so let's ignore it
mcuboot/boot/bootutil/src/loader.c:1265:9: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
1265 |     int rc;
|         ^~
> mcuboot: Ignore mcuboot compile warnings

- interpreters/wamr/Kconfig
The corresponding WAMR change:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2348
> wamr: Add a few options for esp32s3

- testing/ostest/ostest_main.c
Fix config name to execute vfork() test.
CONFIG_ARCH_HAVE_VFORK -> CONFIG_ARCH_HAVE_FORK
> testing/ostest: Fix config name

- interpreters/toywasm/Makefile
Will cause compilation warning if NDEBUG is defined We can't modify the code of the external library, so let's ignore it
> toywasm: ignore compile warnings

- system/spi/spi_exch.c
Previously, when delay control was enabled, spi_transfer would pass junk values down to the underlying driver because these values where not initialized.
Setting them to zero provides a predictable result considering they are not controlled by this tool.
SPI tool provides consistent value to the underlying driver's delay characteristics when enabled.
SPI tool with custom SPI driver.
> system/spi: Set SPI delay characteristics to zero when enabled.

- nshlib/nsh_syscmds.c
For furthur domain usage, CONFIG_PM_NDOMAINS maybe not from .config,
possible generated from <nuttx/power/pm.h>
None
CI-test
> add include to handle when PM_NDOMAINS from pm.h

- interpreters/wamr/Kconfig
from:
ARCH_TEXT_HEAP_SEPARATE_DATA_ADDRESS
ARCH_TEXT_HEAP_WORD_ALIGNED_READ
to:
ARCH_HAVE_TEXT_HEAP_SEPARATE_DATA_ADDRESS
ARCH_HAVE_TEXT_HEAP_WORD_ALIGNED_READ
tested on esp32s3-devkitc
> wamr: rename a few recently-added nuttx options

- system/adb/logcat_service.c
Fix ci error reported here:
https://github.com/apache/nuttx/actions/runs/9153517935/job/25162649194?pr=12380
microADB
ci
> Fix Error: logcat_service.c:69:11: error: variable 'ret' set but not used

- system/taskset/taskset.c
taskset.c: In function 'taskset_main':
Error: taskset.c:141:48: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'cpu_set_t' {aka 'long unsigned int'} [-Werror=format=]
141 |       printf("pid %d's current affinity mask: %x\n", pid, cpuset);
|                                               ~^          ~~~~~~
|                                                |          |
|                                                |          cpu_set_t {aka long unsigned int}
|                                                unsigned int
|                                               %lx
cc1: all warnings being treated as errors
make[2]: *** [/github/workspace/sources/apps/Application.mk:271: taskset.c.github.workspace.sources.apps.system.taskset.o] Error 1
make[2]: …
> Fix compiler errors

- system/nxdiag/Makefile
* system/nxdiag: Remove unnecessary `--depth` parameter
* Espressif common headers do not require it and the parameter is not supported for some GIT operations.
Enable using local `http`-based URL for `ESP_HAL_3RDPARTY_URL`.
Internal CI testing
> system/nxdiag: Remove unnecessary `--depth` parameter

- examples/nxscope/nxscope_main.c
- system/sensorscope/CMakeLists.txt
- system/sensorscope/Kconfig
- system/sensorscope/Make.defs
- system/sensorscope/Makefile
- system/sensorscope/sensorscope_main.c
- examples/nxscope: add static to private functions
- nxscope: add sensor streaming tool
This tool allows you to send sensor data via the nxscope interface.
Useful when we test sensors or when we just need a tool to visualize
data from sensors.
Works only with the new sensor framework.
new tool
thingy53 and nxscli tool
Below is an example of a data stream visualized with plotjuggler
> logging/nxscope: add tool to stream sensor data

- examples/usrsocktest/usrsocktest_basic_connect.c
Fix the warning reported here: https://github.com/apache/nuttx/pull/12320#issuecomment-2123613920
minor
ci
> Fix Error: usrsocktest_basic_connect.c:112:7: error: variable 'ret' set but not used

- testing/ostest/ostest_main.c
testing/ostest: temporary remove vfork test on arch/sim
fix cifailed
> testing/ostest: temporary remove vfork test on arch/sim

- examples/sotest/lib/Makefile
- examples/sotest/lib/dynload/.gitignore
- examples/sotest/lib/dynload/Makefile
- examples/sotest/lib/dynload/dynload.c
- examples/sotest/sotest_main.c
* examples/sotest/lib/Makefile
- Add dynload directory to build
* examples/sotest/lib/dynload/Makefile
- Build the dynload shared object test
* examples/sotest/lib/dynload/dynload.c
- Test case for loading of ET_DYN shared objects
* examples/sotest/lib/dynload/.gitignore
- Exclude built object from git
* examples/sotest/sotest_main.c
- Load and invoke the dynload test
Support of ET_DYN shared objects was added to NuttX, this PR adds a test.
New test `dynload` is built.
Run `sotest` and the `dynload` shared object will be loaded, a symbol located and invoked, and the module unloaded.
> Add loading of ET_DYN shared object test to sotest

- benchmarks/dhrystone/.gitignore
- benchmarks/superpi/.gitignore
benchmark: update gitignore for superpi and dhrystone
ignore downloaded files for superpi and dhrystone
local build
> benchmark: update gitignore for superpi and dhrystone

- testing/drivertest/drivertest_pm_runtime.c
sleep(3) * 10 times used 30s, for test case don't have to use that long time.
when SMP,  when workq task priority will not 100% percent suspend the current thread, will cause the 
pm_runtime_set_autosuspend_delay(_, 0) case failed.
None.
CI-test
> pm_rumtime: test shorten time, make compatible with SMP.

- system/telnetd/CMakeLists.txt
Adds CMake support for `system/telnetd`
CMake
- local testing with `rv-virt`
- CI checks
> system/telnetd: add CMake

- testing/ostest/fpu.c
revises fpu test to support rv64ilp32.
ostest
- local testing with `rv-virt`
- CI checks
> testing/ostest: fpu.c for rv64ilp32

- examples/audio_rttl/CMakeLists.txt
- examples/audio_rttl/Makefile
- examples/bmi160/Makefile
- examples/charger/Makefile
- examples/fxos8700cq_test/Makefile
Remove unnecessary SDKDIR variable from some Makefiles.
And fix audio_rttl to pass cmake build.
> examples: Remove unnecessary descriptions from Makefile

- examples/stepper/stepper.c
Fix typo inside for() loop
Fix
STM32F401RC-RS485
> examples/stepper: Fix typo inside for() loop

- testing/smart_test/smart_test.c
testing/smart_test: Fix Wrong Offset in Fseek from SEEK_END
testing/smart_test/smart_test.c: To seek to the last 30 bytes of the file, offset from SEEK_END should be negative.
Bug fixed.
```
nsh> smart_test -c 1000 -s 1000 -w 1000 /mnt/smart
Creating file /mnt/smart for write mode
Writing test data.  2000 lines to write
1999
Done.
Performing 1000 random seek tests
1000
Append test passed
Performing 1000 random seek with write tests
999
Pass
Creating circular log with 40000 records
Performing 1000 circular log record update tests
999
Pass
```
> Fix Wrong Offset in Fseek from SEEK_END

- testing/sd_bench/sd_bench_main.c
- testing/sd_stress/sd_stress_main.c
testing/[sd_bench|sd_stress]: Make Printing Compatible for Both 32-bit and 64-bit Environments.
Currently, on 64-bit environment, for example, qemu-armv8a, compilation of `sd_bench` and `sd_stress` are broken due to [type errors](https://gist.github.com/Windrow14/c42b6ee36e749c3d264678a82ed2a1cc).
testing/sd_bench/sd_bench_main.c:
testing/sd_stress/sd_stress_main.c: `size_t` type should be printed with `%zu` instead of `%u`.
Bugs fixed.
Verify compilation with:
- 32-bit environment configuration: esp32s3-devkit:smp
- 64-bit environment configuration: qemu-armv8a:netnsh
Run `sdstress` and `sdbench` test in virtual environment:
```
qemu-system-aarch64 \
-cpu cortex-a53 \
-smp 4 \
-nographic \
-machine virt,virtualization=on,gic-version=3 \
-chardev stdio,id=con,mux=on \
-serial chardev:con …
```
> [sd_bench|sd_stress]: Compatible Sd Test Printing

- netutils/netinit/netinit.c
Fix error caused by netinit code assuming CONFIG_NETINIT_DNS was enabled
It will avoid error case the user select the DHCPC but forget to enable CONFIG_NETDB_DNSCLIENT
N/A
> Fix error caused by netinit code assuming CONFIG_NETINIT_DNS was enabled

- system/nxcodec/CMakeLists.txt
- system/nxcodec/Kconfig
- system/nxcodec/Make.defs
- system/nxcodec/Makefile
- system/nxcodec/nxcodec.c
- system/nxcodec/nxcodec.h
- system/nxcodec/nxcodec_context.c
- system/nxcodec/nxcodec_context.h
- system/nxcodec/nxcodec_main.c
Add nxcodec for v4l2m2m decoder/encoder verification.
```
ap> nxcodec -h
NxCodec Version: 1.00
Usage: nxcodec -d devname -s [wxh] -f [informt] -i infile -f [outformat] -o outfile
Default settings for decoder parameters
Options:
-d | --device  Video device name
-s | --size    Size of stream
-h | --help    Print this message
-f | --format  Format of stream
-i | --infile  Input filename for M2M devices
-o | --outfile Outputs stream to filename
```
NA
**decoder**
```
nsh> mount -t hostfs -o fs=/path/from/ /stream
nsh> nxcodec -d /dev/video1 -i /stream/256x144.h264 -o /stream/256x144-yuv420p-out.yuv
```
**encoder**
```
nsh> mount -t hostfs -o fs=/path/from/ /stream
nxcodec -d /dev/video2 -s 256x144 -f YU12 -i /stream/256x144-yuv420p.yuv -f H264 -o /stream/256x144-out.h264
```
```
> V4l2m2m nxcodec

- interpreters/wamr/Kconfig
There is little reason to prefer the ancient version from 2021.
> wamr: bump the default version

- examples/telnetd/telnetd.c
Add support to reset command via Device Configuration over Telnet
Users will be able to reset the board over telnetd
- Configure, build and load the firmware on device.
- Use telenet to access the board
- Set command reset 
> Device Configuration over Telnet
> You can add functions to setup your device
> Type '?' and press for help
> cfg> ?
> Available commands:
> help, ? - show help
> reset - reset the board
> exit - exit shell
> examples/telnetd: Add support to reset command

- lte/alt1250/Kconfig
The change by https://github.com/apache/nuttx/pull/12639 to enable CONFIG_NET_ICMP as default
has made it necessary to enable CONFIG_MM_IOB which is unnecessary for usrsock.
CONFIG_NET_USRSOCK_ICMP should be enabled if usrsock is used.
LTE ALT1250
> lte/alt1250: Select NET_USRSOCK_ICMP if LTE_ALT1250 is enabled

- .github/workflows/build.yml
added option -N Use CMake with Ninja as the backend.
depends on this PR https://github.com/apache/nuttx/pull/12721
There should be no impact.
CI
> github/workflows/build.yml: added option -N job docker

- interpreters/wamr/Kconfig
wamr: add a few missing options to match the wamr repo counterpart
> wamr: add a few missing options to match the wamr repo counterpart

- system/i2c/i2c_common.c
- system/i2c/i2c_dev.c
- system/i2c/i2c_main.c
- system/i2c/i2ctool.h
The `i2ctool dev` command now supports an additional command-line flag, `-z`, to the `dev` command. This flag will use a zero-byte write request over I2C as the scan instead of the default 1 byte read. This sometimes allows for discovery of more devices, such as the SHT41 temperature and humidity sensor, and the MS5611 barometric pressure sensor.
This PR closes #994.
This should save some developers time debugging or wondering why their devices didn't show up (and trying to wrongly diagnose a hardware issue like myself :laughing:).
Using the previous version of this command on an I2C bus with the following sensors:
- MS5611 barometric pressure sensor (2, at 0x76 and 0x77)
- SHT41 temperature and humidity sensor (0x44)
- MAXM10S GPS (0x42)
- M24C02 EEPROM (0x50)
- LSM6DSO32 IMU (0x6b)
The …
> `i2ctool dev` command now uses an empty write header to scan the I2C bus

- .github/workflows/build.yml
Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of actions/upload-artifact or actions/download-artifact.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This PR removes the following warning annotations:
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/download-artifact@v3, actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node2 …
> build.yml: Updated the workflow to use version v4 of the actions/upload-artifact and actions/download-artifact

- examples/camera/camera_main.c
In camera_main.c, the dev paths of capture_initialize() and open() are different. So open could always failed.
Only camera example.
Test the camera example works well with sprsense:camera config.
> examples/camera: Fix wrong device file path

- .github/workflows/build.yml
**job msys2** fix
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
python-xyz', where xyz is the package you are trying to
install.
If you wish to install a non-MSYS2-packaged Python package,
create a virtual environment using 'python -m venv path/to/venv'.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 66[8](https://github.com/apache/nuttx/actions/runs/10140159746/job/28034852319?pr=12787#step:4:9) for the detailed specification.
see this PR …
> build.yml: fix error: externally-managed-environment

- examples/qencoder/qe.h
- examples/qencoder/qe_main.c
Normally, the qencoder position is obtained using the QEIOC_POSITION ioctl call. Adding the -i argument uses the QEIOC_GETINDEX to obtain the qe_index_s struct containing the position alongisde other fields.
Tested locally on the SaMoCon board with commands
```
qe -i -p /dev/qe0  # successful QEIOC_GETINDEX on /dev/qe0
qe -i -p /dev/qe1  # successful QEIOC_GETINDEX on /dev/qe1
qe -i /dev/qe0     # only QEIOC_POSITION on /dev/qe0
qe -i /dev/qe1     # only QEOIC_POSITION on /dev/qe1
```
> examples/qencoder: obtain samples using the QEIOC_GETINDEX ioctl call

- .github/workflows/build.yml
Divided jobs risc-v and xtensa to finish workflow under 2 hours.
depends on this PR https://github.com/apache/nuttx/pull/12793
speeds up workflow
CI
> build.yml: Added jobs to speed up CI checks.

- nshlib/nsh_ddcmd.c
- As was merged in commit 1852731df87e5895e299b74aabdb1984b7e3f795 on dd_main.c: lseek returns -1 on error.
Should be consistent in nsh_ddcmd.c and nsh_main.c.
> nsh_dd: fix lseek return check.

- testing/ostest/ostest_main.c
The test was disabled because of a bug in the NuttX kernel, which is now fixed. Obviously depends on the fix.
Enable vfork test
rv-virt:knsh64 + ostest
Depends on https://github.com/apache/nuttx/pull/12820
> ostest: Enable vfork test for BUILD_KERNEL

- testing/ostest/ostest_main.c
This enables fpu_test() calling for FLAT build only, to be in line with the `fpu.c`.
`ostest` doesn't fail for PROTECTED build
- local checks with rv-virt:pnsh64
- CI checks
> ostest/fpu_test: enable for FLAT mode only

- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/ISSUE_TEMPLATE/002_feature_request.yml
- .github/ISSUE_TEMPLATE/003_help.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/issue_labeler.yml
**-Template**
Bug report
Report a bug to improve NuttX stability
Feature request
Request an enhancement for NuttX
General Help
Get general support regarding NuttX
Of course, others can be added. !!! :)
**-Action**
An action for automatically labelling issues
**Keywords**
Keywords are present in the dropdowns (the user can select more than one option) of the form Bug report and are:
- BSD, Linux, Mac, Windows, Other
- all, arm, arm64, avr, ceva, hc, mips, misoc, openrisc, renesas, risc-v, simulator, sparc, tricore, x86, x86_64, xtensa, z16, z80
- Applications, Api, Board support, Build System, Configuring, Debugging, Drivers, File System, Installing, Kconfig, Kernel, Memory Management, Native port, Networking, OS Components, Posix, Sensors, Specific Peripheral
Of course these keywords are …
> Issues: Added Issue templates

- examples/leds_rust/Kconfig
- examples/leds_rust/Make.defs
- examples/leds_rust/Makefile
- examples/leds_rust/leds_rust_main.rs
- examples/leds_rust/nuttx.rs
- This PR adds `examples/leds_rust` to call NuttX POSIX APIs like `open()` and `ioctl()`, so that it blinks an LED
- The `leds_rust` app is also used for testing the GPIO and LED Drivers for Ox64 BL808 SBC and QEMU RISC-V Emulator in Google Summer of Code
- `leds_rust` be executed locally on Linux / macOS / Windows, by commenting out the first 2 lines of code
- The code is based on `examples/leds` in C, and `examples/hello_rust` in Rust
- `Kconfig`: Configuration file for `leds_rust` that defines `EXAMPLES_LEDS_RUST`
- `Make.defs`: Build the app if `EXAMPLES_LEDS_RUST` is enabled
- `Makefile`: Makefile for `leds_rust`
- `leds_rust_main.rs`: Call NuttX POSIX APIs and LED driver to blink the LED
- `nuttx.rs`: NuttX Module for Rust to access the NuttX POSIX APIs in a safer way
- With this …
> examples/leds_rust: Add Rust App for blinking the LED

- testing/memstress/memorystress_main.c
Initialize the pointer to avoid the pointer being unknown when the memory alloc fails
```
In function 'memorystress_iter',
inlined from 'memstress_main' at memorystress_main.c:475:10:
memorystress_main.c:289:10: error: 'ptr' may be used uninitialized [-Werror=maybe-uninitialized]
289 |       if (ptr == NULL)
|          ^
memorystress_main.c: In function 'memstress_main':
memorystress_main.c:248:20: note: 'ptr' was declared here
248 |       FAR uint8_t *ptr;
|                    ^~~
```
> testing/memstress:Initialize the pointer

- nshlib/nsh_fscmds.c
do
{
nbyteswritten = write(wrfd, iobuffer, nbytesread);
if (nbyteswritten >= 0)
The write return type is ssize_t, which is different in size from the originally declared type, so the unified type is ssize_t
None
> nshlib/fscmds:Fix write overflow during cp -r process

- benchmarks/coremark-pro/Makefile
Avoiding warnings caused by source code implementation leads to build failure. Most warnings are undef and the value is 0. We think it is not enabled.
None
> coremark-pro:Ignore the implementation warning

- testing/memstress/memorystress_main.c
Support enabling multi-thread stress testing. Added "-x" to set the number of threads, the default is 1
memstress support multi-thread testing.
> testing/memstress:Support enabling multi-threaded stress testing

- testing/cachetest/Kconfig
- testing/cachetest/Make.defs
- testing/cachetest/Makefile
- testing/cachetest/cachetest_main.c
A tool is provided to test the case of data correctness after cache flush. It requires an uncacheable offset to check whether the uncacheable address is consistent with the data in the buffer after calling up_dcache_flush.
A new test tool has been added
Through this case, we found the cache consistency problem
> cachetest:Tools for testing cache and uncacheable

- benchmarks/dhrystone/Makefile
Warnings have no impacton the program itelf.
The function implementation does not specify a return type, and is treated as a void return value function during use, so it is ignored. 
```
CC:  icmpv6_ping.c dhrystone/v2.1/dhry_2.c:30:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
30 | Proc_6 (Enum_Val_Par, Enum_Ref_Par)
| ^~~~~~
2. The implementation of some functions is opposite to the calling position, and the processing can be ignored dhrystone/v2.1/dhry_2.c:39:9: warning: implicit declaration of function ‘Func_3’ [-Wimplicit-function-declaration]
39 |   if (! Func_3 (Enum_Val_Par))
3. This function is called from dhry_2.c and void behavior is expected. dhrystone/v2.1/dhry_2.c:30:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
30 | Proc_6 …
```
> dhrystone:Ignore warnings. 

- nshlib/nsh_ddcmd.c
Fixed NSH_CMDOPT_DD_STATS output format warning in 64-bit environment
```
In file included from nsh_ddcmd.c:44:
nsh_ddcmd.c: In function 'cmd_dd':
nsh_ddcmd.c:456:20: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
456 |   nsh_output(vtbl, "%llu bytes copied, %u usec, ",
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
457 |              total, (unsigned int)elapsed);
|              ~~~~~
|              |
|              uint64_t {aka long unsigned int}
nsh_console.h:55:49: note: in definition of macro 'nsh_output'
55 | #  define nsh_output(v, ...)   (v)->output(v, ##__VA_ARGS__)
|                                                 ^~~~~~~~~~~
nsh_ddcmd.c:456:24: note: format string is …
```
> nshlib/ddcmd:Fixed NSH_CMDOPT_DD_STATS output format warning

- benchmarks/fio/CMakeLists.txt
- benchmarks/iozone/CMakeLists.txt
Provides CmakeList support for the following benchmarks:
1. fio
2. iozone
None
> Benchmark add cmake

- benchmarks/ramspeed/Kconfig
- benchmarks/ramspeed/ramspeed_main.c
1. Fixed memleak caused by "ramspeed -a"
2. Add more print logs
3. Improve test accuracy, now print in double type in us time unit
4. Optional test item, if we do not pass in the src address, only memset will be executed
None
> Ramspeed improve

- builtin/exec_builtin.c
- include/builtin/builtin.h
- nshlib/nsh.h
- nshlib/nsh_altconsole.c
- nshlib/nsh_builtin.c
- nshlib/nsh_command.c
- nshlib/nsh_console.c
- nshlib/nsh_console.h
- nshlib/nsh_fileapps.c
- nshlib/nsh_fscmds.c
- nshlib/nsh_parse.c
- nshlib/nsh_script.c
- nshlib/nsh_timcmds.c
- testing/cmocka/cmocka_main.c
This is an attempt to refactor nsh to allow commands to have input redirects (`<`). It allows `<` to change the stdin descriptor when starting a nuttx task or to set the save/restore strucutures on the nsh handling.
I am not sure if this is the correct way to achieve this, so I open this PR to get feedback from the community. Please let me know if there is a better way or if I am misunderstanding or missing something.
I also plan to support `<<` style heredoc and pipes `|`. But those are not implemented yet.
If I get positive feedback, I could implement those in a future PR.
Partially fixes https://github.com/apache/nuttx-apps/issues/2454
Now we can stdin and stdout redirection:
```
nsh> echo hello > oi
nsh> cat < oi
hello
nsh> cat < oi > ola
nsh> cat ola
hello
nsh> echo even works the …
```
> nsh: input redirects

- nshlib/nsh_parse.c
The PR #2469 broke handling of environment variables because an error in the if/else if control flow. I am sorry.
Thank you @tmedicci for reporting the problem. Here is the fix.
Fixes https://github.com/apache/nuttx-apps/pull/2474:
```
NuttShell (NSH) NuttX-12.5.1
nsh> ls
/:
bin/
dev/
etc/
proc/
tmp/
nsh> echo $?
0
nsh> ls lalala
nsh: ls: stat failed: 2
nsh> echo $?
1
nsh> ls lalala
nsh: ls: stat failed: 2
nsh> echo $? > /tmp/out
nsh> cat < /tmp/out
1
nsh> 
```
Manually
> fix(nsh_parse): handle env variables correctly

- interpreters/bas/CMakeLists.txt
This correctly enables BASIC interpreter in CMake based build for at least sim:bas board configuration.
Configuration sim:bas was building - but interpreter was not showing up in built-in programs.
Hard to estimate - previous build was not linking interpreter because of missing CMakeLists.txt
Local build and execution of sim:bas.
Feeling a bit nostalgic here - but assuming that it's in the tree - it should work.
@acassis @xiaoxiang781216
> build: Missing CMakeLists.txt for BASIC interpreter

- builtin/CMakeLists.txt
builtin registered cmake handles adding the case where there is no sources.
for more details, please refer to : https://github.com/apache/nuttx/pull/12910
CI build
> [cmake] builtin register support NONE srcs target

- builtin/CMakeLists.txt
Reverts apache/nuttx-apps#2478
Let's revert this modification first
There are cmake scripts in examples and system that do not meet this feature,
and they need to be modified synchronously before CI is performed together
```shell
/tools/gcc-aarch64-none-elf/bin/../lib/gcc/aarch64-none-elf/13.2.1/../../../../aarch64-none-elf/bin/ld: apps/builtin/libapps_builtin.a(builtin_list.c.obj):(.rodata.g_builtins+0x88): undefined reference to `sotest_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x58): undefined reference to `udpblaster_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x58): undefined reference to `romfs_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x118): undefined reference to `tcpblaster_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x40): undefined …
```
> Revert "[cmake] builtin register support NONE srcs target"

- benchmarks/cachespeed/cachespeed_main.c
- testing/ramtest/ramtest.c
Fixed cachespeed / ramtest output format to avoid warnings in 64-bit environments
None
> fix printing variables in 32/64-bit

- testing/ltp/0011-ltp-fix-the-proc.h-header-file-duplicate-inclusion.patch
- testing/ltp/0012-ltp-fix-build-error.patch
- testing/ltp/Makefile
1. fix the "proc.h" inclusion build error
2. fix the "NSIG" redefined build warning
> fix the ltp build error

- canutils/candump/candump.c
apps/canutils: fix the build warning on greenhills compiler
> greenhills support: fix the variables set but never used build warning

- Makefile
1. fix the unknown build option handle warning with ghs compiler
> greenhills support: fix the unknow build options warning

- system/nxplayer/nxplayer.c
In audio.c, when audio_start calls the driver’s start function, it needs to check upper->started. The issue occurs in the complete case which does not call ioctl STOP, so started is not reset to false and resulting in the inability to play again.
tested on vela sim.
> apps/nxplayer: add ioctl stop when play completed

- netutils/iptables/CMakeLists.txt
add cmake support for xtables.c, solves the problem of missing symbols when compiling with cmake
cortex-m33 board
> netutils/iptables: add cmake support.

- examples/lvgldemo/lvgldemo.c
fix uninit_use_in_call
lvgldemo
lvgldemo
> lvgldemo: fix uninit_use_in_call

- .gitignore
- nshlib/nsh_parse.c
- testing/ostest/fpu.c
1. fix the packed warning and variable unused warnings that issued by ghs compiler
2. update the .gitignore rule to exclude the intermediate file that generated during compiling
> greenhills support: fix the warning issued by ghs compiler

- Application.mk
1. overwritten issue 
when there are a lot of SRCS files and they are split into many batches, 
the Make.dep file will be overwritten, causing incremental compilation exceptions.
2. incremental compile speed issue
when incremental compilation is performed, the contents of the Make.dep file will be repeated multiple times (because the incremental SRC changes will cause .depend to be executed). 
this will cause additional overhead when Make.dep is parsed by GNU Make. 
In the case I tested, Make.dep was incrementally compiled to more than 1G, slowing down the incremental compilation speed.
CI
> [bugfix] fix Make.dep result was Overwritten when there are too many files

- netutils/webclient/webclient.c
Fix to close socket when it fails to resolve hostname.
webclient. 
> netutils/webclient: Fix bug that the socket is not close

- crypto/mbedtls/Makefile
mbedtls/library/alignment.h:98:5: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
98 |     memcpy(p, &x, sizeof(x));
|     ^~~~~~~~~~~~~~~~~~~~~~~~
mbedtls/library/cmac.c: In function 'mbedtls_cipher_cmac_finish':
mbedtls/library/cmac.c:288:19: note: at offset 20 into destination object 'M_last' of size 16
288 |     unsigned char M_last[MBEDTLS_CIPHER_BLKSIZE_MAX];
|                   ^~~~~~
> fix build warning to [-Wstringop-overflow=].

- system/argtable3/CMakeLists.txt
This fixes missing include directories for iperf application.
Make based build was able to proceed - CMake build had two aforementioned issues.
Hard to estimate.
Local playing around rpserver and rpproxy in sim flavor.
> build: Fix rpserver and rpproxy CMake builds

- netutils/netlib/netlib_obtainipv6addr.c
Use the `netlib_add_ipv6addr` interface to set the IPv6 address, and delete the redundancy code.
N/A
After obtaining the IPv6 address with the `renew6` command, use `ifconfig` to view the results.
> Use the netlib_add_ipv6addr to set the IPv6 address

- audioutils/libmad/.gitignore
- audioutils/libmad/CMakeLists.txt
- audioutils/libmad/Kconfig
- audioutils/libmad/Make.defs
- audioutils/libmad/Makefile
libmad0-dev and libmad0-dev:i386 cannot be installed simultaneously, which causes conflicts when compiling sim m32 and sim m64. Therefore, the libmad library has been ported to apps/audioutils and will be compiled with nuttx-apps.
> apps/audioutils:Add libmad library.

- wireless/wapi/src/util.c
no permission bit was provided when creating the file, resulting in the loss of permission to create the file and ultimately unable to read it
wapi save config
> util.c:Add mode when creating files in the wapi_save_config

- crypto/mbedtls/CMakeLists.txt
- crypto/mbedtls/Makefile
```
if  !defined(unix) && !defined(__unix) && !defined(__unix__) && \
!defined(__APPLE__) && !defined(_WIN32) && !defined(__QNXNTO__) && \
!defined(__HAIKU__) && !defined(__midipix__)
error
"Platform entropy sources only work on Unix and Windows, see MBEDTLS_NO_PLATFORM_ENTROPY in mbedtls_config.h"
nuttx/libs/libxx/libcxx/include/__config
nuttx/libs/libxx/libcxx/include/limits.h:40,
apps/crypto/mbedtls/mbedtls/include/mbedtls/check_config.h:31, apps/crypto/mbedtls/mbedtls/include/mbedtls/build_info.h:151, apps/crypto/mbedtls/mbedtls/library/common.h:26,
apps/crypto/mbedtls/mbedtls/library/entropy_poll.c:25
if defined(__NuttX__)
undef __linux__
undef __APPLE__
undef __FreeBSD__
undef __GLIBC__
undef __NetBSD__
undef _WIN32
undef __sun__
undef _AIX
/ For the current use of the __unix__ …
```
> mbedtls: fix build error when libcxx is enabled.

- system/tcpdump/Kconfig
The default stack size of the tcpdump tool is 2KB. Since the do_capture function in the tool allocates memory on the stack and consumes 1.5KB of memory, causing stackoverflow, the default stack size is modified and changed to 4k.
> tcpdump:fix tcpdump stack overflow bug

- examples/usbserial/usbserial_main.c
The usbserial runs fail if usb serial device already registered, add checking if usb serial device exist before register.
usbserial app
esp32s3-devkit
> examples/usbserial: Check if usbserial device exist before register

- testing/ostest/robust.c
This does not require the use of mutex internal fields
ostest
> ostest: delete the code that accesses the internal fields of mutex

- testing/ostest/CMakeLists.txt
- testing/ostest/Makefile
- testing/ostest/nxevent.c
- testing/ostest/ostest.h
- testing/ostest/ostest_main.c
testing/ostest: add nxevent test into ostest
Depends on: https://github.com/apache/nuttx/pull/12802
N/A
ci-check
>  testing/ostest: add nxevent test into ostest

- testing/drivertest/drivertest_pwm.c
Description: Divide info.duty into two parts: multi-channel and single-channel
> apps/testing/drivertest_pwm.c: Fix apps/testing/drivertest_pwm.c compile_error

- testing/drivertest/CMakeLists.txt
- testing/drivertest/Makefile
- testing/drivertest/drivertest_mps2.c
MPS2_AN500 have UART1,2,3,4, TIMER0,1, is a great board to do irqprio test.
qemu mps2-an500 to run test case.
None, only test case, and default not enabled in other defconfig
'qemu-system-arm -M mps2-an500 -nographic -kernel nuttx.bin' to lauch qemu
> testing: add case for irqprio, should only work with qemu MPS2_AN500

- examples/fb/fb_main.c
1. adapt to double buffer mode
2. supported bpp = 24
3. select the FB_NO_OVERLAY because it will be showed on the main surface
fb demo
fb demo
> Enhance the FB demo to enable it to run on a wider range of hardware devices

- examples/can/can_main.c
This enhances can example application with the possibility to send CAN FD frames if FD mode is configured. Both EDL and BRS flags are now correctly set with the latter one configurable with application's arguments. Also data bytes are now correctly switched to DLC.
Example application can be now used for FD as well.
With SAMv7 MCAN.
> can: add support for FD frames if FD mode is configured

- examples/nimble/nimble_main.c
- examples/nimble: fix example after update to latest master
this example is broken since bc68d954a
since https://github.com/apache/mynewt-nimble/commit/bf761837418da4cc1d55abb4be50b8308e7bf18a ble_hci_sock_init is called from nimble code, so we can't call it again in example code
nrf52840-dk/sdc_nimble example
> examples/nimble: fix example after update to latest master

- system/settings/settings.c
Silly error in settings.c causing compiler error when settings utility caching is enabled
> Update System utility "settings.c" to correct compiler error

- testing/ostest/ostest_main.c
- testing/ostest/smp_call.c
smp_call only valid in FLAT BUILD
> ostest: smp_call only valid in FLAT BUILD

- nshlib/nsh_command.c
- nshlib/nsh_script.c
nshlib: move g_builtin_prompt from data to rodata
1. move g_builtin_prompt from data to rodata
2. add g_ prefix to some global variables
N/A
ci-check
> nshlib: move g_builtin_prompt from data to rodata

- testing/kasantest/Kconfig
- testing/kasantest/Make.defs
- testing/kasantest/Makefile
- testing/kasantest/kasantest.c
-u: This option is used to test the use of freed memory
-h: This option is used to test heap memory out-of-bounds access errors.
-g: This option is used to test global variables for out-of-bounds access errors.
-s: This option is used to test the Memory Stampede phenomenon.
> tests: add kasan test

- benchmarks/osperf/Kconfig
Building osperf requires pipes and hpwork. However, the configurations for pipes and hpwork are disabled by default. These features should be enabled automatically when osperf is enabled, which would be helpful for developers configuring osperf, so we want to add the select statement.
Without this change, the osperf fails to build with the following error:
```
fukui@herbtea:~/proj/package-hda/nuttxspace/nuttx$
:) make
Create version.h
LN: platform/board to /home/fukui/proj/package-hda/nuttxspace/apps/platform/dummy
Register: osperf
Register: hello
Register: nsh
Register: sh
Register: ostest
LD: nuttx.elf
ld: warning: intel64_vectors.o: missing .note.GNU-stack section implies executable stack
ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
ld: …
```
> benchmark: Build osperf only when pipes and hpwork are enabled

- testing/ltp/0013-ltp-handle-low-accuracy-of-time-in-some-platfrom.patch
- testing/ltp/Makefile
ltp: handle low accuracy of time in some platfrom
some platform use TICK to calculate the time, for example 1tick = 1ms, when the test may run less then 1ms, then gettime() before + sleep = after
ltp case
sim
> ltp: handle low accuracy of time in some platfrom

- system/debug/CMakeLists.txt
- system/debug/Kconfig
- system/debug/Make.defs
- system/debug/Makefile
- system/debug/debug.c
This patch add some command line arguments for debug program, then you can use it to insert watchpoint or breakpoint to arbitrary address at runtime.
New debug feature
ESP32C3
> testing/debug: Enhancement for watch address by cmd line

- netutils/thttpd/thttpd.c
When 'httpd' sends a file, it does not correctly calculate the offset of the read file data.
It does not take into account the header, but accepts the packet size instead of the size of the file data that was read.
```
[CPU1] httpd_start_request: File: "/data/www/css/main.css"
[CPU1] handle_send: offset: 0 end_offset: 469 bytes_sent: 0
[CPU1] handle_send: Read 52 bytes, buflen 256
[CPU1] tcp_max_wrb_size: tcp_max_wrb_size = 5840 for conn 0x3fc94a00
[CPU1] psock_tcp_send: new wrb 0x3fc95120 (non blocking)
[CPU1] psock_tcp_send: Queued WRB=0x3fc95120 pktlen=256 write_q(0x3fc95120,0x3fc95120)
[CPU1] handle_send: Wrote 256 bytes
[CPU0] tcp_callback: flags: 0010
[CPU1] handle_send: offset: 256 end_offset: 469 bytes_sent: 256
[CPU0] psock_send_eventhandler: flags: 0010
[CPU1] handle_send: Read …
```
> Thttpd Fix: wrong calc offset

- system/uorb/uORB/uORB.h
system/uorb: using uorb.h to replace sensors header file 
Vela
> system/uorb: using uorb.h to replace sensors header file

- .gitignore
Add .aider* to .gitignore
Minor
CI
> .gitignore: Add .aider* to .gitignore

- system/fastboot/Kconfig
- system/fastboot/fastboot.c
- New Feature
- Auto download mode: [fastbootd:add delay ms for bootloader](https://github.com/apache/nuttx-apps/commit/a4556435a9ffbefb9708b54710412d69b6f515dd)   **-- by @anjiahao1** 
- CMD: oem memdump & filedump : [system/fastboot: Support upload & oem(memdump, filedump) command](https://github.com/apache/nuttx-apps/commit/ac2665b2ab54eaa99caf20df3b71e48ccd23a711)
- Retry if open EP failed: [system/fastboot: Retry if open EP failed](https://github.com/apache/nuttx-apps/commit/3fdd967aa133652d7d801165f9ef7c044a6064eb)
- CMD: erase: [system/fastboot: erase - add driver independent](https://github.com/apache/nuttx-apps/commit/15a4fd99dd77d564a2648ed0c4a5ccbd0ec0b469), [system/fastboot: Complete the erase command](https://github.com/apache/nuttx-apps/commit/752829e050857a804c71af0d00f3722b …
> New features and bug fix for Fastboot

- CMakeLists.txt
- cmake/nuttx_add_luamod.cmake
- examples/lua_module/CMakeLists.txt
- interpreters/lua/CMakeLists.txt
add CMake module for register lua mod
```
nuttx_add_luamod(MODS hello)
```
```
nsh> lua
Lua 5.4.0  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> hello.say_hello()
Hello World!
> io.write("abs is =",math.abs(-10),"\n")
abs is =10
> os.exit()
nsh>
```
CI
> [cmake]:implement CMake build for NuttX Lua interpreter

- system/nxcodec/nxcodec.c
- system/nxcodec/nxcodec_context.c
- system/nxcodec/nxcodec_context.h
emun_format gets all supported formats, matches the passed format parameter, and then sets it via try_fmt
NA
NA
> nxcodec: Modify logic of judging the correctness of incoming pixformat

- netutils/pppd/lcp.c
If a PPP peer disconnects and then tries to reconnect it will send an 'LCP configure request' packet. The code that handles that scenario seems to be clearing the wrong `lcp_state` flag (`LCP_RX_UP` instead of `LCP_TX_UP`) and thus the nuttx ppp client will keep sending IPCP packets which are rightfully dropped by the new peer since it is still in the LCP negotiation phase.
> ppp: Fix wrong lcp_state handling on peer reconnection

- system/adb/logcat_service.c
Boards may set default(CONFIG_RAMLOG_POLLTHRESHOLD) to a very large value, causes logcat "can not" get poll notify.
adbd
> Bug fix for ADB

- examples/sotest/Kconfig
- examples/sotest/sotest_main.c
1. Fix warning of unused variable 'devname' - f876f3bd330175e70db62a47ae759a9058ac49d7
2. Fix depends of SOTEST_BUILTINFS - c7418f13b8248e107cc3528fee92019e8096985f
Please see commit message for more details.
examples/sotest
- Configuration
```
./tools/configure.sh -l sim:sotest
```
- Run
```
nsh> sotest
main: Registering romdisk at /dev/ram3
main: Mounting ROMFS filesystem at target=/mnt/romfs with source=/dev/ram3
module_initialize:
module_initialize:
testfunc1: Hello, everyone!
caller: Hello to you too!
testfunc2: Hope you are having a great day!
caller: Not so bad so far.
testfunc3: Let's talk again very soon
caller: Yes, don't be a stranger!
module_uninitialize: arg=0
module_uninitialize: arg=0
nsh>
```
> Fix warning and depends of examples/sotest

- examples/sotest/Kconfig
- examples/sotest/sotest_main.c
For case that /dev/ram${EXAMPLES_SOTEST_DEVMINOR} (e.g. "/dev/ram0") already exists, and users may not care which device to use.
e.g. Try from "/dev/ram0" to "/dev/ram${EXAMPLES_SOTEST_DEVMINOR_MAX} ("/dev/ram5" by default)"
examples/sotest
- Configuration
```
./tools/configure.sh -l sim:sotest
```
- Runtime
"/dev/ram0", "/dev/ram1" and "/dev/ram2" are already exist, using "/dev/ram3".
```
nsh> sotest
main: Registering romdisk at /dev/ram0
main: Registering romdisk at /dev/ram1
main: Registering romdisk at /dev/ram2
main: Registering romdisk at /dev/ram3
main: Mounting ROMFS filesystem at target=/mnt/romfs with source=/dev/ram3
module_initialize:
module_initialize:
testfunc1: Hello, everyone!
caller: Hello to you too!
testfunc2: Hope you are having a great day!
caller: Not so bad so far. …
```
> module/sotest: Try devminor of romdisk

- nshlib/nsh_command.c
- nshlib/nsh_fscmds.c
In below two cases "rm" command with "-f" option will return 0:
1. Bad arguments
2. File not exists
Follow "rm" of GNU coreutils 8.32
nshlib/nsh_command - "rm"
Configuration
```
./tools/configure.sh -l sim:sotest
```
```
$ rm --version
rm (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Paul Rubin, David MacKenzie, Richard M. Stallman,
and Jim Meyering.
$ rm /FILE_NOT_EXISTS
rm: cannot remove '/FILE_NOT_EXISTS': No such file or directory
$ echo $?
1
$ rm -f
$ echo $?
0
$ rm -f /FILE_NOT_EXISTS
$ echo $?
0
```
```
nsh> rm
nsh: rm: missing required argument(s) …
```
> nshlib: Support "-f" option for command "rm"

- tools/mksymtab.sh
-  Exclude symbols that dynamic modules in bin/ call each other. - be3a91e87d4b60a296ed372bf2293a55f0447dcf (by @anjiahao1 )
- Bugfix: Add check for sed expression. - 1973f15aca063e555562be325a812f035f3ad96a
- Support adding additional symbols that are not in undefined list. - b4d995f916ede75f6a95d30d5389ecae6c8ec1a6
- For apps to be built in the future, the required symbols may not be included in the symbol table, and you will need to rebuild the NuttX kernel to run it.
- With this patch, you can add symbols may be used in the future manually to the symbol table.
- Extended usage:  - e3844a1b43182e6fa6343f8f74bcc4da2e11cbaa
- The lines start with "," make no effects(as comments)
- Support symbol name overriding
- See commit message for more details.
Build scripts that using mksymtab.sh …
> New features for tools/mksymtab.sh

- Application.mk
- Makefile
this patch is relate to: https://github.com/apache/nuttx/pull/13452
> module build:replace BUILD_LOADABLE with MODULES

- system/uorb/sensor/topics.c
- system/uorb/uORB/uORB.c
Fix build error
- Error Log
```
CC:  procfs/fs_procfsversion.c uORB/uORB.c: In function ‘orb_advsub_open’:
uORB/uORB.c:73:23: error: assignment to expression with array type
73 |       reginfo.path    = path;
|                       ^
sensor/topics.c: In function ‘orb_get_meta’:
sensor/topics.c:173:15: warning: returning ‘uint64_t’ {aka ‘long long unsigned int’} from a function with return type ‘const struct orb_metadata *’ makes pointer from integer without a cast [-Wint-conversion]
173 |   return state.priv;
|          ~~~~~^~~~~
```
- Related: https://github.com/apache/nuttx/pull/13531
system/uorb
```
./tools/configure.sh -l sim:rpproxy
```
> uORB/uORB: Using array to save path for sensor_reginfo_s

- examples/gps/gps_main.c
Vendor may add extended sentence may not handled in switch, error if -Werror=switch enabled.
And extended sentence should not added to general examples.
Log:
```
gps_main.c: In function 'gps_main':
gps_main.c:140:16: error: 'MINMEA_SENTENCE_LOR_LSQ' undeclared (first use in this function)
case MINMEA_SENTENCE_LOR_LSQ:
^
gps_main.c:140:16: note: each undeclared identifier is reported only once for each function it appears in
```
The example "examples/gps"
```
./tools/configure.sh -l lilygo_tbeam_lora_gps:gps
```
compilation ok, failed in link stage, need check CI result.
> examples/gps: The extended sentence may not supported by minmea

- testing/ramtest/CMakeLists.txt
This issue was preventing ramtest to be displayed into nsh (this is why all modifications need to be tested!! "should work" doesn't work).
This is was discovered by user @nonpawite
Users will be able to use ramtest again
sim
> testing/ramtest: Fix not updated CMake file

- system/uorb/sensor/gas.c
The gas.c file adapts uORB's new macro definition so that it can be output in uorb listener
Compile and Gas Sensor。
PC:ubuntu 2004, X86, SIM, GCC 13.1
order:
`uorb_listener -n 10 sensor_gas`
> gas.c:Adapt to uORB new macro definition content.

- system/uorb/listener.c
- system/uorb/uORB/uORB.c
- system/uorb/uORB/uORB.h
1. New feature: uorb output structure data is replaced by a string by a callback function. You can print the content of the structure by giving the structure description string.
2. uorb listener adapts the o_format parameter and adds data output to the file
- This function converts strings to structures and structures to strings. It is used to record and replay uorb data for easy development and debugging.
1. uorb debug output
PC:ubuntu 2004, X86, SIM, GCC 13.1
order:
`uorb_listener -n 10 sensor_accel_uncal`
output
`sensor_accel_uncal(now:81651200):timestamp:81650900,x:0.138864,y:0.634463,z:9.938332,temperature:29.029297`
> uORB: Add formatted string ("o_format") parameters and remove callback log ("cb") printing.

- nshlib/nsh_fsutils.c
leaking here means fork/vfork will duplicate fd without O_CLOEXEC flag to the child process.
nsh
cortex M55
> nshlib:enable O_CLOEXEC expliciti to avoid potential fd leak

- .github/workflows/labeler.yml
Add workflow that assigns labels based on the PR's size.
The same as on kernel side: https://github.com/apache/nuttx/pull/13542
change from https://github.com/apache/nuttx/pull/13558 is not yet ported, because the apps repo requires different labels.
Each PR will have a label assigned depending on its size:
xs_label: 'Size: XS', max size = 10
s_label: 'Size: S', max size = 100
m_label: 'Size: M', max size = 500
l_label: 'Size: L', max size = 1000
xl_label: 'Size: XL', > 1000
not tested, should work the same as on NuttX repo
> github/workflows: add PR size labeler

- nshlib/nsh_script.c
- nshlib/nsh_syscmds.c
leaking here means fork/vfork will duplicate fd without O_CLOEXEC flag to the child process.
nshlib
ci test
> nshlib: enable O_CLOEXEC explicit to avoid potential fd leak

- system/uorb/uORB/uORB.c
to avoid potential fd leak which means fork/vfork will duplicate fd without O_CLOEXEC flag to the child process.
uorb
> uorb: enable O_CLOEXEC explicit

- nshlib/Kconfig
- nshlib/nsh.h
- nshlib/nsh_command.c
- nshlib/nsh_proccmds.c
This command looks through the currently running processes and kills the those that match the selection criteria. This way system can send signal to processes by name and without knowing the IDs. The implementation match the one of `kill` and `pidof`.
Example (kill application hello):
`	pkill -15 hello`
The command can be turned off by `NSH_DISABLE_PKILL` option and depends on `FS_PROCFS`.
New command.
> nshlib: add support for pkill command

- .github/workflows/build.yml
This PR modifies NuttX CI and GitHub Actions, to comply with ASF Policy.
According to ASF Policy: We should run at most 15 Concurrent Jobs: https://infra.apache.org/github-actions-policy.html
build.yml: Limit the GitHub Runners
see @lupyuen PR https://github.com/apache/nuttx/pull/13412
added -N -S options 
-N Use CMake with Ninja as the backend.
PR https://github.com/apache/nuttx/pull/12721
-S Adds the nxtmpdir folder for storing third-party packages.
PR https://github.com/apache/nuttx/pull/13301
none
CI
It complies with ASF Policy: The GitHub Runners did not exceed 15 during the build.
> build.yml:  Workflow aligned with nuttx repo

- system/adb/Kconfig
- system/uorb/Kconfig
- testing/monkey/Kconfig
Adapt %p* newly added LIBC_PRINT_EXTENSION kconfig configuration(https://github.com/apache/nuttx/pull/13536)
N/A
PC:ubuntu 2004, X86, SIM, GCC 13.1
build：./tools/configure.sh sim:nsh
./nuttx
> Adapt %p* newly added LIBC_PRINT_EXTENSION kconfig configuration

- examples/netloop/lo_listener.c
- examples/nettest/nettest_server.c
- examples/poll/net_listener.c
- examples/poll/net_reader.c
- examples/rpmsgsocket/rpsock_server.c
- examples/tcp_ipc_server/tcp_ipc_server_main.c
- examples/tcpblaster/tcpblaster_server.c
- examples/tcpecho/tcpecho_main.c
- examples/ustream/ustream_server.c
- examples/xmlrpc/xmlrpc_main.c
- netutils/ftpc/ftpc_socket.c
- netutils/ftpd/ftpd.c
- netutils/iperf/iperf.c
- netutils/netcat/netcat_main.c
- netutils/netlib/netlib_server.c
- netutils/telnetd/telnetd_daemon.c
- netutils/thttpd/libhttpd.c
- netutils/webserver/httpd.c
- system/gdbstub/gdbstub.c
- system/telnet/telnet_chatd.c
leaking here means fork/vfork will duplicate fd without O_CLOEXEC flag to the child process.
net apps and utils
please ignore mixed case warning:
```
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/netutils/thttpd/libhttpd.c:1857:2: error: Mixed case identifier found
Error: Process completed with exit code 1.
```
> enable SOCK_CLOEXEC explicit

- system/uorb/CMakeLists.txt
- system/uorb/Kconfig
- system/uorb/Makefile
- system/uorb/uORB/epoll.c
- system/uorb/uORB/internal.h
- system/uorb/uORB/loop.c
- system/uorb/uORB/uORB.h
1. Added urob loop function module and supported epoll.
```
struct orb_handle_s  g_handle;
struct orb_handle_s  g_handle1;
struct orb_loop_s    g_loop;
int count = 0;
void *test_loop(void *arg)
{
struct orb_loop_s *loop = arg;
if ( loop == NULL)
{
return ((void *)0);
}
if(orb_loop_run(loop) < 0)
{
syslog(1, "&&&& THREAD  error!\n");
}
syslog(1, "&&&& THREAD  exit !\n");
return ((void *)0);
}
int print_accel(FAR struct orb_handle_s *handle, FAR void *arg)
{
int ret;
struct sensor_accel accel;
pthread_t id = pthread_self();
ret = orb_copy(ORB_ID(sensor_accel), handle->fd, &accel);
if (ret == OK)
{
syslog(1, "data [%d] -> fd:%d, x:%f, y:%f, z:%f handle:%p, threadid:%d",
(int)arg, handle->fd, accel.x, accel.y, accel.z, handle, id);
}
count++;
return OK;
}
int flush_accel(FAR struct …
```
> uorb:Added urob loop function module and supported epoll.

- system/uorb/sensor/accel.c
- system/uorb/sensor/accel.h
- system/uorb/sensor/angle.c
- system/uorb/sensor/angle.h
- system/uorb/sensor/gesture.h
- system/uorb/sensor/motion.c
- system/uorb/sensor/motion.h
- system/uorb/sensor/pose_6dof.c
- system/uorb/sensor/pose_6dof.h
- system/uorb/sensor/rotation.c
- system/uorb/sensor/rotation.h
- system/uorb/sensor/step_counter.c
- system/uorb/sensor/step_counter.h
- system/uorb/sensor/topics.c
- system/uorb/uORB/uORB.c
- system/uorb/uORB/uORB.h
1. uorb adds interface for getting info
2. Add some sensor types from aosp( 6dof motion and gesture related types).
n/a
- Environment:
OS and Version: Ubuntu 20.04.6 LTS x86_64
GCC Version: 13.1.0
SIM: ./tools/configure.sh sim:nsh
- Order:
./nuttx
> uorb:Update uorb info and uorb topic

- nshlib/nsh_proccmds.c
Add newline at the end of cmd_pidof to show nsh
prompt correctly.
Before this patch:
```
nsh> pidof wifi
3 nsh>
```
After:
```
nsh> pidof wifi
3
nsh>
```
Minor
Local
> nshlib: Add missing newline in cmd_pidof output

- benchmarks/coremark/Makefile
**Why is this change necessary?**
The crc16 naming implemented in coremark is duplicated in zblue.
**Changes**
The redefinition function is renamed inside the makefile
```
CFLAGS += -Dcrc16=coremark_crc16
```
**Is a new feature added?:** NO
**Impact on build**: NO
**Impact on hardware**:NO, this change does not specifically target any particular hardware architectures or boards.
**Impact on documentation**: NO,This patch does not introduce any new features
**Impact on compatibility**: This implementation aims to be backward compatible. No existing functionality is expected to be broken.
Build Host(s): Linux x86
Target(s): sim/nsh
coremark is OK
```
NuttShell (NSH) NuttX-12.3.0-vela
nsh> 
nsh> 
nsh> ls
/:
bin/
dev/
etc/
proc/
tmp/
nsh> coremark
2K performance run parameters for coremark. …
```
> coremark:Fix renaming issues with other libraries

- testing/crypto/ecdsa.c
1. Add asynchronous call test into ecdsa test case.
2. Add command line parameters to facilitate subsequent expansion.
Now can test synchronous call through 'ecdsa -s SECP256R1' and test asynchronous call through 'ecdsa -a SECP256R1'
N/A
ci
> testing/crypto: add ECDSA P256 testing case for asynchronous call

- .gitignore
- nshlib/nsh_alias.c
- testing/ostest/semtimed.c
1. fix the variable set but never used warning
2. fix pointless comparison of unsigned integer with zero warning
has no impact on current implementation
1. has pass the ostest
2. has tested on gcc and ghs compiler
> greenhills support: fix green hills toolchain build warnings

- examples/fb/fb_main.c
it should be written into act_fbmem  rather than fbmem in draw_rect24
fb exmaple with 24 bpp
run fb
> fb_main: fix draw_rect24

- system/ymodem/rb_main.c
- system/ymodem/sb_main.c
- system/ymodem/sbrb.py
- system/ymodem/ymodem.c
- system/ymodem/ymodem.h
The waiting duration of the rb/sb command can be determined based on the number of retransmissions, so that ymodem can restart to the normal system after running in the bootloader for a short period of time.
ymodem
use stm32 ymodem
> ymodem:set the transport retry as optional

- CMakeLists.txt
- cmake/nuttx_add_wamrmod.cmake
- examples/wamr_module/CMakeLists.txt
- examples/wamr_module/Kconfig
- examples/wamr_module/Make.defs
- examples/wamr_module/Makefile
- examples/wamr_module/module_hello.c
- interpreters/wamr/.gitignore
- interpreters/wamr/CMakeLists.txt
- interpreters/wamr/Kconfig
- interpreters/wamr/Makefile
- interpreters/wamr/Module.mk
- interpreters/wamr/registry/.gitignore
- interpreters/wamr/wamr_custom_init.c
This patch adds module registration mechanism for WAMR runtime.
To register a module, these steps are required:
1. Include Module.mk in your module's Makefile
2. Define WAMR_MODULE_NAME as the module name
3. Implement bool wamr_module_WAMR_MODULE_NAME_register(void) function in your module's source file
4. Enable INTERPRETERS_WAMR_EXTERNAL_MODULE_REGISTRY in menuconfig
build system
Local
> wamr: Add external module registration mechanism

- crypto/mbedtls/Kconfig
1. change MBEDTLS_DEBUG_C dependence DEBUG_CRYPTO_INFO，because MBEDTLS_DEBUG_C is widely used
2. MBEDTLS_X509_CRT_POOL depends on MBEDTLS_THREADING_C.
N/A
ci
> mbedtls/Kconfig: Fix mbedtls configuration dependency issue

- tools/mksymtab.sh
Add support for multiple additional symbols` file
Makefiles calling mksymtab.sh, like apps/Makefile(selftest OK).
Forward compatible.
1. Selftest
```
$ cat basic.txt
test_a
test_b
test_c
$ cat math.txt
acosf
asinf
atan2f
ceilf
cosf
expf
$ ./mksymtab.sh ./ g_TEST basic.txt
#include <nuttx/compiler.h>
#include <nuttx/symtab.h>
extern void *test_a;
extern void *test_b;
extern void *test_c;
const struct symtab_s g_TEST_exports[] =
{
{"test_a", &test_a},
{"test_b", &test_b},
{"test_c", &test_c},
};
const int g_TEST_nexports = sizeof(g_TEST_exports) / sizeof(struct symtab_s);
$ ./mksymtab.sh ./ g_TEST basic.txt math.txt
#include <nuttx/compiler.h>
#include <nuttx/symtab.h>
extern void *acosf;
extern void *asinf;
extern void *atan2f;
extern void *ceilf;
extern void *cosf;
extern void *expf; …
```
> tools/mksymtab.sh: Support multiple additional symbols` file

- system/adb/adb_banner.c
adb_banner.c:60:47: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=], `PRIx32` is used in place of `%x`.
system/adb/adb_banner 
ci
> system/adb: fix build warning

- crypto/libsodium/CMakeLists.txt
- crypto/libsodium/Makefile
fix libsodium compilation warning with missing configuration
N/A
ci
> crypto/libsodium: fix libsodium compilation warning

- nshlib/nsh_command.c
- nshlib/nsh_ddcmd.c
nshlib: support dd with conv=notrunc,nocreat
refs to: https://man7.org/linux/man-pages/man1/dd.1.html
support dd with new paramenter  conv=notrunc,nocreat
Vela
> nshlib: support dd with conv=notrunc,nocreat

- testing/ostest/CMakeLists.txt
- testing/ostest/Makefile
- testing/ostest/ostest.h
- testing/ostest/ostest_main.c
- testing/ostest/smp_call.c
Fix smp_call test not running.
CONFIG_SMP_CALL has been removed from https://github.com/apache/nuttx/pull/13282
ostest of qemu for arm64
```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -Bbuild -GNinja -DBOARD_CONFIG=boards/arm64/qemu/qemu-armv8a/configs/nsh_smp nuttx
qemu-system-aarch64 -smp 4 -cpu cortex-a53 -semihosting -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel build/nuttx -s
```
> ostest: fix smp call test

- Application.mk
- Make.defs
Add a `PREFIX` extension to your application compilation.
by defining the `PREFIX` variable and setting it to an external path, 
`make -C /some/app` can be called independently to build a separate application out_of_tree.
modify Make.defs and Application.mk so that their dependent variables can be overwritten.
Usage:
```makefile
PREFIX = out/of/tree/dir/
``` 
compiled products and intermediate products can be separated from the source tree
forward compatibility
CI build
> build(enhancement):enhance apps to support independent out-of-tree builds

- interpreters/luamodules/CMakeLists.txt
- interpreters/luamodules/luasyslog/CMakeLists.txt
Add luasyslog cmake support as an example.
No impact. 
1. Build and run
```
cmake -Bbuild -GNinja -DBOARD_CONFIG=boards/sim/sim/sim/configs/lua nuttx
ninjia -C build
./build/nuttx
```
2. Test
```
nsh>
nsh> lua
Lua 5.4.0  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> for k,v in pairs(lsyslog)
>> do
>> print(k,v)
>> end
open    function: 0x402d49c0
FACILITY_LOCAL4 0.0
FACILITY_AUTH   0.0
_COPYRIGHT      Copyright (C) 1994-2021 Nicolas Casalini (DarkGod)
FACILITY_DAEMON 0.0
FACILITY_LOCAL1 0.0
LOG_WARNING     4.0
close   function: 0x402d4990
FACILITY_AUTHPRIV       0.0
LOG_ALERT       1.0
_DESCRIPTION    LuaSyslog allows to use log to an unix Syslog daemon, direct or via LuaLogging
FACILITY_CRON   0.0
FACILITY_FTP    0.0
LOG_DEBUG       7.0
FACILITY_LOCAL0 0.0
LOG_NOTICE      5.0 …
```
> luasyslog: add cmake support

- .gitignore
- nshlib/nsh_alias.c
fix compiling warning in non-GNU compilers, variable never used.
Building C object apps/CMakeFiles/apps.dir/nshlib/nsh_alias.c.o
"apps/nshlib/nsh_alias.c", line 395: warning #550-D: variable "option" was set but never used
int option;
None
Greenhills compilers build
> toolchain/ghs: Fix green hills toolchain build Vela warnings

- examples/gpio/gpio_main.c
- nshlib/nsh_syscmds.c
- system/batterydump/Kconfig
- system/batterydump/Make.defs
- system/batterydump/Makefile
- system/batterydump/batterydump.c
- testing/drivertest/drivertest_pm_runtime.c
- testing/drivertest/drivertest_regulator.c
Add example for wakeup gpio type.
Update regulator samples.
move battery dump to system.
fix pmconfig command catched issue reported by coverity(unsigned compare with 0)
more samples, 
batterydump now regard as a tool, not a test
CI-test.
> Update samples. move battery dump to system, fix problems report by coverity(unsigned compare with 0)

- examples/usbserial/Kconfig
- examples/usbserial/usbserial_main.c
There are config macro in the usbserial code, such as INONLY / OUTONLY for direction, ONLYSMALL / ONLYBIG for message, but user cannot choose it, so add  these config macro to Kconfig to enable user customize for usbserial use, and also add in/out waiting time config for customization.
impact to usbserial app
Test with esp32s3-devkit/usb_device
> usbserial: Add config for customize direction, message and wait time

- testing/ostest/smp_call.c
Add smp_call from interrupt test.
> ostest/smpcall: add smp call from interrupt test

- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/ISSUE_TEMPLATE/002_feature_request.yml
- .github/ISSUE_TEMPLATE/003_help.yml
- .github/workflows/issue_labeler.yml
sync github lables with main NuttX repo: https://github.com/apache/nuttx/pull/13545
"Area:" labels don't quite fit into nuttx-apps, but I'll fix them later with auto labeler support
no imact on users, only github labels
tested on nuttx repo
> github: sync labels with nuttx repo

- testing/kasantest/CMakeLists.txt
- testing/kasantest/Makefile
- testing/kasantest/kasantest.c
1. fix the size passed by mm_initialize is incorrect
2.  add CMakeLists.txt
* `testing/kasantest`.
No
> kasantest.c: fix the size passed by mm_initialize is incorrect and add CMakeLists.txt

- nshlib/CMakeLists.txt
- nshlib/Kconfig
- nshlib/Makefile
- nshlib/nsh.h
- nshlib/nsh_command.c
- nshlib/nsh_parse.c
- nshlib/nsh_wait.c
'wait' command will block nsh from running until pid1 and pid2 finish. This is useful for parallel requirements to perform certain tasks
nsh
```
usage like:
nsh> sleep 10 &
[5:100]
nsh>set pid1=$!
nsh>sleep 15 &
[6:100]
nsh>set pid2=$!
nsh>wait $pid1 $pid2
```
> nsh:support wait command to wait task exit.

- examples/nettest/nettest_server.c
- examples/tcpblaster/tcpblaster_server.c
[linguini@pastabox nuttx]$ make -j
CC:  tcpblaster_server.c
LN: platform/board to
/home/linguini/cuinspace/pico-nuttx/apps/platform/dummy tcpblaster_server.c: In function ‘tcpblaster_server’: tcpblaster_server.c:159:14: error: implicit declaration of function ‘accept4’; did you mean ‘accept’? [-Wimplicit-function-declaration]
159 |   acceptsd = accept4(listensd, (FAR struct sockaddr *)&myaddr,
&addrlen,
|              ^~~~~~~
|              accept
make[3]: *** [Makefile:92: tcpblaster_server.hobj] Error 1
make[2]: *** [Makefile:53:
/home/linguini/cuinspace/pico-nuttx/apps/examples/tcpblaster_context]
Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:180: context] Error 2
make: *** [tools/Unix.mk:457:
/home/linguini/cuinspace/pico-nuttx/apps/.context] Error 2 …
> fix build error

- nshlib/nsh_syscmds.c
add restore to indicate "restore the factory settings" and  the previous "factory" represents the confirmation of restoring to factory settings.
resetcause
CI test
> resetcause:restore to factory, factory to factory_inquiry

- Makefile
- tools/mksymtab.sh
1. tools/mksymtab.sh: Use getopts for parameter parsing
2. apps/Makefile: Passing additional arguments to mksymtab
Usage of mksymtab.sh about param "additionalsymbolspath" changed, has checked by searching in nuttx-apps and nuttx.
"additionalsymbolspath" should not depends on "symtabprefix".
```
usage="Usage: $0 <imagedirpath> [symtabprefix [additionalsymbolspath]]"
usage="Usage: $0 <imagedirpath> [symtabprefix] [-a additionalsymbolspath]"
```
1. Selftest result attached to commit message
2. Github NuttX CI
> apps/Makefile: Support passing additional arguments to mksymtab.sh

- system/adb/CMakeLists.txt
make adb generate elf binary correctly
adbd
ci
> system/adbd: Fix typo error(CONFIG_ADB_SERVER->CONFIG_SYSTEM_ADBD)

- nshlib/nsh_proccmds.c
1. When the stack is allocated in megabytes, printing seven bits of ps will not align
> nsh: Fix PS printing misalignment

- .github/workflows/arch.yml
This PR syncs the CI Build Rules from `nuttx` to `nuttx-apps` repo. The Build Rules were added to `nuttx` repo here: https://github.com/apache/nuttx/pull/13858
No impact. The Build Rules will not take effect until we sync `build.yml` from `nuttx` to `nuttx-apps` repo. This will happen in the next PR.
Details shall be provided in the next PR.
> CI: Sync the Build Rules from nuttx repo

- .github/workflows/build.yml
This PR syncs the CI Build Workflow `build.yml` from `nuttx` repo to `nuttx-apps`. The updated `build.yml` consolidates these changes:
- https://github.com/apache/nuttx/pull/13301
- https://github.com/apache/nuttx/pull/13806
- https://github.com/apache/nuttx/pull/13862
`build.yml` from `nuttx` repo was slightly modified for `nuttx-apps`:
- All References to `apache/nuttx/.../arch.yml` were changed to `apache/nuttx-apps/.../arch.yml` (we decouple them so they are easier to update)
- Removed `pull_request > paths-ignore` and `push > paths-ignore` (following the existing convention)
With the updated `build.yml`, `nuttx-apps` will be built according to the PR Arch Labels, as explained here: https://github.com/apache/nuttx/issues/13775
This has no impact on `nuttx-apps`, since Arch Labels are …
> CI: Sync the Build Workflow from nuttx repo

- system/dhcp6c/Kconfig
Add missing dependency `NET_ICMPv6_AUTOCONF`.
See #2412 
Previously the build failed if NET_ICMPv6_AUTOCONF was disabled (due to the missing `netlib_obtain_ipv6addr` symbol).
Compile-tested only.
See #2412: after the change the build via `sim:nsh` failed *later* (probably sim-specific).
> system/dhcp6c: add NET_ICMPv6_AUTOCONF dependency

- examples/noteprintf/noteprintf_main.c
fix noteprint compile error
The sched_note_string/bprintf/dump interfaces have been removed and replaced with printf and event
None
sim/note
> examples: fix noteprint compile error

- lte/alt1250/alt1250_netdev.c
- lte/alt1250/usock_handlers/alt1250_ioctl_ifreq.c
- netutils/netinit/netinit.c
- netutils/netlib/netlib_setifstatus.c
turn off interface by checking IFF_UP flag isn't set: https://github.com/apache/nuttx/issues/1838
RELEASE
CI
> {Bp-2647} net: Remove IFF_DOWN flag to compatible with Linux/*BSD

- system/dhcp6c/CMakeLists.txt
Keep the dhcpv6 renew process name the same in cmake and makefile
Minor
Nuttx CI & Vela CI
> Keep the dhcpv6 renew process name the same in cmake and makefile

- examples/romfs/CMakeLists.txt
- examples/tcpblaster/CMakeLists.txt
- examples/tcpblaster/tcpblaster_host.cmake
- examples/udpblaster/udpblaster_host.cmake
- examples/unionfs/CMakeLists.txt
- system/cdcacm/CMakeLists.txt
- system/critmon/CMakeLists.txt
- system/stackmonitor/CMakeLists.txt
After https://github.com/apache/nuttx-apps/pull/2478
We have a range of legacy applications that do not conform to the specification.
This patch completes part of it.
1. Added example of romfs unionfs
2. Added cmake host support for udp tcp blaster
**This will fix the current CI BB**
```shell
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x58): undefined reference to `udpblaster_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x58): undefined reference to `romfs_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x118): undefined reference to `tcpblaster_main'
/usr/bin/ld: nuttx.rel:(.data.rel.ro.g_builtins+0x40): undefined reference to `unionfs_main'
``` 
CI
> cmake:add romfs/unionfs/tcpblaster/udpblaster exmaple app CMake build

- system/gcov/Kconfig
- system/gcov/gcov.c
1. supports generating device-side code coverage
2. adjust gcov configuration name
3. deal compile warming
> system/gcov: enhance gcov

- testing/monkey/monkey_event.c
- testing/monkey/monkey_main.c
- testing/monkey/monkey_type.h
Add screen offset configuration to enable clicking within a limited range of the screen.
None.
```makefile
TESTING_MONKEY=y
```
utouch starts at (10,20) on the screen and randomly clicks in a rectangular area of ​​100x200.
```bash
monkey -t 11 --screen-offset 10,20 -s 100x200 &
```
> testing/monkey: add screen offset config support

- canutils/libobd2/obd_sendrequest.c
https://github.com/apache/nuttx-apps/pull/2635 replaced ch_unused with ch_tcf
RELEASE
CI
> {Bp-2668} canutils/libobd2: replace field ch_unused with ch_tcf

- canutils/libobd2/obd_sendrequest.c
https://github.com/apache/nuttx-apps/pull/2635 replaced ch_unused with ch_tcf
build error
CI
> canutils/libobd2: replace field ch_unused with ch_tcf

- fsutils/mkmbr/mkmbr.c
argv[argn] is accessed out of range when there are neither four partitions are specified nor the last partition is of auto size.
`mkmbr /dev/mmcsd1 233 666 auto 1234` -> `partn = 2` -> `argv[6]` -> panic
```
#0  0x4005544b in ?? ()
#1  0x42056a90 in mkmbr_main (argc=<optimized out>, argv=<optimized out>) at mkmbr.c:140
#2  0x42007449 in nxtask_startup (entrypt=0x420569e8 <mkmbr_main>, argc=6, argv=0x3ca01a60) at sched/task_startup.c:70
#3  0x42003be4 in nxtask_start () at task/task_start.c:114
```
Fix the problem by adding a number of partition variable `nr_part` based on input argument number.
Null pointer bug fixed.
Make `mkmbr` command support divide the device into less than four partitions with space left at the end.
```
nsh> mkmbr /dev/mmcsd1 233 666 auto 1234
nsh> hexdump …
```
> fsutils/mkmbr/mkmbr.c: fix null pointer access when not all device space is defined in mbr

- graphics/lvgl/0001-fix-demo-fix-compile-warning.patch
- graphics/lvgl/CMakeLists.txt
- graphics/lvgl/Kconfig
- graphics/lvgl/Makefile
Reverts apache/nuttx-apps#2670
revert until LVGL is released
> Revert "{Bp-2592} lvgl: upgrade to release/v9.2.1"

- nshlib/nsh_syscmds.c
1. struct rpmsg_ping_s ack change to cmd;
2. Update the help descrption based on the new cmd meaning;
rpmsg command
sim rpserver and rpproxy
> nsh_syscmds.c: upadate rpmsg ping help

- system/libuv/CMakeLists.txt
- system/libuv/Makefile
> libuv: Remove GCCVER and add compilation options directly.

- examples/noteprintf/noteprintf_main.c
```
noteprintf_main.c:52:7: warning: unused variable 'binary' [-Wunused-variable]
52 |     } binary =
```
Fix typo.
No impact.
Tested with configuration: `stm32f429i-disco:systemview`
> noteprintf: fix compile warnings

- system/system/Kconfig
- system/system/system.c
In some cases, applicationes use system() to excute the nsh command, but it's hard to find out who used the system function to execute the nsh command, so  add this config to print the call backtrace and the command content.
system command
sim
> system/system: add config SYSTEM_SYSTEM_DUMPINFO

- nshlib/nsh_parse.c
Now we can pass symbol " and ' to the nsh command arguments
Nsh
sim
> nshlib/nsh_parse: support use \" and \' to pass " and ' to arguments

- wireless/wapi/src/util.c
wapi_json_load: the buf need add null character
If the buf no null character, the strlen acces buf maybe out of bounds
> wapi_json_load: the buf need add null character

- benchmarks/osperf/osperf.c
Avoid the new thread write the closed pipe
osperf
sim
> osperf/osperf: move close pipefd after pthread_join

- benchmarks/coremark/Makefile
/data/project/oh2/rel-4.0/prebuilts/gcc/linux/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: crc16_sw.c.data.project.oh2.rel-4.0.external.zblue.zblue_1.o (symbol from plugin): in function `crc16':
(.text+0x0): multiple definition of `crc16'; core_util.c.data.project.oh2.rel-4.0.apps.benchmarks.coremark_1.o (symbol from plugin):(.text+0x0): first defined here
coremark
compile with coremark
> coremark/Makefile: avoid crc function multiple definition

- system/lsan/CMakeLists.txt
- system/lsan/Kconfig
- system/lsan/Make.defs
- system/lsan/Makefile
- system/lsan/lsan_main.c
lsan: add system cmd lsan support
The Alsans support for the LeakSanitizer (lsan) memory leak detection tool.
ref:
https://github.com/gcc-mirror/gcc/blob/master/libsanitizer/include/sanitizer/lsan_interface.h
This tool used for runtime check memleak on the SIM platfrom.
new tool
sim
> lsan: add system cmd lsan support

- examples/bmi160/CMakeLists.txt
- examples/bmi160/Kconfig
- examples/bmi160/Makefile
- examples/bmi160/sixaxis_uorb_main.c
examples/bmi160:bmi160 add urob mode example.
N/A
- Environment:
1.   OS and Version: Ubuntu 20.04.6 LTS x86_64
2.   GCC Version: 13.1.0
3.   SIM: ./tools/configure.sh sim:nsh
- Order:
1. ./nuttx 
2. sixaxis
> examples/bmi160:bmi160 add urob mode example.

- system/uorb/uORB/uORB.c
- uORB:Fixed the problem that uorb output cannot wrap after deleting lib_libbsprintf automatic wrapping.
N/A
- Environment:
1.   OS and Version: Ubuntu 20.04.6 LTS x86_64
2.   GCC Version: 13.1.0
3.   SIM: ./tools/configure.sh sim:nsh
- Order:
1. ./nuttx 
2. uorb_listener -r 50 -n 100  sensor_accel_uncal
> uORB:Fixed the problem that uorb output cannot wrap after deleting lib_libbsprintf automatic wrapping.

- system/adb/Kconfig
- system/adb/Makefile
1. Add timer to check usb hotplug event
2. Using inotify to check usb hotplug event
3. Implement ADB function through qemu pipe
Only Kconfig and Makefile, for implement please see microADB
system/adb
CI
> ADB: Hotplug check and QEMU pipe

- .github/workflows/build.yml
* MSYS2 + CMAKE + NINJA build is broken due a limit of 8192 characters for command line arguments on Windows.
* Ninja generator in CMake needs to be disabled until a solution is found, use Makefile generator.
* This is a quick fix for CI builds ending up with `parameter list too long` errors.
* MSYS2 CI Build system: Makefile generator is used by CMake in place of Ninja (may result in slower builds).
* CI build.
* Local machine with Windows (see https://github.com/apache/nuttx/pull/13971#issuecomment-2401902929).
> build.yml[bugfix]:disable CMake Ninja for Msys2

- .github/workflows/check.yml
To avoid the following CI error:
```
This environment is externally managed
--> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
```
CI checks are fixed now
Check the logs.
> [Fixes CI now!] ci: use venv for check

- system/cu/cu_main.c
only when devfd and stdfd both are tty, we call tcsetattr
cu
internal testing
> fix ECHO problem

- interpreters/quickjs/Makefile
in function `mp_mul':
apps/interpreters/quickjs/quickjs/libbf.c:1179: multiple definition of `mp_mul'; nuttx/staging/libapps.a:apps/math/libtommath/libtommath/bn_mp_mul.c:8: first defined here
sim
> quickjs: fix mp_mul multiple definition

- examples/usrsocktest/usrsocktest_basic_connect.c
- examples/usrsocktest/usrsocktest_basic_daemon.c
- examples/usrsocktest/usrsocktest_basic_getsockname.c
- examples/usrsocktest/usrsocktest_basic_getsockopt.c
- examples/usrsocktest/usrsocktest_basic_send.c
- examples/usrsocktest/usrsocktest_basic_setsockopt.c
- examples/usrsocktest/usrsocktest_block_recv.c
- examples/usrsocktest/usrsocktest_block_send.c
- examples/usrsocktest/usrsocktest_chardev.c
- examples/usrsocktest/usrsocktest_daemon.c
- examples/usrsocktest/usrsocktest_multi_thread.c
- examples/usrsocktest/usrsocktest_noblock_connect.c
- examples/usrsocktest/usrsocktest_noblock_recv.c
- examples/usrsocktest/usrsocktest_noblock_send.c
- examples/usrsocktest/usrsocktest_nodaemon.c
- examples/usrsocktest/usrsocktest_poll.c
- examples/usrsocktest/usrsocktest_remote_disconnect.c
- examples/usrsocktest/usrsocktest_wake_with_signal.c
error: variable 'ret' set but not used [-Werror=unused-but-set-variable]
112 |   int ret;
sim
> examples: fix usrsocktest compiler warning

- benchmarks/osperf/osperf.c
osperf: changes irq_t to irqstate_t
pass build
ci
> osperf: changes irq_t to irqstate_t

- system/telnetd/Kconfig
Using the default 3K stack size will result in insufficient stack when executing certain commands.
Telnet.
Local testing revealed 3K stack overflow on certain commands. This fixes the issue.
> telnet: Configure the telnet session stack to be the same as nsh

- testing/ostest/setjmp.c
This is an improved testing program for https://github.com/apache/nuttx/pull/14152 which tests the behaviour of the `setjmp` when invoking `longjmp` with the second argument as `0`.
Improve the testing scope for setjmp and longjmp.
N/A
> add test for longjump with 0 as return value

- benchmarks/ramspeed/ramspeed_main.c
We may want to test ramspeed by specific address, but be ignored.
print the not-aligned address, the last patch here is aim to solve align issue. we just need report the not-aligned manually input address.
fix bug now can use manual address to test the ram speed.
exit when not aligned address input.
CI-test, local arm-v8m board.
> ramspeed: fix -r -w parameter ignored, report align issue

- nshlib/nsh_console.h
- nshlib/nsh_parse.c
The NSH hangs after exec the test command.
`nsh_redirect()` needs to save three fd(stderr, stdout and stdin) but array length is only two, stack buffer overflowed!
- Config
```
sim:nsh
```
- Command
```
cat < /etc/init.d/rc.sysinit
```
Related: https://github.com/apache/nuttx-apps/pull/2469
nsh/redirect
- Selftest as summary shown
- Apache:NuttX CI
> nshlib: Fix stack-buffer-overflow of nsh_redirect()

- testing/ostest/setjmp.c
Revert "add test for longjump with 0 as return value"
This reverts commit 63542f83c2985723071ae7e428311213008aa108.
user_main: setjmp test
setjmp_test: Initializing jmp_buf
setjmp_test: Try jump
setjmp_test: About to jump, longjmp with ret val: 123
setjmp_test: Jump succeed
setjmp_test: Try jump
setjmp_test: About to jump, longjmp with ret val: 0
setjmp_test: Try jump
dump_assert_info: Current Version: NuttX  10.4.0 11e0262ae8 Oct 14 2024 12:53:49 sim
dump_assert_info: Assertion failed : at file: setjmp.c:46 task: ostest process: ostest 0x7de654
sched_dumpstack: backtrace:
sched_dumpstack: [ 6] [<0xb211b1>] host_backtrace+0x2d/0x41
sched_dumpstack: [ 6] [<0x7a39b2>] up_backtrace+0x10a/0x189
sched_dumpstack: [ 6] [<0x78dc79>] sched_backtrace+0x4d/0x9a
sched_dumpstack: [ 6] [<0x7974e5>] …
> Revert "add test for longjump with 0 as return value"

- benchmarks/dhrystone/CMakeLists.txt
- benchmarks/dhrystone/Makefile
Error details:
dhrystone/v2.2/dry.c:714:3: error: 'Int_2_Loc' may be used uninitialized [-Werror=maybe-uninitialized]
714 |   fprintf (stderr, "Int_2_Loc:           %d\n", Int_2_Loc);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dhrystone/v2.2/dry.c:543:25: note: 'Int_2_Loc' was declared here
543 |   REG   One_Fifty       Int_2_Loc;
|                         ^~~~~~~~~
> apps/benchmarks/dhrystone: Fix compilation errors

- nshlib/nsh_fscmds.c
nshlib:Add macro restrictions to code that uses floating point numbers
nsh fs
qmue
some paltform can't use flaot
> nshlib:Add macro restrictions to code that uses floating point numbers

- testing/drivertest/drivertest_rtc.c
Use gmtime to avoid time zone issues
N/A
ci
> rtc: change localtime to gmtime.

- examples/oneshot/oneshot_main.c
- nshlib/nsh_parse.c
- system/coredump/coredump.c
- system/fastboot/fastboot.c
- system/ntpc/ntpcstatus_main.c
- system/readline/readline.c
- testing/drivertest/drivertest_oneshot.c
- testing/drivertest/drivertest_watchdog.c
- testing/getprime/getprime_main.c
- testing/ostest/ostest_main.c
The `nuttx/arch.h` included in `userspace.h` will cause some unnecessary headers to be introduced in the user program (such as `net.h`). We are trying to remove the inclusion of `nuttx/arch.h`. In order to avoid compilation errors, we first need to add the missing header file inclusion in `nuttx-apps` after removing `nuttx/arch.h`.
This patch fix compilation error after excluding nuttx/arch.h.
Tested on QEMU/arm64 and QEMU/x86_64
> apps: Fix compilation error after nuttx/arch.h excluded

- testing/drivertest/drivertest_block.c
testing/drivertest_block.c: Fix cmoka driver block test error
1. Fix the problem that pre->source may have memory stampede
2. Fix total block size larger than cache size condition
Test in Vela
> testing/drivertest_block.c: Fix cmoka driver block test error

- testing/cxxtest/cxxtest_main.cxx
skip the locale related test if libc doesn't enable CONFIG_CXX_LOCALIZATION.
cxxtest
ci
> cxxtest: optional stream test

- nshlib/nsh_parse.c
Now the nsh can use \\ to pass '\' to the command
nsh
sim:nsh
> nshlib/nsh_parse: support use \\ to pass '\' to argument

- testing/drivertest/Makefile
If BUILD_FLAT is not enabled, the app and CPU run in user mode and kernel mode respectively. The kernel and app are in different memory address spaces. Different apps are in the same memory address space. drivertest_block.c cannot directly call the kernel API.
Rpmsg blk driver test
Test in vela
> drivertest/Makefile: add CONFIG_BUILD_FLAT limit for drivertest_block.c

- system/zlib/Kconfig
- system/zlib/Makefile
zlib:Support using Kconfig to control memory usage in zlib
zlib
qmeu with zlib
> zlib:Support using Kconfig to control memory usage in zlib

- nshlib/nsh_timcmds.c
Fix the date command sets an invalid month and then sets a valid month.
N/A
CI
> cmd_date:Set optind to zero in the error case.

- system/coredump/Kconfig
- system/coredump/coredump.c
system coredump impove
1. support coredump can save board memory
2. upload kernal coredump change
3. fix coverity bug
4. Increase coredump swap buffer size to improve speed
mps3 an547 with coredump
> system coredump impove

- nshlib/nsh.h
- nshlib/nsh_fsutils.c
nsh/fsutils: fix build break if CONFIG_NSH_DISABLE_PKILL not disabled
```
arm-none-eabi/bin/ld: apps/libapps.a(nsh_proccmds.c.obj): in function `cmd_pkill':
apps/nshlib/nsh_proccmds.c:861:(.text.cmd_pkill+0x38): undefined reference to `nsh_getpid'
```
N/A
ci-check
> nsh/fsutils: fix build break if CONFIG_NSH_DISABLE_PKILL not disabled

- netutils/libwebsockets/Kconfig
- netutils/libwebsockets/Make.defs
- netutils/libwebsockets/Makefile
- netutils/libwebsockets/libwebsockets.patch
- netutils/libwebsockets/lws_config.h
- netutils/libwebsockets/lws_config_private.h
1. netutils: introduce libwebsockets support
2. Fix to compile failure after mqttc is enabled
> netutils: introduce libwebsockets support

- testing/cxxsize/README.md
After optimization by the Xiaomi team, cxxsize has been reduced by more than 45% on average, please refer to here https://github.com/apache/nuttx-apps/pull/2722#issuecomment-2412030370.
c++ STL
ci
> cxxsize: Updata code size.

- nshlib/nsh_proccmds.c
nsh: Add top command and watch command
sim
> nshlib: fix top command sorting result error

- examples/sotest/main/sotest_main.c
Correct the path in the log.
```diff
- ERROR: dlopen(/sotest) failed
+ ERROR: dlopen(/mnt/sotest/romfs/sotest) failed
```
sotest
- Selftest
- CI
> examples/sotest: Correct the path in the log

- crypto/mbedtls/CMakeLists.txt
- crypto/mbedtls/Kconfig
1.Supplement cmake to compile POLY1305/RIPEMD160/Bignum algorithms 
2.Add blowfish and arc4 algorithm configuration
compile
ci
> apps/mbedtls: add compilation configuration

- nshlib/nsh_fscmds.c
e.g. Casting "-1" to `size_t` is equals to a very large value.
cmd_cat
CI
> nshlib/cmd_cat: Avoid casting -1 to size_t as count of nsh_write()

- Application.mk
- Make.defs
1. PREFIX needs to be added to Make.dep to avoid Make.dep regeneration during incremental compilation .
2. AROBJSRULES is just the .o file in the copy archive. Its output content is worthless, so we hide it by default.
fix Make.dep files are generated repeatedly during incremental compilation
hide unhelpful output
cmake -B build -DBOARD_CONFIG=qemu-armv7a:nsh
> build(bugfix):fix Make.dep location missing when specifying PREFIX, hide invalid cp output from ar

- nshlib/nsh_fsutils.c
Modify the implementation logic of changing directory. There's an error handling the path incluing "../" or "./"
bug examples:
nsh> cd proc/self/group
nsh> cd ../..
nsh: cd: chdir failed: 2
nsh> pwd
/proc/self
nsh> ls
/proc/self:
status
cmdline
stack
group/
nsh> cd ./group
nsh: cd: chdir failed: 2
No
No
depends on https://github.com/apache/nuttx/pull/14365
> apps/nshlib/cmd_cd: Modify the logic of cd

- .github/workflows/arch.yml
- .github/workflows/build.yml
This PR disables all CI Jobs for macOS and Windows, to reduce GitHub Cost. Details here: https://github.com/apache/nuttx/issues/14376
CI Jobs for macOS and Windows will no longer run, until we find a way to manage their costs.
We tested the skipping of macOS and Windows jobs: https://github.com/lupyuen5/label-nuttx/actions/runs/11379543159
> CI: Disable all jobs for macOS and Windows

- .github/workflows/arch.yml
When we submit or update a Complex PR that affects All Architectures (Arm, RISC-V, Xtensa, etc): CI Workflow shall run only half the jobs. Previously CI Workflow will run `arm-01` to `arm-14`, now we will run only `arm-01` to `arm-07`.
When the Complex PR is Merged: CI Workflow will still run all jobs `arm-01` to `arm-14`
Simple PRs with One Single Arch / Board will build the same way as before: `arm-01` to `arm-14`
This is explained here: https://github.com/apache/nuttx/issues/14376
Note that this version of `arch.yml` has diverged from `nuttx` repo, since we are unable to merge https://github.com/apache/nuttx/pull/14377
When we submit or update a Complex PR: CI Workflow shall run only half the jobs: `arm-01` to `arm-07` (instead of `arm-01` to `arm-14`)
No changes to the CI Workflow …
> CI: Skip jobs arm-08 to arm-14 when a Complex PR is created / updated

- examples/foc/Kconfig
- examples/foc/foc_device.c
- examples/foc/foc_fixed16_thr.c
- examples/foc/foc_float_thr.c
- examples/foc/foc_motor_b16.c
- examples/foc/foc_motor_f32.c
- examples/foc/foc_perf.c
- examples/foc/foc_perf.h
- examples/foc/foc_thr.h
* examples/foc: fix snprintf warning
fix snprintf warning:
foc_thr.c:110:39: warning: '%d' directive output may be truncated writing between 1 and 11 bytes into a region of size 7 [-Wformat-truncation=]
110 |   snprintf(mqname, sizeof(mqname), "%s%d", CONTROL_MQ_MQNAME, envp->id);
|                                       ^~
foc_thr.c:110:36: note: directive argument in the range [-2147483648, 0]
110 |   snprintf(mqname, sizeof(mqname), "%s%d", CONTROL_MQ_MQNAME, envp->id);
|                                    ^~~~~~
foc_thr.c:110:3: note: 'snprintf' output between 5 and 15 bytes into a destination of size 10
110 |   snprintf(mqname, sizeof(mqname), "%s%d", CONTROL_MQ_MQNAME, envp->id);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* examples/foc: fix compilation …
> Various improvements to FOC example

- wireless/wapi/src/wapi.c
wireless/wapi.c: Initialize variables to avoid abnormal data when wapi get country code
Fix that using uninitialized variables cannot correctly read country code
Verify use esp32s3-devkitc
```
nsh> wapi country wlan0
CN
```
> wireless/wapi.c: Initialize variables to avoid abnormal

- system/uorb/sensor/ppgd.c
- system/uorb/sensor/ppgq.c
The PRIu16 macro in the system is defined as "u", and "hu" is required. In Linux and Nuttx, PRIu32 PRIu16 PRIu8 are all defined as "u", but %pB prints the structure and needs its offset. %pB gets the offset through sizeof(short int)
N/A
Environment:
OS and Version: Ubuntu 20.04.6 LTS x86_64
GCC Version: 13.1.0
SIM: ./tools/configure.sh sim:nsh
Order:
./nuttx 
uorb_listener -n 10 sensor_ppgd
> uorb:Fixed the abnormal issue of printing uint16 with PRIu16.

- .github/workflows/arch.yml
When we submit or update a Complex PR that affects All Architectures (Arm, RISC-V, Xtensa, etc): CI Workflow shall run only half the jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to `03`
- `xtensa-01`
- `sim-01`
When the Complex PR is Merged: CI Workflow will still run all jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to `06`
- `xtensa-01` to `02`
- `sim-01` to `02`
Simple PRs with One Single Arch / Board will build the same way as before:
- `risc-v-01` to `06`
- `xtensa-01` to `02`
- `sim-01` to `02`
We hope to lower drastically our usage of GitHub Runners before the ASF Deadline, as explained here: https://github.com/apache/nuttx/issues/14376
When we submit or update a Complex PR: CI Workflow shall run only half the jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to …
> CI: Skip half of RISC-V, Xtensa and Simulator targets when a Complex PR is created / updated

- nshlib/nsh_command.c
- nshlib/nsh_ddcmd.c
Add support for reading from/writing to standard input/output.
~~The feature depends on https://github.com/apache/nuttx-apps/pull/2737~~
nshlib/cmd_dd
```bash
nsh> dd bs=5
1234512345AAAAAAAAAABBBBBBBBBB
nsh> dd if=/etc/init.d/rc.sysinit
mkrd -m 2 -s 512 1024
mkfatfs /dev/ram2
mount -t vfat /dev/ram2 "/tmp"
dd of=/data/dd_stdout bs=5
$ cat ../nuttx/dd_stdout
QWERT
```
> nshlib/dd: Add support for reading from/writing to standard input/output

- .github/workflows/arch.yml
- .github/workflows/build.yml
This PR syncs https://github.com/apache/nuttx/pull/14282 from `nuttx` repo to `nuttx-apps`.
See https://github.com/apache/nuttx/pull/14282
See https://github.com/apache/nuttx/pull/14282
> CI: Split the Build Jobs for Arm64 and x86_64

- .github/workflows/arch.yml
This PR updates the Build Rules `arch.yml` to build only these Arm32 Targets when we create or update a Complex PR:
- arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
No changes for Simple PRs (arm-01 to arm-14) and for Merging PRs (also arm-01 to arm-14).
This will improve our breadth of CI Checks across Arm32 Targets, as explained here: https://github.com/apache/nuttx/issues/14376
We build only these Arm32 Targets when we create or update a Complex PR:
- arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
No changes for Simple PRs and for Merging PRs.
Creating a Complex PR will build only arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
- https://github.com/lupyuen5/label-nuttx/actions/runs/11426738940
Creating a Simple PR will build arm-01 to arm-14
- …
> CI: Build only Arm32 Targets arm-01 / 03 / 05 / 06 / 07 / 09 / 11 for Complex PRs

- .github/workflows/build.yml
This PR syncs the Simulator Targets `sim-01`, `sim-02`, `sim-03` from `nuttx` repo to `nuttx-apps`: https://github.com/apache/nuttx/pull/14428
When we create or modify a Complex PR, the CI Checks for Simulator will complete earlier. This is explained here: https://github.com/apache/nuttx/issues/14376
See https://github.com/apache/nuttx/pull/14428
> CI: Split the targets in sim-01 and add sim-03

- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/ISSUE_TEMPLATE/002_feature_request.yml
- .github/ISSUE_TEMPLATE/003_help.yml
- .github/workflows/issue_labeler.yml
Not all labels are added because there is no match with the label name.
issue_labeler.yml
os: Linux -> os: linux
001_bug_report.yml
Type: bug -> Type: Bug
Corrected label in links
002_feature_request.yml
Type: enhancement -> Type: Enhancement
Corrected label in links
003_help.yml
Type: question -> Community: Question
Corrected label in links
same fixed and merged on Nuttx [14435](https://github.com/apache/nuttx/pull/14435)
Impact on user: No changes to user-facing functionality
Impact on build: Build process remains the same
CI
https://github.com/simbit18/nuttx-testing-templates/issues
> ISSUE_TEMPLATE: fix missing labels

- testing/kasantest/kasantest.c
1. By printing the results, we can know which libc memory APIs or illegal memory operation detectionin the current system support kasan check; for examples:
KASan Test: heap underflow -> PASS
KASan Test: heap overflow -> PASS
KASan Test: heap use after free -> PASS
KASan Test: heap invalid free -> PASS
KASan Test: heap double free -> PASS
KASan Test: heap poison -> PASS
KASan Test: heap unpoison -> PASS
KASan Test: heap illegal memchr -> PASS
KASan Test: heap illegal memcpy -> PASS
KASan Test: heap illegal memcmp -> PASS
KASan Test: heap illegal memmove -> PASS
KASan Test: heap illegal memset -> PASS
KASan Test: heap illegal strcmp -> PASS
KASan Test: heap illegal strcpy -> PASS
KASan Test: heap illegal strlen -> FAIL
KASan Test: heap illegal strncpy -> FAIL
KASan Test: heap illegal …
> kasantest: Add some tests for legitimate and illegitimate operations of memory APIs

- examples/spislv_test/CMakeLists.txt
- examples/spislv_test/Kconfig
- examples/spislv_test/Make.defs
- examples/spislv_test/Makefile
- examples/spislv_test/spislv_test.c
This app can be used to test spi slave driver. Using this app will be more fast to users test and verify spi slave driver.
For instance whats happened here: https://github.com/apache/nuttx/issues/13855#issuecomment-2426461702
No impact, new feature.
This app was used to test lower half changes done in this PR: https://github.com/apache/nuttx/pull/14420
> Add to nuttx apps a simple app to test spi slave driver.

- .github/workflows/arch.yml
CI Build Job sim-02 was disabled to reduce our usage of GitHub Runners, to comply with ASF Policy: https://github.com/apache/nuttx/issues/14376#issuecomment-2427837859
However this causes the Scheduled Merge Job to fail, due to reduced CI Checks: https://github.com/NuttX/nuttx/actions/runs/11490041505/job/31980056690#step:7:465
This PR re-enables sim-02 when we create or update a Complex PR.
When we create or update a Complex PR, the CI Workflow will now run sim-02, for improved CI Checking.
Creating a Complex PR now executes sim-02: https://github.com/lupyuen5/label-nuttx/actions/runs/11490590600?pr=82
> CI: Enable sim-02 build when we create or update a Complex PR

- netutils/connectedhomeip/CMakeLists.txt
as c++ versions are upgraded, hard code compilation options can cause build error.
sim:local
> netutils/connectedhomeip: use CONFIG_CXX_STANDARD instead of hard code

- examples/gpio/gpio_main.c
- examples/noteprintf/noteprintf_main.c
- nshlib/nsh_syscmds.c
- system/batterydump/Kconfig
- system/batterydump/Make.defs
- system/batterydump/Makefile
- system/batterydump/batterydump.c
- system/gcov/Kconfig
- system/gcov/gcov.c
- testing/drivertest/drivertest_pm_runtime.c
- testing/drivertest/drivertest_regulator.c
fix noteprint compile error
The sched_note_string/bprintf/dump interfaces have been removed and replaced with printf and event
RELEASE
CI
Note
includes 
https://github.com/apache/nuttx-apps/pull/2596
https://github.com/apache/nuttx-apps/pull/2614
https://github.com/apache/nuttx-apps/pull/2650
https://github.com/apache/nuttx-apps/pull/2677
https://github.com/apache/nuttx-apps/pull/2681
> {Bp-2655} examples: fix noteprint compile error 

- examples/lvgldemo/lvgldemo.c
Memory leak can be detected when simply change the while(1) loop to break after certain time. The `lv_nuttx_deinit` will free resources including display, input etc.
This issue only happen when the while(1) loop exist and need to de-init `lvgl`.
Now no memory leak detected using `lsan` command on sim. This 
Tested on sim with ASAN enabled.
```patch
+CONFIG_FRAME_POINTER=y
+CONFIG_MM_CUSTOMIZE_MANAGER=y
+CONFIG_SIM_ASAN=y
-CONFIG_INIT_ARGS="\"widgets\""
-CONFIG_INIT_ENTRYPOINT="lvgldemo_main"
+CONFIG_INIT_ENTRYPOINT="nsh_main"
```
```patch
diff --git a/examples/lvgldemo/lvgldemo.c b/examples/lvgldemo/lvgldemo.c
index 52d48ba7d..f5b42bddb 100644
--- a/examples/lvgldemo/lvgldemo.c
+++ b/examples/lvgldemo/lvgldemo.c
@@ -149,7 +149,8 @@ int main(int argc, FAR char *argv[])
#ifdef …
```
> lvgldemo: should use nuttx_deinit to free all resources

- fsutils/inifile/inifile.c
simple fix
minor warning fix
ci
> fix compile warning for fsutils inifile.c

- examples/mqttc/Kconfig
- examples/mqttc/mqttc_pub.c
- netutils/mqttc/Kconfig
Add mbedTLS option to `examples/mqttc`.
I haven't tried to connect with this code exactly to `"broker.hivemq.com"`, so example may not work as is (somebody needs to try), but I used this code to connect to other MQTT server with TLS.
This code has some advantages compared to native MQTT-C `mbedtls_sockets.h` implementation in the way that it tolerates self-signed certificates on a server (usually useful during development).
Extend MQTT-C example
Tested on ESP32-S3, but connecting to custom MQTT provider service
> examples/mqttc: add option to use MBED TLS for connections

- system/flatbuffers/CMakeLists.txt
- system/gprof/CMakeLists.txt
Added flatbuffers cmake scripts
Added system/gprof cmake scripts
No impact on the past
ci build
> cmake:replenish flatbuffers system/gprof app CMake build

- examples/lvgldemo/Kconfig
- examples/lvgldemo/lvgldemo.c
Default to /dev/input0, now it's configurable.
No functionality change after this change. Impact is minor.
Tested with `sim:lvgl_fb`.
> lvgldemo: allow to customize input dev path

- examples/netpkt/CMakeLists.txt
- examples/netpkt/Makefile
- examples/netpkt/netpkt_ethercat.c
add a simple example to test ethercat's sending and receiving.
x86_64 device
> examples/netpkt: add ethercat test example for robot

- netutils/connectedhomeip/CMakeLists.txt
- netutils/connectedhomeip/Kconfig
Logs have a great impact on image size, so whether to print logs is modified as a compilation option and controlled by Kconfig
sim:matter
> matter: add Kconfig option to control logging

- canutils/candump/Kconfig
- canutils/cansend/Kconfig
- canutils/libcanutils/Kconfig
canutils: change dependency from GPL to BSD
socketCAN utils are dual licence, there is no point in using GPL licence when we can use BSD.
Also change `select CANUTILS_LIBCANUTILS` to `depends on CANUTILS_LIBCANUTILS`. We can't `select` that option when `ALLOW_BSD_COMPONENTS` is not set.
depends on: https://github.com/apache/nuttx/pull/14520
SocketCAN utils depends on BSD now
CI
> canutils: change dependency from GPL to BSD

- testing/cmocka/cmocka_main.c
set CMOCKA_SHUFFLE_SEED environment variable
cmocka launcher
ci
> testing/cmocka: shuffling test sequence and pass seed arg

- netutils/netlib/netlib_obtainipv4addr.c
netutils/netlib/netlib_obtainipv4addr.c:117: undefined reference to `netlib_getmacaddr'
minor
ci
> netutils: fix compile error when not defined CONFIG_NET_ETHERNET

- system/termcurses/tcurses_vt100.c
- system/vi/vi.c
1. Since Nuttx commit https://github.com/apache/nuttx/commit/df5c876932c4c82e8aee32adca651bb99d9d6200 , the serial driver enable ICANON flag as default. This broken the VI and all keystrokes inputs are buffered. So disable it in termcurses.
2. If the VI exits in an error condition it will break the console.  This is because release_vi was not called to restore the console configuration, so fix it.
All VI-enabled boards.
Test in Ubuntu 24.20 use sim:nsh.
> app/system/vi: Fix broken VI editor

- Application.mk
build warning fix
macos
CP:  /Users/vela/ajh/nuttx/include/nuttx/fs/hostfs.h CC:  inode/fs_inodebasename.c ar: no archive members specified usage:  ar -d [-TLsv] archive file ...
ar -m [-TLsv] archive file ...
ar -m [-abiTLsv] position archive file ...
ar -p [-TLsv] archive [file ...]
ar -q [-cTLsv] archive file ...
ar -r [-cuTLsv] archive file ...
ar -r [-abciuTLsv] position archive file ...
ar -t [-TLsv] archive [file ...]
ar -x [-ouTLsv] archive [file ...]
add this patch,and build sim:module in macos, no warning output
> macos:fix sim:module build warning

- testing/x86-64-ABI/0001-app-testing-Resolve-the-issue-of-compilation-failure.patch
- testing/x86-64-ABI/Kconfig
- testing/x86-64-ABI/Make.defs
- testing/x86-64-ABI/Makefile
app/testing:Add x86_64 abi test download path
Add x86_64 abi test cases
noimpact
ostest
> app/testing:Add x86_64 abi test cases

- testing/resmonitor/CMakeLists.txt
- testing/resmonitor/Kconfig
- testing/resmonitor/Make.defs
- testing/resmonitor/Makefile
- testing/resmonitor/fillcpu.c
- testing/resmonitor/filldisk.c
- testing/resmonitor/fillmem.c
- testing/resmonitor/showinfo.c
add tools from 
after enable TESTING_RESMONITOR, use showinfo -i 2 can show cpuload to syslog every two seconds.
```text
showinfo [-i <interval>] [-p <pid>] [-a] [-d <dir>] [-l <logpath>] [-k <logpath>]
-i: Set the refresh interval (in seconds), i.e., how often to print the result. Default is 1 second.
-p: Set the pid of the process to monitor. If not set, only system information is shown.
-a: Effective only if -p is set. If not set, the displayed CPU and memory usage reflect only the specified pid
(excluding child threads or child tasks). If enabled, the displayed CPU and memory usage include the
total for the process and all its child threads (i.e., the same task group).
-d: View file system information. Total size represents the total size of the file system, free size shows
the …
```
> resmonitor: add showinfo/filldisk/fillcpu/fillmem

- netutils/netlib/netlib_getarptab.c
- nshlib/nsh_netcmds.c
> net/arp: optimize the arp command display result

- benchmarks/tinymembench/0001-tinymembench-fix-compiling-error-for-NuttX.patch
- benchmarks/tinymembench/CMakeLists.txt
- benchmarks/tinymembench/Kconfig
- benchmarks/tinymembench/Make.defs
- benchmarks/tinymembench/Makefile
This patch adds `tinymembench` for memory bandwidth and latency measuring.
None.
Tested on QEMU/x86.
> benchmarks: support tinymembench

- examples/netpkt/netpkt_ethercat.c
the current usage description is incorrect,
ifname must follow ethercat. The number of transfers can be specified only after ifname is specified.
qemu:local
> netpkt_ethercat.c: fix the description of usage

- system/ymodem/ymodem.c
ymodem bug fix
ymodem
Create some scenarios that require retransmission, and trigger retransmission to enable normal transmission
> ymodem:fix bug,When sending a retransmission, HEAD is overwritten.

- nshlib/nsh_console.c
nshlib/console: fix compile error when open CONFIG_NSH_ALTCONDEV
CC:  mm_heap/mm_memalign.c misc/rwbuffer.c: In function 'rwb_readbytes': misc/rwbuffer.c:1172:2: warning: #warning Not Implemented [-Wcpp]
1172 | #warning Not Implemented
|  ^~~~~~~
CC:  binfmt_unloadmodule.c In file included from nsh_console.c:40: nsh_console.c: In function 'nsh_consoleredirect':
nsh_console.h:85:30: error: 'struct serialsave_s' has no member named 'cn_confd'; did you mean 'cn_infd'?
85 | #  define INFD(p)      ((p)->cn_confd)
|                              ^~~~~~~~
nsh_console.c:344:7: note: in expansion of macro 'INFD'
344 |       INFD(ssave) = INFD(pstate);
|       ^~~~
nsh_console.c: In function 'nsh_consoleundirect':
nsh_console.h:85:30: error: 'struct serialsave_s' has no member named 'cn_confd'; did …
> nshlib/console: fix compile error when open CONFIG_NSH_ALTCONDEV

- benchmarks/rt-tests/0001-rt-tests-cyclictest-Port-for-NuttX.patch
- benchmarks/rt-tests/CMakeLists.txt
- benchmarks/rt-tests/Kconfig
- benchmarks/rt-tests/Make.defs
- benchmarks/rt-tests/Makefile
- benchmarks/rt-tests/numa.h
This commit supports cyclictest from RT-Tests for the timer jitter profiling.
None.
Tested on QEMU/x86_64.
> benchmarks: support cyclictest

- benchmarks/test-tlb/0001-test-tlb-port-for-NuttX.patch
- benchmarks/test-tlb/CMakeLists.txt
- benchmarks/test-tlb/Kconfig
- benchmarks/test-tlb/Make.defs
- benchmarks/test-tlb/Makefile
This commit added support for test-tlb, a memory latency micro-benchmark.
None.
Tested on QEMU/x86_64 and QEMU/armv8a-virt.
> benchmarks: support test-tlb

- boot/nxboot/CMakeLists.txt
- boot/nxboot/Kconfig
- boot/nxboot/Make.defs
- boot/nxboot/Makefile
- boot/nxboot/include/nxboot.h
- boot/nxboot/loader/boot.c
- boot/nxboot/loader/flash.c
- boot/nxboot/loader/flash.h
- boot/nxboot/nxboot_main.c
- boot/nxboot/tools/nximage.py
- boot/nxboot/tools/requirements.txt
This commit adds NuttX based bootloader with the support for image update and recovery if not confirmed. The algorithm utilizes three flash partitions: primary (image runs from this area), secondary and tertiary. Secondary and tertiary areas are used for update upload and recovery.
The update is performed by simple copy from update area to primary area with recovery being created in recovery area if not already present. Once image is confirmed by the user, the image in update area is confirmed as well, update area becomes recovery area and vice versa. This means the recovery is always present (except for the first update) and subsequent updates just copy image from update to primary. This makes the update significantly faster and more considerable to flash wear while keeping the …
> boot: add NuttX bootloader with update and recovery support

- system/debugpoint/debug.c
Issue is about adress alignment differences between [idf](https://github.com/espressif/esp-idf/blob/master/components/riscv/include/riscv/rv_utils.h) and [nuttx](https://github.com/apache/nuttx/blob/master/arch/risc-v/src/common/riscv_debug.c#L326) implementation. On idf implementation we round the size value if size is greater than one. Due to this difference example is failing because data length was 27 and not rounded. [According to add idf watchpoint description](https://github.com/espressif/esp-idf/blob/master/components/esp_hw_support/include/esp_cpu.h#L493-L497) it has to be power of 2.
- Fix RO watchpoint test issue for esp devices
`esp32c3-generic:nsh` config used with `CONFIG_SYSTEM_DEBUGPOINT` and `LIB_GDBSTUB` options enabled and `debugpoint` command used
> system/debugpoint: Fix RO watchpoint test issue for esp devices

- system/nxdiag/Kconfig
- system/nxdiag/Makefile
- system/nxdiag/nxdiag.c
- tools/host_sysinfo.py
- Improve nxdiag example for Espressif devices
All ESP32 devices
Tested with `esp32c3-generic:nsh` config with these options enabled:
```
CONFIG_SYSTEM_NXDIAG=y
CONFIG_SYSTEM_NXDIAG_ESPRESSIF=y
CONFIG_SYSTEM_NXDIAG_ESPRESSIF_CHIP=y
```
During build process make sure that chip is connected. Output should be like this:
```
nsh> nxdiag --all
Nxdiag Report:
NuttX RTOS info:
Hostname: 
Release: 10.4.0
Build: 69e813ce78 Oct 31 2024 10:43:05
Arch: risc-v
Defconfig: esp32c3-generic:nsh-dirty
Host system OS:
...
Espressif specific information:
Bootloader version:
esp32: v5.1-dev-3972-g1559b6309f
esp32s2: v5.1-dev-3972-g1559b6309f
esp32s3: v5.1-dev-3972-g1559b6309f
esp32c2: v5.1-dev-3972-g1559b6309f
esp32c3: v5.1-dev-3972-g1559b6309f
esp32c6: v5.1-dev-3972-g1559b6309f
esp32h2: …
```
> Improve nxdiag example for Espressif devices

- .github/workflows/arch.yml
This PR enables the CI Builds for msys2, msvc, arm-08, arm-10, arm-13 for Complex PRs. We disable the CI Builds for arm-01, arm-09, arm-11.
This will help to fix the recent breakage of builds: https://github.com/apache/nuttx/issues/14598
When we create or update a Complex PR: CI Workflow will now build msys2, msvc, arm-08, arm-10, arm-13 (instead of arm-01, arm-09, arm-11)
No changes to Simple PRs.
Creating a Complex PR will now build msys2, msvc, arm-08, arm-10, arm-13 (instead of arm-01, arm-09, arm-11):
https://github.com/lupyuen5/label-nuttx/actions/runs/11638217458
Creating a Simple Arm32 PR will build arm-01 to arm-14, like before:
https://github.com/lupyuen5/label-nuttx/actions/runs/11638211712
> CI: Enable builds for msys2, msvc, arm-08, arm-10, arm-13 for Complex PRs

- .github/workflows/check.yml
This PR syncs https://github.com/apache/nuttx/pull/14323 from `nuttx` repo to `nuttx-apps`.
This will resolve the `checkpatch.sh` failure: https://github.com/apache/nuttx-apps/issues/2812
`checkpatch.sh` now runs correctly in the CI Workflow.
We synced https://github.com/apache/nuttx/pull/14323 from `nuttx` repo to `nuttx-apps`. `checkpatch.sh` now runs correctly:
https://github.com/nuttxpr/nuttx-apps/actions/runs/11641702799/job/32420488934?pr=4
> CI: Add Python linter to check

- examples/sotest/main/CMakeLists.txt
- system/ymodem/CMakeLists.txt
1. fix ymodem typo
2. implement cmake sotest when kernel build does not support yet
CMake: ymodem and sotest fixes.
CI test
> cmake(bugfix):fix ymodem cmake typo error and sotest build error

- interpreters/wamr/CMakeLists.txt
This patch allow from other module that outside
WAMR directory include `wasm_export.h` to use WAMR as library.
cmake build system of WAMR
> wamr: add iwasm include directory to nuttx target

- examples/ble/CMakeLists.txt
- examples/ble/Kconfig
- examples/ble/Make.defs
- examples/ble/Makefile
- examples/ble/ble.c
- examples/ble/ble_main.c
- examples/ble/dummy.c
- examples/ble/sensors.c
- examples/ble/sensors.h
Created a minimal demo application for Bluetooth. It works by displaying some data over Bluetooth and the user can connect to the device running it on NuttX and read this data.
This can work in 2 scenarios: a real scenario, in which data from the BME680 (temperature, humidity, etc..) is used and the user will be able to read it.  The second scenario involves displaying some dummy data (hardcoded values) for testing purposes.
This application can serve as an example for users implementing more complex application using Bluetooth on NuttX.
I used the ESP32-Sparrow (which includes the BME680 sensor) and the ESP32-devkitc boards for testing.
The Bluetooth stack starts by default with advertising when it initializes, however I noticed that enabling advertising in the stack does not work (at …
> Added demo for BLE

- .github/workflows/build.yml
Due to the [recent cost-cutting](https://github.com/apache/nuttx/issues/14376), we are no longer running PR Merge Jobs in the `nuttx` and `nuttx-apps` repos. For this to happen, I am now running a script on my computer that will cancel any PR Merge Jobs that appear: [kill-push-master.sh](https://github.com/lupyuen/nuttx-release/blob/main/kill-push-master.sh)
This PR disables PR Merge Jobs permanently, so that we no longer need to run the script. This prevents our CI Charges from over-running, in case the script fails to operate properly.
Some NuttX Developers may wish to run the PR Merge Jobs in their repos. They will have to re-enable the job in `build.yml`:
```yaml
on: ...
push: ...
branches:
- master
```
Or they may rename the Default Branch from `master` to `releases/master` branch. …
> CI: Disable the CI Build on push to master branch

- .github/workflows/build.yml
When compiling the Release Branch of `nuttx-apps`, our CI Workflow `build.yml` checks out the Master Branch of `nuttx` repo, which is incorrect. This happens due to a typo in `build.yml`: https://github.com/apache/nuttx/issues/14513
This PR fixes the typo in `build.yml` to checkout the correct branch of `nuttx` repo.
When compiling the Release Branch of `nuttx-apps`, our CI Workflow `build.yml` now checks out the Release Branch of `nuttx` repo.
No changes when compiling the Master Branch of `nuttx` and `nuttx-apps` repos.
__Before the PR:__ Fetch-Source Log shows that CI is incorrectly checking out the Master Branch of `nuttx` repo (instead of `releases/12.7`): https://github.com/apache/nuttx-apps/actions/runs/11518661640/job/32069568370#step:3:66
```text
/usr/bin/git checkout --progress …
```
> CI: Check out the correct branch of nuttx repo when compiling nuttx-apps

- benchmarks/rt-tests/.gitignore
- benchmarks/tacle-bench/.gitignore
- benchmarks/test-tlb/.gitignore
- benchmarks/tinymembench/.gitignore
Updated `benchmarks/rt-tests/.gitignore` so local cache and package files are ignored on git repo and not added by mistake.
`benchmarks/rt-tests` cache and dist files are ignored on git repo.
ci
> benchmarks: add .gitignore files

- nshlib/nsh_vars.c
There is no corresponding sched_lock() for this and therefore this causes random crashes.
Found when running a long init script which utilizes shell variables in SMP mode.
Remove sched_unlock() from a place that does not use sched_lock()
Downstream MPFS target which utilizes nsh_vars.
> nsh_vars: Remove rogue sched_unlock()

- boot/nxboot/loader/boot.c
API function `nxboot_get_confirm` was returning incorrect value if primary image was flashed directly into the embedded flash (this image does not have a tail, but is automatically considered as valid and stable based on the header magic value).
Fixes return value for `nxboot_get_confirm` function.
SAMv7 MCU custom board.
> nxboot: fix incorrect confirm state for directly flashed image

- testing/ostest/smp_call.c
reason:
The old implementation of the SMP call, even when using the "no wait" parameter, could still result in waiting, if invoking it within a critical section may lead to deadlocks. Therefore, in order to implement a truly asynchronous SMP call strategy, we have added nxsched_smp_call_async.
https://github.com/apache/nuttx-apps/pull/2822
https://github.com/apache/nuttx/pull/14656
These two pull requests (PRs) must be merged together.
smp call
ci ostest
**Build Host:**
* OS: Ubuntu 20.04
* CPU: x86_64 
* Compiler: GCC 9.4.0
Configuring NuttX and compile:
$ ./tools/configure.sh -l qemu-armv8a:nsh_smp
$ make
Running with qemu
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic \
-machine virt,virtualization=on,gic-version=3 \
-net none -chardev stdio,id=con,mux=on -serial chardev:con \ …
> smpcall: add nxsched_smp_call_async and nxsched_smp_call_single_async

- testing/ostest/smp_call.c
fix compile error
Error: smp_call.c:36:31: error: 'g_call_data' defined but not used [-Werror=unused-variable]
36 | static struct smp_call_data_s g_call_data;
|                               ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/github/workspace/sources/apps/Application.mk:237: smp_call.c.github.workspace.sources.apps.testing.ostest.o] Error 1
make[2]: Target 'all' not remade because of errors.
make[1]: *** [Makefile:52: /github/workspace/sources/apps/testing/ostest_all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [tools/LibTargets.mk:248: /github/workspace/sources/apps/libapps.a] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 385: …
> fix compile error

- system/uorb/sensor/gnss.c
Update debug format of "sensor_gnss".
uorb_listener
1. Selftest
```
uorb_listener -n 20 sensor_gnss
```
2. NuttX CI
> uORB/sensor: Add GNSS firmware version for `sensor_gnss_format`

- audioutils/nxaudio/nxaudio.c
- Ensure `AUDIO_STOP` via `ioctrl` is followed by `mq_send STOP` without race conditions.
- Modify loop condition to correctly handle `running = false` upon receiving STOP signal.
- Resolve potential issue where `AUDIO_MSG_DEQUEUE` could still accept buffers after STOP signal due to timing.
Before:
- `nxaudio_stop` would call `ioctrl AUDIO_STOP` followed by `mq_send STOP`, which might lead to `AUDIO_MSG_DEQUEUE` accepting buffers after STOP.
After:
- Synchronized the sequence of `ioctrl AUDIO_STOP` and `mq_send STOP` to prevent buffer addition after STOP.
- Enhanced loop condition to accurately reflect the STOP state.
N/A
N/A
> nxaudio: fix audio stop logic to prevent buffer addition after STOP signal

- examples/pipe/transfer_test.c
write returns in case some bytes were written but not everything can fit.
This wasn't the case in NuttX but commit
d0680fd1bc51b7ead0b068fb24a31a144d22dc6c introduced this standard behavior.
This should fix CI as reported in https://github.com/apache/nuttx/pull/14667#issuecomment-2461197521.
`pipe` was executed on custom same7 board and passed.
<details>
```
> pipe
pipe_main: Performing FIFO test
open_write_only: Opening FIFO for write access
open_write_only: Waiting for open_write_only thread
pipe_main: open_write_only returned 0
transfer_test: fdin=4 fdout=3
transfer_test: Starting transfer_reader thread
transfer_test: Starting transfer_writer thread
transfer_reader: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: started
transfer_writer: 18200 bytes written …
```
> examples/pipe: fix write usage

- testing/ostest/wqueue.c
isrthread: add configuring the stack of an isrthread as static
reason:
we configure the isr thread stack as static to allow for more flexible placement of the stack.
isrthread
https://github.com/apache/nuttx/pull/14686
https://github.com/apache/nuttx-apps/pull/2828
These two pull requests (PRs) must be merged together.
ci ostest
> isrthread: add configuring the stack of an isrthread as static

- graphics/lvgl/CMakeLists.txt
LVGL 9.2.1 archive is ~70MB. Over poor connections, it may take longer to download it. This renders CMake build unusable in such environments.
CMake build for LVGL configurations is now usable over poor network connections.
Local CMake configure step for 
```
cmake .. -G Ninja -DBOARD_CONFIG=sim:lvgl_fb
```
> build: increase FetchContent timeout to 120 seconds for LVGL

- testing/ostest/pthread_rwlock.c
We need to wait for race_cond_thread2 to acquire the rdlock first, otherwise it may cause a deadlock.
ostest
ostest
> ostest/pthread_rwlock: We need to wait for race_cond_thread2 to acquire the rdlock first, otherwise it may cause a deadlock.

- nshlib/nsh_fscmds.c
nshlib/cmd_cat: Retry if `nsh_read()` was interrupted by a signal.
When read from stdio of child process through pipe, SIGCHLD received if child exits.
nshlib/cmd_cat.
1. Selftest
```
ls | cat | cat | cat | cat
```
2. Github CI
> nshlib/cmd_cat: Retry if `nsh_read()` was interrupted by a signal

- nshlib/nsh_ddcmd.c
nshlib/cmd_dd: Retry if read() was interrupted
- Without this patch
```bash
nsh> ls /etc/group | dd | dd
sh [13:100]
sh [14:100]
nsh: dd: read failed: 4
nsh>
```
- With this patch
```
nsh> ls | dd | dd | dd | dd | dd
sh [4:100]
sh [5:100]
sh [6:100]
sh [7:100]
sh [8:100]
/:
bin/
dev/
etc/
proc/
tmp/
var/
nsh>
```
Link: https://github.com/apache/nuttx-apps/pull/2833 (same reason), https://github.com/apache/nuttx-apps/pull/2737 (nsh pipeline)
nshlib/cmd_dd
- nsh:sim with pipeline enabled
- NuttX CI
> nshlib/cmd_dd: Retry if read() was interrupted

- builtin/exec_builtin.c
- include/builtin/builtin.h
- include/nshlib/nshlib.h
- nshlib/Kconfig
- nshlib/nsh.h
- nshlib/nsh_builtin.c
- nshlib/nsh_fileapps.c
- nshlib/nsh_parse.c
- testing/cmocka/cmocka_main.c
Add pipeline support for nsh commandline through `pipe2()` and `posix_spawn_file_actions_adddup2()`
1. Pack parameters of nsh_execute() as struct nsh_exec_param_s
- Input redirect flags currently is hardcode, passing by arguments maybe better.
- Only support redirect to path_name, redirect to fd is needed for pipeline.
2. Add pipeline support for commandline
And nesting pipeline supported.
nsh: nsh_parse_command()
```
cat < /etc/init.d/rc.sysinit
ls | cat
ls | cat | cat | cat
mkfifo /dev/testfifo
cat /dev/testfifo &
ls > /dev/testfifo
set name `uname`
echo $name
sotest
```
Depends: https://github.com/apache/nuttx-apps/pull/2751
```bash
mount -t hostfs -o fs=. /data 
ls | cat | dd | cat | dd of=/data/test_dd_stdin
#Read from stdin and write to stdout
ls | cat | dd | cat | dd
```
- patch …
> Add pipeline support for nsh commandline

- interpreters/quickjs/0001-Disabled-unsupported-feature-on-NuttX.patch
- interpreters/quickjs/CMakeLists.txt
add cmake compilation scripts for quickjs
nop
cd nuttx
cmake -B build -DBOARD_CONFIG=sim:nsh
cmake --build build -t menuconfig and enable following configs: CONFIG_PIPES, CONFIG_SYSTEM_POPEN, LIBC_DLFCN, CONFIG_INTERPRETERS_QUICKJS, CONFIG_INTERPRETERS_QUICKJS_BIGNUM
cmake --build build
> add cmake compilation scripts for quickjs

- include/audioutils/nxaudio.h
audioutils/nxaudio: added pause/resume interface in nxaudio.h
nxaudio
nxaudio
> audioutils/nxaudio: added pause/resume interface in nxaudio.h

- nshlib/nsh_fsutils.c
- testing/ostest/nxevent.c
- testing/ostest/pthread_exit.c
- testing/ostest/setjmp.c
- testing/ostest/setvbuf.c
- testing/ostest/signest.c
Remove stdio.h  unnecessary header file
Many compilation configs rely on removing redundant header files in stdio
build sim:nsh
> stdio.h:Remove unnecessary header file, app header change

- examples/pipe/pipe_main.c
- examples/pipe/redirect_test.c
- system/libuv/0001-libuv-port-for-nuttx.patch
- system/popen/popen.c
- testing/cmocka/cmocka_main.c
- testing/drivertest/drivertest_pm_runtime.c
- testing/drivertest/drivertest_posix_timer.c
- testing/drivertest/drivertest_rtc.c
- testing/drivertest/drivertest_uart.c
- testing/testsuites/kernel/fs/cases/fs_getfilep_test.c
- testing/testsuites/kernel/mm/cases/mm_test_008.c
- wireless/bluetooth/btsak/btsak.h
stdio.h:remove <nuttx/xxx.h>
all use stdio.h
sim:citest build and sim:nsh build
https://github.com/apache/nuttx/pull/14697 Associated PR
> stdio.h:remove <nuttx/xxx.h>

- examples/nimble/CMakeLists.txt
/github/workspace/sources/apps/examples/nimble/nimble_main.c:40:10: fatal error: nimble/nimble_npl.h: No such file or directory
40 | #include "nimble/nimble_npl.h"
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
bugfix
cmake -B build -DBOARD_CONFIG=nrf52840-dk/sdc_nimble -GNinja
build pass
> cmake(bugfix):add INCLUDE_DIRECTORIES for nimble

- nshlib/nsh_parse.c
Fix variable arguments concat error of `nsh_execute()`  
```
nsh> set time 5
nsh> echo $time
5
nsh> sleep $time &
sh [5:100]
nsh> nsh: sleep: missing required argument(s)
```
```
nsh> set time 5
nsh> echo $time
5
nsh> sleep $time &
sh [4:100]
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK            STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 0069616 Idle_Task
1     0 224 FIFO     Kthread   - Waiting  Signal    0000000000000000 0067536 loop_task
2     0 224 FIFO     Kthread   - Waiting  Semaphore 0000000000000000 0067504 hpwork 0x501760e0 0x50176128
3     3 100 FIFO     Task      - Running            0000000000000000 0067536 nsh_main
4     4 100 FIFO     Task      - Waiting  Signal    0000000000000000 0067520 sh -c sleep
``` …
> nshlib/nsh_parse: Fix variable arguments concat error of `nsh_execute()`

- nshlib/nsh_parse.c
Concat variable arguments failed
1. Without this patch
```
nsh> set var_test `uname`
nsh> echo $var_test
NuttX
nsh> echo $var_test | cat
sh [5:100]
nsh>
```
2. With this patch
```
nsh> set var_test `uname`
nsh> echo $var_test
NuttX
nsh> echo $var_test | cat
sh [4:100]
NuttX
nsh>
```
Reported by @jasonbu and @yangao1@xiaomi.com, thank you ;-)
nshlib/pipeline
1. Selftest as commit message show
2. NuttX CI
> nshlib/pipeline: Concat variable arguments failed

- examples/posix_spawn/Kconfig
- examples/posix_spawn/spawn_main.c
`posix_spawn` depends on these configurations:
- !BINFMT_DISABLE
- !DISABLE_MOUNTPOINT
- BOARDCTL
- BOARDCTL_APP_SYMTAB
- ELF
- FS_ROMFS
Check them in compile time may waste some time if the dependencies are not met, move them to Kconfig to avoid this.
No
Local machine
> posix_spawn: Move dependencies to Kconfig

- nshlib/Kconfig
- nshlib/nsh.h
- nshlib/nsh_command.c
- nshlib/nsh_wait.c
Wait failed if `FS_PROCFS` not enabled
```diff
- CONFIG_FS_PROCFS=y
```
```
nsh> sleep 5 &
sh [4:100]
nsh> wait 4
nsh: wait: wait failed: 2
```
```C
snprintf(path, sizeof(path), "/proc/%d/status", tid);
```
Reported by @XuNeo and @Gary-Hobson, thank you;-)
nshlib/cmd_wait
1. Selftest: Using `sim:nsh` with `CONFIG_FS_PROCFS` disabled - PASSED
2. NuttX CI
> nshlib/cmd_wait: Wait failed if `FS_PROCFS` not enabled

- testing/uclibcxx_test/Makefile
make[2]: *** No rule to make target '/home/nuttx/libs/libxx/uClibc++/tests/testframework.cpp', needed by '/home/nuttx/libs/libxx/uClibc++/tests/testframework.cpp.home.apps.testing.uclibcxx_test.o'.  Stop.
make uClibc++ test pass ci
internal ci
> build(bugfix):fix uClibc++ layout build error

- testing/iob/CMakeLists.txt
- testing/iob/Kconfig
- testing/iob/Make.defs
- testing/iob/Makefile
- testing/iob/iob_main.c
testing: add iob test
iob
ostest
> mm/iob: add ostest test

- benchmarks/osperf/CMakeLists.txt
add benchmarks osperf miss CMake build
fix ci fail in https://github.com/apache/nuttx/pull/14756
```
cmake -B build -DBOARD_CONFIG=qemu-armv8a/nsh_smp -GNinja
```
refresh pass
> cmake(build):add benchmarks osperf CMakeLists.txt

- interpreters/minibasic/CMakeLists.txt
- system/nxlooper/CMakeLists.txt
add interpreter basic and nxlooper missing CMake build
fix ci fail in https://github.com/apache/nuttx/actions/runs/11880169863/job/33103008538?pr=14756
```
cmake -B build -DBOARD_CONFIG=sim:minibasic -GNinja
cmake -B build -DBOARD_CONFIG=sim:alsa -GNinja
```
refresh pass
> cmake(build):add missing basic and nxlooper cmake script

- netutils/rtptools/CMakeLists.txt
> cmake:add missing rtptools CMake scripts

- system/adb/Kconfig
The `"%pV"` format depends on libc extension
e.g. Calling `avb_log()` in function `adbd_main()`:
```
adbd_main (***): 0x3fc9175cV
```
system/adb
- Selftest (esp32s3-devkit:adb(in process))
- NuttX CI
> system/adb: Fix log format error

- system/gcov/Kconfig
- system/gcov/gcov.c
system: support gcov output to stdout
For detailed description, please refer to https://github.com/apache/nuttx/pull/14838
qemu
> system: support gcov output to stdout

- testing/ostest/signest.c
testing/ostest/wdog.c: remove a set-only global
esp32s3-devkit:smp
> testing/ostest/wdog.c: remove a set-only global

- testing/ostest/signest.c
Note that MAX_SIGNO is a valid signal number.
esp32s3-devkit:smp
> testing/ostest/signest.c: fix the range of signals

- .github/workflows/build.yml
CMake+Ninja arm-none-eabi-ar: Argument list too long
has been fixed on the NuttX  https://github.com/apache/nuttx/pull/14892
You need to disable the msys2 cache from the GitHub action because we moved the Scheduled Merge Jobs to a new NuttX Mirror Repo. https://github.com/apache/nuttx/pull/14909
https://github.com/apache/nuttx-apps/actions/caches
Impact on user: No changes to user-facing functionality
Impact on build: Build process remains the same
Github
local msys2
```
$ cmake -B build -DBOARD_CONFIG=nucleo-l152re:nsh -GNinja
-- Initializing NuttX
Select HOST_WINDOWS=y
Select WINDOWS_MSYS=y
--   CMake:  3.28.1
--   Ninja:  1.11.1
--   Board:  nucleo-l152re
--   Config: nsh
--   Appdir: /home/nuttx/nxninja/apps
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler …
```
> build.yml: MSYS2 GitHub Action disabled ccache and enabled option -N (CMake+Ninja)

- system/coredump/Kconfig
- system/coredump/coredump.c
pervious coredump is depend on board_crashdump enabled,
but for some use case, we need to not open crashdump and open coredump restore.
for example AMP case.
also we already finished the blkout stream seek support, should make coredump infomation seek only depend on seek API.
should work with
https://github.com/apache/nuttx/pull/14997
if want using coredump to blk/mtd -> reboot -> restore to filesystem -> adb/ymodem/.. this kind of workflow.
the coredump infomation position has changed, we now able to put more data in coredump section.
we now able to close board_crash dump and open crash dump restore.
CI test, local arm-v8m board.
> Coredump restore application isolate with board_crashdump

- math/kissfft/CMakeLists.txt
- math/ruy/CMakeLists.txt
- mlearning/CMakeLists.txt
- mlearning/tflite-micro/CMakeLists.txt
- mlearning/tflite-micro/Kconfig
- system/flatbuffers/CMakeLists.txt
system/flatbuffers: fix patch flow of flatbuffers
```
Applying patch to flatbuffers
patching file '<'
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file '<.rej'
patching file '<'
Hunk #1 FAILED at 39.
1 out of 1 hunk FAILED -- saving rejects to file '<.rej'
patching file '<'
Hunk #1 FAILED at 495.
1 out of 1 hunk FAILED -- saving rejects to file '<.rej'
patching file '<'
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file '<.rej'
patch: **** Can't reopen file '<' : No such file or directory
-- Configuring done (12.8s)
-- Generating done (0.3s)
```
N/A
sim/nsh and enable CONFIG_SYSTEM_FLATBUFFERS
> system/flatbuffers: fix patch flow of flatbuffers

- crypto/controlse/Kconfig
- crypto/controlse/cmbedtls_se05x_extension.hxx
- crypto/mbedtls/0001-mbedtls-entropy_poll-use-getrandom-to-get-the-system.patch
- crypto/mbedtls/0002-mbedtls-add-mbedtls-x509-crt-pool.patch
- crypto/mbedtls/Kconfig
- crypto/mbedtls/include/mbedtls/mbedtls_config.h
Even though there is `CONFIG_MBEDTLS_VERSION`, this commit is needed for 2 reasons:
1. The patches: 0001 works almost as-is (with fuzz 2) but 0002 hunk #&#8203;4 failed and had to apply it manually. The targeted code (context) is lower down in library/x509_crt.c and thus the `patch` tool wouldn't apply it. The targeted code is the same and the inserted patches are identical to the initial contribution.
2. The changes in mbedtls_config.h: Following the same approach for the Kconfig as in the original contribution, this commit updates both Kconfig and mbedtls_config.h according to:
```
mbedtls$ git diff v3.4.0...v3.6.2 -- include/mbedtls/mbedtls_config.h
```
Default configuration is identical except for the following:
- `MBEDTLS_SSL_PROTO_TLS1_3` is now enabled by default (as per MbedTLS' …
> Update MbedTLS 3.4.0 -> 3.6.2 and set it as default

- mlearning/tflite-micro/0004-tflite-add-extern-C-to-main-function-to-avoid-c-mang.patch
- mlearning/tflite-micro/CMakeLists.txt
- mlearning/tflite-micro/Kconfig
tflm: add tflm hello world example into nuttx build
1. add tflm hello world example into nuttx build
2. add tflm model convert flow
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/README.md
N/A
Test on sim/tflm
```
$ cmake -B build -DBOARD_CONFIG=sim/tflm -GNinja
$ cmake --build build
$ ./build/nuttx
```
```
nsh> tflm_hello
0 (id=0): size=16, offset=0, first_used=0 last_used=1
1 (id=1): size=64, offset=64, first_used=1 last_used=2
2 (id=2): size=64, offset=0, first_used=2 last_used=3
3 (id=3): size=16, offset=64, first_used=3 last_used=3
0: 0000000000...................................................................... (1k)
1: …
```
> tflm: add tflm hello world example into nuttx build

- examples/lvgldemo/lvgldemo.c
In lvgl singleton mode, it is necessary to prevent users from trying to start multiple lvgl instances, otherwise lvgl data will be accessed by multiple processes, causing a crash.
lvgldemo
sim lvgl_fb
> lvgldemo: add LVGL duplicate initialization protection

- crypto/mbedtls/0003-Fix-MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT-warning.patch
- crypto/mbedtls/CMakeLists.txt
- crypto/mbedtls/Makefile
This is to patch upstream MbedTLS issue: https://github.com/Mbed-TLS/mbedtls/issues/9425 that triggers a -`Werror=undef` on `MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT` when `MBEDTLS_SSL_PROTO_DTLS` is undefined. There is no other way to silence that warning and it breaks builds in systems with `-Werror`. Once the upstream issue is resolved, this can be reverted.
Given that NuttX might stay with this particular version of MbedTLS for a while (even if upstream fixes the issue and releases it), this patch seems like the best compromise (hopefully acceptable?) until it is resolved.
Said warning breaks builds in systems configured with `-Werror` and  `CONFIG_MBEDTLS_SSL_PROTO_DTLS` not set, and there is no way to work around it other than:
- Not using `-Werror` (might not be an option)
- Enabling …
> MbedTLS: patch warning when DTLS is off

- system/usbmsc/Kconfig
- system/usbmsc/usbmsc.h
- system/usbmsc/usbmsc_main.c
Add support for setting paths bind to LUN at runtime.
```
nsh> msconn -h
Usage: msconn [-o OPTION]... [-l LUNs]...
Configures the USB mass storage device and exports the LUN(s).
Supported arguments
-o
nc: No const LUN
ro: Readonly
rw: Read/Write(default)
-l
Device path to export
Examples
1. Export const LUN(s) only
msconn
2. Export /dev/ramx and const LUN(s)
msconn -l /dev/ramx
3. Export /dev/ramx without const LUN
msconn -o nc -l /dev/ramx
```
```
nsh> msconn -o nc -l /dev/esp32s3flash
mcsonn_main: Creating block drivers
mcsonn_main: Configuring with NLUNS=1
mcsonn_main: handle=0x3fc8ec80
mcsonn_main: Bind LUN=0 to /dev/esp32s3flash
mcsonn_main: Connected
nsh> msdis
msdis: Disconnected
```
```
nsh> mkrd -m 10 -s 512 640
nsh> msconn
mcsonn_main: Creating block drivers
mcsonn_main: …
```
> system/usbmsc: Add support for setting paths bind to LUN at runtime

- system/nxdiag/Makefile
* system/nxdiag: Change the order for generating the sysinfo.h file
The generation of `sys info.h` depends on evaluating whether Espressif's HAL exists in the arch folder. However, cloning the HAL itself happens in the `context` phase of the build, so it is necessary to wait for it to finish before proceeding to the evaluation in nxdiag. This is done by using the `depend` phase to generate the `sysinfo.h` file.
Closes https://github.com/apache/nuttx/issues/15063
Internal CI testing + NuttX CI
> system/nxdiag: Change the order to generate the sysinfo.h file

- testing/mtetest/CMakeLists.txt
- testing/mtetest/Kconfig
- testing/mtetest/Make.defs
- testing/mtetest/Makefile
- testing/mtetest/mtetest.c
Added basic mte instructions, ldg, stg, irg, gmi instruction tests
➜  NX git:(master) ✗ qemu-system-aarch64 -cpu max -nographic \
-machine virt,virtualization=on,gic-version=3,mte=on \
-chardev stdio,id=con,mux=on, -serial chardev:con \
-mon chardev=con,mode=readline  -kernel ./nuttx/nuttx
- Ready to Boot Primary CPU
- Boot from EL2
- Boot from EL1
- Boot to C runtime for OS Initialize
NuttShell (NSH)
nsh>
nsh>
nsh> mtetest
Spawning process for test: mtetest1
Running test: mtetest1
Test 'mtetest1' completed
Spawning process for test: mtetest2
Running test: mtetest2
Test 'mtetest2' completed
Spawning process for test: mtetest3
Running test: mtetest3
Test 'mtetest3' completed
Spawning process for test: mtetest4
Running test: mtetest4
Test 'mtetest4' completed
Spawning process for test: …
> mtetest: Add a series of tests for the mte instruction set

- testing/drivertest/CMakeLists.txt
- testing/drivertest/Kconfig
- testing/drivertest/Makefile
- testing/drivertest/drivertest_mps2_isr_signal.c
cmocka case for call signal in exception direct handler.
case only,  fix cmake support for cmocka_driver_mps2_zerointerrupt
CI-test, local qemu mps2
> drivertest: add arm-m signal through isr case

- benchmarks/ramspeed/ramspeed_main.c
ramspeed: fix dest align typo, add not-aligned print
fix typo
CI-test, local board.
> ramspeed: fix dest align typo, add not-aligned print

- testing/ltp/Kconfig
Inside CI Build risc-v-05: `rv-virt:citest` fails with a Stack Overflow at ltp_interfaces_pthread_barrierattr_init_2_1:
- https://github.com/apache/nuttx/issues/15170
This PR doubles the Stack Size for `testing/ltp` (from 4096 bytes to 8192), so that `rv-virt:citest` completes successfully.
With this PR, `rv-virt:citest` will complete successfully.
We tested `rv-virt:citest` on Docker:
https://gist.github.com/lupyuen/3688826ed676971536249509ceefe834
```text
sudo docker run \
-it \
ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest \
/bin/bash
cd
git clone https://github.com/apache/nuttx
git clone https://github.com/lupyuen2/wip-nuttx-apps --branch ltp-stack apps
pushd nuttx ; echo NuttX Source: https://github.com/apache/nuttx/tree/$(git rev-parse HEAD) ; popd
pushd apps  ; echo NuttX Apps: …
```
> testing/ltp: Increase Stack Size

- system/uorb/sensor/gnss.c
uORB/sensor: Add macro for satellite format string.
Make it easier to extend the format of struct member.
uORB/sensor
1. Selftest - The format string remains the same
2. NuttX CI
> uORB/sensor: Add macro for satellite format string

- nshlib/Kconfig
- nshlib/nsh_proccmds.c
nshlib: add support for disable sigmask from ps command
before:
```
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK            STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 0069616 Idle_Task
1     0 224 FIFO     Kthread   - Waiting  Signal    0000000000000000 0067536 loop_task
2     0 224 FIFO     Kthread   - Waiting  Semaphore 0000000000000000 0067504 hpwork 0x400fcfe0 0x400fd028
3     3 100 FIFO     Task      - Running            0000000000000000 0067536 nsh_main
```
after:
```
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT       STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0069616 Idle_Task
1     0 224 FIFO     Kthread   - Waiting  Signal    0067536 loop_task
2     0 224 FIFO     Kthread   - …
```
> nshlib: add support for disable sigmask from ps command

- crypto/libtomcrypt/Kconfig
- interpreters/luamodules/luv/Kconfig
It has been removed a few years ago.
https://github.com/apache/nuttx/pull/6197
> Remove all references to CONFIG_SCHED_ATEXIT

- interpreters/luamodules/luv/Kconfig
interpreters/luamodules/luv: use "depends on" instead of "select"
build-tested with https://github.com/apache/nuttx/pull/15264
> interpreters/luamodules/luv: use "depends on" instead of "select"

- testing/ostest/Makefile
- testing/ostest/ostest.h
- testing/ostest/ostest_main.c
- testing/ostest/sched_thread_local.c
* ostest: Add test for GCC's tls (CONFIG_SCHED_THREAD_LOCAL)
Enables testing the GCC thread local storage (tls) and the __thread keyword within ostest.
Insert an automated test for the GCC's tls feature that is not yet tested on NuttX;
Internal CI testing + `rv-virt:citest` with `CONFIG_SCHED_THREAD_LOCAL=y`:
```
make distclean && ./tools/configure.sh rv-virt:citest && make menuconfig
```
Enable `CONFIG_SCHED_THREAD_LOCAL` on menuconfig. Then build and run it:
```
make EXTRAFLAGS="-Wno-cpp -Werror" -j$(nproc) && qemu-system-riscv32 -semihosting -M virt,aclint=on -cpu rv32 -smp 1 -bios none -kernel nuttx -nographic
``` 
Finally, run `ostest`:
```
nsh> ostest
...
sched_thread_local_test: g_tls_int value is: 6
sched_thread_local_test: Starting waiter thread 0
sched_thread_local_test: …
```
> ostest: Add test for GCC's tls (CONFIG_SCHED_THREAD_LOCAL)

- mlearning/tflite-micro/CMakeLists.txt
mlearning/tflite-micro: fix build break if enable cmsis-nn and neon
N/A
Cortex-R52
> mlearning/tflite-micro: fix build break if enable cmsis-nn and neon

- testing/testsuites/kernel/fs/cases/fs_fsync_test.c
- testing/testsuites/kernel/fs/cases/fs_stream_test.c
```
kernel/fs/cases/fs_stream_test.c:279:70: error: format ‘%zi’ expects argument of type ‘signed size_t’, but argument 4 has type ‘int’ [-Werror=format=]
279 |           syslog(LOG_ERR, "len = %zi != return value from fwrite = %zi",
|                                                                    ~~^
|                                                                      |
|                                                                      long int
|                                                                    %i
280 |                  len, ret);
|                       ~~~
|                       |
|                       int
kernel/fs/cases/fs_stream_test.c:311:69: error: format ‘%zi’ expects argument of type ‘signed size_t’, but argument 4 has type ‘int’ [-Werror=format=] …
```
> fs cases: fix compile error

- nshlib/nsh_parse.c
1. [nshlib/nsh_parse: Closing fds opened for redirection if necessary](https://github.com/apache/nuttx-apps/commit/ade300b1b9b28d295f4684f17802e5a59d874c96)
```
CID 1612743: (#1 of 1): RESOURCE_LEAK
12. leaked_handle: The handle variable fd_out is out of scope and will leak the handle.
```
2. [nshlib/nsh_parse: Removing unnecessary value assigning about redirection](https://github.com/apache/nuttx-apps/commit/6a50d76f1752e29563a680425384b239e0b74ab1)
```
CID 1612757: (#1 of 1): UNUSED_VALUE
assigned_value: The value -1 is assigned to param.fd_in here, but the stored value is overwritten before it can be used.
```
nshlib/nsh_parse
1. Selftesting with cmd return value and pipeline PASSED
2. NuttX CI
> nshlib/nsh_parse: Closing fds opened for redirection if necessary 

- testing/sensortest/sensortest.c
Add support to Speed Sensors on sensortest
Depends on: https://github.com/apache/nuttx/pull/15293
User will be able to use speed sensors
FS3000
> testing/sensortest: Add support to Velocity Sensors

- crypto/libtomcrypt/Kconfig
- interpreters/luamodules/luv/Kconfig
interpreters/luamodules/luv: use "depends on" instead of "select"
Included
https://github.com/apache/nuttx-apps/pull/2898
RELEASE
CI
> {bp-2902} interpreters/luamodules/luv: use "depends on" instead of "select"

- system/uorb/sensor/gnss.c
1. [uORB/sensor: Add carrier frequency for GNSS Satellite](https://github.com/apache/nuttx-apps/commit/87c303cba00abb63bf9d4b6652c01b738fb5c964)
The struct sensor_gnss_satellite.cf(carrier frequency) can be parsed from GSV.signal_id(e.g. NMEA 0183 v4.11) and struct sensor_gnss_satellite.constellation(sv_type)
See https://github.com/apache/nuttx/pull/15296
2. [uORB/sensor: Update macro of sensor_gnss format string](https://github.com/apache/nuttx-apps/commit/4e00f16b43cb954fe6038732d4b9748758f24c4e)
uORB/sensor
NuttX CI (depends on https://github.com/apache/nuttx/pull/15296)
> Add carrier frequency for GNSS Satellite

- testing/memstress/memorystress_main.c
In the original memstress multithreading, multiple threads shared a context. This is not enough for the stress testing of the use case, so we modified it so that each thread has an independent context to increase the overall memory pressure.
1. In a multi-threaded scenario, each thread has its own context
2. Adjust code structure
This slightly changes the usage, some parameters now have initial values.
Linux
sim:nsh
```
nsh> memstress
MemoryStress:
max_allocsize: 8192
nodelen: 1024
sleep_us: 100
nthreads: 1
debug: false
MemoryStress:testing...
```
> Multiple threads memorystress

- testing/scanftest/Kconfig
When I used scanftest, I found that some of its test cases depended on the function enabled by CONFIG_LIBC_SCANSET. So I added a dependency to it to ensure the correct operation of this test case.
```
"",
instead of
"   ",
to the first argument.
Test #29 returned 0 instead of 1.
Test #29 assigned
"",
instead of
"  q",
to the first argument.
Test #30 returned 0 instead of 2.
Test #30 assigned
"",
instead of
"  ",
to the first argument.
Test #30 assigned
"",
instead of
"Q",
to the second argument.
Test #31 returned 0 instead of 2.
Test #31 assigned
"",
instead of
"qwerty-",
to the first argument.
Test #31 assigned
"",
instead of
"QWERTY-",
to the second argument.
```
Add CONFIG_LIBC_SCANSET dependency to enable the use case
Compiles fine on local code
> scanftest:need enable CONFIG_LIBC_SCANSET

- interpreters/toywasm/Makefile
- interpreters/toywasm/include/toywasm_version.h
- interpreters/toywasm/tmpl/c-sections.in
- interpreters/toywasm/tmpl/license.in
> Update toywasm to v65.0.0 and fixes SPDX stuff

- system/libuv/Kconfig
libuv unconditionally uses pipe().
Fixes: https://github.com/apache/nuttx/issues/14773
RELEASE
CI
> {bp-2893} system/libuv/Kconfig: depends on CONFIG_PIPES

- testing/rpmsgdev/CMakeLists.txt
- testing/rpmsgdev/Kconfig
- testing/rpmsgdev/Make.defs
- testing/rpmsgdev/Makefile
- testing/rpmsgdev/testdev.c
1. `testing/rpmsgdev: Add from tests/testcases` - Copy from internal repo, history is squashed, see commit message
2. `testing/rpmsgdev: Format code` - Format using checkpatch.sh
3. `testing/rpmsgdev: Add option for rpmsgdev_export()` - Add option for rpmsgdev_export() and fix errors for other platform
New testcase for rpmsgdev
1. Selftest passed with `RPMSGDEV_TEST` enabled passed
2. NuttX CI
> Add testcases for rpmsgdev

- testing/monkey/monkey_main.c
Add runtime control to exit Monkey after a specified amount of time.
Monkey test.
`TESTING_MONKEY=y`
Example of using the --running-minutes parameter: Monkey testing ends after ten minutes.
```bash
monkey -t 11 --running-minutes 10
```
> testing/monkey: add running-minutes parameter

- .github/workflows/arch.yml
This PR increases the CI Jobs for Complex PRs from 50% to 100%, as explained here:
- https://github.com/apache/nuttx/issues/15451#issuecomment-2576576664
This PR also includes the fix for Simple x86 PR:
- https://github.com/apache/nuttx/pull/14896
By increasing the CI Checks, we will have better quality PRs that won't fail the Daily Builds.
Complex PRs will now complete CI Checks in 2 hours 10 mins. (Instead of 1.5 hours previously)
Complex PRs will now execute 100% of CI Jobs:
- https://github.com/lupyuen5/label-nuttx-apps/actions/runs/12663507115
> CI: Increase CI Jobs to 100% for Complex PRs

- testing/nettest/CMakeLists.txt
- testing/nettest/Kconfig
- testing/nettest/Make.defs
- testing/nettest/Makefile
- testing/nettest/tcp/test_tcp.c
- testing/nettest/tcp/test_tcp.h
- testing/nettest/tcp/test_tcp_common.c
- testing/nettest/tcp/test_tcp_connect_ipv4.c
Provides a network automated testing framework, including the main directory structure and Makefile, CMakeLists, Kconfig and other files such as tcp.
N/A
Local qemu environment verification
> apps/testing: Add a cmocka framework for network testing

- builtin/CMakeLists.txt
Support `add_application` to register without compiling,
used in scenarios where redefining the main symbol is not required
enhancement
CI test build
> cmake[enhance]:builtin register support NONE srcs target

- testing/stressapptest/CMakeLists.txt
- testing/stressapptest/Kconfig
- testing/stressapptest/Makefile
> stressapptest: Add download step

- examples/usbserial/host.c
Fix code style issue found in https://github.com/apache/nuttx-apps/pull/2939
- Break long preprocessor conditionals across multiple lines
- Add spaces around operators for better readability
- Reformat long string literals to fit within line length limits
- Improve consistency in spacing around parentheses and brackets
Code style only
GitHub CI
> examples/usbserial: Fix style issues in host.c

- examples/lp503x/lp503x_main.c
- netutils/rexec/rexec.c
- nshlib/nsh.h
- nshlib/nsh_console.h
- nshlib/nsh_login.c
- nshlib/nsh_mmcmds.c
- nshlib/nsh_parse.c
- nshlib/nsh_script.c
- nshlib/nsh_session.c
- nshlib/nsh_telnetlogin.c
- nshlib/nsh_timcmds.c
- system/nxcamera/nxcamera_main.c
- system/nxlooper/nxlooper_main.c
- system/nxplayer/nxplayer_main.c
- system/nxrecorder/nxrecorder_main.c
- system/readline/readline.c
- system/taskset/taskset.c
- system/trace/trace.c
Using `lib_get_tempbuffer()` to save stack space
1. apps/nshlib: Using `lib_get_tempbuffer()` to save stack space
2. apps/**nshlib**: replace `CONFIG_NSH_LINELEN` to `LINE_MAX`
3. apps/**system**: replace `CONFIG_NSH_LINELEN` to `LINE_MAX` (Picked from https://github.com/apache/nuttx-apps/pull/2918 by @anchao )
- apps/nshlib
- apps/system
1. Selftest as commit message shown
- Config: "esp32s3-devkit:adb" with `CONFIG_LINE_MAX=512`
- Test CMD: `ls | cat | cat | cat`
- Without this patch
|                | Before Test CMD | After Test CMD  |
|---------------:|----------------:|----------------:|
| nsh_main.STACK | 0002624/0008096 | 0002624/0008096 |
|       sh.STACK | 0003360/0004008 | 0003360/0004008 |
|     Free/Total |   355288/403116 |   355288/403116 |
- With this patch
| …
> apps/nshlib: Using `lib_get_tempbuffer()` to save stack space

- examples/rust/baremetal/Kconfig
- examples/rust/baremetal/Make.defs
- examples/rust/baremetal/Makefile
- examples/rust/baremetal/hello_rust_main.rs
- Renamed hello_rust example to rust/baremetal to better reflect its purpose
- Updated file headers and Makefile paths
- Maintained all existing Kconfig options and functionality
- Prepares for future Rust development patterns where Cargo will be the mainstream approach, with baremetal demonstrating traditional build method
- Creates clearer structure for Rust examples as we expand Rust support
- No functional changes to the example itself
- Better organization of Rust examples under examples/rust/
- Existing configurations using this example will continue to work
- Build system will now look for the example in the new location
- Confirmed Kconfig options remain unchanged
- GitHub CI passed and local build tested
> examples/rust: Rename hello_rust to rust/baremetal

- nshlib/Kconfig
* apps/nshlib: Remove the deprecated config `NSH_LINELEN`.
* POSIX standard `LINE_MAX` is used instead.
* See https://github.com/apache/nuttx/pull/15541 and https://github.com/apache/nuttx-apps/pull/2943 please.
apps/nshlib
CI
> apps/nshlib: Remove the deprecated config `NSH_LINELEN`

- examples/camera/camera_main.c
- testing/drivertest/drivertest_audio.c
- testing/drivertest/drivertest_framebuffer.c
- testing/drivertest/drivertest_gpio.c
- testing/drivertest/drivertest_lcd.c
1.Fixed skipped logic errors
2.Fix the GPIO test sim error
driver test
./tools/configure.sh -l sim:citest
make -j20
nsh> cmocka_driver_gpio
[==========] tests: Running 1 test(s).
[ RUN      ] drivertest_gpio
[input and output test]  outvalue is 1, invalue is 1
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 1, invalue is 1
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 0, invalue is 0
[input and output test]  outvalue is 1, invalue is 1
[input and output test]  outvalue is 1, invalue is 1
[       OK ] drivertest_gpio
[==========] tests: 1 test(s) …
> Driver test issue fix

- nshlib/nsh_parse.c
apps/nshlib: Save result and return ERROR if `lib_get_tempbuffer()` fails, missing goto ;-(
apps/nshlib: background
CI
> apps/nshlib: Save result and return ERROR if `lib_get_tempbuffer()` fails

- nshlib/nsh_mmcmds.c
Use lib_get_tempbuffer Saving stack
Saves the consumption of stack space
./tools/configure.sh -l sim:nsh
make -j5
> Use lib_get_tempbuffer Saving stack

- interpreters/wamr/Toolchain.defs
- Added explicit mapping of thumbv7a architecture to thumbv7 in the WAMR toolchain definitions
- WAMR's AOT compiler uses armv7/thumbv7 as the target architecture for all ARMv7-A processors
- This includes Cortex-A series processors like Cortex-A9 which use the armv7a/thumbv7a ISA
- Fixes AOT compilation for ARM Cortex-A processors using thumbv7a architecture
- Maintains compatibility with WAMR's expected target architecture naming
- Ensures consistent architecture targeting across all ARMv7-A processors
- No impact on other architectures or build configurations
GitHub CI and internal CI
> wamr: Map armv7a/thumbv7a to armv7/thumbv7 for wamrc

- examples/rust/hello/Cargo.toml
- Removed the unused panic handler from the `profile.dev` and `profile.release` sections
- Added `codegen-units = 1` and `opt-level = 'z'` to the `profile.release` section to optimize the binary size
- The changes result in a smaller binary size (244316 -> 228380 bytes)
- Reduces the final binary size by ~7%, improving resource utilization
- Maintains compatibility with existing functionality while optimizing for size
- Simplifies the build configuration by removing unnecessary panic handler settings
Tested with sabre-6quad:nsh
> rust/hello: Optimize the build flags

- cmake/nuttx_add_rust.cmake
- tools/Rust.mk
- Added support for `panic_immediate_abort` in Rust builds, which causes the system to abort immediately on panic instead of unwinding the stack
- Enabled `-Zbuild-std-features=panic_immediate_abort` flag for release builds when `CONFIG_DEBUG_FULLOPT` is set
- Updated both CMake and Makefile build systems to include the new flag
- Significantly reduces binary size (e.g., from 2270605 to 84987 bytes for riscv64imc)
- Changes panic behavior to immediate abort, which may be preferred for embedded systems
- Improves system reliability by preventing undefined behavior from stack unwinding in constrained environments
- Maintains compatibility with existing Rust code while providing a more deterministic panic handling mechanism
For example, if it is enabled, the system will panic immediately: …
> tools/Rust: Add support for panic_immediate_abort

- system/gdbstub/gdbstub.c
Add const for send buffer.
Minor, should have no impact on existing projects.
CI build pass.
> gdbstub: add const to send buffer

- nshlib/nsh_fscmds.c
- nshlib/nsh_fsutils.c
- nshlib/nsh_timcmds.c
- nshlib: Remove the unnecessary temp path buffer
- nshlib: Replace the big temp buffer with lib_get_[path|temp]buffer
* stack consumption decrease.
* nshlib: nsh_fscmds, nsh_fsutils, nsh_timcmds.
sim:nsh
> Reduce nsh stack consumption 

- system/cu/cu_main.c
* `system/cu`: remove canonical input mode from termios flag.
* `ASCII_DEL` stopped working after below change:
https://github.com/apache/nuttx/pull/14037
```
| commit df5c876932c4c82e8aee32adca651bb99d9d6200
| Author: zhangwenjian <zhangwenjian@xiaomi.com>
| Date:   Thu May 23 13:13:48 2024 +0800
|
|     libc:getline support backspace
|
|     Signed-off-by: zhangwenjian <zhangwenjian@xiaomi.com>
```
* Remove canonical input mode in order to again bring back support backspace in `cu`.
Signed-off-by: chao an <anchao.archer@bytedance.com>
CU: Backspace works again on cu / nsh console.
sim/rpproxy   sim/rpserver  cu and check the backspace whether works as expected.
> system/cu: remove canonical input mode from termios flag

- .gitignore
- examples/gps/Kconfig
- examples/gps/gps_main.c
This PR adds the ability to specify the GPS's serial port in the `gps` example, instead of only being able to use `/dev/ttyS1`. It also marks the MINMEA library as a dependency for the `gps` example.
Now that MINMEA is marked as a dependency, the `gps` example is unfortunately not visible in the list of applications until MINMEA is available. However, I wanted to avoid the use of `select` in Kconfig since it will not recursively enable dependencies.
The user is now also able to run the `gps` example with a serial port for the GPS specified, supporting this example on boards where the serial port is different. I have left `/dev/ttyS1` as the default when no port is specified to keep backward compatibility.
Closes #2966.
Tested this example with a board that has GPS on `/dev/ttyS0` and it …
> Allow GPS serial port to be specified as argument to `gps` example

- examples/module/main/Kconfig
- examples/module/main/module_main.c
This allows loading kernel modules from hostfs file system.
None
- local checks with FLAT mode NuttX on qemu-armv7a
- CI checks
> examples/module: allow module on hostfs

- cmake/nuttx_add_rust.cmake
- tools/Rust.mk
- Added support for x86 and x86_64 architectures in the Rust build system
- Updated `nuttx_rust_target_triple` function in `cmake/nuttx_add_rust.cmake` to handle x86 and x86_64 target triples
- Updated `RUST_TARGET_TRIPLE` macro in `tools/Rust.mk` to include x86 and x86_64 target triples
- Enables Rust crate compilation for x86 and x86_64 platforms
- No functional changes for existing architectures (ARM, RISC-V, etc.)
- Improves platform compatibility and expands Rust support in NuttX
GitHub CI and local build with rust on sim32/sim64
Refer to https://github.com/rust-lang/rust/pull/136181
> tools/Rust: Add support for x86 platform

- testing/ostest/CMakeLists.txt
Fix build break using cmake.
```
/nuttx/apps/testing/ostest/ostest_main.c:322:(.text.user_main+0x3c3): undefined reference to `sched_thread_local_test'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
cmake works now.
```
cmake -Bbuild -GNinja -DBOARD_CONFIG=qemu-intel64:nsh nuttx
ninja -C build
```
> ostest: fix cmake build break

- examples/amg88xx/Kconfig
Small fix for my previous sloppy work on amg88xx example.
I forgot to add correct dependency for kconfig options.
Also, I've followed DTH driver as example, you can see that in the kconfig stack size option :D
In non-interactive build, some defines previously polluted the header file with no impact on build. Now is fixed.
In interactive build (running make menuconfig ~or equivalent~) the amg88xx example was visible without enabling the needed driver
Manually.
Checked that the define is no longer included in the output header.
Check that the amg88xx example is not longer present in the menuconfig if the amg88xx driver is disabled.
> examples/amg88xx: fix kconfig

- testing/libc/wcstombs/CMakeLists.txt
- testing/libc/wcstombs/Kconfig
- testing/libc/wcstombs/Make.defs
- testing/libc/wcstombs/Makefile
- testing/libc/wcstombs/wcstombs_main.c
* testing/libc/wcstombs: Add testing application for wcstombs
This application tests the libc's `wcstombs` function for different len sizes (bigger than the converted string, exactly the size of it and smaller than it).
Enabling testing the libc's `wcstombs()`function. No impact on existing applications. This application is used to test a bugfix regarding `wcstombs` behavior.
Internal CI testing + `rv-virt:nsh`:
Build with:
```
make -j distclean && ./tools/configure.sh rv-virt:nsh && kconfig-tweak -e LIBC_LOCALE && kconfig-tweak -e TESTING_WCSTOMBS && make olddefconfig && make
```
Run with:
```
$ qemu-system-riscv32 -semihosting -M virt,aclint=on -cpu rv32 -smp 1 -bios none -kernel nuttx -nographic
ABC
nsh> help
help usage:  help [-v] [<cmd>]
.           cmp …
```
> testing/libc/wcstombs: Add testing application for wcstombs

- system/uorb/Kconfig
- system/uorb/listener.c
This pull request closes the issue raised [here](https://github.com/apache/nuttx/issues/15599).
Now `DEBUG_UORB` depends on `LIBC_FLOATINGPOINT`. This is because it is not possible to view sensor debug output without this enabled, which is only a problem for systems without an FPU (systems with an FPU have this enabled by default).
Users now have to enable `LIBC_FLOATINGPOINT` on systems without an FPU in order to use `DEBUG_UORB`. The dependency marked with `depends on` means that the uORB debug option will not be visible until `LIBC_FLOATINGPOINT` is selected, but this was determined to be acceptable in the discussion under the linked issue.
This prevents the annoyance of re-flashing the device because floating point printing was disabled, rendering debug output almost useless.
I have …
> system/uorb: require that LIBC_FLOATINGPOINT be enabled for DEBUG_UORB

- nshlib/nsh_builtin.c
nshlib/builtin: check background task before restore the signal
fix crash if:
CONFIG_SCHED_WAITPID=n
CONFIG_SCHED_CHILD_STATUS=y
The old signal will be restored only when sigaction is saved to avoid invaild access.
Signed-off-by: chao an <anchao.archer@bytedance.com>
N/A
1. build qemu-armv7a/rpserver_ivshmem
cmake -B build -DBOARD_CONFIG=qemu-armv7a/rpserver_ivshmem -GNinja
2. enable CONFIG_SCHED_CHILD_STATUS=y
cmake --build build -t menuconfig
3. start qemu
qemu-system-arm -cpu cortex-a7 -nographic -machine virt,highmem=off  -kernel build/nuttx -nographic
4. exec hello and system will hangup
>  nshlib/builtin: check background task before restore the signal

- examples/spislv_test/spislv_test.c
Improve example, now it can receive data from user
Spislv example was improved. Now it can receive data from user. It follow spitool features standard:
This changes was done in parallel at https://github.com/apache/nuttx/pull/14642. Both are tested together .
No Impact
This changes was done in parallel at https://github.com/apache/nuttx/pull/14642. Both are tested together .
> examples:spislave_test: Improve example

- system/fastboot/Kconfig
- system/fastboot/fastboot.c
Add prefix "SYSTEM" for USB boardctl configuration
```diff
- FASTBOOTD_USB_BOARDCTL
+ SYSTEM_FASTBOOTD_USB_BOARDCTL
```
Reason:
```
$ grep "^config " Kconfig -rn
15:config SYSTEM_FASTBOOTD_PRIORITY
19:config SYSTEM_FASTBOOTD_STACKSIZE
23:config SYSTEM_FASTBOOTD_DOWNLOAD_MAX
27:config SYSTEM_FASTBOOTD_USB_BOARDCTL
```
system/fastboot
CI
> system/fastboot: Add prefix "SYSTEM" for USB boardctl configuration

- system/cpuload/Make.defs
* system/cpuload: Fix application's Make.defs location
The PR https://github.com/apache/nuttx-apps/pull/2974 first moved it to `testing/sched/cpuload` and the `Make.defs` was adjusted accordingly. However, during the review process, it was moved to `system/cpuload` folder, but its `Make.defs` wasn't updated. This PR fixes it.
Impact on user: YES. It enables users to build `cpuload` app.
Impact on build: YES. Now we can build it.
Impact on hardware: NO.
Impact on documentation: NO.
Impact on security: NO.
Impact on compatibility: NO.
Test it for ESP32-S3's `nsh` defconfig, for instance:
```
make -j distclean && ./tools/configure.sh esp32s3-devkit:nsh && kconfig-tweak -e SCHED_CPULOAD_SYSCLK && kconfig-tweak -e CONFIG_SYSTEM_CPULOAD && make olddefconfig && make flash ESPTOOL_BINDIR=./ …
```
> system/cpuload: Fix application's Make.defs location

- examples/rust/hello/Make.defs
- examples/spislv_test/Make.defs
- mlearning/cmsis-nn/Make.defs
- system/sensorscope/Make.defs
- testing/cxx/cxxsize/Make.defs
- testing/cxx/cxxsize/Makefile
fix Relative file path does not match actual file.
Impact on user: NO
Impact on build: NO
local
> [nxstyle] fix Relative file path

- system/irtest/Make.defs
fix this error
make[3] *** /nuttxspace/nuttx/apps/testing/irtest: No such file or directory.  Stop.
same error with macOS on Nuttx mirror
```
make: *** /Users/runner/work/nuttx/nuttx/sources/apps/testing/irtest: No such file or directory.  Stop.
make[2]: *** [/Users/runner/work/nuttx/nuttx/sources/apps/testing/irtest_context] Error 2
make[2]: Target `context_all' not remade because of errors.
make[1]: *** [context] Error 2
make: *** [/Users/runner/work/nuttx/nuttx/sources/apps/.context] Error 2
make: Target `all' not remade because of errors.
/Users/runner/work/nuttx/nuttx/sources/nuttx/tools/testbuild.sh: line 385: /Users/runner/work/nuttx/nuttx/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
```
https://github.com/NuttX/nuttx/actions/runs/13430411340/job/37521010985#logs …
> system/irtest/Make.defs: fixed the wrong path

- interpreters/quickjs/CMakeLists.txt
Setting the right version 2024-02-14
To avoid future breakage, used the URL with last commit ID
PR https://github.com/apache/nuttx-apps/pull/2993
Impact on user: NO.
Impact on build: YES.Prevents future breaks if the quickjs repository changes..
Build it with:
cmake -B build -DBOARD_CONFIG=sim:quickjs -GNinja
cmake --build build
> interpreters/quickjs/CMakeLists.txt: Sync of build Cmake with build Make

- netutils/pppd/ppp.h
This commit add include necessary when we enable network debug feature using ppp feature.
When we enable debug feature :
-> Debug Options, Network Debug Feature, [enable all].
Build issue happens:
CC:  netlib_ipv4addrconv.c In file included from ahdlc.c:45:
```
ahdlc.c: In function 'ahdlc_rx':
ppp_conf.h:57:33: warning: implicit declaration of function 'ninfo' [-Wimplicit-function-declaration]
57 | #define debug_printf            ninfo
|                                 ^~~~~
ahdlc.c:53:21: note: in expansion of macro 'debug_printf'
53 | #  define DEBUG1(x) debug_printf x
|                     ^~~~~~~~~~~~
ahdlc.c:152:11: note: in expansion of macro 'DEBUG1'
152 |           DEBUG1(("Discard since char is < 0x20 hex and asysnc map is 0\n"));
|           ^~~~~~
CC:  nsh_fscmds.c In file …
```
> netutils/pppd/ppp.h: Fix build issue when network debug is enabled

- system/fastboot/Kconfig
- system/fastboot/fastboot.c
Add support for fastboot oem shell to support executing custom commands.
Usage
```
fastboot oem shell <command>
```
system/fastboot
```
$ fastboot --version
fastboot version 35.0.2-12147458
$ fastboot oem shell ls /FILE_NOT_EXISTS
FAILED (remote: 'error detected 255 4')
fastboot: error: Command failed
$ fastboot oem shell ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK            STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 0003056 Idle_Task
1     0 224 RR       Kthread   - Waiting  Semaphore 0000000000000000 0001976 hpwork 0x3fc8bd50 0x3fc8bd80
2     2 100 RR       Task      - Waiting  Semaphore 0000000000000000 0004048 nsh_main
3     3 100 RR       Task      - Ready              0000000000000000 0001992 fastbootd
4     4 100 RR …
```
> system/fastboot: Add support for fastboot oem shell

- crypto/mbedtls/Kconfig
- examples/rmtchar/Kconfig
- system/settings/Kconfig
- system/zlib/Kconfig
- testing/mm/stressapptest/Kconfig
- testing/sched/timerjitter/Kconfig
Remove spaces from Kconfig files
Add TABs
Replace help => ---help---
Remove extra TABs
Impact on user: NO
Impact on build: NO
local
> [Kconfig style] Fix Kconfig style

- interpreters/toywasm/Makefile
- interpreters/toywasm/include/toywasm_version.h
toywasm: bump version v65.0.0 -> v66.0.0.
see https://github.com/yamt/toywasm/releases/tag/v66.0.0
interpreters/toywasm
?
> toywasm: bump to v66.0.0

- testing/cxx/uclibcxx_test/Make.defs
- testing/libc/atomic/Make.defs
I'm sorry. In my previous modification to apps/testing folder, I made a mistake in the make.defs of uclibcxx and atomic.
The main impacts are the testing/libc/atomic/Make.defs file and testing/cxx/uclibcxx_test/Make.defs
testing/libc/atomic/Make.defs:23:
CONFIGURED_APPS += $(APPDIR)/testing/sched/atomic
CONFIGURED_APPS += $(APPDIR)/testing/libc/atomic
testing/cxx/uclibcxx_test/Make.defs:22:
CONFIGURED_APPS += $(APPDIR)/testing//cxx/uclibcxx_test
--------->
CONFIGURED_APPS += $(APPDIR)/testing/cxx/uclibcxx_test
CI TEST.
> apps/testing:fix uclibc atomic make.defs error

- testing/ostest/nxevent.c
In the case of slow overall system response (such as when MM_KASAN is turned on and RR_INTERVAL > 200), the nxevent case work thread will not be executed and will be switched back to the main thread, so that the event does not get the expected result and the case fails.
By adjusting the thread priority, the work thread can be scheduled to avoid the expected result failure.
Adjusted the priority of the nxevent creation thread in ostest.
Local test in QEMU with case of slow overall system response is ok.
> ostest:Fix the issue that nxevent pthread was not executed, causing case failed

- benchmarks/osperf/osperf.c
Fix osperf build warning
```
In function 'performance_gettime',
inlined from 'hpwork_performance' at osperf.c:245:10:
osperf.c:123:3: error: 'result.end' may be used uninitialized [-Werror=maybe-uninitialized]
123 |   up_perf_convert(result->end - result->start, &ts);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
osperf.c: In function 'hpwork_performance':
osperf.c:228:29: note: 'result.end' was declared here
228 |   struct performance_time_s result;
|                             ^~~~~~
CC:  audio/lib_buffer.c
CC:  common/arm64_initialize.c
CC:  builtin/lib_builtin_getname.c
```
* Build: fix warnings.
* Runtime: initialize memory before use.
Local build success
> benchmarks/osperf: fix warning maybe-uninitialized

- examples/unionfs/Kconfig
- examples/userfs/Kconfig
- testing/fs/nxffs/Kconfig
- testing/fs/smart/Kconfig
Adjusted Kconfig of some use cases under apps to ensure that the correct configuration can be opened before using these use cases.
The changes are as follows:
1.ftpd
2.unionfs
3.userfs
4.nxffs
5.smart
Adjusted the depends config of the above testcase/demo
> examples: Add depends to different test cases 

- boot/nxboot/Kconfig
- boot/nxboot/include/nxboot.h
- boot/nxboot/loader/boot.c
- boot/nxboot/loader/flash.c
- boot/nxboot/loader/flash.h
- boot/nxboot/tools/nximage.py
This commit enhances the bootloader capabilities. The image's header is extended with header version, size, platform identifier and pointer to optional next header. CRC32 now includes part of the header in its calculation as well.
The change also avoids having two different magics for image uploaded over programmer and update image. Both these images have the same magic and this magic is changed internally by the bootloader's logic. The change is needed because image with standard magic is automatically considered as a confirmed image (uploaded with programmer).
The current implementation avoids tails at all, therefore the user application uploading the image does not have to erase the tail before new upload. The image is considered as confirmed if it has standard magic or its recovery is …
> [BREAKING] boot/nxboot: enhance bootloader capabilities and decision logic

- games/snake/Kconfig
- games/snake/Make.defs
- games/snake/Makefile
- games/snake/snake_input_console.h
- games/snake/snake_input_gpio.h
- games/snake/snake_inputs.h
- games/snake/snake_main.c
* games/snake: Add snake game
Add snake game support to have more demo games to show
Impact on user: No, game was not in repo before
Impact on build: No, game is not related to build system
Impact on hardware: No
Impact on documentation: Yes, doc update added on nuttx repo
Impact on security: No
Impact on compatibility: No
```
make distclean && ./tools/configure.sh esp32-devkitc:snake && make -j && make download ESPTOOL_PORT=/dev/ttyUSB0 ESPTOOL_BAUD=921600 && picocom /dev/ttyUSB0 -b 115200
```
Alternatively, you can use `esp32-devkitc:nsh` defconfig with enabling following options:
```
CONFIG_DEV_GPIO=y
CONFIG_ESP32_GPIO_IRQ=y
CONFIG_ESP_RMT=y
CONFIG_EXAMPLES_GPIO=y
CONFIG_EXAMPLES_RMTCHAR=y
CONFIG_EXAMPLES_RMTCHAR_RX=y
CONFIG_EXAMPLES_RMTCHAR_TX=y
CONFIG_EXAMPLES_WS2812=y …
```
> games/snake: Add snake game

- examples/fbcon/CMakeLists.txt
- examples/fbcon/Kconfig
- examples/fbcon/Make.defs
- examples/fbcon/Makefile
- examples/fbcon/fbcon_main.c
This adds a new "Example App" that allows a framebuffer character device to be used for STDOUT and/or STDERR text rendering.
It is a standalone app so has no impact on anything else
On a custom board (SAMA5D27C-D1g with 800x480 TFT
> Add fbcon example

- .github/workflows/build.yml
msvc job is missing brought into sync with nuttx repository
added:
- CI: Kill CI Test after 2 hours
see https://github.com/apache/nuttx/pull/14849
- msvc job => Windows native
https://github.com/apache/nuttx/pull/13894
https://github.com/apache/nuttx/pull/15989
Impact on user: NO.
Impact on build: NO.
CI
> build.yml: Brought into sync with NuttX repository

- examples/fbcon/Kconfig
This PR fixes the `endchoice` and `help` in the Kconfig for fbcon
- https://github.com/apache/nuttx-apps/pull/3029#discussion_r2006527306
This patch will fix these build errors:
```text
apps/examples/fbcon/Kconfig:62: syntax error
apps/examples/fbcon/Kconfig:172: unknown option "---help--"
```
https://github.com/lupyuen/nuttx-riscv64/actions/runs/13981663903/job/39147989438#step:5:158
This PR will fix the build errors for various NuttX Targets, e.g. `rv-virt:nsh`
Tested with local build of `rv-virt:nsh` on macOS.
> examples/fbcon: Fix endchoice and help in Kconfig

- examples/xmlrpc/calls.c
* examples/xmlrpc/calls.c used 80 bytes call buffers.
* update buffers to CONFIG_XMLRPC_STRINGSIZE+1 that is build time configurable.
* this keeps buffers size coherent with configuration.
* updated internal variable names to pass lint checks.
* xmlrpc strings and buffers are now equal in size that prevents overflows.
Please help in runtime testing :-)
```
% uname -a
FreeBSD octagon 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
% ./tools/configure.sh -B esp32-devkitc:wifinsh
% gmake menuconfig <- enable apps / examples / xmlrpc.
% kconfig-diff
BASE_DEFCONFIG "esp32-devkitc:wifinsh" -> "esp32-devkitc:wifinsh-dirty"
EXAMPLES_XMLRPC n -> y
NETUTILS_XMLRPC n -> y
+EXAMPLES_XMLRPC_BUFFERSIZE 1024
+XMLRPC_STRINGSIZE 64
% gmake -j8
Create version.h
Cloning Espressif HAL for 3rd Party …
```
> examples/xmlrpc: Fix calls buffers size.

- canutils/lely-canopen/0001-tools-eliminate-multiple-definitions-of-poll-compile.patch
- canutils/lely-canopen/0002-tools-coctl.c-fix-printf-issues.patch
- canutils/lely-canopen/0003-src-co-nmt.c-fix-compilation.patch
- canutils/lely-canopen/0004-tools-coctl.c-add-missing-mutex-init.patch
- canutils/lely-canopen/0005-add-NuttX-support.patch
- canutils/lely-canopen/CMakeLists.txt
- canutils/lely-canopen/Kconfig
- canutils/lely-canopen/Makefile
This commit fixes lely-canopen build for make and cmake.
It also update lely commit tag to the latest lely master.
The required changes are now split into several patches to make it easier to fix any issues in the future.
NuttX upstream doesn't have any lely configs at this moment so over the years the compilation has been broken.
fix lely build
lely compiles without errors for local configs that I have with make and cmake.
> fix build for canutilis/lely-canopen

- modbus/CMakeLists.txt
fix cmake build for FreeModBus:
1. nuttx-apps/modbus/mb.c:50:12: fatal error: mbrtu.h: No such file or directory 50 | #  include "mbrtu.h"
2. nuttx-apps/modbus/functions/mbutils.c:41:10: fatal error: port.h: No such file or directory 41 | #include "port.h"
3. various "undefined reference to" errors
fix cmake build for modbus
local modbus RTU configuration with cmake
> cmake: fix cmake build for FreeModBus

- nshlib/Kconfig
In `nshlib/Kconfig:509`:
`NSH_DISABLE_NSFMOUNT` should be `NSH_DISABLE_NFSMOUNT`
Typo fixed. Without this fix, the function "Disable nfsmount" in nsh would not work,
as the code is controlled by `CONFIG_NSH_DISABLE_NFSMOUNT`
Test on `sim:nsh`
1. enabled NFS function from menuconfig
2. build and enter nsh shell
3. use `help` to check available command
```
$ ./nuttx 
NuttShell (NSH)
nsh> help
help usage:  help [-v] [<cmd>]
.           cmp         fdinfo      ls          printf      true        
[           dirname     free        mkdir       ps          truncate    
?           dd          help        mkfatfs     pwd         uname       
alias       df          hexdump     mkfifo      readlink    umount      
unalias     dmesg       ifconfig    mkrd        rm          unset       
arp …
```
> nshlib: typo fixed in Kconfig

- cmake/nuttx_add_rust.cmake
- examples/rust/slint/Cargo.toml
- examples/rust/slint/src/lib.rs
- tools/Rust.mk
**Summary:**
* Update the NuttX Rust crate dependency to use the `main` branch instead of `master` for consistency with upstream repository changes.
* Fix framebuffer pixel format check by replacing `Format::RGB565` with `FB_FMT_RGB16_565` to ensure accurate validation of the video format.
nuttx-rs (https://github.com/no1wudi/nuttx-rs) generate binding from NuttX's C header now, which simplify the build setup and get more accurate struct/data type definitions.
**Impact:**
* **New feature added?** NO  
* **Impact on user?** NO
* **Impact on build?** YES - Updates dependency branch in `Cargo.toml`, affecting crate resolution.  
* **Impact on hardware?** NO  
* **Impact on documentation?** NO  
* **Impact on security?** NO  
* **Impact on compatibility?** NO  
This PR ensures compatibility …
> Enhancement for Rust build

- testing/ostest/mutex.c
This change enhances NuttX's test coverage by validating mutex behavior
in non-standard relocation scenarios, while explicitly noting this
extends beyond POSIX specifications. The test helps prevent regressions
in edge-case mutex handling.
* Add test case for mutex move functionality in ostest
* Verifies correct behavior when a mutex is relocated in memory
* Introduces new test structure with thread argument passing
* Includes validation of mutex state across thread operations
* Related to Rust language discussion: https://github.com/rust-lang/rust/pull/138400
* New feature added?: YES - Adds new mutex move test scenario
* Impact on user?: NO - Test suite enhancement only
* Impact on build?: NO - Existing test infrastructure used
* Impact on hardware?: NO - Pure software validation
* …
> ostest: Implement mutex move test functionality

- crypto/mbedtls/Kconfig
Current defconfig and mbedtls_config.h can not enable the definition of MBEDTLS_SSL_COOKIE_C. This option is now added to Kconfig.
mbedtls: Add "Enable SSL cookie implementation" to Kconfig.
sim:matter
> mbedtls: add MBEDTLS_SSL_COOKIE_C to Kconfig for manual configuration

- benchmarks/mtd/CMakeLists.txt
- benchmarks/mtd/Kconfig
- benchmarks/mtd/Make.defs
- benchmarks/mtd/Makefile
- benchmarks/mtd/mtd.c
This test allows measuring write and read operations on an MTD flash device, evaluating its transfer rates.
Impact on user: YES, by providing a testing application for MTD devices (without any kind of buffering or file system).
Impact on build: NO.
Impact on hardware: NO.
Impact on documentation: NO.
Impact on security: NO.
Impact on compatibility: NO.
To test it, create an MTD partition and register it as a block driver. Using `esp32s3-devkit:spiflash` defconfig, let's try it:
First of all, apply the following patch (which will be submitted to the `nuttx` repository):
```
diff --git a/boards/xtensa/esp32s3/common/src/esp32s3_board_spiflash.c b/boards/xtensa/esp32s3/common/src/esp32s3_board_spiflash.c
index 7d0ceecc6d..37c15357c2 100644
--- …
```
> benchmarks/mtd: Add MTD transfer rates benchmark.

- modbus/Kconfig
- modbus/nuttx/port.h
- modbus/nuttx/portother.c
Introduce new configuration option that allow disable all logging functionality for FreeModBus. This option is useful for small systems when we don't use any logging features.
fix broken compilation when FILE_STREAM is disabled
local modbus RTU configuration with file streams disabled
> modbus: add an option to disable log

- system/nxplayer/nxplayer.c
- system/nxrecorder/nxrecorder.c
system/nxplayer/nxrecorder: move apb buffer instance to stack
move apb buffer instance to stack to avoid alloc buffer from heap
Signed-off-by: chao an <anchao.archer@bytedance.com>
N/A
ci-check
> system/nxplayer/nxrecorder: move apb buffer instance to stack

- system/nxlooper/nxlooper.c
nxlooper: fix typo in nxlooper
replace CONFIG_O_MULTI_SESSION to CONFIG_AUDIO_MULTI_SESSION
Signed-off-by: chao an <anchao.archer@bytedance.com>
N/A
enable CONFIG_AUDIO_MULTI_SESSION
> nxlooper: fix typo in nxlooper

- testing/drivers/drivertest/drivertest_uart.c
drivertest_uart: Pass in the specified parameters to test
https://github.com/apache/nuttx/blob/master/tools/ci/testrun/script/test_framework/test_cmocka.py
cmocka --skip test_case_posix_timer|test_case_oneshot|write_default|read_default|burst_test|gpiotest01
In the CI of the community, this test is skipped because this test will block the terminal, and I think that the test added to cmocka should not be designed this way
drivertest_uart
local test
> drivertest_uart: Pass in the specified parameters to test

- nshlib/nsh_fsutils.c
Commit 5330966 replaced local static buffer with malloc allocated `lib_get_pathbuffer`. This however prevents the usage of `sizeof(buffer)` in the follow up read function, therefore the read size has to be specified as `PATH_MAX - 1`.
This fixes the functionality of `pidof` function call (and subsequently `pkill` call that uses `pidof`).
Fixes the behavior of `pidof` and `pkill` calls.
Tested with `sim:nsh` configuration.
Before the change
```
NuttShell (NSH) NuttX-12.8.0
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK            STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 0069616 Idle_Task
1     0 224 FIFO     Kthread   - Waiting  Signal    0000000000000000 0067528 loop_task
2     0 224 FIFO     Kthread   - Waiting  Semaphore …
```
> nshlib/nsh_fsutils.c: fix getpid_callback function read size

- testing/drivers/drivertest/drivertest_adc.c
- testing/drivers/drivertest/drivertest_audio.c
- testing/drivers/drivertest/drivertest_block.c
- testing/drivers/drivertest/drivertest_framebuffer.c
- testing/drivers/drivertest/drivertest_i2c_spi.c
- testing/drivers/drivertest/drivertest_lcd.c
- testing/drivers/drivertest/drivertest_mps2.c
- testing/drivers/drivertest/drivertest_mps2_zerointerrupt.c
- testing/drivers/drivertest/drivertest_oneshot.c
- testing/drivers/drivertest/drivertest_pm.c
- testing/drivers/drivertest/drivertest_pm_runtime.c
- testing/drivers/drivertest/drivertest_pm_smp.c
- testing/drivers/drivertest/drivertest_posix_timer.c
- testing/drivers/drivertest/drivertest_pwm.c
- testing/drivers/drivertest/drivertest_regulator.c
- testing/drivers/drivertest/drivertest_relay.c
- testing/drivers/drivertest/drivertest_rtc.c
- testing/drivers/drivertest/drivertest_simple.c
- testing/drivers/drivertest/drivertest_timer.c
- testing/drivers/drivertest/drivertest_touchpanel.c
- testing/drivers/drivertest/drivertest_watchdog.c
1.Some test functions are named too simply
2.Many driver tests depend on specific configurations and hardware, and the unified specification name facilitates cmocka to skip tests by using the skip parameter for wildcard matching
None
local test
> testing/drivers/drivertest: Uniform test case name

- examples/adc/adc_main.c
examples/adc: fix printf warning
none
adc with sim
> examples/adc: fix printf warning

- boot/mcuboot/CMakeLists.txt
- crypto/tinydtls/CMakeLists.txt
- graphics/lvgl/CMakeLists.txt
- netutils/cjson/CMakeLists.txt
- netutils/wakaama/CMakeLists.txt
- system/adb/CMakeLists.txt
- system/argtable3/CMakeLists.txt
- testing/mm/stressapptest/CMakeLists.txt
- testing/unity/CMakeLists.txt
- wireless/bluetooth/nimble/CMakeLists.txt
remove empty strings from FetchContent to eliminate cmake build warnings like this:
CMake Warning (dev) at /usr/share/cmake/Modules/FetchContent.cmake:1564 (cmake_parse_arguments):
The BUILD_COMMAND keyword was followed by an empty string or no value at
all.  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
ARG_BUILD_COMMAND variable rather than setting it to an empty string.
eliminate empty commands which cause warnings for cmake version >= 3.31
unity and nimble with cmake build with no warnings
> cmake: remove empty strings from FetchContent

- examples/nimble_blecent/CMakeLists.txt
- examples/nimble_blecent/Kconfig
- examples/nimble_blecent/Make.defs
- examples/nimble_blecent/Makefile
- examples/nimble_blecent/blecent.h
- examples/nimble_blecent/misc.c
- examples/nimble_blecent/nimble_blecent_main.c
- examples/nimble_blecent/peer.c
- examples/nimble_bleprph/CMakeLists.txt
- examples/nimble_bleprph/Kconfig
- examples/nimble_bleprph/Make.defs
- examples/nimble_bleprph/Makefile
- examples/nimble_bleprph/bleprph.h
- examples/nimble_bleprph/gatt_svr.c
- examples/nimble_bleprph/misc.c
- examples/nimble_bleprph/nimble_bleprph_main.c
1.   examples/nimble_bleprph: fix various coding standard issues and fix compilation for make
2. examples/nimble_blecent: fix various coding standard issues  and fix compilation for make
fix various coding standard issues, no functional changes
compile nimble_bleprph and nimble_blecent with make
> examples: fix coding standard issues for nimble_blecent and nimble_bleprpt

- examples/gps/gps_main.c
This PR modifies some `printf` calls from `%d` to `PRId32` to solve warnings due to compiler changes.
Relates to this [issue](https://github.com/apache/nuttx/issues/15755).
Example of the build warning, when compiling with new int types for Xtensa devices:
```
Error: gps_main.c:102:61: error: format '%d' expects argument of type 'int', but argument 2 has type 'int_least32_t' {aka 'long int'} [-Werror=format=]
102 |                   printf("Fixed-point Latitude...........: %d\n",
|                                                            ~^
|                                                             |
|                                                             int
|                                                            %ld
103 | …
```
> gps: modify printf to use format specifier macros

- benchmarks/mtd/Kconfig
- benchmarks/mtd/mtd.c
The application requires libc's floating point support. Although it may be already enabled by other applications and/or hardware support, it should be explicitly selected by the app too. Also, to improve portability, use `PRIxxx` macro instead of int/long int format specifiers.
Impact on user: YES, by improving portability.
Impact on build: YES, by avoiding build errors related to the variable format.
Impact on hardware: NO.
Impact on documentation: NO.
Impact on security: NO.
Impact on compatibility: NO.
Not a specific one. One can use the same testing procedure at https://github.com/apache/nuttx-apps/pull/3033
> benchmarks/mtd: Select libc's floating point support and improve format specifiers portability

- industry/foc/fixed16/foc_feedforward.c
- industry/foc/float/foc_feedforward.c
fix typo in calculations for vdq_comp->q. It should use idq->d not idq->q.
Reported in https://github.com/apache/nuttx-apps/issues/3047
here foc diagram for reference: https://i.sstatic.net/ltXRB.png
obvious typo
CI
> foc/foc_feedforward.c: vdq_comp->q should use idq->d

- import/Make.defs
kernel build:avoid multiple definition ld script
bugfix
qemu armv7a with kernel build
> kernel build:avoid multiple definition ld script

- logging/nxscope/nxscope_pser.c
use crc16xmodem directly to avoid using confusing crc16()
depends on https://github.com/apache/nuttx/pull/16147
none
CI
> nxscope/nxscope_pser.c: use xmodem crc16 directly

- interpreters/toywasm/Makefile
- interpreters/toywasm/include/toywasm_version.h
toywasm: bump to v67.
https://github.com/yamt/toywasm/releases/tag/v67.0.0
the "fix GCC warnings for the target with long uint32_t" change is for https://github.com/apache/nuttx/pull/16022.
* tested on sim/macOS/amd64
* build-tested esp32s3-devkit:toywasm with https://github.com/apache/nuttx/pull/16022
> toywasm: bump to v67

- examples/camera/camera_bkgd.c
Use SEM_INITIALIZER macro instead of direct { 0 }
Initialize the semaphore using the SEM_INITIALIZER macro
No impact, but direct assigning 0 conflicts with NuttX PR https://github.com/apache/nuttx/pull/16194
Tested that this compiles
> examples/camera: Initialize g_nximage semaphore with SEM_INITIALIZER

- canutils/lely-canopen/0005-add-NuttX-support.patch
- canutils/slcan/slcan.c
This matches PR https://github.com/apache/nuttx/pull/16225 in Nuttx, where units for SocketCAN bitrate ioctls were changed to bits-per-second, matching what Linux uses for SocketCAN bitrate (though Linux uses netlink instead of ioctl). In that PR, the data structure passed to bitrate ioctls was changed to use bps, so all code in nuttx-apps using those iotctls needs to be changed as well.
No user impact.
The change is needed for tools to work after Nuttx PR is merged.
* Is new feature added? NO Is existing feature changed? NO
* Impact on build: NO
* Impact on hardware: NO
* Impact on documentation: NO
* Impact on security: NO
* Impact on compatibility: NO
Tested using slcan to check bitrate is properly set (CAN message still arrive properly) after this change.
> canutils: use bps units for bitrate in SocketCAN interfaces.

- examples/elf/Kconfig
- examples/elf/elf_main.c
- examples/elf/tests/.gitignore
- examples/elf/tests/Makefile
Add the possibility to create a `romfs` image for an "external" file system. The `romfs.img` can directly be written to a configurable `mtdblock` device.
The elf loader can also be used to generate a `romfs.img` that contains applications. This `romfs.img` can be written directly to a internal `mtdblock` device. The example then provides a method to illustrate how to separate `kernel` from applications and allows recompilation and update of the `romfs` without a kernel update.   
None, it is an extra sample configuration.
Tested on `esp32_devkitc:elf`. The example configuration is:
```console
<*> ELF Loader Example
ELF File System (External File system)  --->
[*]     Mount external file system
[ ]         Removable file system
(romfs) External file system type
(/dev/mtdblock0) Block …
```
> examples/elf: add possibility to create romfs image

- canutils/slcan/slcan.c
A recent change (https://github.com/apache/nuttx/pull/16199) has made the bitrate setting no longer bring the interface up. Moreover, it is now no longer possible to change bitrate of a CAN interface if it is up. Therefore, slcan needs to bring the interface down to change it. Fortunately, it already had commands to open and close the interface which map nicely to this.
slcan would be unable to change the interface bitrate after the aforementioned (already merged) Nuttx patch, without this change.
Tested using a second serial line (/dev/gsmtty2) and CAN interface (named can_6_14) on a custom board. The CAN bus is attacked using an adapter talking socketcand protocol:
```
< hi >< can_6_14 B 1000000 -1 -1 -1 -1 -1 -1 -1 >
< ok >< open can_6_14 >
< ok >< send 123 0 >
```
Before this patch …
> Make slcan brin the interface up/down with the appropiate commands

- system/uorb/CMakeLists.txt
- system/uorb/Kconfig
- system/uorb/Makefile
- system/uorb/uORB/epoll.c
- system/uorb/uORB/loop.c
- system/uorb/uORB/uORB.h
Configured loop function with `UORB_LOOP_MAX_EVENTS`, added eventfd for loop exit notification, fixed orb_loop_s undeclared error, and included API for sending loop exit event. We can exit the loop by calling the new API `orb_loop_exit_async()`.
1. Using `UORB_LOOP_MAX_EVENTS` to config loop function
2. Add eventfd to notify loop exit
3. Fix orb_loop_s undeclared error
4. Add API for sending loop exit event
- system/uorb/uORB: Add new API `orb_loop_exit_async()`
```diff
+/****************************************************************************
+ * Name: orb_loop_exit_async
+ *
+ * Description:
+ *   Send exit event to the current loop(not wait).
+ *
+ * Input Parameters:
+ *   loop   orb loop contains multiple handles.
+ *
+ * Returned Value:
+ *   Zero (OK) on success; a -1 (ERROR) …
```
> system/uORB: Add support for exiting loop by writing eventfd

- testing/ostest/signest.c
"kill" sends the signal to any of the the threads in the group. The intention of the test is to send signals only to the "waiter" thread.
I believe this test has been broken since 2023 when the test changed from using tasks to using pthreads. This has gone unnoticed since the test doesn't really fail in single CPU systems (since the threads have different priorities), even if the signals were executed in other thread's context than the "waiter".
In SMP systems, the signest test threads actually run in parallel, so scheduling signal actions to different threads in the same group causes also signal actions to run in parallel (for different signals of course).
Running signal actions in parallel is not compatible behaviour with the signest test, which assumes that signals are being run one …
> testing/ostest/signest: Replace kill with pthread_kill to fix running in SMP

- examples/optee/CMakeLists.txt
- examples/optee/Kconfig
- examples/optee/Make.defs
- examples/optee/Makefile
- examples/optee/optee_main.c
Add an example app that opens a session with the device pseudo-TA and enumerates the available devices (prints their UUIDs only).
The example showcases:
- opening the OP-TEE client driver
- printing its version
- opening a session
- allocating shared memory
- registering shared memory
- invoking a function to the TA referencing the shared memory
- closing the session
Enabled with `CONFIG_EXAMPLES_OPTEE`.
No impact other than showcasing usage of the TEE driver and perhaps enabling quick testing.
Tested on an NXP i.MX93 EVK running:
- TF-A: version v2.10.0, tag `lf-6.6.52_2.2.0`
- OP-TEE OS: revision 4.4 (60beb308810f9561), tag `lf-6.6.52_2.2.0`
- NuttX PR https://github.com/apache/nuttx/pull/16309, with  `CONFIG_DEV_OPTEE_SMC64`
- NuttX configs `imx93-evk:nsh` and `imx93-evk:knsh`
``` …
```
> examples/optee: Introduce an OP-TEE client example

- examples/posix_stdio/CMakeLists.txt
- examples/posix_stdio/Kconfig
- examples/posix_stdio/Make.defs
- examples/posix_stdio/Makefile
- examples/posix_stdio/posix_stdio.c
As new on nuttx and posix style, I missed some simple examples for the classic 'hello world' (note from @cederom see https://github.com/apache/nuttx-apps/tree/master/examples/hello).
To solve it, just create one simple code that can be compiled in both nuttx env and linux. 
For this example we are using the basic nuttx shell feature and no additional documentation should be required.
How does it works?
0 - configure your rtos (for this test I've used: sim:nsh)
1 - run: make menuconfig
2 - enable the example "Hello Nuttx"
3 - save it and exit from menuconfig. 
4 - Then run: make
5 - Next, run: ./nuttx
6 - At NSH, just call the app: `./posix_stdio`.
7 - This will be the output (test logs):
```
nsh> posix_stdio
Hello, NuttX users, welcome!!!
Hello, NuttX users, welcome!!!
Hello, NuttX users, …
```
> examples/posix_stdio: Adding posix stdio example for new joiners.

- testing/ostest/signest.c
This adds checking that the signal is delivered to a correct thread, if sent with pthread_kill. The check is added to signest test, as it fits there with minimal addition.
There is currently an issue in nuttx, that if the signal is masked at the time of dispatch, it is added to the task groups pending queue. From there it is later delivered, but always to any thread in the group (whichever thread happens to remove the pending signal).
This adds functionality to ostest's signest testing case.
Tested that after this patch,  the signest test eventually fails (at least on an SMP system), for the test.
Note: Integrating this will cause failures before the actual issue is resolved in NuttX. I will provide a suggestion for fixing it as well for the NuttX repo.
Maintainers have to decide whether …
> testing/ostest: add checking of signal deliver thread

- interpreters/python/Makefile
* interpreters/python: Do not link to standard libraries
This prevents Python from linking to standard libraries.
This is needed because Python's `configure` script tests for a set of available functions that are provided by NuttX (instead of the toolchain) and not having `-nostdlib` set may give wrong results.
Impact on user: NO.
Impact on build: YES. Prevent Python's from linking toolchain's libraries.
Impact on hardware: NO.
Impact on documentation: NO.
Impact on security: NO.
Impact on compatibility: NO.
This can be tested by checking the `apps/interpreters/python/build/target/config.log` file when building the `esp32s3-devkit:python` defconfig file.
```
make -j distclean && ./tools/configure.sh esp32s3-devkit:python && make -s -j$(nproc)
```
At …
> interpreters/python: Do not link to standard libraries

- system/uorb/sensor/gnss.c
Add timestamp for GNSS measurements and clock, for matching.
When recovering the combination of `GnssMeasurement` and `GnssClock` into [GnssData](https://android.googlesource.com/platform/hardware/libhardware/+/refs/heads/android14-release/include/hardware/gps.h#1748), the reason for splitting is that the uORB buffer is not large enough to accommodate `GnssData`, since different topics cannot guarantee the same timing when publishing and subscribing data, we need an index to match.
**Depends on https://github.com/apache/nuttx/pull/16355**
Developers using the structures `struct sensor_gnss_measurement` and `struct sensor_gnss_clock` need to be aware of the changes to the structure members (a new member of type `uint64_t` has been added at the beginning).
CI
> [BREAKING] uORB/sensor: Add timestamp for GNSS data

- examples/optee/optee_main.c
- examples/optee_gp/CMakeLists.txt
- examples/optee_gp/Kconfig
- examples/optee_gp/Make.defs
- examples/optee_gp/Makefile
- examples/optee_gp/optee_gp_main.c
- tee/.gitignore
- tee/CMakeLists.txt
- tee/Make.defs
- tee/Makefile
- tee/libteec/.gitignore
- tee/libteec/0001-libteec-NuttX.patch
- tee/libteec/CMakeLists.txt
- tee/libteec/Kconfig
- tee/libteec/Make.defs
- tee/libteec/Makefile
> [!NOTE]
> Will keep this a draft until https://github.com/apache/nuttx/pull/16356 is merged, as the current driver is not fully compatible with the GP API. https://github.com/apache/nuttx/pull/16356 also introduces the necessary nxstyle whitelisting for this one to pass the CI checks.
This PR addresses the following:
1. **examples/optee**: Fixes usage of some fields during shared memory registration in the existing OP-TEE example
- Previous version of optee example was using id during shm registration as input whereas it is an output variable. It was also specifying flags to dictate the behaviour whereas the latest implementation of the driver prohibits their use.
2. **tee/libteec**:  Adds the libteec library into NuttX-Apps
- Downloads …
> Add GlobalPlatform API client library (libteec) and example app (optee_gp)

- include/logging/nxscope/nxscope.h
- include/logging/nxscope/nxscope_chan.h
- include/logging/nxscope/nxscope_intf.h
- include/logging/nxscope/nxscope_proto.h
logging/nxscope: allow use in C++ code
nxscope can be used in C++ code
custom project
> logging/nxscope: allow use in C++ code

- wireless/bluetooth/nimble/Kconfig
wireless/bluetooth/nimble/Kconfig: add missing header
cosmetic change
none
> wireless/bluetooth/nimble/Kconfig: add missing header

- examples/optee_gp/Kconfig
Previous Kconfig had a mistake guarding optee_gp Kconfig values based on `EXAMPLES_OPTEE` instead of `EXAMPLES_OPTEE_GP`.
Fixes the case where `CONFIG_EXAMPLES_OPTEE_GP` is enabled without `CONFIG_EXAMPLES_OPTEE`, which is a valid case.
Tested on a NXP i.MX93 EVK running:
- TF-A: version v2.10.0, tag `lf-6.6.52_2.2.0`
- OP-TEE OS: revision 4.4 (60beb308810f9561), tag `lf-6.6.52_2.2.0`
- NuttX config `imx93-evk:koptee` with additional config:
```
CONFIG_EXAMPLES_OPTEE_GP=y
CONFIG_LIBTEEC=y
```
- Logs
```
[...]
OP-TEE: OS revision 4.4 (60beb308810f9561)
NuttShell (NSH)
knsh> optee_gp
INF [6] TEEC:main:159: Available devices:
INF [6] TEEC:main:169:   d96a5b40-c3e5-21e3-8794-1002a5d5c61b
INF [6] TEEC:main:169:   f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c
```
> examples/optee_gp: Fix Kconfig if/else condition

- testing/ostest/wdog.c
This PR added periodic wdog testing and updated the wdog_test to adapt to the semantic changes of the `wd_start`.
This PR only affects the ostest/wdog_test.
Tested on `QEMU/x86_64`, `sim` and `QEMU/riscv32`.
> ostest/wdog: Update wdog_test.

- examples/posix_stdio/Kconfig
When I have submitted the example, somehow, there was an issue on the Kconfig, where the stack size was absent.
Thus, it cause an issue to compile nuttx when 'examples/posix_stdio' was included. Now it was tested properly and it is as expected.
To fix the example, it was needed to add the the following onto Kconfig file:
config EXAMPLES_POSIX_STDIO_STACKSIZE
int "POSIX_STDIO stack size"
default 2048
depends on EXAMPLES_POSIX_STDIO
vinicius@labs:~/embedded_sys/nuttxspace/nuttx$ ./nuttx 
NuttShell (NSH) NuttX-12.9.0
nsh> uname -a
NuttX 12.9.0 de0c697db8 May 25 2025 17:39:28 sim sim
nsh> 
nsh> 
nsh> posix_stdio
Hello, NuttX users, welcome!!!
Hello, NuttX users, welcome!!!
Hello, NuttX users, welcome!!!
Hello, NuttX users, welcome!!!
Hello, NuttX users, welcome!!!
Hello, NuttX users, …
> Fixing Kconfig file, adding the STACKSIZE symbol to example posix_stdio

- system/uorb/CMakeLists.txt
Fix `orb_subscribe_multi` undefined error.
```
/workspace/prebuilts/gcc/linux/arm64/bin/../lib/gcc/aarch64-none-elf/13.2.1/../../../../aarch64-none-elf/bin/ld: apps/system/uorb/libapps_uorb_listener.a(listener.c.o): in function `listener_monitor':
/workspace/apps/system/uorb/listener.c:803:(.text.listener_monitor.constprop.0+0xe4): undefined reference to `orb_subscribe_multi'
/workspace/apps/system/uorb/listener.c:803:(.text.listener_monitor.constprop.0+0xe4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `orb_subscribe_multi'
```
system/uORB
CI
> system/uORB: fix `orb_subscribe_multi` undefined

- boot/nxboot/Kconfig
- boot/nxboot/include/nxboot.h
- boot/nxboot/loader/boot.c
- boot/nxboot/loader/flash.c
- boot/nxboot/nxboot_main.c
This PR has been created after email-list discussions mainly with with @Cynerd and @michallenc
This was driven as a result of the inevitable time that firmware upgrades can take. The progress is reported via syslog, but not all embedded systems use this and, in the case (such as mine) where a user LCD is available, it is beneficial to allow progress to be displayed duringh booting and upgrades - especially should things go wrong.
To achieve this there is a new Kconfig choice - `NXBOOT_PRINTF_PROGRESS` which is disabled by defailt - to allow messages to be printed to stdout.
Since other users may wish to treat NXboot as a library, and perhaps handle the messages differently, the feature is implemented by calls to a specific `nxboot_progress` function using new enums to indicate the type of …
> boot/nxboot: Enhancements to add progress messages and copy-to-RAM

- testing/testsuites/kernel/fs/cases/fs_file_get_test.c
- testing/testsuites/kernel/fs/cmocka_fs_test.c
- testing/testsuites/kernel/fs/include/fstest.h
testing/fs: update api name fs_getfilep/fs_putfilep to file_get/file_put.
DEPENDS ON: https://github.com/apache/nuttx/pull/16499
fix compile break
CI
> testing/fs: update api name fs_getfilep/fs_putfilep to file_get/file_put

- system/fastboot/fastboot.c
Move initialization of usbdev to after "help()".
This patch fix that even users just run `fastbootd -h`, the usbdev will also be (re)initialized, and if the daemon is running the status will be broken.
system/fastboot
CI
> system/fastboot: move usbdev init after help

- .gitignore
- system/syslogd/CMakeLists.txt
- system/syslogd/Kconfig
- system/syslogd/Make.defs
- system/syslogd/Makefile
- system/syslogd/syslogd_main.c
Initial implementation of syslogd including version information, simple usage help and UDP transmission. The current implementation transmits RFC 5424 formatted syslog entries over UDP for consumption by a syslog collector. Only some options from the manpage are implemented since NuttX doesn't currently have the ability for some of the more complex features (-l, etc.).
Users can use this application alongside the new RFC 5424 support (see other PR here: https://github.com/apache/nuttx/pull/16493) to send syslog entries over the network in a format that is understood by various logging servers and network utilities (i.e. WireShark, rsyslog, etc).
Testing was performed by completing a local build on the `sim` and `raspberrpi-pico-w` platforms with all new `syslogd` options enabled. Builds …
> system/syslogd: Initial implementation

- system/fastboot/fastboot.c
Add qualifier "const" to the declaration of `memdump_print_t`, the value of the 2nd argument will not be changed.
- system/fastboot
- CI
> system/fastboot: add const for memdump_print_t

- boot/nxboot/Kconfig
- boot/nxboot/include/nxboot.h
- boot/nxboot/nxboot_main.c
Function `nxboot_progress` is located in `nxboot_main.c`, but this file is not compiled when NXboot is used as a library to an existing application and not as a bootloader. Therefore, the declaration of `nxboot_progress` function should be dependent on `NXBOOT_PROGRESS` config option.
Fixes NXboot compilation if used as a library without `nxboot_main.c` file.
Tested on samv7 custom board. Both bootloader and library now compiles and work as expected.
> boot/nxboot: fix compile errors caused by nxboot_progress

- system/fastboot/Kconfig
- system/fastboot/fastboot.c
Add TCP network transport support for fastboot, users can add "-s tcp:HOST[:PORT]" option to specify a network device.
1. replace GETUINT32 with be32toh
2. add func for context and usbdev
3. add support for fastboot tcp
- system/fastboot
config: qemu-armv8a:netnsh
```
$ fastboot -s tcp:192.168.100.2 getvar version
version: 0.0.0
Finished. Total time: 0.042s
```
- Host side
```
$ fastboot -s tcp:192.168.100.2 flash virtblk0 fastboot.c
Warning: skip copying virtblk0 image avb footer (virtblk0 partition size: 0, virtblk0 image size: 37142).
Sending 'virtblk0' (36 KB)                         OKAY [  0.084s]
Writing 'virtblk0'                                 OKAY [  0.042s]
Finished. Total time: 0.372s
```
- Device side (hexdump block device)
```
NuttShell (NSH)
nsh> uname -a
NuttX  0.0.0  Jun …
```
> system/fastboot: Add support for TCP network device

- .github/workflows/check.yml
- This PR add missing cvt2utf installation on our CI
see apache/nuttx#16561
Impact on user: NO
Impact on build: NO
CI
> check.yml: fix cvt2utf not found sync with nuttx repository

- .asf.yaml
- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SECURITY.md
- .github/linters/setup.cfg
- .github/workflows/check.yml
Many improvement apply only to nuttx repo, this pr bring up all to apps repo.
app's ci workflow is same as nuttx git now.
ci
> sync the change from nuttx/.github folder

- system/fastboot/fastboot.c
Add disconnection for usb transport and remove interest list for epoll.
1. Disconnect usbdev when deinit USB transport.
2. Remove fds from the interest list and close epoll if need.
- system/fastboot
CI
> system/fastboot: release resource & disconnect usbdev if need

- system/settings/settings.c
Fix non-NULL pointer assertion in `get_setting()` caused by uninitialized pointer variables.
system/settings' `get_setting()` function performs non-NULL assertion on non-initialized variables, triggering assertions.
See https://github.com/apache/nuttx-apps/issues/3107 for more details.
Fix a bug causing system/settings to be unusable.
Tested on a private project making use of `system/settings` on NuttX 12.9.0.
> system/settings: fix assertion triggered by uninitialized variables

- system/gcov/gcov.c
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
All output methods are implemented at the kernel level and passed through environment variables.
None
1. ci
2. enable CONFIG_COVERAGE_MINI，the usage is the same as before, but when the path is a file, it will output the data to the file, and then it can be converted through nuttx/tools/gcov.py
> system/gcov: Update gcov functionality

- system/settings/settings.c
* Remove duplicate checks, use switch/case whenever possible
* Remove assertions just before if () condition checking the exact same thing
* Replace if (condition) assert(0) with assert(condition)
No impact on users.
Ran the example "settings" app using sim:nsh NuttX 12.9.0 configuration.
Before:
```
NuttShell (NSH) NuttX-12.9.0
nsh> settings
Example of settings usage to file: /tmp/settings.bin and /tmp/settings.txt:--------------------------------------------------------------
No existing binary storage file found. Creating it.
No existing text storage file found. Creating it.
Retrieved settings value (v1) with value:default value
Trying to (re)create a setting that already exists (v1)
Retrieved setting type is: 4
Trying to change setting (v1) to integer type
Deliberate fail: settings …
```
> system/settings: general code cleaning

- nshlib/nsh_codeccmd.c
- nshlib/nsh_command.c
Sometimes users may want to calculate the MD5 of part of a file(e.g. check
partition contents for debug after flashing, size of which may be greater
than image). This can be done with the "dd" command and pipes, the "md5"
command just needs to support reading from standard input. For example:
`dd if=/dev/virtblk0 bs=512 count=1 | md5`.
- nshlib/md5
1. Selftest: PASS
```diff
11d10
< # CONFIG_SYSTEM_DD_STATS is not set
27d25
< CONFIG_CODECS_HASH_MD5=y
59d56
< CONFIG_NETUTILS_CODECS=y
```
```bash
nsh> md5 -f /etc/init.d/rcS
1f0f871eca6a67fc58f2f33f03ea917fnsh> 
nsh> 
nsh> dd if=/etc/init.d/rcS | md5
sh [10:100]
1f0f871eca6a67fc58f2f33f03ea917fnsh> 
nsh>
nsh> cat /etc/init.d/rcS
fastbootd &
nsh> dd if=/etc/init.d/rcS bs=1 count=8 | md5
sh [12:100]
d7c865c834612f458707597e3be8a0f0nsh> 
nsh> …
```
> nshlib/md5: Support reading from standard input

- netutils/thttpd/Kconfig
- netutils/thttpd/libhttpd.c
When trying to enable and use the thttp net utility, it was found that CGI apps didnt send any http responses of data from the CGI app back to the browser client,
Investigation revealed this was due to the net socket being opened with the  O_CLOEXEC flag set.
This is the result, I believe, of a PR last year [here]( https://github.com/apache/nuttx-apps/pull/2595).
See [this](https://github.com/apache/nuttx-apps/issues/3111) issue.
In correcting the issue, some complier warnings were encountered and fixed, along with a Kconfig error and an omission, and the opportunity was taken to improve some help text within Kconfig.
This is why there are two commits in the PR.
The cgi_child app that is spawned closes all open file descriprors except stdin, stdout, stderr and the socket's descriptor, up …
> netutils/thttpd: fix broken cgi and fixup kconfig

- system/coredump/coredump.c
Companion PR to apache/nuttx#16690, since the same logic is also duplicated in the `coredump` app here.
> system/coredump: Fix missing loglevel to logmask conversion

- .github/workflows/build.yml
fix
ERROR: Dangerous symbolic link path was ignored : sources\nuttx\boards\sim\sim\sim\configs\citest\run : ............\tools\ci\cirun.sh
ERROR: Dangerous symbolic link path was ignored : sources\nuttx\boards\risc-v\qemu-rv\rv-virt\configs\citest\run : ............\tools\ci\cirun.sh
ERROR: Dangerous symbolic link path was ignored : sources\nuttx\boards\risc-v\qemu-rv\rv-virt\configs\citest64\run : ............\tools\ci\cirun.sh
ERROR: Dangerous symbolic link path was ignored : sources\nuttx\boards\arm\imx6\sabre-6quad\configs\citest\run : ............\tools\ci\cirun.sh
https://github.com/apache/nuttx-apps/actions/runs/16226275585/job/45842790929#logs
add Command Line Switch -snld
-snld -> allow extracting of denagerous symbolic links. …
> [CI] build.yml: fix ERROR: Dangerous symbolic link path was ignored on MSVC job

- netutils/nanopb/Makefile
Fix unpack step for MACOS
Enabling and building `nanopb` works when building on MACOS
Tested with local build
> netutils/nanopb: fix unpack step for MACOS

- graphics/libjpeg/Makefile
This PR adds the required JPEG compressor files to the Makefile.
Before this PR, the Makefile contained only the required decompressor files.
Users can now use the JPEG compressor. All the required files are added by default.
Tested on the STM32H7.
A couple photos were decompressed with 1:8 scaling.
Then compressed again with 20% quality.
JPEG hardware was not used.
```
nsh> resize sd/PROC/11c.jpg sd/PROC/test.jpg 8 20
Resized JPEG written to sd/PROC/test.jpg
nsh> resize sd/PROC/11c.jpg sd/PROC/test.jpg 8 20
Resized JPEG written to sd/PROC/test.jpg
nsh> 
```
And as expected, the output looks correct.
> graphics/libjpeg: Add JPEG compressor support to Makefile

- system/gdbstub/Kconfig
Add depends of `LIB_GDBSTUB` for gdbstub.
```
in function `gdbstub_main': undefined reference to `gdb_state_init'
undefined reference to `gdb_process'
undefined reference to `gdb_state_uninit'
```
- apps/system/gdbstub
CI
> system/gdbstub: Add depends of LIB_GDBSTUB

- include/netutils/esp8266.h
- netutils/esp8266/esp8266.c
Fix compile error and nxstyle.
Fix bug to get gateway address.
Fix bug that channel retrieved by lesp_list_access_points is undefined.
netutils/esp8266
Build CONFIG_NETUTILS_ESP8266=y and run it on esp8266 board.
> netutils/esp8266: Fix compile error and some bugs

- tee/optee_supplicant/0001-tee-supplicant-port-to-nuttx.patch
- tee/optee_supplicant/CMakeLists.txt
- tee/optee_supplicant/Kconfig
- tee/optee_supplicant/Make.defs
- tee/optee_supplicant/Makefile
This PR introduces to `nuttx-apps`, the OP-TEE supplicant. Since `LIBTEEC` already downloads a zip file containing the supplicant and the supplicant **requires** `LIBTEEC`, I decided to re-use the downloaded artifact from LIBTEEC and apply the supplicant patch on top of it, in the `apps/tee/optee_supplicant/optee_client` directory.
The build system will expect `CONFIG_OPTEE_SUPPLICANT_VERSION` to match `CONFIG_LIBTEEC_VERSION` otherwise
the build will abort with an error message.
The main reason this application is added, is to provide to OP-TEE secure storage. So an expected (and the currently tested) scenario is to run `optee_supplicant` as a background app in order to allow Trusted Applications (TAs) running in the OP-TEE to have access to secure files. These files are created on the …
> tee/optee_supplicant: Added optee supplicant

- examples/xedge_demo/Kconfig
- examples/xedge_demo/Make.defs
- examples/xedge_demo/Makefile
- examples/xedge_demo/xedge_main.c
- netutils/xedge/.gitignore
- netutils/xedge/Kconfig
- netutils/xedge/Make.defs
- netutils/xedge/Makefile
examples/xedge_demo: Add Xedge IoT Toolkit with BAS integration
Add support for Xedge, an embedded software toolkit for IoT applications
using Lua scripting with HTTP(S), WebSockets, MQTT, and device I/O.
* netutils/xedge: Dependency manager that downloads BAS library
and BAS-Resources, generates XedgeZip.c during build
* examples/xedge_demo: Complete example showing Xedge integration
with HTTP server, Lua runtime, and SNTP time synchronization
I'm supporting @surfskidude to update xedge support with nuttx.
This commit covers conversations: 
https://github.com/apache/nuttx/pull/16352
https://github.com/apache/nuttx-apps/pull/3071
``xedge_demo`` a lightweight Lua-based web framework for building secure, real-time IoT applications
============================================================= …
> examples/xedge: Add Xedge example with BAS integration

- examples/mtdpart/mtdpart_main.c
1. Due to the automatic wrapping of MTD devices during the open() process, the legacy registration methods ftl_initialize() and bchdev_register() are no longer required for MTD device registration. The new method is now changed to register_mtddriver
2. Some code for space release and deregistration has been added, and certain error handling methods have been updated.
Run the `examples/mtdpart` in sim:nsh for test an test is passed
```
nsh> mtdpart
Flash Geometry:
blocksize:      512
erasesize:      4096
neraseblocks:   32
No. partitions: 4
Partition size: 64 Blocks (32768 bytes)
Creating partitions
Partition 1. Block offset=0, size=64
Partition 2. Block offset=64, size=64
Partition 3. Block offset=128, size=64
Partition 4. Block offset=192, size=64
Initializing media:
Checking partitions: …
```
> examples/mtdpart:Register MTD devices using the mtd_register method

- boot/nxboot/loader/boot.c
This patch corrects a mathematical error in the progress reporting function which caused incorrect percentage progress calculations.
This problem was discovered while testing https://github.com/apache/nuttx-apps/pull/3136.
None. Just fixes a problem where the reported % went negative and then misbehaved. Schoolboy maths error!
On my custom SAMA5D27C-D1G board using NXboot and an 800x480 nLCD with NXboot progress display enabled to view the percentage complete of various NXboot flash operations.
> nxboot/loader: Fix boot progress calculation.

- include/netutils/dhcpc.h
- netutils/dhcpc/dhcpc.c
- netutils/dhcpc/dhcpc: add implementation to get renewal (T1) time and rebinding (T2) time from DHCP packet
- According to RFC 2131, T1 and T2 times play a critical role in lease management in DHCP clients.
> 
> T1 Time (Renewal Time)
> Definition: The time at which the client enters the RENEWING state.
> Default Value: 50% of the lease time (0.5 × lease_time).
> 
> T2 Time (Rebinding Time)
> Definition: The time at which the client enters the REBINDING state.
> Default Value: 87.5% of the lease time (0.875 × lease_time).
New Feature/Change: Correctly receive and store T1 and T2 time provided by the server
User Impact: Provide a foundation for the implementation of intelligent renewal mechanism in the future
Build Impact:No new Kconfig options or build system changes.
Hardware Impact: No …
> netutils/dhcpc/dhcpc: add implementation to get renewal (T1) time and rebinding (T2) time from DHCP packet

- include/testing/unity_config.h
- testing/unity/Kconfig
Allows the user to select whether or not they want access to the Unity ``TEST_PRINTF`` commands.
Impacts only the build system by adding one more Kconfig option.
Verified that adding this definition allowed use of the ``TEST_PRINTF`` Unity macro without compilation issues.
> apps/unity: Add printf configuration

- fsutils/libtinycbor/Makefile
- fsutils/libtinycbor/fix_open_memstream.patch
This PR updates TinyCBOR to the latest 0.6.1 tagged release.
N/A
These changes were tested on a Linux host, targeting a custom Cortex-M0+ (RP2040) board using NuttX v12.8.0 as the baseline. They were then manually ported to the current master branch.
> fsutils/libtinycbor: Update TinyCBOR to 0.6.1

- system/dd/dd_main.c
while this is not a goal for this repository,
it's convenient for me (hopefully for some others too) to be able to build this for other platforms.
an obvious downside is to have a few more ifdefs.
tested with:
```
/opt/wasi-sdk-25.0/bin/clang -Wall -Oz -s -o dd.wasm dd_main.c
```
> system/dd: portability to non-nuttx platforms

- boot/nxboot/loader/boot.c
Following steps led to incorrect behavior:
- upload update image
- restart device and perform the update
- upload the same update image again without confirming
This led to the unwanted confirm of the update image. This change ensures the update image is not confirmed by uploading the same image to the update slot. The correct behavior is to perform revert to the last stable image if this occurs.
None on current update process, tested with both standard update and revert, works as before.
ping @TimJTi if you want to verify
Tested on samv7 custom board for standard update and revert processes + double update described above.
> boot/nxboot/loader/boot.c: avoid unwanted confirm on double update

- examples/i2schar/i2schar.h
- examples/i2schar/i2schar_main.c
- examples/i2schar/i2schar_receiver.c
- examples/i2schar/i2schar_transmitter.c
* examples/i2schar: Implement loopback mode check
- Implements the loopback mode for the i2schar example application. This mode - available only when both RX and TX are enabled - allows the user to test the I2S buses when the TX pin is connected to the RX pin. This is done by pre-filling a buffer with known data (additionally, it checks the peripheral's data width to format the data in the buffer accordingly) and passing it for both the transmitter and the receiver threads. This buffer is written to the TX and the received buffer is compared to the known buffer.
Please note that https://github.com/apache/nuttx/pull/16914 should be merged first. Otherwise, the testing application won't be able to fetch the data width (it would use the default value, instead) and the read/write operations …
> examples/i2schar: Implement loopback mode check

- .codespell-ignore-lines
- .codespellrc
- wireless/bluetooth/nimble/CMakeLists.txt
- wireless/bluetooth/nimble/Kconfig
Update NimBLE to the latest master. This includes fixing the debug log control, which was broken since:
https://github.com/apache/mynewt-nimble/commit/da4e2f0f12859079f1bde47cbd69f39026c3cc73
The debug log was always enable and it wasn't possible to disable it.
debug log can be disabled again
nrf52840-dk/sdc_nimble
> bluetooth/nimble: update to the latest master

- system/ntpc/Kconfig
- system/ntpc/ntpcstart_main.c
- system/ntpc/ntpcstop_main.c
This PR updates verbosity on ntpc commands. Also updated documentation on NuttX side.
No impact for user, build or hardware. Only changes some program outputs.
ntpcstart:
```
nsh> ntpcstart
Starting NTP client...
Using NTP servers: 0.pool.ntp.org;1.pool.ntp.org;2.pool.ntp.org
NTP client started successfully (task ID: 10)
NTP client is now running in the background
nsh> date
Fri, Sep 05 18:49:37 2025
```
ntpcstatus:
```
nsh> ntpcstatus
The number of last samples: 5
[0] srv <ip> offset 0.993639955 delay 0.029989675
[1] srv <ip> offset 0.994610567 delay 0.019975724
[2] srv <ip> offset 0.996539219 delay 0.019954988
[3] srv <ip> offset 0.998574000 delay 0.049963876
[4] srv <ip> offset 0.999926716 delay 0.029991036
```
ntpcstop:
```
nsh> ntpcstop
Stopping NTP client...
Stopped the NTP daemon …
```
> system/ntpc: update ntpc messages

- benchmarks/cyclictest/cyclictest.c
This small commit fixes a compile warning (`reqtimeout_timer may be used uninitialized`) and also adds a termination "structure" into the optargs array to work properly with `getopt_long`.
> cyclictest: fix comp. warning (reqtimeout_timer) and optargs termination

- nshlib/nsh_syscmds.c
Fix format string not appropriate warning for cause.flag.
```
nsh_syscmds.c: In function 'cmd_reset_cause':
nsh_syscmds.c:513:24: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint32_t' {aka 'unsigned int'} [-Werror=format=]
513 |       nsh_output(vtbl, "%s(%lu)\n",
|                        ^~~~~~~~~~~
514 |              g_resetcause[cause.cause], cause.flag);
|                                         ~~~~~~~~~~
|                                              |
|                                              uint32_t {aka unsigned int}
```
- nshlib/reset_cause
CI
> nshlib/reset_cause: Fix format warning for flag

- system/cdcacm/CMakeLists.txt
- system/cdcacm/Makefile
- system/cdcacm/cdcacm.h
- system/cdcacm/sercon_main.c
- system/cdcacm/serdis_main.c
- Put sercon and serdis in separate source files, so that the main functions can be compiled in also in kernel build.
- Don't store the ttyacm handle in the application, it is stored in kernel side in case of the system_cdcacm
Only sercon and serdis, but requires https://github.com/apache/nuttx/pull/17010
Tested on IMX9 platform, with CONFIG_BUILD_KERNEL
> system/cdcacm: Support sercon and serdis in CONFIG_BUILD_KERNEL
