builtin/registry/Makefile
Change-Id: Ia61ff63b4b1e4cb6ec52ac216626bbb76fdf3a33
=> Add .updated target to handle the no builtin app case correctly

netutils/ftpd/ftpd.c
1. This fixes the issue reported in Bitbucket apps/ Issue 15.  That is, if fopen() fails, the NULL stream handle would be used in subsequent logic.  The handling of the failure was incomplete.
2. Some of the error handling was also fixed.  In the event of an error, it was returning an error value ONLY if we failed to report the error and even then the wrong error would be reported.  This change now preserves and returns the correct error number that is the root cause of the failure.
3. Ran the file through tools/nxstyle and cleaned up many formatting problems.
=> apps/netutils/ftpd/ftpd.c:  Fixes several problems:

include/wireless/wapi.h, wireless/wapi/src/wapi.c, wireless/wapi/src/wireless.c
Scan print layout:
nsh> wapi scan wlan0
bssid / frequency / signal level / ssid
**:**:**:**:**:**       2437    -38     <ssid>
**:**:**:**:**:**       2427    -36     <ssid>
...
Change-Id: I8201d89e3263262c41e2334e9a772ae6eb177bf6
=> wapi/scan: add frequency/rssi printf

netutils/thttpd/Kconfig, nshlib/nsh_timcmds.c
Change-Id: I409c22eb7f6cf5717d51b2d6fc1a532ae69bb9f0
=> Remove TIME_EXTENDED related stuff since kernel remove this option

testing/cxxtest/Make.defs
=> Append $(APPDIR)/testing/cxxtest to CONFIGURED_APPS

examples/module/drivers/chardev/Makefile, examples/sotest/lib/modprint/Makefile, examples/sotest/lib/sotest/Makefile
Change-Id: I496328d3692ad6a7e556b098ae07298d2d25d151
=> Reference tools/define.sh through DEFINE macro

system/telnet/telnet_client.c
since the host has more powerful intelligent
Change-Id: Ia2d580f9d0b98dc52439fd7b5fe7217b3e17e29f
=> Shouldn't use local readline in telnet

testing/smp/smp_main.c
Change-Id: Ieb52948ad1266f7168a85e3d17b4c79e7957894c
=> testing/smp: Replace up_cpu_index with sched_getcpu

wireless/gs2200m/gs2200m_main.c
- Due to recent refactoring, some applications (such as telnetd) call setsockopt() and caused ASSERT in gs2200m daemon. To avoid this situation, I added setsockopt_request() support in gs2200m_main.c
- This PR affects network applications which uses setsockopt()
- Currently setsockopt() only checks parameters.
- Several network applications such as renew, telnetd, webserver and wget are tested with Spresene + GS2200M.
=> wireless: gs2200m: Add support for setsockopt_request()

examples/README.txt
=> Change CONFIG_CXX_NEWLONG to CONFIG_ARCH_SIZET_LONG

examples/poll/poll_listener.c, nshlib/README.txt
follow the nuttx side change
Change-Id: I9f08a59b349ae1596bbd49d17860abce1ae4ee71
=> Remove CONFIG_DEV_LOWCONSOLE from source code

canutils/Make.defs, examples/Make.defs, fsutils/Make.defs, gpsutils/Make.defs, graphics/Make.defs, graphics/nxwidgets/UnitTests/Make.defs, industry/Make.defs, interpreters/Make.defs, netutils/Make.defs, system/Make.defs, testing/Make.defs, wireless/Make.defs, wireless/bluetooth/Make.defs, wireless/ieee802154/Make.defs
Change-Id: Iaeac72f9f86a9d4eb077abbb31089b0f4075ad34
=> make.defs: complete include path

examples/netlink_route/netlink_route_main.c
Change-Id: Ib3cbe3f2f0064c72e39b7369e67ab7158d1f9890
=> examles/netlink: fix build break

examples/elf/Makefile
To fix "don't know how to create tests/dirlist.h" make complaints.
=> examples/elf: Add a few make rules

import/Make.defs
=> import/Make.defs: Avoid flock errors

include/wireless/wapi.h, netutils/netinit/netinit_associate.c, nshlib/nsh_altconsole.c, nshlib/nsh_consolemain.c, nshlib/nsh_init.c, nshlib/nsh_usbconsole.c, wireless/wapi/Kconfig, wireless/wapi/src/driver_wext.c, wireless/wapi/src/util.c, wireless/wapi/src/wapi.c
Change-Id: I4f7e9a8e4b4f38f08bd0a1ede1994e24f80bf89b
=> netutils: add support to save wapi config to file system

netutils/telnetc/telnetc.c
Change-Id: I34d62c1cc916a7f464e4f16173f50e8f9d41452b
=> Fix some wrong state handler in _negotiate

netutils/telnetc/telnetc.c
=> telnet: Fix compile error by commit 39bf19d

Makefile
Change-Id: I55576aec46bd057bc98cf2b6579d7ac96446ae27
=> Makefile don't change symtab_apps.c timestamp if no any change

Application.mk, examples/elf/Kconfig, examples/elf/tests/Makefile, examples/module/Kconfig, examples/module/drivers/Makefile
Change-Id: I30e43ca436248a7b6230b7e70a259f44c3ede81c
=> Strip the debug information if CONFIG_DEBUG_SYMBOLS isn't enable

.github/actions/ci-container/action.yaml, .github/workflows/main.yml
=> Use new docker image container and add xtensa build support

nshlib/nsh.h, nshlib/nsh_command.c, nshlib/nsh_netcmds.c
Change-Id: Iac7a9a6b871d473e4720db1d6cbfeea3dc9796a0
=> nsh: Call getaddrinfo in cmd_nslookup to support the dual stack host

netutils/ping/icmp_ping.c, netutils/ping/icmpv6_ping.c
Change-Id: I5db830400b5d5806e9d89550acc25766e5e37805
=> ping/ping6: Support the dual stack host correctly

.github/workflows/build.yml
Testlist update in apache/incubator-nuttx-testing#26
=> CI: update matrix boards accordingly since testlist updated

.github/workflows/build.yml
This is a sync from testing repo.
=> CI: Add macOS builds

wireless/gs2200m/gs2200m_main.c
Please see https://github.com/apache/incubator-nuttx/pull/782 for details.
=> wireless: gs2200m: Add support for UDP connect in gs2200m_main.c

.github/workflows/check.yml
=> CI: refine checkpatch commits in check.yml

.github/workflows/build.yml
Signed-off-by: Brennan Ashton <bashton@brennanashton.com>
=> Add retry to pull docker image

nshlib/Kconfig
Change-Id: I98bd022fdc901ecb4e2e45a0faf779d83c260844
=> nshlib: remove the dependency of date on RTC

examples/nettest/.gitignore
=> example/nettest: tcpclient and tcpserver to .gitignore

.github/workflows/build.yml
since arm-12 finish more quickly than arm-11
=> build.yaml: Change arm-11 to arm-12

examples/i2schar/i2schar.h, examples/i2schar/i2schar_main.c, examples/i2schar/i2schar_receiver.c, examples/i2schar/i2schar_transmitter.c, examples/i2sloop/i2sloop_main.c, graphics/nxwidgets/src/cwidgetcontrol.cxx, include/graphics/nxwm/cstartwindow.hxx, include/system/nxplayer.h, include/system/nxrecorder.h, system/nxplayer/nxplayer.c, system/nxplayer/nxplayer_main.c, system/nxrecorder/nxrecorder.c, system/nxrecorder/nxrecorder_main.c
dependent on https://github.com/apache/incubator-nuttx/pull/836
=> various nxstyle fixes linked with the nuttx/audio PR

DISCLAIMER-WIP, README.txt
* Update the disclaimer to note that some ASF files don't have correct ASF header
=> Update the disclaimer to note that some ASF files don't have correct…ASF header (#203)

.github/workflows/build.yml
This is the port of https://github.com/apache/incubator-nuttx/pull/850 that never made it in
=> CI: Add logic for determining which branches of OS App and Testing

examples/unionfs/Makefile
=> examples/unionfs: clean up the residual files after 'make distclean'

examples/adxl372_test/adxl372_test_main.c, examples/lsm330spi_test/lsm330spi_test_main.c
=> examples: Remove all '#undef __KERNEL__' from source code

examples/flash_test/Kconfig, examples/i2schar/Kconfig, examples/mtdpart/Kconfig, examples/mtdrwb/Kconfig, system/composite/Kconfig, system/usbmsc/Kconfig
=> Kconfig: Change !BUILD_PROTECTED && !BUILD_KERNEL to BUILD_FLAT

wireless/gs2200m/gs2200m_main.c
- During testing https://github.com/apache/incubator-nuttx/pull/917, I found a bug in gs2200m daemon that a server socket is not released in close(). For example, kill tcpserver and then restarting tcpserver fails due to the internal cid is not released.
- This PR introduces BOUND state in gs2200m_main.c to release in close_request().
- Also, I did refactoring in close_request() so that it can handle both TCP/UDP socket in same logic.
- This PR affects gs2200m daemon only. However it affects all sockets. (i.e. TCP and UDP, client and server).
- I checked UDP server and client as well as TCP server and client.
=> wireless: gs2200m: Fix to release a bound socket

examples/elf/tests/errno/Makefile, examples/elf/tests/hello/Makefile, examples/elf/tests/helloxx/Makefile, examples/elf/tests/longjmp/Makefile, examples/elf/tests/mutex/Makefile, examples/elf/tests/pthread/Makefile, examples/elf/tests/signal/Makefile, examples/elf/tests/struct/Makefile, examples/elf/tests/task/Makefile, examples/module/drivers/chardev/Makefile, examples/sotest/lib/modprint/Makefile, examples/sotest/lib/sotest/Makefile
follow up the kernel side change
=> examples: Replace all -luc with -lc

builtin/exec_builtin.c, fsutils/mkfatfs/mkfatfs.c, fsutils/mksmartfs/mksmartfs.c, netutils/ftpc/ftpc_connect.c, netutils/ftpc/ftpc_login.c, netutils/tftpc/tftpc_get.c, netutils/tftpc/tftpc_put.c, nshlib/nsh_fileapps.c, platform/mikroe-stm32f4/mikroe_configdata.c
=> Fix nxstyle issue

examples/hdc1008_demo/Kconfig, examples/hdc1008_demo/Make.defs, examples/hdc1008_demo/Makefile, examples/hdc1008_demo/hdc1008_main.c
New version of the hdc1008 pull request with the not-so-messed-up history.
=> Example application for the hdc1008 driver.

graphics/littlevgl/Kconfig, graphics/littlevgl/lv_conf.h
=> graphics/littlevgl: Add missing configs

examples/README.txt, examples/dhcpd/Kconfig, examples/dhcpd/Makefile, examples/dhcpd/dhcpd_daemon.c, examples/dhcpd/dhcpd_daemon.h, examples/dhcpd/dhcpd_start.c, examples/dhcpd/dhcpd_stop.c, examples/dhcpd/target.c, include/netutils/dhcpd.h, netutils/dhcpd/Kconfig, netutils/dhcpd/dhcpd.c
netutils/dhcpd: cancelable dhcp daemon
=> netutils/dhcpd: cancelable dhcp daemon

wireless/gs2200m/gs2200m_main.c
- This PR contains add support for getsockname() to gs2200m daemon
- Please see https://github.com/apache/incubator-nuttx/pull/1046 as well
- This PR affects gs2200m daemon only. More specifically when getsockname() is called.
- Please see https://github.com/apache/incubator-nuttx/pull/1046 
- NOTE: we need to enable ftpc manually in defconfig for testing.
=> wireless: gs2200m: Add support for getsockname() to gs2200m

examples/cromfs/Makefile, examples/elf/tests/Makefile, examples/flowc/Makefile, examples/module/drivers/Makefile, examples/nettest/Makefile, examples/tcpblaster/Makefile, examples/udp/Makefile, examples/usbserial/Makefile.host, system/zmodem/Makefile.host
=> build: host executable should use HOSTEXEEXT not EXEEXT

wireless/gs2200m/gs2200m_main.c
- This PR updates help messages in gs2200m_main.c
- This PR only affects gs2200m_main.c 
- See https://github.com/apache/incubator-nuttx/pull/1101
=> wireless: gs2200m: Update help messages in gs2200m_main.c

netutils/webclient/webclient.c
webclient.c: Limit the number of redirections
=> webclient.c: Limit the number of redirections

include/netutils/netlib.h
- Avoid giving a wrong impression to users
- Save a little memory
=> netlib: #if 0 out unimplemented fields in url_s

netutils/netlib/netlib_parsehttpurl.c, netutils/netlib/netlib_parseurl.c
=> netlib_parseurl: Fix pathlen check

examples/bridge/Makefile, examples/flowc/Makefile, examples/nettest/Makefile, examples/tcpblaster/Makefile, examples/udp/Makefile, examples/udpblaster/Makefile
Change-Id: Iabedaa5da6439f4bfc34fb861382276446b4224f
=> examples: Fix the wrong dependence about config.h

system/zmodem/Makefile.host, system/zmodem/zm.h, system/zmodem/zm_proto.c
Change-Id: If6b324c20fcb245633f3bdc9000bc48f581c7dc6
=> zmodem: Fix the build break and warning for host binary

system/nxplayer/nxplayer.c
- This PR removes redundant code regarding audio buffer configuration in nxplayer.c
- In previous implementation, there were many #ifdef CONFIG_AUDIO_DRIVER_SPECIFIC_BUFFERS which resulted in complicated code.
- This PR simplifies nxplayer.c which ** always ** calls ioctl() to the nuttx audio driver to obtain buffer configurations and stores the information to buf_info. If ioctl() failed which means that underlying audio driver does not support 'audio driver specific buffers', then use default values such as CONFIG_AUDIO_BUFFER_NUMBYTES and CONFIG_AUDIO_NUM_BUFFERS
- This PR affects nxplayer
- I tested this PR with both spresense which has CONFIG_AUDIO_DRIVER_SPECIFIC_BUFFERS=y and lc823450-xgevk which ** does not ** have CONFIG_AUDIO_DRIVER_SPECIFIC_BUFFERS=y
=> system: nxplayer: Refactor nxplayer.c

examples/buttons/Kconfig, examples/leds/Kconfig
=> Fix the wrong dependence for userled and button

examples/nxflat/Makefile, examples/nxflat/tests/Makefile, examples/nxflat/tests/mkdirlist.sh
Update nxflat Makefile etc to pass parallel build
Build with eagle100:nxflat config
=> examples/nxflat: update Makefile etc to fix build break

netutils/webclient/webclient.c
webclient: Fix errno in case of recv failure
webclient
i tested a different version of this code by injecting a failure
=> webclient: Fix errno in case of recv failure

system/nxrecorder/nxrecorder.c
- This PR removes redundant code regarding audio buffer configuration in nxrecorder.c
- The approach is the same as https://github.com/apache/incubator-nuttx-apps/pull/285
- This PR affects nxrecorder.c only
- I tested this PR with spresense:wifi where CONFIG_AUDIO_DRIVER_SPECIFIC_BUFFERS=y
- To test CONFIG_AUDIO_DRIVER_SPECIFIC_BUFFERS=n case, I had to modify the followings
```
--- a/drivers/audio/Kconfig
+++ b/drivers/audio/Kconfig
@@ -31,7 +31,6 @@ config AUDIO_CXD56
bool "CXD56 audio driver"
default n
depends on AUDIO
- select AUDIO_DRIVER_SPECIFIC_BUFFERS
---help---
Enable support for audio playback using the CXD5247 chip on the
CXD56 Spresense board.
--- a/boards/arm/cxd56xx/spresense/configs/wifi/defconfig
+++ b/boards/arm/cxd56xx/spresense/configs/wifi/defconfig
@@ -16,15 +16,15 …
```
=> system: nxrecorder: Refactor nxrecorder.c

examples/camera/Kconfig, examples/camera/Make.defs, examples/camera/Makefile, examples/camera/README.txt, examples/camera/camera_fileutil.c, examples/camera/camera_fileutil.h, examples/camera/camera_main.c
The camera example will take the specified number of pictures (default 10)
then will exit
To enable the example add the following line in your defconfig
EXAMPLES_CAMERA
examples for camera
Spresense board
=> Examples: camera: add a simple camera snapshot example

examples/gpio/gpio_main.c
NuttX PR: https://github.com/apache/incubator-nuttx/pull/1374
=> gpio: add new GPIO pin types

.github/workflows/build.yml
The checks are failing because the change is only in testing/. This updates apps/.
=> Update boards matrix to add AVR builds.

wireless/gs2200m/gs2200m_main.c
Fix minor bug.
Tested by spresense:wifi.
=> wireless/gs2200m: Fix freeing uninitialized memory

interpreters/duktape/.gitignore, interpreters/duktape/Kconfig, interpreters/duktape/Make.defs, interpreters/duktape/Makefile, interpreters/duktape/duk_cmdline.patch
Add initial support for duktape js interpreter
None
REPL and string eval tested on stm32f746g-disco.
=> [WIP]interpreters: Add initial duktape support

examples/fb/fb_main.c, examples/lvgldemo/fbdev.c, graphics/pdcurs34/nuttx/pdcdisp.c
Work with https://github.com/apache/incubator-nuttx/pull/1458
=> Change FBIO_UPDATE argument from nxgl_rect_s to fb_area_s

examples/lvgldemo/Makefile, fsutils/inih/Makefile, graphics/lvgl/Makefile, netutils/cjson/.gitignore, netutils/cjson/Makefile, system/embedlog/Makefile, system/psmq/Makefile, testing/unity/.gitignore, testing/unity/Makefile
=> Remove the unnecessary touch and delete from Makefile

netutils/ftpc/ftpc_connect.c, netutils/ftpc/ftpc_getreply.c, netutils/ftpc/ftpc_internal.h
follow up the kernel side change: https://github.com/apache/incubator-nuttx/pull/1545
=> netutils/ftpc: Embed wdog_s in ftpc_session_s directly

system/cu/cu_main.c
option -c will disable \n -> \r\n conversion both for serial device and console if it is a tty
refactor: use only one function to set termios parameters, use termious related code and options only if CONFIG_SERIAL_TERMIOS is defined
This options is handy (and very vital) to interact with serial devices with binary protocol together with option '-f' (endless mode without escape sequence) introduced in df5d4cd033167c775fd69692446a146fe3453a0f.
due to ifdef construction nxstyle complains
`cu_main.c:246:44: error: Unmatched right parentheses`
should I (and how) eliminate this?
I've built and tested this as cherry pick to 8.2 and only with CONFIG_SERIAL_TERMIOS defined. Haven't built it without this.
=> system/cu: refactor, add option -c to disable \n -> \r\n conversion

netutils/ftpc/ftpc_connect.c, netutils/ftpc/ftpc_getreply.c, netutils/ftpc/ftpc_internal.h, netutils/ftpc/ftpc_transfer.c
follow up the kernel side change: https://github.com/apache/incubator-nuttx/pull/1565
=> netutils/ftpc: Change watchdog callback prototype

include/netutils/icmp_ping.h, include/netutils/icmpv6_ping.h, include/system/nxrecorder.h, netutils/ping/icmp_ping.c, netutils/ping/icmpv6_ping.c, netutils/usrsock_rpmsg/Make.defs, netutils/usrsock_rpmsg/Makefile, netutils/usrsock_rpmsg/usrsock_rpmsg.h, netutils/usrsock_rpmsg/usrsock_rpmsg_client.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c, system/nxplayer/nxplayer_main.c, system/nxrecorder/Makefile, system/nxrecorder/nxrecorder.c, system/nxrecorder/nxrecorder_main.c
Xiaomi already sign SGA, so there isn't block issue to change the license.
=> Change all files come from Xiaomi/Pinecone to Apache License 2.0 

Application.mk
See title
None
Tested on stm32
=> build: Support both .s & .S

Makefile
Companion change to one in NuttX repo
Build system
Build locally
=> export APPDIR using 'export' keyword (TOPDIR already exported by nuttx/)

Application.mk
Fix multi MAINSRC match suffix in single Makefile 
We can compile multi program in single makefile with different suffix file in MAINSRC.
eg: MAINSRC = xxx1.c
PROGNAME = xxx1
MAINSRC += xxx2.cpp
RROGNAME += xxx2
Built locally
=> Fix multi MAINSRC match suffix in single Makefile

examples/wgetjson/Kconfig, examples/wgetjson/wgetjson_main.c, include/netutils/webclient.h, netutils/webclient/webclient.c
tested with:
CONFIG_EXAMPLES_WGETJSON_URL="http://httpbin.org/get"
CONFIG_EXAMPLES_WGETPOST_URL="http://httpbin.org/post"
wgetjson -D
wgetjson -P -D
wgetjson -p -D
=> wgetjson fixes

.github/workflows/build.yml
Add Renesas precheck for RX65N-GRROSE and RX65N-RSK2MB
=> Add renesas precheck

examples/wget/wget_main.c, examples/wgetjson/wgetjson_main.c, include/netutils/webclient.h, netutils/webclient/webclient.c, nshlib/nsh_netcmds.c
Highlights:
* TLS support (a hook to allow users to provide TLS implementation)
* ability to add extra request headers
* ability to use PUT method
* ability to report http status
* error handling improvements
Proposed on the ML while ago:
https://www.mail-archive.com/dev@nuttx.apache.org/msg03803.html
The original API is kept for now.
I plan to remove them after adapting the existing users.
(examples in this repo)
tested with my local app
=> webclient improvements

fsutils/ipcfg/ipcfg.h, fsutils/ipcfg/ipcfg_binary.c
This adds a version for the binary file structure. 
Should be none as this is not used yet.
inspection.
=> ipcfg:Version the binary structure

wireless/gs2200m/gs2200m_main.c
- During Wi-Fi stress test, I noticed ASSERT happens in gs2200m_main.c
- Actually, req->max_buflen was 0 but the case was not handled correctly
- Affects read/recvfrom with len=0 cases
- Run nxplayer for audio streaming
- Run ps/free/ifconfig commands via telnet
- Run smp command via telnet
=> wireless: gs2200m: Fix recvfrom_reques() in gs2200m_main.c

fsutils/ipcfg/ipcfg_binary.c, netutils/netinit/netinit.c
Fixes https://github.com/apache/incubator-nuttx-apps/issues/426
Fix compiler warning in ipcfg_binary.c
Fix typo in net init.
will not link
built with px4_fmu-v5x
=> ipcfg & net init fixes

system/sched_note/note_main.c, system/trace/trace.c, system/trace/trace_dump.c
App code support for https://github.com/apache/incubator-nuttx/pull/2044
See https://github.com/apache/incubator-nuttx/pull/2044
See https://github.com/apache/incubator-nuttx/pull/2044
=> Add note_syscall args support

system/sched_note/Kconfig
follow up the kernel side change
No, just Kconfig change.
=> system/sched_note: Change DRIVER_NOTE to DRIVER_NOTERAM

system/sched_note/note_main.c, system/trace/trace_dump.c
App code support for https://github.com/apache/incubator-nuttx/pull/2043
"note" and "trace" commands support the new feature.
See https://github.com/apache/incubator-nuttx/pull/2043
See https://github.com/apache/incubator-nuttx/pull/2043
=> Add SCHED_INSTRUMENTATION_HIRES support

examples/fxos8700cq_test/fxos8700cq_main.c
Change-Id: I96821efd5f3ed78da5a51b39972596774f5645cf
Bug: https://github.com/apache/incubator-nuttx/pull/199
=> fxos8700cq: Remove unused var

testing/sensortest/Kconfig, testing/sensortest/Make.defs, testing/sensortest/Makefile, testing/sensortest/sensortest.c
This testing for sensor driver is so simple, it use ioctl to control sensor and get some event to verify driver is OK.
It and [https://github.com/apache/incubator-nuttx/pull/2039](url) are closely linked.
We can use tool to find issue about sensor driver.
daily test.
=> testing/sensortest: add sensor driver test

examples/watchdog/watchdog_main.c
This PR allows user to pass the wdt's devname as a parameter for the example.
Now the user can run the example with multiple instances of wdt, it will not be necessary to build NuttX again to change the devname parameter.
It always tested by selecting different wdts.
=> Examples/WDT: Added argument to select devname

examples/hello/Make.defs, examples/hello/Makefile, examples/hello/hello_main.c
Change headers from `hello` app to Apache, as Greg is sole author.
Header change
N/A
=> hello: update to Apache license

system/trace/trace_dump.c
App code support for https://github.com/apache/incubator-nuttx/pull/2142
See https://github.com/apache/incubator-nuttx/pull/2142
See https://github.com/apache/incubator-nuttx/pull/2142
=> Add task name record for task trace

nshlib/nsh_routecmds.c, nshlib/nsh_syscmds.c, nshlib/nsh_telnetlogin.c, nshlib/nsh_test.c, nshlib/nsh_vars.c
Fix coding style issues for the files in nshlib directory.
No impact on functionality. Changed code in compliance with NuttX coding style.
Does NOT add/modify any functionality. Should build & run normally.
P.S. The only exception that remains in this directory is the false +ve nsh_timcmds.c.
=> Fixing coding style issues for rest of nshlib directory

system/adb/Kconfig, system/adb/Make.defs, system/adb/Makefile, system/adb/adb_banner.c, system/adb/adb_main.c, system/adb/logcat_service.c, system/adb/shell_pipe.c, system/adb/shell_pipe.h, system/adb/shell_service.c, system/libuv/0001-initial-libuv-port-to-nuttx.patch, system/libuv/libuv/Kconfig, system/libuv/libuv/Makefile, system/libuv/tests/Makefile
add Android Debug Bridge daemon for NuttX.
https://developer.android.com/studio/command-line/adb
None. Disabled by default.
Validated on "sim" board (TCP) and stm32 (both TCP and USB).
There are still some issues that will be address soon:
* Authentication check disabled due to missing RSA crypto lib in NuttX
* Some instabilities and memory leak using "adb shell"
* adb forward/reverse (socket) disabled for now as it needs a refactoring
defconfig for test purposes can be found at https://github.com/spiriou/incubator-nuttx/commits/adb_examples
=> Android Debug Bridge daemon

netutils/webserver/httpd.c
=> netutils/webserver: fix build error

nshlib/nsh_dbgcmds.c, system/ramtest/ramtest.c, testing/ostest/signest.c
fix some printf errors found by the compiler.
https://github.com/apache/incubator-nuttx/pull/2222
=> Fix printf format warnings

include/wireless/wapi.h, wireless/wapi/src/wapi.c, wireless/wapi/src/wireless.c
wapi/wireless: add get sensitivity support 
N/A
API test
=> wapi/wireless: add get sensitivity support 

examples/esp32_himem/Kconfig, examples/esp32_himem/Make.defs, examples/esp32_himem/Makefile, examples/esp32_himem/esp32_himem_main.c
Add ESP32 High Memory Application Example
User will be able to test high memory
esp32-core
=> Add ESP32 High Memory Application Example

examples/fboverlay/fboverlay_main.c, examples/media/media_main.c, examples/romfs/romfs_main.c
see https://github.com/apache/incubator-nuttx/pull/2222
now i visited all errors in apps found by local testlist/all.dat testbuild on macos.
=> fix printf format wanings

testing/sensortest/sensortest.c
See https://github.com/apache/incubator-nuttx/pull/2222
=> testing/sensortest/sensortest.c: Fix a printf format warning

netutils/netcat/Kconfig, netutils/netcat/Make.defs, netutils/netcat/Makefile, netutils/netcat/README.md, netutils/netcat/netcat_main.c
Check readme for usage and demo:
[![weboftwins-osvehicle-2020-rzr](
https://files.mastodon.social/media_attachments/files/105/163/916/892/863/178/original/05468e28b4463f95.png
)](
https://mastodon.social/@rzr/105225153152922220#weboftwins-osvehicle-2020-rzr
"weboftwins-osvehicle-2020-rzr")
Change-Id: I2eac915954ca6cf585f01addb53df581631a7ae6
Bug: https://github.com/apache/incubator-nuttx/pull/1999
Relate-to: https://github.com/rzr/aframe-smart-home/issues/3
Forwarded: https://github.com/apache/incubator-nuttx/pulls/rzr
=> netutils/netcat: Add netcat tool

examples/fxos8700cq_test/fxos8700cq_main.c
Change-Id: Iab80381e4f451ac186515cd5593434d80e4c7421
Relate-to: https://github.com/rzr/aframe-smart-home/issues/3
=> fxos8700cq_test: Adjust rate and lint json output

canutils/candump/candump.c
=> canutils/candump/candump.c: Fix scanf format warnings

system/readline/readline.h
Fix compile break when disable CONFIG_READLINE_ECHO
Fix compile break
daily test
=> Fix compile break

testing/sensortest/sensortest.c
Fix test failed when some apis are NULL.
Fix bug for some special driver.
daily test
=> Fix test failed when some apis are NULL

fsutils/mkfatfs/configfat.c, fsutils/mkfatfs/mkfatfs.c, fsutils/mkfatfs/writefat.c
see https://github.com/apache/incubator-nuttx/pull/2347
=> Fix syslog formats

fsutils/mkfatfs/mkfatfs.c
see https://github.com/apache/incubator-nuttx/pull/2347
=> fsutils/mkfatfs/mkfatfs.c: Fix a syslog format

netutils/dhcpc/dhcpc.c, netutils/netlib/netlib_ipmsfilter.c
=> Syslog format and nxstyle fixes

system/cle/cle.c
=> system/cle/cle.c: Fix syslog formats

canutils/candump/candump.c
=> canutils/candump/candump.c: Fix printf formats

graphics/nxwidgets/src/cimage.cxx, graphics/nxwm/src/ccalibration.cxx, graphics/nxwm/src/ctouchscreen.cxx
=> Syslog format fixes

examples/chrono/chrono_main.c
And rename Rename button_daemon to chrono_daemon
=> examples/chrono: Fix error: 'CONFIG_EXAMPLES_SLCD_DEVNAME' undeclared 

graphics/twm4nx/apps/ccalibration.cxx
=> graphics/twm4nx/apps/ccalibration.cxx: Fix syslog formats

fsutils/mkfatfs/configfat.c, netutils/chat/chat.c
=> syslog and nxstyle fixes

examples/touchscreen/tc_main.c
=> examples/touchscreen/tc_main.c: Fix a syslog format

wireless/wapi/src/util.c, wireless/wapi/src/wapi.c
wapi/conf: convert mac address 
wapi save_config/reconnect
wapi wlan0 save_config
wapi wlan0 reconnect
=> wapi/conf: convert mac address 

examples/serialrx/send.py, tools/bitmap_converter.py
=> Remove unneeded semicolons and parentheses from Python files

testing/ltp/Kconfig, testing/ltp/Make.defs, testing/ltp/Makefile
Add LTP support
test on local environment
=> Add LTP support

testing/ltp/Makefile
Signed-off-by: nietingting <nietingting@xiaomi.com>
ltp: fix build fail issue
No 
test on local
=> ltp: fix build fail issue

wireless/wapi/src/wapi.c
wireless/wapi: Fix the usage message
confirmed the output locally
=> wireless/wapi: Fix the usage message

testing/irtest/cmd.cpp
testing/irtest: Remove an unused function
build-tested
=> testing/irtest: Remove an unused function

include/system/nxlooper.h, system/nxlooper/Kconfig, system/nxlooper/Make.defs, system/nxlooper/Makefile, system/nxlooper/nxlooper.c, system/nxlooper/nxlooper_main.c
which record and play raw data using audio subsystem
to verify audio record and playback function
Signed-off-by: danguanghua <danguanghua@xiaomi.com>
Change-Id: I2c768b8e8234a31f9622cb9955f785329cf402a5
Signed-off-by: danguanghua <danguanghua@xiaomi.com>
=> system: nxlooper: add nxlooper for loopback test

include/system/nxlooper.h, include/system/nxplayer.h, include/system/nxrecorder.h
include/system/nx: include mqueue.h explicitly
include/system/nx
=> include/system/nx: include mqueue.h explicitly

testing/sensortest/sensortest.c
fix bug about getopt and custom type in sensortest
normal use
daily test
=> testing/sensortest: fix bug because getopt

graphics/lvgl/Kconfig, graphics/lvgl/Makefile, graphics/lvgl/lv_fs_interface.c, graphics/lvgl/lv_fs_interface.h
lvgl: Add file system interface.
let lvgl access file system.
daily test
=> lvgl: Add file system interface.

system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c, system/nxrecorder/nxrecorder.c
system/nx: update mqueue_open return value
=> system/nx: update mqueue_open return value

testing/ostest/mqueue.c, testing/ostest/timedmqueue.c
testing/ostest: update mqueue testing code
As the mqd_t change to int
=> testing/ostest: update mqueue testing code

examples/README.md, netutils/tftpc/tftpc_packets.c, netutils/tftpc/tftpc_put.c
Some typos in examples/README.md and netutils TFTP client code, nxtyle changes
No functional change
=> Netutils typos

testing/getprime/Kconfig, testing/getprime/getprime_main.c
- This commit introduces configurable thread priority
- Also, thread policy is set based on RR_INTERVAL
- getprime only
=> testing: getprime: Introduce configurable thread priority

system/netdb/netdb_main.c
netdb: Fix usage and comment
tested on esp32-devkitc
=> netdb: Fix usage and comment

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
usrsock: delete sock->s_crefs to fix compile break, this patch associated with #2899
daily test
=> usrsock: delete sock->s_crefs to fix compile break

nshlib/nsh_codeccmd.c
apps/md5: fix md5 result error
=> apps/md5: fix md5 result error

examples/rpmsgsocket/Kconfig, examples/rpmsgsocket/Make.defs, examples/rpmsgsocket/Makefile, examples/rpmsgsocket/rpsock_client.c, examples/rpmsgsocket/rpsock_server.c
rpmsgsocket: add rpmsgsocket test case
=> rpmsgsocket: add rpmsgsocket test case

netutils/iperf/README.md
netutils/iperf/README.md: document what this is
=> netutils/iperf/README.md: document what this is

interpreters/quickjs/qjsmini.c
Fix typo in qjsmini.c
None
SIM
=> interpreters/quickjs: Fix typo in qjsmini.c

testing/ostest/sporadic2.c
Results were difficult to interpret because the counts during the high priority, budget interval were included with other counts during the low priority interval.  This corrects that reporting by using two counts:  One for the low and one for the high priority interval.  This makes the results much easier to interpret.
There should be no impact to anything other that the sporadic scheduler case of the OS test.
Tested using the the stm32f4discovery:sporadic configration.  That configuration has no yet been merged but is available from incubator-apps PR 3097.
=> OS test: Improve reporting from the dual thread sporadic test

nshlib/nsh_builtin.c
nsh/builtin: Ignore the child status if run the application on background.
N/A
fix the leak of child status if the background process
exceeds "CONFIG_PREALLOC_CHILDSTATUS".
N/A
nsh command stress test
=> nsh/builtin: Ignore the child status if run the application on background.

system/nxplayer/nxplayer.c
https://github.com/apache/incubator-nuttx/pull/3212 depends on this PR.
Should not,  change the debug code
Pass CI.
=> system/nxplayer: Fix error: 'outstanding' undeclared

testing/fstest/fstest_main.c
Add hash checking of file's name to avoid creating same-name file.
=> testing/fstest: Add hash checking of file's name to avoid creating same-name file

netutils/mqttc/Kconfig, netutils/mqttc/Make.defs
and remove the temp change since NuttX specific change has been upstreamed:
https://github.com/LiamBindle/MQTT-C/pull/131
Switch to new version
=> neutils/mqttc: Update to version 1.1.5

.github/workflows/cancel.yml
Companion change to the one on main nuttx repo.
CI
CI
=> CI: cancel redundant workflows

.github/workflows/build.yml
Adapt to changes in https://github.com/apache/incubator-nuttx-testing/pull/92
CI
CI
=> CI: add to testlist changes

nshlib/Kconfig
- Fix https://github.com/apache/incubator-nuttx/issues/3011
=> nshlib: Disable mb, mh, and mw by default

testing/ostest/getopt.c
Add logic to assure that the getopt() functions parse exactly the correct number of parameters.  Previously if the test terminated early, the error would be undetected.  Also, prevents indexing past the end of the results array.
Fixes a coding error that was not causing a test failure.
Add some minimal level of testing for invalid options (this found a good bug in getopt_long()).
Affects only the getopt() test cases of the OS test.
Verified using an NSH simulator configuration set up to add apps/testing/ostest as a built-in command.
=> OS Test:  Minor improvement to the getopt() test

examples/modbus/modbus_main.c, examples/modbusmaster/mbmaster_main.c, include/modbus/mbport.h
modbus: Fix compilation issue and advice users about termios
Improve modbus compilation
Tested modbus slave communicating with computer
Note: Please ignore Coding Style errors, FreeModBus uses CamelCase
=> modbus: Fix compilation issue and advice users about termios

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
to improve the performance
internal soc
=> netutils/rpmsg: Prepare poll fds only when error with EINTR

wireless/wapi/src/wapi.c
=> [BACKPORT #682]wireless/wapi/src/wapi.c: When executing a command return its error code

testing/ostest/barrier.c, testing/ostest/mutex.c, testing/ostest/ostest_main.c, testing/ostest/timedmutex.c
Report "ERROR" the same way for all the test cases.  This also helps to script around the output to find out issues.
N/A
esp32-devkitc:ostest
esp32c3-devkit:ostest
=> testing/ostest: Report "ERROR" the same way for all the test cases.

testing/unity/Kconfig, testing/unity/Makefile
Bump the default version to the latest one.
N/A
N/A
=> testing/unity: Select the latest version.

netutils/wakeonlan/Kconfig, netutils/wakeonlan/Make.defs, netutils/wakeonlan/Makefile, netutils/wakeonlan/wol_main.c
Add wake on lan util, see [wol(1) - Linux man page](https://linux.die.net/man/1/wol)
=> netutils: add Wake-on-LAN util

netutils/wakeonlan/Kconfig
Minor style change.
No
Pass CI
=> netutils/wakeonlan: Remove the tab from the blank line in Kconfig

examples/elf/elf_main.c
Regress by PR https://github.com/apache/incubator-nuttx-apps/pull/709
Minor, warning only fix
Pass CI
=> examples/elf: Fix error: unused variable 'desc' [-Werror=unused-variable]

examples/module/module_main.c
Fix build break report here:
https://github.com/apache/incubator-nuttx/pull/3706/checks?check_run_id=2573929542
Minor
Pass CI
=> examples/module: Fix error: unused variable 'desc'

graphics/nxwidgets/src/cscaledbitmap.cxx, graphics/nxwidgets/src/cwidgetcontrol.cxx
=> include debug.h for xerr/xinfo/xwarn caller

examples/rpmsgsocket/rpsock_server.c, fsutils/passwd/passwd_find.c, netutils/dhcpd/dhcpd.c, netutils/ftpc/ftpc_getfile.c, netutils/ftpc/ftpc_listdir.c, netutils/ftpc/ftpc_putfile.c, netutils/ftpc/ftpc_socket.c, netutils/netlib/netlib_ipv4adaptor.c, netutils/netlib/netlib_ipv6adaptor.c, netutils/ntpclient/ntpclient.c, netutils/telnetd/telnetd_daemon.c, nshlib/nsh_fsutils.c, nshlib/nsh_netcmds.c, nshlib/nsh_session.c, system/taskset/taskset.c, testing/getprime/getprime_main.c
=> Include assert.h for DEBUGASSERT caller

examples/alarm/alarm_main.c
This small PR:
- Fixes a typo (we already have bugs to deal with, no demon is necessary). Just a joke.
- Fixes coding style issues in the alarm example.
Alarm example users.
No functional impact.
N/A.
=> examples/alarm: fix typo and coding style issues

examples/foc/foc_device.c, examples/foc/foc_fixed16_thr.c, examples/foc/foc_float_thr.c, examples/foc/foc_main.c, interpreters/bas/bas_statement.c, interpreters/bas/bas_vt100.c, system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c, system/nxrecorder/nxrecorder.c
Minor
Please ignore the follow warning:
```
../nuttx/tools/checkpatch.sh -g 98de0d6a686ce3f417895175743e00e0d5e1436f..HEAD
Error: /home/runner/work/incubator-nuttx-apps/incubator-nuttx-apps/apps/interpreters/bas/bas_statement.c:85:7: error: Mixed case identifier found
```
=> Include assert.h in necessary place

builtin/exec_builtin.c, system/popen/popen.c, system/system/system.c
Depend on https://github.com/apache/incubator-nuttx/pull/3698
Minor
Pass CI
=> system/popen: Follow up task_spawn change from kernel

examples/leds/leds_main.c
Based on PR #742 for having a kill \<pid\> that will send SIGTERM default signal to the task,
this example of a "daemon leds" will handle SIGTERM in order to gracefully terminate itself.
It allows to restart this daemon after correctly terminating it. No need to reset the board to reestablish a good state.
Tested in flat mode with CONFIG_SIG_DEFAULT=y as well as undefined.
=> add SIGTERM handling in leds example

fsutils/ipcfg/ipcfg.c, fsutils/ipcfg/ipcfg_binary.c, fsutils/ipcfg/ipcfg_text.c, nshlib/nsh_vars.c
Fix Breakage from https://github.com/apache/incubator-nuttx/pull/3738
master broken
CI / buid localy
=> Fix Breakage from https://github.com/apache/incubator-nuttx/pull/3738

LICENSE, interpreters/bas/bas.c, interpreters/bas/bas.h, interpreters/bas/bas_auto.c, interpreters/bas/bas_auto.h, interpreters/bas/bas_autotypes.h, interpreters/bas/bas_error.h, interpreters/bas/bas_fs.c, interpreters/bas/bas_fs.h, interpreters/bas/bas_global.c, interpreters/bas/bas_global.h, interpreters/bas/bas_main.c, interpreters/bas/bas_program.c, interpreters/bas/bas_program.h, interpreters/bas/bas_programtypes.h, interpreters/bas/bas_statement.c, interpreters/bas/bas_statement.h, interpreters/bas/bas_str.c, interpreters/bas/bas_str.h, interpreters/bas/bas_token.h, interpreters/bas/bas_value.c, interpreters/bas/bas_value.h, interpreters/bas/bas_var.c, interpreters/bas/bas_var.h, interpreters/bas/bas_vt100.c, interpreters/bas/bas_vt100.h
revert the license to the original state and add it to LICENSE file
LICENSE
NONE
=> interpreters: bas: license update

LICENSE, canutils/canlib/canlib_getbaud.c, canutils/canlib/canlib_getloopback.c, canutils/canlib/canlib_getsilent.c, canutils/canlib/canlib_setbaud.c, canutils/canlib/canlib_setloopback.c, canutils/canlib/canlib_setsilent.c, wireless/bluetooth/btsak/btsak.h, wireless/bluetooth/btsak/btsak_advertise.c, wireless/bluetooth/btsak/btsak_features.c, wireless/bluetooth/btsak/btsak_gatt.c, wireless/bluetooth/btsak/btsak_info.c, wireless/bluetooth/btsak/btsak_main.c, wireless/bluetooth/btsak/btsak_scan.c, wireless/bluetooth/btsak/btsak_security.c, wireless/ieee802154/libutils/ieee802154_addrtostr.c
update licenses to Apache
Gregory Nutt is has submitted the SGA
Sebastien Lorquet has submitted the ICLA
as a result we can migrate the licenses to Apache.
LICENSE
NONE
=> canutils: canlib: update licenses to Apache 

wireless/ieee802154/libmac/ieee802154_assocreq.c, wireless/ieee802154/libmac/ieee802154_assocresp.c, wireless/ieee802154/libmac/ieee802154_disassocreq.c, wireless/ieee802154/libmac/ieee802154_getreq.c, wireless/ieee802154/libmac/ieee802154_gtsreq.c, wireless/ieee802154/libmac/ieee802154_orphanresp.c, wireless/ieee802154/libmac/ieee802154_pollreq.c, wireless/ieee802154/libmac/ieee802154_resetreq.c, wireless/ieee802154/libmac/ieee802154_rxenabreq.c, wireless/ieee802154/libmac/ieee802154_scanreq.c, wireless/ieee802154/libmac/ieee802154_setreq.c, wireless/ieee802154/libmac/ieee802154_startreq.c, wireless/ieee802154/libmac/ieee802154_syncreq.c, wireless/ieee802154/libmac/sixlowpan_assocreq.c, wireless/ieee802154/libmac/sixlowpan_assocresp.c, wireless/ieee802154/libmac/sixlowpan_disassocreq.c, wireless/ieee802154/libmac/sixlowpan_getpromisc.c, wireless/ieee802154/libmac/sixlowpan_getreq.c, wireless/ieee802154/libmac/sixlowpan_gtsreq.c, wireless/ieee802154/libmac/sixlowpan_orphanresp.c, wireless/ieee802154/libmac/sixlowpan_pollreq.c, wireless/ieee802154/libmac/sixlowpan_resetreq.c, wireless/ieee802154/libmac/sixlowpan_rxenabreq.c, wireless/ieee802154/libmac/sixlowpan_scanreq.c, wireless/ieee802154/libmac/sixlowpan_setreq.c, wireless/ieee802154/libmac/sixlowpan_startreq.c, wireless/ieee802154/libmac/sixlowpan_syncreq.c
Gregory Nutt is has submitted the SGA as a result we can migrate the licenses to Apache.
LICENSE
NONE
=> wireless: ieee802154: libmac: update licenses to Apache

netutils/iperf/Kconfig, netutils/iperf/iperf.c, netutils/iperf/iperf_main.c
* accept -t 0, meaning forever
* Make -t0 the default for server mode
* improve report precision
tested with tcp, both rx and tx.
=> iperf improvements

builtin/exec_builtin.c, examples/posix_spawn/spawn_main.c, nshlib/nsh_fileapps.c, system/popen/popen.c, system/system/system.c
pair with the kernel side change(https://github.com/apache/incubator-nuttx/pull/3916) to follow the standard defintion:
https://pubs.opengroup.org/onlinepubs/009695399/functions/posix_spawn.html
More confirm to the standard
=> Call posix_spawn with filename as the first argv entry

testing/fatutf8/fatutf8_main.c, testing/fstest/fstest_main.c, testing/nxffs/nxffs_main.c
=> testing: Exit with non zero value in the failure path

examples/elf/elf_main.c, examples/nxflat/nxflat_main.c, examples/posix_spawn/spawn_main.c
Report here: https://github.com/apache/incubator-nuttx/pull/3928
Fix the non-standard usage.
=> example/posix_spawn: Ensure argv has filename and NULL terminator

system/argtable3/Makefile
cf. https://github.com/argtable/argtable3/commit/7704006f3cbb556e11da80a5b97469075a32892e
tested on sim on macos.
=> argtable3: Workaroud a clang warning

testing/sensortest/sensortest.c
sensortest: add '\n' for gps output debug log
testing/sensor: fix bug about -h
sensortest error handling
=> Minor fix for sensortest

system/critmon/Makefile, system/critmon/critmon.c
=> system/critmon: add critmon program for critmon once

include/netutils/icmp_ping.h, include/netutils/icmpv6_ping.h, system/ping/ping.c, system/ping6/ping6.c
Return EXIT_FAILURE in the error case
=> system/ping[6]: correct the ping return value

netutils/dhcpc/dhcpc.c
- check for minimum packet length (44 bytes, which includes the fields we
read next)
- pass the correct remaining buffer length to dhcpc_parseoptions()
- dhcpc_parseoptions(): ensure we never read past the end of the buffer
I was not able to provoke a crash with the existing code.
=> dhcpc: fix potential invalid memory reads

examples/watchdog/Kconfig
=> examples/watchdog: add depends on CONFIG_WATCHDOG

system/critmon/critmon.c
system/critmon: add thread run time support
This depneds on 
https://github.com/apache/incubator-nuttx/pull/4030/commits/0dd7e7e1bcbd1ce22e33eda122f909525c51aaa9
=> system/critmon: add thread run time support

nshlib/nsh.h
nshlib: support c++ access nsh api
Change-Id: I90de4a4ce1f089a2db2e3b81f83f7b39434d6421
=> nshlib: support c++ access nsh api

examples/pipe/Kconfig, examples/pipe/pipe.h
pipe: modify default stack size to fix stack overflow
Change-Id: I16910ff216db6b915d7c1cc4084c0b79228769a5
=> pipe: modify default stack size to fix stack overflow

testing/sensortest/sensortest.c
=> fix(sensortest): move set_interval and batch before activate.

fsutils/mkfatfs/mkfatfs.c
required by: https://github.com/apache/incubator-nuttx/pull/4193
Minor change.
=> Fix the printf warning after blkcnt_t change

examples/README.md, examples/cordic/Kconfig, examples/cordic/Make.defs, examples/cordic/Makefile, examples/cordic/cordic_main.c
examples: add CORDIC example
depends on https://github.com/apache/incubator-nuttx/pull/4244
Tested on nucleo-g431rb
=> examples: add CORDIC example

testing/fstest/README.md, testing/fstest/fstest_main.c
Signed-off-by: anjianjun <anjianjun@xiaomi.com>
Test with parameter so we can test different directory and times without rebuild the img.
=> testing/fstest:Support test fs with parameter

system/trace/trace_dump.c
The Trace Compass cannot display the task control flow graph correctly in the following cases:
- The code running in the interrupt handler requests a context switch.
- The task terminates.
This patch fixes the issues.
Only when CONFIG_SYSTEM_TRACE = y
After this patch, the Trace Compass displays a correct control flow graph.
=> system/trace: Fix trace output for the correct display in Trace Compass

examples/media/media_main.c
Found by https://github.com/apache/incubator-nuttx/pull/4193
Minor warning fix.
=> examples/media: Fix the compiler wanring after off_t type change

system/dumpstack/Kconfig, system/dumpstack/Make.defs, system/dumpstack/Makefile, system/dumpstack/dumpstack.c
system/dumpstack: add dump stack tool support 
add support for printing the arbitrary thread stack in runtime to monitor the thread status
( only support cortex-m / cortex-a(thumb) )
libs/libc: move the backtrace implement to sched
arch/cortex-m: add arch backtrace support 
sched/backtrace: add sched_backtrace support 
Depends on:
https://github.com/apache/incubator-nuttx/pull/4259
N/A, new feature
Running tasks:
```
ap> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED    CPU COMMAND
0     0   0 FIFO     Kthread N-- Ready              00000000 003052 001044  34.2%   94.4% Idle Task
1     1 253 RR       Kthread --- Waiting  Semaphore 00000000 003044 000344  11.3%    0.0% hpwork 0x2011dc34
2     2 253 RR       Kthread --- Waiting  Semaphore 00000000 …
```
=> system/dumpstack: add dump stack tool support 

netutils/thttpd/cgi-src/ssi.c, netutils/thttpd/libhttpd.c, system/trace/trace.c
follow the kernel side change: https://github.com/apache/incubator-nuttx/pull/4268
=> Change match to fnmatch

examples/userfs/userfs_main.c
Follow up the change: https://github.com/apache/incubator-nuttx/pull/4307
Can't pass CI until https://github.com/apache/incubator-nuttx/pull/4307 merge
=> examples/userfs: Implement the dummy callback of fchstat and chstat

netutils/webclient/webclient.c
webclient: check content-length
While it's better to use a reliable transport like
TLS with working close notify, it isn't always possible.
webclient
the non-error cases are tested with my app on sim.
the error case is not tested well.
=> webclient: check content-length

examples/hall/Kconfig, examples/hall/Make.defs, examples/hall/Makefile, examples/hall/hall.h, examples/hall/hall_main.c
Add Hall effect sensor example
nucleo-f446re
=> examples: add Hall effect sensor example

include/netutils/netlib.h
netutils: add NETLIB_SOCK_TYPE for AF_RPMSG
daily test
=> netutils: add NETLIB_SOCK_TYPE for AF_RPMSG

netutils/webclient/webclient.c
webclient: handle EINTR in a few places
with my local app on linux
=> webclient: handle EINTR in a few places

examples/camera/Kconfig
until the camera patches are merged we must add the
EXAMPLES_CAMERA_OUTPUT_LCD option to Kconfig
BUILD
Compiled
=> examples: camera: add EXAMPLES_CAMERA_OUTPUT_LCD

examples/charger/charger_main.c
See the discussion here https://github.com/apache/incubator-nuttx/pull/4626
Same as before
=> examples/charger: Update enum type usage per kernel change

include/industry/foc/fixed16/foc_align.h, include/industry/foc/fixed16/foc_ident.h, include/industry/foc/fixed16/foc_routine.h, include/industry/foc/float/foc_align.h, include/industry/foc/float/foc_ident.h, include/industry/foc/float/foc_routine.h, industry/foc/Kconfig, industry/foc/Makefile, industry/foc/fixed16/foc_align.c, industry/foc/fixed16/foc_ident.c, industry/foc/fixed16/foc_routine.c, industry/foc/float/foc_align.c, industry/foc/float/foc_ident.c, industry/foc/float/foc_routine.c
- industry/foc: add general FOC routine handler
- industry/foc: add sensor alignment routine (zero offset + direction)
- industry/foc: add motor identification routine (phase resistance + phase inductance)
New functionality.
Tested with modified example/foc app.
=> industry/foc: add support for motor identification and sensor alignment

examples/foc/Kconfig, examples/foc/foc_cfg.h, examples/foc/foc_fixed16_thr.c, examples/foc/foc_float_thr.c, examples/foc/foc_main.c, examples/foc/foc_parseargs.c, examples/foc/foc_parseargs.h, examples/foc/foc_thr.h
examples/foc: add option to disable open-loop operations
Initial step towards sensored control
None
CI
=> examples/foc: add option to disable open-loop operations

examples/foc/foc_motor_b16.c, examples/foc/foc_motor_f32.c, include/industry/foc/fixed16/foc_routine.h, include/industry/foc/float/foc_routine.h, industry/foc/Kconfig, industry/foc/fixed16/foc_align.c, industry/foc/float/foc_align.c
- industry/foc/foc_align: add support for sensor index search
- examples/foc: add support for sensor index search
b-g431b-esc1
=> examples/foc: add support for sensor index search

examples/foc/Kconfig
FOC Kconfig menuconfig info part corrected
=> FOC Kconfig corrected

nshlib/nsh_session.c
Make the command sh command line handling more robust
run sh with script
=> nshlib/nsh_session: Handle the command arguments in any order

system/sched_note/Makefile, system/sched_note/note_main.c
Few cosmetics and typo fixes for sched_note app
N/A
N/A
=> Few cosmetics and typo fixes for sched_note app

testing/sensortest/sensortest.c
Signed-off-by: buyuer <dingddding@163.com>
=> sensortest: support new gps struct and more sensor type.

examples/helloxx/helloxx_main.cxx, testing/cxxtest/cxxtest_main.cxx
No
Pass CI and run without error
=> examples/helloxx: add extern "C" to main implementation directly

testing/fstest/fstest_main.c
=> Improve testing/fstest

include/netutils/dhcpc.h, netutils/dhcpc/dhcpc.c
netutils/dhcpc: add non-blocking interface
Signed-off-by: songlinzhang <songlinzhang@xiaomi.com>
Add dhcpc_request_async function
Replace dhcpc_request
=> netutils/dhcpc: add non-blocking interface

examples/touchscreen/tc_main.c
added timestamp printing in tc
Signed-off-by: futerigele <futerigele@xiaomi.com>
=> examples/touchscreen: added timestamp printing in tc

examples/thttpd/content/tasks/tasks.c
since it move to task_info_s now, see here: https://github.com/apache/incubator-nuttx/pull/4913
thttpd example
Pass CI.
=> examples/thttpd: Don't touch task_tcb_s::argv field

examples/foc/Kconfig, examples/foc/foc_cfg.h, examples/foc/foc_intf.c
examples/foc: add a simple character based interface to interact with the app
b-g431b-esc1/foc_f32
=> examples/foc: add a simple character based interface

examples/gpio/gpio_main.c
Extension to the existing GPIO example to allow changing pintypes. This assumes that the lower half GPIO driver implements the setpintype command.
This is an extension and should not break the old functionality of the application. All old commands should still work.
I used this extended GPIO example application to test https://github.com/apache/incubator-nuttx/pull/4774 on a S32K144EVB board.
=> GPIO example: Add support for changing pintypes

boot/mcuboot/Kconfig
Extend configuration options for MCUboot
MCUboot based applications
PreCI pass
=> boot/mcuboot/Kconfig: extend configuration options

examples/hdc1008_demo/hdc1008_main.c
Same as https://github.com/apache/incubator-nuttx/commit/34c7bec0dc644ba3bab9f0ffa91de9dafd44b37d but on the example app.
Modulo operation used to calculate digits after decimal point, but if that result is <10, a leading zero wasn't added, giving a wrong value.
Tested on real hardware (custom board).
Thanks!
=> examples/hdc1008_demo: fix formatting after decimal point

examples/noteprintf/Kconfig, examples/noteprintf/Make.defs, examples/noteprintf/Makefile, examples/noteprintf/noteprintf_main.c
sched note: printf API example
test API:
void sched_note_string(FAR const char *buf);
void sched_note_dump(uint32_t module, uint8_t event,
FAR const void *buf, size_t len);
void sched_note_printf(FAR const char *fmt, ...) printflike(1, 2);
void sched_note_bprintf(uint32_t module, uint8_t event,
FAR const char *fmt, ...) printflike(3, 4);
https://github.com/apache/incubator-nuttx/pull/4963
suggestion: add "&" after the command when running this example.
example outout:
```
NuttShell (NSH) NuttX-10.1.0
ap> noteprintf &
noteprintf [18:100]
ap> trace start
ap> trace dump
noteprintf-18  [0]  23.768000000: dump_string: shced note test
noteprintf-18  [0]  23.768000000: dump_binary: module=main event=1 count=2 0x1 0x2
noteprintf-18  [0]  23.768000000: dump_binary: module=main event=2 count=1 0x1 …
```
=> sched note: printf API example

examples/sht3x/Kconfig, examples/sht3x/Make.defs, examples/sht3x/Makefile, examples/sht3x/sht3x_main.c
Add simple application to test SHT3x sensor
Users will be able to test the sensor
```
nsh> sht3x
Converting...
Temperature = 27.104218
Humidity    = 61.417564
Converting...
Temperature = 27.104218
Humidity    = 61.429771
Converting...
Temperature = 27.074844
Humidity    = 61.412987
Converting...
Temperature = 27.061493
Humidity    = 61.452660
```
=> apps/sht3x: Add simple application to test SHT3x sensor

examples/isl29023/Kconfig, examples/isl29023/Make.defs, examples/isl29023/Makefile, examples/isl29023/isl29023_main.c
Add example app for isl29023 driver
Created from the hdc1008_demo example.
Only this simple app added
Tested on real hardware (custom board)
Thanks!
=> Add example app for isl29023 driver

graphics/nxwidgets/UnitTests/README.md
graphics/nxwidgets: Change CONFIG_USER_ENTRYPOINT to CONFIG_INIT_ENTRYPOINT
Related to: [#5065](https://github.com/apache/incubator-nuttx/pull/5065)
N/A DOC change
=> graphics/nxwidgets: Change CONFIG_USER_ENTRYPOINT to CONFIG_INIT_ENTRYPOINT

canutils/libobd2/obd_decodepid.c
Fix a few issues on the debug prints, and also some nxstyle issues
No impact
Compile-tested only
=> canutils: fix a few debug prints

netutils/ntpclient/ntpclient.c
ntpc: optimize stack used, this pr is related to https://github.com/apache/incubator-nuttx/pull/5159.
reduce stack used
local compile
=> ntpc: optimize stack used

wireless/gs2200m/gs2200m_main.c
wireless/gs2200m: replace the preamble scratch to union 
fix the preamble scratch buffer issue
N/A, I do not have the wifi module....
=> wireless/gs2200m: replace the preamble scratch to union 

netutils/dhcpc/dhcpc.c
netutils/dhcpc: Fix dhcpc lease bug
Signed-off-by: songlinzhang songlinzhang@xiaomi.com
dhcpc lease management
call dhcpc_request_async
=> netutils/dhcpc: Fix dhcpc lease bug

examples/nxterm/nxterm_internal.h, examples/nxtext/nxtext_internal.h, examples/usrsocktest/defines.h, netutils/thttpd/thttpd_strings.h, wireless/ieee802154/i8sak/i8sak_events.h
Fix the warning found in: https://github.com/apache/incubator-nuttx-apps/pull/966
Minor
Pass CI
=> Fix the nxstyle warning

netutils/netcat/netcat_main.c
sendfile related code refactoring + small fixes.
Build NuttX:
```
$ ./tools/configure.sh -l sim:tcpblaster
$ make menuconfig
(enable / disable CONFIG_NETUTILS_NETCAT_SENDFILE,
enable CONFIG_SCHED_ATEXIT,
enable CRYPTO_LIBTOMCRYPT,
enable LIBTOMCRYPT_DEMOS,
enable CONFIG_LIBTOMCRYPT_HASHSUM,
enable CONFIG_DEV_URANDOM)
$ make
```
Enable TUN/TAP on Linux host:
```
$ sudo setcap cap_net_admin+ep ./nuttx
$ sudo ./tools/simhostroute.sh wlan0 on
```
Run netcat server on Linux host:
`$ netcat -l -p 31337 | md5sum`
Run NuttX on Linux host:
```
$ ./nuttx
NuttShell (NSH) NuttX-10.2.0
nsh> ifconfig eth0 10.0.1.2
nsh> ifup eth0
ifup eth0...OK
nsh> dd if=/dev/urandom of=/tmp/test.bin count=1000
nsh> hashsum -a md5 /tmp/test.bin
761821531e22d6d9e910a0d023b82708 */tmp/test.bin
nsh> netcat …
```
=> netutils/netcat: sendfile related code refactoring + small fixes

system/input/Kconfig, system/input/Make.defs, system/input/Makefile, system/input/input.c
Add system / input command line tool
You can write data to the virtual device created by uinput on the command line
=> system/input: add system input cmd tool

testing/sensortest/sensortest.c
Modify sensortest for new sensor types PPGD and PPGQ instead old type PPG.
It is coupled with PR: https://github.com/apache/incubator-nuttx/pull/5356
Signed-off-by: liucheng5 <liucheng5@xiaomi.com>
sensortest.c depends on sensor.h. So this PR is coupled with https://github.com/apache/incubator-nuttx/pull/5356
On arm-based EVB
=> fix: sensor: modify sensortest for PPG

boot/mcuboot/mcuboot_agent_main.c, nshlib/nsh_syscmds.c, system/adb/Kconfig, system/adb/adb_main.c
Could reboot to the different state by:
adb reboot bootloader
adb reboot recovery
Pass CI
=> system/adb: Support reset to bootloader and recovery mode

examples/tcpecho/Kconfig
examples/tcpecho: fix typo
N/A
CI check
=> examples/tcpecho: fix typo

netutils/netlib/netlib_autoconfig.c, netutils/netlib/netlib_getdripv4addr.c, netutils/netlib/netlib_getessid.c, netutils/netlib/netlib_getifstatus.c, netutils/netlib/netlib_getipv4addr.c, netutils/netlib/netlib_getipv4netmask.c, netutils/netlib/netlib_getipv6addr.c, netutils/netlib/netlib_getmacaddr.c, netutils/netlib/netlib_setdripv4addr.c, netutils/netlib/netlib_setdripv6addr.c, netutils/netlib/netlib_setessid.c, netutils/netlib/netlib_setifstatus.c, netutils/netlib/netlib_setipv4addr.c, netutils/netlib/netlib_setipv4netmask.c, netutils/netlib/netlib_setipv6addr.c, netutils/netlib/netlib_setipv6netmask.c, netutils/netlib/netlib_setmacaddr.c
Replace strncpy with strlcpy
No
Pass CI
=> Fix error: 'strncpy' specified bound 16 equals destination size

examples/buttons/buttons_main.c
Strange code detected during code review. Remove unnecessary code.
None. Seems to be dead code
Pass CI
=> examples/buttons: fix strange code in buttons_main

include/industry/foc/float/foc_velocity.h, industry/foc/Kconfig, industry/foc/Makefile, industry/foc/float/foc_vel_odiv.c, industry/foc/float/foc_vel_opll.c
industry/foc/float: add velocity observers support
=> industry/foc/float: add velocity observers support

examples/hello_rust/Kconfig, examples/hello_rust/Make.defs, examples/hello_rust/Makefile, examples/hello_rust/hello_rust_main.rs
Hello, Rust!!
nothing as it's new
Simulation on MacBook Air M1 with Monterey 12.2.1 using rustc rustc 1.58.1 (stable) via Homebrew.
=> apps: hello_rust example program

graphics/nxwidgets/UnitTests/README.md
follow up nuttx chagne: https://github.com/apache/incubator-nuttx/pull/5559
Minor
Pass CI
=> graphics/nxwidgets: Rename ARCHCPUFLAGS[XX] to ARCHC[XX]FLAGS

Application.mk, Make.defs, Makefile, import/Make.defs
Pair with https://github.com/apache/incubator-nuttx/pull/5557
Code refactor
Pass CI
=> Replace cygpath with CONVERT_PATH

system/trace/trace.c
usage:
trace switch switch [+|-]
Configure switch trace filter
trace print [+|-]
Configure dump trace filter
Signed-off-by: zhanghu6 <zhanghu6@xiaomi.com>
=> apps/trace: add switch and dump instrumentation

examples/oneshot/Kconfig
Modify oneshot example to let users see it working
Users will see oneshot example waiting for
ESP32-Devkitc
=> apps: Modify oneshot example to let users see it working

testing/ostest/Makefile, testing/ostest/ostest.h, testing/ostest/ostest_main.c, testing/ostest/setjmp.c
Test setjmp/longjmp in ostest.
ostest
sabre-6quad:nsh and rv-virt:nsh
=> ostest: Introduce basic setjmp/longjmp test

nshlib/Kconfig
=> Simplify DEFAULT_SMALL usage in Kconfig

.gitignore
=> Ignore .context (follow NuttX main repo)

system/libuv/0001-libuv-port-for-nuttx.patch, system/libuv/Makefile
Use posix_spawn based process implementation instead of fork
libuv
sim:adb
=> system/libuv: Switch process.c to process_spawn.c

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
since it's more simpler than psock_ioctl
Code refactor only
Pass CI.
=> netutils/usrsock_rpmsg: Switch the nonblocking mode by psock_ioctl instead

netutils/netlib/netlib_getdevs.c, netutils/netlib/netlib_getnodeaddr.c, netutils/netlib/netlib_getpanid.c, netutils/netlib/netlib_getproperties.c, netutils/netlib/netlib_ipv6adaptor.c, netutils/netlib/netlib_seteaddr.c, netutils/netlib/netlib_setnodeaddr.c
Report here: https://github.com/apache/incubator-nuttx/runs/5424034399?check_suite_focus=true
Fix compiler warning
Pass CI
=> netutils/netlib: Fix error: 'strncpy' specified bound 16 equals destination size

graphics/nxwidgets/src/cprogressbar.cxx, netutils/webserver/httpd_dirlist.c, system/nxplayer/nxplayer.c, system/termcurses/tcurses_vt100.c
Report here: https://github.com/apache/incubator-nuttx/pull/5476
Minor
Pass CI
=> Fix warning found without -fno-builtin

system/hexed/src/hexmove.c
Report here: https://github.com/apache/incubator-nuttx/runs/5458719278?check_suite_focus=true
Minor
Pass CI
=> system/hexed: fix error: 'memset' used with length equal to number of elements without multiplication by element size

system/input/input.c
In the command line, you can write data to the uinput device through the input tool
=> system/input: add input tool button support

testing/uclibcxx_test/Kconfig, testing/uclibcxx_test/Make.defs, testing/uclibcxx_test/Makefile
=> uclibcxx_test: add uclibcxx_test Kconfig

examples/rpmsgsocket/rpsock_client.c, examples/rpmsgsocket/rpsock_server.c
Fix rpmsg example's bug
N/A
N/A
=> examples/rpmsgsocket: Fix rpmsg example's bug

system/adb/Kconfig, system/adb/Makefile
and enable the port forwarding feature: https://github.com/spiriou/microADB/pull/27
=> system/adb: Update to microADB to the latest version

testing/fatutf8/fatutf8_main.c
Signed-off-by: fanzhuyun <fanzhuyun@xiaomi.com>
testing/fstest: add cleanup to fatutf8
add cleanup to fatutf8
local test
=> testing/fstest: add cleanup to fatutf8

graphics/nxwidgets/UnitTests/README.md
Correct configuration option name in README.md
None
Pass CI
=> graphics/nxwidgets/UnitTests: correct configuration option name in README.md

include/netutils/dhcp6c.h, netutils/dhcp6c/Kconfig, netutils/dhcp6c/Make.defs, netutils/dhcp6c/Makefile, netutils/dhcp6c/dhcp6c.c
Add dhcp6c module for nuttx
Improve IPv6 function
dhcp6c test passed
=> Add dhcp6c module

system/ping/ping.c, system/ping6/ping6.c
since the mdev is calculated through function provided by fixedmath.h
Shouldn't
Pass CI
=> system/ping: Don't include nuttx/lib/math.h

system/cfgdata/cfgdata_main.c
Implement `"format"` option for `cfgdata` tool.
None. New option added
Pass CI
=> system/cfgdata: implement "format" option

wireless/wapi/src/driver_wext.c, wireless/wapi/src/network.c, wireless/wapi/src/wireless.c
Continue the work https://github.com/apache/incubator-nuttx/pull/5476:
Minor
Pass CI
=> wireless/wapi: Fix warning: 'strncpy' specified bound 16 equals destination size

netutils/rexecd/rexecd.c, testing/scanftest/scanftest_main.c
fix compile warning about rexec and scanftest
N/A
local test
=> apps: fix compile warning

examples/watchdog/watchdog_main.c
Fix watchdog command parameter error
no effect.
pass
=> examples/watchdog: Fix watchdog command parameter error

system/trace/trace.c
VELAPLATFO-2058
Change-Id: I4cfa400c90d9421dfb565de3536b8378a28ae3fb
Signed-off-by: zhuyanlin <zhuyanlin1@xiaomi.com>
=> trace: fix pointer cross the border

testing/cxxtest/cxxtest_main.cxx
This PR intends to extend the scope of `cxxtest` by including some features from C++17 standard.
Only if `LIBCXX` is selected and if `-std=c++17` compiler flag is provided, otherwise no impact is expected.
- `esp32-devkitc:cxx`
- `esp32s2-saola-1:cxx`
- `esp32c3-devkit:cxx`
- `esp32s3-devkit:cxx`
=> testing: Extend cxxtest with some C++17 features

nshlib/nsh.h, nshlib/nsh_envcmds.c, nshlib/nsh_fscmds.c, nshlib/nsh_fsutils.c
nshlib: merge nsh_getdirpath() to nsh_fsutils.c
nshlib
VELA
=> nshlib: merge nsh_getdirpath() to nsh_fsutils.c

system/nxlooper/nxlooper.c
nxlooper: support different period size of player & recorder
nxlooper
VELA
=> nxlooper: support different period size of player & recorder

include/nshlib/nshlib.h, nshlib/nsh_system.c, system/nsh/sh_main.c
nsh: sh_main also support isctty = true
sh
VELA
=> nsh: sh_main also support isctty = true

system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c
nxlooper, nxplayer:   fix warning
nxlooper, nxplayer
vela
=> Fix nxplayer/nxrecoder/nxlooper warning

nshlib/nsh_command.c, nshlib/nsh_syscmds.c
rptun cmd update
add rptun reset/panic/ping/dump support
This depends on:
https://github.com/apache/incubator-nuttx/pull/5847
rptun cmds
VELA
=> rptun cmd update

examples/usrsocktest/usrsocktest_daemon.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c, wireless/gs2200m/gs2200m_main.c
This PR mainly contains some USRSOCK related changes
This submission depends on the nuttx's submission！
=> This PR mainly contains some USRSOCK related changes

examples/mqttc/mqttc_pub.c, netutils/ftpd/ftpd.c, netutils/ftpd/ftpd.h, netutils/pppd/ppp.c, system/uniqueid/uniqueid_main.c
Unify `FAR` attribute usage across apps
Should be none
Pass CI
=> apps: unify FAR attribute usage across apps

examples/poll/poll_listener.c
fs/epoll: fix compile break about change type of pollevent_t
N/A
CI
=> fs/epoll: fix compile break about change type of pollevent_t

.github/workflows/check.yml
Follow up [#6014](https://github.com/apache/incubator-nuttx/pull/6014)
Same as before
Pass CI
=> .github/workflows/check.yml: Enable Change-ID check explicitly

netutils/usrsock_rpmsg/usrsock_rpmsg.h, netutils/usrsock_rpmsg/usrsock_rpmsg_client.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
rpmsg_usrsock: Support the wireless ioctl which contain pointer
This PR depends on below PR:
https://github.com/apache/incubator-nuttx/pull/6041
=> rpmsg_usrsock: Support the wireless ioctl which contain pointer

nshlib/nsh_syscmds.c
fix reset cause  nsh command print
resetcause cmd
VELA tested
=> fix resetcause nsh command print

netutils/usrsock_rpmsg/usrsock_rpmsg.h, netutils/usrsock_rpmsg/usrsock_rpmsg_client.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
Broadcast the client DNS server to server
Synchronize DNS between client and server
Test passed
=> netutils/usrsock_rpmsg: broadcast the client DNS server to server

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
Don't clear available flag if the response indicate there is more data
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
=> usrsock: Don't clear recv and send available flag

examples/camera/camera_bkgd.c, examples/termios/termios_main.c, testing/getprime/getprime_main.c
follow up the nuttx change: https://github.com/apache/incubator-nuttx/pull/6088
Minor
Pass CI
=> Remove the unneeded void cast

system/critmon/critmon.c
Remove branch since errcount could never bigger than 100.
critmon
CI
=> system/critmon: Fix dead code

boot/mcuboot/Make.defs, boot/mcuboot/Makefile, crypto/libtomcrypt/Make.defs, crypto/libtomcrypt/Makefile
Update Makefiles for mcuboot and libtomcrypt
None. Style changes only
Pass CI
=> make: update makefiles for mcuboot and libtomcrypt

examples/elf/elf_main.c, examples/nxflat/nxflat_main.c, netutils/thttpd/thttpd_cgi.c
Follow nuttx side change: https://github.com/apache/incubator-nuttx/pull/6120
Minor
Pass CI
=> Update the call site of exec to accommodate the environment variables

.gitignore
follow https://github.com/apache/incubator-nuttx/pull/4730
git status
Pass CI
=> .gitignore: Ignore gcov files(*.gcno and *.gcda)

system/gcov/Kconfig, system/gcov/Make.defs, system/gcov/Makefile, system/gcov/gcov.c
pair with https://github.com/apache/incubator-nuttx/pull/4730
New tools for gcov
sim
=> system: Add gcov command

nshlib/nsh_netcmds.c, nshlib/nsh_session.c
apps/nshlibs: fix warning by tools converity report
N/A
local test
=> apps/nshlibs: fix warning by tools converity report

nshlib/nsh_session.c
apps/nshlib: fix run break when argc < 1
fix break
Ci
=> apps/nshlib: fix run break

examples/nrf24l01_btle/nrf24l01_btle.c, examples/nrf24l01_term/nrf24l01_term.c
Follow https://github.com/apache/incubator-nuttx/pull/6232
Minor
Need merge together with https://github.com/apache/incubator-nuttx/pull/6232
=> examples/nrf24l01: Replace the hardcode value with enum const

interpreters/wamr/Kconfig
interpreters/wamr/Kconfig: Add INTERPRETERS_WAMR_PERF_PROFILING
tested on esp32
=> interpreters/wamr/Kconfig: Add INTERPRETERS_WAMR_PERF_PROFILING

testing/ostest/prioinherit.c
See https://github.com/apache/incubator-nuttx/issues/6310
Loss of system priorities
master nuttx
=> ostest:priority_inheritance Added priority restoration test

nshlib/nsh_syscmds.c
Signed-off-by: zhuyanlin <zhuyanlin1@xiaomi.com>
Testing pass in inner board
=> pmconfig: add last state and modify current state to next state

include/netutils/webclient.h, netutils/webclient/webclient.c
webclient: implement basic proxy
a ported version tested on macOS
=> webclient: implement basic proxy

examples/fb/fb_main.c
Exemplary fb App bug fix for drawing rectangle in 1 bit palette
Writing own driver gives and testing using fb app gives bad result. The problem was in app, not in new implemented driver. 
The frame buffer was filled with a wrong manner.
Tested with won implemented driver. Content of frame buffer was verified in order to check if the bits are correctly set.
=> Fixed bug in drawing rectangle using 1 bit palette

mlearning/darknet/Kconfig, mlearning/darknet/Make.defs, mlearning/darknet/Makefile
Darknet is an open source neural network framework written
in C and CUDA. It is fast, easy to install, and supports
CPU and GPU computation.
You Only Look Once (YOLO) is a state-of-the-art,
real-time object detection system
ML
ML
=> mlearning: add Darknet (Open Source Neural Networks in C)

include/netutils/webclient.h, netutils/webclient/webclient.c
webclient: implement https proxy
A ported version was tested on macOS with my local app + squid.
=> webclient: implement https proxy

testing/fstest/fstest_main.c
support fstest can run many times
fstest in sim use tmpfs
fstest -m /tmp &
fstest -m /tmp &
=> fstest:support fstest can run many times

examples/serialblaster/serialblaster_main.c
Serlalblaster exemplary app bugfixes.
In my opinion there ware many bugs in previous implementation. 
None
Yes, on Nucleo Wl55JC board
=> serialblaster bugfix

graphics/nxwidgets/src/cwidgetcontrol.cxx, graphics/nxwm/src/ccalibration.cxx, graphics/nxwm/src/ckeyboard.cxx, graphics/nxwm/src/cnxterm.cxx, graphics/nxwm/src/cstartwindow.cxx, graphics/nxwm/src/ctouchscreen.cxx, graphics/nxwm/src/cwindowmessenger.cxx, graphics/nxwm/src/nxwm_main.cxx, graphics/twm4nx/apps/ccalibration.cxx, graphics/twm4nx/apps/cclock.cxx, graphics/twm4nx/apps/cnxterm.cxx, graphics/twm4nx/src/cbackground.cxx, graphics/twm4nx/src/ciconwidget.cxx, graphics/twm4nx/src/cinput.cxx, graphics/twm4nx/src/cmainmenu.cxx, graphics/twm4nx/src/ctwm4nx.cxx, graphics/twm4nx/src/cwindow.cxx, graphics/twm4nx/src/cwindowevent.cxx
Found by https://github.com/apache/incubator-nuttx/pull/6434
=> Remove the non standard c++ header file inclusion

wireless/wapi/src/wapi.c
wireless/wapi: authentication parameters should update before key set
set authentication parameters before key set on command mode
N/A
wapi command on bcm43013
=> wireless/wapi: authentication parameters should update before key set

wireless/wapi/src/util.c
wapi/utils: add SIOCGIWSENS into string name list
N/A
wapi test
=> wapi/utils: add SIOCGIWSENS into string name list

include/netutils/webclient.h, netutils/webclient/webclient.c
webclient: webclient_get_tunnel API cleanup and comments
tested with my local app.
=> webclient: webclient_get_tunnel API cleanup and comments

.github/dependabot.yml, .github/linters/setup.cfg, .github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/lint.yml
especially, the change from https://github.com/apache/incubator-nuttx/pull/6472
The bot could generate the PR to update the dependence automatically
Pass CI
=> Sync github action from nuttx side

examples/capture/Kconfig, examples/capture/Make.defs, examples/capture/Makefile, examples/capture/cap.h, examples/capture/cap_main.c
add pwm input capture example
nothing
tested on custom board based on stm32f405rg
=> examples: add pwm input capture example

.gitignore, examples/ws2812/Kconfig, examples/ws2812/Make.defs, examples/ws2812/Makefile, examples/ws2812/ws2812_main.c
Example app using the neopixel driver that displays a rainbow pattern.
Should not impact other apps.
Tested app with single and multiple pixel chains with various update speeds.
=> Added Neopixel Example

examples/noteprintf/noteprintf_main.c
follow the kernel side change:
https://github.com/apache/incubator-nuttx/pull/6613
Minor
Pass CI
=> examples/noteprintf: Change CONFIG_LIBC_LONG_LONG to CONFIG_HAVE_LONG_LONG

nshlib/nsh.h, nshlib/nsh_fsutils.c
Fixed a couple of typos that our CI is constantly complaining about.
N/A
N/A
=> nsh: Fixed typos in comments.

nshlib/nsh.h, nshlib/nsh_command.c, nshlib/nsh_fscmds.c
nshlib/dmesg: update config about enable dmesg
N/A
Vela Ci
=> nshlib/dmesg: update config about enable dmesg

netutils/usrsock_rpmsg/usrsock_rpmsg_client.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
usrsock: adjust rptun API
usrsock IPC
VELA
This depends on:
https://github.com/apache/incubator-nuttx/pull/6713
=> usrsock: adjust rptun API

system/nxlooper/nxlooper.c
nxlooper: nxlooper should wait call buffer returned before close
nxlooper
VELA
=> nxlooper: nxlooper should wait call buffer returned before close

nshlib/nsh_command.c, nshlib/nsh_syscmds.c
rptun & pmconfig cmd update
rptun & pmconfig cmd
VELA
=> rptun & pmconfig cmd update

games/.gitignore, games/Make.defs, games/Makefile, games/shift/Kconfig, games/shift/Make.defs, games/shift/Makefile, games/shift/shift_input_console.h, games/shift/shift_input_gesture.h, games/shift/shift_input_joystick.h, games/shift/shift_inputs.h, games/shift/shift_main.c
Add shift game
Users could use this game with any board with LCD framebuffer
https://www.youtube.com/shorts/dsUN4EQ0_JI
=> apps/games: Add shift game

wireless/gs2200m/gs2200m_main.c
When dis-associtaion happens, the socket is destroyed. And all blocking
sockets are released for that error handling can be performed.
Only gs2200m usrsock daemon.
This commit is related on https://github.com/apache/incubator-nuttx/pull/6747
Check if tcpblaster on spresense:wifi work well and if it received an error when disassociation happened.
=> wireless/gs2200m: Release all blocking socket

examples/bridge/bridge_main.c, examples/discover/discover_main.c, examples/ipcfg/ipcfg_main.c, examples/tcpecho/tcpecho_main.c, examples/webserver/webserver_main.c, examples/xmlrpc/xmlrpc_main.c, netutils/iperf/iperf.c, netutils/iperf/iperf_main.c, netutils/thttpd/libhttpd.c, nshlib/nsh_netcmds.c, wireless/wapi/src/wapi.c
Depends on apache/incubator-nuttx#6751
Replaces ntoa by ntoa_r
See apache/incubator-nuttx#6751
=> Use thread-safe ntoa functions

examples/etl/Kconfig, examples/etl/Make.defs, examples/etl/Makefile, examples/etl/etl_main.cxx
Example application for the Embedded Template Library (ETL).
apache/incubator-nuttx#6791
=> Embedded Template Library (ETL) Example application

system/cfgdata/cfgdata_main.c
Add missing description to help message
None
Pass CI
=> system/cfgdata: add "format" command to description

tools/pre-commit
tools/pre-commit should be copied to .git/hooks/pre-commit to take effect.
New file
=> tools: add git pre-commit hook for apps

system/input/Kconfig, system/input/input.c
add input tools keyboard support
Enable CONFIG_INPUT_UINPUT and CONFIG_SYSTEM_INPUT ,
you can use "input keyup/keydown <keycode>" to enter virtual key values on the command line
=> system/input: add input tools keyboard support

examples/foc/foc_motor_b16.c
examples/foc/foc_motor_b16.c: fix open loop Q current
=> examples/foc/foc_motor_b16.c: fix open loop Q current

wireless/wapi/Kconfig, wireless/wapi/src/network.c, wireless/wapi/src/util.c, wireless/wapi/src/wireless.c
Fix coverity warning
Correct return value for scan case
Make the initial scan buffer configurable through Kconfig
=> Some WAPI changes

system/uorb/test/unit_test.c
=> system/uorb: Pass NULL to task_create directly

system/input/input.c
update uinput device name.
uinput keyboard device name should be /dev/ukeyboard
and remove some duplicate prompts
=> system/input: update input device name

nshlib/nsh_fileapps.c
When an application is used as a loadable ELF module like as `CONFIG_EXAMPLES_XXX=m`,
the priority and stack size of that application task is always fixed at the default values.
In other words, `CONFIG_EXAMPLES_XXX_PRIORITY` and `CONFIG_EXAMPLES_XXX_STACKSIZE`
are not referenced at all.
This commit changes to get the priority and stack size of the application from the bulitin list.
If you change the name of the application offline, it will still work with the default values.
If the application name is used as it was built, the priority and stack size set in Kconfig can be applied.
Loadable ELF application.
=> nshlib: Change ELF priority and stack size based on builtin list

testing/monkey/Kconfig, testing/monkey/Make.defs, testing/monkey/Makefile, testing/monkey/monkey.c, testing/monkey/monkey.h, testing/monkey/monkey_assert.h, testing/monkey/monkey_dev.c, testing/monkey/monkey_dev.h, testing/monkey/monkey_log.c, testing/monkey/monkey_log.h, testing/monkey/monkey_main.c, testing/monkey/monkey_proc.c, testing/monkey/monkey_recorder.c, testing/monkey/monkey_recorder.h, testing/monkey/monkey_type.h, testing/monkey/monkey_utils.c, testing/monkey/monkey_utils.h
A UI stress test program based on uinput.
The currently implemented functions are:
1. Support random click and swipe
2. Support recording user operations and playback
3. Support multiple instances, you can start multiple monkey processes to run independently at the same time
4. Support simultaneous monitoring and operation of multiple devices
Add new features.
daily test.
=> testing: add monkey test

include/wireless/wapi.h, wireless/wapi/src/util.c, wireless/wapi/src/wapi.c, wireless/wapi/src/wireless.c
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
wireless/wapi/src/util.c has some Mix case warning.
=> wireless: Add ioctl cmd to setting PTA prio

fsutils/mkgpt/mkgpt.c
Signed-off-by: weizihan <weizihan@xiaomi.com>
fsutils/mkgpt/mkgpt.c
Fix bug by calling getrandom
mkgpt.c  calling getrandom 
passed vela CI
=> apps: Fix bug by calling getrandom

fsutils/mkfatfs/configfat.c, fsutils/mkfatfs/writefat.c, netutils/netlib/netlib_parsehttpurl.c, netutils/telnetd/telnetd_daemon.c, nshlib/nsh_command.c, nshlib/nsh_dbgcmds.c, nshlib/nsh_envcmds.c, nshlib/nsh_fscmds.c, nshlib/nsh_mmcmds.c, nshlib/nsh_mntcmds.c, nshlib/nsh_modcmds.c, nshlib/nsh_netcmds.c, nshlib/nsh_parse.c, nshlib/nsh_passwdcmds.c, nshlib/nsh_proccmds.c, nshlib/nsh_syscmds.c, nshlib/nsh_telnetd.c, nshlib/nsh_test.c, nshlib/nsh_timcmds.c, system/readline/readline_common.c, system/readline/readline_fd.c
Fixes various compiler warnings that I encounter using some of the apps.
N/A
Build test.
=> Fixed compiler warnings.

wireless/gs2200m/gs2200m_main.c
fix the conflict after usrsock reconstruct:
https://github.com/apache/incubator-nuttx/pull/6949
Minor
Pass CI
=> wireless/gs2200m: Rename usrsock_request to usrsock_handle_request

include/netutils/ftpd.h, netutils/ftpd/ftpd.c
Just a few minor changes in FTP daemon:
* Added one missing include.
* Fixed a conditional include.
* Silenced a couple of compiler warnings about unused variables.
N/A
Build test only.
=> Minor changes in ftpd.

netutils/dhcpc/dhcpc.c
In this patch, dhcp will try to get a random xid. If that fails, dhcp will use the default xid.
The reason to do so is from RFC2131:
"The 'xid' field is used by the client to match incoming DHCP messages
with pending requests.  A DHCP client MUST choose 'xid's in such a
way as to minimize the chance of using an 'xid' identical to one used
by another client. For example, a client may choose a different,
random initial 'xid' each time the client is rebooted, and
subsequently use sequential 'xid's until the next reboot.  Selecting
a new 'xid' for each retransmission is an implementation decision.  A
client may choose to reuse the same 'xid' or select a new 'xid' for
each retransmitted message."
DHCP
BL602 tested
=> netutils/dhcpc:Make DHCP xid random

nshlib/nsh_netcmds.c
nshlib/netcmd: add sanity check for netdev
add sanity check for nsh_foreach_netdev() to avoid unnecessary messages being printed
enable CONFIG_NET_MLD, CONFIG_NET_STATISTICS
```
nsh> ls /proc/net
/proc/net:
stat
mld
tcp
route/
eth0
```
Before:
(The message of proc node mld is printed out by ifconfig)
```
nsh> ifconfig
Joins: 0000 Leaves: 0000
Sent       Sched Sent
Queries: 0000  0000
Reports:
Ver 1: ----  0000
Ver 2: 0000  0000
Done:    0000  0000
Received:
Queries:
Gen:   0000
MAS:   0000
MASS:  0000
Ucast: 0000
Bad:   0000
Reports:
Ver 1: 0000
Ver 2: 0000
Done:    0000
eth0	Link encap:Ethernet HWaddr 00:00:00:00:00:00 at RUNNING
inet addr:10.0.0.2 DRaddr:10.0.0.1 Mask:255.255.255.0
inet6 addr: fe80::200:ff:fe00:0/64
inet6 DRaddr: ::/64
IPv4 …
```
=> nshlib/netcmd: add sanity check for netdev 

netutils/dhcpc/dhcpc.c
If Many devices begin DHCPC at the same time. Current DHCP will fail because one device will receive many dhcp packets not for it, and thus exceeds retry count.
Here I made following modification:
1. Receiving unexpected packets does not result in retry count increasing(Only recv timeout will increase retry count)
DHCP
ESP32C3 tested.
=> netutils/dhcpc:receiving unexpected packet not leading to dhcp retry.

testing/mtd_config_fs/mtd_config_fs_test_main.c
test case only
Tested on ESP32C3
=> testing/nvconfig:fix compiling err after removing MTD_CONFIG_ERASEDVALUE

nshlib/Kconfig, nshlib/nsh_command.c
correct commands order in kconfig
N/A
=> Correct commands with alphabet order in kconfig

testing/mtd_config_fs/mtd_config_fs_test_main.c
More test cases for drivers/mtd/mtd_config_fs.c
mtd_config_fs.c only
Tested on ESP32C3 and passed
=> testing/mtd_config_fs:more test cases for garbage collection.

testing/mm/mm_main.c, wireless/ieee802154/i8sak/i8sak_main.c
Required by https://github.com/apache/incubator-nuttx/pull/7185
code refactor
=> Replace #include <queue.h> with #include <nuttx/queue.h>

include/graphics/tiff.h, netutils/thttpd/cgi-src/phf.c, netutils/thttpd/cgi-src/redirect.c, netutils/thttpd/tdate_parse.c, netutils/thttpd/thttpd_cgi.c, netutils/thttpd/thttpd_strings.c, netutils/thttpd/timers.c
Fixed several non-UTF8 characters throughout the source code.
See also [here](https://github.com/apache/incubator-nuttx/pull/7201).
N/A
N/A
=> Fixed non-UTF8 characters.

system/cachespeed/Kconfig, system/cachespeed/Make.defs, system/cachespeed/Makefile, system/cachespeed/cachespeed_main.c
Signed-off-by: crafcat <110923103+crafcat7@users.noreply.github.com>
system/cachespeed:Tools for testing cache-related speed.
None
None
=> system/cachespeed:Tools for testing cache-related speed.

system/ramspeed/ramspeed_main.c
system/ramspeed: Add system interrupt switch.
None
None
=> system/ramspeed: Add system interrupt switch.

testing/ostest/restart.c
Add sem wait test case for task restart.
NA
sabre-6quad:smp
=> ostest: add semaphore wait case for task restart

netutils/dhcpc/dhcpc.c
Two fixes in DHCP client:
1. Previously, on every request the client was setting the current IP address to `INADDR_ANY`. This may be OK for the initial request, but it is problematic for renewals. If any other task is using the network simultaneously with the DHCP renewal, then it was disrupted. Also setting the address to `INADDR_ANY` has not any real advantage for DHCP, as it uses broadcasts. Thus this is removed. DHCP should change the IP only when a new valid lease is offered.
2. In case of a NAK response from the server, the current IP must not be used. Previously the code just exited, and didn't respect that. Now, when the IP is refused, the interface is set to `INADDR_ANY`, ensuring that it the old IP will not be used.
Network communications should be more stable now during DHCP …
=> Fixes in DHCP client.

examples/usrsocktest/usrsocktest_block_recv.c, netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
Correct some status exceptions in non-blocking mode usrsock connect
Depends on https://github.com/apache/incubator-nuttx/pull/7291
=> usrsock_server: Correct some status exceptions in non-blocking mode usrsock connect

nshlib/nsh.h, nshlib/nsh_altconsole.c, nshlib/nsh_consolemain.c, nshlib/nsh_session.c, nshlib/nsh_stdsession.c, nshlib/nsh_system.c, nshlib/nsh_telnetd.c, nshlib/nsh_usbconsole.c
to avoid the code duplication
Code refactor only
Test with sim:adb(https://github.com/apache/incubator-nuttx/pull/7332)
=> nshlib: Reuse nsh_session logic in nsh_telnetmain

interpreters/toywasm/Kconfig, interpreters/toywasm/Make.defs, interpreters/toywasm/Makefile
=> Add interpreters/toywasm

testing/ostest/restart.c
- This commit fixes the task_restart test for the 2nd time execution
- None
- sim:ostest
=> testing: ostest: Fix task_restart test

wireless/gs2200m/gs2200m_main.c
Fix the regression reported here: https://github.com/apache/incubator-nuttx/issues/7367
···
gs2200m [5:50]
nsh> ifconfig
wlan0   Link encap:Ethernet HWaddr 14:5a:fc:f8:14:c5 at UP
inet addr:192.168.28.50 DRaddr:192.168.28.1 Mask:255.255.255.0
nsh> wget http://www.example.com/index.html
<!doctype html>
<html>
<head>
<title>Example Domain</title>
<meta charset="utf-8" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style type="text/css">
body {
background-color: #f0f0f2;
margin: 0;
padding: 0;
font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
div {
width: 600px;
margin: 5em auto;
padding: 2em;
background-color: …
=> gs2200m: fix usrsock_bind error in gs2200m module

netutils/mqttc/Kconfig, netutils/mqttc/Make.defs
Support tls in mqttc
mqttc
Pass CI
=> netutils/mqttc: Add mbedtls configs.

examples/ajoystick/ajoy_main.c, examples/djoystick/djoy_main.c, examples/foc/Kconfig, examples/nunchuck/nunchuck_main.c, examples/timer_gpio/timer_gpio_main.c, examples/zerocross/zerocross_main.c, include/canutils/lely/config.h, netutils/thttpd/libhttpd.c, netutils/thttpd/libhttpd.h, nshlib/nsh_fsutils.c, system/libuv/Makefile, system/spi/spi_main.c
Multiple minor fixes
Fix possible memory overflow
Pass CI
=> Minor fixes

netutils/thttpd/libhttpd.c, netutils/thttpd/libhttpd.h, netutils/thttpd/thttpd.c, netutils/thttpd/thttpd_cgi.c, netutils/thttpd/timers.h
Report here: https://github.com/apache/incubator-nuttx/actions/runs/3302940198/jobs/5450348182
Minor
Pass CI
=> Fix thttpd_alloc.h:64:32: error: 'free' called on pointer 'hc' with nonzero offset 286 [-Werror=free-nonheap-object]

examples/ajoystick/ajoy_main.c, examples/djoystick/djoy_main.c, examples/foc/Kconfig, examples/nunchuck/nunchuck_main.c, examples/timer_gpio/timer_gpio_main.c, examples/zerocross/zerocross_main.c, include/canutils/lely/config.h, netutils/thttpd/libhttpd.c, netutils/thttpd/libhttpd.h, nshlib/nsh_fsutils.c, system/libuv/Makefile, system/spi/spi_main.c
Reverts apache/incubator-nuttx-apps#1377
=> Revert "Minor fixes"

boot/mcuboot/Make.defs, boot/mcuboot/Makefile, canutils/lely-canopen/Make.defs, crypto/libtomcrypt/Make.defs, crypto/mbedtls/Make.defs, crypto/tinycrypt/Make.defs, gpsutils/minmea/Make.defs, graphics/libjpeg/Make.defs, graphics/lvgl/Make.defs, interpreters/duktape/Make.defs, interpreters/lua/Make.defs, interpreters/quickjs/Make.defs, interpreters/wamr/Make.defs, interpreters/wasm3/Make.defs, math/libtommath/Make.defs, mlearning/cmsis/Make.defs, mlearning/cmsis/libcmsisdsp/Make.defs, mlearning/cmsis/libcmsisdsp/Makefile, mlearning/cmsis/libcmsisnn/Make.defs, mlearning/darknet/Make.defs, mlearning/libnnablart/Make.defs, netutils/cwebsocket/Make.defs, netutils/mqttc/Make.defs, system/argtable3/Make.defs, system/libuv/Make.defs, system/uorb/Make.defs
This parameter is not used, it has been removed in this commit
See git commit # 5eae32577e5d5226e5d3027c169eeb369f83f77d
=> Makefile: Remove INCDIROPT

examples/camera/camera_main.c
This example can support for both ISX012 and ISX019 image sensors.
None
./tools/configure.sh spresense:example_camera
=> examples/camera: Dynamically get the connected device

examples/fmsynth/keyboard_main.c, examples/fmsynth/mmlplayer_main.c, games/shift/shift_main.c, modbus/ascii/mbascii.c, nshlib/nsh_fscmds.c
=> Fix waring found by clang

builtin/exec_builtin.c, nshlib/nsh_fileapps.c, system/popen/popen.c, system/system/system.c
follow up the kernel side change
need merge with https://github.com/apache/incubator-nuttx/pull/7485 together
=> Rename task_spawnattr_setstacksize to posix_spawnattr_setstacksize

netutils/iperf/iperf.c
netutils/iperf: add newline in printf format 
N/A
iperf test
=> netutils/iperf: add newline in printf format 

testing/mm/mm_main.c
mm: add memory stress test
mm test
VELA
=> mm: add memory stress test

netutils/webclient/Kconfig
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
Add symbols to web client example application.
=> add symbols in webclient kconfig

examples/gps/Makefile, examples/gps/gps_main.c
Fix GPS example application
Now everybody can test it.
LilyGO_TBeam_LoRa_GPS board
=> gps: Fix GPS example application

system/ramspeed/ramspeed_main.c
In the previous ramspeed test process, it was necessary to keep adding size to achieve speed tests for different sizes of memcpy and memset. After the modification, the results will be automatically looped from 32k to the input size.
=> system/ramspeed:Add automated testing process

canutils/slcan/slcan.c, examples/mcuboot/swap_test/version_main.c, examples/sx127x_demo/sx127x_demo.c, wireless/wapi/src/wapi.c
Found by https://github.com/apache/incubator-nuttx/pull/7391
Minor
Pass CI
=> Fix warn found by https://github.com/apache/incubator-nuttx/pull/7391

nshlib/nsh_command.c, nshlib/nsh_ddcmd.c
add verfiy option to dd
nothing,but if you use dd,can use dd with verfiy option to make sure the file is copied correctly 
local test
=> cmd_dd:add verfiy option to dd

interpreters/wamr/Kconfig
New option to control ref types feature
New feature
custom board
=> interpreters/wamr: New option to support ref types

examples/dac/dac_main.c, examples/foc/foc_fixed16_thr.c, examples/foc/foc_float_thr.c
Found by https://github.com/apache/incubator-nuttx/pull/7391
Minor
Pass CI
=> Fix clang compiler warning

netutils/dhcpc/Kconfig, netutils/dhcpd/Kconfig, system/dhcpc/Kconfig
Found by https://github.com/apache/incubator-nuttx/pull/7627
Minor
Pass CI
=> dhcp: Make the option dependence work for usrsock case

netutils/iperf/iperf.c, netutils/iperf/iperf.h, netutils/iperf/iperf_main.c
netutils/iperf: add support of multi-instance
N/A
iperf test on different port
=> netutils/iperf: add support of multi-instance

examples/ltr308/Kconfig, examples/ltr308/Make.defs, examples/ltr308/Makefile, examples/ltr308/ltr308_main.c
Signed-off-by: Robert-Ionut Alexa <robertalexa2000@gmail.com>
=> apps/ltr308: add simple application to test ltr308 sensor

examples/tcp_ipc_server/uart_lorawan_layer.c, interpreters/ficl/src/nuttx.c, interpreters/minibasic/basic.c, netutils/thttpd/thttpd.c
Please ignore "error: Mixed case identifier found" warning.
minor
Pass CI
=> Remove the unnecessary "return;" at the end of function

interpreters/toywasm/.gitignore
Add .gitignore, following wasm3 and wamr.
=> toywasm: add .gitignore

interpreters/toywasm/Makefile
update toywasm version
tested on esp32-devkitc.
=> interpreters/toywasm: update toywasm version

include/nshlib/nshlib.h, nshlib/Kconfig, nshlib/nsh_login.c, nshlib/nsh_stdlogin.c
Enhance nshlib
nsh login
pass CI
=> nshlib:add platform function

examples/chrono/chrono_main.c, examples/hidkbd/hidkbd_main.c, examples/slcd/slcd_main.c
- examples/hidkbd: Reuse lib_meminstream_s and remove hidbkd_instream_s
Note: need merge with https://github.com/apache/nuttx/pull/7772
Code refactor
Pass CI
=> libc/stream: Rename (put|get) to (putc|getc)

.github/workflows/build.yml
=> build.yml: Sync with nuttx version

nshlib/nsh_telnetlogin.c
forget in the follow patches:
```
commit 6aef469c197a4c5d7a3a8cd766ea04fccb14ed3c
Author: huangjian <huangjian@xiaomi.com>
Date:   Fri Nov 4 20:37:04 2022 +0800
nshlib:judge whether nsh login username is a valid input
Signed-off-by: huangjian <huangjian@xiaomi.com>
commit 88fff23d3497de541d74325690c79c0616f31d6a
Author: huangjian <huangjian@xiaomi.com>
Date:   Fri Nov 4 20:39:26 2022 +0800
nshlib:add platform skip login function
Signed-off-by: huangjian <huangjian@xiaomi.com>
commit 5a623cc9e3f51845007614de9a1e4c74c262d8e9
Author: huangjian <huangjian@xiaomi.com>
Date:   Fri Nov 4 20:35:07 2022 +0800
nshlib:add platform challenge function for nsh login
Signed-off-by: huangjian <huangjian@xiaomi.com>
```
telnet
Pass CI
=> nshlib: Add login skip, invalid name ignore and password challenge to telnet login

examples/pipe/pipe.h
pipe: fix pipe test case failed
pipe shouldn't use /tmp folder, /tmp maybe mounted to tmpfs
pipe
sim:nsh
=> pipe: fix pipe test case failed

include/nshlib/nshlib.h, nshlib/nsh_login.c, nshlib/nsh_stdlogin.c
Enhance nshlib
nsh login
pass CI
=> nshlib:add function to nshlib.h

testing/ostest/sighand.c
ostest: remove printf & sem_wait in sigaction
As the note said:
Use of printf in a signal handler is NOT safe! It can cause deadlocks!
ostest signal test
VELA
=> ostest: remove printf & sem_wait in sigaction

interpreters/luamodules/luasyslog/.gitignore, interpreters/luamodules/luasyslog/Kconfig, interpreters/luamodules/luasyslog/Make.defs, interpreters/luamodules/luasyslog/Makefile
Add lua module lsyslog
No
Locally tested.
=> luamodules/lsyslog: add lua syslog module

interpreters/lua/Module.mk
Support register a list of lua modules.
No.
=> interpreters/lua: support lua module list register

interpreters/lua/Makefile
Fix the duplicated tar unpack on incremental build
No.
=> interpreters/lua: fix unpack on incremental build

testing/cmocka/Kconfig, testing/cmocka/Make.defs, testing/cmocka/Makefile, testing/cmocka/cmocka_main.c
Signed-off-by: yintao <yintao@xiaomi.com>
Add automated testing framework cmocka
None
Pass vela CI
=> cmocka:Add automated testing framework cmocka in testing

system/trace/trace_dump.c
follow the kernel change: https://github.com/apache/nuttx/pull/7900
Minor
Pass CI
=> system/trace: Check NOTERAM_GETTASKNAME existence directly

include/netutils/netlib.h, netutils/netlib/Makefile, netutils/netlib/netlib_iptables.c, system/iptables/Kconfig, system/iptables/Make.defs, system/iptables/Makefile, system/iptables/iptables.c
patches included:
- netutils: Add iptables in netlib. 
- apps/system: Add iptables command. 
Add our own implementation of iptables command compatible with linux one.
Currently used for NAT.
Add a method for user space to control kernel NAT/firewall(maybe).
Tested manually with https://github.com/apache/nuttx/pull/7989
=> apps: Add iptables compatible netlib & command.

interpreters/toywasm/Makefile
interpreter/toywasm: Update toywasm version
Tested on esp32-devkitc.
=> interpreter/toywasm: Update toywasm version

testing/crypto/3descbc.c, testing/crypto/Makefile, testing/crypto/aescbc.c, testing/crypto/aesctr.c, testing/crypto/aesxts.c, testing/crypto/hmac.c
add a testcase for aescbc
crypto test
sim:crypto
=> add a testcase for aescbc

include/system/nxlooper.h, include/system/nxplayer.h, include/system/nxrecorder.h, system/nxcamera/nxcamera.c, system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c, system/nxplayer/nxplayer_main.c, system/nxrecorder/nxrecorder.c
media: fix race condition on nx_xx testcase
system/media: replace sem lock with pthread_mutex
system/media: fix race condion on pthread id
media testcase: nx_xx
VELA
=> media: fix race condition on nx_xx testcase

graphics/pdcurs34/nuttx/Make.defs, modbus/nuttx/Make.defs, testing/ltp/Kconfig
=> Minor typo fix

system/adb/Kconfig
=> adb: add depends on LIBUV

system/argtable3/Kconfig, system/argtable3/Makefile
New test case, but disabled by default
Pass CI
=> [system/argtable3] Add test suite for argtable3

testing/cpuload/Kconfig, testing/cpuload/Make.defs, testing/cpuload/Makefile, testing/cpuload/cpuload_main.c
=> cpuload: add cpulad test case

crypto/tinycrypt/.gitignore
avoid git untracked
Untracked files:
(use "git add <file>..." to include in what will be committed)
crypto/tinycrypt/tinycrypt/
No
Vela
=> crypto/tinycrypt: sync .gitignore with mbedtls/.gitignore

nshlib/nsh_ddcmd.c
Fixes a couple of compiler warnings in dd command.
N/A
Build test in simulator.
=> Fixed compiler warnings in dd.

examples/ajoystick/ajoy_main.c, examples/djoystick/djoy_main.c, examples/module/drivers/chardev/chardev.c, examples/nunchuck/nunchuck_main.c, examples/nxdemo/nxdemo_bkgd.c, examples/nxlines/nxlines_bkgd.c, examples/pwlines/pwlines_internal.h, examples/pwlines/pwlines_update.c, examples/udpblaster/udpblaster.h, examples/zerocross/zerocross_main.c, graphics/nxwidgets/UnitTests/CGlyphButton/cglyphbuttontest.hxx, graphics/twm4nx/src/cresize.cxx, netutils/thttpd/fdwatch.c, netutils/thttpd/libhttpd.h, netutils/thttpd/thttpd_alloc.c, nshlib/nsh_netcmds.c, system/input/input.c, system/nxcamera/nxcamera.c, system/nxlooper/nxlooper.c, testing/ostest/sporadic.c, testing/ostest/sporadic2.c, wireless/gs2200m/gs2200m_main.c
This PR is a follow-up to https://github.com/apache/nuttx/pull/8397.
Code clean-up, should have no impact.
CI build pass.
=> Use `MIN`/`MAX` definitions from `sys/param.h`

include/system/nxlooper.h, system/nxlooper/nxlooper.c, system/nxlooper/nxlooper_main.c
nxlooper: add loopback of compressed audio data.
New functionality
Xiaomi Vela
=> nxlooper: add loopback of compressed audio data.

include/system/nxrecorder.h, system/nxrecorder/Kconfig, system/nxrecorder/nxrecorder.c, system/nxrecorder/nxrecorder_main.c
nxrecorder:  add support to record media file.
New functionality
Xiaomi Vela
=> nxrecorder: add support to record media file.

testing/drivertest/Kconfig, testing/drivertest/Make.defs, testing/drivertest/Makefile, testing/drivertest/cmocka_driver_simple.c, testing/drivertest/drivertest_simple.c
Add drivertest for cmocka driver testcases
None
Pass vela CI
=> testing/drivertest: add drivertest for cmocka driver testcases

system/uorb/sensor/ecg.c, system/uorb/sensor/hall.c, testing/sensortest/sensortest.c
need merged with https://github.com/apache/nuttx/pull/8278
- fix: sensor: update hall data type
- fix: sensor: support ECG event lead info
Minor
Pass CI
=> log hall and ecg sensor info correctly

testing/sensortest/sensortest.c
regression in https://github.com/apache/nuttx-apps/pull/1507
sensnortest
CI
=> testing/sensortest: Fix the typo for ecg sensor

testing/irtest/cmd.cxx
Found by https://github.com/apache/nuttx/pull/8434
Minor
CI
=> tesint/irtest: Include unistd.h to get close prototype

testing/drivertest/Makefile, testing/drivertest/drivertest_rtc.c
Add rtc test case.
New test case
Please ignore "error: Mixed case identifier found" due to cmocka symbols
=> testing/drivertest:add rtc test case.

testing/drivertest/Makefile, testing/drivertest/drivertest_timer.c
add timer driver test
New test case
Please ignore "error: Mixed case identifier found" due to cmocka symbols
=> testing/drivertest: add timer driver test

graphics/ft80x/ft80x_ramcmd.c, graphics/ft80x/ft80x_touch.c
report here: https://github.com/apache/nuttx/actions/runs/4100097451/jobs/7070641033
Minor
CI
=> graphics/ft80x: Fix error: implicit declaration of function 'getpid

logging/nxscope/nxscope_chan.c
=> logging/nxscope/nxscope_chan.c: fix printf warnings

system/trace/trace_dump.c
expand NOTE_DUMP_STRING for use with SCHED_NOTE_CUSTOM_BEGIN
=> trace: expand NOTE_DUMP_STRING

testing/drivertest/Makefile, testing/drivertest/drivertest_pwm.c
add pwm driver test
new test case
Please ignore "error: Mixed case identifier found" due to cmocka symbols
=> testing/drivertest: add pwm driver test

testing/drivertest/Makefile, testing/drivertest/drivertest_watchdog.c
add watchdog test case.
New test case
=> testing/drivertest:add watchdog test case.

testing/drivertest/Makefile, testing/drivertest/drivertest_block.c
=> testing/drivertest: add block driver test

testing/drivertest/Makefile, testing/drivertest/drivertest_gpio.c
=> testing/drivertest: add gpio driver test

system/readline/readline_fd.c
readline: Check the fd before echo
readline, minor
QEMU
=> readline: Check the fd before echo

testing/drivertest/Makefile, testing/drivertest/drivertest_relay.c
Add relay test case
Should be none
test in sim
=> drivertest_relay: add relay test case

examples/watcher/Kconfig, system/sched_note/Kconfig, system/trace/Kconfig
follow the kernel side change: https://github.com/apache/nuttx/pull/8531
Minor
CI
=> system: Change DRIVER_NOTExxx to DRIVERS_NOTExxx

wireless/bluetooth/nimble/Kconfig
which contain the fix: https://github.com/apache/mynewt-nimble/pull/1459
nimble
CI
=> bluetooth/nimble: Update to ed083b36cb85c7437b905ee905ea4aed6a1653ad

testing/drivertest/drivertest_block.c
=> drivertest/block:Add FAR to the pointer

testing/drivertest/drivertest_gpio.c
=> drivertest/gpio:Add FAR to the pointer

system/sched_note/note_main.c, system/trace/trace_dump.c
Need merge with https://github.com/apache/nuttx/pull/8635
=> trace: remove SCHED_INSTRUMENTATION_HIRES

interpreters/bas/bas_auto.c, interpreters/bas/bas_global.c, interpreters/bas/bas_value.c
except "Mixed case identifier found"
Minor
CI
=> interpreters/bas: Fix the nxstyle warning

testing/drivertest/Makefile, testing/drivertest/drivertest_uart.c, testing/drivertest/test_content_gen.py
There are three test.
1. Write a long default string into the serial port.
2. Read the default string given by the last test from the serial port.
3. Manually execute the `test_content_ gen.py` script and write the text into the serial device to test the burst capability or run this script and specify device path to automatically test.
=> drivertest/drivertest_uart: uart driver testcase

examples/udp/udp_server.c
Fix warnings by -Wformat.
Nothing special.
Build and style check
=> apps/examples/udp: Fix warnings by -Wformat

examples/noteprintf/noteprintf_main.c
exampels/note: modify SCHED_NOTE_XXX -> sched_note_xxx
=> exampels/note: modify SCHED_NOTE_XXX -> sched_note_xxx

graphics/lvgl/port/lv_port_fbdev.c
In the double buffer mode, by comparing the position and area of ​​the dirty area in the front and back frames, the copy of the dirty area is reduced.
LVGL application
lvgldemo
=> lvgl/port: optimize fbdev buffer sync algorithm

Application.mk, audioutils/mml_parser/README.md, audioutils/mml_parser/mml_parser.c, canutils/libcanardv1/Makefile, examples/README.md, examples/etl/etl_main.cxx, examples/foc/README.md, examples/lp503x/Kconfig, examples/mcuboot/swap_test/README.md, examples/tcp_ipc_client/README.md, examples/tcp_ipc_client/tcp_ipc_client_main.c, examples/tcp_ipc_server/README.md, examples/tcp_ipc_server/protocol.c, examples/tcp_ipc_server/uart_lorawan_layer.c, examples/timer_gpio/Kconfig, examples/watched/Kconfig, examples/watcher/Kconfig, netutils/iperf/Kconfig, testing/mtd_config_fs/README.md
=> Remove the tail space char from all files

examples/can/Makefile, examples/hidkbd/Makefile, examples/lp503x/Makefile
=> Fix mistakes in comments

examples/apds9960/Makefile
=> apps/examples/apds9960/Makefile: Fix mistakes in comments

examples/ina226/Makefile
=> apps/examples/ina226/Makefile: Fix mistake in comment

examples/battery/Make.defs, examples/battery/Makefile, examples/battery/batt_main.c
=> nuttx-apps/examples/battery: Fix mistakes in comments

system/termcurses/tcurses_vt100.c
Since termcurse will control whole echo and vt100 command itself.
This fix the dupped character in VI's command mode and some display issue in editor mode, like:
```
~
~
~
~
:qq!!
```
termcurse base application
QEMU with vi
=> termcurses: Disable echo for serial driver

examples/qencoder/Makefile, examples/qencoder/qe.h
=> nuttx-apps/examples/qencoder: Fix mistakes in comments

examples/rpmsgsocket/rpsock_client.c, examples/rpmsgsocket/rpsock_server.c, examples/userfs/userfs_main.c, netutils/dhcpd/dhcpd.c, netutils/iperf/iperf.c, netutils/iperf/iperf_main.c, netutils/netinit/netinit.c, system/uorb/sensor/topics.c, testing/getprime/getprime_main.c, testing/ostest/cancel.c, testing/ostest/cond.c, testing/ostest/getopt.c, testing/ostest/prioinherit.c, testing/ostest/pthread_rwlock_cancel.c, testing/ostest/roundrobin.c, testing/ostest/sighand.c, testing/ostest/signest.c, testing/ostest/timedwait.c, testing/ostest/waitpid.c, testing/sensortest/sensortest.c
This PR is a complement to https://github.com/apache/nuttx-apps/pull/1629, both related to the work started on https://github.com/apache/nuttx/pull/8744.
No functional changes, should have no impact.
CI build pass.
=> Include missing headers throughout the repository

modbus/ascii/Make.defs, modbus/functions/Make.defs, system/cachespeed/Make.defs, system/nxrecorder/Make.defs, system/setlogmask/Make.defs, system/uorb/Makefile
=> apps/system: Fix mistakes in comments

nshlib/nsh_login.c, system/termcurses/tcurses_vt100.c
Follow https://github.com/apache/nuttx/pull/8800
nsh login and termcurses
QEMU
=> termios: Fix wrong ECHO flag

canutils/lely-canopen/Make.defs, examples/cordic/Makefile, examples/hello/Makefile, examples/hello_nim/Makefile, examples/hello_rust/Makefile, examples/hello_zig/Makefile, examples/mount/Makefile, examples/noteprintf/Makefile, examples/nxflat/tests/struct/Makefile, examples/nxscope/Makefile, examples/posix_spawn/filesystem/hello/Makefile, examples/sht3x/Makefile, examples/watcher/Makefile, examples/xbc_test/Makefile, fsutils/mkmbr/Makefile, graphics/nxglyphs/Make.defs, graphics/nxglyphs/Makefile
fix error: Relative file path does not match actual file
none
=> apps: fix nxstyle

testing/arch_libc/Kconfig, testing/arch_libc/Make.defs, testing/arch_libc/Makefile, testing/arch_libc/README.md, testing/arch_libc/arch_libc_test_main.c
This a testcase for https://github.com/apache/nuttx/pull/8814
N/A
Tested on QEMU with lm3s6965-ek:qemu-flat
=> Add Arch-specific libc test case.

netutils/codecs/Make.defs, netutils/dhcp6c/Make.defs, netutils/dhcpc/Make.defs, netutils/dhcpd/Make.defs, netutils/discover/Make.defs, netutils/esp8266/Make.defs, netutils/ftpc/Make.defs, netutils/ftpd/Make.defs, netutils/libcurl4nx/Make.defs, netutils/netinit/Make.defs, netutils/netlib/Make.defs, netutils/ntpclient/Make.defs, netutils/pppd/Make.defs, netutils/rexec/Make.defs, netutils/rexecd/Make.defs, netutils/smtp/Make.defs, netutils/telnetc/Make.defs, netutils/telnetd/Make.defs, netutils/tftpc/Make.defs, netutils/thttpd/Make.defs, netutils/webclient/Make.defs, netutils/webserver/Make.defs, netutils/xmlrpc/Make.defs
Add missing first line header
none
=> apps/netutils/: fix nxstyle

examples/elf/elf_main.c, examples/mtdpart/mtdpart_main.c, examples/nxflat/nxflat_main.c, examples/posix_spawn/spawn_main.c, examples/webserver/cgi.c, interpreters/bas/bas_vt100.c, system/vi/vi.c
Fix some hard coded buffer len of snprintf
minor
CI
Please ignore nxstyle warning from origin code.
=> Fix some hard coded buffer len of snprintf

canutils/candump/Kconfig, canutils/cansend/Kconfig, netutils/pppd/ppp.h
Fix indentation issues
None
Pass CI
=> Fix indentation issues

examples/foc/foc_fixed16_thr.c, examples/foc/foc_float_thr.c, examples/foc/foc_motor_b16.c, examples/foc/foc_motor_f32.c, examples/foc/foc_thr.c, examples/pipe/interlock_test.c, examples/pipe/transfer_test.c, examples/popen/popen_main.c, examples/watchdog/watchdog_main.c, industry/foc/fixed16/foc_ang_openloop.c, industry/foc/fixed16/foc_angle.c, industry/foc/fixed16/foc_handler.c, industry/foc/fixed16/foc_model.c, industry/foc/fixed16/foc_routine.c, industry/foc/fixed16/foc_velocity.c, industry/foc/float/foc_ang_openloop.c, industry/foc/float/foc_angle.c, industry/foc/float/foc_handler.c, industry/foc/float/foc_model.c, industry/foc/float/foc_routine.c, industry/foc/float/foc_velocity.c, interpreters/luamodules/cjson/0002-bugfix-Fix-implicit-declaration-warning-for-strncase.patch, interpreters/luamodules/cjson/Makefile, system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c, system/nxplayer/nxplayer_mp3.c, system/nxrecorder/nxrecorder.c, testing/ostest/suspend.c
This PR is a complement to https://github.com/apache/nuttx-apps/pull/1629 and https://github.com/apache/nuttx-apps/pull/1633, all related to the work started on https://github.com/apache/nuttx/pull/8744.
No functional changes, should have no impact.
CI build pass.
=> Add another batch of missing headers throughout the repository 

examples/ftpd/ftpd_main.c
choose the network protocol (ipv4 or ipv6) to bind network in setting ftpd(default ipv6)
N/A
CI check
before
ap> ftpd_start
Starting the FTP daemon
ap> FTP daemon [91] started
Adding accounts:
Root account: USER=root PASSWORD=abc123 HOME=(none)
User account: USER=ftp PASSWORD=(none) HOME=(none)
User account: USER=anonymous PASSWORD=(none) HOME=(none)
after
ap> ftpd_start -4
Starting the FTP daemon
ap> FTP daemon [58] started
Adding accounts:
Root account: USER=root PASSWORD=abc123 HOME=(none)
User account: USER=ftp PASSWORD=(none) HOME=(none)
User account: USER=anonymous PASSWORD=(none) HOME=(none)
ap> ftpd_start -6
Starting the FTP daemon
ap> FTP daemon [86] started
Adding accounts:
Root account: USER=root PASSWORD=abc123 HOME=(none)
User account: USER=ftp PASSWORD=(none) HOME=(none) …
=> examples/ftpd: Add support for choosing address family

nshlib/README.md
Forget in the commit #1319 
commit 06f39d10f15c7e68b3bd1c528bb7bb89fe5a8bd0
Author: Junbo Zheng <zhengjunbo1@xiaomi.com>
Date:   Mon Sep 12 15:43:36 2022 +0800
apps/nshlib: add uptime command support
Improve usage of more commands in NuttX
Local Build
=> nshlib/README.md: add uptime command description

nshlib/nsh_parse.c
This adds support for more complex alias handling, such as:
$ alias ls='ls -l'
Previously such an alias was not split into the command verb and the argument correctly, instead the full alias string was handled as the verb, which obviously fails.
This commit fixes this by expanding the alias, checking whether it has arguments and if so, it merges the expanded alias + the old command line together, resulting in a completely new command line.
Example (assuming the alias above has been created):
$ ls /bin
Results in a new command line: "ls -l /bin" which is then parsed and executed.
Adds support for aliases with arguments
icicle:nsh
=> nsh/alias: Add support for alias arguments

examples/dac/dac_main.c, examples/webserver/webserver_main.c, include/netutils/httpd.h, include/netutils/netlib.h, netutils/netlib/netlib_server.c, netutils/webserver/httpd.c
Fix misc issues found by code review:
1. Add missing `FAR` and `CODE`
2. Improve modularity of `httpd`
3. Fix indentation issue
4. Fix typos in comments
N/A
Pass CI
=> Fix misc issues found by code review

nshlib/nsh_telnetlogin.c
Current implementation is broken, in this patch ECHO is disabled by termios.
This patch works with https://github.com/apache/nuttx/pull/8950
telnet login
QEMU and sim
=> nshlib: Don't show passwd in telnet login

testing/ostest/roundrobin.c
=> apps/testing/ostest/roundrobin.c: Fix nxstyle errors

system/ymodem/Kconfig, system/ymodem/README.md, system/ymodem/rb_main.c, system/ymodem/sb_main.c, system/ymodem/sbrb.py, system/ymodem/ymodem.c, system/ymodem/ymodem.h
ymodem enhancements and code style fixes
use ymodem
armv8-m armv7-m board
For more precautions, please read the readme
this commit depens on [nuttx 9049](https://github.com/apache/nuttx/pull/9049)
=> ymodem enhancements and code style fixes

graphics/nxwidgets/src/cwindoweventhandlerlist.cxx
Fix incorrect #endif position
Now users will be able to use nxwidgets with touch
N/A
=> Nxwidget: Fix incorrect #endif position

graphics/tiff/tiff_finalize.c, include/graphics/tiff.h
error: Bad alignment
error: Right brace must be followed by a blank line
error: Long line found
none
=> graphics: Fix nxstyle errors

testing/ostest/signest.c
If the same signal is quickly repeated multiple times, the signal may be ignored. In SMP since we cannot control thread scheduling to ensure timely signal processing, it is best to use semaphores to wait for signal processing to complete, which can also shorten the ostest time
none
ostest
=> ostest:fix signal test fail

nshlib/README.md, nshlib/nsh_command.c
modify the description of setting MTU
N/A
N/A
=> nshlib/netcmds:modify the description of setting MTU

system/sched_note/note_main.c, system/termcurses/tcurses_vt100.c
=> system: Fix nxstyle errors

examples/foc/foc_motor_b16.h, examples/foc/foc_motor_f32.h
examples/foc: improve the readability of the motor structures
Purely cosmetic change
CI
=> examples/foc: improve the readability of the motor structures

testing/ostest/sighand.c
sem need to be destroyed
none
none
=> ostest/sighand_test: sem need to be destroyed

nshlib/Kconfig
Remove spaces from Kconfig file
none
=> nshlib/Kconfig: Fix Kconfig style

system/nxlooper/nxlooper.c, system/nxplayer/nxplayer.c, system/nxrecorder/nxrecorder.c
check ac_channels upper four bits which means min channels.
=> system/audio: check if channels are valid

wireless/wapi/src/driver_wext.c, wireless/wapi/src/util.c, wireless/wapi/src/wapi.c, wireless/wapi/src/wireless.c
to avoid some return -1, otheer return -errno
=> wireless/wapi: Return -errno in all fail path

tools/Wasm.mk
Link `libgcc.a` like compiler intrinsics library into wasm module.
Wasm module only
=> tools/Wasm.mk: Link compiler-rt into wasm module

examples/rpmsgsocket/rpsock_client.c, examples/rpmsgsocket/rpsock_server.c, system/uorb/listener.c
Fix compilation warnings
None
Pass CI
=> apps: correct print specifiers to fix compilation warnings

system/ramtest/ramtest.c
In this change, we have added a malloc from the heap to get the address when the user does not pass an address. We took into account that the user would be testing the memory after the device was started, but this required them to focus on how to get a piece of address available. To improve the experience of tool users, we can simply ask them to get a size for testing purposes, while also keeping the ability to test for a given address This change is mainly in the 'parse_commandline' function, so there are a few changes in the way it is used, see usage for details.
=> system/ramtest.c:New automatic memory acquisition function.

testing/monkey/monkey_recorder.c
Add missing file permission setting, fix file read failure.
None.
None.
=> testing/monkey: add file permission settings

examples/README.md, examples/libtest/Kconfig, examples/libtest/Make.defs, examples/libtest/Makefile, examples/libtest/libtest.c, examples/libtest/libtest.h, examples/libtest/libtest_main.c
Redefine the name of BIN to support static library:
```
BIN = $(APPDIR)/libtest$(LIBEXT)
```
new example
ci
=> apps/libtest: add libtest demo

system/setlogmask/setlogmask.c
add syslog channel filtering function
=> syste/setlogmask: add syslog channel filtering function

examples/mtdpart/CMakeLists.txt, examples/mtdrwb/CMakeLists.txt, examples/nettest/host/CMakeLists.txt, examples/usrsocktest/CMakeLists.txt, fsutils/mksmartfs/CMakeLists.txt, netutils/iperf/CMakeLists.txt, system/nxplayer/CMakeLists.txt, testing/fstest/CMakeLists.txt, testing/nxffs/CMakeLists.txt, wireless/bluetooth/CMakeLists.txt, wireless/bluetooth/btsak/CMakeLists.txt
cmake/apps: add more applications into cmake support
N/A
ci-check
=> cmake/apps: add more applications into cmake support

examples/nimble/nimble_main.c, wireless/bluetooth/nimble/Kconfig, wireless/bluetooth/nimble/Makefile.nimble, wireless/bluetooth/nimble/include/syscfg/syscfg.h
Various improvements for NimBLE
Improve NimBLE integration
Tested with custom app based on NimBLE
=> Various improvements for NimBLE

include/netutils/xtables.h
Based on the previous patch comments, some changes were made to corrected some issues and make it more nuttx style.
https://github.com/apache/nuttx-apps/pull/1829
sim:local
=> iptables: modify the formatting of some definitions in xtables.h

testing/drivertest/Makefile, testing/drivertest/drivertest_block.c
There are a total of three changes to blk in that Patch
1. The storage device is tested for functionality once through BCH, and the time taken varies for different storage media.
2. Bypass BCH, directly write a piece of data size (simulated file system)
3. bypass BCH, write the size of the cache size of the data, the purpose of the test is to detect the existence of the cache function on the drive whether there is an impact, because when there is a problem with the cache function, it may affect the read and write function of the storage driver.
=> blktest:New Test Items

examples/foc/Kconfig, examples/mld/Kconfig, examples/nettest/Kconfig, examples/tcpblaster/Kconfig, examples/udp/Kconfig, examples/udpblaster/Kconfig, graphics/nxwidgets/Kconfig, graphics/nxwm/Kconfig, netutils/webserver/Kconfig, nshlib/Kconfig, testing/ostest/cancel.c, testing/ostest/ostest_main.c, testing/ostest/pthread_rwlock_cancel.c
and remove the unnecessary defined(CONFIG_PTHREAD_CLEANUP_STACKSIZE)
minor
ci
=> Kconfig: Simplify the conditional default statement 

.github/workflows/check.yml, system/argtable3/CMakeLists.txt
system/artable3: add cmake build support
N/A
sim/rpserver
=> system/artable3: add cmake build support 

testing/mm/mm_main.c
testing/mm: add maxsize parameter
none
none
=> testing/mm: add maxsize parameter

fsutils/mkgpt/mkgpt.c
fsutils/mkgpt: dump partition when verify failed
add dump info to check why gpt verify failed.
daily test
=> fsutils/mkgpt: dump partition when verify failed

system/uorb/uORB/uORB.c
system/uorb: Solve the problem of wrong use of return value
fix subscribe/advertise failed
daily test
=> system/uorb: Solve the problem of wrong use of return value

math/CMakeLists.txt, math/libtommath/CMakeLists.txt
migrate libtommath to cmake build, libtomcrypt depend on this mathlib
None
None
=> cmake:migrate apps CMakeLists for libtommath

examples/camera/camera_main.c
depends on https://github.com/apache/nuttx/pull/9932
internal test
=> examples/camera: Video driver multi-instance adaptation

audioutils/fmsynth/fmsynth.c, audioutils/fmsynth/fmsynth_eg.c, audioutils/fmsynth/fmsynth_op.c, include/audioutils/fmsynth.h, include/audioutils/fmsynth_eg.h, include/audioutils/fmsynth_op.h
To use this with static instance, add create function with arguments.
examples/fmsynth
Execute the example if it works well.
=> audioutils/fmsynth: Add create instance for static

examples/nrf24l01_btle/nrf24l01_btle.h, include/audioutils/mml_parser.h, include/netutils/webclient.h, industry/foc/fixed16/foc_ang_onfo.c, industry/foc/float/foc_ang_onfo.c, lte/alt1250/alt1250_container.h, lte/alt1250/alt1250_postproc.h, netutils/webclient/webclient.c, system/ntpc/ntpcstatus_main.c
=> Fix nuttx coding style

crypto/CMakeLists.txt, crypto/mbedtls/CMakeLists.txt
migrate cmake build for mbedtls
sim , mbedtls benchmark
=> cmake:migrate apps CMakeLists for mbedtls

.gitignore, crypto/libsodium/0001-fix-multiple-definition-bug-in-libsodium-test.patch, crypto/libsodium/0002-fix-cannot-find-file-sodium-version.h.patch, crypto/libsodium/Kconfig, crypto/libsodium/Make.defs, crypto/libsodium/Makefile
=> crypto/libsodium: porting libsodium

testing/ltp/0002-Use-ifdef-instead-of-if-for-__linux__.patch, testing/ltp/Makefile
Fix github download ltp code error:
Cloning into 'ltp'...
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository. fatal: unable to auto-detect email address (got 'root@33ba2a4a6fc5.(none)')
=> ltp/makefile: nuttx on github download ltp code failed fix

crypto/libtomcrypt/CMakeLists.txt
migrate cmake build for libtomcrypt
sim,  ltcrypt demo
=> cmake:migrate apps CMakeLists for libtomcrypt

netutils/wakaama/Kconfig
wakaama: update wakaama to a commit that include a fix for wakaama examples under NuttX
sim with wakaama example
=> wakaama: update wakaama

graphics/libyuv/Makefile
=> graphics/libyuv: refine makefile

tools/mkkconfig.sh
=> apps/tools:fix build warning.

testing/osperf/Kconfig, testing/osperf/Make.defs, testing/osperf/Makefile, testing/osperf/osperf.c
Measure the performance of core system functions
such as thread switching and the time required for semaphore execution
=> testing: add os performance measurement

testing/drivertest/drivertest_rtc.c, tools/mkkconfig.sh
=> drivertest_rtc:fix RTC_HAVE_SET_TIME is false.

testing/drivertest/Makefile, testing/drivertest/drivertest_oneshot.c, testing/drivertest/drivertest_posix_timer.c
=> add oneshot test

nshlib/nsh_syscmds.c
resetcause:show reset string not number
reboot arg
use `reboot factory` can pass the correct restart flag
=> resetcause:show reset string not number

testing/drivertest/Kconfig, testing/drivertest/Makefile, testing/drivertest/drivertest_framebuffer.c, testing/drivertest/drivertest_lcd.c
=> add frambuffer and lcd driver test

system/fdt/Kconfig, system/fdt/Make.defs, system/fdt/Makefile, system/fdt/version_gen.h
add fdt utility tools, work with https://github.com/apache/nuttx/pull/10121
tools for fdt
internal testing
=> fdttools: add fdt utility tools

testing/drivertest/Makefile, testing/drivertest/drivertest_timer.c
=> Timer test

testing/drivertest/Makefile, testing/drivertest/drivertest_regulator.c
=> add test case for regulator

system/i2c/i2c_hexdump.c, system/i2c/i2c_main.c, system/i2c/i2c_reset.c
=> Add function is missing FAR

testing/drivertest/Makefile, testing/drivertest/drivertest_adc.c
=> drivertest/adc : support cmocka_driver_adc

examples/poll/poll_main.c
example/poll: add delay for poll testcase
for should setup the fifo firstly
=> example/poll: add delay for poll testcase

crypto/libtomcrypt/Kconfig, crypto/libtomcrypt/Makefile
porting libtomcrypttest
no impact
=> Feat porting libtomcrypttest

testing/cmocka/Kconfig, testing/cmocka/Make.defs
=> Memory leaks can be checked using cmocka

testing/drivertest/Makefile
=> testing/drivertest : fix build error

crypto/tinycrypt/0001-TinyCrypt-test-resolve-compile-error.patch, crypto/tinycrypt/Kconfig, crypto/tinycrypt/Makefile
=> Enable TinyCrypt tests.

interpreters/quickjs/Kconfig, interpreters/wamr/Kconfig, interpreters/wasm3/Kconfig
=> Fix Kconfig style

graphics/lvgl/Kconfig, testing/drivertest/Makefile, testing/drivertest/drivertest_touchpanel.c
=> drivertest:Add touch panel test case.

examples/touchscreen/tc_main.c
=> apps/examples:Edit arm64 compilation error

system/i2c/i2c_bus.c, system/i2c/i2c_dev.c
=> Fix the bug of i2c_bus

testing/cmocka/0003-cmocka-update-method-for-strmatch-to-regex-and-add-list-all-testcases-function.patch, testing/cmocka/Kconfig, testing/cmocka/Makefile, testing/cmocka/cmocka_main.c
=> Update testing/cmocka to support more functions.

testing/mtd_config_fs/Kconfig
=> select some configuration

crypto/libsodium/Makefile
(1)fix unable to pull source code
(2)fix compile warning
=> crypto/libsodium: fix libsodium compilation problem

examples/capture/cap_main.c
=> example/capture : fixed build warning

testing/ostest/ostest_main.c, testing/ostest/tls.c
follow nuttx change: https://github.com/apache/nuttx/pull/10320
ci
=> testing: Check CONFIG_TLS_NELEM is defined before using it

system/libuv/Makefile
system/libuv: export GCCVER to environment
N/A
ci-check
=> system/libuv: export GCCVER to environment

examples/keyboard/Kconfig, examples/keyboard/Make.defs, examples/keyboard/Makefile, examples/keyboard/kbd_main.c
Add test example for keyboard device
apps/examples
ci
=> apps/examples:Add keyboard example

nshlib/nsh_syscmds.c
=> nshlib: fix a typo

testing/drivertest/drivertest_regulator.c
add a testcase for regualtor register when id is the same
=> regulator:add testcase for regualtor register

system/nxcamera/nxcamera.c
After optimizing the vync mechanism, it is necessary to use ioctl (display) to refresh the display in dual buffer mode.
Nxcamera.
Run nxcamera.
=> system/nxcamera: add pan_display when it is not single buffer.

benchmarks/coremark/CMakeLists.txt, canutils/lely-canopen/CMakeLists.txt, canutils/libdronecan/CMakeLists.txt, canutils/libopencyphal/CMakeLists.txt, crypto/libsodium/CMakeLists.txt, crypto/libtomcrypt/CMakeLists.txt, crypto/mbedtls/CMakeLists.txt, crypto/tinycrypt/CMakeLists.txt, fsutils/inih/CMakeLists.txt, fsutils/libtinycbor/CMakeLists.txt, math/libtommath/CMakeLists.txt
clean code smell
no functional changes
CI build
=> focus on fixing cmake code smell issues

testing/fatutf8/fatutf8_main.c
=> solve CI compilation error problem

system/ramspeed/ramspeed_main.c
The result of repeat_cnt * step has been truncated
ramspeed
internal test
=> app:ramspeed the result of repeat_cnt * step has been truncated

testing/ltp/Makefile
=> app/ltp : enable can_filter/can_rcv_own_msgs

include/netutils/md5.h, netutils/codecs/md5.c
Add the API for 'md5_file' to directly obtain the digest value by passing in the file path
None
None
=> codecs: add md5_file API

nshlib/nsh_fsutils.c
Fix errors in static scanning
None
None
=> Implement md5_file

testing/cmocka/cmocka_main.c
=> run testsuites where name match pattern value of --suite

.gitignore, testing/nist-sts/.gitignore, testing/superpi/.gitignore
=> add superpi fold and nist-sts fold to gitignore

examples/configdata/configdata_main.c
reported by https://github.com/apache/nuttx/actions/runs/6147485876/job/16679277697?pr=10589
minor
ci
=> Fix Error: configdata_main.c:402:14: error: variable 'iteration' set but not used [-Werror,-Wunused-but-set-variable]

netutils/dhcpd/dhcpd.c
dhcpd:Optimize the data area memory and reduce it by about 1k bytes
If a daemon app(e.ot_client) starts dhcpd by calling dhcpd_start and needs to shut it down after use, then the global static variables ds_inpacket and ds_outpacket will always occupy the data area,causing unnecessary waste.
minor
=> dhcpd:Optimize the data area memory and reduce it by about 1k bytes

testing/ostest/sigprocmask.c
Fix signal test
signal test
./tools/configure.sh -l qemu-armv8a:nsh_smp
=> Fix signal test

tools/Wasm.mk
Fix issues with multi thread compilation.
Wasm module build only
Vela
=> tools: Lock wasm archive during ar rcs

testing/ltp/config.h
this config.h using to control the test procedure of the relative test cases. this config.h file is generated by ltp project internal build file, as we are nuttx build system, so need to manage this file by manual
=> testing/ltp: add config.h file

wireless/gs2200m/gs2200m_main.c
Support SIOCDENYINETSOCK ioctl command to set usrsock status.
If usock_enable is false, its means application wants to create
a socket with other network stack.
GS2200
Spresense with WiFi
=> wireless/gs2200m: Add support SIOCDENYINETSOCK ioctl command

testing/cmocka/0004-cmocka-xml-report-and-generate-case-and-suite-tool.patch, testing/cmocka/Makefile, testing/cmocka/cmocka_main.c
=> support xml report and a case create tool

testing/drivertest/Makefile, testing/drivertest/drivertest_pm_runtime.c
add pm runtime testcase
self test
=> pm:add pm runtime testcase

lte/alt1250/usock_handlers/alt1250_shutdownhdlr.c
ALT1250 daemon to support shutdown.
Only ALT1250 dameon.
=> lte/alt1250: Correspond to shutdown

system/uorb/test/unit_test.c
=> apps/system/uorb/test/unit_test.c: add orb_copy return judgment.

crypto/mbedtls/0002-mbedtls-add-mbedtls-x509-crt-pool.patch, crypto/mbedtls/Makefile, crypto/mbedtls/include/mbedtls/mbedtls_config.h
Reducing the use of memory due to multiple network links loading certificates
=> crypto/mbedtls: load certificate memory optimization

examples/wiegand/Kconfig, examples/wiegand/Make.defs, examples/wiegand/Makefile, examples/wiegand/wiegand.c
Added apps to Wiegand Protocol 
None of the existing systems
=> App for Wiegand Protocol

system/zlib/Makefile
system/zlib:fix makefile rule
zlib
sim:zipfs
=> system/zlib:fix makefile rule

examples/shm_test/CMakeLists.txt, examples/shm_test/Kconfig, examples/shm_test/Make.defs, examples/shm_test/Makefile, examples/shm_test/shm_main.c
SHM example with producer and consumer
=> Shm example

wireless/gs2200m/gs2200m_main.c
Fix handling of ioctl except SIOCDENYINETSOCK
gs2200 daemon.
Test with spresense borad.
=> Fix handling of ioctl except SIOCDENYINETSOCK 

examples/ftpc/ftpc_main.c, examples/lp503x/lp503x_main.c, examples/nrf24l01_term/nrf24l01_term.c, include/system/readline.h, interpreters/lua/Makefile, system/nxcamera/nxcamera_main.c, system/nxlooper/nxlooper_main.c, system/nxplayer/nxplayer_main.c, system/nxrecorder/nxrecorder_main.c, system/readline/CMakeLists.txt, system/readline/Makefile, system/readline/readline.c, system/readline/readline_stream.c
system/readline: correct the readline(3) prototype
Reference:
https://man.openbsd.org/readline.3
N/A
ci-check
=> system/readline: correct the readline(3) prototype

nshlib/nsh_command.c, nshlib/nsh_fscmds.c
to follow host tool usage:
https://github.com/util-linux/util-linux/blob/master/sys-utils/losetup.c#L473
losetup/lomtd
ci
=> nshlib: losetup/lomtd change "-s <sectsize>" to "-b <sectsize>"

examples/foc/Kconfig, examples/foc/foc_cfg.h, examples/foc/foc_thr.c
- examples/foc: add warning if no controller enabled
- examples/foc: fix setpoint scale for char interface
- foc/example/Kconfig: cosmetics
=> examples/foc: minor changes

examples/foc/Kconfig, examples/foc/foc_cfg.h, examples/foc/foc_fixed16_thr.c, examples/foc/foc_float_thr.c, examples/foc/foc_main.c, examples/foc/foc_motor_b16.c, examples/foc/foc_motor_b16.h, examples/foc/foc_motor_f32.c, examples/foc/foc_motor_f32.h, examples/foc/foc_parseargs.c
examples/foc: add velocity PI controller
=> examples/foc: add velocity PI controller

industry/foc/fixed16/foc_ramp.c, industry/foc/float/foc_ramp.c
industry/foc/ramp: fix acceleration in CCW direction and simplify code
=> industry/foc/ramp: fix acceleration in CCW direction and simplify code

testing/ostest/CMakeLists.txt, testing/ostest/Makefile, testing/ostest/ostest.h, testing/ostest/ostest_main.c, testing/ostest/smp_call.c
This is test case for [PR#10934.](https://github.com/apache/nuttx/pull/10934)
NA
qemu-armv8a:nsh_smp ostest pass
=> ostest: Add smp function call test case

examples/foc/foc_parseargs.c
-  examples/foc: use the current configuration values when printing the help message  
This is useful when tuning the controller and running application many times with different parameters from the NSH
=> examples/foc: use the current configuration values when printing the help message 

examples/stepper/CMakeLists.txt, examples/stepper/Kconfig, examples/stepper/Make.defs, examples/stepper/Makefile, examples/stepper/stepper.c
=> Add stepper example

LICENSE, crypto/wolfssl/Kconfig
wolfssl depends on ALLOW_GPL_COMPONENTS
CI
=> wolfssl depends on ALLOW_GPL_COMPONENTS

system/cachespeed/cachespeed_main.c, testing/arch_libc/arch_libc_test_main.c, testing/osperf/osperf.c
follow up the the kernel change:
https://github.com/apache/nuttx/pull/10834
no
ci
=> testing: Swith up_perf_xxx to perf_xxx

testing/memtester/Kconfig
Fixed display errors in Kconfig
None
None
=> memtester:Modify the misnaming in Kconfig

system/memstress/memorystress_main.c
This patch enhances the debug capabilities of memstress.
1. Add more output information
2. When a problem occurs, print the error location immediately and trigger assert.
3. Replace most printf with syslog.
None
Local test Passed
=> memorystress:Enhanced debugging capabilities

testing/fmemopen/Kconfig, testing/fmemopen/Make.defs, testing/fmemopen/Makefile, testing/fmemopen/fmemopen.c
Test tool application for `fmemopen` for CI testing. Performs basic read/write/seek/append operations.
CI test
CI passes.
=> testing: add fmemopen function test tool

include/system/nxrecorder.h, system/nxrecorder/CMakeLists.txt, system/nxrecorder/Makefile, system/nxrecorder/nxrecorder.c, system/nxrecorder/nxrecorder_amr.c, system/nxrecorder/nxrecorder_common.c
=> system/nxrecorder: add amr offload record support

benchmarks/spinlock_bench/CMakeLists.txt, benchmarks/spinlock_bench/Kconfig, benchmarks/spinlock_bench/Make.defs, benchmarks/spinlock_bench/Makefile, benchmarks/spinlock_bench/spinlock_bench.c
spinlock benchmark
None
local test
=> feature: spinlock benchmark

testing/monkey/Kconfig, testing/monkey/monkey.c, testing/monkey/monkey_event.c, testing/monkey/monkey_event.h, testing/monkey/monkey_log.h, testing/monkey/monkey_main.c, testing/monkey/monkey_proc.c, testing/monkey/monkey_type.h, testing/monkey/monkey_utils.c, testing/monkey/monkey_utils.h
1. Simplify kconfig configuration items.
2. Use events to control the status of virtual devices and improve testing efficiency.
3. Add adaptive screen resolution support.
None.
Daily test.
=> testing/monkey: refact monkey test

testing/cmocka/Makefile, testing/cmocka/cmocka_main.c
=> add short command-line arguments and record execution time

examples/foc/foc_motor_b16.c, examples/foc/foc_motor_f32.c
examples/foc: set direction when updating new setpoint
refactor
locally on various hw
=> examples/foc: set direction when updating new setpoint

examples/foc/Kconfig, examples/foc/foc_cfg.h, examples/foc/foc_motor_b16.c, examples/foc/foc_motor_b16.h, examples/foc/foc_motor_f32.c, examples/foc/foc_motor_f32.h
- examples/foc: add velocity saturation
- examples/foc: add torque saturation
- examples/foc: pass from velocity controller to torque controller
preparation for position controller
odriver3.6
=> examples/foc: refactor motor controller

interpreters/wamr/Kconfig
See also: https://github.com/bytecodealliance/wasm-micro-runtime/pull/2795
New option
Vela
=> wamr: Add support for custom section loading

interpreters/toywasm/Makefile, interpreters/toywasm/include/toywasm_version.h
toywasm: update to v35
sim/macOS
=> toywasm: update to v35

system/coredump/coredump.c
coredump:support coredump command restore coredump form block device
coredump
use` coredump -s /data` ,we can save coredump file at /data
=> coredump:support coredump command restore coredump form block device

system/gdbstub/gdbstub.c
update gdb_process api
gdbstub
gdbstub demo
nuttx pr: [11350](https://github.com/apache/nuttx/pull/11350)
=> gdbstub:update gdb_process api

interpreters/wamr/Kconfig
See also:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2975
No
WAMR Community
=> wamr: Add new option to enable tail call support

system/adb/Kconfig, system/adb/Makefile, system/adb/adb_main.c, system/adb/logcat_service.c
- adbd/logcat: Change alog_ prefix to logcat_
- adb: Don't declare variables in the middle of function 
need merge together with https://github.com/apache/nuttx/pull/11499
minor
internal
=> Minor fix for adb

interpreters/wamr/Kconfig
wamr: Add new option to enable quick aot entry
WAMR side: https://github.com/bytecodealliance/wasm-micro-runtime/pull/3040
No.
CI
=> wamr: Add new option to enable quick aot entry

.github/workflows/build.yml
build.yml  -> add msys2 job
There should be no impact.
We tested on the local platform MSYS2 and GitHub
=> tools/ci: add initial support for MSYS2

system/tcpdump/tcpdump.c
apps/tcpdump: Support capture RAW IP interfaces like TUN
tcpdump capture file header only
Together with https://github.com/apache/nuttx/pull/11744, capturing both TUN and ETH.
=> apps/tcpdump: Support capture RAW IP interfaces like TUN

testing/cmocka/0005-cmocka-cmocka_private-fix-warning-in-cmocka_private.patch
=> fix patch error:no such file

database/Make.defs, database/Makefile, database/sqlite/.gitignore, database/sqlite/Kconfig, database/sqlite/Make.defs, database/sqlite/Makefile, database/sqlite/sqlite_cfg.h
enable UTILS_SQLITE configuration, use the sqlite3 command line tool
sim
=> database: add sqlite support

database/.gitignore
fix compile failure
Untracked files:
(use "git add <file>..." to include in what will be committed)
database/Kconfig
=> database: fix compile failure

testing/cmocka/0006-fix-linux-risc-v-compile-error-list_initialize.patch, testing/cmocka/Makefile
fix error https://github.com/apache/nuttx/actions/runs/8258128633/job/22589978029?pr=11654
linux risc-v
=> fix compile error: list_initialize

testing/testsuites/kernel/fs/cases/fs_eventfd_test.c, testing/testsuites/kernel/fs/cases/fs_fsync_test.c, testing/testsuites/kernel/fs/cases/fs_stream_test.c, testing/testsuites/kernel/time/cases/clock_test_timer03.c
fix build warning for kernel testsuites
CI
local host
=> fix build warning for kernel testsuites

testing/cmocka/.gitignore
=> ignore zip file

canutils/canlib/canlib_getbaud.c, canutils/canlib/canlib_getloopback.c, canutils/canlib/canlib_getsilent.c, canutils/canlib/canlib_setbaud.c, canutils/canlib/canlib_setloopback.c, canutils/canlib/canlib_setsilent.c, include/canutils/canlib.h
=> canutils: Fix minor style issue found in canlib

testing/mtd_config_fs/mtd_config_fs_test_main.c
The previous test case simulation writing did not consider byte alignment
Pass CI.
Local build with the following config, pass.
CONFIG_MTD_CONFIG=y
CONFIG_MTD_BYTE_WRITE=y
CONFIG_MTD_CONFIG_FAIL_SAFE=y
CONFIG_TESTING_MTD_CONFIG_FAIL_SAFE=y
CONFIG_MTD_WRITE_ALIGN_SIZE=8
=> mtd_config_fs: support align size test

netutils/ping/icmp_ping.c
fix ping return error when ifdown interface
PING
Vela products
=> ping early return bugs fix

audioutils/fmsynth/test/Makefile, benchmarks/iozone/Makefile, examples/adjtime/Makefile, examples/lvgldemo/Make.defs, examples/wiegand/Makefile, examples/ws2812esp32rmt/Make.defs, examples/ws2812esp32rmt/Makefile, fsutils/mkgpt/Makefile, graphics/nxwidgets/Makefile, graphics/nxwidgets/UnitTests/CButton/Makefile, graphics/nxwidgets/UnitTests/CKeypad/Makefile, graphics/screenshot/Makefile, netutils/iptables/Make.defs, netutils/iptables/Makefile, netutils/thttpd/cgi-src/Makefile, system/dhcp6c/Make.defs, system/dhcp6c/Makefile, testing/atomic/Makefile, testing/cpuload/Makefile, testing/nist-sts/Makefile, testing/sd_bench/Make.defs, testing/sd_bench/Makefile, testing/sd_stress/Make.defs, testing/testsuites/Make.defs, testing/testsuites/Makefile
fix Relative file path does not match actual file.
Add missing Apache Foundation copyright header
none
=> fix nxstyle

interpreters/toywasm/Makefile, interpreters/toywasm/include/toywasm_version.h, interpreters/toywasm/src/toywasm_config.c
=> toywasm: update to v44.0.0

interpreters/wamr/Kconfig
expected merge order:
https://github.com/apache/nuttx/pull/12355
https://github.com/apache/nuttx-apps/pull/2395
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3439
=> wamr: tweak the defaults according to the new ARCH kconfig options

benchmarks/ramspeed/ramspeed_main.c
Don't expose interrupt control with kernel configuration.
enter_critical_section and leave_critical_section aren't reliable interfaces to expose in usermode, as they aren't available if CONFIG_IRQCOUNT is enabled.
Allows the ramspeed benchmark to be built when both `CONFIG_BUILD_KERNEL` and `CONFIG_IRQCOUNT` are enabled. 
Litex based board with the above configuration enabled.
=> benchmarks/ramspeed: Don't expose interrupt control with kernel configuration.

interpreters/toywasm/Makefile, interpreters/toywasm/include/toywasm_version.h
tested with esp32s3-devkit:toywasm
=> toywasm: bump to v48.0.0

wireless/bluetooth/nimble/Kconfig, wireless/bluetooth/nimble/include/syscfg/syscfg.h
nimble: update to the latest master
draft until https://github.com/apache/mynewt-nimble/pull/1795 is merged
=> nimble: update to the latest master

testing/debug/CMakeLists.txt, testing/debug/Kconfig, testing/debug/Make.defs, testing/debug/Makefile, testing/debug/debug.c
It is a simple test case of the NuttX debugging facilities (breakpoint and watchpoint).
See also: https://github.com/apache/nuttx/pull/12549
New test case
STM32F411
=> testing: Add simple debug test program

audioutils/fmsynth/CMakeLists.txt, lte/alt1250/CMakeLists.txt, lte/lapi/CMakeLists.txt, system/spi/CMakeLists.txt
lte: Add CMakeLists.txt
system/spi: Add CMakeLists.txt
audioutils/fmsynth: Fix CMakeLists.txt
=> lte: Add CMakeLists.txt 

examples/oneshot/oneshot_main.c
oneshot/oneshot_main.c: fix printf warning
=> oneshot/oneshot_main.c: fix printf warning

examples/telnetd/telnetd.c, examples/telnetd/telnetd.h
Make it clear the goal of this telned:
https://acassis.wordpress.com/2024/07/02/how-a-supposed-malfunction-revealed-another-hidden-feature-of-nuttx/
Avoid confusing example telnetd with netutils telnetd
N/A
=> examples/telnetd: Make it clear the goal of this telned

testing/ltp/Kconfig
lpt/Kconfig: hide TESTING_LTP_STACKSIZE option
hide TESTING_LTP_STACKSIZE option when TESTING_LTP=n
cosmetic change
CI
=> lpt/Kconfig: hide TESTING_LTP_STACKSIZE option

system/nxcodec/Kconfig
Improve Kconfig help，add submitted .rst documentation  through URL https://github.com/apache/nuttx/pull/12650
NA
NA
=> nxcodec: improve Kconfig help

system/dd/dd_main.c
Add oseek optional parameter to seek/skip on output file.
If oseek=N passed, will seek N*bs on output file before witing.
Optional,  keeping existing seek and bs as-is.
dd if=/dev/zero of=/dev/mtd0 bs=1 count=32 oseek=15728640
=> dd_main.c: Add oseek optional argument.

interpreters/wamr/Kconfig
wamr: add an option for exception-handling
build-tested
=> wamr: add an option for exception-handling

nshlib/nsh_fscmds.c, system/popen/popen.c, testing/fstest/fstest_main.c
1、fstest: If the file is deleted it will not be opened
2、popen: Replace fcntl with ioctl
3、nshlib: Optimize the size of the recursive stack
fstest
fstest
=> fstest: If the file is deleted it will not be opened

benchmarks/superpi/CMakeLists.txt
=> add superpi cmake

netutils/libcoap/Makefile
correct the LIBCOAP_VERSION format
cortex-m33 board
=> libcoap: fix makefile compile error after menuconfig

netutils/mqttc/CMakeLists.txt
add cmakelist for mqttc 
None
tested on sim
=> netutils/mqttc: add cmake support

testing/drivertest/Makefile, testing/drivertest/drivertest_framebuffer.c, testing/drivertest/drivertest_touchpanel.c
Fix running drivertest shows exception
drivertest model
Local test passed
=> Drivertest

system/input/input.c
Fix input simulates touch reporting error
simulates touch
simulates
=> apps: Fix input simulates touch reporting error

graphics/lvgl/Makefile
Add `LV_SYSMON_GET_IDLE` and `LV_PROFILER_BEGIN/END` system interface adapter.
lvgl
=> lvgl/Makefile: add LV_SYSMON_GET_IDLE and LV_PROFILER porting

system/nxcamera/CMakeLists.txt
=> system/nxcamera: add CMakeLists.txt

testing/drivertest/CMakeLists.txt, testing/drivertest/Makefile, testing/drivertest/drivertest_pm.c
=> testing/drivertest: add driver pm testcase

system/critmon/critmon.c
Command "critmon" has some format errors and information errors, such as:
After bug fix:
config is:
N/A
Execute "critmon" in nsh
=> [BugFix]Command "critmon" error

system/spi/spi_exch.c
=> Fixed the problem of memory trampling caused by not initializing the structure

examples/capture/cap_main.c
Description: Add test of the function of counting cap edges
=> apps/examples: Add test of edges counting at capture

examples/mld/mld_main.c, netutils/netlib/netlib_setdripv4addr.c, nshlib/nsh_routecmds.c
fix stack-overflow bug
need to ci with https://github.com/apache/nuttx/pull/12994
tested on sim
=> netlib/setroute: fix dhcpd stack-overflow when with debug info-level

testing/pcitest/Kconfig, testing/pcitest/Make.defs, testing/pcitest/Makefile, testing/pcitest/pcitest.c
=> pci: add pcitest tool

audioutils/lame/CMakeLists.txt, audioutils/libmad/CMakeLists.txt
1. libmad: Add download libmad.zip to CMakeLists.txt
2. lame: update CMakeLists.txt
Fix https://github.com/apache/nuttx/pull/13088 check error.
```
nxrecorder
nxrecorder> device pcm1c
nxrecorder> record /data/rec.mp3 2 16 44100
```
=> lame_libmad: update CMakeLists.txt

system/uorb/listener.c
=> system/uorb: fix err when using the -n 1 parameter

system/nxrecorder/nxrecorder.c
=> Mp3 opus upstream

system/debugpoint/CMakeLists.txt, system/debugpoint/Kconfig, system/debugpoint/Make.defs, system/debugpoint/Makefile, system/debugpoint/debug.c
Rename debug to debugpoint according to https://github.com/apache/nuttx/pull/13319
No
Local machine
=> system: Rename debug to debugpoint

testing/fftest/CMakeLists.txt, testing/fftest/Kconfig, testing/fftest/Make.defs, testing/fftest/Makefile, testing/fftest/fftest.c
testing/fftest: add Force feedback driver test
Add testcase for ff driver
Vela
=> testing/fftest: add Force feedback driver test

examples/amg88xx/CMakeLists.txt, examples/amg88xx/Kconfig, examples/amg88xx/Make.defs, examples/amg88xx/Makefile, examples/amg88xx/amg88xx_main.c
Simple example for the amg88xx driver
=> examples/amg88xx: add example for amg88xx driver

examples/dhcpd/dhcpd_daemon.c
dhcpd routing will cover other routing 
routing 
tested on vela product
=> apps/dhcpd: fix dhcpd set routing error

include/wireless/wapi.h, wireless/wapi/src/util.c, wireless/wapi/src/wapi.c, wireless/wapi/src/wireless.c
1. add set/get  powersave api for lowpower device
2. add set/get  pmksa api for fast-wifi-connect requirement
3. add extend api for private needs,and can trans any struct but should equal with vendor
N/A
tested on vela product
=> Private requirement for wapi

testing/drivertest/CMakeLists.txt, testing/drivertest/Makefile, testing/drivertest/drivertest_i2c_read.c, testing/drivertest/drivertest_i2c_write.c
=> I2C slave test case

graphics/lvgl/CMakeLists.txt, graphics/lvgl/Kconfig, graphics/lvgl/Makefile
Add lvgl custom compilation optimization level to balance code size and code execution efficiency.
lvgl application.
set `CONFIG_LV_OPTLEVEL=-O3`
=> lvgl: add customize compilation optimization level config

interpreters/quickjs/Makefile, interpreters/wamr/Makefile, math/libtommath/Makefile
1. complete missing DEPPATH for applactions
supplement missing code declaration
CI
=> build(bugfix): add missing --deppath

interpreters/toywasm/Makefile, interpreters/toywasm/include/toywasm_version.h
=> Bump toywasm to v63.0.0

nshlib/nsh.h, nshlib/nsh_builtin.c, nshlib/nsh_command.c, nshlib/nsh_fileapps.c, nshlib/nsh_parse.c
nsh:support $! get last pid use nsh run
nsh
sim nsh
```
test:
nsh> hello &
hello [4:100]
nsh> Hello, World!!
nsh> echo $!
4
nsh> echo $!
3
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK COMMAND
0     0   0 FIFO     Kthread   - Ready              0000000000000000 0069616 Idle_Task
1     1 224 FIFO     Kthread   - Waiting  Signal    0000000000000000 0067536 loop_task
2     2 224 FIFO     Kthread   - Waiting  Semaphore 0000000000000000 0067504 hpwork 0x45ae80 0x45aea8
3     3 100 FIFO     Task      - Running            0000000000000000 0067536 nsh_main
nsh>
```
=> nsh:support $! get last pid use nsh run

testing/drivertest/drivertest_posix_timer.c
change deviation to be pass as parameter.
N/A
chip: cortexM55
=> update posix timer testcase

netutils/ntpclient/ntpclient.c
Based on the printed error and the call stack, it was determined that the `clock_settime` function is called in the NTP code, and there is an overflow of the `int64` parameter. By adding logging, it was found that during NTP synchronization, the time offset can be negative. The previous calculation method caused negative values to be converted to -1, which, when cast to `uint32_t`, becomes 4294967295. Consequently, adding this offset to the current time results in an overflow of `int64` after synchronizing twice.
ntp
sim
=> ntp:fix parameter is negative numbers.

testing/ostest/CMakeLists.txt, testing/ostest/Makefile, testing/ostest/ostest.h, testing/ostest/ostest_main.c, testing/ostest/wdog.c
Add wdog test case in flat build.
NA
Test at BES board, run ostest pass.
=> ostest: Add wdog test case

system/dhcpc/CMakeLists.txt, system/fdt/CMakeLists.txt
1.  Fix wrong name for dhcpc
2. Add fdt CMake support
No.
Local CI build
=> minor fix for cmake

system/uorb/Kconfig, system/uorb/listener.c, system/uorb/sensor/topics.c, system/uorb/test/unit_test.c, system/uorb/uORB/uORB.c, system/uorb/uORB/uORB.h
1. orb_flush: After you call orb_flush(), you can determine whether the flush is completed by listening to the POLLPRI event
of fd and getting the event in orb_get_events.
2. remove non-posix implement, include api and header file, let uorb compile in aosp.
3. bug fix
new api: orb_flush, orb_get_events
Vela
=> system/uorb: bug fix and support flush/get_events api and comiple in aosp

examples/elf/elf_main.c, examples/elf/tests/Makefile, examples/sotest/lib/Makefile, examples/sotest/sotest_main.c
examples/sotest/elf: enable and run sotest/elf simultaneously 
N/A
Vela
=> examples/sotest/elf: enable and run sotest/elf simultaneously 

examples/ws2812esp32rmt/ws2812esp32rmt_main.c, graphics/nxwm/src/cnxterm.cxx, graphics/twm4nx/apps/cnxterm.cxx, lte/alt1250/alt1250_devevent.c, system/uniqueid/uniqueid_main.c, testing/sensortest/sensortest.c
Misc bugfixes in apps spotted during code review
Should be none
Pass CI
=> Misc bugfixes in apps

examples/elf/tests/helloxx/hello++4.cxx, examples/elf/tests/helloxx/hello++5.cxx, examples/nxflat/tests/hello++/hello++4.cxx, lte/lapi/src/lapi_dbg.h, netutils/ptpd/ptpd.c, system/cu/cu_main.c
Fix few indentation issues spotted during browsing the code
Add missing `FAR` for `ptpd`
N/A
Pass Ci
=> Add missing 'FAR' in apps

testing/drivertest/Makefile, testing/drivertest/drivertest_mps2_zerointerrupt.c
mps2: add zero-latency-interrupt case on mps2
mps2 new test case
this case
=> mps2: add zero-latency-interrupt case on mps2

examples/romfs/Kconfig
=> examples/romfs: Add a new dependency

system/uorb/Kconfig, system/uorb/listener.c, system/uorb/sensor/topics.c, system/uorb/test/unit_test.c, system/uorb/uORB/uORB.c, system/uorb/uORB/uORB.h
orb_flush: After you call orb_flush(), you can determine whether the flush is completed by listening to the POLLPRI event
of fd and getting the event in orb_get_events.
remove non-posix implement, include api and header file, let uorb compile in aosp.
bug fix
RELEASE
CI
=> {Bp-2639} system/uorb: bug fix and support flush/get_events api and comiple in aosp

system/nxcodec/nxcodec.c, system/nxcodec/nxcodec_context.c, system/nxcodec/nxcodec_main.c
- nxcodec: add rich debugging logs
- nxcodec: fix build warning 
minor
ci
=> nxcode improvement

system/cle/cle.c, system/readline/readline_fd.c
getline function support backspace
None
sim qemu arm
=> libc:getline support backspace

examples/pipe/pipe.h, examples/pipe/pipe_main.c, examples/pipe/transfer_test.c
By arranging and combining the priorities of read and write threads to cover more usage scenarios.
pipe example
QEMU
=> examples/pipe: Enhance test by different r/w thread priority

testing/cxxsize/CMakeLists.txt, testing/cxxsize/Kconfig, testing/cxxsize/Make.defs, testing/cxxsize/Makefile, testing/cxxsize/README.md, testing/cxxsize/array.cxx, testing/cxxsize/condition_variable.cxx, testing/cxxsize/deque.cxx, testing/cxxsize/exception.cxx, testing/cxxsize/forward_list.cxx, testing/cxxsize/future.cxx, testing/cxxsize/iostream.cxx, testing/cxxsize/list.cxx, testing/cxxsize/map.cxx, testing/cxxsize/multiset.cxx, testing/cxxsize/mutex.cxx, testing/cxxsize/rtti.cxx, testing/cxxsize/semaphore.cxx, testing/cxxsize/set.cxx, testing/cxxsize/shared_ptr.cxx, testing/cxxsize/string.cxx, testing/cxxsize/string_view.cxx, testing/cxxsize/thread.cxx, testing/cxxsize/unordered_map.cxx, testing/cxxsize/unordered_multimap.cxx, testing/cxxsize/unordered_multiset.cxx, testing/cxxsize/unordered_set.cxx, testing/cxxsize/vector.cxx, testing/cxxsize/weak_ptr.cxx
profile the code size for stl class
new test case
ci
=> apps/testing:Add c++ STL code size test case.

system/cu/cu_main.c
Fix issue with return value not being checked
avoid the busy loop
ci
=> Fix issue with return value not being checked

system/libuv/CMakeLists.txt, system/libuv/Makefile
Reverts apache/nuttx-apps#2679
=> Revert "libuv: Remove GCCVER and add compilation options directly."

testing/drivertest/drivertest_block.c
driverteset_block.c: Reduce the stack consumption
The stack size used is reduced from about 3200 bytes to about 2000 bytes.
1. By reducing the use of local variables geometry
2. Use structure pre_build_s pointers instead of using the structure directly
Test in vela
=> driverteset_block.c: Reduce the stack consumption

nshlib/nsh_parse.c, system/trace/trace.c, system/trace/trace_dump.c
1. nshlib: Add startup process buried points 
2. trace: fix trace dump crash 
sim
=> nshlib: Add startup process buried points 

netutils/thttpd/libhttpd.c, netutils/thttpd/thttpd.c, netutils/thttpd/thttpd_cgi.c, netutils/thttpd/thttpd_cgi.h, netutils/thttpd/timers.c, netutils/thttpd/timers.h
error: Mixed case identifier found
thttpd
ci
=> thttpd:fix Coding Style Check Failed issue

examples/rpmsgsocket/rpsock_client.c, examples/rpmsgsocket/rpsock_server.c
1.  fix build warning, add header files
2. fix redefine warning
none
sim/ vela ci
=> rpmsgsocket：fix build warning

testing/fstest/fstest_main.c
Add header to fix build issues
none
vela ci
=> fstest: Add header to fix build issues

system/ymodem/rb_main.c, system/ymodem/sb_main.c
follow the change in kernel side change
No
No
=> system/ymodem: Change #include <nuttx/mm/circbuf.h> to #include <nuttx/circbuf.h>

nshlib/Kconfig, nshlib/nsh.h, nshlib/nsh_command.c, nshlib/nsh_proccmds.c
Optimize the implementation of the ps command and implement the top command
1. added pid list for ps command.
we can ps <pid ...>
2. ps supports noheap parameter
skip forech heap for ps, use -heap to shwo heap
3. Reconstruct ps command for top command
nshlib/ps
qemu/sim run ps and top
=> Optimize the implementation of the ps command and implement the top command

system/coredump/coredump.c
type of info->time has changed into timespec
coredump
=> coredump app: type of info->time has changed into timespec

nshlib/Kconfig, nshlib/nsh.h, nshlib/nsh_command.c, nshlib/nsh_timcmds.c
nsh: support watch command 
sim
=> nsh: support watch command 

testing/mm/mm_main.c
In the mm test, if the memory requested this time exceeds 3/4 of the remaining memory,
the request will be skipped to avoid insufficient memory.
testing/mm
qemu/sim run mm
=> testing: mm test will be skipped to prevent memory overflow

testing/drivertest/drivertest_i2c_spi.c
Supports incoming device nodes so we can test both iic and spi
drivertest_i2c_spi
local test
=> drivertest_i2c_spi: Supports incoming device nodes so we can test both iic and spi

system/libuv/CMakeLists.txt, system/libuv/Makefile
=> libuv: Remove GCCVER redefinition.

nshlib/nsh_parse.c
nsh_parse using nsh_arg_clone and pthread detach.
when pthread detached, and parent task exit, the sub-thread will quit directly.
lead to **memleak**. we should prefer use sub-process to do nsh background tasks.
this case can re-produce memory leak.
```C
int main(int argc, FAR char *argv[])
{
printf("Hello, World!!\n");
system("sleep 1 &");
return 0;
}
```
use 
```
sh -c
```
to do backtground command, will also compatible with kernel build.
before fix, spawn feature used many times. and try run buildin_cmds & quit quickly, will cause a memory leak.
after fix, spawn required nsh all from nsh_spawn.c
No more memleak in previouse case.
basic features still works as expect.
enable tmpfs and work with qemu-armv8a & qemu-armv7a.
```C
int main(int argc, FAR char *argv[])
{
char buffer[100]; …
```
=> nshlib: use sh -c replace pthread detach when nsh background.

fsutils/mkgpt/mkgpt.c, netutils/dhcpc/dhcpc.c
and follow the kernel side change:
https://github.com/apache/nuttx/pull/14509
code refactor only
ci(need merge https://github.com/apache/nuttx/pull/14509 first)
=> Replace getrandom with arc4random_buf to simplify the usage

testing/stressapptest/.gitignore
=> testing/stressapptest: fix: git status --ignore normalization check problem

testing/drivertest/CMakeLists.txt, testing/drivertest/Kconfig, testing/drivertest/Makefile, testing/drivertest/drivertest_pm.c, testing/drivertest/drivertest_pm_smp.c
update drivertest case, pm case now support smp, oneshot case default disabled.
pm case not able to run in smp, need to adapt pm_idle API.
CI-test, qemu-armv8a.
=> update drivertest case, pm case now support smp, oneshot case default disabled.

testing/ostest/ostest_main.c, testing/ostest/wqueue.c
ostest: update wqueue test for new API
work_xx_wq()
wqueue test case
CI
=> ostest: update wqueue test for new API

system/gcov/Kconfig
gcov: modify depends on
No
depends on https://github.com/apache/nuttx/pull/14557
=> gcov: modify depends on

testing/cxxtest/cxxtest_main.cxx
=> cxxtest: Add static string test.

system/gprof/Kconfig
gprof: modify depends on
None
please enable CONFIG_PROFILE_MINI and CONFIG_SYSYTEN_GPROF，and nsh run: gprof
=> gprof: modify depends on

.gitignore, Application.mk, Make.defs, Makefile
bin:Copy debug info to a separate folder
Reduce bin size
sim:sotest with debug symbol
=> bin:Copy debug info to a separate folder

system/dd/dd_main.c
* make if= of= optional
* printf format
* eof handling
* portability
system/dd
esp32s3-devit
wasip1
=> system/dd: a few improvements

testing/kasantest/Kconfig
=> kasantest.c: Adding Dependencies

system/gcov/gcov.c
gcov: Add a signature end statement to test statement matching
=> gcov: Add a signature end statement to test statement matching

testing/nand_sim/Kconfig
nand_sim testing compile failed
nand_sim testing compile failed
Local test
=> TESTING_NAND_SIM: Add depends on

testing/testsuites/Kconfig
fix tab error and remove Useless depends on
None
local test
=> fix tab error and remove Useless depends on

examples/adxl372_test/Kconfig, examples/apa102/Kconfig, examples/battery/Kconfig, examples/bmi160/Kconfig, examples/camera/Kconfig, examples/chrono/Kconfig, examples/dhtxx/Kconfig, examples/hdc1008_demo/Kconfig, examples/hidkbd/Kconfig, examples/ina219/Kconfig, examples/ina226/Kconfig, examples/isl29023/Kconfig, examples/lp503x/Kconfig, examples/lsm330spi_test/Kconfig, examples/pca9635/Kconfig, examples/powerled/Kconfig, examples/powerled/powerled_main.c, examples/powermonitor/Kconfig, examples/rfid_readuid/Kconfig, examples/rfid_readuid/rfid_readuid.c, examples/slcd/Kconfig, examples/smps/Kconfig, examples/smps/smps_main.c, examples/ws2812/Kconfig, examples/xbc_test/Kconfig, examples/xbc_test/xbc_test_main.c, testing/irtest/Kconfig, testing/pcitest/Kconfig, testing/sensortest/Kconfig, testing/testsuites/Kconfig
examples: Add depends on
none
local test
=> examples: Add depends on

testing/rpmsgdev/Kconfig
Replace space with tab for Kconfig.
testing/rpmsgdev
CI
=> testing/rpmsgdev: Replace space with tab for Kconfig

testing/nettest/CMakeLists.txt, testing/nettest/Kconfig, testing/nettest/Makefile, testing/nettest/others/test_others.c, testing/nettest/others/test_others.h, testing/nettest/others/test_others_bufpool.c, testing/nettest/others/test_others_common.c
Add test for net bufpool
apps / testing / net / bufpool.
local qemu test
=> testing/nettest: Add test for net bufpool

examples/lp503x/lp503x_main.c
examples/lp503x/lp503x_main: Variables and error handling minor fixes.
examples/lp503x
local test
=> lp503x_main: Minor fix

nshlib/nsh_mmcmds.c
apps/nshlib: Reuse local variable for cmd_memdump
apps/nshlib/memdump
CI
=> apps/nshlib: Reuse local variable for cmd_memdump

system/coredump/coredump.c
Update system/coredump utility as changes in https://github.com/apache/nuttx/pull/15677
Should have no impact on usage.
=> move coredump info to note 

benchmarks/cyclictest/cyclictest.c
Without the -q (--quiet) option, the program outputs the thread stats every 100ms, which is compatible with the original rt-tests/cyclictest utility.
This commit makes it possible to see thread stats in realtime. The -q option turns it off.
Locally on my samv71 board.
Note: Build and before / after runtime logs are more than welcome :-)
=> benchmarks/cyclictest/cyclictest.c: periodic output and -q option

system/uorb/listener.c
fix typo "Mointor" -> "Monitor"
Impact on user: NO.
Impact on build: NO.
CI
=> system/uorb/listener.c: fix typo

system/dd/dd_main.c
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/dd.html
> notrunc
>   Do not truncate the output file. Preserve blocks in the output
>   file not explicitly written by this invocation of the dd utility.
=> system/dd: Implement conv=notrunc

testing/ostest/wdog.c
The peridiodical wdog test cases should be removed due to the removing of the periodical wdog APIs. (https://github.com/apache/nuttx/pull/16481)
None.
Tested on QEMU/x86_64 and SIM.
=> ostest/wdog: Remove periodical wdog test cases.

games/snake/snake_main.c
Add high score feature into snake game
Add high score feature to print at the end in Snake game example
Snake game
Same steps applied on https://github.com/apache/nuttx-apps/pull/3028
```
make distclean && ./tools/configure.sh esp32-devkitc:snake && make -j && make download ESPTOOL_PORT=/dev/ttyUSB0 ESPTOOL_BAUD=921600 && picocom /dev/ttyUSB0 -b 115200
```
Alternatively, you can use `esp32-devkitc:nsh` defconfig with enabling following options:
```
CONFIG_DEV_GPIO=y
CONFIG_ESP32_GPIO_IRQ=y
CONFIG_ESP_RMT=y
CONFIG_EXAMPLES_GPIO=y
CONFIG_EXAMPLES_RMTCHAR=y
CONFIG_EXAMPLES_RMTCHAR_RX=y
CONFIG_EXAMPLES_RMTCHAR_TX=y
CONFIG_EXAMPLES_WS2812=y
CONFIG_GAMES_SNAKE=y
CONFIG_GAMES_SNAKE_USE_GPIO=y
CONFIG_RMT=y
CONFIG_RMTCHAR=y
CONFIG_RMT_DEFAULT_RX_BUFFER_SIZE=256
CONFIG_SCHED_LPWORK=y …
```
=> games/snake: Enchacements for snake game

games/match4/Kconfig, games/match4/Make.defs, games/match4/Makefile, games/match4/match4_input_console.h, games/match4/match4_input_gpio.h, games/match4/match4_inputs.h, games/match4/match4_main.c
Related to https://github.com/apache/nuttx/pull/16712
Add match4 game for demo purposes. Currently, game requires 8x8 led matrix (or serial output can be used when debug option enabled) and buttons/console input. Goal is matching 4 pieces vertical,horizontal or diagonal. You can play game against device(AI) or another player.
* games/snake: Fix terminal issue after returning back from snake game
Fix terminal issue after returning back from game
* games: Add match4 game
Add match4 game support
Impact on user: Yes, a new game can be used to make demos
Impact on build: No, nothing got affected from build system
Impact on hardware: ESP32-DevkitC has a new defconfig but nothing will be effected
Impact on documentation: Yes, game and defconfig docs added
Impact on security: No
Impact on …
=> Games: Add match4 game

crypto/mbedtls/source/cmac_alt.c, crypto/mbedtls/source/poly1305_alt.c, crypto/mbedtls/source/sha1_alt.c, crypto/mbedtls/source/sha256_alt.c, crypto/mbedtls/source/sha512_alt.c
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
aligned return value in shax with mbedtls test suits
*Update this section with information on why change is necessary,
what it exactly does and how, if new feature shows up, provide
references (dependencies, similar problems and solutions), etc.*
add input parameter check
*Update this section, where applicable, on how change affects users,
build process, hardware, documentation, security, compatibility, etc.*
nsh> test_suite_shax
SHA-1 Test Vector NIST CAVS #1 .................................... PASS
SHA-1 Test Vector NIST CAVS #2 .................................... PASS
SHA-1 Test Vector NIST CAVS #3 .................................... PASS
SHA-1 Test Vector NIST CAVS #4 …
=> crypto/mbedtls-alt: aligned shax return value with mbedtls test

boot/nxboot/Kconfig, boot/nxboot/tools/nximage.py
Mention the name of the possible entrypoint function for nxboot.
Previously it was hard to guess the name of the entrypoint.
Two other text snippets are fixed or improved.
Readers may appreciate this.
The new text is readable and seems to be free of spelling mistakes.
=> boot/nxboot: improve documentation
