Application.mk

since the file generated by REGISTER macro don't have such suffix
Change-Id: I6814f5bd257563f897c63d9698f8892d9649dcef

Application.mk remove _main suffix from REGLIST

---

system/cle/cle.c

- changes NSH command line editing so ctrl-K deletes from char pos to EOL like GNU readline
- now you can delete entire line with `ctrl-A` `ctrl-K`
- None if `CONFIG_NSH_CLE` is not set
- if `CONFIG_NSH_CLE=y` is set, `ctrl-K` deletes from cursor position to end of line, instead of the old behavior, cursor position + 1 to end of line. 
- The new behavior is more like GNU Readline
- Manual, on the SAMA5D36-Xplained board.
- `CONFIG_NSH_CLE=y`in `.config`
- make clean; make
- connect to the NSH via a serial console
- You should see the new command line editing behavior

changes NSH command line editing so ctrl-K deletes from char pos to EOL like GNU readline

---

netutils/ftpd/ftpd.c

In error clean-up, it was trying to free memory on an error where we failed allocated memory.  Not good.

netutils/ftpd/ftpd.c:  Fix an error introduced in PR10.

---

examples/sx127x_demo/sx127x_demo.c

Also fix issues reported by nxstyle

Include the file name to open and the fail error number

---

examples/README.txt
examples/netloop/Kconfig
examples/netloop/netloop.h
examples/poll/poll_internal.h
netutils/thttpd/config.h

NuttX commit 346336bb9e5c9199b82e34d08bf23dd1bc389460 make CONFIG_NET_TCP_READADHEAD unselectable and removed all references to CONFIG_NET_TCP_READHEAD from the the NuttX repositories.  However, there was no corresponding removal of CONFIG_NET_TCP_READHEAD from the apps/ repository.  As a result, there was logic that depended on the selection of CONFIG_NET_TCP_READHEAD that could never be enabled.
This was found during build testing using the configuration olimex-lpc1766stk/thttpd-binfs.  THTTPD was not being built fully because it had dependencies on CONFIG_NET_TCP_READHEAD.  There resulted int numerous new warnings and, finally, the error:
(.../apps.examples.thttpd.o): in function `thttp_main':
thttpd_main.c:(.text+0x104): undefined reference to `thttpd_main'

Remove unselectable CONFIG_NET_TCP_READHEAD dependencies.

---

Application.mk

The GNU make CURDIR will always be a POSIX-like path with forward slashes as path segment separators.  If we know that this is a native build, then we need to fix up the path so the DELIM will match the actual delimiter.

apps/Application.mk:  Fix path calculation.

---

examples/module/drivers/chardev/Makefile

chardev bin may not availabe before make install in parallel build,
so add install dependency on chardev BIN here.
Change-Id: If28451ceeeed0a6463544d8c342871cecda5a057

Add install dependency on chardev BIN to fix parallel build break

---

wireless/gs2200m/gs2200m_main.c

- Removed unnecessary usleep() in gs2200m_main.c to improve throughput.
- All network use-cases whch use gs2200m Wi-Fi module.
- I tested webserver and telnetd use-cases with Spresense.

apps: gs2200m: Remove unnecessary usleep() to improve throughput

---

examples/posix_spawn/filesystem/Makefile
examples/posix_spawn/filesystem/hello/Makefile
examples/posix_spawn/filesystem/redirect/Makefile

In stm32f4discovery:posix_spawn and lc823450-xgevk:posix_spawn parallel build,
it failed since apps/examples/posix_spawn/filesystem/romfs/hello is not available
which is needed by examples/posix_spawn/filesystem/symtab.c.
Change-Id: I588317396f8e3ca4d69d4ec8db8ccad219207048

examples/posix_spawn: update dependency to fix parallel build break

---

graphics/nxglyphs/Kconfig

to avoid warning: symbol value '' invalid for NXGLYPHS_BACKGROUNDCOLOR
Change-Id: I56e83a88b41d26a6833131a8dc89afe0dcf25d96

Set NXGLYPHS_BACKGROUNDCOLOR default value

---

system/zmodem/zm_state.c

fix message typo on system/zmodem/zm_state.c

---

examples/sendmail/Kconfig
examples/sendmail/sendmail_main.c
netutils/smtp/Kconfig
netutils/smtp/smtp.c
system/zmodem/zm_state.c

The sendmail example hasn't been used in years.  I am not sure it was ever debugged.  It is so old that it still expects hand editted .config files.  As a result, all of the configuration settings were missing from the Kconfig file.
This commit adds the missing apps/examples/sendmail configuration settings so that the example at least builds.  I cannot test it because I have no smtp server that I am willing to spam.
This configuration also adds missing configuration dependencies and runs the C files in apps/examples/sendmail and apps/netutils/smtp through nxstyle.
This commit resolves an issue reported by surya prakash rased in the Google group:  https://groups.google.com/forum/#!topic/nuttx/idr-M164Y24

Add configuration settings for apps/examples/sendmail.

---

wireless/gs2200m/gs2200m_main.c

- This is an additional PR (please see https://github.com/apache/incubator-nuttx/pull/171)
- This PR only affects the gs2200m daemon and typically for congested network or receiver window size is zero cases.
- To test this PR, https://github.com/apache/incubator-nuttx/pull/171 must be used.

wireless: gs2200m: Fix sendto_request() in gs2200m_main.c

---

platform/dummy/Make.defs

On some platforms like macOS, we can't create an empty archive.

Fix a build on macOS

---

examples/hello/hello_main.c

- The hello app now shows cpu index when running in SMP mode.
- This PR only affects the hello app.
- I only tested the app with Sony Spresense in SMP/non-SMP modes.

examples: hello: Show CPU index when running in SMP mode

---

examples/userfs/userfs_main.c

Fixes warning:
CC:  userfs_main.c
userfs_main.c:182:3: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
ufstest_truncate,
^
userfs_main.c:182:3: note: (near initialization for ‘g_ufstest_ops.truncate’)

apps/examples/userfs/userfs_main.c:  Fix warning

---

netutils/ftpd/ftpd.c
netutils/netlib/netlib_listenon.c

Change-Id: I24990bbec8cc4d6d0f06899bec45c575dd35b77f

Remove all CONFIG_NET_HAVE_REUSEADDR guard

---

examples/elf/tests/task/task.c

-  Increase stack size for task test from 512B to 2KB to avoid stack corruption
-  This PR only affects a task test in apps/examples/elf
- Test program passed on Sony Spresense board

apps: elf: Fix stack corruption in task test

---

wireless/gs2200m/gs2200m_main.c

The ioctl doesn't return why it failed.
It might or might not be a transient failure.
In my environment, gs2200m often returns the following for AT+WA.
It usually works after a few retries.
[   12.110000] _parse_pkt_in_s1: +++++ 0:(msize=19, msg=WLAN CONNECT ERROR|)
[   12.110000] _parse_pkt_in_s1: +++++ 1:(msize=6, msg=ERROR|)

gs2200m: Retry indefinately on GS2200M_IOC_ASSOC failure

---

netutils/netlib/netlib_listenon.c
wireless/gs2200m/gs2200m_main.c

As commented [1] all the code guarded by `CONFIG_NET_HAVE_REUSEADDR` was dead code.
The pull request [2] made some of it back to life to "undead" code, that raises an error always in `netlib_listenon()`
This fix that by lowering it as a warning in netlib and `DEBUGASSERT` in `gs2200m` command.
[1] https://github.com/apache/incubator-nuttx-apps/pull/45#discussion_r374093618
[2] https://github.com/apache/incubator-nuttx-apps/pull/47/files

Fix error about netlib and gs2200m

---

netutils/telnetd/telnetd_daemon.c

Recent change from Xiao Xiang enabled the SO_REUSEADDR socket option unconditionally.  This, of course, causes link time failures if socket options are not enabled:
apps/netutils/telnetd/telnetd_daemon.c:182: undefined reference to 'setsockopt'.
Observed during build testing with configuration rddrone-uavcan144:nsh

apps/netutils/telnetd:  Fix undefined reference to setsockopt.

---

wireless/gs2200m/gs2200m_main.c

Eliminate warning:
gs2200m_main.c:  In function 'gs2200m_loop':
gs2200m_main.c:1416:1:  warning: label 'errout' defined but not used [-Wunused-label]

apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning

---

examples/elf/tests/mutex/mutex.c
examples/elf/tests/pthread/pthread.c

- Fix warnings such as "warning: cast from pointer to integer of different size"
- This PR only affects apps/examples/elf.
- Tested with Sony Spresense (armv7-m 32bit) and K210 (RISC-V RV64GC)

examples: elf: Fix warnings when compiled for RISC-V 64bit

---

examples/elf/elf_main.c

As we know where the binaries are, there's little point
to use CONFIG_PATH_INITIAL.

examples/elf: Don't bother to honor CONFIG_PATH_INITIAL

---

examples/elf/tests/mksymtab.sh
examples/module/drivers/mksymtab.sh
examples/posix_spawn/filesystem/mksymtab.sh
examples/sotest/lib/mksymtab.sh

As it seems GNU-find only.  macOS doesn't have it.
-perm is in POSIX and should be more widely available.

mksymtab.sh: Avoid using find -executable

---

examples/elf/elf_main.c

If an external file system is used but is not mounted by the the ELF example, then a compilation error will occur.  This configuration problem has existed for a long time but was unmasked by a recent PR.  In the failure mode, CONFIG_EXAMPLES_ELF_FSTYPE would not be defined because it depends on CONFIG_EXAMPLES_ELF_FSMOUNT which is not defined.  The resulting mountpoint, MOUNTPT, would therefore be left in an invalid state.  Previous changes to conditional logic now allowed setenv() to run and to attempt to set the PATH variable to MOUNTPT, causing a compile time failure like this:
CC:  elf_main.c
elf_main.c: In function 'elf_main':
elf_main.c:113:32: error: expected ')' before 'CONFIG_EXAMPLES_ELF_FSTYPE'
^~~~~~~~~~~~~~~~~~~~~~~~~~
elf_main.c:364:18: note: in expansion of macro 'MOUNTPT' …

apps/examples/elf:  Correct mount point configuration error.

---

testing/fstest/fstest_main.c

testing/fstest/fstest_main.c: Eliminate a warning found during the build

---

Make.defs

- When an application is built as a loadable app, the application name should not be shown in the builtin app list (i.e. apps/builtin/buitlin_list.h) This PR does not create .bdat as well as .pdat if an application is built as a loadble.
- This PR affects application build for both builtin and loadable.
-  I checked this PR with spresense:rndis and spresense:wifi which include both builtin apps and loadable apps.

Make.defs: Fix to exclude loadable apps from builtin app list

---

.gitignore
Application.mk
Make.defs
Makefile

Use flock to serialize ar steps to avoid parallel build break
sometimes.
Change-Id: I3a916b3b27422cdb6d718f7d554361565457fa08

build: Use flock to serialize ar steps as workaround

---

examples/usrsocktest/usrsocktest_block_recv.c
examples/usrsocktest/usrsocktest_noblock_recv.c

- This PR fixes a part of usrsocktest errors. (i.e. errors in NoBlockRecv and BlockRecv)
- Actually, the test cases checked sockaddr_in values which contain padding field, however, the field should be ignored because it contains random values.
- This PR affects a usrsocktest application only.
- There still remain errors and need more investigation.
- I tested this PR with spresense:wifi which I added usrsocktest application.

Fix usrsocktest errors

---

nshlib/nsh_parse.c

In the case of enable the BUILTIN_APPS/FILE_APPS at the same
time, try the builtin list first to ensure that the relevant
configuration(stacksize, priority) can be set normally.
Change-Id: Ib99b39f884dfc651f4e47481d366a27ff984717f

nsh/parse: try the builtin configuration first

---

Application.mk
Directory.mk
Makefile

This reverts commit 52222cb020c70f14b2ff766c96da87c3c4bfd32c.
This broke the build.
To reproduce
For apps and nuttx `git fetch nuttx`
For apps and nuttx `git checkout master`
For apps and nuttx `git reset -hard nuttx/master`
`make distclean`
`./tools/configure.sh  imxrt1060-evk:nsh`
`make oldconfig`
`make`
```
Leaving directory '/home/david_s5/src/PX4/repos/mainline/NuttX/apps/platform'
arm-none-eabi-ar rcs  /home/david_s5/src/PX4/repos/mainline/NuttX/apps/libapps.a  make[1]: Entering directory '/home/david_s5/src/PX4/repos/mainline/NuttX/apps' make[2]: Entering directory '/home/david_s5/src/PX4/repos/mainline/NuttX/apps/nshlib' /home/david_s5/src/PX4/repos/mainline/NuttX/apps/nshlib/nsh_init.home.david_s5.src.PX4.repos.mainline.NuttX.apps.nshlib.o …
```

Revert "Avoid calling ARCHIVE in multiple places"

---

platform/Makefile

Remove the additional unlink to fix errors in parallel build as below.
cc1: fatal error: ./board/dummy.c: No such file or directory

Remove the additional UNLINKDIR to fix parallel build break

---

examples/tcpblaster/Kconfig
examples/tcpblaster/Makefile
examples/tcpblaster/README.txt
examples/tcpblaster/tcpblaster.h
examples/tcpblaster/tcpblaster_client.c
examples/tcpblaster/tcpblaster_server.c

* Improves reporting with timestamp, group count, and clarified bandwidth (changes message that incorrectly shows Kb [kilobits] to KB [kilobytes])
* Adds group configuration (was hardcoded at 50 buffers per send; this is now configurable)
* Adds README that shows how to configure and run
* None if you don't use tcpblaster
* tcpblaster is now more configurable and has clearer reporting that allows for hang-detection on long runtimes
* Manual on the simulator, SAMA5D3-Xplained (SAMA5D36), and Linux.
* Run tcpblaster as per the README

tcpblaster reporting and documentation improvements

---

examples/discover/discover_main.c

- This PR fixes compilation errors in discover_main.c
-  This PR affects examples/discover apps only
- This PR was tested with spresense:wifi by adding following configs
+CONFIG_NSH_NETINIT=n
+CONFIG_EXAMPLES_DISCOVER=y
+CONFIG_EXAMPLES_DISCOVER_DHCPC=y

examples: discover: Use htonl() instead of HTONL() in discover_main.c

---

Make.defs

It was necessary for PROTECTED build.
This reverts commit 4ee39e208048f075860179a0a2b60c3a651cf16e.

Revert "Remove libapps.a from LDLIBS"

---

examples/ipforward/ipforward.c

In IP Forwarding application for IPv4, 
the function 'net_ipv4addr_hdrcopy(dest,src) - (Path: nuttx/include/nuttx/net/ip.h),' 
expects a pointer for copying source IP to destination IP.
But in the application (Path: apps/examples/ipforward/ipforward.c), the value is passed directly instead of the address of the parameters which creates the issue.
The issue is rectified by the above fix.

IP Header issue for IPv4 fixed

---

testing/ostest/cond.c

- This PR adds workaround for SMP in cond.c to avoid error messages in cond_test.
- Only ostest (actually cond_test) will be affected.
-  I tested this PR with spresense:smp (Cortex-M4F in dual core mode), maix-bit:smp (RV64GC in dual core mode) and sabre-6quad:smp (Cortex-A9 in quad core mode).

testing: ostest: Add workaround for SMP in cond.c

---

testing/ostest/cond.c

- This PR will fix a warning in cond.c for non-SMP configurations.
cond.c: In function 'thread_signaler':
cond.c:184:5: warning: "CONFIG_SMP_NCPUS" is not defined, evaluates to 0 [-Wundef]
184 | #if CONFIG_SMP_NCPUS > 1
|     ^~~~~~~~~~~~~~~~
- Only ostest (actually cond_test) will be affected.
- I tested this PR with both  spresense:smp and spresense:wifi (non-SMP).

testing: ostest: Fix a warning in cond.c for non-SMP configurations.

---

.github/workflows/main.yml

Github action CI workflow steps as below:
1. Use docker container with build essential tools preinstalled
2. nxstyle check pull request with checkpatch.sh
3. Call testing cibuild.sh to do jobs matrix check builds
Now split full testlist into sim/mips-riscv-x86/arm01~arm15 totally 17 jobs to do parallel builds.
All the jobs could be finished in half an hour at most. We could reduce the build time later by refine the configs in each job.
Also note that the pull request check is by default whole file check.
For example, refer to the check build in my own fork:
https://github.com/liuguo09/incubator-nuttx-apps/pull/3/checks

Initial checkin nuttx-apps github action CI workflow

---

netutils/netinit/netinit.c

Change-Id: If82ab372e552205c8ae09068f0b19c710a6345ba

netinit: Unregister notification at the end in netinit_monitor

---

examples/tcpblaster/tcpblaster_client.c
examples/tcpblaster/tcpblaster_server.c

tcpblaster_server.c: In function 'tcpblaster_server':
tcpblaster_server.c:256:71: warning: passing argument 1 of 'localtime' from incompatible pointer type [-Wincompatible-pointer-types]
strftime(timebuff, 100, "%Y-%m-%d %H:%M:%S.000", localtime (&curr));
^
In file included from tcpblaster_server.c:50:0:
/usr/include/time.h:123:19: note: expected 'const time_t * {aka const long int *}' but argument is of type 'struct timespec *'
extern struct tm *localtime (const time_t *__timer) __THROW;
^~~~~~~~~
tcpblaster_client.c: In function 'tcpblaster_client':
tcpblaster_client.c:230:71: warning: passing argument 1 of 'localtime' from incompatible pointer type [-Wincompatible-pointer-types]
strftime(timebuff, 100, "%Y-%m-%d %H:%M:%S.000", localtime (&curr));
^
Signed-off-by: Xiang Xiao …

examples/tcpblaster: Fix the nightly build warning

---

examples/elf/Makefile
examples/elf/tests/Makefile

- This PR fixes build errors in examples/elf in parallel build.
- I applied the same logic in examples/posix_spawn/Makefile which adds an explicit context:: target.
- Also, I modified tests/Makefile to avoid compiling incomplete symtab.c
- This PR affects examples/elf only.
- I tested this PR for maix-bit:elf configuration with -j1 to -j24 options.

Fix parallel buid errors in examples/elf

---

.github/workflows/main.yml

As discussion in https://github.com/apache/incubator-nuttx/pull/549 shows,
update github action workflow to let build jobs do not depend on nxstyle
check job in order to make sure each PR (including some nxstyle waiving cases)
be built at least.

Update workflow to let build jobs do not depend on check nxstyle job

---

examples/posix_spawn/filesystem/Makefile

During generating symtab.c, compile seqeuence would start with
incomplete symtab.c. This change will fix such a situation.

examples/posix_spawn: Fix parallel build errors at link time

---

Makefile
examples/elf/tests/Makefile
examples/posix_spawn/filesystem/Makefile

Makefile: remove context dependency to avoid apps context build twice
In nuttx pass1dep and pass2dep builds, context firstly would be built once.
It then call 'make -C apps depend' which would trigger the context built twice.
There is race condition between symtab.c generated by mksymtab.sh in second time
and compiling symtab.c in parallel build. So remove context dependency for apps
depend to make sure context build only one time for apps.
Parallel build break logs as below:
/home/jenkins/jenkins-slave/workspace/NuttX-Nightly-Build/apps/examples/elf/elf_main.c:357: undefined reference to `g_elf_nexports'
riscv64-unknown-elf-ld: /home/jenkins/jenkins-slave/workspace/NuttX-Nightly-Build/apps/examples/elf/elf_main.c:357: undefined reference to `g_elf_exports'
make[1]: *** [nuttx] Error 1 …

Nightly parallel build fix for elf/posix_spawn/module build break

---

examples/module/drivers/Makefile

In parallel build, for example maix-bit:module config, it reports:
nm: 'a.out': No such file
This is caused by FSROOT not populated with chardev when symtab.c
generated. So update SYMTAB_SRC dependency to fix it.
Change-Id: I5bb5d17db41f3bba98ae70a2acdd2ec594736611

example/module: update SYMTAB_SRC dependency to fix FSROOT not populated

---

examples/elf/Makefile
examples/elf/tests/Makefile
examples/elf/tests/errno/Makefile
examples/elf/tests/hello/Makefile
examples/elf/tests/helloxx/Makefile
examples/elf/tests/longjmp/Makefile
examples/elf/tests/mutex/Makefile
examples/elf/tests/pthread/Makefile
examples/elf/tests/signal/Makefile
examples/elf/tests/struct/Makefile
examples/elf/tests/task/Makefile
examples/module/Makefile
examples/module/drivers/Makefile
examples/module/drivers/chardev/Makefile
examples/nxflat/Makefile
examples/nxflat/tests/Makefile
examples/posix_spawn/Makefile
examples/posix_spawn/filesystem/Makefile
examples/posix_spawn/filesystem/hello/Makefile
examples/posix_spawn/filesystem/redirect/Makefile
examples/sotest/Makefile
examples/sotest/lib/Makefile
examples/sotest/lib/modprint/Makefile
examples/sotest/lib/sotest/Makefile
examples/thttpd/Makefile
examples/thttpd/content/Makefile.binfs
examples/thttpd/content/Makefile.nxflat
examples/thttpd/content/hello/Makefile
examples/thttpd/content/tasks/Makefile

1.Remove build target to avoid build and install run parallelly
2.Invoke the sub Makefile just before the parent source code compile

examples: Fix the parallel build break

---

examples/tcpblaster/tcpblaster.h
examples/tcpblaster/tcpblaster_cmdline.c

@yamt This should address #150 
Please take a look.

examples/tcpblaster: When a host PC is used, take its implementation of hton/ntoh functions.

---

nshlib/nsh_command.c

Do not show the module application in built-in list

nsh/command: do not show the module application in built-in list

---

.github/workflows/build.yml

There is chance pull docker container failure in build jobs,
remove the additional pull docker container step may make it
more stable. Meanwhile, it also saves some time for build job.

CI: remove the additional pull docker container step

---

.github/workflows/build.yml

Namely the following commit:
commit 29f2116356451ee3430332df28b953f76da2d284
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Fri Apr 3 13:56:42 2020 +0900
Use testbuild -G ("git clean" instead of "make distclean")

CI: sync with testing repo

---

LICENSE

There were a few missing entries in the LICENSE file that were picked up with Fossology that this adds.  There was nothing that seemed to be needed to be added to the NOTICE file.

Include some missing entries from the LICENSE file

---

netutils/netlib/netlib_getessid.c
netutils/netlib/netlib_getifstatus.c
netutils/netlib/netlib_getmacaddr.c
netutils/netlib/netlib_setessid.c
netutils/netlib/netlib_setifstatus.c
netutils/netlib/netlib_setmacaddr.c

use the common one(NETLIB_SOCK_FAMILY)
Change-Id: Ifc255f82f169d3bb37604c49006361a40c9933d1

netlib: Remove AF_FAMILY and PF_FAMILY definition

---

examples/configdata/configdata_main.c
examples/elf/elf_main.c
examples/posix_spawn/spawn_main.c
examples/stat/stat_main.c
examples/usrsocktest/usrsocktest_main.c
graphics/nxwidgets/UnitTests/CButtonArray/cbuttonarray_main.cxx
graphics/nxwidgets/UnitTests/CCheckBox/ccheckbox_main.cxx
graphics/nxwidgets/UnitTests/CGlyphButton/cglyphbutton_main.cxx
graphics/nxwidgets/UnitTests/CGlyphSliderHorizontal/cglyphsliderhorizontal_main.cxx
graphics/nxwidgets/UnitTests/CImage/cimage_main.cxx
graphics/nxwidgets/UnitTests/CKeypad/ckeypad_main.cxx
graphics/nxwidgets/UnitTests/CLatchButtonArray/clatchbuttonarray_main.cxx
graphics/nxwidgets/UnitTests/CListBox/clistbox_main.cxx
graphics/nxwidgets/UnitTests/CProgressBar/cprogressbar_main.cxx
graphics/nxwidgets/UnitTests/CRadioButton/cradiobutton_main.cxx
graphics/nxwidgets/UnitTests/CScrollbarHorizontal/cscrollbarhorizontal_main.cxx
graphics/nxwidgets/UnitTests/CScrollbarVertical/cscrollbarvertical_main.cxx
graphics/nxwidgets/UnitTests/CSliderHorizonal/csliderhorizontal_main.cxx
graphics/nxwidgets/UnitTests/CSliderVertical/cslidervertical_main.cxx
netutils/thttpd/thttpd_alloc.c
system/composite/composite_main.c
system/usbmsc/usbmsc_main.c
system/zmodem/host/nuttx/compiler.h
testing/fstest/fstest_main.c
testing/nxffs/nxffs_main.c
testing/ostest/ostest_main.c
testing/ostest/sigev_thread.c
testing/ostest/sighand.c
testing/smart/smart_main.c

This is the companion to PR #766.  It removes the CONFIG_CAN_PASS_STRUCT option as recommended by Issue #620
NuttX PR #766 depends on PR being in place but not vice versa.  This PR should be merge-able without #766 and then PR #766 should also pass its checks.

Remove CONFIG_CAN_PASS_STRUCT

---

include/graphics/twm4nx/cwindow.hxx
interpreters/bas/bas.c
interpreters/bas/bas_fs.c
interpreters/bas/bas_token.c
nshlib/nsh_envcmds.c
nshlib/nsh_netcmds.c

src/cwindowfactory.cxx: In member function 'void Twm4Nx::CWindowFactory::redrawIcons(const nxgl_rect_s*)':
src/cwindowfactory.cxx:461:38: warning: 'iconPos.nxgl_point_s::y' may be used uninitialized in this function [-Wmaybe-uninitialized]
461 |           iconBounds.pt2.y = iconPos.y + iconSize.h - 1;
|                              ~~~~~~~~^
src/cwindowfactory.cxx:460:38: warning: 'iconPos.nxgl_point_s::x' may be used uninitialized in this function [-Wmaybe-uninitialized]
460 |           iconBounds.pt2.x = iconPos.x + iconSize.w - 1;
|                              ~~~~~~~~^
nsh_netcmds.c:424:20: warning: 'nsh_addrconv' defined but not used [-Wunused-function]
static inline bool nsh_addrconv(FAR const char *hwstr,
^
nsh_netcmds.c:446:20: warning: 'nsh_sethwaddr' defined but not used …

apps: Fix the nightly build warning

---

interpreters/bas/bas_program.c

bas_program.c:234:35: error: adding 'size_t' (aka 'unsigned long') to a string does not append to the string [-Werror,-Wstring-plus-int]
FS_putChars(chn, "        " + len);
~~~~~~~~~~~^~~~~
bas_program.c:234:35: note: use array indexing to silence this warning
FS_putChars(chn, "        " + len);
^
&          [    ]
1 error generated.

Fix bas_program.c build warning under macos

---

examples/lvgldemo/lv_test_theme_2.c
graphics/littlevgl/Makefile
graphics/littlevgl/lv_fix_warning.patch
interpreters/bas/bas_program.c

Backport #184 to releases/9.0

---

nshlib/nsh_altconsole.c
nshlib/nsh_consolemain.c
nshlib/nsh_script.c
nshlib/nsh_telnetd.c
nshlib/nsh_usbconsole.c

Fix the regression discuss here: https://github.com/apache/incubator-nuttx-apps/pull/185

Fix BOARDIOC_FINALINIT get skipped when CONFIG_NSH_ROMFSETC isn't enabled

---

.github/workflows/build.yml

Until the code base restore to the origin state after "make distclean"

Revert "build.yml: Remove -G from cibuild.sh command line"

---

include/netutils/webclient.h
netutils/ping/icmp_ping.c
netutils/ping/icmpv6_ping.c
netutils/webclient/webclient.c

Also wget state is now allocated in order to conserve stack space.

webclient: use getaddrinfo to get IPv4 addresses on dual stack systems

---

examples/mount/Kconfig
netutils/libcurl4nx/Kconfig

There were several places where default sector and buffer sizes of 2048 were changed to DEFAULT_TASK_STACKSIZE.  This is not correct.  This was noted by Xiao Xiang.

Fix errors from DEFAULT_TASK_SIZE change

---

examples/unionfs/Makefile

examples/unionfs: Remove [a|b]testdir.h in distclean

---

.github/workflows/build.yml

Use make distclean instead of git clean to do check build clean defaultly.

CI: Remove -G from cibuild.sh command line

---

wireless/bluetooth/btsak/btsak_security.c

Inspired by Abdelatif's find, here are other cases where /n was used when \n ws intended

wireless/bluetooth/btsak/btsak_security.c:  Fix newline character

---

examples/timer/Kconfig
system/readline/Kconfig

Remove the unnecessary BUILD_FLAT dependence from Kconfig

---

testing/ostest/prioinherit.c

In lowpri_thread if sem_wait fail nwaiting will not be set even
though the rest of the function uses it.  This is a failure
so really just handling the compiler warning with this.
Signed-off-by: Brennan Ashton <bashton@brennanashton.com>

Fix uninitialized variable warning in ostest

---

examples/bmi160/sixaxis_main.c
examples/charger/charger_main.c

examples: Remove the prefix of main from bmi160 and charger

---

.github/workflows/build.yml

Something change on the GitHub side that has broken credentials
between the the fetch and buld workflow steps.  There is no
way to tell the checkout action to only re-auth so we have it
checkout the repo again, but it will use what it already has.
In the future we can change fetch step to just compute the
target refs and store them in a script that we can call to
set the environment variables for the targets much like
this patch.

Restore Git Credentials on NuttX repo

---

netutils/usrsock_rpmsg/Kconfig
netutils/usrsock_rpmsg/Make.defs
netutils/usrsock_rpmsg/Makefile
netutils/usrsock_rpmsg/usrsock_rpmsg.h
netutils/usrsock_rpmsg/usrsock_rpmsg_client.c
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

This is a more suitable location
need work with https://github.com/apache/incubator-nuttx-apps/pull/234

Move usrsock_rpmsg from system to netutils folder

---

netutils/usrsock_rpmsg/Make.defs
netutils/usrsock_rpmsg/Makefile

Not all files were correctly modified when usrsock_rpmsg was moved from apps/system to apps/netutils.  Changes were overlooked in the Makefile and Make.defs file.
Should correct the PR check system which is failing on this problem.

netutils/usrsock_rpmsg:  Fix build failures

---

testing/ostest/Makefile
testing/ostest/ostest_main.c
testing/ostest/tls.c

A first step in implementing the user-space error is force TLS to be enabled at all times. It is no longer optional.
Risky all architectures are affected.
Not yet.

Remove CONFIG_TLS

---

builtin/exec_builtin.c
fsutils/mkfatfs/mkfatfs.c
fsutils/mksmartfs/mksmartfs.c
netutils/ftpc/ftpc_connect.c
netutils/ftpc/ftpc_login.c
netutils/netlib/netlib_autoconfig.c
netutils/tftpc/tftpc_get.c
netutils/tftpc/tftpc_put.c
netutils/webclient/webclient.c
nshlib/nsh_fileapps.c
platform/mikroe-stm32f4/mikroe_configdata.c
system/popen/popen.c
system/system/system.c

The normal assignment errno = errcode should work fine now.

Remove use of set_errno() from application code.

---

.github/workflows/check.yml

Use 'git diff $commits' as a whole patchset instead of 'git show $commits' to avoid checkpatch with duplicate error/warning logs sometimes and rename file not opened issue.

CI: use 'git diff $commits' as a whole patchset to do checkpatch

---

testing/ostest/Makefile
testing/ostest/ostest_main.c

After the redesign of pthread-specific data, CONFIG_NPTHREAD_KEYS is removed and replaced with CONFIG_TLS_NELEM

Rename CONFIG_NPTHREAD_KEYS to CONFIG_TLS_NELEM

---

testing/ostest/ostest_main.c

Replace the old NPTHREAD_KEYS with TLS_NELM.

testing/ostest/ostest_main.c: Replace the old NPTHREAD_KEYS with TLS_NELM

---

.github/workflows/check.yml

This reverts commit 9c4cdc5331c1989b9a82e392255e516b16a5a47b.
If one PR is on a former master code base, using 'git diff $commits' would result in
abnormal checkpatch report sometimes. So revert it anyway.

Revert "CI: use 'git diff $commits' as a whole patchset to do checkpatch"

---

netutils/dhcpd/Kconfig
netutils/dhcpd/dhcpd.c

netutils/dhcpd: correct the option header check
netutils/dhcpd: Fix the minor typo error

netutils/dhcpd: correct the option header check

---

system/netdb/netdb_main.c

Eliminate a simple "variable unused" warning.

system/netdb/netdb_main.c: Eliminate a warning when CONFIG_NETDB_HOSTFILE is not set.

---

examples/ftpc/ftpc_main.c

- This PR fixes a compile warning in ftpc_main.c if configuration is IPv4 only.
- Also fixes style violations.
- This PR affects ftpc only.
- Add CONFIG_EXAMPLES_FTPC=y to spresense:wifi then run configure.sh
- make EXTRAFLAGS="-Wno-cpp -Werror

examples: ftpc: Fix a compile warning for IPv4 only configuration

---

Application.mk
examples/elf/Makefile
examples/elf/elf_main.c
examples/elf/tests/.gitignore
examples/elf/tests/Makefile
examples/elf/tests/mkdirlist.sh
examples/module/Makefile
examples/module/drivers/.gitignore
examples/module/drivers/Makefile
examples/module/module_main.c
examples/nxflat/Makefile
examples/nxflat/nxflat_main.c
examples/nxflat/tests/.gitignore
examples/nxflat/tests/Makefile
examples/nxflat/tests/mkdirlist.sh
examples/nxflat/tests/mksymtab.sh
examples/posix_spawn/Makefile
examples/posix_spawn/filesystem/.gitignore
examples/posix_spawn/filesystem/Makefile
examples/posix_spawn/spawn_main.c
examples/sotest/Makefile
examples/sotest/lib/.gitignore
examples/sotest/lib/Makefile
examples/sotest/sotest_main.c
examples/thttpd/Makefile
examples/thttpd/content/.gitignore
examples/thttpd/content/Makefile.binfs
examples/thttpd/content/Makefile.nxflat
examples/thttpd/content/mksymtab.sh
examples/thttpd/thttpd_main.c

Update make dependency for elf/module/nxflat/posix_spawn/sotest/thttpd examples which make use of mksymtab.sh. This could avoid them built twice in 'make depend' and 'make all' which would result in file truncated build break. Now only build once by 'make all'.
Pass local nightly build

Update make dependency for elf/module/nxflat/posix_spawn/sotest/thttpd

---

tools/mksymtab.sh

Suppress apache nightly build find error msg as below:
find: '/home/jenkins/jenkins-slave/workspace/NuttX-Nightly-Build/apps/bin': No such file or directory

tools/mksymtab.sh: suppress 'find apps/bin' No such file or directory error msg

---

nshlib/nsh_parse.c

An important feature of ELF binaries for NSH is the capability to replace built-in applications with updated ELF applictions on a file system.  This works because of this ording in NSH:
- Load file from file system if possible
- If not, run built-in application if possible
- If not, run NSH command line command if possible
- If not, report that the command was not found
This critical behavior was broken by this commit:
commit 9a28ccf836c1b9f0eb5e1163964042eddc207697
Author: chao.an <anchao@xiaomi.com>
Date:   Fri Feb 21 09:54:47 2020 +0800
nsh/parse: try the builtin configuration first
In the case of enable the BUILTIN_APPS/FILE_APPS at the same time,
try the builtin list first to ensure that the relevant configuration
(stacksize, priority) can be set normally.
This commit breaks the …

apps/nshlib:  Restore correct load order for binaries.

---

nshlib/nsh_parse.c

Add some comments to nsh_parse.c emphasizing the reason that things are done in the order that they are.  Perhaps such comments will avoid similar breakage in the future.
None.. purely cosmetic and, hopefully, helpful to people in the future.
N/A

apps/nshlib/nsh_parse.c:  Add some comments.

---

wireless/gs2200m/gs2200m_main.c

- This PR fixes hardfault when read()/recvfrom() are called with length which is greater than 1500.
- Now it allocates a memory with requested size.
- This PR only affects gs2200m daemon. More specifically read()/recvfrom() are called from application.
- I tested this PR with wget on spresense:wifi by changing read size from 512 to 4096 in nsh_netcmds.c

wireless: gs2200m: Fix to receive a big packet

---

builtin/exec_builtin.c
nshlib/nsh_parse.c

nsh/parse: Try FILE_APPS first in the case of builtin
Bring back the BUILTIN_APPS / FILE_APPS calling sequence

nsh/parse: Try FILE_APPS first in the case of builtin

---

nshlib/Kconfig
nshlib/nsh_netcmds.c

##Summary
- This PR introduces CONFIG_NSH_WGET_BUFF_SIZE to customize the buffer size for wget command.
- This PR only affects wget command for nsh.
- I tested this PR with spresense:wifi

nshlib: Introduce CONFIG_NSH_WGET_BUFF_SIZE

---

system/nxplayer/Kconfig
system/nxplayer/nxplayer.c

- This PR introduces max host and file name for http url in nxplayer.c
- The default values are brought from webclient.h
- This PR only affects nxplayer. Specifically in case that http streaming is enabled.
- I tested this PR with spresense:wifi

system: nxplayer: Introduce max host and file name for http url

---

Application.mk

https://github.com/apache/incubator-nuttx-apps/pull/250 resulted in generated empty
Make.dep for SRCS with VPATH.
Test with sim:nsh config for apps/platform with board VPATH

Application.mk: fix generated empty Make.dep for SRCS with VPATH

---

netutils/ftpd/ftpd.c

- We noticed that ftpc on NuttX does not work with ftpd on NuttX.
- Finally I found that there is a bug in EPSV mode handling in ftpd.c
- It seems that IPv6 related code is OK, so I applied the same logic to IPv4.
- Also fixed style violations.
- This PR only affects ftpd in EPSV mode.
- We tested this PR with spresense:wifi
- One is running ftpc and the other is running ftpd.

netutils: ftpd: Fix EPSV mode in ftpd.c (IPv4 only)

---

Make.defs

Remove the duplicated MAKE_template and SDIR_template definitions since they go into nuttx/tools/Config.mk in https://github.com/apache/incubator-nuttx/pull/1102. 
Rerun check jobs once https://github.com/apache/incubator-nuttx/pull/1102 merged.

build: Remove some duplicated definitions

---

Application.mk

Update .depend dependency for SRCS with VPATH to avoid the generated symtab.c etc trigger built in make depend.

Application.mk: update .depend dependency for SRCS with VPATH

---

netutils/dhcpc/dhcpc.c

dhcpc: Don't use an uninitialized variable

dhcpc: Don't use an uninitialized variable

---

netutils/webclient/Kconfig
netutils/webclient/webclient.c

http -> https redirection is rather common. The old code was
just broken in that case.
Also, this commit is a step towards https support.
* Switch to netlib_parseurl
* Fix error propagation in wget_parseheaders
* Bail out on a redirect to a URL with unsupported scheme

webclient: Fix http -> https redirection

---

netutils/webclient/webclient.c

Instead of relying on indirect namespace pollutions.

webclient: include string.h for strlen

---

netutils/webclient/webclient.c

webclient: Check the return value of netlib_parseurl correctly

---

examples/lvgldemo/Kconfig
examples/lvgldemo/lvgldemo.c

Some touch screen don't need calibration,  so let the touch calibration as optional
No impact for current board configs, touch calibration is enabled by default
It tested with stm32f746g-disco and my custom board

examples/lvgldemo: Make touch calibration optional

---

system/nxrecorder/nxrecorder.c

- This PR fixes compile warnings in nxrecorder.c
- This PR affects nxrecorder only.
- I tested this PR with spresense:wifi (need to add nxrecorder to defconfig)

system: nxrecorder: Fix compile warnings in nxrecorder.c

---

examples/pca9635/pca9635_main.c

##Summary
The brightness struct name was changed in the OS driver, thus this example needs to follow suit.
This impacts only the pca9635 example.

examples/pca9635/pca9635_main.c: Change the brightness sturct's name.

---

LICENSE

apps/canutils/candump includes five third part files from VW that have a dual BSD-3/GPLv2 license.  This commits updates the LICENSE file to indicate this.
No functional change
N/A

LICENSE:  Update with candump

---

examples/bmp180/Kconfig
examples/bmp180/bmp180_main.c

Added support for BMP280 sensor to bmp180 app. Probably this app should be named differently eventually. 
Only extends support to existing app
Using BMP280 sensor on custom board.

bmp180: enable use for BMP280 as well

---

system/composite/composite.h

Composite app does not really need CDCACM driver enabled, it is just the usual case.
Extends functionality of composite app to more configurations 
Using composite USBDEV different than CDCACM

Remove the need to have CDCACM enabled for composite app

---

examples/pty_test/Kconfig
examples/pty_test/pty_test.c

This change allows the pty app to wait on the underlying serial device to appear. This is useful for the case where this device is actually a USB serial device emulator which may be opened only when the USB cable is plugged. This allows for maintaining the serial console on the hard serial device but to open another console on a USB device on boot (using a boot script which runs "pts").
Adds an optional feature.
Tested with CDCACM device and an NSH init script calling "conn" (connect composite device) and "pts". With the feature enabled, once the cable is connected the console can be used.

PTY: add option to wait on serial device

---

system/nxrecorder/nxrecorder.c

- This PR lets nxrecorder create a new file with O_TUNC option.
- This PR affects nxrecorder only.
- I tested this PR with spresense:wifi configuration.
```
nsh> nxrecorder
nxrecorder> device /dev/audio/pcm_in1
nxrecorder> recordraw /mnt/sd0/rec0001.raw
nxrecorder> stop
```

system: nxrecorder: Add O_TRUNC when creating a file

---

system/sched_note/note_main.c

Add support for decoding interrupt and system call instrumentation
None other than to system/sched_note/note_main.c.
Tested with sim:nsh

system/sched_note/note_main.c:  Add interrupt/syscall call decode.

---

Application.mk

apps/makefile/implicit rules: completion the obj path
Depends  on https://github.com/apache/incubator-nuttx/pull/1290
```
./tools/configure.sh arty_a7/nsh
make -j16
```

 apps/makefile/implicit rules: completion the obj path

---

nshlib/Kconfig

This is a bad change.  It has been show to cause an increase in size by around 2.3Kb in minimal configurations that cannot tolerate that massive size increase.
This reverts commit 4adb83c754500cfebe4c24a498eb4139e3ff8866.
This will correct the behavior of the configuration bying restoring what is was in NuttX-9.0 
Size problem demonstrated on stm32f4discovery:nsh

Revert "nshlib: remove the dependency of date on RTC"

---

nshlib/Kconfig

This is a bad change.  It has been show to cause an increase in size by around 2.3Kb in minimal configurations that cannot tolerate that massive size increase.
This is a backport of #307

[Backport-307] Revert "nshlib: remove the dependency of date on RTC"

---

Application.mk

Make programs under apps/bin executable since tools/mksymtab.sh called with
'find $dir -type f -perm -a=x 2>/dev/null'. So generate symtab file rightly.
Verify with sim:loadable config. Or running nuttx with sim loadable config got stuck.

Make programs under apps/bin executable to generate symtab file rightly

---

Application.mk

This is a backport of PR #303 
Make programs under apps/bin executable since tools/mksymtab.sh called with
'find $dir -type f -perm -a=x 2>/dev/null'. So generate symtab file rightly.

[Backport-303] Make programs under apps/bin executable to generate symtab file rightly

---

testing/cxxtest/cxxtest_main.cxx

cxxtest: Check CONFIG_CXX_EXCEPTION instead of CONFIG_UCLIBCXX_EXCEPTION because the user may use libcxx which just define CONFIG_LIBCXX_EXCEPTION
No functionality change.

cxxtest: Check CONFIG_CXX_EXCEPTION instead of CONFIG_UCLIBCXX_EXCEPTION

---

examples/mld/mld_main.c
examples/netloop/lo_main.c
netutils/dhcpc/dhcpc.c

net/sockopt: change the socket option style from Linux to BSD
```
Linux Programmer's Manual
...
IP(7)
...
NOTES
...
Using the SOL_IP socket options level isn't portable;
BSD-based stacks use the IPPROTO_IP level.
```
CI check is enough.

net/sockopt: change the socket option style from Linux to BSD

---

nshlib/nsh_fscmds.c

since NuttX kernel support really support symlink not link.
Note: link equal symlink now because the hard link doesn't support yet
No, since link equal symlink in the current implementation

nshlib: Call symlink if user pass -s for ln command

---

Makefile

make/import: add incdir into import build 
export build break by commit https://github.com/apache/incubator-nuttx/commit/5555070fc3320d91876391bc24f0a7283d31841c
make export
Depends on: https://github.com/apache/incubator-nuttx/pull/1332
Before patch:
```
$ cd $(NUTTX_DIR)
$ ./tools/configure.sh stm32f429i-disco:nsh
$ make export -j12
$ cd $(APPS_DIR)
$ ./tools/mkimport.sh -x $(NUTTX_DIR)/nuttx-export-9.1.0.zip
$ make import -j12
...
/bin/sh: 1: /home/archer/code/apps/import/tools/incdir: not found
/bin/sh: 1: /home/archer/code/apps/import/tools/incdir: not found
/bin/sh: 1: /home/archer/code/apps/import/tools/incdir: not found
/bin/sh: 1: /home/archer/code/apps/import/tools/incdir: not found
/bin/sh: 1: /home/archer/code/apps/import/tools/incdir: not found
/bin/sh: 1: …
```

make/import: add incdir into import build 

---

import/Makefile

import: add hex/raw binary support
make export
After patch:
```
$ make import -j12
...
LD: nuttx
CP: nuttx.hex
CP: nuttx.bin
make[1]: Leaving directory '/home/archer/code/apps/import'
```

import: add hex/raw binary support

---

examples/elf/Kconfig
examples/elf/tests/helloxx/Makefile
testing/README.txt
testing/cxxtest/README.txt

apps: Make c++ examples/testing work with both uClibc++ and libcxx

---

examples/README.txt
examples/helloxx/helloxx_main.cxx

since this config doesn't appear inside examples/helloxx/Kconfig anymore and
there is any c++ compiler can't construct the stack object as far as I know
No, since the related code path never activate.

example/helloxx: Remove EXAMPLES_HELLOXX_NOSTACKCONST

---

Makefile
import/Make.defs
import/Makefile
tools/mkimport.sh

1. make/import: support import zip use relative path
```
mkimport.sh failure if using relative path:
$ ./tools/mkimport.sh -x ../incubator-nuttx/nuttx-export-9.1.0.zip
unzip:  cannot find or open ../incubator-nuttx/nuttx-export-9.1.0.zip, ../incubator-nuttx/nuttx-export-9.1.0.zip.zip or ../incubator-nuttx/nuttx-export-9.1.0.zip.ZIP.
ERROR: unzip ../incubator-nuttx/nuttx-export-9.1.0.zip failed
```
2. make/import: copy the exported buildin registers
`copy the exported buildin registers to avoid symbols dropping on import build`
3. make/import: add post build support
`support post processing after binary install`
4. make/import: move the binary install to the top Makefile
`move the binary install to the main Makefile to support link extra libraries`
make import
Depends on: …

make import: enhance make import

---

system/zmodem/host/nuttx/compiler.h

follow up the kernel side change
No function chnage since host binary don't use these variables.

zmodem: Remove CONFIG_HAVE_INLINE from compiler.h

---

testing/cxxtest/cxxtest_main.cxx

cxxtest_main.cxx: In function ‘void test_rtti()’:
cxxtest_main.cxx:199:3: warning: deleting object of polymorphic class type ‘Base’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
199 |   delete a;
|   ^~~~~~~~
cxxtest_main.cxx:200:3: warning: deleting object of polymorphic class type ‘Base’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
200 |   delete b;
No.

testing/cxxtest: Fix the compiler warning

---

testing/ostest/mqueue.c

SIGKILL was captured and call nxsig_abnormal_termination,
which kills the children when SIGCHLD was set. 
Solution: change SIGKILL to SIGUSR1.

ostest: fix assert when open CONFIG_SIG_DEFAULT

---

examples/mount/mount_main.c
interpreters/ficl/src/nuttx.c
nshlib/nsh_mntcmds.c

Please ignore nxstyle false alarm:
```
apps/interpreters/ficl/src/nuttx.c:56:6: error: Mixed case identifier found
```

Fix nxsytle warning

---

netutils/telnetd/telnetd_daemon.c

Should only memset ipv6 part of socket address(exclude famliy and port field)

telnetd: Fix the buffer overflow

---

examples/nrf24l01_term/nrf24l01_term.c

Please ignore the false nxstyle alarm:
```
apps/examples/nrf24l01_term/nrf24l01_term.c:129:13: error: Mixed case identifier found
```

examples/nrf24l01_term: Fix the nxsytyle warning

---

netutils/ntpclient/Kconfig
netutils/ntpclient/ntpv3.h

- I found that some NTP servers did not respond with ntpclient
- Finally, I found that authentication headers in NTP packet are not implemented correctly, so some NTP servers could not send a response.
- This PR introduces to CONFIG_NETUTILS_NTPCLIENT_WITH_AUTH to implement authentication in the future. (the current default value is false)
- This PR affects ntpclient.
- I tested this PR with CONFIG_NETUTILS_NTPCLIENT_SERVER="162.159.200.1"

netutils: netclient: Introduce CONFIG_NETUTILS_NTPCLIENT_WITH_AUTH

---

.gitignore
Application.mk
Directory.mk
Make.defs
Makefile

This PR has 2 main commits.  The first one related to #340.  It prevents the `preconfig` target from executing in application directories that don't actually need any pre-configuration.
The second one limits the execution scope of `clean` and `distclean` to the folder that we know we have built, instead of recursively going through every sub-directory.
The `preconfig` commit reduces configuration time.
The `clean` and `distclean` commit reduces cleaning time.
Both remove a bunch of unnecessary output.
The whole `./tools/configure.sh make make distclean` procedure shall be faster.
A bunch of configurations with different examples, hello, helloxx, ostest, etc.

Don't preconfig, clean or distclean when it's not necessary

---

Directory.mk

The subdirectories' clean and distclean targets need to be unique to avoid the "overriding recipe for target" warning.

Directory.mk: The subdirectories' clean and distclean targets need to be unique.

---

testing/fatutf8/Kconfig
testing/fatutf8/Make.defs
testing/fatutf8/Makefile
testing/fatutf8/fatutf8_main.c

Testing for CONFIG_FAT_LFN_UTF8, because nsh doesn't accept characters outside 0x7f
--
--

Testing for UTF8 support for FAT Filesystem.

---

examples/usrsocktest/usrsocktest_basic_connect.c
examples/usrsocktest/usrsocktest_basic_daemon.c
examples/usrsocktest/usrsocktest_basic_getsockname.c
examples/usrsocktest/usrsocktest_basic_getsockopt.c
examples/usrsocktest/usrsocktest_basic_send.c
examples/usrsocktest/usrsocktest_basic_setsockopt.c
examples/usrsocktest/usrsocktest_block_recv.c
examples/usrsocktest/usrsocktest_block_send.c
examples/usrsocktest/usrsocktest_chardev.c
examples/usrsocktest/usrsocktest_daemon.c
examples/usrsocktest/usrsocktest_main.c
examples/usrsocktest/usrsocktest_multi_thread.c
examples/usrsocktest/usrsocktest_noblock_connect.c
examples/usrsocktest/usrsocktest_noblock_recv.c
examples/usrsocktest/usrsocktest_noblock_send.c
examples/usrsocktest/usrsocktest_nodaemon.c
examples/usrsocktest/usrsocktest_remote_disconnect.c
examples/usrsocktest/usrsocktest_wake_with_signal.c
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
wireless/gs2200m/gs2200m_main.c

- Add flags to usrsock daemons
- Fix coding style
usrsock drivers can be process recv() flags.
Tested by spresense:wifi

Add flags to usrsock daemons

---

interpreters/duktape/Makefile

Fix error line wrap for download URL in Makefile.
Tested on sim & stm32f746g-disco.

interpreters/duktape: Fix tarball download url

---

interpreters/duktape/duk_cmdline.patch

Fix build warning for sim, the duk_config.h check the platform flags and apply them for different build, 
it treat NuttX sim platform as Linux, then cause some build warning.
sim:duktape
Tested on sim.

interpreters/duktape: Fix warning for sim

---

netutils/dhcpd/dhcpd.c

##Summary
netutils/dhcpd: correct the member name
build break if enable CONFIG_DEBUG_NET_ERROR
enable CONFIG_DEBUG_NET_ERROR and compile pass

netutils/dhcpd: correct the member name

---

interpreters/duktape/duk_cmdline.patch

See #355 
sim:duktape on macOS

interpreters/duktape: Fix build warning for sim on macOS

---

nshlib/nsh_parse.c

- Fix memory corruption when pthread_create() failed in nsh_execute()
- nsh builtin command execution in background with errors
- Tested with hifive1-revb:nsh
- Set CONFIG_MAX_TASKS=4
- Run 'sleep 1000 &' in 3 times will cause pthread_create error
- Run free, ps command

nshlib: Fix memory corruption in nsh_parse.c

---

examples/lvgldemo/Makefile
graphics/lvgl/Kconfig
graphics/lvgl/Makefile
interpreters/duktape/Makefile

* Minor change for makefile, add duktape's builtin console/print/alart module support.
* Make lvgl version configurable by kconfig
Duktape interpreter
Tested on stm32f746g-disco & sim.

interpreters/duktape: Add console/print/alart support

---

netutils/ftpc/ftpc_transfer.c

forget in commit efeb1d10b1bbc43255406f8ab7d32284357e2211

ftpc_transfer.c:667:15: Fix error: ‘argc’ undeclared

---

system/libuv/.gitignore
system/libuv/0001-initial-libuv-port-to-nuttx.patch
system/libuv/Make.defs
system/libuv/Makefile
system/libuv/libuv/Kconfig
system/libuv/libuv/Make.defs
system/libuv/libuv/Makefile
system/libuv/tests/Kconfig
system/libuv/tests/Make.defs
system/libuv/tests/Makefile
system/libuv/tests/runner-nuttx.c
system/libuv/tests/runner-nuttx.h
system/libuv/tests/test_main.c

Summary
From http://docs.libuv.org/en/v1.x/
"libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily developed for use by Node.js, but it’s also used by Luvit, Julia, pyuv, and others."
Initial port to NuttX from libuv v1.38.1.
Impact
None, disabled by default (CONFIG_LIBUV)
Testing
Select CONFIG_LIBUV and CONFIG_LIBUV_UNIT_TESTS. Then run "libuvtest" in nsh.
All CONFIG_LIBUV_* options must be enabled for all the tests to pass.
Validated on "sim" and "stm32f4discovery" targets.

system: add libuv port for NuttX

---

examples/nxterm/nxterm_main.c
examples/pty_test/pty_test.c
include/system/readline.h
nshlib/nsh.h
nshlib/nsh_altconsole.c
nshlib/nsh_console.c
nshlib/nsh_console.h
nshlib/nsh_consolemain.c
nshlib/nsh_session.c
nshlib/nsh_stdsession.c
nshlib/nsh_system.c
nshlib/nsh_timcmds.c
nshlib/nsh_usbconsole.c
system/nsh/nsh_main.c

See the dissussion here: https://github.com/apache/incubator-nuttx/pull/1597
Please ignore the false nxstyle alarm:
```
nshlib/nsh_timcmds.c:115:35: error: Multiple data definitions
```

nsh: Accept the command line arguments like sh

---

nshlib/nsh_command.c
nshlib/nsh_fscmds.c

Remove NSH_HAVE_WRITABLE_MOUNTPOINT define as it is not defined anymore (see commit 74c506b4d16bb91802da5f3f5f64a5fb5f63c78e)

nshlib: remove NSH_HAVE_WRITABLE_MOUNTPOINT to enable mkrd again

---

interpreters/duktape/.gitignore
interpreters/duktape/Make.defs
interpreters/duktape/Makefile
interpreters/duktape/duk_cmdline.patch

This is useful for using duktape as a library.
None
Tested on sim & stm32

interpreters/duktape:Add duktape to global search path

---

wireless/bluetooth/btsak/btsak.h
wireless/bluetooth/btsak/btsak_main.c

Update btsak application to use the new BTPROTO_L2CAP `sockaddr_l2` struct instead of the generic one we had for Bluetooth before.
No change in functionality.
Tool works the same as before.

Bluetooth: Use the new l2cap socket address type

---

interpreters/quickjs/.gitignore
interpreters/quickjs/Kconfig
interpreters/quickjs/Make.defs
interpreters/quickjs/Makefile
interpreters/quickjs/quickjs.patch

Add QuickJS support with std/os library, and full function `qjs` application as desktop platform.
None
Tested on sim & stm32f746g-disco

interpreters/quickjs: Initial QuickJS support

---

.github/workflows/check.yml

Previously there were issues with how we identified changed files for running checkpatch.  Internally this is now handled with `git diff` instead of `git show`.  This also means we simplify the computing of the commit range.  This aligns with the changes in the OS repo https://github.com/apache/incubator-nuttx/pull/1706
Also Issue https://github.com/apache/incubator-nuttx/issues/1637

CI: Fix check patch to handle renames / deletes

---

system/readline/readline_common.c

system/readline: Fix the stack overflow when application name is too long

---

.github/workflows/build.yml

Same change as https://github.com/apache/incubator-nuttx/pull/1762 applied here
CI
CI itself

CI: don't cache sources, use artifacts only

---

.github/workflows/build.yml

Follow up change to https://github.com/apache/incubator-nuttx/pull/1771
CI
CI

Remove -x from cibuild.sh call in CI since this will abort the build on first error and we do not want that

---

interpreters/wasm3/.gitignore
interpreters/wasm3/Kconfig
interpreters/wasm3/Make.defs
interpreters/wasm3/Makefile

Introduce wasm3 WebAssembly runtime support, with baisc test utility.
None
Tested on stm32

interpreters: Initial wasm3 WebAssembly runtime support

---

.gitignore
Application.mk
Directory.mk
Make.defs
Makefile

This is the corresponding change to the one on main NuttX repo (see https://github.com/apache/incubator-nuttx/pull/1765).
In this case this involves splitting the build of libapps.a into: a) building
all applications (which is safely parallelizable), b) adding each
application's object files to the archive in turns (serial by nature).
This removes the need for the flock used to protect the parallel build.
NOTE: this will not pass CI since it depends on the other PR
Build
Builds correctly

Fix: ensure archive files do not carry object files from prior builds

---

netutils/ntpclient/ntpclient.c

In case of DNS resolution failure the NTP daemon was exiting without updating its state, which caused later calls to ntpc_start or ntpc_stop to fail.

ntpclient: fix NTP daemon state in case of DNS failure

---

system/nxplayer/nxplayer.c

- This commit fixes a compile error
- Affects nxplayer with CONFIG_DEBUG_AUDIO_ERROR=y
- Tested with spresense:rndis

system: nxplayer: Fix a compile error if CONFIG_DEBUG_AUDIO_ERROR=y

---

interpreters/wamr/.gitignore
interpreters/wamr/0001-Introduce-support-for-NuttX-RTOS.patch
interpreters/wamr/Kconfig
interpreters/wamr/Make.defs
interpreters/wamr/Makefile

Support interpreter/aot mode, and this patch had submitted to WAMR (Apache License). See 
https://github.com/bytecodealliance/wasm-micro-runtime/pull/377
The patch file will be removed on WAMR's next release.
None
Tested on stm32.

interpreters: Inroduce support for WAMR

---

examples/fb/fb_main.c

examples/fb: correct the munmap(2) parameter type 
```
fb_main.c: In function 'fb_main':
fb_main.c:473:15: warning: passing argument 1 of 'munmap' makes pointer from integer without a cast [-Wint-conversion]
473 |   munmap(state.fd, state.fbmem);
|          ~~~~~^~~
|               |
|               int
In file included from fb_main.c:43:
/home/archer/code/upload/incubator-nuttx/include/sys/mman.h:177:22: note: expected 'void *' but argument is of type 'int'
177 | int munmap(FAR void *start, size_t length);
|                ~~~~~~^~~~~
fb_main.c:473:25: warning: passing argument 2 of 'munmap' makes integer from pointer without a cast [-Wint-conversion]
473 |   munmap(state.fd, state.fbmem);
|                    ~~~~~^~~~~~
|                         |
|                         void *
In …
```

examples/fb: correct the munmap(2) parameter type 

---

interpreters/wamr/Kconfig

Add missing options to Kconfig, now these symbol provided by NuttX, handled in WAMR side.
None
Tested on STM32.

interpreters/wamr: Add missing options

---

wireless/wapi/src/wapi.c

wireless/wapi: ignore the fail case
do not break the show process if some cases failure
Change-Id: I5d5768ba116a9e8a8ea62ae9455d773838328bd5

wireless/wapi: ignore the fail case in show command

---

netutils/dhcpc/dhcpc.c

netutils/dhcpc: try to get the host name via syscall first
Change-Id: I22aa8316f5c126bf3bafe9476a27a43c01da6129

netutils/dhcpc: try to get the host name via syscall first

---

include/wireless/wapi.h
wireless/wapi/src/wireless.c

wireless/wapi: add scan partial channel support
Change-Id: I2279406a9ca0cc3a9535ce79fbf651dbaf14ad4c

wireless/wapi: add scan partial channel support

---

include/wireless/wapi.h
netutils/netinit/netinit_associate.c
wireless/wapi/src/driver_wext.c
wireless/wapi/src/util.c
wireless/wapi/src/wapi.c

wireless/wapi: add option to associate with bssid 
Change-Id: I68ef42edfc50ef5baf0f02a570d0e7f79669659f

wireless/wapi: add option to associate with bssid 

---

Application.mk
Makefile
import/Makefile

apps/MAKE: Add register staging to context
When compiling an external library, and the library need "configure" firstly.
Then there are 2 ways to doing the "configure" :
1. preconfig stage:
If put "configure" in this stage, the global config.h (external library also needed) hasn't ready.
2. context stage:
If put "configure" in this stage, the action of registering will be failed, because PROGNAME in library
has dependency to action "configure".
In another word, compiler should follow this step for this library:
preconfig(config.h) ->  configure to library -> PROGNAME -> action of registering to built-in list
So, to resolve this.
preconfig(config.h) ->  configure to library -> PROGNAME -> action of registering to built-in list
preconfig stage &emsp; &emsp; &emsp;   context stage   &emsp; …

apps/MAKE: Add register staging to context

---

netutils/dhcpc/dhcpc.c

- dhcpc now uses gethostname() but the hostname might be empty
- All use cases which use dhcpc
- Tested with spresense:wifi

netutils: dhcpc: Fix dhcpc.c

---

examples/nxterm/nxterm_main.c

fflush(stdout) was called twice to back-to-back.
No impact is anticipated.  One fflush() is enough.
Only PR checks.

apps/examples/nxterm:  Remove duplicated fflush() call.

---

include/system/nxplayer.h
include/system/nxrecorder.h
system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_main.c
system/nxrecorder/nxrecorder.c
system/nxrecorder/nxrecorder_main.c

nxplayer&nxrecoder: add channel map support
add channel map as the last cmd line param,
this is base on :
https://github.com/apache/incubator-nuttx/pull/1892

nxplayer&nxrecoder: add channel map support

---

system/nxplayer/nxplayer_main.c

system/nxplayer/nxplayer_main.c: fix '%d' missing in sscanf
nxplayer

system/nxplayer/nxplayer_main.c: fix '%d' missing in sscanf

---

interpreters/wamr/Kconfig

New feature in WAMR, handled in WAMR side but need kconfig symbol from NuttX.
None
stm32f429i-disco

interpreters/wamr: Add configs for heap pool & custom name sections

---

examples/timer/timer_main.c

This commit allows passing a timer device path argument to the timer example. 
Now, the example may run with multiple timer instances.
The change was tested by running the following command in the NuttX shell in the esp32 SoC which has 4 timers:
timer -d /dev/timerx (x = 0,1,2,3)

Added timer device path as a CLI option

---

examples/wgetjson/wgetjson_main.c

The rest of errors are about cJSON identifiers:
wgetjson_main.c:181:2: error: Mixed case identifier found
wgetjson_main.c:183:9: error: Mixed case identifier found
wgetjson_main.c:186:37: error: Mixed case identifier found
wgetjson_main.c:190:12: error: Mixed case identifier found
wgetjson_main.c:191:6: error: Mixed case identifier found
wgetjson_main.c:203:39: error: Mixed case identifier found
wgetjson_main.c:256:36: error: Mixed case identifier found
wgetjson_main.c:283:2: error: Mixed case identifier found
wgetjson_main.c:286:9: error: Mixed case identifier found
wgetjson_main.c:289:37: error: Mixed case identifier found
wgetjson_main.c:295:6: error: Mixed case identifier found
tested with nxstyle locally

examples/wgetjson/wgetjson_main.c: nxstyle fixes

---

examples/ipcfg/Kconfig
examples/ipcfg/Make.defs
examples/ipcfg/Makefile
examples/ipcfg/ipcfg_main.c
fsutils/ipcfg/Kconfig
fsutils/ipcfg/Make.defs
fsutils/ipcfg/Makefile
fsutils/ipcfg/ipcfg.c
include/fsutils/ipcfg.h

This commit adds support to access an IPv4 Configuration file similar to the Linux dhpc.client ipfcg file.  This version, tailored for deeply embedded systems supports several options to tailor the file and file access to different environments.  It supports:
- Writable as well as read-only configuration files.
- ASCII human readable files as well as smaller binary files.
- It supports using character driver access to constrained media (such as EEPROM).
Since nothing uses the IPv4 Configuration file at present, there should be no impact from this addition.
To be provided after initial review.

Add IPv4 Configuration File Access Helper

---

examples/ipcfg/ipcfg_main.c
fsutils/ipcfg/ipcfg.c
include/fsutils/ipcfg.h

This commit adds structures, modifies function prototypes, and renames data to support the future addition of IPv6 support.  This commit does _NOT_ add that IPv6, only the hooks for backward compatible future support.
At present this has no impact because there is no existing use of the ipcfg access helpers in the repository.  However, it does affect the logic of the pending change of PR #415 
Verified with examples/ipcfg in binary mode using stm32f4discovery:netnsh

ipcfg:  Add hooks for future IPv6 support.

---

examples/ipcfg/Kconfig
examples/ipcfg/ipcfg_main.c
fsutils/ipcfg/Kconfig
fsutils/ipcfg/Makefile
fsutils/ipcfg/ipcfg.c
fsutils/ipcfg/ipcfg.h
fsutils/ipcfg/ipcfg_binary.c
fsutils/ipcfg/ipcfg_text.c
include/fsutils/ipcfg.h

The IP Configuration File access library at apps/fsutils/ipcfg was originally merged with IPv4 support only.  Only hooks were provided for IPv6.  This PR adds that missing IPv6 support.
Related PRs:  #407 #414 #415 #416 
This could potentially effect apps/netutils/netinit which is the only client of apps/fsutils/ipcfg.
The changes were verified using apps/examples/ipcfg with the base configuration stm32f4discovery:netnsh
Testing was fairly thorough.  I verified:
- IPv4
- IPv6
- IPv4 + IPv6
- All possible binary or human-readable text formats
- Assertions on and off

apps/fsutils/ipcfg:  Add support for IPv6

---

fsutils/ipcfg/ipcfg_text.c
include/fsutils/ipcfg.h
netutils/netinit/netinit.c

Uses logic from apps/fsutils/ipcfg to obtain the IP address configuration from a file, if available.  This only effects the behavior of netinit if CONFIG_FSUTILS_IPCFG is selected and if an IP configuration file is available on a file system. Otherwise, it reverts to the preceding behavior.
Also adds definitions to apps/include/fsutils/ipcfg.h to formalize a bit encoding of the prototype which was already in use, but not documented.
This PR also corrects a few problems with fsutils/ipcfg:
- Corrects some bad assertions (duplicated in PR #420, we can close that PR if this one is merged first.
- Corrects some inconsitent variable naming between apps/includes/fsutils/ipcfg.c and apps/fsutils/ipcfg/ipcfg_text.c
Obviously, the apps/netutils/netinit logic is affected.  The use of the ipcfg IP …

Incorporate IP configuration files into netinit.

---

interpreters/wamr/Kconfig

just be explicit about a prerequisite
sim build on macos. (with some other patches)

interpreters/wamr: This requires CLOCK_MONOTONIC to build

---

system/trace/Kconfig
system/trace/Make.defs
system/trace/Makefile
system/trace/README.md
system/trace/trace.c
system/trace/trace.h
system/trace/trace_dump.c

This PR adds "trace" command for task trace.
- Currently the documentation is available at https://github.com/YuuichiNakamura/nuttx-task-tracer-doc/blob/master/NuttXTaskTracer.md 
- rst version will be prepared later.
- "trace" command is added as built-in apps. It is available only when the related kernel configurations are enabled.
Tested by spresense:nsh by changing the following configurations.
```
CONFIG_SCHED_INSTRUMENTATION=y
CONFIG_SCHED_INSTRUMENTATION_FILTER=y
CONFIG_SCHED_INSTRUMENTATION_SYSCALL=y
CONFIG_SCHED_INSTRUMENTATION_IRQHANDLER=y
CONFIG_DRIVER_NOTE=y
CONFIG_DRIVER_NOTERAM=y
CONFIG_DRIVER_NOTECTL=y
CONFIG_SYSTEM_TRACE=y
CONFIG_SYSTEM_SYSTEM=y
```
Then "trace" command is added as built-in apps.
```
nsh> trace cmd usleep 1000
nsh> trace dump
```
This can get the following …

Add task trace support

---

examples/fxos8700cq_test/Kconfig
examples/fxos8700cq_test/Make.defs
examples/fxos8700cq_test/Makefile
examples/fxos8700cq_test/fxos8700cq_main.c

It was tested on NXP FRDM-64F:
nsh> fxos8700cq
{ accel: [2174, 555, -752], magn: [0, 0, 0] }
{ accel: [-300, 547, 1951], magn: [55, -188, 276] }
Change-Id: If5180ce69913cf096e04db7772f3f9dd63f853bd
Bug: https://github.com/apache/incubator-nuttx/issues/1988
Forwarded: https://github.com/apache/incubator-nuttx/pulls/rzr

examples: Add fxos8700cq sensor test

---

system/sched_note/note_main.c
system/trace/trace_dump.c

App code support for https://github.com/apache/incubator-nuttx/pull/2005
"note" and "trace" commands are fixed.
See https://github.com/apache/incubator-nuttx/pull/2005
See https://github.com/apache/incubator-nuttx/pull/2005

Fix note_syscall_leave_s to avoid unaligned access

---

README.md
examples/README.md
graphics/nxwidgets/ChangeLog.txt
graphics/nxwm/ChangeLog.txt
include/wireless/wapi.h
netutils/netlib/netlib_ipv6netmask2prefix.c
system/cu/Kconfig
system/nsh/Kconfig
wireless/ieee802154/i8sak/i8sak.h
wireless/ieee802154/i8sak/i8sak_assoc.c
wireless/ieee802154/i8sak/i8sak_blaster.c
wireless/ieee802154/i8sak/i8sak_poll.c
wireless/ieee802154/i8sak/i8sak_scan.c
wireless/ieee802154/i8sak/i8sak_sniffer.c
wireless/ieee802154/i8sak/i8sak_startpan.c
wireless/ieee802154/i8sak/i8sak_tx.c
wireless/wapi/src/network.c
wireless/wapi/src/util.c
wireless/wapi/src/util.h
wireless/wapi/src/wireless.c

Unify the naming convention. Please ignore the failse alarm:
```
apps/wireless/wapi/src/util.c:79:6: error: Mixed case identifier found
apps/wireless/wapi/src/util.c:106:9: error: Mixed case identifier found
```
None.

Change all 'Nuttx' to 'NuttX'

---

examples/fxos8700cq_test/Kconfig

SENSORS_FXOS8700CQ needs SENSORS for linking
Change-Id: Ie0f1ba57517f27fa7697b6c8cf7a1f6558107732
Bug: https://github.com/apache/incubator-nuttx/pull/1999
Forwarded: https://github.com/apache/incubator-nuttx/pulls/rzr

fxos8700cq: Select SENSORS if used

---

wireless/gs2200m/gs2200m_main.c

- This PR updates the gs2200m daemon and consists of the following 4 commits
- commit 1: wireless: gs2200m: Fix to handle UDP connect() with bind()
- This commit fixes to handle UDP connect() with bind() to local port
- NOTE: GS2200M does not support TCP connect() with bind to local port
- commit 2: wireless: gs2200m: Fix to handle address info in accept()
- This commit fixes to handle address info in accept()
- commit 3: wireless: gs2200m: Implement getpeername_request()
- This commit adds getperrname_request() to gs2200m_main.c
- commit 4: wireless: gs2200m: Add support for ioctl(fd, SIOCGIFADDR, ...)
- This commit adds support for ioctl(fd, SIOCGIFADDR, ...) to gs2200m_main.c
- All use cases which use accept() with gs2200m
- All use cases which use ioctl(fd, SIOCGIFADDR, ...) with …

Update gs2200m daemon

---

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
system/cu/cu_main.c

system/cu/cu_main.c: ctrlC will send SIGINT/SIGSTP
usrsock_rpmsg: fix can't wake ppoll when no ACTION,
no matter open/close CONFIG_SIGUSR1_ACTION, usrsock always do,
unmask SIGUSR1, set action to NULL.

Fix cu can't receive ctrl+c, usrsock_rpmsg: fix can't wake ppoll when no SIGUSR1_ACTION

---

nshlib/nsh_fsutils.c
nshlib/nsh_netcmds.c

Fix for nuttx [issue # 1883](https://github.com/apache/incubator-nuttx/issues/1883). When proc file-system is not mounted, running ifconfig should give output as "ifconfig: procfs is not mounted" instead of "ifconfig: opendir failed: 20".
Addressed review comments from @v01d & @xiaoxiang781216. For more details, please refer to [pull request 443](https://github.com/apache/incubator-nuttx-apps/pull/443). Based on the discussion, the error message should now be "**Could not open <dir/file name> (is procfs mounted?)**" at all relevant places.
When proc file-system is not mounted, running ifconfig should give output as "ifconfig: procfs is not mounted" instead of "ifconfig: opendir failed: 20".
Should be built and tested against relevant h/w platforms.
__Since I don't have necessary h/w …

Fix for nuttx issue 1883

---

nshlib/nsh_fsutils.c

Fixed for Nuttx coding standards violations in nsh_fsutils.h as reported in [pull request # 446](https://github.com/apache/incubator-nuttx-apps/pull/446) and [here](https://github.com/apache/incubator-nuttx-apps/pull/446/checks?check_run_id=1320354396).
Fixed for Nuttx coding standards violations in nsh_fsutils.h.
Should build and run normally without affecting any functionality.

Fixed coding std violations in nsh_fsutils.h

---

.github/workflows/build.yml

To simplify the build list management
No functional change
Pass the automation build

build.yml: Switch avr-mips-riscv-x86-xtensa.dat to other.dat

---

nshlib/nsh_builtin.c
nshlib/nsh_ddcmd.c
nshlib/nsh_modcmds.c
nshlib/nsh_proccmds.c
nshlib/nsh_romfsetc.c

Fixed NuttX coding std violations in the following files -
- nsh_builtin.c
- nsh_ddcmd.c
- nsh_modcmds.c
- nsh_proccmds.c
- nsh_romfsetc.c
No impact on functionality. Changes are meant for conformance with NuttX coding guidelines.
Does NOT add/modify any functionality. Should build & run normally.

Fixed coding std issues

---

examples/nxterm/nxterm_main.c
graphics/nxwm/src/cnxterm.cxx
graphics/twm4nx/apps/cnxterm.cxx
nshlib/nsh_altconsole.c
nshlib/nsh_usbconsole.c

since it is wrong to close the builtin stream and specially note
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html:
Since after the call to fclose() any use of stream results in
undefined behavior, fclose() should not be used on stdin, stdout,
or stderr except immediately before process termination (see XBD
Process Termination), so as to avoid triggering undefined behavior
in other standard interfaces that rely on these streams. If there
are any atexit() handlers registered by the application, such a
call to fclose() should not occur until the last handler is
finishing. Once fclose() has been used to close stdin, stdout, or
stderr, there is no standard way to reopen any of these streams.
and it is also unnecessary because the stream always get flushed.
Remove the …

Remove all fclose with stdin, stdout and stderr

---

examples/lvgldemo/lvgldemo.c
graphics/lvgl/Makefile
graphics/lvgl/lv_conf.h
graphics/lvgl/lv_tick_interface.c
graphics/lvgl/lv_tick_interface.h

This makes LVGL use malloc/free to handle its memory (instead of
their own memory handling) and supports a tick interface by which
LVGL can ask NuttX the elapsed time, instead of having to periodically
"tick" LVGL internal time in a thread.
Improves integration with LVGL
Sim with X11 framebuffer

lvgl: use malloc/free for memory handling and "tickless" tick interface

---

.github/workflows/build.yml

Backport #448
Switch avr-mips-riscv-x86-xtensa.dat to other.dat
This is required to allow this branch to keep building against the CI system.

[BACKPORT #448] build.yml: Switch avr-mips-riscv-x86-xtensa.dat to other.dat

---

wireless/gs2200m/gs2200m_main.c

Backport of #439
This PR updates the gs2200m daemon and consists of the following 4 commits
commit 1: wireless: gs2200m: Fix to handle UDP connect() with bind()
This commit fixes to handle UDP connect() with bind() to local port
NOTE: GS2200M does not support TCP connect() with bind to local port
commit 2: wireless: gs2200m: Fix to handle address info in accept()
This commit fixes to handle address info in accept()
commit 3: wireless: gs2200m: Implement getpeername_request()
This commit adds getperrname_request() to gs2200m_main.c
commit 4: wireless: gs2200m: Add support for ioctl(fd, SIOCGIFADDR, ...)
This commit adds support for ioctl(fd, SIOCGIFADDR, ...) to gs2200m_main.c

[BACKPORT #439] Update gs2200m daemon

---

examples/nxterm/nxterm_main.c
graphics/nxwm/src/cnxterm.cxx
graphics/twm4nx/apps/cnxterm.cxx
nshlib/nsh_altconsole.c
nshlib/nsh_usbconsole.c

[BACKPORT #425] Remove all fclose with stdin, stdout and stder

---

wireless/bluetooth/nimble/.gitignore
wireless/bluetooth/nimble/Kconfig
wireless/bluetooth/nimble/Make.defs
wireless/bluetooth/nimble/Makefile
wireless/bluetooth/nimble/README.md

This PR adds support for nimBLE host-layer stack for NuttX, for when NuttX's own stack is disabled. This will build a `nimble` app, which is an example shipped with nimBLE which includes a simple GATT server. An application wishing to use the stack need to add the appropriate include path.
At the moment this points to my fork of nimBLE, which is currently awaiting merge upstream. Once it is accepted upstream, I will create another PR to point to the official repo.
Add application.
Developed own application using nimBLE on top of to-be-upstream nRF52 link-layer. Also tested on sim build, using bthcisock config. A nimBLE specific config will be added in separate PR on main repo for others to test.

nimBLE integration application/library

---

graphics/nxwm/src/ctaskbar.cxx
include/graphics/nxwm/ctaskbar.hxx

Fixed the crash caused by a NULL memory access to an invalid background
window fixes.
Verified that the simulation is starting without a crash. An image is displayed in the simulation window.
Signed-off-by: Sebastian Ene <sene@apache.org>

arch/sim: Fix NXWM test failure

---

graphics/nxwm/src/ctaskbar.cxx
include/graphics/nxwm/ctaskbar.hxx

Backports #456
Fixed the crash caused by a NULL memory access to an invalid background
window.

[BACKPORT #456] arch/sim: Fix NXWM test failure

---

wireless/gs2200m/gs2200m_main.c

Summary:
- This commit enables gs2200m application to get IWNWID/IWFREQ/IWSENS information
Impact:
- Affects gs2200m only
Testing:
- Tested with spresense:wifi
@masayuki2009

gs2200m: Add function to get IWNWID / IWFREQ / IWSENS information

---

examples/mount/mount_main.c

Fix for NuttX [issue # 2089](https://github.com/apache/incubator-nuttx/issues/2089).
Ideally, this should fix the selftest issue for sim:mount configuration. Selftest should now complete without any errors.
Changed g_target to g_mntdir as g_target and g_testdir4 are on the same filesystem, a prerequisite for EXDEV.
`fail_rename(g_mntdir, g_testdir4, EXDEV);`
Also, changed error type `EEXIST` to `ENOENT` for the second `fail_rename()` call.
To be tested for sim:mount configuration. Ideally, the test should now run without any issues.

Fix for sim:mount selftest failure

---

examples/mount/mount_main.c

This backports #464
Fix for sim:mount selftest failure

[BACKPORT #464] Fix for sim:mount selftest failure

---

system/adb/.gitignore
system/libuv/.gitignore

Add missing gitignore files for libuv and adb builds

libuv/adb: add gitignore files

---

.github/workflows/build.yml

Remove deprecated usage of set-env in GitHub Actions workflow
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
CI

Remove deprecated usage of set-env in workflows

---

testing/nxffs/nxffs_main.c

Fix for the file naming issue in `sim:nxffs` configuration. Without this change, it generates file names like below -
`File name: /mnt/nxffs/EVwni/b4A/BqjDc42RCtKvjJ6DInifZ0tME26XGRXWl5ZAE`
of which the filename part is `EVwni/b4A/BqjDc42RCtKvjJ6DInifZ0tME26XGRXWl5ZAE` which is pretty confusing.
No impact on functionality. This fix does NOT resolve [issue # 2092](https://github.com/apache/incubator-nuttx/issues/2092), though it could be a step in the right direction.
No impact on functionality.

Fix for file naming issue for sim:nxffs configuration

---

include/wireless/wapi.h
wireless/wapi/src/driver_wext.c

wireless/wapi: add channel frequency set during associate
Therefore, the associate can support the connection of specified
channel if the scan results contain the multiple AP with same essids.
Change-Id: I4e657c52e638693e7ae19aea2a4fe8a431885547
associate with specified channel frequency.

wireless/wapi: add channel frequency set during associate

---

examples/fboverlay/fboverlay_main.c

See https://github.com/apache/incubator-nuttx/pull/2222

examples/fboverlay/fboverlay_main.c: Fix a printf format warning

---

graphics/nxwm/src/chexcalculator.cxx

Typos in the following change:
commit c48e65414b1fe1172029d6f041d615fa438cb320
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Mon Nov 16 14:16:46 2020 +0900
graphics/nxwm/src/chexcalculator.cxx: Fix printf format warnings

graphics/nxwm/src/chexcalculator.cxx: Fix typos

---

.github/workflows/build.yml

[BACKPORT #469] ci: Remove deprecated usage of set-env in workflows

---

include/netutils/webclient.h
netutils/webclient/webclient.c

This fixes the case when webclient_set_static_body is used
for data larger than webclient_context::buflen.
Note: as of writing this, webclient_set_static_body is the
only user of body_callback in NuttX apps tree.
tested with my local app.

webclient: Distinguish request size and buffer size in body callback

---

wireless/wapi/src/driver_wext.c

see https://github.com/apache/incubator-nuttx/pull/2347

wireless/wapi/src/driver_wext.c: Fix a syslog format

---

testing/irtest/Kconfig
testing/irtest/Make.defs
testing/irtest/Makefile
testing/irtest/cmd.hpp
testing/irtest/cmdGeneral.cpp
testing/irtest/cmdLirc.cpp
testing/irtest/enum.hpp
testing/irtest/enumDefine.cpp
testing/irtest/main.cpp

Test remote control by this Interactive cmd shell tool.
This tool supports simultaneous operation of multiple devices, the maximum number of devices depends on CONFIG_TESTING_IRTEST_MAX_NIRDEV, and the maximum size of sending data depends on CONFIG_TESTING_IRTEST_MAX_SIRDATA.
You can open /dev/lirc0 character device by input  "open_device /dev/lirc0";
You can read data from /dev/lirc0 by input "read_data index 1", index represents the order number in which the device is turned on, 1 is size of reading data.
You can input "help" to get more usag information.
Test remote control device
Daily test

Test rc by LIRC interface

---

canutils/candump/candump.c

Candump original Linux version (linux-can/can-utils) assumes that time_t is a long integer whereas in NuttX time_t is a unsigned integer. Thus giving compiler printf warnings, this PR removes the warnings by using the correct specifier.
Minimal removes compile warnings, no functional change.
Tested on PX4-Firmware also fixes PX4/PX4-Autopilot#16251

Candump: Fix printf compile warning regarding time_t

---

examples/i2schar/i2schar_main.c

2schar_main.c: In function 'parse_args':
i2schar_main.c:199:20: error: 'struct i2schar_state_s' has no member named 'rxcount'
199 |             i2schar->rxcount = (uint32_t)value;
|                    ^~
i2schar_main.c:211:20: error: 'struct i2schar_state_s' has no member named 'txcount'
211 |             i2schar->txcount = (uint32_t)value;
|                    ^~
i2schar_main.c: In function 'i2schar_main':
i2schar_main.c:276:16: error: 'struct i2schar_state_s' has no member named 'rxcount'
276 |       g_i2schar.rxcount = CONFIG_EXAMPLES_I2SCHAR_RXBUFFERS;
|                ^

examples/i2schar: Fix the compile error

---

examples/mld/mld_main.c

examples/mld: Fix undefined reference to `mld_catfile'

---

examples/cctype/cctype_main.cxx

since isascii isn't a standard defined function and then
may not exist in all cctype header file(e.g. libc++):
```
cctype_main.cxx: In function 'int cctype_main(int, char**)':
cctype_main.cxx:64:45: error: 'isascii' is not a member of 'std'; did you mean 'isascii'?
64 |                       std::isspace(i), std::isascii(i), std::isprint(i), std::isgraph(i),
|                                             ^~~~~~~
```

examples/cctye: change std::isascii to isascii

---

examples/pwm/pwm_main.c

- Fix bug for multiple PWM outputs (CONFIG_PWM_MULTICHAN). Wrong define
was in use and only the information about the first channel was shown.
- Fix formatting (a few line breaks and spaces missing).
Only the help message modified. It was very confusing before because only one channel was shown, but it shouldn't impact anything else.
Built and tested.
Thanks!

examples/pwm: fix help message

---

wireless/wapi/src/driver_wext.c

wireless/wapi: do not associate with essid/bssid at same time
bssid is a associate trigger point of connection in some drivers.
wapi save/reconnect
CONFIG_NETINIT
wapi save/reconnect
CONFIG_NETINIT

wireless/wapi: do not associate with essid/bssid at same time

---

examples/lvgldemo/Makefile
graphics/lvgl/Makefile
graphics/lvgl/lv_conf.h

This makes LVGL use NuttX's printf facilities instead of its own
LVGL
Various LVGL configs

LVGL: use NuttX's printf()

---

system/adb/Makefile
system/adb/adb_main.c
system/adb/shell_pipe.c
system/adb/shell_service.c

- Fix memory leak due to stdout pipe endpoint not closed
- Add support for "adb reboot [target]" command

system/adb: fix shell issue and add reboot feature

---

system/nxrecorder/nxrecorder.c

Change-Id: I785f44a4381965df700000cbd33faeb2d2e24f6e
Signed-off-by: danguanghua <danguanghua@xiaomi.com>

fix build bread if CONFIG_AUDIO_MULTI_SESSION enabled

---

nshlib/nsh_usbconsole.c

- stdin/stdout/stderr are now preallocated in libc and fs_fd
in file_struct are also initialized to -1
- So we need to call fdopen() for stdin again as we did before.
- Also, cn_outstream and cn_errstream are not needed to be set.
- See apps/nshlib/nsh_console.h as well
- nsh_usbconsole.c only
- Tested with stm32f4discovery:usbnsh

nshlib: Fix nsh_usbconsole.c

---

system/nxplayer/nxplayer.c
system/nxrecorder/nxrecorder.c

the audio driver may config a very large buffer count,
so let's adjust the message queue length dynamically.
Should no impact on the normal case.

system: nxplayer and nxrecorder shouldn't hardcode message length to 16

---

nshlib/nsh_console.c
nshlib/nsh_usbconsole.c

not really need since these file stream should be opened automatically.
Need work with https://github.com/apache/incubator-nuttx/pull/2540.
See the discussion here: #521
Handle the usb console in a more standardized way
Need tested with https://github.com/apache/incubator-nuttx/pull/2540

nshlib: Remove fdopen for the stdin, stdout and stderr

---

examples/ftpc/ftpc_cmds.c
examples/ftpc/ftpc_main.c

Allow -4 and -6 command line options to select IPv4 or IPv6 on dual-stack devices, instead of always defaulting to IPv6
Uses `getaddrinfo()` so can do host name lookups, option -n to disable (also works without CONFIG_LIBC_NETDB for IP addr only, like before)
`getopt()` always called in a loop so no need for non-portable `optind = -1` construction
Added missing `htons()` for port number
Command line syntax slightly changed, syntax `host:port` changed to have `port` as separate argument (easier for numeric IPv6)

examples/ftpc: proper dual-stack support, also fix getopt re-entrancy issues

---

system/adb/adb_main.c

- This commit fixes compile issues for the following condition
- CONFIG_ADBD_BOARD_INIT=n && CONFIG_BOARDCTL_RESET=y
- adb only
- Tested with stm32f4discovery:adb (not pushed yet)

system: adb: Fix compile issues in adb_main.c

---

wireless/bluetooth/nimble/Makefile
wireless/bluetooth/nimble/README.md

Since NuttX is now officially supported in nimBLE (https://github.com/apache/mynewt-nimble/pull/878) this makes the Makefile
point to official repo instead of my fork. I also fixed some issues with handling of the downloaded tarball.
Once this is merged, I will refresh https://github.com/apache/incubator-nuttx/pull/2129 which will complete integration of nimBLE into NuttX.
fix/update nimBLE app
sim:nimble (to be provided)

nimble: point to upstream, improve Makefile

---

examples/README.md
examples/watched/Kconfig
examples/watched/Make.defs
examples/watched/Makefile
examples/watched/watched.c
examples/watched/watched.h
examples/watched/watched_main.c
examples/watcher/Kconfig
examples/watcher/Make.defs
examples/watcher/Makefile
examples/watcher/ramdisk.c
examples/watcher/ramdisk.h
examples/watcher/task_mn.c
examples/watcher/task_mn.h
examples/watcher/watcher_main.c
examples/watcher/wdt.c
examples/watcher/wdt.h

This PR intends to add a set of examples: The watcher and the watched examples. They were designed to work together.
The watcher is a task that will monitor other tasks that subscribed to be watched.
If a subscribed task doesn't request the watcher to feed the dog before the timeout completes, the watcher prints the name of all currently subscribed tasks exposing which one(s) starved the dog.
The watcher may serve as a helper to identify offending tasks in applications with multiple tasks.
The watched example shows how to subscribe, to request the watcher to feed the dog, and also how to unsubscribe. The watched example also exposures the functionality by creating 2 tasks that will starve the dog and 2 other tasks that will feed the dog. Try it!
Besides it, this set of examples may serve …

Added Watcher Example

---

wireless/bluetooth/nimble/Kconfig

Last PR #528 missed a change, where the branch name to use is no longer "nuttx". For now "master" it is used until next stable release of nimBLE is available, where a tag name will be used instead.
Allow building nimBLE
sim:nimble (to be provided)

nimble: fix wrong git ref name to use

---

system/nxplayer/nxplayer.c
system/nxrecorder/nxrecorder.c

to avoid multiple open operations of audio_open
Change-Id: Id283def4811c71f3c0bd38dc1a480afce303c4c3
Signed-off-by: danguanghua <danguanghua@xiaomi.com>

system: enable O_CLOEXEC when openning audio device

---

interpreters/wamr/.gitignore
interpreters/wamr/Kconfig
interpreters/wamr/Makefile

Now supports specifying the version number of wamr as main.
None
Tested on stm32f429i-disco

interpreters/wamr: Support latest snapshot for main branch

---

netutils/netinit/Kconfig

* It doesn't make much sense to have the default values for
these highly environment-dependent settings.
* netutils/netinit/netinit_associate.c calls wpa_driver_wext_associate
if the SSID is not empty. Depending on the environment, it can take
long to fail. It slows down the boot of some configurations
considerably. eg. esp32-devkitc:wapi
esp32-devkitc:wapi (with some local patches)

netinit: Make the default SSID and passphrase empty

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/lint.yml

See https://github.com/apache/incubator-nuttx/pull/2622
*In addition to the problem listed here this also brings this in-line with the OS workflow files.*
Apache Infrastructure recently made a change to the GitHub projects so that they cannot use actions that are not under the Apache org, GitHub org, or verified.   We were using some outside of this and this prevented builds from running.
Policy:
* https://infra.apache.org/github-actions-secrets.html
Discussion builds@apache.org:
* https://lists.apache.org/thread.html/r435c45dfc28ec74e28314aa9db8a216a2b45ff7f27b15932035d3f65%40%3Cbuilds.apache.org%3E
Discussion users@infra.apache.org:
* https://lists.apache.org/thread.html/r900f8f9a874006ed8121bdc901a0d1acccbb340882c1f94dad61a5e9%40%3Cusers.infra.apache.org%3E
One drawback is that the …

CI: Only use approved GitHub Actions

---

examples/nrf24l01_btle/Kconfig
examples/nrf24l01_btle/Make.defs
examples/nrf24l01_btle/Makefile
examples/nrf24l01_btle/nrf24l01_btle.c
examples/nrf24l01_btle/nrf24l01_btle.h

Using nRF24L01+ as A Bluetooth Low Energy Broadcaster/Beacon. This app is inspired by Dmitry Grinberg’s idea [Faking Bluetooth LE](https://dmitry.gr/index.php?r=05.Projects&proj=11.%20Bluetooth%20LE%20fakery). 
I have already tested on stm32f103-minimum:nrf24

added: Using nRF24L01+ as A Bluetooth Low Energy Broadcaster/Beacon

---

testing/ostest/mqueue.c

let's change to 0 instead since mq_t mayn't be a pointer. Found by PR: https://github.com/apache/incubator-nuttx/pull/2631
No real change since NULL always equals 0
Pass the build

ostest: Don't assign NULL to mq_t varaibles

---

examples/webserver/webserver_main.c

Prior to this change, the webserver program would _never_ terminate, even when running as a NSH built-in app.  For example:
```
nsh> webserver &
webserver [6:100]
nsh> Starting webserver
nsh> kill -9 6
nsh> webserver_main: Still running
nsh> webserver_main: Still running
nsh> webserver_main: Still running
nsh> webserver_main: Still running
```
The message "Still running" would be printed forever, every 3 seconds. Despite printing "Still running," httpd has terminated and the process is doing nothing. This was done because webserver can be a standalone app which must never terminate.
This PR preserves the above behavior when built as a standalone program that must never terminate, but makes it possible to terminate the app normally when built as a NSH built-in app:
```
nsh> webserver & …
```

examples/webserver: Allow exit when run as a NSH built-in app

---

include/wireless/wapi.h
wireless/wapi/src/wapi.c
wireless/wapi/src/wireless.c

wireless/wapi: add set country code support
N/A
wapi wlan0 country CN

wireless/wapi: add set country code support

---

system/readline/readline_common.c

system/readline: check the control ascii only to support multi-languages 
```
nsh> echo hello world
hello world
nsh> echo こんにちは
こんにちは
nsh> echo 你好
你好
```

system/readline: check the control ascii only to support multi-languages 

---

system/trace/trace_dump.c

Fix fprintf() format warnings by using inttypes.h macros.
Only when CONFIG_SYSTEM_TRACE = y
Tested by 32bit and 64bit compiler. (spresense and maix-bit)
format warnings are disappeared.

system/trace: Fix fprintf format warnings

---

netutils/iperf/Kconfig
netutils/iperf/Make.defs
netutils/iperf/Makefile
netutils/iperf/README.md
netutils/iperf/iperf.c
netutils/iperf/iperf.h
netutils/iperf/iperf_main.c
system/argtable3/.gitignore
system/argtable3/Kconfig
system/argtable3/Make.defs
system/argtable3/Makefile

This example was implemented by Chen Wen chenwen@espressif.com and reviewed by Abdelatif Guettouche
Add iperf example.
It is a network performance testing example, its usage is the same as iperf of a 3rd party applications, please refer to README.md for details.

netutils/iperf: Add iperf example.

---

examples/pty_test/pty_test.c
system/adb/shell_pipe.c

examples/pty_test: Remove O_NONBLOCK from open
nsh: Pass the correct command lines to nsh_consolemain
pts test can run sucesfully

Fix pty_test issue during testing

---

examples/ftpd/ftpd.h
examples/ftpd/ftpd_main.c
netutils/ftpd/Makefile
netutils/ftpd/ftpd.c
netutils/ftpd/ftpd.h

- Fixes crash when ftpd_close() called before account setup
- Fixes compilation on dual-stack (both IPv4 and IPv6) systems
- Rename command RNTO return -EINVAL if no from path (This is just a minor thing, to correct original code that had superfluous return statement)
- nxstyle fixes

Ftpd fixes

---

netutils/webclient/webclient.c

webclient: Report unexpected connection loss as an explicit error
Otherwise, it can end up with mysterious results in user apps.
tested with a local app

webclient: Report unexpected connection loss as an explicit error

---

system/argtable3/0001-feat-Switch-to-FreeBSD-getopt-library.patch
system/argtable3/Kconfig
system/argtable3/Make.defs
system/argtable3/Makefile

And remove the patch process since it doesn't need anymore.
update to the latest version

system/argtable3: Update to the latest version(v3.1.5.1c1bb23)

---

examples/pty_test/pty_test.c

should be CONFIG_EXAMPLES_PTYTEST_SERIALDEV, regression in commit:
```
commit 6ddbffd2000fb62c71914c6f57c93f2e7d1f50e8
Date:   Sun Jan 3 23:50:50 2021 -0800
examples/pty_test: Remove O_NONBLOCK from open
to avoid the log storm:
ERROR Failed to read from serial: 11
ERROR Failed to read from serial: 11
ERROR Failed to read from serial: 11
ERROR Failed to read from serial: 11
ERROR Failed to read from serial: 11
...
```
pty test can open CONFIG_EXAMPLES_PTYTEST_SERIALDEV, instead the hardcode /dev/console

examples/pty_test: Fix the hardcode uart device path

---

netutils/iperf/iperf.c
netutils/iperf/iperf_main.c

- This commit fixes compile warnings with Arm GCC 9.3.1
- None
- Tested with lm3s6965-ek:discover
- NOTE: need to add the following configs
+CONFIG_EXAMPLES_IPERF=y
+CONFIG_EXAMPLES_IPERFTEST_DEVNAME="eth0"

netutils : iperf: Fix compile warnings with Arm GCC 9.3.1

---

include/netutils/webclient.h
netutils/webclient/webclient.c

webclient: Add AF_LOCAL support
AF_LOCAL part:
Tested against Docker Engine socket on macOS and Linux. (with a ported version of webclient)
Only build-tested for NuttX.
"webclient: Don't call the sink callback if no data is available" part:
Tested with a local app (only with TCP on NuttX)

webclient: Add AF_LOCAL support

---

netutils/webclient/webclient.c

Detected by clang static analyzer.
* the static analyzer complaint disappeared.
* not really tested this specific "Failed to resolve hostname" path.

webclient: Fix a use of uninitialized variable

---

canutils/slcan/Kconfig
canutils/slcan/Make.defs
canutils/slcan/Makefile
canutils/slcan/slcan.c
canutils/slcan/slcan.h

Implementation of SLCAN (CAN over serial) UART protocol to convert SocketCAN interfaces to UART interfaces
None, just a new application
Verifed on UCANS32K146-01 converting both CAN buses to 2 seperate serial ports.

canutils/slcan: Add SLCAN utility

---

examples/romfs/romfs_main.c

since romfs can return the soft link with the kernel change:
commit 67ef70d460db4695b950208d861ff47d4a40bdb3
Date:   Mon Jul 6 00:34:32 2020 +0800
vfs/dirread: Should return the same file type as lstat
by extend the possible value of d_type for the special file
Pass the test now

examples/romfs: Add ldir(soft link) into check

---

include/netutils/ntpclient.h
netutils/ntpclient/Kconfig
netutils/ntpclient/ntpclient.c
netutils/ntpclient/ntpv3.h

Port from Haltian's production NTP implementation to upstream NuttX. 
Sprry about having this in one commit only, it is somewhat tedious manual merge from our private apps tree.
Changes:
Allow multiple NTP servers, also with runtime configurable list
Add validation of received NTP packets
NTPv4 support with 'Kiss o' Death' message handling
IPv6 support
Collect multiple NTP samples and filter outsiders
Check if system clock has been altered during NTP (if CONFIG_CLOCK_MONOTONIC)
Has been used by us many years, many products. IPv6 support is very new, might need additional testing.
Compile tested only with Apache NuttX tree.

netutils/ntpclient: add more features

---

netutils/netcat/netcat_main.c

The buffer doesn't have the space for the terminating NUL.
Fix it by replacing it with fwrite, as there seems to be little reason
to use fprintf and NUL-terminated string in the first place.
tested on esp32-devkitc

netcat: Fix a buffer overflow

---

netutils/netcat/netcat_main.c

* Make "netcat -l" stop after processing a connection
* Stop echoing back the input.
It isn't the responsibility of this app, IMO.
* Allow non-text data
* Error checks and cleanups
tested on esp32-devkitc. the peer was netbsd nc.

netcat fixes and improvements

---

nshlib/nsh_printf.c

A NuttX user reported that the command to turn ON/OFF the userleds from nsh wasn't working:
nsh> printf \x01 > /dev/userleds
It is described in this video tutorial: https://www.youtube.com/watch?v=GzX9okqfxX4&t=150s
After some investigation I discovered that the issue was caused by this modification:
https://github.com/apache/incubator-nuttx/commit/7a18ebe45980a80370b7afaa4b4d0be703402318
Now users will be able to use the printf command again to control the LEDs, but they will need to send 32-bit instead of 8-bit:
nsh> printf \x00000001 > /dev/userleds
stm32f103-minimum board

Add support in printf command to send 8-32 bits value

---

wireless/wapi/src/wapi.c

wireless/wapi: add get sensitivity command 
wapi sense wlan0
ap> wapi sense wlan0
-128

wireless/wapi: add get sensitivity command 

---

include/wireless/wapi.h
wireless/wapi/src/wireless.c

wapi: Extend "WAPI_ESSID_DELAY_ON" flag to support customized connection behavior
The current essid setting(SIOCSIWESSID) are not satisfactory in case
of specified bssid connection, if there are multiple essids with same name,
we need additional bssid information to connect to the specified softap.
The extended flag "WAPI_ESSID_DELAY_ON" instructs the driver to delay the
connection behavior of essid, so that which can accept more accurate
information before generating a connection.
About flow of wapi command, drivers that support WAPI_ESSID_DELAY_ON semantics
will have the following behavior changes:
1. Station mode without bssid set:
```
$ ifup wlan0
$ wapi mode wlan0 2
$ wapi psk wlan0 12345678 3
$ wapi essid wlan0 archer 1
$ renew wlan0
```
2. Station mode with bssid set:
```
$ ifup …
```

wapi: Extend "WAPI_ESSID_DELAY_ON" flag to support customized connection behavior

---

netutils/iperf/iperf.c

- I noticed that lc823450-xgevk:rndis does not work with iperf
- Finally, I found that it does not call pthread_join()
- No impact
- Tested with lc823450-xgevk:rndis
- NOTE: need to add iperf in the defconfig

netutils: iperf: Add pthread_join() to wait for completion

---

examples/wget/wget_main.c

wget: print a message on an error
To give the user some clue on what's going.
a slight variant was tested locally

wget: print a message on an error

---

netutils/ntpclient/ntpclient.c

ntpclient.c: Avoid integer overflows in offset calculation
The current calculation easily overflows if the local time is
around the unix epoch.  I guess it isn't too unusual for
devices without RTC.  Or, the battery is dead.  Or, whatever.
This commit avoids the overflow by simply dividing everything by 2.
While more sophisticated and precise solutions are possible,
I feel that they are overkill for this simple implementation.
For example,
The unix epoch (1970) is 0x83aa7e8000000000 in
64-bit NTP timestamp. (1900-origin)
The timestamp now, as of writing this, is 0xe3cda16b00000000.
With the code before this commit, the offset will be:
(lldb) p (long long)((0xe3cda16b00000000 - 0x83aa7e8000000000) + (0xe3cda16b00000000 - 0x83aa7e8000000000)) / 2
(long long) $16 = -2295952992316162048 …

ntpclient.c: Avoid integer overflows in offset calculation

---

netutils/dhcpc/Kconfig
netutils/dhcpc/dhcpc.c

netutils/dhcpc: configurable Bootstrap flags
Change-Id: I9a364fda2ac536422ef3294a7217474f48eaad21
depends on: https://github.com/apache/incubator-nuttx/pull/2774

netutils/dhcpc: configurable Bootstrap flags

---

netutils/webclient/webclient.c

from:
return - ECONNABORTED;
to:
return -ECONNABORTED;
The latter style is more commonly used within NuttX code base.
Note: nxstyle doesn't complain on either of them.
nxstyle passed locally

webclient.c: Remove a space after a negative sign

---

examples/hidkbd/hidkbd_main.c

Remove the "sanity" check for `CONFIG_USBHOST` for the hidkbd example.   Other drivers can implement this came interface, the application should not be requiring this.
There is even a HID over i2c spec that mimics the USB HID spec making this restriction make even less sense.
The hidkbd driver can now be built without `CONFIG_USBHOST`.  There is no functional change.
Testing with my keyboard feather device which implements this interfaces via an i2c device.
```
nsh> hidkbd
Opening device /dev/kbda
Device /dev/kbda opened
test device
```

hidkbd: Do not require CONFIG_USBHOST for the app

---

netutils/ntpclient/Kconfig

netutils/ntpclient/Kconfig: Add NETUTILS_NTPCLIENT_STAY_ON
It's used in the code but missing in Kconfig.
I guess the PR [1] forgot to add this.
Make it "y" by default because it seems like the original behavior
before the PR [1].  I have no strong opinions on the default
either ways.
[1] https://github.com/apache/incubator-nuttx-apps/pull/570
tested on qemu with lm3s6965-ek:qemu-protected (with https://github.com/apache/incubator-nuttx/pull/2851)

netutils/ntpclient/Kconfig: Add NETUTILS_NTPCLIENT_STAY_ON

---

examples/watchdog/watchdog_main.c

Fix printf format warnings when building with `CONFIG_DEBUG_WATCHDOG` enabled.
No impact.
- nrf52832-dk:wdog

examples/watchdog: Fix printf format warnings

---

wireless/bluetooth/nimble/Kconfig

Pin Nimble release to working commit until stable tag is ready
See issue noted here: https://github.com/apache/incubator-nuttx-apps/issues/592
CI should function again
CI passes this was a previously tested sha.

Pin Nimble release to working commit until stable tag is ready

---

nshlib/Kconfig

Currently it is not possible to disable the `mkfatfs` NSH command due to a typo in the `FSUTILS_MKFATFS` configuration in the dependency list.
No impact, since no board configuration currently selects `NSH_DISABLE_MKFATFS`
`NSH_DISABLE_MKFATFS` option properly appear on `make menuconfig` after dependencies are satisfied.

nshlib: Fix dependency on FSUTILS_MKFATFS

---

canutils/candump/candump.c
canutils/cansend/cansend.c

Global print_usage function in canutils/candump/ was causing double definition error while compiling NuttX with some extern apps, like pysimCoder for example. Therefore the following change to static function. To be on safe side, the same change was also done in cansend.
Tested on Teensy 4.1 with pysimCoder.

canutils: changed print_usage function to static

---

examples/watcher/Kconfig

Watcher application makes use of the Note RAM Driver and also calls `mkfatfs` function which is only available if `FSUTILS_MKFATFS` is provided.
This PR makes the dependencies explicit on Kconfig.
No impact, only `esp32-devkitc:watcher` included Watcher application, and it already included both dependencies.
Watcher example application no longer shows when dependencies are missing.

examples/watcher: Add missing dependencies on Kconfig

---

fsutils/mkfatfs/mkfatfs.c

apache/incubator-nuttx#2861 updates `struct geometry` to use `uint32_t` instead of `size_t`. This PR alters the format string used for printing geometry details.
Along with the other PR, this PR fixes geometry support on platforms where `size_t` is not 32 bits.
CI tests only.

fsutils: update geometry size (c.f. apache/incubator-nuttx#2861)

---

system/cle/cle.c

As noted by @v01d in [incubator-nuttx#2838](https://github.com/apache/incubator-nuttx/pull/2838#issuecomment-778363299), there was a missing whitespace after the NSH prompt.
It seems it was due to a bug in the CLE application, which was miscalculating the initial cursor position. At first, after printing the "nsh> " prompt the Host correctly reports the initial cursor position as `ESC ] 39 ; 6 R`, which means **row:39** and **column:6**.
But, next the CLE app calculates an offset of 5 (column - 1) for the initial cursor position. But, this offset is sent to the Host later as if the first column was 0.
```
NuttShell (NSH) NuttX-10.0.1
nsh> Returning: .[1b]
Returning: [[5b]
Returning: 3[33]
Returning: 9[39]
Returning: ;[3b]
Returning: 6[36]
Returning: R[52]
row=39 column=6
row=39 column=6 …
```

Fix CLE initial cursor position

---

include/netutils/ntpclient.h
netutils/ntpclient/ntpclient.c
system/ntpc/Makefile
system/ntpc/ntpcstatus_main.c

Add ntpcstatus command, which shows the client status.
```
nsh> ntpcstatus
The number of last samples: 5
[0] srv 178.16.23.50 offset -0.014006560 delay 0.349967444
[1] srv 5.9.57.158 offset 0.001792161 delay 0.269991633
[2] srv 206.75.147.25 offset 0.009916600 delay 0.129989672
[3] srv 162.159.200.1 offset 0.011508908 delay 0.019917401
[4] srv 185.19.184.35 offset 0.021468135 delay 0.239915030
nsh> 
```
this depends on https://github.com/apache/incubator-nuttx/pull/2869
tested locally with `lm3s6965-ek:qemu-protected` config.

ntpclient: Add api and command to query status

---

system/i2c/README.md
system/i2c/i2c_get.c
system/i2c/i2c_main.c
system/i2c/i2c_set.c
system/i2c/i2c_verf.c
system/i2c/i2ctool.h

Fix several typos in the "repetitions" word.
No impact.
Not applicable.

system/i2c: Fix typo in "repetitions" word

---

netutils/thttpd/thttpd.c
netutils/thttpd/thttpd_cgi.c
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

Merges the socket array info file descriptor array. this patch associated with patch:
https://github.com/apache/incubator-nuttx/pull/2899
daily test.

net/socket: change config CONFIG_NSOCKET_DESCRIPTORS to CONFIG_NFILE_DESCRIPTORS

---

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

Recover POLLSOCK and support  polling directly by socket, this patch associated with #2899

net/socket: recover POLLSOCK and support polling directly by socket

---

netutils/thttpd/thttpd.c

netutils/thttpd: fix compile break
change NSOCKET_DESCRIPTORS to NFILE_DESCRIPTORS

netutils/thttpd: fix compile break

---

netutils/dhcpd/dhcpd.c

Fix printf format error based on different chip arches.
Test with PR: https://github.com/apache/incubator-nuttx/pull/2939.

netutils/dhcpd: Fix printf format error based on different chip arches

---

system/i2c/Makefile
system/i2c/i2c_devif.c
system/i2c/i2c_main.c
system/i2c/i2c_reset.c
system/i2c/i2ctool.h

This PR intends to add a new command to the I2C tool for enabling a quick test of the Reset function.
No impact, new command for the I2C tool.
Tested with `esp32c3-devkit`.

system/i2c: Add command for resetting an I2C bus

---

examples/README.md
examples/romfs/romfs_main.c
examples/unionfs/unionfs_main.c
graphics/ft80x/ft80x_audio.c
include/graphics/ft80x.h
netutils/usrsock_rpmsg/Kconfig
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
nshlib/README.md
nshlib/nsh.h

Dynamically allocated file descriptor and delete NFILE_DESCRIPTORS limits. This patch associates with https://github.com/apache/incubator-nuttx/pull/3045.
daily test

app: delete NFILE_DESCRIPTORS limits

---

netutils/iperf/iperf.c
netutils/iperf/iperf_main.c

iperf: plug memory leaks
tested locally on an esp32 board

iperf: plug memory leaks

---

netutils/thttpd/Kconfig
netutils/thttpd/thttpd.c
netutils/thttpd/thttpd_cgi.c

using THTTPD_NFILE_DESCRIPTORS instead of NFILE_DESCRIPTORS. This patch associates with https://github.com/apache/incubator-nuttx/pull/3045.
daily test

thttpd: add THTTPD_NFILE_DESCRIPTORS

---

examples/watched/watched.c
examples/watched/watched.h
examples/watched/watched_main.c
examples/watcher/Kconfig
examples/watcher/task_mn.c
examples/watcher/watcher_main.c
examples/watcher/wdt.c

This PR:
1.  Fixes an assert failure that was being caused because the print logs were being done from the ISR context.
Now, the ISR only signals a signal handler, which then print tasks that starved the dog. 
2. Improve some minor things like comments.
All watcher/watched examples.

apps/examples/watcher: Fixed an assert failure

---

examples/mtdpart/Kconfig
examples/mtdrwb/Kconfig

select CONFIG_BCH in a few places
for https://github.com/apache/incubator-nuttx/pull/3061
`sim:mtdpart` and `sim:mtdrwb` are built with https://github.com/apache/incubator-nuttx/pull/3061

select CONFIG_BCH in a few places

---

netutils/dhcpd/dhcpd.c
netutils/telnetd/telnetd_daemon.c

dhcpd/telnet: don't need to dupcalite listen socket when task_create. this patch associates with https://github.com/apache/incubator-nuttx/pull/3045
normal using telnetd/dhcpd.
daily test

dhcpd/telnet: don't need to dupcalite listen socket when task_create

---

testing/ostest/Makefile
testing/ostest/ostest.h
testing/ostest/ostest_main.c
testing/ostest/sporadic2.c

This commit adds the test developed by Jan Staschulat with Issue #apache/incubator-nuttx/2935
It is expected to cause the OS test to fail for the time being since that issue reports a bug (that has been corrected; no bug is reported by OS test).
The test is rather long (about 10 minutes), however, that is only if the sporadic scheduler is enabled.  I don't think it ever is.
Tested using the (new) stm32f4discovery:sporadic configuration.

Extend Testing of Sporadic Scheduler in OS test

---

fsutils/mksmartfs/Kconfig

This PR intends to fix a regression caused by PR [3061](https://github.com/apache/incubator-nuttx/pull/3061), which separated the BCH logic from CONFIG_DISABLE_MOUNTPOINT.
Since the Block-to-character driver is not built by default, `mksmartfs` fails to open the file descriptor of the MTD block device.
Fix `mksmartfs` NSH command on targets that support SMARTFS file system.
`esp32-devkic:spiflash` and also on custom configuration for `sim`
`fstest` also executed to completion.
Previous behavior:
```shell
NuttShell (NSH) NuttX-10.0.1
nsh> mksmartfs /dev/smart0
nsh: mksmartfs: mksmartfs failed: 2
nsh> 
```
With proposed change:
```shell
NuttShell (NSH) NuttX-10.0.1
nsh> mksmartfs /dev/smart0
nsh> 
```

fsutils/mksmartfs: Fix regression caused by BCH separation

---

examples/qencoder/qe_main.c

- Fix printf() had "%d" but argument was int32_t by changing format string to "%ld" and casting the int32_t to long int for purposes of printing, to ensure portability.
- Fix nxstyle errors.
Removes compiler warnings and nxstyle errors.
- build testing
- nxstyle

examples/qencoder: Fix printf() warning

---

netutils/dhcpd/dhcpd.c

netutils/dhcpd: handshake the dhcpd message with server port. 
resolve the dhcpd compatibility issues on some strict system, such as Windows XP,7,10
DHCPD  lease the address
DHCPD offer/lease the address to windows PC

[DHCPD Compatibility with Windows XP,7,10] netutils/dhcpd: handshake the dhcpd message with server port. 

---

examples/README.md
examples/termios/Kconfig
examples/termios/Make.defs
examples/termios/Makefile
examples/termios/termios_main.c

This example uses the termios interface to reconfigure serial parameters.
N/A
Tested in ESP32-C3 devkitc.

apps/examples: Adds termios example

---

fsutils/mkfatfs/Kconfig

Similar situation as #624 
mkfatfs doesn't report issues anymore.
sim:nsh

fsutils/mkfatfs/Kconfig: Select BCH

---

examples/oneshot/oneshot_main.c

This little PR is intended only to:
* Fix a wrong constant that was being used to convert time unities and 
* Refactor the code using constant definitions instead of raw numbers. 
N/A
After the changes the maximum delay became correct.

examples/oneshot: fixed wrong constant and refactored

---

testing/fstest/fstest_main.c

fstest: Fix printf format error
fstest will pass on CI test
ESP32-C3

fstest: Fix printf format error

---

Application.mk

This PR intends to revert a change from PR #626 that introduced a regression to the build system.
After a configuration change that modifies the list of builtin applications, the build system will not generate the updated object files for the builtin application list, resulting in linker errors.
Fix to the build system.
Follow the steps to reproduce the issue:
```shell
$ ./tools/configure.sh -E sim:nsh
$ make
$ make menuconfig
$ make
```
It will result in the following error:
```shell
/usr/bin/ld: nuttx.rel:(.data.rel.ro+0x7b0): undefined reference to `hello_main'                         
collect2: error: ld returned 1 exit status …
```

build: Fix builtin list regeneration after config update

---

canutils/candump/candump.c

optind, et al, are not longer simple globals variables (after incubator-nuttx PR 3170).  Redundantly externing them in application code now results in compilation errors.
Need for compile with incubator_nuttx PR 3170.  No other impact expected.
CI only

candump.c:  Must not extern optind, et al

---

testing/fstest/fstest_main.c

The fstest allow to create random file name with 1 character, then the filename collides often.
Avoid creating files with only 1 character to fix the error when the fstest try to create another file with same name.
ESP32-C3

fstest: Force the minimum filename to 4 to avoid collisions

---

examples/mqttc/README.md
examples/mqttc/mqttc_pub.c

Provide a sane hostname default (I used a public test broker for convenience). Otherwise it results in a crash since the
hostname variable was uninitialized. I also made slight improvements to output.
Fix potential crash in example app.
esp32-devkitc:wapi

mqttc example: provide sane hostname default to avoid crash

---

include/netutils/httpd.h
netutils/webserver/httpd.c
netutils/webserver/httpd_cgi.c

This exposes https_send_headers (previously send_headers) to public interface so it can be used from within
a CGI handler (otherwise there's no way to build a complete HTTP response).
I also added some comments to existing functions.
Make public internal HTTPD interface.
esp32-devkitc:wapi

httpd: expose http_send_headers to be used in CGI handlers

---

examples/lvgldemo/Makefile
examples/lvgldemo/fbdev.c
examples/lvgldemo/fbdev.h
examples/lvgldemo/lcddev.c
examples/lvgldemo/lcddev.h
examples/lvgldemo/lvgldemo.c

This provides an adaptor for using lvgl with the lcddev in addition to the fbdev. As part of this it also fixes a compilation error when fbdev was used with CONFIG_FB_UPDATE.  There is also a monitoring callback enabled for monitoring the performance of the demo.
lvgldemo can now be used without requiring a framebuffer to be created.
You can see the demo running on my keyboard feather using the lcddev here (ignore the terrible refresh rate, that is due to the 8MHz SPI bus and DMA limitations I am addressing):
```
NuttShell (NSH) NuttX-10.0.1
nsh> lvgldemo
VideoInfo:
fmt: 11
xres: 240
yres: 320
nplanes: 1
PlaneInfo (plane 0):
bpp: 16
tp_init: Opening /dev/input0
76800 px refreshed in 2250 ms
```

lvgldemo: Add support for lcddev

---

.github/workflows/build.yml

follow up nuttx-testing repo change:
```
commit 08d766faef84e43112b70a08f6f0c54654482024
Date:   Sun Apr 4 04:21:57 2021 +0800
Split sim.dat to sim00.dat and sim01.dat
to speed up the macOS build
```
Speed up the CI check
Pass CI

build: Replace sim with sim01 and sim02

---

testing/ostest/getopt.c

- Fix optind range checking.  optind may index through argc (to the NULL argv entry) on the last option since optind is required to always point to the next command line argument.
- Add two more test cases were the final thing on the command line is an invalid long option.
- Fix a check that used an older, obsoleted hard-coded value that was not updated.
This should have no impact other than to the getopt() test cases of the OS test.
Tested on the simulator using a modified NSH configuration.

testing/ostest:  More improvements to getopt() testing/ostest

---

testing/ostest/getopt.c

The Linux man page requires that the getopt_long() and getopt_long_only() functions accept arguments to options in a form like:
--option=argument
This PR adds a test that missing functionality that was recently added to NuttX.
This change also fixes an error in string comparison that was working before only because of the way that strings are stored by in linker ELF.  The address of the strings were being compared, not the value of the string.
This change effects only the getopt() tests of the OS test.
Tested on a simulator NSH configuration and used to verify the NuttX change.

apps/testing/ostest:  Add test for required argument format

---

examples/lvgldemo/Makefile
examples/lvgldemo/lvgldemo.c

This PR intends to make the initialization of the LVGL input driver conditional to whether the board offers any input method.
With this PR, it is possible to build LVGL demo without enabling CONFIG_INPUT.
`esp32-wrover-kit` with LVGL

examples/lvgldemo: Enable build without input methods

---

.github/workflows/build.yml

This is the app half off https://github.com/apache/incubator-nuttx/pull/3318
CI tooling and docker container is now in the os repo.
CI should build.

CI: Migrate ci tooling from testing repository to main os repo

---

Application.mk

It's better to report error if user forget set PRIORITY or STACKSIZE
Build sytem
Pass CI

build: Remove the redundant check from Applicaiton.mk

---

examples/lvgldemo/Kconfig
examples/lvgldemo/fbdev.c
examples/lvgldemo/lcddev.c

This PR intends to add support for asynchronous flush operation on the `lvgldemo` example application, for both the Framebuffer and LCD character devices.
This enables the parallelization of the rendering of the next frame by LVGL and the drawing of the current frame to the display device.
Expected some performance improvement when `CONFIG_EXAMPLES_LVGLDEMO_DOUBLE_BUFFERING` is also enabled.
No impact if `CONFIG_EXAMPLES_LVGLDEMO_ASYNC_FLUSH` is not enabled.
Tested `sim:lvgl` with **Benchmark** and **Stress**  examples from `lvgldemo`.

examples/lvgldemo: Add support for asynchronous flush

---

netutils/webclient/webclient.c

webclient: 304 and 305 are not really redirects
Eg. The docker API sometimes returns 304 even for requests without etags.
https://docs.docker.com/engine/api/v1.40/#operation/ContainerStop
tested against the docker api
(not on nuttx, with my fork of webclient.c)

webclient: 304 and 305 are not really redirects

---

examples/lvgldemo/Kconfig
examples/lvgldemo/lvgldemo.c

This PR intends to add a configuration for enabling double buffering support to the **lvgldemo** example application.
New feature, should have no impact to existing configurations.
`sim:lvgl`

examples/lvgldemo: Add configuration for double buffering support

---

graphics/lvgl/Kconfig
graphics/lvgl/lv_conf.h

This PR intends to add a new option for enabling LVGL's performance monitor, which adds a small widget at the bottom right corner for showing CPU usage and FPS count real-time stats.
New feature, no impact if not used.
`sim:lvgl`

graphics/lvgl: Add config to enable LVGL Performance Monitor

---

examples/lvgldemo/Kconfig
examples/lvgldemo/lv_ex_conf.h

This PR intends to add a new config for enabling Slideshow mode for the LVGL Widgets example demo.
New feature, no impact if not selected.
`sim:lvgl`

examples/lvgldemo: Add config to enable Slideshow mode for Widgets demo

---

examples/ajoystick/Kconfig
examples/buttons/Kconfig
examples/buttons/buttons_main.c
examples/djoystick/Kconfig
examples/touchscreen/tc_main.c
graphics/pdcurs34/nuttx/Kconfig

This PR intends to fit the INPUT configs to the new naming template from https://github.com/apache/incubator-nuttx/pull/3482.
Just renaming, should have no impact.
Build tests.

examples: Fit INPUT related configs to new naming template

---

examples/README.md
examples/djoystick/djoy_main.c

This PR intends to fixup #675, which missed one DJOYSTICK macro.
Fix CI build from https://github.com/apache/incubator-nuttx/pull/3482
Successfully built `open1788:pdcurses` configuration

examples: Update missing DJOYSTICK macro to new INPUT template

---

examples/README.md
examples/foc/Kconfig
examples/foc/Make.defs
examples/foc/Makefile
examples/foc/README.md
examples/foc/foc_adc.h
examples/foc/foc_cfg.h
examples/foc/foc_debug.h
examples/foc/foc_device.c
examples/foc/foc_device.h
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_main.c
examples/foc/foc_mq.c
examples/foc/foc_mq.h
examples/foc/foc_thr.h

Add FOC motor controller example.
For now, only open-loop velocity control is supported.
Depends on https://github.com/apache/incubator-nuttx-apps/pull/677
Tested with SIM and STM32

Add FOC motor controller example

---

wireless/ieee802154/i8sak/i8sak_scan.c
wireless/ieee802154/i8sak/i8sak_tx.c

i8sak: Fixes bug where daemon was being requested again when operation is finished, instead of being released.
Running the i8sak tx or i8sak scan app repeatedly won't keep requesting the daemon count over and over and things should shut down as it's supposed to.
Built and ran configuration.

i8sak: Fixes bug where daemon was being requested again

---

testing/ltp/0001-Fix-static-struct-warning.patch
testing/ltp/0002-Use-ifdef-instead-of-if-for-__linux__.patch
testing/ltp/Makefile

This adjusts the build for LTP so that it can pass the CI system and build correctly.
Should be able to enable LTP configuration.
With this PR https://github.com/apache/incubator-nuttx/pull/3510 I am able to build the sim:ltp configuration with our standard build flags `make EXTRAFLAGS="-Werror -Wno-cpp" -j8`

ltp: Resolve compile warnings

---

examples/lvgldemo/Kconfig

This PR intends to make LVGL demo input-related options depend on CONFIG_INPUT.
The motivation is for easing the usage of the `lvgldemo` with displays that don't support touch input.
Now `CONFIG_EXAMPLES_LVGLDEMO_CALIBRATE` will only be selected by default if `CONFIG_INPUT` is also selected. So, in practice, there will be no real impact, since this is the only useful combination.
`sim:lvgl` successful build with `CONFIG_INPUT=n` and proper execution with disabled input, as expected.

examples/lvgldemo: Make input options depend on CONFIG_INPUT

---

include/wireless/wapi.h
wireless/wapi/src/wapi.c
wireless/wapi/src/wireless.c

Fix issue of getting the incorrect operating frequency flags.
- None
`wapi show <ifname>`

wireless/wapi: Fix issue of getting the operating frequency

---

examples/lvgldemo/Makefile
examples/lvgldemo/lvgldemo.c
examples/lvgldemo/tp.h

This PR intends to fix a build warning introduced in recent PRs related to LVGL demo application.
It also changes some `ifdef`s that were checking for `CONFIG_INPUT` in favor of more specific input subclasses configs (`CONFIG_INPUT_TOUCHSCREEN` or `CONFIG_INPUT_MOUSE`)
No impact, only fix build warning.
`sim:lvgl` with an without input configurations

example/lvgldemo: Fix "unused-but-set-variable" build warning

---

wireless/wapi/src/wapi.c

When a command was executed `EXIT_SUCCESS` was always returned even if the command failed.  This made the `echo $?` return not reliable.
Fix return of WAPI commands
Tested with ESP32.
Before:
```
nsh> wapi essid wlan0 wrongssid 1
ioctl(SIOCSIWESSID): 1
ERROR: Process command (essid) failed.
nsh> echo $?
0
```
After
```
nsh> wapi essid wlan0 wrongssid 1
ioctl(SIOCSIWESSID): 1
ERROR: Process command (essid) failed.
nsh> echo $?
1
```

wireless/wapi/src/wapi.c: When executing a command return it's error code on failure.

---

examples/mqttc/mqttc_pub.c

This little MR intends to prevent a dump when the broker ip address is not valid.
To achieve this purpose, we set fd to -1, so even if the socket function returns
a valid fd, in case the connect function fails, fd will be invalidated preventing the 
rest of the code to execute. Instead, it will print `ERROR! Couldn't create socket`
and leave the program.
Target: MQTT users.
Consequence: People will not have a dump when type a wrong broker ip address. 
I passed a wrong IP broker address. It showed the expected error message.
I passed a valid IP broker address. It connected and published as expected.
PS: The coding style will fail due to a Mixed case identifier.

examples/mqttc: Makes fd invalid when connect() fails.

---

interpreters/ficl/Makefile

A NuttX user told that ficl wasn't working as suggested in the
README.txt, then I found that the root cause was the order of the
Make.srcs inclusion inside the Makefile. I think we can do better:
we could automate the process to download and configure ficl.
Users will get ficl support working on NuttX
Compiled correctly

interpreters/ficl: Fix compilation issue

---

examples/modbus/Kconfig
examples/modbus/modbus_main.c

Improve Modbus slave example and let it to control USERLEDs
User will be able to control USERLEDs over Modbus
STM32F4Discovery
NOTE: CI will fail because Modbus used Mixed case, please ignore it.

Improve modbus example and let it to control USERLEDs

---

netutils/usrsock_rpmsg/Kconfig
netutils/usrsock_rpmsg/usrsock_rpmsg_server.c

netutls/usrsock_rpmsg_server: add support for send reassemble 
usrsock/server: replace the wakeup source to eventfd
usrsock rpmsg
usrsock rpmsg sanity test on sim/rpserver sim/rpproxy

netutls/usrsock_rpmsg_server: add support for send reassemble 

---

nshlib/nsh_routecmds.c

addroute: inet_pton cannot accept slash notation.  We must fixup the argument before calling.
Fix addroute for cases using slash notation.
Built and ran configuration.

addroute: inet_pton cannot accept slash notation. 

---

system/spi/spi_exch.c

This PR intends to improve the output of the `exchange` command of SPI tool. This eases the comparison for testing SPI with looped back MOSI and MISO signals.
Visual impact to the output of `exchange` command of SPI tool.
Tested with `esp32c3-devkit` platform by looping back MOSI and MISO pins, width configured as 16-bit:
```shell
nsh> spi exch -x 15 DEADA55ABEEFA55ADEADA55ABEEFA55ADEADA55ABEEFA55ADEADA55ABEEF
Sending: ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 
Received: ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 5AA5 ADDE 5AA5 EFBE 
```

system/spi: Print sent data in the same way as received.

---

netutils/dhcpc/Kconfig

DHCPC depends on CONFIG_NET_UDP_BINDTODEVICE in many cases.  Safest thing is to just auto-select it whenever DHCPC is selected.
There may be circumstances where CONFIG_NET_UDP_BINDTODEVICE is not needed.  There are existing DHCPC configurations that do not set CONFIG_NET_UDP_BINDTODEVICE
$ find boards/ -name defconfig | xargs grep -l CONFIG_NETUTILS_DHCPC | xargs grep -l CONFIG_NET_UDP=y | wc -
26      26    1496 -
$ find boards/ -name defconfig | xargs grep -l CONFIG_NETUTILS_DHCPC | xargs grep -l CONFIG_NET_UDP=y | xargs grep -l BINDTODEVICE | wc -
6       6     323 -
In the past, CONFIG_NET_UDP_BINDTODEVICE was not needed if there was only a single network device.  But things have changed.
Only successful configuration and build was verified.

apps/netutils/dhcpc/Kconfig:  Auto-select CONFIG_NET_UDP_BINDTODEVICE

---

netutils/dhcpc/Kconfig

- This commit fixes the renew command with the usrsock
- https://github.com/apache/incubator-nuttx-apps/pull/696#issuecomment-828930765
- None
- Tested with spresense:wifi and esp32-devkitc:wapi

netutils: dhcpc: Fix Kconfig for the usrsock

---

netutils/webclient/webclient.c

If a connection to the HTTP server cannot be established, the socket descriptor will leak.
I tested my local app.

netutils/webclient: Fixed socket descriptor leak.

---

system/spi/Kconfig
system/spi/README.md
system/spi/spitool.h

This PR intends to address some documentation issues I found while studying the SPI Slave architecture.
Related to: https://github.com/apache/incubator-nuttx/pull/3662
No impact, just changes to documentation.
Not applicable.

system/spi: Adopt CPHA as the abbreviation for clock phase

---

nshlib/nsh_telnetd.c

nsh/telnetd: bringup the network before telnetd init 
bringup the network before telnetd init if without NSH_CONSOLE
Fix: 
https://github.com/apache/incubator-nuttx/issues/3663
./tools/configure.sh -l photon:wlan

nsh/telnetd: bringup the network before telnetd init 

---

nshlib/nsh_console.c
nshlib/nsh_console.h
nshlib/nsh_telnetd.c

nshlib: Fix the build break in nsh_telnetd.c when CONFIG_NSH_CONSOLE=n
set the config:
CONFIG_NSH_ROMFSETC=y
CONFIG_NSH_CONSOLE=n
nsh_telnetd.c: In function 'nsh_telnetstart':
nsh_telnetd.c:267:22: error: 'vtbl' undeclared (first use in this function)
267 |       nsh_initscript(vtbl);
|                      ^~~~
CONFIG_NSH_ROMFSETC=y
CONFIG_NSH_CONSOLE=n
./tools/configure.sh -l photon:wlan

nshlib: Fix the build break in nsh_telnetd.c when CONFIG_NSH_CONSOLE=n

---

netutils/netlib/netlib_parseurl.c

For EINVAL, it doesn't make sense to keep parsing.
(For E2BIG, it might make some sense.)
Found by LLVM ASan.
Tested with my local app.

netlib_parseurl.c: Fix string overruns

---

system/adb/shell_pipe.c

Fix wrong dup2 return value check after:
[fs: file_dup2 shouldn't hold the file list lock](https://github.com/apache/incubator-nuttx/commit/1e5bfa623aa93b918566e8dc0e2f9c1a1037f45e)
Fix issue in adb shell introduced in:
[nsh: Pass the correct command lines to nsh_consolemain](https://github.com/apache/incubator-nuttx-apps/commit/6aca60133c663cae0de8fa31a64b472f8675fcbb)
Tested on board "raspberrypi-pico" with enc28j60:
```
$ adb connect xxx.xxx.xxx.xxx:5555
$ adb shell
NuttShell (NSH) NuttX-10.1.0-RC1
nsh> help
help usage:  help [-v] [<cmd>]
.         cat       delroute  false     kill      nslookup  route     truncate  
[         cd        df        free      ls        printf    set       uname     
?         cp        dmesg     help      mkdir     ps        sleep     umount    
addroute …
```

system: adb: fix shell service

---

examples/hdc1008_demo/hdc1008_main.c

An extra "%d" that shouldn't be there.
Only the hdc1008_demo app. Warning removed.
Tested on custom board and it works the same way, but the warning is gone.
Thanks!

examples/hdc1008_demo: fix wrong printf parameter

---

examples/bastest/bastest_main.c
examples/elf/elf_main.c
examples/module/module_main.c
examples/posix_spawn/spawn_main.c
examples/romfs/romfs_main.c
examples/sotest/sotest_main.c
examples/unionfs/unionfs_main.c

C file changes:
examples/bastest/bastest_main.c
examples/elf/elf_main.c
examples/module/module_main.c
examples/posix_spawn/spawn_main.c
examples/romfs/romfs_main.c
examples/sotest/sotest_main.c
examples/unionfs/unionfs_main.c
Depends on defconfig changes in nuttx. PR is https://github.com/apache/incubator-nuttx/pull/3689
Tested on local simulator

Apps Issue #246: Replace romdisk_register() with boardctl(BOARDIOC_ROMDISK)

---

examples/embedlog/Make.defs
examples/embedlog/Makefile
examples/embedlog/embedlog_main.c
system/embedlog/Kconfig
system/embedlog/Make.defs
system/embedlog/Makefile

Changes from v0.4.0
- add thread safety code
- add option to print function info (name) in logs
- abi/api stabilization
- bug fixes + increased reliability
Tested on nucleo-f091
Signed-off-by: Michał Łyszczek <michal.lyszczek@bofc.pl>

system/embedlog: update to v0.6.0

---

examples/hdc1008_demo/hdc1008_main.c

No mode was set before the first read by the app.
The first time the app was run, it worked properly, reading temperature and humidity on the first read(). But subsequent reads returned humidity only since that was last mode set up. Also, the ioctl read was returning invalid results.
First run of the app:
```
nsh> hdc1008
Temperature and humidity
========================
data=20.54 56.9
Temperature and humidity (ioctl)
================================
t=20.54, h=56.9
Temperature, 11 bit resolution
==============================
data=20.78
Temperature, 14 bit resolution
==============================
data=20.69
Humidity, 8 bit resolution
===========
data=57.1
Humidity, 11 bit resolution
===========
data=56.9
Humidity, 14 bit resolution
===========
data=56.9
```
Second run of the app: …

hdc1008_demo: set intial measurement mode

---

.github/workflows/build.yml

follow up the kernel side chnage(https://github.com/apache/incubator-nuttx/pull/3710):
```
commit 09a0ed111c0c193a57b2a538e23c2b6a6e9cdf26
Date:   Thu May 13 21:28:43 2021 +0800
tools/ci: Rename sim0x.dat to sim-0x.dat to align with arm-xx.dat
To avoid the build break sim0x.dat will remove in the upcoming patch
```
Pass CI

ci: change sim01 and sim02 to sim-01 and sim-02

---

examples/nxflat/nxflat_main.c
examples/thttpd/thttpd_main.c

The original PR is: https://github.com/apache/incubator-nuttx-apps/pull/709
examples/nxflat/nxflat_main.c and examples/thttpd/thttpd_main.c are listed in Apps issue #246 but were not included in the original PR (linked above). This PR contains the change  from romdisk_register() to boardctl(BOARDIOC_ROMDISK) for examples/nxflat/nxflat_main.c and examples/thttpd/thttpd_main.c.
None
Change from romdisk_register() to boardctl() has been tested in the original PR.

Apps Issue #246:Replace romdisk_register() with boardctl(BOARDIOC_ROMDISK)

---

testing/ostest/timedmutex.c

ostest: Include errno.h in timedmutex.c

---

examples/nxflat/nxflat_main.c
examples/thttpd/thttpd_main.c

Please refer to this error: https://github.com/apache/incubator-nuttx-apps/issues/246#issuecomment-844306537
Solution: Add check for CONFIG_BOARDCTL_ROMDISK because CONFIG_BOARDCTL_ROMDISK must be set to enable boardctl(BOARDIOC_ROMDISK) in these 2 files:
examples/nxflat/nxflat_main.c
examples/thttpd/thttpd_main.c (Added the check to thttpd_main.c for consistency)
boardctl(BOARDIOC_ROMDISK) is enabled

Check CONFIG_BOARDCTL_ROMDISK is set for boardctl(BOARDIOC_ROMDISK) call.

---

system/vi/vi.c

Using Arrow keys in vi when in INSERT mode causes abnormal behaviour
vi text editor
Tested with Minicom 2.7.1

Arrow keys not working when in INSERT mode

---

wireless/bluetooth/nimble/Kconfig
wireless/bluetooth/nimble/Makefile

which contain the following fix(https://github.com/apache/mynewt-nimble/pull/979):
```
commit cd8ab38c3da91b71dd428979153a408f38d3b02e
Date:   Thu May 20 15:43:50 2021 +0800
nuttx: fix error: use of undeclared identifier 'ENOMEM'
```
Minor
Pass CI

nimble: Update version to cd8ab38c3da91b71dd428979153a408f38d3b02e

---

examples/nxflat/tests/Makefile

The issue is described here: https://github.com/apache/incubator-nuttx/issues/3737#issuecomment-844574935

examples/nxflat: fixed an issue with the symbol table creation

---

examples/termios/termios_main.c

This is a small fix on an instruction message to the user, the `databits` should be 7 instead of 5 to be compliant with the code.
From now on, if the user copy the message to paste in the terminal, it will work properly.
It wouldn't work before because the message was with a `databits` different from the configured in the example.  
N/A

examples/termios: Small fix on a print message

---

system/psmq/Kconfig
system/psmq/Make.defs
system/psmq/Makefile
system/psmq/README.md

This release breaks API and ABI by making use of library way
easier and more safe. No app in a nuttx tree uses psmq, so
nothing in-tree will be broken by this change.
Updated license files to Apache 2.0.
Tested on nucleo-f091
Signed-off-by: Michał Łyszczek <michal.lyszczek@bofc.pl>

system/psmq: update to v0.2.1

---

graphics/twm4nx/apps/cclock.cxx

Fix the error reported here:
https://github.com/apache/incubator-nuttx/pull/3712/checks?check_run_id=2649571891
Minor
Pass CI

graphics/twm4nx: Fix error: 'sleep' was not declared in this scope

---

nshlib/nsh_command.c

Fix the build break at:
https://github.com/apache/incubator-nuttx/pull/3738/checks?check_run_id=2652977519
Minor
Pass CI

nsh: Add debug.h inclusion in nsh_command.c

---

system/readline/readline_common.c

This PR intends to provide a fix to readline command history when the top (i.e. last issued) command is issued twice.
Steps to reproduce the issue:
```shell
NuttShell (NSH) NuttX-10.1.0-RC1
nsh> ls    # Issued the ls command
/:
dev/
proc/
nsh> pwd   # Issued the pwd command
/
nsh> pwd   # UP key pressed here, pwd shown as expected
/
nsh> ls    # UP key pressed again, ls erroneously shown
```
NSH with `CONFIG_READLINE_CMD_HISTORY` enabled.
Reproduced the issue with `sim:nsh` and checked that the provided patch fixes the issue.

readline: Reset offset when top command is issued repeateadly

---

examples/termios/Kconfig
examples/termios/termios_main.c

This PR adds a small feature to the termios example.
Exposing how to disable the HW flow control using the termios interface.
N/A
First I configured the HW flow control in my device (ESP32-C3 - this PR support will come), then I ran this example and after it I could disable the hw flow control from picocom and also disconnect the RTS and CTS line and the communication was successful.
P.S: Note that I also increased the delay before setting the configuration. It was done because less fast chips (like ESP32-C3) requires more time to drain out the printf message before re-configuring the serial parameters.

examples/termios: Adds option to disable HW flow control

---

examples/foc/foc_float_thr.c

examples/foc/foc_float_thr.c: fix incorect variable type
Controller motor works much smoother for f32 implementation
nucleo-g431rb/ihm16m1_f32

examples/foc/foc_float_thr.c: fix incorect variable type

---

examples/pwm/pwm_main.c

examples/pwm: fix printf format warnings
None
CI

examples/pwm: fix printf format warnings

---

nshlib/nsh_command.c
nshlib/nsh_proccmds.c

nsh kill cmd can be executed with no signal option.
SIGTERM is the default signal, as in unix kill command.
**nsh>** kill [-\<signal\>] \<pid\>
Using SIGTERM as default signal makes nsh kill command to get closer to the unix version.
Given that NuttX allows to change the signal number of any signal and that default signal# for SIGTERM in NuttX is 12 (and 15 for POSIX signal), it is hard to guess what signal should be used to nicely kill a task.
Thus by using a default SIGTERM signal in kill command, the user just has to use the "kill \<pid\>" to always terminate a task.
Tested in flat mode with CONFIG_SIG_DEFAULT=y as well as undefined.

Change NSH kill cmd to accept SIGTERM as default

---

nshlib/README.md
nshlib/nsh_command.c
nshlib/nsh_timcmds.c

user can use both UTC and local time now. Please ignore the false alarm from nxstyle:
nuttx/apps/nshlib/nsh_timcmds.c:115:35: error: Multiple data definitions
https://github.com/apache/incubator-nuttx-apps/pull/745/files#diff-9b1b76b8967bda035063f8c0c11a08b300ea647f90d68c5d2dfff178e4937843L115
New option
run date with/without -u

nsh/date: Support -u option

---

netutils/iperf/iperf.c

iperf: Do not busy loop on a connection closed by the peer
Tested on esp32-devkitc.
The peer was iperf on NetBSD.
> iperf version 2.0.5 (08 Jul 2010) pthreads

iperf: Do not busy loop on a connection closed by the peer

---

testing/getprime/getprime_main.c

- I noticed that sometimes getprime causes ASSERT in tls_getset.c
- This commit fixes this issue.
- None

testing: getprime: Fix to wait for all the threads to finish

---

examples/dhtxx/Kconfig
examples/dhtxx/dhtxx_main.c

DHTXX sensor example was using predefined devpath which was also different from the one registered in common stm32 board section. This change allows to define the devpath in configuration.
Tested on Nucleo F446RE with DHT11 sensor.

examples/dhtxx: added configuration option for dhtxx sensor devpath

---

wireless/wapi/src/util.c

Please ignore the nxstyle warning:
apps/wireless/wapi/src/util.c:431:6: error: Mixed case identifier found
Minor change

apps warning: add ether_h because  Wimplicit-function-declaration

---

include/netutils/webclient.h
netutils/webclient/webclient.c

webclient: Add a way to specify timeout
webclient
a fork of this was tested with my local app, using a crafted-to-be-slow http server.

webclient: Add a way to specify timeout

---

testing/fstest/fstest_main.c

to avoid the interference from the lasting run

testing/fstest: Add O_TRUNC flag in fstest_wrfile

---

examples/qencoder/qe_main.c

FIx compile error discovered in automatic control to [NuttX PR 3929](https://github.com/apache/incubator-nuttx/pull/3929) (unused label).

examples/qencoder: fix nxstyle warning and errors

---

builtin/exec_builtin.c
examples/elf/tests/hello/hello.c
examples/sotest/sotest_main.c

1. Fix few typos in builtin/ and sotest_main example.
2. Drop the 0x when printing pointers in elf/hello
No functional change.
esp32c3-devkit:elf esp32c3-devkit:sotest

Fix few typos in builtin/ and sotest_main example.

---

netutils/iperf/iperf.c

iperf: Fix an unused function warning seen with clang
build tested for sim/macos.

iperf: Fix an unused function warning seen with clang

---

examples/README.md
examples/timer_gpout/Kconfig
examples/timer_gpout/Make.defs
examples/timer_gpout/Makefile
examples/timer_gpout/timer_gpout_main.c

This PR adds one example.
This example uses the timer interrupt to periodically
change the state of a digital output.
The digital output may be a relay, a led or anything else.
This example can be very useful to validate timer drivers
by using a logic analyzer connected to the digital output.
This example, mainly differs from the timer example because it
waits on a sigwaitinfo() instead of using a signal handler.
This approach ensures a deterministic wake-up time when
the signal occurs.
N/A
Tested and published a video in NuttX Brasil channel running this example with a LA:
https://youtu.be/v4bSGF3b3v4

examples: Adds Timer gpout example

---

system/readline/readline_common.c

Fixing "last command" misbehavior when one command in history is a substring of another.
Fix the minor corner case

apps/system: fix command history behavior

---

netutils/usrsock_rpmsg/Kconfig

Avoid build break when user forget to select EVENT_FD
Default kconfig setting

usrsock/rpmsg/server: select eventfd by default

---

wireless/gs2200m/gs2200m_main.c

- This commit returns -errno to the caller
- gs2200m only
- NOTE: need to update the gs2200m driver in NuttX

wireless: gs2200m: Fix error handling in sendto_request()

---

netutils/ftpc/ftpc_getfile.c

A permission check is performed regardless of the result of stat(), and is used as a resume offset, which may result in invalid operation.
I tested my local app on my custom board.

netutils/ftpc: ftpc_getfile: Fixed permission check and resume offset.

---

nshlib/nsh_command.c
nshlib/nsh_fscmds.c

rm -r /path/to/remove work as the desktop
```
mkdir /tmp/test
echo hello > /tmp/test/hello
rm -r /tmp/test
```

nshlib: Add 'rm -r' recursive remove directory support

---

netutils/telnetd/telnetd_daemon.c

netutils/telnetd: use a larger buffer for a 64-bit pointer
compile tested

netutils/telnetd: use a larger buffer for a 64-bit pointer

---

nshlib/nsh_altconsole.c
nshlib/nsh_builtin.c
nshlib/nsh_console.c
nshlib/nsh_console.h
nshlib/nsh_consolemain.c
nshlib/nsh_fileapps.c
nshlib/nsh_system.c
nshlib/nsh_telnetd.c
nshlib/nsh_usbconsole.c

apps: add variable to identify main shell
This should be with
https://github.com/apache/incubator-nuttx/pull/4042
Root cause:
These modify for shell ctrl + C usefulness when system() execute.
1. execute 'cu' in shell front end, uart record 'cu' pid for later killing.
2. one thread use system() to do sth anything, uart record new pid for later killing.
3. ctrl +c can't kill 'cu' thread
FIX:
add param to nsh_newconsole() to identify the main shell & system cmd shell.

apps: add variable to identify main shell

---

Application.mk

apps/Application.mk: support compile same prefix file in one folder
example:
one folder has aa.s aa.c aa.cpp, then only compile one file.
fix:
add .s/S/c/cxx/cpp to $(SUFFIX)
Change-Id: I6dbc66dda2c10415a698513285313f59f7dda054
Signed-off-by: ligd <liguiding1@xiaomi.com>

apps/Application.mk: support compile same prefix file in one folder

---

netutils/ftpc/ftpc_connect.c

I fixed a problem where ftpc would close stdin (0).
ftpc_connect()
zero fill SESSION structure (cmd, data, dacceptor socket is zero)
and connect cmd socket.
ftpc_login()
execute login sequence on cmd socket.
ftpc_getfile() / ftpc_putfile()
connect data socket (PASV).
transfer data on data socket.
close socket. (descriptor set to -1)
ftpc_quit()
close all socket.
close cmd socket (OK).
close data socket (-1, so it'll be EBADF, it's OK).
close dacceptor socket (zero is stdin, stdin will be closed).
By setting the socket descriptor to -1 initially, stdin will not be closed.
I tested my local app, on Spresense.

netutils/ftpc: ftpc_connect: Fixed invalid socket close.

---

graphics/pdcurs34/nuttx/pdcdisp.c
graphics/pdcurs34/nuttx/pdcscrn.c

Fix a compile error when CONFIG_SYSTEM_TERMCURSES=y.
Fix a compile warning when CONFIG_PDCURSES_MULTITHREAD=n.
None
Run example/pdcurses.

graphics/pdcurs34: Fix compile error

---

examples/bmi160/sixaxis_main.c
examples/charger/charger_main.c
examples/configdata/configdata_main.c

Fix printf format warnings by -Wformat.
None
Run examples/bmi160, examples/charger and examples/configdata.

examples: Fix printf format warnings

---

include/system/nxlooper.h
system/nxlooper/nxlooper.c

```
nxlooper.c: In function 'nxlooper_opendevice':
Error: nxlooper.c:126:15: error: unused variable 'x' [-Werror=unused-variable]
126 |       uint8_t x;
|               ^
Error: nxlooper.c:125:15: error: unused variable 'supported' [-Werror=unused-variable]
125 |       uint8_t supported = true;
|               ^~~~~~~~~
In file included from nxlooper.c:40:
nxlooper.c: In function 'nxlooper_loopthread':
Error: nxlooper.c:482:15: error: format '%d' expects argument of type 'int', but argument 3 has type 'ssize_t' {aka 'long int'} [-Werror=format=]
482 |       audinfo("message received size %d id%d\n", size, msg.msg_id);
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
|                                                  |
|                                                  ssize_t {aka …
```

system/nxlooper: Fix the following compiler warning

---

crypto/.gitignore
crypto/Make.defs
crypto/Makefile
crypto/libtomcrypt/.gitignore
crypto/libtomcrypt/Kconfig
crypto/libtomcrypt/Make.defs
crypto/libtomcrypt/Makefile
crypto/libtomcrypt/digit-bit.patch
crypto/libtomcrypt/ltcrypt-flush.patch
math/.gitignore
math/Make.defs
math/Makefile
math/libtommath/.gitignore
math/libtommath/Kconfig
math/libtommath/Make.defs
math/libtommath/Makefile

This adds the initial support for the libtommath and libtomcrypt libraries.  These are setting the foundation for being able to run the dropbear ssh server/client on NuttX.
Simple crypto test
```
nsh> echo "hello world" > /tmp/pt.txt
nsh> ltcrypt aes /tmp/pt.txt /tmp/ct.bin
Enter key: nsh> hexdump /tmp/ct.bin
/tmp/ct.bin at 00000000:
0000: e3 89 05 22 d7 c1 cb 54 b5 2a b2 40 a9 c1 b6 22 ..."...T.*.@..."
0010: d9 83 ac 24 09 79 ca 47 db 3c c9 9e             ...$.y.G.<..
nsh> ltcrypt -d aes /tmp/ct.bin /dev/console
Enter key:
hello world
nsh> 
```
```
nsh> tommath_test
Digit size 64 Bit 
Size of mp_digit: 8
Size of mp_word: 16
MP_DIGIT_BIT: 60
MP_PREC: 32
SEED: 0x11a
TEST feature_detection
TEST trivial_stuff
TEST mp_get_set_i32
TEST mp_get_set_i64
TEST mp_and
TEST mp_cnt_lsb
TEST …
```

Add initial support libtommath and libtomcrypt libraries

---

Application.mk

wrong: file.c => file.dir.o
right: file.c => file.c.dir.o

Application.mk: correct depends file generated

---

system/cu/cu_main.c

Clear only the bits in `c_cflag` that will be set by cu.
Otherwise if even or odd parity is set all other bits of `c_cflag` will be cleared.
Including `CS8` default character size. And this will leads in the end to the error `EINVAL` in sanity checks on termios setting in `up_ioctl()` in stm32_serial:
https://github.com/apache/incubator-nuttx/blob/02a6966ad5de551a9f2adb0f97c21d404170c79b/arch/arm/src/stm32/stm32_serial.c#L2349-L2360

system/cu: fix setting termios with parity

---

netutils/dhcpd/dhcpd.c

to handle the multiple netcard correctly.
boot device with two net device, and run dhcpd to wait the client.

netutils/dhcpd: bind socket to the interface

---

include/netutils/webclient.h
netutils/webclient/webclient.c

This PR intends to add a new API for notifying the application of received HTTP header data.
The application shall register a callback function for receiving the HTTP header data line-by-line.
These changes were implemented after joint discussion on https://github.com/apache/incubator-nuttx-apps/pull/809#issuecomment-884600636 with @yamt.
New API to `webclient` library, should bring no impact to users if not explicitly used.
Custom application.

netutils/webclient: Notify HTTP header data via dedicated callback

---

include/industry/foc/fixed16/foc_cordic.h
include/industry/foc/float/foc_cordic.h
industry/foc/Kconfig
industry/foc/fixed16/foc_cordic.c
industry/foc/fixed16/foc_handler.c
industry/foc/fixed16/foc_picontrol.c
industry/foc/float/foc_cordic.c
industry/foc/float/foc_handler.c
industry/foc/float/foc_picontrol.c

industry/foc: add support for CORDIC
depends on https://github.com/apache/incubator-nuttx/pull/4244
nucleo-g431rb/ihm16m1_f32 and nucleo-g431rb/ihm16m1_b16

industry/foc: add support for CORDIC

---

testing/ostest/barrier.c
testing/smp/smp_main.c

testing: Remove duplicate pthread_barrierattr_init calls.
SMP and ostest programs.
esp32-devkitc:smp
esp32-devkic:ostest

testing: Remove duplicate pthread_barrierattr_init calls.

---

system/embedlog/Makefile

The `sed` command only with `-i` option has not been supported
on macOS platform, and so it causes build error on macOS.
Fix Makefile so that it passes on all platforms without using
`-i` option.
None
Build tested embedlog on Linux, Windows and macOS.

system/embedlog: Fix sed command usage for macOS

---

examples/media/media_main.c

format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'off_t' {aka 'long long int'}
Minor fix to avoid the warning
Pass CI

examples/media: Fix the compiler warning

---

examples/README.md
examples/elf/elf_main.c
examples/hidkbd/Kconfig
examples/hidkbd/hidkbd_main.c
examples/nxflat/nxflat_main.c
examples/posix_spawn/spawn_main.c
examples/sendmail/sendmail_main.c
nshlib/README.md
nshlib/nsh.h
nshlib/nsh_envcmds.c
system/hex2bin/Kconfig

follow other libc component naming convention
Follow up the kernel change: apache/incubator-nuttx#4267
Pass CI.

Rename LIB_ to LIBC_ for all libc Kconfig 

---

examples/README.md
examples/adc/Kconfig
examples/lvgldemo/lvgldemo.c
examples/module/Kconfig
examples/mount/Kconfig
examples/nx/Kconfig
examples/nxdemo/Kconfig
examples/nxhello/Kconfig
examples/nximage/Kconfig
examples/nxlines/Kconfig
examples/nxterm/Kconfig
examples/posix_spawn/spawn_main.c
examples/pwfb/Kconfig
examples/pwlines/Kconfig
examples/usbserial/Kconfig
graphics/nxwm/src/nxwm_main.cxx
graphics/twm4nx/Kconfig
graphics/twm4nx/src/twm4nx_main.cxx
nshlib/Kconfig
nshlib/nsh.h
system/adb/Kconfig
system/cdcacm/Kconfig
system/composite/Kconfig
system/nsh/Kconfig
system/nsh/nsh_main.c
system/usbmsc/Kconfig
system/usbmsc/README.md

since boardctl isn't a libc feature
Follow up the kernel change: https://github.com/apache/incubator-nuttx/pull/4266
Pass CI

Rename CONFIG_LIB_BOARDCTL to CONFIG_BOARDCTL

---

include/netutils/webclient.h
netutils/webclient/webclient.c

* webclient_perform
* Add a new flag to use non-blocking mode (WEBCLIENT_FLAG_NON_BLOCKING)
* Implement restarting
* Add a few associated API functions
* webclient_get_poll_info: get the descriptor info for poll/select
* webclient_abort: abort the operation (instead of restarting)
tested with my local app.

webclient: Implement non-blocking I/O

---

netutils/webclient/webclient.c

webclient: Add _s suffix to internal structures
To follow our coding standard.
I left the structures which is a part of the API for now.
(E.g. struct webclient_context)
nothing afaik
build test

webclient: Add _s suffix to internal structures

---

include/netutils/netlib.h

uint16_t is what's used in netlib and webclient in most of places.
There is a static analizer complaining on the type mismatch.
(It's actually harmless as far as I understand though.)
strictly speaking, this is an api change.
compile tested

netlib: Change the type of url_s:port to uint16_t

---

canutils/libcanutils/error.h
canutils/libcanutils/lib.c

This file is used by the libcanutils and can be isolated in apps
LICENSE
Compile tested

apps: canutils: libcanutils: move error.h from NuttX

---

canutils/libcanutils/Kconfig

Exclude libcanutils from build unless the license is set to
allow GPL code in the build.
NOTE
Depends on
https://github.com/apache/incubator-nuttx/pull/4352
LICENSE
Compiled

canutils: libcanutils: add GPL build barrier

---

nshlib/nsh_fscmds.c

The iobuffer for write buffer position need to be updated if write
API cannot write data at once.
Although we have not encountered any problems.
fix obvious code logic error.
Verified to be able to use the `cp` command as before.

nshlib: Fix write buffer position in nsh cp command

---

boot/.gitignore
boot/Make.defs
boot/Makefile
boot/mcuboot/.gitignore
boot/mcuboot/Kconfig
boot/mcuboot/Make.defs
boot/mcuboot/Makefile
boot/mcuboot/README.md
boot/mcuboot/mcuboot_agent_main.c
boot/mcuboot/mcuboot_confirm_main.c

This PR intends to add support for **MCUboot**, a secure boot solution for 32-bit microcontrollers.
https://www.mcuboot.com/
https://github.com/mcu-tools/mcuboot/
This port enables the following usages for MCUboot on Apache NuttX:
- MCUboot secure boot solution as a Apache NuttX application.
- Apache NuttX application images capable of accessing MCUboot public interfaces for providing support for secure firmware OTA update solutions.
The Apache NuttX port of MCUboot (https://github.com/mcu-tools/mcuboot/pull/1093) consists of the implementation on the following MCUboot interfaces:
- `<flash_map_backend/flash_map_backend.h>`
- `<mcuboot_config/mcuboot_config.h>`
- `<mcuboot_config/mcuboot_logging.h>`
- `<os/os_malloc.h>`
- `<sysflash/sysflash.h>`
The usage of MCUboot as a complete secure …

boot/mcuboot: Add support for MCUboot bootloader

---

boot/mcuboot/Kconfig
boot/mcuboot/Makefile

This PR intends to deactivate some of the warnings emitted by the compiler when building the MCUboot library.
CI build from https://github.com/apache/incubator-nuttx/pull/4324 was complaining due to `-Werror`.
CI build pass.

boot/mcuboot: Deactivate warnings to enable build of MCUboot library

---

include/system/termcurses.h
system/termcurses/tcurses_vt100.c
system/termcurses/termcurses.c

system/termcurses: Add terminate operation into the termcurses_ops_s interface
The existing implementation of the termcurses_deinitterm calls termcurses_setcolors with some hard-coded values, leading to different terminal emulators' behavior. Instead, a reset call needs to be made to the implementation to roll back changes.
A new operation (terminate) has been added to the termcurses_ops interface to achieve this functionality.
The vt100's terminate implementation ensures that default foreground and background colors are applied portably across different terminals emulators.
Please see the attached screen recordings to see how different terminal emulators behave without fix:
The changes have been tested on minicom, picocom, and gtkterm. All worked well with these changes.

system/termcurses: Add terminate operation into the termcurses_ops_s interface

---

examples/ipforward/ipforward.c

This PR is to reproduce the issue explained in https://github.com/apache/incubator-nuttx/pull/4433
examples/ipforward
```
$ git clone https://github.com/apache/incubator-nuttx.git nuttx
$ git clone https://github.com/apache/incubator-nuttx-apps apps
$ cd nuttx
$ ./tools/configure.sh -l sim:ipforward
$ make
$ ./nuttx
NuttShell (NSH) NuttX-10.1.0
nsh> ipfwd
```
The following log shows the correct order of received packets after https://github.com/apache/incubator-nuttx/pull/4433 issue was resolved.
Created TUN device: tun0
Created TUN device: tun1
**Sending packet 1**: size=83
IP Header:
60000000002b06ff7c00000000000000 00000000000000627c00000000000000
0000000000010147                                                 
TCP Header:
**1234**abcd000000000000000050000000 6b110000 …

examples/ipforward: improved ipforward test to analyze the order of forwarded packets

---

.github/workflows/build.yml

This PR is a complement to https://github.com/apache/incubator-nuttx/pull/4462.
CI only.
CI build pass.

github: Update links to Docker Linux image

---

testing/sensortest/sensortest.c

sensortest: modify errno type when api not support
return correct errno when api isn't support.
daily test

sensortest: modify errno type when api not support

---

nshlib/nsh_builtin.c

nsh: fix compile break for closing CONFIG_NSH_DISABLEBG
N/A
compile

nsh: fix compile break about closing CONFIG_NSH_DISABLEBG

---

nshlib/nsh_consolemain.c

nsh: fix compile break for closing CONFIG_NSH_DISABLESCRIPT
N/A
compile

nsh: fix compile break about closing CONFIG_NSH_DISABLESCRIPT

---

examples/wgetjson/wgetjson_main.c

during a concatenation, the last byte was being lost
get a big json

examples/wgetjson: fix json buffer concatenation

---

netutils/rexec/Kconfig
netutils/rexec/Make.defs
netutils/rexec/Makefile
netutils/rexec/rexec.c
netutils/rexecd/Kconfig
netutils/rexecd/Make.defs
netutils/rexecd/Makefile
netutils/rexecd/rexecd.c

Support rexecd and rexec to remote execution. They support AF_INET, AF_INET6 and AF_RPMSG.
Remote command execution is more efficient
* test1: rexec by AF_INET(localhost+port:512)
```
server> rexecd &
rexecd [6:100]
server> rexec -H localhost ls
/:
dev/
proc/
```
* test2: rexec by AF_RPMSG(remoteproc_name+port:512) on rpproxy and rpserver project
```
proxy> rexecd -r &
rexecd [4:100]
proxy> server>
server> rexec -H proxy -r ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK COMMAND
0         0 FIFO     Kthread N-- Ready              00000000 004064 Idle Task
1       224 FIFO     Kthread --- Waiting  Semaphore 00000000 065504 hpwork 0x566a83fc
2       100 FIFO     Task    --- Waiting  Semaphore 00000000 065520 init
3       224 FIFO     Kthread --- Waiting  Semaphore …
```

netutils: support rexecd/rexec

---

examples/camera/Make.defs
examples/camera/Makefile
examples/camera/README.md
examples/camera/camera_bkgd.c
examples/camera/camera_bkgd.h
examples/camera/camera_fileutil.c
examples/camera/camera_main.c

Fix some issues and update license to Apache2.
- Fix  failure to open the video driver.
- Change format from YUV422 to RGB565,
and add captured image output to LCD.
- An application cannot exit by infinite loop.
- In video-only mode without capturing still images,
do not allocate capture memory for still images to
reduce the memory usage.
examples/camera
Tested by spresense:example_camera

examples/camera: Fix some issues and update license

---

canutils/slcan/slcan.c

Fixes an incorrect format identifier in print functions in the SLCAN code. The variable is of type unsigned long, but the identifier corresponds to a standard unsigned type (hexadecimal): %X needs to be changed to %lX to prevent a compiler warning.
This prevents a warning that for example causes this PR to fail the checks: https://github.com/apache/incubator-nuttx/pull/4560
Builds without warnings/errors now.

SLCAN: Fix incorrect format identifier in print function

---

wireless/wapi/src/wireless.c

scan result only process channel 1~14, and no process for 5g channel
wapi scan result can only show 2g channel
local test with brcm 43013 chip which can search 5g channel and result is pass

wapi: add 5g channel map in wapi

---

netutils/chat/chat.c

Replace _info with ninfo to avoid polluting the nsh
Avoid verbose message in the terminal
Building

chat: Replace _info with ninfo to avoid polluting the nsh

---

tools/mksymtab.sh

The file permission is used to get the execlist, but the file permission
cannot be changed for MSYS environment. As the result, symtab_apps.c cannot
be generated correctly. This commit removes the permission match from script.
And, just in case, add to  ignore the error messages by `nm`.
Related: https://github.com/apache/incubator-nuttx-apps/issues/858
loadable applications by using `mksymtab.sh`.

tools/mksymtab.sh: Fix issue to generate symtab_apps.c for MSYS

---

examples/foc/Makefile
examples/foc/foc_main.c
examples/foc/foc_parseargs.c
examples/foc/foc_parseargs.h

examples/foc: use getopt to parse arguments
More FLASH is used, but further development of the app will be easier.
```
[raiden00:~/git/RTOS/nuttx/nuttx]$ arm-none-eabi-size nuttx_f302_old                                                                                                                                                                                                                       
text	   data	    bss	    dec	    hex	filename                    
61596	    684	   3184	  65464	   ffb8	nuttx_f302_old
[raiden00:~/git/RTOS/nuttx/nuttx]$ arm-none-eabi-size nuttx_f302_getopt …
```

examples/foc: use getopt to parse arguments

---

examples/foc/Kconfig
examples/foc/foc_adc.h
examples/foc/foc_fixed16_thr.c
examples/foc/foc_float_thr.c
examples/foc/foc_main.c
examples/foc/foc_mq.c
examples/foc/foc_mq.h

-  examples/foc: replace the requested velocity input with a more general setpoint input.
This is the inital step to support torque/velocity/position control
- examples/foc: temporarily disable error checking for ADC configuration to pass CI
NOTE: this should be reverted after updating nuttx/boards
All example/foc configurations must be updated to use new configuration options

examples/foc: replace the requested velocity input with a more general setpoint input

---

testing/ostest/aio.c
testing/ostest/sporadic2.c

```
aio.c: In function ‘check_done’:
aio.c:158:41: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘ssize_t’ {aka ‘volatile long int’} [-Wformat=]
158 |           printf("  list[%d]. result = %d\n", i, aiocbp->aio_result);
|                                        ~^        ~~~~~~~~~~~~~~~~~~
|                                         |              |
|                                         int            ssize_t {aka volatile long int}
|                                        %ld
aio.c: In function ‘remove_done’:
aio.c:222:41: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘ssize_t’ {aka ‘volatile long int’} [-Wformat=]
222 |           printf("  list[%d]. result = %d\n", i, aiocbp->aio_result);
| …
```

testing/ostest: Fix the compiler warning

---

README.md
crypto/mbedtls/.gitignore
crypto/mbedtls/Kconfig
crypto/mbedtls/Make.defs
crypto/mbedtls/Makefile
include/crypto/mbedtls_config.h

~~**DRAFT**~~
Add initial support for Mbed TLS in NuttX
~~__This is not really ready for review, but I wanted to get this out there to make sure I am not duplicating work__~~
[Ready for review](https://github.com/apache/incubator-nuttx-apps/pull/566#event-5178283381)
TODO:
x509 and hardware driver support is out of scope for this PR
So far it is able to generate data from the entropy api with /dev/urandom configured.

crypto: Initial support for Mbed TLS

---

interpreters/bas/bas_program.c

As a newbie, I thought trying out the BAS interpreter to be a nice first step. But when I issued a 'list' command to see the short BASIC program I wrote, I got an "Error: Break at: end of program" after printing the first line.
This seems to be a side effect of cleaning up the BAS code to conform to the NuttX coding style. In the 'Program_list()' function (bas_program.c:714), this line:
if (watchIntr && FS_intr) return Value_new_ERROR(value,BREAK);
is changed to (removing the 'FS_intr' variable):
if (watchIntr)
{
return Value_new_ERROR(value, BREAK);
}
At runtime, 'watchIntr' evaluates to 1 by the caller ('channel == STDCHANNEL') when using 'list' at the prompt. Hence, the above 'if' always triggers and listing ends with an error after printing the first line.
In the original code, …

Fixes BAS list 'Error: Break at: end of program' error.

---

crypto/mbedtls/Kconfig
include/crypto/mbedtls_config.h

This PR intends to bump **Mbed TLS** version to 3.0.0.
Since Mbed TLS support on NuttX is fresh, it is better to start it from the latest major revision to avoid future hurdles with API incompatibilities.
Changes to `mbedtls_config.h` were based on [this migration guide](https://github.com/ARMmbed/mbedtls/blob/development/docs/3.0-migration-guide.md).
Should have no impact since Mbed TLS support on NuttX has been added recently.
`esp32-devkitc:mcuboot_agent` using Mbed TLS as the crypto backend.
Also tested the builtin Mbed TLS examples `mbedbenchmark` and `mbedselftest`, worked as expected.
```bash
nsh> mbedselftest
CALLOC(0): passed (NULL)
CALLOC(1): passed
CALLOC(1 again): passed (same address)
MD5 test #1: passed
MD5 test #2: passed
MD5 test #3: passed
MD5 test #4: passed
MD5 test #5: …
```

crypto/mbedtls: Bump Mbed TLS to version 3.0.0

---

boot/mcuboot/Kconfig

This PR intends to enable Mbed TLS as the crypto backend on the MCUboot library.
NuttX port of MCUboot already expects the added config:
https://github.com/mcu-tools/mcuboot/blob/main/boot/nuttx/include/mcuboot_config/mcuboot_config.h#L90-L92
New feature, no impact to current MCUboot users which rely on TinyCrypt library.
`esp32-devkitc:mcuboot_agent` and selecting `MCUBOOT_USE_MBED_TLS`.

boot/mcuboot: Add support for using Mbed TLS as crypto backend

---

examples/foc/foc_main.c

examples/foc: terminate main loop if FOC control loop terminated
Correct app termination if the control thread fails
b-g431b-esc1

examples/foc: terminate main loop if FOC control loop terminated

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_b16.h
examples/foc/foc_motor_f32.c
examples/foc/foc_motor_f32.h
industry/foc/fixed16/foc_ang_qenco.c
industry/foc/float/foc_ang_qenco.c

- industry/foc/qenco: add support for encoder index pin
- examples/foc: add Qenco support
b-g431b-esc1

industry/foc/qenco: add support for encoder index pin and Qenco support for FOC example app

---

nshlib/Kconfig

Reduce the default nuttx binary size and unify the DEFAULT_SMALL usage. Paired with https://github.com/apache/incubator-nuttx/pull/4792
The default nsh setting when DEFAULT_SMALL=y
Pass CI

nshlib: Disable Individual commands when DEFAULT_SMALL equals y

---

nshlib/Kconfig
system/readline/Kconfig

- system/readline: Move READLINE_HAVE_EXTMATCH inside SYSTEM_READLINE section
- nsh: Remove the duplicated NSH_MMCSDMINOR
No real change
Pass CI

Correct nsh library Kconfig

---

nshlib/nsh_session.c
nshlib/nsh_stdsession.c

and sync nsh_stdsession.c with nsh_session.c. Fix the issue raise here: https://github.com/apache/incubator-nuttx-apps/pull/873
stdio session
Pass CI.

nshlib/stdsession: Handle the command arguments in any order

---

nshlib/nsh_proccmds.c

nshlib/nsh_proccmds.c: update ps_callback when get Group
Cause of "Group:" always have in file "status"
Current version:
if defined(CONFIG_SCHED_HAVE_PARENT) && defined(CONFIG_SCHED_CHILD_STATUS) are ture,
but "Group" have no value
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
0               0 FIFO     Kthread N-- Ready              00000000 2097104 004160   0.1%  Idle Task
1           100 FIFO     Kthread --- Waiting  Semaphore 00000000 2097120 003024   0.1%  lpwork 0x5988cec0
Root case:
the cmd_ps()  -> ps_callback() in nshlib/nsh_proccmds.c
static const char g_groupid[]   = "Group:";
need key word "Group:"
But the procfs driver always provide:
"PPID:",
in fs/procfs/fs_procfsproc.c
Resolve:
fs/procfs/fs_procfsproc.c set keywords to …

nshlib/nsh_proccmds.c: update ps_callback when get Group

---

testing/sensortest/sensortest.c

```
sensortest.c: In function 'print_gps':
Error: sensortest.c:169:29: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
169 |   printf("%s: timestamp: %llu time_utc: %llu latitude: %f longitude: %f "
|                          ~~~^
|                             |
|                             long long unsigned int
|                          %lu
......
172 |          " %u\n", name, event->timestamp, event->time_utc, event->latitude,
|                         ~~~~~~~~~~~~~~~~
|                              |
|                              uint64_t {aka long unsigned int}
Error: sensortest.c:169:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 4 has …
```

testing/sensortest: Fix printf format warning

---

fsutils/mkfatfs/Kconfig
fsutils/mkfatfs/mkfatfs.c

Enables alignment of the buffers used by the mkfatfs application
to N bytes. 
This may be needed for systems with cache or buffer alignment constraints.
None behind Kconfig
px4_fmuv5

fsutils/mkfatfs: Allow for configurable buffer alignment

---

boot/mcuboot/Kconfig

MCUboot contain important fix in port for nuttx: https://github.com/mcu-tools/mcuboot/pull/1213
MCUboot loader and MCUboot compatible applications
- Pass CI
- MCUboot loader works on custom SAME70 based board

mcuboot/Kconfig: update hash commit to include fix for referenciation error in memset call

---

examples/fb/fb_main.c

When CONFIG_FB_OVERLAY=y, need set overlay=0,
otherwise the lcd driver doesn't know which
layer to get.
None
It has been verified on my own development board.

fix: fb: set overlay to 0

---

boot/mcuboot/Kconfig

MCUboot contain important fix in port for nuttx: https://github.com/mcu-tools/mcuboot/pull/1222
It is needed in order to unblock https://github.com/apache/incubator-nuttx/pull/4880
MCUboot loader and MCUboot compatible applications
- Pass CI
- MCUboot loader works on custom SAME70 based board

mcuboot/Kconfig: update hash commit to include fix for compilation warnings

---

system/trace/trace.c
system/trace/trace_dump.c

Condition variables that are needed only when SYSCALL or IRQ instrumentation is enabled.
trace porgram.
ESP32 with trace enabled.

system/trace:  Suppress warnings.

---

include/system/cle.h
include/system/readline.h
system/cle/cle.c
system/readline/Makefile
system/readline/readline.c
system/readline/readline_fd.c

- system/readline: Make it work without CONFIG_FILE_STREAM 
- system/cle: Make it work without CONFIG_FILE_STREAM
stdio version work as before, fd version will be used in the upcoming nsh optimization patch
Pass CI and ostest

Make readline/cle work without CONFIG_FILE_STREAM

---

examples/foc/Kconfig
examples/foc/Makefile
examples/foc/foc_adc.h
examples/foc/foc_cfg.h
examples/foc/foc_intf.c
examples/foc/foc_intf.h
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_thr.c
examples/foc/foc_thr.h

- examples/foc/foc_cfg.h: fix typo
- examples/foc: move setpoint and vbus configuration from foc_adc.h to foc_cfg.h
- examples/foc: move threads related logic to a separate file
- examples/foc: move adc and button interfaces logic to a separate file
No functional changes
b-g431b-esc1/foc_f32

examples/foc: improve code modularity and fix typo

---

testing/ostest/tls.c

Required by https://github.com/apache/incubator-nuttx/pull/4913
No real change
Pass CI and ostest

testing/ostest: Include nuttx/arch.h explicitly

---

examples/README.md
examples/timer_gpio/Kconfig
examples/timer_gpio/Make.defs
examples/timer_gpio/Makefile
examples/timer_gpio/timer_gpio_main.c
examples/timer_gpout/Kconfig
examples/timer_gpout/timer_gpout_main.c

https://github.com/apache/incubator-nuttx/pull/4774 changes the naming of GPIO devices. Instead of separate gpout, gpin and gpint devices they are all named /dev/gpioN now. The timer_gpout example seems to be the only application that has explicit references to /dev/gpout0, so I have made changes so that it now uses /dev/gpio0 instead.
I have also renamed the application itself from timer_gpout to timer_gpio, which seems more appropriate now that there is no explicit gpout devices anymore.
See https://github.com/apache/incubator-nuttx/pull/4774 - everybody and everything that was using /dev/gpoutN devices now needs to use /dev/gpioN. With this PR this will already be fixed for the timer_gpio application, which seems to be the only app to directly use a /dev/gpout device.
I don't have …

timer_gpout example: use /dev/gpio0 and rename to timer_gpio

---

crypto/mbedtls/Make.defs

This PR intends to provide a fix to an occasional build failure on Mbed TLS.
Mbed TLS was being added twice to `CONFIGURED_APPS` variable, resulting in it being built more than once. If parallel build is enabled, the build could randomly fail due to unmet dependencies.
Fix to Mbed TLS build. After patch is applied, build passes consistently.
`esp32-devkitc` with a custom defconfig.

crypto/mbedtls: Fix occasional failures during Mbed TLS build

---

system/trace/trace_dump.c

trace dump: add string and binary
NOTE_DUMP_STRING
NOTE_DUMP_BINARY
And incubator-nuttx[trace: and sched note dump #4963] is together

trace dump: add string and binary

---

system/sched_note/note_main.c
system/trace/trace_dump.c

trace dump: build error because add CONFIG_SCHED_INSTRUMENTATION_SWITCH in note driver
https://github.com/apache/incubator-nuttx/pull/4998
note dump: add CONFIG_SCHED_INSTRUMENTATION_SWITCH #4998

trace dump: build error because add CONFIG_SCHED_INSTRUMENTATION_SWITCH in note driver

---

wireless/bluetooth/nimble/Kconfig
wireless/bluetooth/nimble/Makefile

wireless/bluetooth/nimble: make stacksize configurable
After this change, nimble works again on nrf52832:
```
NuttShell (NSH) NuttX-10.2.0
nsh> 
nsh> 
nsh> 
nsh> nimble &
nimble [5:255]
port init
hci init
gap init
gatt init
ans init
ias init
lls init
tps init
hci_sock task init
ble_host task init
nsh> hci sock task
host task
advertise
nsh> ps
PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK COMMAND
0     0   0 FIFO     Kthread N-- Ready              00000000 001000 Idle Task
1     1 224 RR       Kthread --- Waiting  Semaphore 00000000 002016 hpwork 0x20000d24
2     2 100 RR       Kthread --- Ready              00000000 002016 lpwork 0x20000d30
3     3 100 RR       Task    --- Running            00000000 002032 init
4     4 100 RR       Kthread --- Waiting  MQ empty …
```

wireless/bluetooth/nimble: make stacksize configurable

---

examples/wget/wget_main.c

wget, as is coded, only displays downloaded files on console.
This patch allow saving files on as per command syntax: 
`wget  [-o <local-path>]  <url>`
mount -t spiffs /dev/esp/partition/spiffs /var
wget -o /var/test4.txt http://192.168.1.43:8000/partitions.csv
v2. corrected checkpatch.sh errors
v3. combined commit

Saving a file downloaded with wget - v3. combined commit

---

system/lzf/lzf_main.c

system/lzf: replace the semaphore to pthread to ensuring compatibility 
Private SEM_INITIALIZER is incompatible with other OS
N/A just replease the semaphore
lzf host compile test

system/lzf: replace the semaphore to pthread to ensuring compatibility 

---

system/lzf/Makefile.host
system/lzf/lzf_main.c

system/lzf: add support for host build
N/A, new host tool
`apps/system/lzf$ make -f Makefile.host TOPDIR=~/nuttx APPDIR=~/apps V=1`

system/lzf: add support for host build

---

fsutils/ipcfg/ipcfg_binary.c

cppcheck reports the following error:
fsutils/ipcfg/ipcfg_binary.c:332:15: error: Uninitialized variable: fd [uninitvar]
DEBUGASSERT(fd >= 0 && ipv6cfg != NULL);
Update the DEBUGASSERT() to match that of ipcfg_read_binary_ipv4(). fd is
uninitilized and doesn't need to be checked here.
Signed-off-by: Eero Nurkkala <eero.nurkkala@offcode.fi>
The debugassert may behave unexpectedly
No impact
Compile-tested only

fsutils/ipcfg: fix debugassert

---

system/hostname/Kconfig
system/hostname/Make.defs
system/hostname/Makefile
system/hostname/hostname_main.c

Add a tool to get/set hostname
Userspace can now get and set the system hostname
Tested by setting hostname, and getting it back. Checked that the hostname was used in dhcp requests.

Add a system tool to get/set hostname

---

examples/mqttc/mqttc_pub.c

commit 36d4bfa7749ecd48ace51eddb613418350c614d7 set a hostname to work around getaddrinfo failing. getaddrinfo returns a non-zero value on error, and there should be an early return after the error message is printed.
mqttc no longer crashes when getaddrinfo fails.
Tested on a bl602 microcontroller.

examples/mqttc: Fix handling of getaddrinfo errors

---

examples/pwm/pwm_main.c

- Increase number of supported PWM channels from 4 to 6 and add an error if the number of channels is greater than 6
- Adjust channel and duty bounds to allow testing sentinel values
- Use macros from `fixedmath.h` for manipulating duty cycle to avoid magic shift logic in code (no change to behavior)
The PWM example app can now be used to test more channels and sentinel values for channel and duty.
Run the example app via nsh using a board with a bl602 chipset

Update PWM example to handle extra channels

---

Application.mk

The import target for kernel build now fails, due to setting libapps.a
as the default value for the BIN variable.
The fail happens when the ELFLD function passes the LDLIBS parameter
(which contains BIN / libapps.a) for the linker. There is no rule to
create libapps.a in the case of the kernel build, so the linker gives
an error due to it being missing.
This commit patches this behavior so that BIN is not appended to
LDLIBS. Another option would be to implement a dummy rule to create
libapps.a, but looking at the git history this is no longer wanted
behavior, thus the error is patched like this.
Should fix the ELFLD function / linkage when using CONFIG_BUILD_KERNEL
Tested that it builds. Created a ROMFS image with the .elf binaries. Did _not_ test that the elf files themselves work / …

Fix link error due to missing libapps.a in KERNEL build

---

nshlib/nsh_codeccmd.c
nshlib/nsh_fscmds.c
nshlib/nsh_netcmds.c

The `too many arguments` and `missing required argument(s)` messages are shown the wrong way around and need to be switched in order for the correct message to be shown to the user.
Messages when commands are run with `too many arguments` or `missing required argument(s)` are now correct.
Tested `md5`, `mkrd`, `mkfatfs` and `wget` (the working one in nshlib, not the terrible one in examples)

Fix incorrect argument count error message

---

system/hostname/hostname_main.c

Follow up to https://github.com/apache/incubator-nuttx-apps/pull/944
Check for too many arguments to hostname
Also use the symbolic value for the success exit code.
Hostname now rejects multiple arguments
[FAIL] (expected) `hostname foo bar`
[OK] `hostname foo`
[OK] `hostname`

Check for too many arguments to hostname

---

nshlib/nsh_parse.c

Fix some edge case bugs in nsh_parse (these cause serious errors):
- Handle nsh_filecat returning NULL on failure
- Background and redirect must be restored after an empty line
- Output redirection should be removed from argv like background
Remove trailing whitespace from commands as parameters (this is cosmetic). Technically the output should be reparsed, so that quoting can take effect, but this fixes the simple case of feeding the output of one command to another.
nsh doesn't crash on edge cases and arguments do not have internal newlines
Test cases for each bug:
```
echo `rm /tmp/tmp1.dat`
``
hostname > /tmp/x
echo -n `echo hello`
```

Fix some edge case bugs in nsh_parse

---

examples/hts221_reader/hts221_reader_main.c

SNIOC_START is not handled by the hts221 driver.
hts221 example
hts221 example.

hts221_reader_main.c: Fix the start IOCTL.

---

system/sched_note/note_main.c

```
ifdef CONFIG_SCHED_INSTRUMENTATION_DUMP
case NOTE_DUMP_STRING:
case NOTE_DUMP_BINARY:
endif
[  198.244349] [25] [ap] 001e3fcc: Task 18 priority 100, string:shced note test count = 907592.
[  198.244468] [25] [ap] 001e3fcc: Task 18 priority 100, string:shced note test
[  198.244561] [25] [ap] 001e3fcc: Task 18 priority 100, binary:module=main event=1 count=2 0x1 0x2
[  198.244679] [25] [ap] 001e3fcc: Task 18 priority 100, binary:module=main event=2 count=1 0x1
[  198.244795] [25] [ap] 001e3fcc: Task 18 priority 100, binary:module=main event=3 count=2 0x2 0x0
[  198.244921] [25] [ap] 001e3fcc: Task 18 priority 100, binary:module=main event=4 count=4 0x3 0x0 0x0 0x0
[  198.245046] [25] [ap] 001e3fcc: Task 18 priority 100, binary:module=main event=5 count=4 0x4 0x0 0x0 0x0
[  198.245180] …
```

note main: system/sched_note add output of string and binary

---

netutils/usrsock_rpmsg/usrsock_rpmsg_server.c
wireless/gs2200m/gs2200m_main.c

net/usrsock: replace xid type to uint64_t to avoid limitation of connections
remove connect index logic and use usrsock_conn instance address 
Depends on:
https://github.com/apache/incubator-nuttx/pull/5154
usrsock rpmsg test

net/usrsock: replace xid type to uint64_t to avoid limitation of connections

---

netutils/netcat/Kconfig
netutils/netcat/netcat_main.c

This option enables using sendfile() in netcat client mode if a normal file (not stdin) is sent.
If the option is enabled but stdin is sent rather than a normal file, netcat falls back to the combination of read() and write().
Using sendfile() provides a higher performance compared to the combination of read() and write().
Also this option is useful for testing / debugging tcp_sendfile() functionality of NuttX TCP/IP stack.
Build NuttX:
```
$ ./tools/configure.sh -l sim:tcpblaster
$ make menuconfig (enable CONFIG_NETUTILS_NETCAT_SENDFILE, enable / disable CONFIG_NET_TCP_WRITE_BUFFERS)
$ make
```
Enable TUN/TAP on Linux host:
```
$ sudo setcap cap_net_admin+ep ./nuttx
$ sudo ./tools/simhostroute.sh wlan0 on
```
Run netcat server on Linux host:
`$ netcat -l -p 31337`
Run …

netutils/netcat: implemented NETUTILS_NETCAT_SENDFILE option.

---

testing/ostest/roundrobin.c

```
ostest: fix assert when enable CONFIG_PRIORITY_INHERITANCE
[ 96.555456] [265] ap: up_assert: Assertion failed at file:semaphore/sem_holder.c line: 112 task: pt-0x5b09fd0b
[ 96.555657] [265] ap: up_assert: Assertion failed at file:semaphore/sem_recover.c line: 86 task: pt-0x5b09fd0b
[ 96.555828] [265] ap: up_assert: Assertion failed at file:semaphore/sem_recover.c line: 86 task: pt-0x5b09fd0b
[ 96.556023] [265] ap: up_assert: Assertion failed at file:semaphore/sem_recover.c line: 86 task: pt-0x5b09fd0b
[ 96.556222] [265] ap: up_assert: Assertion failed at file:semaphore/sem_recover.c line: 86 task: pt-0x5b09fd0b
[ 96.556437] [265] ap: up_assert: Assertion failed at file:semaphore/sem_recover.c line: 86 task: pt-0x5b09fd0b
[ 96.556639] [265] ap: up_assert: Assertion failed at …
```

ostest: fix assert when enable CONFIG_PRIORITY_INHERITANCE

---

testing/ostest/sighand.c

task is blocked by semphore1, signal handler is blocked by semphore2,
after post semphore2, the task must get -EINTR.
Signed-off-by: Zeng Zhaoxiu <zhaoxiu.zeng@gmail.com>

ostest: sighand.c: add sem_wait in signal handler

---

testing/ostest/Kconfig
testing/ostest/fpu.c

testing/ostest: set the default value to TESTING_OSTEST_FPUSIZE 
.config:2053:warning: symbol value '' invalid for TESTING_OSTEST_FPUSIZE
ostest / fpu
CI-check

testing/ostest: set the default value to TESTING_OSTEST_FPUSIZE 

---

industry/foc/fixed16/foc_picontrol.c
industry/foc/float/foc_picontrol.c

it should Limiting amplitude of voltage DQ,not current DQ
when the current is large enough,there will error
Motor drive verification

dq_saturate bug

---

nshlib/nsh_fscmds.c
nshlib/nsh_syscmds.c
system/usbmsc/README.md

I noticed `boardctl` misspelt as `boarctl` in an error message. This fixes the error message and two other files with comments and documentation.

Fix boarctl typos

---

netutils/ftpc/Kconfig
netutils/ftpc/ftpc_putfile.c

This option enables using sendfile() in ftpc binary transfer mode of PUT operation.
If the option is enabled but ASCII transfer mode is activated, ftpc falls back to the combination of read() and write().
Using sendfile() provides a higher performance compared to the combination of read() and write().
Also this option is useful for testing / debugging tcp_sendfile() functionality of NuttX TCP/IP stack.
Based on the current state of sim:tcpblaster config on my Linux host setup, the results are as follows:
1. CONFIG_NET_TCP_WRITE_BUFFERS=n, CONFIG_FTPC_OVER_SENDFILE=n, file size is 500 KB (or larger), the payload throughput is 50 Kbit/s.
2. CONFIG_NET_TCP_WRITE_BUFFERS=n, CONFIG_FTPC_OVER_SENDFILE=y, file size is 50000 KB, the payload throughput is 380.2 Mbit/s.
3. …

netutils/ftpc: implemented FTPC_OVER_SENDFILE option.

---

netutils/netcat/netcat_main.c

Fixed the following types of warnings:
warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]

netutils/netcat: fixed ISO C89/C90 related warnings

---

system/trace/trace_dump.c

since CONFIG_SMP_NCPUS is always defined now.
Follow up NuttX side change: https://github.com/apache/incubator-nuttx/pull/5264
Minor change
Pass CI

system/trace: Define NCPUS without the preprocess guard

---

system/uniqueid/Kconfig
system/uniqueid/Make.defs
system/uniqueid/Makefile
system/uniqueid/uniqueid_main.c

The `uniqueid` tool provides a way to get the board uniqueid from userspace.
This is useful to be able to set the hostname in startup scripts (for example). It includes command line options to:
- select which bytes of the uniqueid you want to print (1 indexed, like the `cut` tool)
- include a prefix (so that `NSH_ARGCAT` is not required)
- print a delimiter between each byte
- format the bytes (hex, HEX, decimal, octal, char)
```
nsh> uniqueid
010203000a0b0c0048656c6c6f000000
nsh> uniqueid -p nuttx- -b 4-6
nuttx-000a0b
nsh> uniqueid -d: -fd
1:2:3:0:10:11:12:0:72:101:108:108:111:0:0:0
nsh> uniqueid -b 9-13 -f c
Hello
nsh> uniqueid -b16-1
0000006f6c6c6548000c0b0a00030201
nsh> uniqueid -b9-16,1-8
48656c6c6f000000010203000a0b0c00
nsh> uniqueid -b9-16,1-9
ERROR: Too many bytes selected
nsh> …
```

system/uniqueid: Add a tool to get the board uniqueid

---

system/adb/adb_banner.c
system/adb/adb_main.c

adb output through syslog instead printf
Pass CI

system/adb: Replace printf with syslog since adb is a service

---

netutils/netcat/Kconfig
netutils/netcat/netcat_main.c

Implemented NETUTILS_NETCAT_BUFSIZE option.
This option can be used for the performance optimization if sendfile() is not applicable.

netutils/netcat: implemented NETUTILS_NETCAT_BUFSIZE option.

---

Makefile

- I noticed that 'make export' does not work with swama5d4-ek:knsh
- This commit fixes this issue by always creating the registry directory
but not copying pdat files for CONFIG_BUILD_KERNEL=y
- This commit also fixes the delimiter issue on Windows
- NOTE: nuttx needs to be updated as well
- See https://github.com/apache/incubator-nuttx/pull/5329
- CONFIG_BUILD_KERNEL=y only
- Build (make and make export) with sama5d-ek:knsh

Makefile: Fix make export for CONFIG_BUILD_KERNEL=y

---

examples/chrono/chrono_main.c

fix typo in log message
None
Pass CI

examples/chrono: fix typo in log message

---

Makefile
import/Make.defs

- I noticed that applications made by 'make import' contain
undefined symbols such as printf for CONFIG_BUILD_KERNEL=y
- This commit fixes this issue by adding user libraries.
- Also, this commit generates libapps.a which is used for init
- CONFIG_BUILD_KERNEL=y only
- Build (mkimport, make import) with sama5d4-ek:knsh

Makefile, import/Make.defs: Fix undefined symbols for CONFIG_BUILD_KERNEL=y

---

mlearning/.gitignore
mlearning/Make.defs
mlearning/Makefile
mlearning/libnnablart/Kconfig
mlearning/libnnablart/Make.defs
mlearning/libnnablart/Makefile

This is a runtime library for inference Neural Network created
by Neural Network Libraries.
Project git: https://github.com/sony/nnabla-c-runtime
It is almost independent from external libraries(depends on C
standard math library) and is written in Pure C (C99).
It has been developed with priority over readability rather than
performance, making it ideal for learning and porting.
It adopts an extensible architecture, and you can use the function
you implemented yourself as necessary for applications that need performance.
Project license : Apache 2.0 License
https://github.com/sony/nnabla-c-runtime/blob/master/LICENSE
ML
spresense

Add support for NNabla C Runtime

---

examples/pca9635/pca9635_main.c

PCA9635 driver does not support neither need nor write operations.
The ioctl is supports PWMIOC_SETLED_BRIGHTNESS that is a write like operation
None
Pass CI

examples/pca9635: change O_RDONLY to O_WRONLY for driver open call

---

import/Make.defs

- I noticed that 'make import' failed due to recent changes in nuttx
- This commit fixes this issue by adding logic for -lm
- CONFIG_BUILD_KERNEL=y only
- Build (mkimport, make import) with sama5d4-ek:knsh

import: Make.defs: Fix 'make import' for CONFIG_BUILD_KERNEL=y

---

tools/mkimport.sh

- mkimport.sh only accepted absolute file path
- This commit adds support relative file path
- None
- Build (mkimport, make import) with sama5d4-ek:knsh

tools: mkimport.sh: Add support relative file path

---

netutils/thttpd/config.h

since this option doesn't exist anymore. See https://github.com/apache/incubator-nuttx/pull/5392
No
Pass CI

neutils/thttpd: Remove CONFIG_SDCLONE_DISABLE

---

examples/mcuboot/.gitignore
examples/mcuboot/Make.defs
examples/mcuboot/Makefile
examples/mcuboot/swap_test/Kconfig
examples/mcuboot/swap_test/Make.defs
examples/mcuboot/swap_test/Makefile
examples/mcuboot/swap_test/README.md
examples/mcuboot/swap_test/confirm_main.c
examples/mcuboot/swap_test/set_img_main.c
examples/mcuboot/swap_test/version_main.c

This example demonstrate swap between two valid images. Instructions are available at readme.md file inside project directory.
None
samv7-xult

examples: Add mcuboot Swap Test example

---

Application.mk

An alternative is to have symbols like __udivdi3 in
the symbol table explicitly when loading the module.
But I feel it's too cumbersome to maintain.

Application.mk: Link the compiler runtime for ELF modules

---

system/adb/logcat_service.c

Minor fix.
Avoid skip the invocation of uv_fileno in case of NDEBUG.
Pass CI

system/adb: Fix error: 'fd' may be used uninitialized in this function

---

netutils/netinit/netinit.c

CONFIG_NET_LOCAL is used to enable Unix Domain Socket
Minor
Local test

netutils: Check lo by CONFIG_NET_LOOPBACK not CONFIG_NET_LOCAL

---

netutils/netcat/netcat_main.c

Sometimes netcat in server mode crashed with "psock_accept: ERROR: si_accept failed: -9".
And sometimes it crashed with "up_assert: Assertion failed at file:inet/inet_sockif.c line: 841 task: netcat".
```
NuttShell (NSH) NuttX-10.2.0
nsh> ifconfig eth0 10.0.1.2
nsh> ifup eth0
ifup eth0...OK
nsh> netcat -l 31337
log: net: listening on :31337
[42949702.410000] up_assert: Assertion failed at file:inet/inet_sockif.c line: 841 task: netcat
```
```
NuttShell (NSH) NuttX-10.2.0
nsh> ifconfig eth0 10.0.1.2
nsh> ifup eth0
ifup eth0...OK
nsh> netcat -l 31337
log: net: listening on :31337
[42949669.600000] psock_accept: ERROR: si_accept failed: -9
accept failed: Error 9
```

netutils/netcat: fixed crash on accept() invocation.

---

netutils/ftpd/ftpd.c

ftpd: Remove usage of deprecated macro __NUTTX__

---

mlearning/libnnablart/Make.defs

During contribution the folders have moved and the path
should be updated
NNABLA 
compiled

mlearning: nnabla: fix include path

---

examples/foc/Kconfig
examples/foc/foc_cfg.h
examples/foc/foc_main.c
examples/foc/foc_motor_b16.c
examples/foc/foc_motor_f32.c
examples/foc/foc_parseargs.c
examples/foc/foc_parseargs.h
examples/foc/foc_thr.h

examples/foc: make the FOC current controller configurable
For now only the FOC PI current controller is supported, but this can be easily extended to support other control methods
Modularity improved
CI

examples/foc: make the FOC current controller configurable

---

system/adb/Kconfig

improve the speed of "adb push" and "adb pull", follow the upstream change:
https://github.com/spiriou/microADB/pull/22
Kconfig default vaule
Pass CI and local test

system/adb: Change the default value of ADBD_PAYLOAD_SIZE to 1024

---

tools/mksymtab.sh

Found by PR https://github.com/apache/incubator-nuttx/pull/5476
compiler warning
Pass CI

tools/mksymtab.sh: Disable the mismatch warning of builtin declaration

---

mlearning/cmsis/Makefile
mlearning/cmsis/cmsis-nn-support_nnabla.patch

- support float version of convolution
- support the CHW tensor layout
following function prototypes are added:
- arm_convolve_CHW_f32_basic_nonsquare()
- arm_convolve_CHW_q15_basic_nonsquare()
- arm_convolve_CHW_q7_basic_nonsquare()
- arm_nn_CHW_mat_mult_kernel_q7_q15()
NOTE:this patch will be contributed to SMSIS and reverted later from NuttX
CMSIS 5
tested on Spresense

mlearning: CMSIS NN: add support for the CHW tensor layout

---

Application.mk
Make.defs

Extend Application.mk and Make.defs to compile Rust based applications.
nothing as it's new
Simulation on MacBook Air M1 with Monterey 12.2.1 using rustc rustc 1.58.1 (stable) via Homebrew.

apps: Enable Rust based application.

---

include/industry/foc/float/foc_angle.h
include/industry/foc/float/foc_handler.h
industry/foc/Kconfig
industry/foc/Makefile
industry/foc/float/foc_ang_onfo.c
industry/foc/float/foc_ang_osmo.c
industry/foc/float/foc_picontrol.c

Add support park transform angle from sensorless observer, support both nolinear fluxlink observer and sliding mode observer
The former foc control lib in industry just support open-loop,encoder and hall, now we can use sensorless observer mode
Tested on FOC controller based on stm32f405

industry/foc: add support for angle from sensorless observer

---

industry/foc/Kconfig
industry/foc/float/foc_ang_onfo.c
industry/foc/float/foc_ang_osmo.c
industry/foc/float/foc_ang_qenco.c
industry/foc/float/foc_vel_odiv.c
industry/foc/float/foc_vel_opll.c

- industry/foc: rename dir to sensor_dir to be clear that it relates to the direction of the sensor, no movement direction
- industry/foc: fix compilation for smo
- industry/foc: update comments
- industry/foc: remove choice option for angle observers
- industry/foc: refactor and fixes for angle observers
sim/foc

industry/foc: various fixes

---

include/industry/foc/fixed16/foc_angle.h
include/industry/foc/fixed16/foc_handler.h
include/industry/foc/fixed16/foc_velocity.h
industry/foc/Makefile
industry/foc/fixed16/foc_ang_onfo.c
industry/foc/fixed16/foc_ang_osmo.c
industry/foc/fixed16/foc_picontrol.c
industry/foc/fixed16/foc_vel_odiv.c
industry/foc/fixed16/foc_vel_opll.c
industry/foc/float/foc_ang_onfo.c
industry/foc/float/foc_ang_osmo.c

foclib/fixed16: add support for observers - port from foclib/float
depends on https://github.com/apache/incubator-nuttx/pull/5563
sim/foc
not tested on HW yet

foclib/fixed16: add support for observers

---

interpreters/duktape/Makefile

to avoid the verbose unzip message
Minor
Pass CI

interpreters/duktape: Remove v from tar command

---

import/Make.defs

Otherwise build without HAVE_CXX flag fails
Don't add CPP library if it is not configured
CONFIG_BUILD_KERNEL only
Build succeeds without HAVE_CXX flag

BUILD_KERNEL: Include CPP libraries only if configured to do so

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_fsutils.c
nshlib/nsh_mmcmds.c
nshlib/nsh_proccmds.c

nshlib: add memory dump cmd[ps && memdump]. This patch is related to https://github.com/apache/incubator-nuttx/pull/5585.
add memory dump function
daily test

nshlib: add memory dump cmd[ps && memdump]

---

nshlib/nsh_ddcmd.c

if a file size is 10
use dd if=a of=b bs = 8
b file size will 16, is a error
use cmd dd app

cmd_dd:if read nbyte less than bs,must write nbyte

---

mlearning/cmsis/libcmsisdsp/Makefile
mlearning/cmsis/libcmsisnn/Makefile

In case of HW with FPU we can benefit from the FPU support.
CMSIS
Spresense

mlearning: cmsis: enable FPU support

---

system/libuv/0001-libuv-port-for-nuttx.patch
system/libuv/Makefile

libuv: Remove unsupported case from test list
And some minor changes:
* Remove no-proctitle.c from CSRCS since there is a implementation in nuttx.c
* Add sysinfo-[loadavg|memory].c to CSRCS to provide system info
libuv test suite
SIM and CI

libuv: Remove unsupported case from test list

---

netutils/webserver/httpd.c

Report at https://github.com/apache/incubator-nuttx/runs/5396269209?check_suite_focus=true:
```
Error: httpd.c:671:7: error: 'strncpy' output truncated before terminating nul copying 12 bytes from a string of the same length [-Werror=stringop-truncation]
671 |       strncpy(pstate->ht_filename, "/" CONFIG_NETUTILS_HTTPD_INDEX,
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
672 |               strlen("/" CONFIG_NETUTILS_HTTPD_INDEX));
|               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Simple fix
Pass CI

netutils/webserver: Fix the compiler error when -no-builtin is removed

---

nshlib/nsh_routecmds.c

Report here: https://github.com/apache/incubator-nuttx/runs/5431760938?check_suite_focus=true
Fix the warning
Pass CI

Fix error: 'memset' forming offset [16, 27] is out of the bounds [0, 16] of object 'inaddr' with type 'union <anonymous>'

---

system/readline/readline_common.c

Report here: https://github.com/apache/incubator-nuttx/runs/5431571859?check_suite_focus=true
Fix warning
Pass CI

Fix readline_common.c:277:19: error: 'strncpy' destination unchanged after copying no bytes

---

examples/chrono/chrono_main.c
nshlib/nsh_routecmds.c

```
chrono_main.c: In function 'chrono_main':
Error: chrono_main.c:396:11: error: 'strncpy' output truncated before terminating nul copying 7 bytes from a string of the same length [-Werror=stringop-truncation]
396 |           strncpy(str, "00:00.0", 7);
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~
Error: chrono_main.c:434:25: error: '%02ld' directive writing between 2 and 9 bytes into a region of size 8 [-Werror=format-overflow=]
434 |           sprintf(str, "%02ld:%02ld:%01ld", min, sec,
|                         ^~~~~
chrono_main.c:434:24: note: directive argument in the range [-35791394, 35791394]
434 |           sprintf(str, "%02ld:%02ld:%01ld", min, sec,
|                        ^~~~~~~~~~~~~~~~~~~
chrono_main.c:434:24: note: directive argument in the range [-59, 59]
chrono_main.c:434:24: …
```

Fix compiler warning

---

examples/serialrx/serialrx_main.c

The option CONFIG_EXAMPLES_SERIALRX_PRINTSTR was available in the configuration but was not implemented in the source code. This commit implements the option.
Application only.
Basic tests (receiving data over UART and printing them)

examples/serialrx: implement option to print string characters

---

include/netutils/webclient.h
netutils/webclient/webclient.c

Add minimum HTTP 1.1 support.
My motivation is to be able to communicate with a server which rejects HTTP 1.0.
A version ported to linux and macOS has been tested against:
* http://httpbin.org/stream/10
* Docker API

webclient: minimum HTTP 1.1 support

---

netutils/webclient/webclient.c

webclient: Remove an inappropriate comment (a copy-and-paste botch)
compile and nxstyle

webclient: Remove an inappropriate comment (a copy-and-paste botch)

---

netutils/webclient/webclient.c

When making the following change, I haven't noticed that
g_httpuseragentfields contains a "Connection" header.
```
commit 092ce8144445a9b287554e59e3150bab3d67bedb
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Mon Mar 7 09:30:23 2022 +0900
webclient: Always use "connection: close" for HTTP 1.1 for now
* This matches the HTTP 1.0 behavior.
* Persistent connection doesn't make much sense with the current API.
```
It seems that some servers are not happy with the duplicated header
and ignore them. (and do the default keep-alive for HTTP 1.1)
eg. Azure Blob (global)
tested against Azure Blob.

webclient: Remove a duplicated "Connection:" header

---

nshlib/nsh_command.c
nshlib/nsh_fscmds.c

use "mkdir -p /test/test" to ceate a dir
Create the A/B folder, if the A folder does not exist, create the A folder first, and then create the B folder under the A folder

cmd_mkdir:support mkdir opthon -p

---

nshlib/nsh_fscmds.c

nshlib/nsh_fscmds:use strchr instead of strstr

---

examples/timer/timer_main.c
examples/timer_gpio/timer_gpio_main.c

After https://github.com/apache/incubator-nuttx/pull/5747 the apps examples should be updated to fix `struct timer_notify_s` assignment.
Timer driver based examples
Tested with same70-qmtech board

examples/timer: fix timer notification asignment

---

include/netutils/icmp_ping.h
include/netutils/icmpv6_ping.h
netutils/ping/icmp_ping.c
netutils/ping/icmpv6_ping.c
system/ping/ping.c
system/ping6/ping6.c

1、Round trip times in the ping command range from millisecond to subtle
2、Add statistics on RTT related min/avg/Max/mdev in ping program
3、The ping command supports ctrl+c interruption operations
The ping and ping6 commands are affected
PASSED

Modifying the ping command

---

system/cfgdata/cfgdata_main.c

Fix compilation when MTD_CONFIG_NAMED is enabled
Bugfix
Pass CI

system/cfgdata: fix compilation when MTD_CONFIG_NAMED is enabled

---

.gitignore
examples/README.md
examples/lua_module/Kconfig
examples/lua_module/Make.defs
examples/lua_module/Makefile
examples/lua_module/luamod_hello.c
interpreters/README.md
interpreters/lua/.gitignore
interpreters/lua/Kconfig
interpreters/lua/Make.defs
interpreters/lua/Makefile
interpreters/lua/Module.mk
interpreters/lua/nuttx_linit.c
interpreters/lua/registry/.gitignore

Lua is a popular scripting language that is tailored towards embedding in applications and embedded devices. This PR builds Lua as an NSH app. The `apps/interpreters/lua/Makefile` does a few notable things:
- fetches and unpacks a source tarball from the Lua website
- sets defines to use the `readline` library for the Lua REPL
- adopts logic from `apps/builtin/Makefile` to generate headers for including builtin Lua modules
To expand on the last point: Nuttx apps can include `apps/interpreters/lua/LuaModule.mk` to register a C module with the Lua interpreter. This makefile uses the `register` target to write entries to the `apps/interpreters/lua/registry` directory. See `apps/examples/luamod_hello` for an example of how to register a builtin Lua C module. The Lua source file `linit.c` is …

add Lua interpreter

---

system/nxlooper/nxlooper.c
system/nxlooper/nxlooper_main.c
system/nxplayer/nxplayer.c
system/nxplayer/nxplayer_main.c
system/nxrecorder/nxrecorder.c
system/nxrecorder/nxrecorder_main.c
wireless/wapi/src/driver_wext.c
wireless/wapi/src/network.c
wireless/wapi/src/wireless.c

Found by change https://github.com/apache/incubator-nuttx/pull/5476:
- wireless/wapi: Fix warning: 'strncpy' specified bound 16 equals destination size
- system: Fix nx[looper|player|recorder] warning
Minor
Pass CI

Fix warning after removing -fno-builtin

---

interpreters/lua/Makefile

The `apps/interpreters/lua/Makefile` used an `awk` command that was only compatible with GNU `awk`. The build failed on platforms with BSD `awk`, like MacOS.
Replace the `awk` command with a POSIX shell script, using the `expr` command for regex group capture.
Only affects the Lua interpreter used by defconfigs with `CONFIG_INTERPRETERS_LUA` enabled.
The same output is produced by the previous and new make step.

interpreters: lua: replace awk command with shell script

---

fsutils/passwd/passwd_deluser.c
fsutils/passwd/passwd_update.c

`passwd` compilation fails with
```
./passwd_update.c:28:10: fatal error: passwd.h: No such file or directory
28 | #include <passwd.h>
```
None. Fix build issue
Pass CI

fsutils/passwd: fix compilation

---

testing/cxxtest/cxxtest_main.cxx

This PR intends to fix the build of the `cxxtest` testing application.
It is currently failing on `-fno-rtti` builds due to using `std::dynamic_cast`, which requires RTTI support.
Should have no impact, RTTI is only enabled on `sim` defconfigs.
CI pass.

testing: Fix cxxtest application for "no-rtti" builds

---

fsutils/passwd/passwd_encrypt.c
nshlib/nsh_passwdcmds.c

Fix out of bounds array access during password encryption
Boards with `FSUTILS_PASSWD` enabled that have passwords with length not multiple of `8` stored in `FSUTILS_PASSWD_PATH` file.
After applying this change my `/ect/passwd` became unusable and I had to recreate it again.
Tested with custom SAME70 based board.

fsutils/passwd: fix out of bounds array access during password encryption

---

system/cfgdata/cfgdata_main.c

Add missing include file
Fix the build
Pass build locally with `cfgdata` enabled

system/cfgdata: add missing include file

---

netutils/rexec/rexec.c

rexec: correct af type from int to sa_family_t
rexec
VELA

rexec: correct af type from int to sa_family_t

---

testing/mm/mm_main.c

Repair the memory leak question when realloc failed.
realloc return NULL if failed, so we have to use a local variable to store the return value to avoid the missing of old memory pointer.
mm test pass, no memory leak.

testing/mm: repair the memory leak question when realloc failed.

---

nshlib/Kconfig
nshlib/nsh.h
nshlib/nsh_command.c
nshlib/nsh_syscmds.c

add resetcause nsh command, this will call boardctl to read last reset cause
N/A
Vela tested

apps/nsh:add resetcause command

---

nshlib/nsh_command.c

nsh/memdump: support dynamic turn on/off backtrace in heap.
Add: memdump on and memdump off
Ci

nsh/memdump: support dynamic turn on/off backtrace in heap

---

examples/pca9635/pca9635_main.c
system/cfgdata/cfgdata_main.c

Pass file options 0 if only ioctl is used. if write or read handler is not available then `-EACCES` is returned by `inode_checkflags`
Fix cfgdata and pca9635 example operation.
Tested with custom board based on SAME70

open() options: pass file options 0 if only ioctl is used

---

testing/mm/Makefile
testing/mm/mm_main.c

Add the heap boundary realloc test.
When CONFIG_MM_SMALL enable and CONFIG_DEBUG_MM disable, **SIZEOF_MM_ALLOCNODE = 4, MM_MIN_CHUNK = 16, SIZEOF_MM_FRENODE = 12**.
In above figure, **HEAP_SIZE** is not aligned with **MM_MIN_CHUNK** (because **(2 * SIZEOF_MM_ALLOCNODE) != MM_MIN_CHUNK)**), nodeA is a malloced memory node, nodeB is a free memory node and adjacent to heap end node. In this situation, realloc the nodeA may lead the remain size be **(MM_MIN_CHUNK - 2 * SIZEOF_MM_ALLOCNODE) = 8**, which is not large enough to hold a free node, so software will assert fail at mm_heap/mm_realloc.c line: 319.
Related PR: https://github.com/apache/incubator-nuttx/pull/5906
@masayuki2009
Test with nucleo-144 stm32f746zg

testing/mm: add heap boundary realloc test.
